/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/

import GameTheory.Mechanism.FairDivision.Divisible.Basic
import Math.Fin
import Math.FixedPoint.KKM
import Math.MeasureTheory.UnitInterval
import Mathlib.Analysis.Convex.StdSimplex
import Mathlib.MeasureTheory.Constructions.UnitInterval
import Mathlib.MeasureTheory.Measure.Lebesgue.Basic
import Mathlib.Tactic

/-!
# Stromquist's Envy-Free Division

The interval-cut geometry, KKM step, shifted-grid approximation, and compactness
argument used in Stromquist's envy-free division proof for finite nonatomic
measure instances.
-/

open MeasureTheory Set Topology
open scoped unitInterval

namespace GameTheory
namespace SocialChoice
namespace FairDivision
namespace Divisible

variable (n : ℕ) (μ : Fin n → Measure ℝ)
variable [∀ i, IsFiniteMeasure (μ i)] [∀ i, NullSingletonClass (μ i)]

/-- The `i`-th interval piece generated by simplex coordinates `x`.  The piece
runs from the cumulative mass before `i` to the cumulative mass through `i`. -/
noncomputable def stromquistPiece (x : Fin n → ℝ) (i : Fin n) : Set ℝ :=
  Set.Ico (∑ j ∈ Finset.univ.filter (· < i), x j)
    (∑ j ∈ Finset.univ.filter (· ≤ i), x j)

/-- The pieces generated by a simplex point form a measurable partition of
`Ico 0 1`. -/
theorem stromquistPiece_partition (x : Fin n → ℝ) (hx : x ∈ stdSimplex ℝ (Fin n)) :
    (∀ i, MeasurableSet (stromquistPiece n x i)) ∧
    (∀ i j : Fin n, i ≠ j → Disjoint (stromquistPiece n x i) (stromquistPiece n x j)) ∧
    (⋃ i, stromquistPiece n x i = Set.Ico 0 1) := by
  have hnn : ∀ i, 0 ≤ x i := hx.1
  have hsum : ∑ i, x i = 1 := hx.2
  have hn' : 0 < n := by
    rcases Nat.eq_zero_or_pos n with rfl | h
    · simp at hsum
    · exact h
  let L : Fin n → ℝ := fun i => ∑ j ∈ Finset.univ.filter (· < i), x j
  let U : Fin n → ℝ := fun i => ∑ j ∈ Finset.univ.filter (· ≤ i), x j
  have hdef : ∀ i, stromquistPiece n x i = Set.Ico (L i) (U i) := fun _ => rfl
  have hUlast : U ⟨n - 1, by omega⟩ = 1 := by
    simp only [U]
    have heq : Finset.univ.filter (· ≤ (⟨n - 1, by omega⟩ : Fin n)) = Finset.univ := by
      apply Finset.filter_true_of_mem
      intro j _
      rw [Fin.le_iff_val_le_val]
      change j.val ≤ n - 1
      have := j.isLt
      omega
    rw [heq]
    exact hsum
  have hU_le_L : ∀ i j : Fin n, i < j → U i ≤ L j := fun i j hij =>
    Finset.sum_le_sum_of_subset_of_nonneg
      (fun k => by
        simp only [Finset.mem_filter, Finset.mem_univ, true_and]
        exact fun hk => hk.trans_lt hij)
      (fun k _ _ => hnn k)
  have hL_nonneg : ∀ i, 0 ≤ L i := fun i => Finset.sum_nonneg fun j _ => hnn j
  have hU_le_one : ∀ i, U i ≤ 1 := fun i => by
    calc
      U i ≤ ∑ j : Fin n, x j :=
        Finset.sum_le_sum_of_subset_of_nonneg (by simp) (fun k _ _ => hnn k)
      _ = 1 := hsum
  refine ⟨fun i => hdef i ▸ measurableSet_Ico, ?_, ?_⟩
  · intro i j hij
    rw [hdef i, hdef j, Set.Ico_disjoint_Ico]
    rcases lt_or_gt_of_ne hij with h | h
    · exact (min_le_left _ _).trans ((hU_le_L i j h).trans (le_max_right _ _))
    · exact (min_le_right _ _).trans ((hU_le_L j i h).trans (le_max_left _ _))
  · simp_rw [hdef]
    ext t
    simp only [Set.mem_iUnion, Set.mem_Ico]
    constructor
    · rintro ⟨i, hlo, hhi⟩
      exact ⟨(hL_nonneg i).trans hlo, hhi.trans_le (hU_le_one i)⟩
    · intro ⟨ht0, ht1⟩
      have hS_ne : (Finset.univ.filter (fun i : Fin n => t < U i)).Nonempty :=
        ⟨⟨n - 1, by omega⟩, Finset.mem_filter.mpr ⟨Finset.mem_univ _, hUlast ▸ ht1⟩⟩
      set i₀ := (Finset.univ.filter (fun i : Fin n => t < U i)).min' hS_ne
      refine ⟨i₀, ?_, (Finset.mem_filter.mp (Finset.min'_mem _ hS_ne)).2⟩
      rcases Nat.eq_zero_or_pos i₀.val with h0 | hpos
      · have hempty : Finset.univ.filter (fun j : Fin n => j < i₀) = ∅ := by
          rw [Finset.filter_eq_empty_iff]
          intro j _
          simp only [not_lt, Fin.le_iff_val_le_val, h0]
          exact Nat.zero_le _
        simp [L, hempty, ht0]
      · have hpred_lt : i₀.val - 1 < n := by omega
        set pred : Fin n := ⟨i₀.val - 1, hpred_lt⟩
        have hconsec : U pred = L i₀ := by
          simp only [U, L, pred]
          congr 1
          ext j
          simp only [Finset.mem_filter, Finset.mem_univ, true_and,
            Fin.le_iff_val_le_val, Fin.lt_def]
          omega
        have hpred_not_mem : pred ∉ Finset.univ.filter (fun i : Fin n => t < U i) := by
          intro hmem
          have hpred_lt' : pred < i₀ := Fin.lt_def.mpr (by simp [pred]; omega)
          exact absurd (Finset.min'_le _ _ hmem) (not_le.mpr hpred_lt')
        simp only [Finset.mem_filter, Finset.mem_univ, true_and, not_lt] at hpred_not_mem
        linarith [hconsec]

/-- Piece `i` is empty exactly when coordinate `i` is zero. -/
theorem stromquistPiece_empty_iff (x : Fin n → ℝ) (hx : x ∈ stdSimplex ℝ (Fin n))
    (i : Fin n) :
    stromquistPiece n x i = ∅ ↔ x i = 0 := by
  simp only [stromquistPiece, Set.Ico_eq_empty_iff, not_lt]
  have key : ∑ j ∈ Finset.univ.filter (· ≤ i), x j =
      ∑ j ∈ Finset.univ.filter (· < i), x j + x i := by
    have hsplit : Finset.univ.filter (fun j : Fin n => j ≤ i) =
        (Finset.univ.filter (fun j : Fin n => j < i)) ∪ {i} := by
      ext j
      simp only [Finset.mem_filter, Finset.mem_univ, true_and, Finset.mem_union,
        Finset.mem_singleton]
      exact le_iff_lt_or_eq
    have hdisj : Disjoint (Finset.univ.filter (fun j : Fin n => j < i)) {i} := by
      simp only [Finset.disjoint_singleton_right, Finset.mem_filter, Finset.mem_univ,
        true_and]
      exact lt_irrefl i
    rw [hsplit, Finset.sum_union hdisj, Finset.sum_singleton]
  constructor
  · intro h
    linarith [hx.1 i]
  · intro h
    rw [key]
    linarith

/-- Agent `j`'s real-valued measure of piece `i` at division `x`. -/
noncomputable def stromquistValue (x : Fin n → ℝ) (j i : Fin n) : ℝ :=
  (μ j (stromquistPiece n x i)).toReal

/-- For fixed agent and piece, `stromquistValue` is continuous in the cut
coordinates. -/
theorem stromquistValue_continuous (j i : Fin n) :
    Continuous (fun x : Fin n → ℝ => stromquistValue n μ x j i) := by
  have hcdf : Continuous (fun t : ℝ => (μ j (Set.Iic t)).toReal) :=
    Math.MeasureTheory.cdfRealContinuous (μ j)
  have hl_cont : Continuous (fun x : Fin n → ℝ =>
      ∑ k ∈ Finset.univ.filter (· < i), x k) :=
    continuous_finsetSum _ fun k _ => continuous_apply k
  have hr_cont : Continuous (fun x : Fin n → ℝ =>
      ∑ k ∈ Finset.univ.filter (· ≤ i), x k) :=
    continuous_finsetSum _ fun k _ => continuous_apply k
  have hval_eq : ∀ x : Fin n → ℝ, stromquistValue n μ x j i =
      max ((μ j (Set.Iic (∑ k ∈ Finset.univ.filter (· ≤ i), x k))).toReal -
           (μ j (Set.Iic (∑ k ∈ Finset.univ.filter (· < i), x k))).toReal) 0 := fun x => by
    simp only [stromquistValue, stromquistPiece]
    exact Math.MeasureTheory.measure_Ico_toReal (μ j) _ _
  simp_rw [hval_eq]
  exact (hcdf.comp hr_cont |>.sub (hcdf.comp hl_cont)).max continuous_const

/-- Points where piece `i` is a weak maximizer for agent `j`. -/
def stromquistWeakPreferenceSet (i j : Fin n) : Set (Fin n → ℝ) :=
  {x : Fin n → ℝ | ∀ k : Fin n, stromquistValue n μ x j k ≤ stromquistValue n μ x j i}

/-- Weak preference sets are closed. -/
theorem stromquistWeakPreferenceSet_closed (i j : Fin n) :
    IsClosed (stromquistWeakPreferenceSet n μ i j) := by
  simp only [stromquistWeakPreferenceSet, Set.setOf_forall]
  exact isClosed_iInter fun k =>
    isClosed_le (stromquistValue_continuous n μ j k) (stromquistValue_continuous n μ j i)

omit [∀ i, IsFiniteMeasure (μ i)] [∀ i, NullSingletonClass (μ i)] in
/-- For each agent, weak preference sets over pieces cover the simplex. -/
theorem stromquistWeakPreferenceSet_covers (j : Fin n) :
    stdSimplex ℝ (Fin n) ⊆ ⋃ i, stromquistWeakPreferenceSet n μ i j := by
  intro x _
  have hne : (Finset.univ : Finset (Fin n)).Nonempty := ⟨j, Finset.mem_univ j⟩
  obtain ⟨i, _, hi⟩ :=
    Finset.exists_max_image Finset.univ (fun i => stromquistValue n μ x j i) hne
  exact Set.mem_iUnion.mpr ⟨i, fun k => hi k (Finset.mem_univ k)⟩

omit [∀ i, NullSingletonClass (μ i)] in
/-- If agent `j` has positive value for `[0,1)`, the weak preference set for
piece `i` misses the face where piece `i` has zero length. -/
theorem stromquistWeakPreferenceSet_avoids_face (i j : Fin n)
    (hpos : 0 < μ j (Set.Ico 0 1)) :
    stromquistWeakPreferenceSet n μ i j ∩ Math.FixedPoint.simplexFaceOpp i = ∅ := by
  rw [Set.eq_empty_iff_forall_notMem]
  intro x ⟨hA, hface⟩
  simp only [Math.FixedPoint.simplexFaceOpp, Set.mem_inter_iff, Set.mem_setOf_eq] at hface
  obtain ⟨hxi, hx_simp⟩ := hface
  have hpi : stromquistPiece n x i = ∅ :=
    (stromquistPiece_empty_iff n x hx_simp i).mpr hxi
  have hvi : stromquistValue n μ x j i = 0 := by
    simp [stromquistValue, hpi]
  have hv_zero : ∀ k, μ j (stromquistPiece n x k) = 0 := by
    intro k
    have hle : stromquistValue n μ x j k ≤ 0 := hvi ▸ hA k
    have hnn : 0 ≤ stromquistValue n μ x j k := ENNReal.toReal_nonneg
    have heq : stromquistValue n μ x j k = 0 := le_antisymm hle hnn
    simp only [stromquistValue, ENNReal.toReal_eq_zero_iff] at heq
    exact heq.resolve_right (measure_ne_top _ _)
  obtain ⟨hmeas, hdisj, hcover⟩ := stromquistPiece_partition n x hx_simp
  have hmeasure_zero : μ j (Set.Ico 0 1) = 0 := by
    rw [← hcover, measure_iUnion (fun ⦃a b⦄ hab => hdisj a b hab) hmeas, tsum_fintype]
    exact Finset.sum_eq_zero fun k _ => hv_zero k
  exact absurd hmeasure_zero (ne_of_gt hpos)

/-- Points where piece `i` is the unique maximizer for agent `j`. -/
def stromquistUniquePreferenceSet (i j : Fin n) : Set (Fin n → ℝ) :=
  stromquistWeakPreferenceSet n μ i j \
    ⋃ k ∈ Finset.univ.filter (· ≠ i), stromquistWeakPreferenceSet n μ k j

/-- Unique preference sets are open. -/
theorem stromquistUniquePreferenceSet_open (i j : Fin n) :
    IsOpen (stromquistUniquePreferenceSet n μ i j) := by
  have hkey : stromquistUniquePreferenceSet n μ i j =
      ⋂ k ∈ Finset.univ.filter (· ≠ i),
        {x : Fin n → ℝ | stromquistValue n μ x j k < stromquistValue n μ x j i} := by
    ext x
    simp only [stromquistUniquePreferenceSet, stromquistWeakPreferenceSet, Set.mem_sdiff,
      Set.mem_setOf_eq, Set.mem_iUnion, Finset.mem_filter, Finset.mem_univ, true_and,
      Set.mem_iInter, not_exists]
    constructor
    · intro ⟨hmax, hno⟩ k hki
      exact lt_of_le_of_ne (hmax k) (fun h => hno k hki (fun m => h ▸ hmax m))
    · intro hlt
      refine ⟨fun k => ?_, fun k hki hAk => absurd (hAk i) (not_le.mpr (hlt k hki))⟩
      rcases eq_or_ne k i with rfl | hki
      · exact le_refl _
      · exact le_of_lt (hlt k hki)
  rw [hkey]
  apply isOpen_biInter_finset
  intro k _
  exact isOpen_lt (stromquistValue_continuous n μ j k) (stromquistValue_continuous n μ j i)

omit [∀ i, IsFiniteMeasure (μ i)] [∀ i, NullSingletonClass (μ i)] in
/-- For a fixed agent, two distinct pieces cannot both be uniquely best. -/
theorem disjoint_stromquistUniquePreferenceSet (j i i' : Fin n) (hii' : i ≠ i') :
    Disjoint (stromquistUniquePreferenceSet n μ i j) (stromquistUniquePreferenceSet n μ i' j) := by
  simp only [Set.disjoint_left, stromquistUniquePreferenceSet]
  intro x ⟨_, hnotA⟩ ⟨hAi', _⟩
  apply hnotA
  rw [Set.mem_iUnion₂]
  exact ⟨i', Finset.mem_filter.mpr ⟨Finset.mem_univ _, hii'.symm⟩, hAi'⟩

/-- Divisions where some agent uniquely prefers piece `i`. -/
def stromquistUniquePreferenceUnion (i : Fin n) : Set (Fin n → ℝ) :=
  ⋃ j, stromquistUniquePreferenceSet n μ i j

/-- The union of unique preferences for a fixed piece is open. -/
theorem stromquistUniquePreferenceUnion_open (i : Fin n) :
    IsOpen (stromquistUniquePreferenceUnion n μ i) := by
  exact isOpen_iUnion (stromquistUniquePreferenceSet_open n μ i ·)

omit [∀ i, NullSingletonClass (μ i)] in
/-- The union of unique preferences for piece `i` misses the face where that
piece has zero length. -/
theorem stromquistUniquePreferenceUnion_avoids_face (i : Fin n)
    (hpos : ∀ j : Fin n, 0 < μ j (Set.Ico 0 1)) :
    stromquistUniquePreferenceUnion n μ i ∩ Math.FixedPoint.simplexFaceOpp i = ∅ := by
  rw [Set.eq_empty_iff_forall_notMem]
  intro x ⟨hU, hface⟩
  obtain ⟨j, hj⟩ := Set.mem_iUnion.mp hU
  have hB_sub_A :
      stromquistUniquePreferenceSet n μ i j ⊆ stromquistWeakPreferenceSet n μ i j :=
    Set.sdiff_subset
  have hA_mem : x ∈ stromquistWeakPreferenceSet n μ i j := hB_sub_A hj
  have := Set.eq_empty_iff_forall_notMem.mp
    (stromquistWeakPreferenceSet_avoids_face n μ i j (hpos j)) x
  exact this ⟨hA_mem, hface⟩

omit [∀ i, IsFiniteMeasure (μ i)] [∀ i, NullSingletonClass (μ i)] in
private theorem stromquist_fair_assignment (x : Fin n → ℝ)
    (hU : ∀ i, x ∈ stromquistUniquePreferenceUnion n μ i) :
    ∃ assign : Fin n → Fin n, Function.Injective assign ∧
      ∀ i, x ∈ stromquistWeakPreferenceSet n μ i (assign i) ∧
           ∀ k ≠ i, stromquistValue n μ x (assign i) k <
             stromquistValue n μ x (assign i) i := by
  have hchoice : ∀ i, ∃ j, x ∈ stromquistUniquePreferenceSet n μ i j :=
    fun i => Set.mem_iUnion.mp (hU i)
  let assign : Fin n → Fin n := fun i => (hchoice i).choose
  have hassign_mem : ∀ i, x ∈ stromquistUniquePreferenceSet n μ i (assign i) :=
    fun i => (hchoice i).choose_spec
  refine ⟨assign, ?_, ?_⟩
  · intro i i' heq
    by_contra hii'
    have h1 : x ∈ stromquistUniquePreferenceSet n μ i (assign i') := by
      simpa [heq] using hassign_mem i
    have h2 : x ∈ stromquistUniquePreferenceSet n μ i' (assign i') :=
      hassign_mem i'
    exact Set.disjoint_left.mp
      (disjoint_stromquistUniquePreferenceSet n μ _ i i' hii') h1 h2
  · intro i
    have hB : x ∈ stromquistUniquePreferenceSet n μ i (assign i) :=
      hassign_mem i
    have hA : x ∈ stromquistWeakPreferenceSet n μ i (assign i) :=
      Set.sdiff_subset hB
    constructor
    · exact hA
    · intro k hki
      have hnotAk : x ∉ stromquistWeakPreferenceSet n μ k ((hchoice i).choose) := by
        intro hc
        exact hB.2 (Set.mem_biUnion
          (Finset.mem_filter.mpr ⟨Finset.mem_univ k, hki⟩) hc)
      exact lt_of_le_of_ne (hA k) (fun h => hnotAk (fun m => h ▸ hA m))

omit [∀ i, NullSingletonClass (μ i)] in
/-- A common weak-preference point, together with a bijection assigning pieces
to agents, induces an envy-free allocation. -/
theorem stromquist_envyFree_exists_of_preferenceEquiv
    (hn : 0 < n)
    (x : Fin n → ℝ) (hx : x ∈ stdSimplex ℝ (Fin n))
    (e : Fin n ≃ Fin n)
    (hpref : ∀ j : Fin n, x ∈ stromquistWeakPreferenceSet n μ (e.symm j) j)
    (hsupp : ∀ j : Fin n, μ j = (μ j).restrict (Set.Ico 0 1)) :
    ∃ A : Allocation (Fin n) ℝ,
      IsAllocation A ∧ IsEnvyFree (MeasureValuation μ) A := by
  obtain ⟨hmeas, hdisj, hcover01⟩ := stromquistPiece_partition n x hx
  have hpiece_sub : ∀ k, stromquistPiece n x k ⊆ Set.Ico 0 1 :=
    fun k => hcover01 ▸ Set.subset_iUnion (stromquistPiece n x) k
  have hext : ∀ i : Fin n, μ i (Set.Iio 0 ∪ Set.Ici 1) = 0 := fun i => by
    rw [hsupp i, Measure.restrict_apply (measurableSet_Iio.union measurableSet_Ici)]
    have h1 : (Set.Iio (0 : ℝ) ∪ Set.Ici 1) ∩ Set.Ico 0 1 = ∅ := by
      ext t
      simp only [Set.mem_inter_iff, Set.mem_union, Set.mem_Iio, Set.mem_Ici,
        Set.mem_Ico, Set.mem_empty_iff_false, iff_false, not_and]
      rintro (h | h) <;> intro h2 <;> linarith
    rw [h1]
    exact measure_empty
  have hext_disj : ∀ k, Disjoint (stromquistPiece n x k) (Set.Iio 0 ∪ Set.Ici 1) :=
    fun k => Set.disjoint_left.mpr fun t ht_p ht_e => by
      have := hpiece_sub k ht_p
      simp only [Set.mem_Ico] at this
      simp only [Set.mem_union, Set.mem_Iio, Set.mem_Ici] at ht_e
      rcases ht_e with h | h <;> linarith [this.1, this.2]
  let z : Fin n := ⟨0, hn⟩
  refine ⟨fun agent =>
    if agent = z then stromquistPiece n x (e.symm agent) ∪ (Set.Iio 0 ∪ Set.Ici 1)
    else stromquistPiece n x (e.symm agent), ⟨?_, ?_, ?_⟩, ?_⟩
  · intro agent
    simp only [z]
    split_ifs
    · exact (hmeas _).union (measurableSet_Iio.union measurableSet_Ici)
    · exact hmeas _
  · intro i j hij
    have heij : e.symm i ≠ e.symm j := fun h => hij (e.symm.injective h)
    simp only [z]
    split_ifs with hi0 hj0 hj0
    · exact absurd (hi0.trans hj0.symm) hij
    · rw [Set.disjoint_union_left]
      exact ⟨hdisj _ _ heij, (hext_disj (e.symm j)).symm⟩
    · rw [Set.disjoint_union_right]
      exact ⟨hdisj _ _ heij, hext_disj (e.symm i)⟩
    · exact hdisj _ _ heij
  · ext t
    simp only [Set.mem_iUnion, Set.mem_univ, iff_true]
    by_cases ht01 : t ∈ Set.Ico 0 1
    · rw [← hcover01] at ht01
      obtain ⟨k, hk⟩ := Set.mem_iUnion.mp ht01
      refine ⟨e k, ?_⟩
      split_ifs
      · rw [e.symm_apply_apply]
        exact Set.mem_union_left _ hk
      · rw [e.symm_apply_apply]
        exact hk
    · refine ⟨z, ?_⟩
      refine Set.mem_union_right _ ?_
      simp only [Set.mem_Ico, not_and_or, not_lt] at ht01
      simp only [Set.mem_union, Set.mem_Iio, Set.mem_Ici]
      rcases ht01 with h | h
      · exact Or.inl (not_le.mp h)
      · exact Or.inr h
  · have hA_measure : ∀ (i j : Fin n),
        μ i (if j = z then stromquistPiece n x (e.symm j) ∪ (Set.Iio 0 ∪ Set.Ici 1)
              else stromquistPiece n x (e.symm j)) =
          μ i (stromquistPiece n x (e.symm j)) := by
      intro i j
      split_ifs
      · rw [measure_union (hext_disj _) (measurableSet_Iio.union measurableSet_Ici),
          hext i, add_zero]
      · rfl
    intro i j
    simp only [z] at hA_measure ⊢
    simp only [MeasureValuation]
    rw [hA_measure i j, hA_measure i i]
    have hle := hpref i (e.symm j)
    simp only [stromquistValue] at hle
    exact (ENNReal.toReal_le_toReal (measure_ne_top _ _) (measure_ne_top _ _)).mp hle

/-- Usual case of Stromquist's construction: if every simplex point lies in
some open set of uniquely preferred pieces, then there is an envy-free
allocation. -/
theorem stromquist_usualCase_envyFree_exists
    (hn : 0 < n)
    (hcover : stdSimplex ℝ (Fin n) ⊆ ⋃ i, stromquistUniquePreferenceUnion n μ i)
    (hpos : ∀ j : Fin n, 0 < μ j (Set.Ico 0 1))
    (hsupp : ∀ j : Fin n, μ j = (μ j).restrict (Set.Ico 0 1)) :
    ∃ A : Allocation (Fin n) ℝ,
      IsAllocation A ∧ IsEnvyFree (MeasureValuation μ) A := by
  obtain ⟨x, hx_simp, hx_U⟩ := Math.FixedPoint.kkm_open_cover hn
    (stromquistUniquePreferenceUnion n μ)
    (stromquistUniquePreferenceUnion_open n μ)
    (fun i => by
      intro x hx_face hx_U
      have h := Set.mem_inter hx_U hx_face
      rw [stromquistUniquePreferenceUnion_avoids_face n μ i hpos] at h
      simp at h)
    hcover
  obtain ⟨assign, hinj, hassign⟩ := stromquist_fair_assignment n μ x hx_U
  have hbij : Function.Bijective assign := Finite.injective_iff_bijective.mp hinj
  let e : Fin n ≃ Fin n := Equiv.ofBijective assign hbij
  exact stromquist_envyFree_exists_of_preferenceEquiv n μ hn x hx_simp e (fun i => by
      have h := (hassign (e.symm i)).1
      have heq : assign (e.symm i) = i := e.apply_symm_apply i
      rwa [heq] at h) hsupp

/-- The open shifted cell determined by integer coordinates `p` for agent `j`.
The first `n - 1` coordinates are shifted by `α j` and meshed at scale `M`. -/
def stromquistShiftedCell (M : ℕ) (α : Fin n → ℝ) (j : Fin n)
    (p : Fin (n - 1) → ℤ) : Set (Fin n → ℝ) :=
  {x | ∀ k : Fin (n - 1),
    (p k : ℝ) < (M : ℝ) * (x ⟨k.1, by omega⟩ - α j) ∧
      (M : ℝ) * (x ⟨k.1, by omega⟩ - α j) < (p k : ℝ) + 1}

/-- A shifted cell hits piece `i` for agent `j` when it contains a simplex point
where `i` is weakly best for that agent. -/
def stromquistCellHits (M : ℕ) (α : Fin n → ℝ) (j i : Fin n)
    (p : Fin (n - 1) → ℤ) : Prop :=
  ((stromquistShiftedCell n M α j p) ∩ stdSimplex ℝ (Fin n) ∩
    stromquistWeakPreferenceSet n μ i j).Nonempty

/-- The owner of a shifted cell is the least piece whose weak-preference set
meets that cell, if there is one. -/
noncomputable def stromquistCellOwner (M : ℕ) (α : Fin n → ℝ) (j : Fin n)
    (p : Fin (n - 1) → ℤ) : Option (Fin n) := by
  classical
  exact if h : ∃ i : Fin n, stromquistCellHits n μ M α j i p then
    some <| (Finset.univ.filter fun i => stromquistCellHits n μ M α j i p).min'
      (by
        rcases h with ⟨i, hi⟩
        exact ⟨i, Finset.mem_filter.mpr ⟨Finset.mem_univ i, hi⟩⟩)
  else
    none

/-- Approximate unique-preference set obtained by assigning shifted cells to
their owners. -/
noncomputable def stromquistApproxUniquePreferenceSet
    (M : ℕ) (α : Fin n → ℝ) (i j : Fin n) : Set (Fin n → ℝ) :=
  ⋃ p : Fin (n - 1) → ℤ,
    if stromquistCellOwner n μ M α j p = some i then
      stromquistShiftedCell n M α j p
    else
      ∅

/-- Approximate preference union for piece `i`. -/
noncomputable def stromquistApproxPreferenceUnion
    (M : ℕ) (α : Fin n → ℝ) (i : Fin n) : Set (Fin n → ℝ) :=
  ⋃ j : Fin n, stromquistApproxUniquePreferenceSet n μ M α i j

/-- Shifted cells are open in the ambient function space. -/
theorem stromquistShiftedCell_open (M : ℕ) (α : Fin n → ℝ) (j : Fin n)
    (p : Fin (n - 1) → ℤ) : IsOpen (stromquistShiftedCell n M α j p) := by
  classical
  change IsOpen ({x | ∀ k : Fin (n - 1),
    (p k : ℝ) < (M : ℝ) * (x ⟨k.1, by omega⟩ - α j) ∧
      (M : ℝ) * (x ⟨k.1, by omega⟩ - α j) < (p k : ℝ) + 1} : Set (Fin n → ℝ))
  rw [show ({x | ∀ k : Fin (n - 1),
      (p k : ℝ) < (M : ℝ) * (x ⟨k.1, by omega⟩ - α j) ∧
        (M : ℝ) * (x ⟨k.1, by omega⟩ - α j) < (p k : ℝ) + 1} : Set (Fin n → ℝ)) =
      ⋂ k ∈ (Finset.univ : Finset (Fin (n - 1))),
        {x | (p k : ℝ) < (M : ℝ) * (x ⟨k.1, by omega⟩ - α j) ∧
          (M : ℝ) * (x ⟨k.1, by omega⟩ - α j) < (p k : ℝ) + 1} by
    ext x
    simp]
  refine isOpen_biInter_finset fun k _ => ?_
  let g : (Fin n → ℝ) → ℝ := fun x => (M : ℝ) * (x ⟨k.1, by omega⟩ - α j)
  have hg : Continuous g := by
    fun_prop
  change IsOpen
    ({x : Fin n → ℝ | (p k : ℝ) < (M : ℝ) * (x ⟨k.1, by omega⟩ - α j)} ∩
      {x : Fin n → ℝ | (M : ℝ) * (x ⟨k.1, by omega⟩ - α j) < (p k : ℝ) + 1})
  simpa [g] using (isOpen_lt continuous_const hg).inter (isOpen_lt hg continuous_const)

omit [∀ i, IsFiniteMeasure (μ i)] [∀ i, NullSingletonClass (μ i)] in
/-- Approximate unique-preference sets are open. -/
theorem stromquistApproxUniquePreferenceSet_open
    (M : ℕ) (α : Fin n → ℝ) (i j : Fin n) :
    IsOpen (stromquistApproxUniquePreferenceSet n μ M α i j) := by
  classical
  refine isOpen_iUnion fun p => ?_
  by_cases h : stromquistCellOwner n μ M α j p = some i
  · simp [h, stromquistShiftedCell_open]
  · simp [h]

omit [∀ i, IsFiniteMeasure (μ i)] [∀ i, NullSingletonClass (μ i)] in
/-- Approximate preference unions are open. -/
theorem stromquistApproxPreferenceUnion_open
    (M : ℕ) (α : Fin n → ℝ) (i : Fin n) :
    IsOpen (stromquistApproxPreferenceUnion n μ M α i) := by
  exact isOpen_iUnion (stromquistApproxUniquePreferenceSet_open n μ M α i ·)

omit [∀ i, IsFiniteMeasure (μ i)] [∀ i, NullSingletonClass (μ i)] in
/-- For a fixed agent, approximate unique-preference sets for distinct pieces
are disjoint. -/
theorem disjoint_stromquistApproxUniquePreferenceSet
    (M : ℕ) (α : Fin n → ℝ) (j i i' : Fin n) (hii' : i ≠ i') :
    Disjoint (stromquistApproxUniquePreferenceSet n μ M α i j)
      (stromquistApproxUniquePreferenceSet n μ M α i' j) := by
  classical
  simp only [Set.disjoint_left, stromquistApproxUniquePreferenceSet]
  intro x hx hx'
  rcases Set.mem_iUnion.mp hx with ⟨p, hp⟩
  rcases Set.mem_iUnion.mp hx' with ⟨q, hq⟩
  by_cases hpOwner : stromquistCellOwner n μ M α j p = some i
  · by_cases hqOwner : stromquistCellOwner n μ M α j q = some i'
    · have hxp : x ∈ stromquistShiftedCell n M α j p := by
        rw [if_pos hpOwner] at hp
        exact hp
      have hxq : x ∈ stromquistShiftedCell n M α j q := by
        rw [if_pos hqOwner] at hq
        exact hq
      have hpEq : p = q := by
        funext k
        rcases hxp k with ⟨hpk0, hpk1⟩
        rcases hxq k with ⟨hqk0, hqk1⟩
        let t : ℝ := (M : ℝ) * (x ⟨k.1, by omega⟩ - α j)
        have hpFloor : Int.floor t = p k := by
          rw [Int.floor_eq_iff]
          exact ⟨le_of_lt hpk0, hpk1⟩
        have hqFloor : Int.floor t = q k := by
          rw [Int.floor_eq_iff]
          exact ⟨le_of_lt hqk0, hqk1⟩
        exact hpFloor.symm.trans hqFloor
      have hOwnerq : stromquistCellOwner n μ M α j p = some i' := by
        simpa [hpEq] using hqOwner
      have : some i = some i' := hpOwner.symm.trans hOwnerq
      exact hii' (Option.some.inj this)
    · have : x ∈ (∅ : Set (Fin n → ℝ)) := by
        rw [if_neg hqOwner] at hq
        exact hq
      exact this
  · have : x ∈ (∅ : Set (Fin n → ℝ)) := by
      rw [if_neg hpOwner] at hp
      exact hp
    exact this

omit [∀ i, IsFiniteMeasure (μ i)] [∀ i, NullSingletonClass (μ i)] in
private theorem stromquistCellOwner_eq_some_imp_hits
    (M : ℕ) (α : Fin n → ℝ) (j i : Fin n) (p : Fin (n - 1) → ℤ)
    (h : stromquistCellOwner n μ M α j p = some i) :
    stromquistCellHits n μ M α j i p := by
  classical
  unfold stromquistCellOwner at h
  split_ifs at h with hex
  · have hmem :
        (Finset.univ.filter fun i => stromquistCellHits n μ M α j i p).min'
          (by
            rcases hex with ⟨i0, hi0⟩
            exact ⟨i0, Finset.mem_filter.mpr ⟨Finset.mem_univ i0, hi0⟩⟩) ∈
        (Finset.univ.filter fun i => stromquistCellHits n μ M α j i p) :=
      Finset.min'_mem _ _
    have hhit :
        stromquistCellHits n μ M α j
          ((Finset.univ.filter fun i => stromquistCellHits n μ M α j i p).min'
            (by
              rcases hex with ⟨i0, hi0⟩
              exact ⟨i0, Finset.mem_filter.mpr ⟨Finset.mem_univ i0, hi0⟩⟩)) p :=
      (Finset.mem_filter.mp hmem).2
    injection h with hi
    simpa [hi] using hhit

/-- A simplex point lies on an agent-`j` shifted boundary hyperplane. -/
def stromquistOnShiftedBoundary (M : ℕ) (α : Fin n → ℝ) (j : Fin n)
    (x : Fin n → ℝ) : Prop :=
  ∃ k : Fin (n - 1), ∃ z : ℤ,
    (M : ℝ) * (x ⟨k.1, by omega⟩ - α j) = z

private theorem stromquist_mem_shiftedCell_of_not_onBoundary
    (α : Fin n → ℝ) (M : ℕ) (x : Fin n → ℝ) (j : Fin n)
    (hx : ¬ stromquistOnShiftedBoundary n M α j x) :
    let p : Fin (n - 1) → ℤ := fun k =>
      Int.floor ((M : ℝ) * (x ⟨k.1, by omega⟩ - α j))
    x ∈ stromquistShiftedCell n M α j p := by
  intro p k
  have hk : k.1 < n := Nat.lt_of_lt_of_le k.2 (Nat.sub_le n 1)
  constructor
  · have hle :
        ((Int.floor ((M : ℝ) * (x ⟨k.1, hk⟩ - α j))) : ℝ) ≤
          (M : ℝ) * (x ⟨k.1, hk⟩ - α j) :=
      Int.floor_le _
    have hne :
        ((Int.floor ((M : ℝ) * (x ⟨k.1, hk⟩ - α j))) : ℝ) ≠
          (M : ℝ) * (x ⟨k.1, hk⟩ - α j) := by
      intro hEq
      apply hx
      exact ⟨k, Int.floor ((M : ℝ) * (x ⟨k.1, hk⟩ - α j)), hEq.symm⟩
    exact lt_of_le_of_ne hle hne
  · simp [p]

omit [∀ i, IsFiniteMeasure (μ i)] [∀ i, NullSingletonClass (μ i)] in
/-- The shifted-cell unions cover the simplex when the agent shifts have
pairwise irrational differences. -/
theorem stromquistApproxPreferenceUnion_covers
    (hn : 0 < n)
    (α : Fin n → ℝ)
    (hα : Pairwise fun j k : Fin n => Irrational (α j - α k))
    (M : ℕ) (hM : 0 < M) :
    stdSimplex ℝ (Fin n) ⊆ ⋃ i, stromquistApproxPreferenceUnion n μ M α i := by
  intro x hx
  by_contra hxU
  have hxU' : ∀ i : Fin n, x ∉ stromquistApproxPreferenceUnion n μ M α i := by
    intro i hi
    exact hxU (Set.mem_iUnion.mpr ⟨i, hi⟩)
  have hxBoundary : ∀ j : Fin n, stromquistOnShiftedBoundary n M α j x := by
    intro j
    by_contra hj
    let p : Fin (n - 1) → ℤ := fun k =>
      Int.floor ((M : ℝ) * (x ⟨k.1, by omega⟩ - α j))
    have hxCell : x ∈ stromquistShiftedCell n M α j p :=
      stromquist_mem_shiftedCell_of_not_onBoundary n α M x j hj
    obtain ⟨i, hi⟩ := Set.mem_iUnion.mp (stromquistWeakPreferenceSet_covers n μ j hx)
    have hHit : stromquistCellHits n μ M α j i p := by
      refine ⟨x, ?_⟩
      exact ⟨⟨hxCell, hx⟩, hi⟩
    have hOwnerNeNone : stromquistCellOwner n μ M α j p ≠ none := by
      classical
      have hex : ∃ i : Fin n, stromquistCellHits n μ M α j i p := ⟨i, hHit⟩
      unfold stromquistCellOwner
      simp [hex]
    classical
    cases hOwner : stromquistCellOwner n μ M α j p with
    | none =>
        exact (hOwnerNeNone hOwner).elim
    | some i0 =>
        have hxB : x ∈ stromquistApproxUniquePreferenceSet n μ M α i0 j := by
          refine Set.mem_iUnion.mpr ⟨p, ?_⟩
          simp [hOwner, hxCell]
        have hxUi0 : x ∈ stromquistApproxPreferenceUnion n μ M α i0 :=
          Set.mem_iUnion.mpr ⟨j, hxB⟩
        exact hxU' i0 hxUi0
  choose k z hk using hxBoundary
  have hcard : Fintype.card (Fin (n - 1)) < Fintype.card (Fin n) := by
    simp only [Fintype.card_fin]
    omega
  obtain ⟨j, j', hjj', hkk⟩ := Fintype.exists_ne_map_eq_of_card_lt k hcard
  have hk_j :
      (M : ℝ) * (x ⟨(k j).1, by omega⟩ - α j) = z j :=
    hk j
  have hk_j' :
      (M : ℝ) * (x ⟨(k j).1, by omega⟩ - α j') = z j' := by
    simpa [hkk] using hk j'
  have hsub : (M : ℝ) * (α j - α j') = ((z j' - z j : ℤ) : ℝ) := by
    have hk_j_lin :
        (M : ℝ) * x ⟨(k j).1, by omega⟩ - (M : ℝ) * α j = z j := by
      linarith
    have hk_j'_lin :
        (M : ℝ) * x ⟨(k j).1, by omega⟩ - (M : ℝ) * α j' = z j' := by
      linarith
    have hαj : (M : ℝ) * α j = (M : ℝ) * x ⟨(k j).1, by omega⟩ - z j := by
      linarith
    have hαj' : (M : ℝ) * α j' = (M : ℝ) * x ⟨(k j).1, by omega⟩ - z j' := by
      linarith
    calc
      (M : ℝ) * (α j - α j') = (M : ℝ) * α j - (M : ℝ) * α j' := by ring
      _ = (((M : ℝ) * x ⟨(k j).1, by omega⟩ - z j) -
          ((M : ℝ) * x ⟨(k j).1, by omega⟩ - z j')) := by rw [hαj, hαj']
      _ = (z j' : ℝ) - (z j : ℝ) := by ring
      _ = ((z j' - z j : ℤ) : ℝ) := by rw [Int.cast_sub]
  have hrepr : α j - α j' = ((z j' - z j : ℤ) : ℝ) / M := by
    have hM0 : (M : ℝ) ≠ 0 := by exact_mod_cast (Nat.ne_of_gt hM)
    apply (eq_div_iff hM0).2
    nlinarith [hsub]
  have hirr := (irrational_iff_ne_rational (α j - α j')).mp (hα hjj')
  exact hirr (z j' - z j) M (by exact_mod_cast (Nat.ne_of_gt hM)) hrepr

private theorem stromquist_same_shiftedCell_dist_le
    (hn : 0 < n)
    (M : ℕ) (hM : 0 < M) (α : Fin n → ℝ) (j : Fin n)
    (p : Fin (n - 1) → ℤ) (x y : Fin n → ℝ)
    (hx : x ∈ stromquistShiftedCell n M α j p)
    (hy : y ∈ stromquistShiftedCell n M α j p)
    (hxs : x ∈ stdSimplex ℝ (Fin n)) (hys : y ∈ stdSimplex ℝ (Fin n)) :
    dist x y ≤ n / M := by
  rcases n with _ | m
  · exact Fin.elim0 j
  have hmM_nonneg : 0 ≤ (m : ℝ) / (M : ℝ) := by positivity
  have hcoord : ∀ k : Fin m,
      |x k.castSucc - y k.castSucc| ≤ 1 / (M : ℝ) := by
    intro k
    have hxk := hx k
    have hyk := hy k
    have hMpos : (0 : ℝ) < M := by exact_mod_cast hM
    change |x ⟨k.1, by omega⟩ - y ⟨k.1, by omega⟩| ≤ 1 / (M : ℝ)
    rw [abs_sub_le_iff]
    constructor
    · have hlt : x ⟨k.1, by omega⟩ - y ⟨k.1, by omega⟩ < 1 / (M : ℝ) := by
        rw [lt_div_iff₀ hMpos]
        nlinarith [hxk.2, hyk.1]
      linarith
    · have hlt : y ⟨k.1, by omega⟩ - x ⟨k.1, by omega⟩ < 1 / (M : ℝ) := by
        rw [lt_div_iff₀ hMpos]
        nlinarith [hyk.2, hxk.1]
      linarith
  have hlast :
      |x (Fin.last m) - y (Fin.last m)| ≤ m / (M : ℝ) := by
    calc
      |x (Fin.last m) - y (Fin.last m)|
          ≤ ∑ k : Fin m, |x k.castSucc - y k.castSucc| :=
            Math.Fin.abs_last_sub_last_le_sum_abs_castSucc x y hxs.2 hys.2
      _ ≤ ∑ _k : Fin m, (1 / (M : ℝ)) :=
            Finset.sum_le_sum fun k _ => hcoord k
      _ = m / (M : ℝ) := by
            simp [Finset.sum_const, Finset.card_univ, Fintype.card_fin, nsmul_eq_mul,
              div_eq_mul_inv]
  have hdist_nonneg : 0 ≤ (m.succ : ℝ) / (M : ℝ) := by positivity
  rw [dist_pi_le_iff hdist_nonneg]
  intro i
  by_cases hi : i = Fin.last m
  · subst hi
    simpa [dist_eq_norm] using hlast.trans
      (div_le_div_of_nonneg_right (by norm_num : (m : ℝ) ≤ m + 1) (Nat.cast_nonneg _))
  · obtain ⟨k, hk⟩ := i.eq_castSucc_of_ne_last hi
    subst hk
    simpa [dist_eq_norm] using (hcoord k).trans
      (by
        rw [div_le_div_iff_of_pos_right (by positivity : (0 : ℝ) < M)]
        exact_mod_cast Nat.succ_le_succ (Nat.zero_le m))

omit [∀ i, IsFiniteMeasure (μ i)] [∀ i, NullSingletonClass (μ i)] in
/-- If the approximate shifted-cell cover avoids the forbidden faces, KKM gives
a simplex point and a permutation whose assigned weak-preference sets are within
mesh distance `n / M`. -/
theorem stromquistApproxPreferenceWitnesses
    (hn : 0 < n)
    (α : Fin n → ℝ)
    (hα : Pairwise fun j k : Fin n => Irrational (α j - α k))
    (M : ℕ) (hM : 0 < M)
    (hface :
      ∀ i, Math.FixedPoint.simplexFaceOpp i ⊆
        (stromquistApproxPreferenceUnion n μ M α i)ᶜ) :
    ∃ (x : Fin n → ℝ) (_ : x ∈ stdSimplex ℝ (Fin n)) (perm : Fin n ≃ Fin n),
      ∀ j : Fin n, ∃ y ∈ stromquistWeakPreferenceSet n μ (perm.symm j) j,
        y ∈ stdSimplex ℝ (Fin n) ∧ dist x y ≤ n / M := by
  obtain ⟨x, hxS, hxU⟩ := Math.FixedPoint.kkm_open_cover hn
    (stromquistApproxPreferenceUnion n μ M α)
    (stromquistApproxPreferenceUnion_open n μ M α)
    hface
    (stromquistApproxPreferenceUnion_covers n μ hn α hα M hM)
  obtain ⟨assign, hassign⟩ :
      ∃ assign : Fin n → Fin n,
        ∀ i, x ∈ stromquistApproxUniquePreferenceSet n μ M α i (assign i) := by
    have h_choice : ∀ i, ∃ j, x ∈ stromquistApproxUniquePreferenceSet n μ M α i j := by
      intro i
      exact Set.mem_iUnion.mp (hxU i)
    choose assign hassign using h_choice
    exact ⟨assign, hassign⟩
  have h_inj : Function.Injective assign := by
    intro i i' heq
    by_contra hii'
    have hdisj := disjoint_stromquistApproxUniquePreferenceSet n μ M α (assign i) i i' hii'
    exact Set.disjoint_left.mp hdisj (hassign i) (by simpa [heq] using hassign i')
  let perm : Fin n ≃ Fin n :=
    Equiv.ofBijective assign ⟨h_inj, Finite.injective_iff_surjective.mp h_inj⟩
  refine ⟨x, hxS, perm, ?_⟩
  intro j
  have hcellUnion : x ∈
      stromquistApproxUniquePreferenceSet n μ M α (perm.symm j) j := by
    have h := hassign (perm.symm j)
    have hassign_eq : assign (perm.symm j) = j := perm.apply_symm_apply j
    rwa [hassign_eq] at h
  simp only [stromquistApproxUniquePreferenceSet, Set.mem_iUnion] at hcellUnion
  obtain ⟨p, hp⟩ := hcellUnion
  by_cases howner : stromquistCellOwner n μ M α j p = some (perm.symm j)
  · have hxcell : x ∈ stromquistShiftedCell n M α j p := by
      rwa [if_pos howner] at hp
    have hhit := stromquistCellOwner_eq_some_imp_hits n μ M α j (perm.symm j) p howner
    simp only [stromquistCellHits] at hhit
    obtain ⟨y, ⟨⟨hycell, hyS⟩, hyPref⟩⟩ := hhit
    exact ⟨y, hyPref, hyS,
      stromquist_same_shiftedCell_dist_le n hn M hM α j p x y hxcell hycell hxS hyS⟩
  · have : x ∈ (∅ : Set (Fin n → ℝ)) := by
      rwa [if_neg howner] at hp
    exact this.elim

/-- For all sufficiently fine meshes, the approximate shifted-cell preference
unions avoid the forbidden faces. -/
theorem stromquistApproxPreferenceUnion_eventually_avoids_faces
    (hn : 0 < n)
    (α : Fin n → ℝ)
    (hpos : ∀ j : Fin n, 0 < μ j (Set.Ico 0 1)) :
    ∃ M₀ : ℕ, 0 < M₀ ∧ ∀ M ≥ M₀, ∀ i,
      Math.FixedPoint.simplexFaceOpp i ⊆
        (stromquistApproxPreferenceUnion n μ M α i)ᶜ := by
  have h_dist_pos (i j : Fin n) :
      ∃ δ > 0, ∀ x ∈ Math.FixedPoint.simplexFaceOpp i,
        ∀ y ∈ stromquistWeakPreferenceSet n μ i j ∩ stdSimplex ℝ (Fin n),
          δ ≤ dist x y := by
    let F : Set (Fin n → ℝ) := Math.FixedPoint.simplexFaceOpp i
    let P : Set (Fin n → ℝ) := stromquistWeakPreferenceSet n μ i j ∩ stdSimplex ℝ (Fin n)
    have hF_compact : IsCompact F := by
      have hF_closed : IsClosed F :=
        (isClosed_eq (continuous_apply i) continuous_const).inter
          (isClosed_stdSimplex ℝ (Fin n))
      exact (isCompact_stdSimplex ℝ (Fin n)).of_isClosed_subset hF_closed
        (by intro x hx; exact hx.2)
    have hP_closed : IsClosed P :=
      (stromquistWeakPreferenceSet_closed n μ i j).inter (isClosed_stdSimplex ℝ (Fin n))
    have hdisj : Disjoint F P := by
      rw [Set.disjoint_left]
      intro x hxF hxP
      have hnot := Set.eq_empty_iff_forall_notMem.mp
        (stromquistWeakPreferenceSet_avoids_face n μ i j (hpos j)) x
      exact hnot ⟨hxP.1, hxF⟩
    obtain ⟨r, hrpos, hr⟩ := Metric.exists_pos_forall_lt_edist hF_compact hP_closed hdisj
    refine ⟨(r : ℝ), by exact_mod_cast hrpos, fun x hx y hy => ?_⟩
    have hlt := hr x hx y hy
    rw [edist_dist] at hlt
    exact le_of_lt (ENNReal.toReal_lt_of_lt_ofReal hlt)
  choose δ hδ_pos hδ using h_dist_pos
  let i0 : Fin n := ⟨0, hn⟩
  let δs : Finset ℝ := Finset.univ.image (fun p : Fin n × Fin n => δ p.1 p.2)
  have hδs_nonempty : δs.Nonempty :=
    ⟨δ i0 i0, Finset.mem_image.mpr ⟨(i0, i0), Finset.mem_univ _, rfl⟩⟩
  let δmin : ℝ := δs.min' hδs_nonempty
  have hδmin_pos : 0 < δmin := by
    have hmem := Finset.min'_mem δs hδs_nonempty
    obtain ⟨p, _, hp⟩ := Finset.mem_image.mp hmem
    change 0 < δs.min' hδs_nonempty
    rw [← hp]
    exact hδ_pos p.1 p.2
  have hδmin_le : ∀ i j : Fin n, δmin ≤ δ i j := by
    intro i j
    exact Finset.min'_le δs (δ i j)
      (Finset.mem_image.mpr ⟨(i, j), Finset.mem_univ _, rfl⟩)
  obtain ⟨M₀, hM₀_pos, hM₀_bound⟩ :
      ∃ M₀ : ℕ, 0 < M₀ ∧ ∀ M ≥ M₀, (n : ℝ) / (M : ℝ) < δmin := by
    refine ⟨⌊(n : ℝ) / δmin⌋₊ + 1, Nat.succ_pos _, fun M hM => ?_⟩
    have hMpos : (0 : ℝ) < M := by
      exact_mod_cast lt_of_lt_of_le (Nat.succ_pos _) hM
    rw [div_lt_iff₀ hMpos]
    have hceil : (n : ℝ) / δmin < (⌊(n : ℝ) / δmin⌋₊ + 1 : ℕ) := by
      simpa [Nat.cast_add, Nat.cast_one] using
        Nat.lt_floor_add_one ((n : ℝ) / δmin)
    have hMreal : ((⌊(n : ℝ) / δmin⌋₊ + 1 : ℕ) : ℝ) ≤ M := by
      exact_mod_cast hM
    calc
      (n : ℝ) = ((n : ℝ) / δmin) * δmin := by
        rw [div_mul_cancel₀ _ hδmin_pos.ne']
      _ < ((⌊(n : ℝ) / δmin⌋₊ + 1 : ℕ) : ℝ) * δmin :=
        mul_lt_mul_of_pos_right hceil hδmin_pos
      _ ≤ (M : ℝ) * δmin :=
        mul_le_mul_of_nonneg_right hMreal hδmin_pos.le
      _ = δmin * (M : ℝ) := by ring
  refine ⟨M₀, hM₀_pos, fun M hM i x hxface hxU => ?_⟩
  obtain ⟨j, hxB⟩ := Set.mem_iUnion.mp hxU
  obtain ⟨p, hp⟩ := Set.mem_iUnion.mp hxB
  by_cases howner : stromquistCellOwner n μ M α j p = some i
  · have hxcell : x ∈ stromquistShiftedCell n M α j p := by
      rwa [if_pos howner] at hp
    have hhit := stromquistCellOwner_eq_some_imp_hits n μ M α j i p howner
    simp only [stromquistCellHits] at hhit
    obtain ⟨y, ⟨⟨hycell, hyS⟩, hyPref⟩⟩ := hhit
    have hMpos : 0 < M := lt_of_lt_of_le hM₀_pos hM
    have hdist_le := stromquist_same_shiftedCell_dist_le n hn M hMpos α j p x y
      hxcell hycell hxface.2 hyS
    have hsep : δmin ≤ dist x y :=
      (hδmin_le i j).trans (hδ i j x hxface y ⟨hyPref, hyS⟩)
    linarith [hM₀_bound M hM, hdist_le, hsep]
  · have : x ∈ (∅ : Set (Fin n → ℝ)) := by
      rwa [if_neg howner] at hp
    exact this.elim

/-- Compactness limit for Stromquist witnesses: if every positive tolerance has
an approximate simplex point and permutation with nearby preference witnesses,
then there is an exact common weak-preference point. -/
theorem stromquist_preferenceEquiv_exists_of_approx
    (h : ∀ ε > (0 : ℝ), ∃ (x : Fin n → ℝ) (_ : x ∈ stdSimplex ℝ (Fin n))
        (e : Fin n ≃ Fin n),
      ∀ j : Fin n, ∃ y ∈ stromquistWeakPreferenceSet n μ (e.symm j) j,
        dist x y < ε) :
    ∃ (x : Fin n → ℝ) (_ : x ∈ stdSimplex ℝ (Fin n)) (e : Fin n ≃ Fin n),
      ∀ j : Fin n, x ∈ stromquistWeakPreferenceSet n μ (e.symm j) j := by
  have h_compact : IsCompact (stdSimplex ℝ (Fin n)) :=
    isCompact_stdSimplex ℝ (Fin n)
  have h_seq : ∃ (x : ℕ → Fin n → ℝ), (∀ k, x k ∈ stdSimplex ℝ (Fin n)) ∧
      ∃ (e : ℕ → Fin n ≃ Fin n),
        ∀ k, ∀ j, ∃ y ∈ stromquistWeakPreferenceSet n μ ((e k).symm j) j,
          dist (x k) y < 1 / (k + 1 : ℝ) := by
    choose x hx e he using h
    refine ⟨fun k => x (1 / (k + 1 : ℝ)) (by positivity), ?_,
      fun k => e (1 / (k + 1 : ℝ)) (by positivity), ?_⟩
    · intro k
      exact hx _ _
    · intro k j
      exact he _ _ j
  obtain ⟨x, hx_seq, e, he⟩ := h_seq
  obtain ⟨x_star, hx_star, subseq, hsubseq_mono, hsubseq_tendsto⟩ :
      ∃ x_star ∈ stdSimplex ℝ (Fin n), ∃ subseq : ℕ → ℕ,
        StrictMono subseq ∧ Filter.Tendsto (fun r => x (subseq r)) Filter.atTop
          (nhds x_star) := by
    exact h_compact.tendsto_subseq hx_seq
  have h_e_const : ∃ e₀ : Fin n ≃ Fin n, Set.Infinite {r | e (subseq r) = e₀} := by
    by_contra h_contra
    push Not at h_contra
    exact Set.infinite_univ
      (Set.Finite.subset
        (Set.Finite.biUnion (Set.toFinite (Set.univ : Set (Fin n ≃ Fin n)))
          fun e₀ _ => h_contra e₀)
        fun r _ => by simp)
  obtain ⟨e₀, he₀⟩ := h_e_const
  obtain ⟨subsubseq, hsubsubseq_mono, hsubsubseq_const⟩ :
      ∃ subsubseq : ℕ → ℕ, StrictMono subsubseq ∧
        ∀ r, e (subseq (subsubseq r)) = e₀ := by
    refine ⟨fun r => Nat.recOn r (Nat.find he₀.nonempty)
        (fun r ih => Nat.find (he₀.exists_gt ih)), ?_, ?_⟩
    · exact strictMono_nat_of_lt_succ fun r => (Nat.find_spec (he₀.exists_gt _)).2
    · intro r
      exact Nat.recOn r (Nat.find_spec he₀.nonempty)
        (fun r ih => (Nat.find_spec (he₀.exists_gt _)).1)
  have h_y_tendsto : ∀ j,
      Filter.Tendsto (fun r => Classical.choose (he (subseq (subsubseq r)) j))
        Filter.atTop (nhds x_star) := by
    intro j
    have h_dist : Filter.Tendsto
        (fun r => dist (x (subseq (subsubseq r)))
          (Classical.choose (he (subseq (subsubseq r)) j)))
        Filter.atTop (nhds 0) := by
      refine squeeze_zero
        (f := fun r => dist (x (subseq (subsubseq r)))
          (Classical.choose (he (subseq (subsubseq r)) j)))
        (g := fun r => 1 / (subseq (subsubseq r) + 1 : ℝ))
        (fun _ => dist_nonneg) ?_ ?_
      · intro r
        exact (Classical.choose_spec (he (subseq (subsubseq r)) j)).2.le
      · exact tendsto_one_div_add_atTop_nhds_zero_nat.comp
          (hsubseq_mono.tendsto_atTop.comp hsubsubseq_mono.tendsto_atTop)
    have h_diff_tendsto : Filter.Tendsto
        (fun r => x (subseq (subsubseq r)) -
          Classical.choose (he (subseq (subsubseq r)) j))
        Filter.atTop (nhds 0) := by
      exact tendsto_zero_iff_norm_tendsto_zero.mpr (by simpa [dist_eq_norm] using h_dist)
    simpa using h_diff_tendsto.neg.add
      (hsubseq_tendsto.comp hsubsubseq_mono.tendsto_atTop)
  refine ⟨x_star, hx_star, e₀, ?_⟩
  intro j
  have h_y_in_pref : ∀ r,
      Classical.choose (he (subseq (subsubseq r)) j) ∈
        stromquistWeakPreferenceSet n μ (e₀.symm j) j := by
    intro r
    simpa only [hsubsubseq_const r] using
      (Classical.choose_spec (he (subseq (subsubseq r)) j)).1
  exact IsClosed.mem_of_tendsto
    (stromquistWeakPreferenceSet_closed n μ (e₀.symm j) j)
    (h_y_tendsto j)
    (Filter.Eventually.of_forall h_y_in_pref)

/-- Positive-measure Stromquist case: if every agent gives positive value to
`[0,1)`, then there is a common weak-preference point and a bijection from
pieces to agents. -/
theorem stromquist_preferenceEquiv_exists_of_positive
    (hn : 0 < n)
    (hpos : ∀ j : Fin n, 0 < μ j (Set.Ico 0 1)) :
    ∃ (x : Fin n → ℝ) (_ : x ∈ stdSimplex ℝ (Fin n)) (e : Fin n ≃ Fin n),
      ∀ j : Fin n, x ∈ stromquistWeakPreferenceSet n μ (e.symm j) j := by
  obtain ⟨α, hα⟩ := Math.Fin.irrationalShifts_exist n
  obtain ⟨M₀, hM₀_pos, hface⟩ :=
    stromquistApproxPreferenceUnion_eventually_avoids_faces n μ hn α hpos
  refine stromquist_preferenceEquiv_exists_of_approx n μ ?_
  intro ε hε
  let M : ℕ := ⌊(n : ℝ) / ε⌋₊ + M₀ + 1
  have hM_ge : M₀ ≤ M := by
    omega
  have hM_pos : 0 < M := lt_of_lt_of_le hM₀_pos hM_ge
  have h_n_div_M : (n : ℝ) / (M : ℝ) < ε := by
    have hM_real : ((⌊(n : ℝ) / ε⌋₊ + 1 : ℕ) : ℝ) ≤ M := by
      simp [M]
    have hfloor : (n : ℝ) / ε < ((⌊(n : ℝ) / ε⌋₊ + 1 : ℕ) : ℝ) := by
      simpa [Nat.cast_add, Nat.cast_one] using Nat.lt_floor_add_one ((n : ℝ) / ε)
    have hM_real' : (n : ℝ) / ε < (M : ℝ) := lt_of_lt_of_le hfloor hM_real
    have hM_real_pos : (0 : ℝ) < M := by exact_mod_cast hM_pos
    rw [div_lt_iff₀ hM_real_pos]
    calc
      (n : ℝ) = ((n : ℝ) / ε) * ε := by
        rw [div_mul_cancel₀ _ hε.ne']
      _ < (M : ℝ) * ε := mul_lt_mul_of_pos_right hM_real' hε
      _ = ε * (M : ℝ) := by ring
  obtain ⟨x, hx, e, hwit⟩ :=
    stromquistApproxPreferenceWitnesses n μ hn α hα M hM_pos (hface M hM_ge)
  refine ⟨x, hx, e, fun j => ?_⟩
  obtain ⟨y, hyPref, _hyS, hydist⟩ := hwit j
  exact ⟨y, hyPref, lt_of_le_of_lt hydist h_n_div_M⟩

/-- Stromquist's real-line construction for positive finite non-atomic measures
supported on `[0,1)`. -/
theorem stromquist_envyFree_exists_of_positive
    (hn : 0 < n)
    (hpos : ∀ j : Fin n, 0 < μ j (Set.Ico 0 1))
    (hsupp : ∀ j : Fin n, μ j = (μ j).restrict (Set.Ico 0 1)) :
    ∃ A : Allocation (Fin n) ℝ,
      IsAllocation A ∧ IsEnvyFree (MeasureValuation μ) A := by
  obtain ⟨x, hx, e, hpref⟩ := stromquist_preferenceEquiv_exists_of_positive n μ hn hpos
  exact stromquist_envyFree_exists_of_preferenceEquiv n μ hn x hx e hpref hsupp

/-- Stromquist's real-line construction for finite non-atomic measures
supported on `[0,1)`. Agents assigning zero total value to the cake are handled
by replacing their measures with a positive nonatomic reference measure while
constructing the preference point. -/
theorem stromquist_envyFree_exists
    (hn : 0 < n)
    (hsupp : ∀ j : Fin n, μ j = (μ j).restrict (Set.Ico 0 1)) :
    ∃ A : Allocation (Fin n) ℝ,
      IsAllocation A ∧ IsEnvyFree (MeasureValuation μ) A := by
  let μpos : Fin n → Measure ℝ :=
    fun j => if 0 < μ j (Set.Ico 0 1) then μ j else volume.restrict (Set.Ico 0 1)
  haveI hfin_pos : ∀ j : Fin n, IsFiniteMeasure (μpos j) := fun j => by
    by_cases hj : 0 < μ j (Set.Ico 0 1)
    · simpa [μpos, hj] using (inferInstance : IsFiniteMeasure (μ j))
    · simpa [μpos, hj] using
        (inferInstance : IsFiniteMeasure (volume.restrict (Set.Ico (0 : ℝ) 1)))
  haveI hnoatoms_pos : ∀ j : Fin n, NullSingletonClass (μpos j) := fun j => by
    by_cases hj : 0 < μ j (Set.Ico 0 1)
    · simpa [μpos, hj] using (inferInstance : NullSingletonClass (μ j))
    · simpa [μpos, hj] using
        (inferInstance : NullSingletonClass (volume.restrict (Set.Ico (0 : ℝ) 1)))
  have hpos_pos : ∀ j : Fin n, 0 < μpos j (Set.Ico 0 1) := by
    intro j
    by_cases hj : 0 < μ j (Set.Ico 0 1)
    · simp [μpos, hj]
    · simp [μpos, hj]
  obtain ⟨x, hx, e, hpref_pos⟩ :=
    stromquist_preferenceEquiv_exists_of_positive n μpos hn hpos_pos
  obtain ⟨_, _, hcover01⟩ := stromquistPiece_partition n x hx
  have hpiece_sub : ∀ k : Fin n, stromquistPiece n x k ⊆ Set.Ico 0 1 :=
    fun k => hcover01 ▸ Set.subset_iUnion (stromquistPiece n x) k
  have hpref : ∀ j : Fin n, x ∈ stromquistWeakPreferenceSet n μ (e.symm j) j := by
    intro j
    by_cases hj : 0 < μ j (Set.Ico 0 1)
    · intro k
      have h := hpref_pos j k
      simpa [μpos, hj, stromquistValue] using h
    · have hj_zero : μ j (Set.Ico 0 1) = 0 :=
        le_antisymm (le_of_not_gt hj) zero_le
      intro k
      have hk_zero : μ j (stromquistPiece n x k) = 0 :=
        measure_mono_null (hpiece_sub k) hj_zero
      have hown_zero : μ j (stromquistPiece n x (e.symm j)) = 0 :=
        measure_mono_null (hpiece_sub (e.symm j)) hj_zero
      simp [stromquistValue, hk_zero, hown_zero]
  exact stromquist_envyFree_exists_of_preferenceEquiv n μ hn x hx e hpref hsupp

end Divisible
end FairDivision
end SocialChoice
end GameTheory
