/-
Copyright (c) 2025 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/

import GameTheory.Concepts.Learning.FictitiousPlay
import GameTheory.Concepts.Mixed.MixedImprovement
import GameTheory.Concepts.Potential.MixedPotential
import Mathlib.Analysis.PSeries

/-!
# Fictitious play in potential games

This file records the Monderer-Shapley reduction at the fictitious-play layer:
an exact-potential game has the same fictitious-play processes as the
identical-interest game generated by its potential.
-/

noncomputable section

namespace GameTheory

open Math.Probability

namespace KernelGame

variable {ι : Type} [Fintype ι]

open scoped BigOperators

/-- The aggregate gain of the actions actually played by a fictitious-play
process at round `t`, measured against the belief entering that round. -/
noncomputable def fictitiousPlayPlayedGain [DecidableEq ι] (G : KernelGame ι) [Finite G.Outcome]
    (a : ℕ → Profile G) (t : ℕ) : ℝ :=
  ∑ who, G.mixedGain (G.belief a (t + 1)) who (a (t + 1) who)

/-- The played gain weighted by each player's number of pure strategies. This
is the finite constant needed to dominate the aggregate positive pure-deviation
gap. -/
noncomputable def fictitiousPlayWeightedPlayedGain [DecidableEq ι] (G : KernelGame ι)
    [∀ i, Fintype (G.Strategy i)] [Finite G.Outcome]
    (a : ℕ → Profile G) (t : ℕ) : ℝ :=
  ∑ who, (Fintype.card (G.Strategy who) : ℝ) *
    G.mixedGain (G.belief a (t + 1)) who (a (t + 1) who)

open Classical in
/-- Along a fictitious-play process, the action played at each round has
nonnegative current pure-deviation gain. -/
theorem IsFictitiousPlay.playedGain_nonneg
    [DecidableEq ι] {G : KernelGame ι} [∀ i, Finite (G.Strategy i)] [Finite G.Outcome]
    {a : ℕ → Profile G} (hfp : G.IsFictitiousPlay a) (t : ℕ) (who : ι) :
    0 ≤ G.mixedGain (G.belief a (t + 1)) who (a (t + 1) who) := by
  letI : Fintype (G.Strategy who) := Fintype.ofFinite (G.Strategy who)
  let p := G.belief a (t + 1)
  let played := a (t + 1) who
  have hpoint :
      ∀ s : G.Strategy who, G.mixedGain p who s ≤ G.mixedGain p who played := by
    intro s
    have hbest := hfp t who s
    change
      G.mixedExtension.eu (Function.update p who (PMF.pure played)) who ≥
        G.mixedExtension.eu (Function.update p who (PMF.pure s)) who at hbest
    rw [mixedGain, mixedGain]
    linarith
  have hmono := expect_mono (p who)
    (fun s : G.Strategy who => G.mixedGain p who s)
    (fun _ : G.Strategy who => G.mixedGain p who played) hpoint
  rw [G.weighted_gain_sum_zero p who, expect_const] at hmono
  exact hmono

theorem IsFictitiousPlay.fictitiousPlayPlayedGain_nonneg
    [DecidableEq ι] {G : KernelGame ι} [∀ i, Finite (G.Strategy i)] [Finite G.Outcome]
    {a : ℕ → Profile G} (hfp : G.IsFictitiousPlay a) (t : ℕ) :
    0 ≤ G.fictitiousPlayPlayedGain a t := by
  rw [fictitiousPlayPlayedGain]
  exact Finset.sum_nonneg fun who _ => hfp.playedGain_nonneg t who

open Classical in
/-- Along fictitious play, the aggregate positive pure-deviation gap is bounded
by the strategy-cardinality-weighted gain of the actions actually played. -/
theorem IsFictitiousPlay.mixedImprovement_le_weightedPlayedGain
    [DecidableEq ι] {G : KernelGame ι} [∀ i, Fintype (G.Strategy i)] [Finite G.Outcome]
    {a : ℕ → Profile G} (hfp : G.IsFictitiousPlay a) (t : ℕ) :
    G.mixedImprovement (G.belief a (t + 1)) ≤
      G.fictitiousPlayWeightedPlayedGain a t := by
  rw [mixedImprovement, fictitiousPlayWeightedPlayedGain]
  refine Finset.sum_le_sum fun who _ => ?_
  have hplayed_nonneg : 0 ≤
      G.mixedGain (G.belief a (t + 1)) who (a (t + 1) who) :=
    hfp.playedGain_nonneg t who
  have hpoint :
      ∀ s : G.Strategy who,
        max (G.mixedGain (G.belief a (t + 1)) who s) 0 ≤
          G.mixedGain (G.belief a (t + 1)) who (a (t + 1) who) := by
    intro s
    have hbest := hfp t who s
    have hgain :
        G.mixedGain (G.belief a (t + 1)) who s ≤
          G.mixedGain (G.belief a (t + 1)) who (a (t + 1) who) := by
      rw [mixedGain, mixedGain]
      linarith
    exact max_le hgain hplayed_nonneg
  calc
    (∑ s : G.Strategy who, max (G.mixedGain (G.belief a (t + 1)) who s) 0)
        ≤ ∑ _s : G.Strategy who,
            G.mixedGain (G.belief a (t + 1)) who (a (t + 1) who) := by
          exact Finset.sum_le_sum fun s _ => hpoint s
    _ = (Fintype.card (G.Strategy who) : ℝ) *
          G.mixedGain (G.belief a (t + 1)) who (a (t + 1) who) := by
          simp [Finset.sum_const, nsmul_eq_mul]

open Classical in
/-- Updating one coordinate to the next empirical marginal is affine at the
expected-utility level. -/
theorem mixedExtension_eu_update_empiricalMarginal_succ
    [DecidableEq ι] (G : KernelGame ι) [∀ i, Finite (G.Strategy i)] [Finite G.Outcome]
    (a : ℕ → Profile G) (σ : ∀ i, PMF (G.Strategy i))
    (who : ι) (t : ℕ) :
    G.mixedExtension.eu
        (Function.update σ who (G.empiricalMarginal a who (t + 2))) who =
      ((t + 1 : ℝ) / (t + 2 : ℝ)) *
          G.mixedExtension.eu
            (Function.update σ who (G.empiricalMarginal a who (t + 1))) who +
        (1 / (t + 2 : ℝ)) *
          G.mixedExtension.eu
            (Function.update σ who (PMF.pure (a (t + 1) who))) who := by
  letI : Fintype (G.Strategy who) := Fintype.ofFinite (G.Strategy who)
  rw [G.mixedExtension_eu_update σ who (G.empiricalMarginal a who (t + 2))]
  rw [G.empiricalMarginal_succ_expect a who t
    (fun s => G.mixedExtension.eu (Function.update σ who (PMF.pure s)) who)]
  rw [← G.mixedExtension_eu_update σ who (G.empiricalMarginal a who (t + 1))]

open Classical in
/-- Difference form of `mixedExtension_eu_update_empiricalMarginal_succ`. -/
theorem mixedExtension_eu_update_empiricalMarginal_succ_sub
    [DecidableEq ι] (G : KernelGame ι) [∀ i, Finite (G.Strategy i)] [Finite G.Outcome]
    (a : ℕ → Profile G) (σ : ∀ i, PMF (G.Strategy i))
    (who : ι) (t : ℕ) :
    G.mixedExtension.eu
        (Function.update σ who (G.empiricalMarginal a who (t + 2))) who -
      G.mixedExtension.eu
        (Function.update σ who (G.empiricalMarginal a who (t + 1))) who =
      (1 / (t + 2 : ℝ)) *
        (G.mixedExtension.eu
            (Function.update σ who (PMF.pure (a (t + 1) who))) who -
          G.mixedExtension.eu
            (Function.update σ who (G.empiricalMarginal a who (t + 1))) who) := by
  have h :=
    G.mixedExtension_eu_update_empiricalMarginal_succ a σ who t
  have ht2 : (t + 2 : ℝ) ≠ 0 := by positivity
  rw [h]
  field_simp [ht2]
  ring

open Classical in
/-- If only player `who`'s marginal is advanced from belief `t+1` to belief
`t+2`, the EU increment is exactly the step size times the gain of the action
played by `who` at that round. -/
theorem mixedExtension_eu_belief_update_empiricalMarginal_succ_sub
    [DecidableEq ι] (G : KernelGame ι) [∀ i, Finite (G.Strategy i)] [Finite G.Outcome]
    (a : ℕ → Profile G) (who : ι) (t : ℕ) :
    G.mixedExtension.eu
        (Function.update (G.belief a (t + 1)) who
          (G.empiricalMarginal a who (t + 2))) who -
      G.mixedExtension.eu (G.belief a (t + 1)) who =
      (1 / (t + 2 : ℝ)) *
        G.mixedGain (G.belief a (t + 1)) who (a (t + 1) who) := by
  have h := G.mixedExtension_eu_update_empiricalMarginal_succ_sub
    a (G.belief a (t + 1)) who t
  have hsame :
      Function.update (G.belief a (t + 1)) who
          (G.empiricalMarginal a who (t + 1)) =
        G.belief a (t + 1) := by
    ext i
    by_cases hi : i = who
    · subst hi
      simp [belief]
    · simp [Function.update, hi]
  rw [hsame] at h
  simpa [mixedGain] using h

open Classical in
/-- Team-game version of the one-coordinate empirical update increment, stated
for any fixed common-payoff player `payoffPlayer`. -/
theorem IsTeamGame.mixedExtension_eu_belief_update_empiricalMarginal_succ_sub
    [DecidableEq ι] {G : KernelGame ι} [∀ i, Finite (G.Strategy i)] [Finite G.Outcome]
    (hteam : G.IsTeamGame) (a : ℕ → Profile G) (payoffPlayer who : ι) (t : ℕ) :
    G.mixedExtension.eu
        (Function.update (G.belief a (t + 1)) who
          (G.empiricalMarginal a who (t + 2))) payoffPlayer -
      G.mixedExtension.eu (G.belief a (t + 1)) payoffPlayer =
      (1 / (t + 2 : ℝ)) *
        G.mixedGain (G.belief a (t + 1)) who (a (t + 1) who) := by
  have h :=
    G.mixedExtension_eu_belief_update_empiricalMarginal_succ_sub a who t
  have hnew :
      G.mixedExtension.eu
          (Function.update (G.belief a (t + 1)) who
            (G.empiricalMarginal a who (t + 2))) payoffPlayer =
        G.mixedExtension.eu
          (Function.update (G.belief a (t + 1)) who
            (G.empiricalMarginal a who (t + 2))) who :=
    hteam.mixedExtension.eu_eq _ payoffPlayer who
  have hbase :
      G.mixedExtension.eu (G.belief a (t + 1)) payoffPlayer =
        G.mixedExtension.eu (G.belief a (t + 1)) who :=
    hteam.mixedExtension.eu_eq _ payoffPlayer who
  rw [hnew, hbase]
  exact h

open Classical in
/-- Updating one coordinate to the next empirical marginal is affine for the
mixed extension of a pure-profile potential. -/
theorem mixedPotential_update_empiricalMarginal_succ
    [DecidableEq ι] (G : KernelGame ι) [∀ i, Finite (G.Strategy i)]
    (Φ : Profile G → ℝ) (a : ℕ → Profile G)
    (σ : ∀ i, PMF (G.Strategy i)) (who : ι) (t : ℕ) :
    G.mixedPotential Φ
        (Function.update σ who (G.empiricalMarginal a who (t + 2))) =
      ((t + 1 : ℝ) / (t + 2 : ℝ)) *
          G.mixedPotential Φ
            (Function.update σ who (G.empiricalMarginal a who (t + 1))) +
        (1 / (t + 2 : ℝ)) *
          G.mixedPotential Φ
            (Function.update σ who (PMF.pure (a (t + 1) who))) := by
  letI : Fintype (G.Strategy who) := Fintype.ofFinite (G.Strategy who)
  rw [G.mixedPotential_update Φ σ who (G.empiricalMarginal a who (t + 2))]
  rw [G.empiricalMarginal_succ_expect a who t
    (fun s => G.mixedPotential Φ (Function.update σ who (PMF.pure s)))]
  rw [← G.mixedPotential_update Φ σ who (G.empiricalMarginal a who (t + 1))]

open Classical in
/-- Difference form of `mixedPotential_update_empiricalMarginal_succ`. -/
theorem mixedPotential_update_empiricalMarginal_succ_sub
    [DecidableEq ι] (G : KernelGame ι) [∀ i, Finite (G.Strategy i)]
    (Φ : Profile G → ℝ) (a : ℕ → Profile G)
    (σ : ∀ i, PMF (G.Strategy i)) (who : ι) (t : ℕ) :
    G.mixedPotential Φ
        (Function.update σ who (G.empiricalMarginal a who (t + 2))) -
      G.mixedPotential Φ
        (Function.update σ who (G.empiricalMarginal a who (t + 1))) =
      (1 / (t + 2 : ℝ)) *
        (G.mixedPotential Φ
            (Function.update σ who (PMF.pure (a (t + 1) who))) -
          G.mixedPotential Φ
            (Function.update σ who (G.empiricalMarginal a who (t + 1)))) := by
  have h := G.mixedPotential_update_empiricalMarginal_succ Φ a σ who t
  have ht2 : (t + 2 : ℝ) ≠ 0 := by positivity
  rw [h]
  field_simp [ht2]
  ring

open Classical in
/-- The gain in mixed potential from replacing one marginal by a pure action. -/
noncomputable def mixedPotentialPureGain [DecidableEq ι] (G : KernelGame ι)
    [∀ i, Finite (G.Strategy i)]
    (Φ : Profile G → ℝ) (σ : ∀ i, PMF (G.Strategy i))
    (who : ι) (a : G.Strategy who) : ℝ :=
  G.mixedPotential Φ (Function.update σ who (PMF.pure a)) -
    G.mixedPotential Φ σ

open Classical in
/-- If the current coordinate is still the previous empirical marginal, advancing
that coordinate has exactly the Cesàro first-order mixed-potential increment. -/
theorem mixedPotential_update_empiricalMarginal_succ_sub_of_eq
    [DecidableEq ι] (G : KernelGame ι) [∀ i, Finite (G.Strategy i)]
    (Φ : Profile G → ℝ) (a : ℕ → Profile G)
    (σ : ∀ i, PMF (G.Strategy i)) (who : ι) (t : ℕ)
    (hσ : σ who = G.empiricalMarginal a who (t + 1)) :
    G.mixedPotential Φ (Function.update σ who (G.empiricalMarginal a who (t + 2))) -
      G.mixedPotential Φ σ =
      (1 / (t + 2 : ℝ)) *
        G.mixedPotentialPureGain Φ σ who (a (t + 1) who) := by
  have h := G.mixedPotential_update_empiricalMarginal_succ_sub Φ a σ who t
  have hsame :
      Function.update σ who (G.empiricalMarginal a who (t + 1)) = σ := by
    ext i
    by_cases hi : i = who
    · subst hi
      simp [hσ]
    · simp [Function.update, hi]
  rw [hsame] at h
  simpa [mixedPotentialPureGain] using h

open Classical in
/-- In an exact-potential game, if only player `who`'s marginal is advanced
from belief `t+1` to belief `t+2`, the mixed-potential increment is exactly
the step size times that player's played pure-deviation gain. -/
theorem IsExactPotential.mixedPotential_belief_update_empiricalMarginal_succ_sub
    [DecidableEq ι] {G : KernelGame ι} [∀ i, Finite (G.Strategy i)] [Finite G.Outcome]
    {Φ : Profile G → ℝ} (hΦ : G.IsExactPotential Φ)
    (a : ℕ → Profile G) (who : ι) (t : ℕ) :
    G.mixedPotential Φ
        (Function.update (G.belief a (t + 1)) who
          (G.empiricalMarginal a who (t + 2))) -
      G.mixedPotential Φ (G.belief a (t + 1)) =
      (1 / (t + 2 : ℝ)) *
        G.mixedGain (G.belief a (t + 1)) who (a (t + 1) who) := by
  have h := G.mixedPotential_update_empiricalMarginal_succ_sub
    Φ a (G.belief a (t + 1)) who t
  have hsame :
      Function.update (G.belief a (t + 1)) who
          (G.empiricalMarginal a who (t + 1)) =
        G.belief a (t + 1) := by
    ext i
    by_cases hi : i = who
    · subst hi
      simp [belief]
    · simp [Function.update, hi]
  have hbase := congrArg (G.mixedPotential Φ) hsame
  let newVal : ℝ :=
    G.mixedPotential Φ
      (Function.update (G.belief a (t + 1)) who
        (G.empiricalMarginal a who (t + 2)))
  let oldVal : ℝ :=
    G.mixedPotential Φ
      (Function.update (G.belief a (t + 1)) who
        (G.empiricalMarginal a who (t + 1)))
  let baseVal : ℝ := G.mixedPotential Φ (G.belief a (t + 1))
  let pureVal : ℝ :=
    G.mixedPotential Φ
      (Function.update (G.belief a (t + 1)) who
        (PMF.pure (a (t + 1) who)))
  have h_old :
      newVal - oldVal = (1 / (t + 2 : ℝ)) * (pureVal - oldVal) := by
    simpa [newVal, oldVal, pureVal] using h
  have h_old_base : oldVal = baseVal := by
    simpa [oldVal, baseVal] using hbase
  have hgain :
      G.mixedGain (G.belief a (t + 1)) who (a (t + 1) who) = pureVal - baseVal := by
    simpa [mixedGain, pureVal, baseVal] using
      hΦ.mixedExtension_pure_diff (G.belief a (t + 1)) who (a (t + 1) who)
  change newVal - baseVal =
    (1 / (t + 2 : ℝ)) * G.mixedGain (G.belief a (t + 1)) who (a (t + 1) who)
  rw [hgain]
  rw [h_old_base] at h_old
  exact h_old

open Classical in
/-- In an exact-potential game, pure mixed-potential gains are the same as the
corresponding mixed-extension utility gains. -/
theorem IsExactPotential.mixedPotentialPureGain_eq_mixedGain
    [DecidableEq ι] {G : KernelGame ι} [∀ i, Finite (G.Strategy i)] [Finite G.Outcome]
    {Φ : Profile G → ℝ} (hΦ : G.IsExactPotential Φ)
    (σ : ∀ i, PMF (G.Strategy i)) (who : ι) (a : G.Strategy who) :
    G.mixedPotentialPureGain Φ σ who a = G.mixedGain σ who a := by
  rw [mixedPotentialPureGain]
  exact (hΦ.mixedExtension_pure_diff σ who a).symm

open Classical in
/-- If a pure potential is uniformly bounded on pure profiles, then its mixed
extension is bounded by the same constant. -/
theorem mixedPotential_abs_le_of_abs_bound
    (G : KernelGame ι) [∀ i, Finite (G.Strategy i)]
    (Φ : Profile G → ℝ) {C : ℝ}
    (hC : ∀ s : Profile G, |Φ s| ≤ C)
    (σ : ∀ i, PMF (G.Strategy i)) :
    |G.mixedPotential Φ σ| ≤ C := by
  letI (i : ι) : Fintype (G.Strategy i) := Fintype.ofFinite (G.Strategy i)
  rw [mixedPotential]
  rw [expect_eq_sum]
  calc
    |∑ s : Profile G, ((Math.PMFProduct.pmfPi (A := G.Strategy) σ) s).toReal * Φ s|
        ≤ ∑ s : Profile G,
            |((Math.PMFProduct.pmfPi (A := G.Strategy) σ) s).toReal * Φ s| :=
          Finset.abs_sum_le_sum_abs _ _
    _ ≤ ∑ s : Profile G,
          ((Math.PMFProduct.pmfPi (A := G.Strategy) σ) s).toReal * C := by
          refine Finset.sum_le_sum fun s _ => ?_
          have hw :
              0 ≤ ((Math.PMFProduct.pmfPi (A := G.Strategy) σ) s).toReal :=
            ENNReal.toReal_nonneg
          rw [abs_mul, abs_of_nonneg hw]
          exact mul_le_mul_of_nonneg_left (hC s) hw
    _ = C := by
          have hsum :=
            Math.Probability.pmf_toReal_sum_one (Math.PMFProduct.pmfPi (A := G.Strategy) σ)
          have hmul := congrArg (fun x : ℝ => x * C) hsum
          simpa [Finset.sum_mul] using hmul

open Classical in
/-- A real-valued function on the finite pure-profile space is bounded. -/
theorem exists_profile_abs_bound
    {κ : Type} [Finite κ] (G : KernelGame κ) [∀ i, Finite (G.Strategy i)]
    (Φ : Profile G → ℝ) :
    ∃ C : ℝ, ∀ s : Profile G, |Φ s| ≤ C := by
  letI : Fintype κ := Fintype.ofFinite κ
  letI (i : κ) : Fintype (G.Strategy i) := Fintype.ofFinite (G.Strategy i)
  refine ⟨∑ s : Profile G, |Φ s|, ?_⟩
  intro s
  exact Finset.single_le_sum (fun τ _ => abs_nonneg (Φ τ)) (Finset.mem_univ s)

open Classical in
/-- Advancing one marginal by one empirical step changes a bounded mixed
potential by at most `2C/(t+2)`. -/
theorem mixedPotential_update_empiricalMarginal_succ_abs_sub_le
    [DecidableEq ι] (G : KernelGame ι) [∀ i, Finite (G.Strategy i)]
    (Φ : Profile G → ℝ) {C : ℝ} (hC : ∀ s : Profile G, |Φ s| ≤ C)
    (a : ℕ → Profile G) (σ : ∀ i, PMF (G.Strategy i))
    (who : ι) (t : ℕ)
    (hσ : σ who = G.empiricalMarginal a who (t + 1)) :
    |G.mixedPotential Φ (Function.update σ who (G.empiricalMarginal a who (t + 2))) -
      G.mixedPotential Φ σ| ≤
      (1 / (t + 2 : ℝ)) * (2 * C) := by
  have h := G.mixedPotential_update_empiricalMarginal_succ_sub Φ a σ who t
  have hsame :
      Function.update σ who (G.empiricalMarginal a who (t + 1)) = σ := by
    ext i
    by_cases hi : i = who
    · subst hi
      simp [hσ]
    · simp [Function.update, hi]
  rw [hsame] at h
  have hstep_nonneg : 0 ≤ (1 / (t + 2 : ℝ)) := by positivity
  have hpure := G.mixedPotential_abs_le_of_abs_bound Φ hC
    (Function.update σ who (PMF.pure (a (t + 1) who)))
  have hbase := G.mixedPotential_abs_le_of_abs_bound Φ hC σ
  have hdiff_bound :
      |G.mixedPotential Φ (Function.update σ who (PMF.pure (a (t + 1) who))) -
        G.mixedPotential Φ σ| ≤ 2 * C := by
    have habs := abs_sub
      (G.mixedPotential Φ (Function.update σ who (PMF.pure (a (t + 1) who))))
      (G.mixedPotential Φ σ)
    linarith
  calc
    |G.mixedPotential Φ (Function.update σ who (G.empiricalMarginal a who (t + 2))) -
      G.mixedPotential Φ σ|
        = |(1 / (t + 2 : ℝ)) *
            (G.mixedPotential Φ (Function.update σ who (PMF.pure (a (t + 1) who))) -
              G.mixedPotential Φ σ)| := by rw [h]
    _ = (1 / (t + 2 : ℝ)) *
            |G.mixedPotential Φ (Function.update σ who (PMF.pure (a (t + 1) who))) -
              G.mixedPotential Φ σ| := by
          rw [abs_mul, abs_of_nonneg hstep_nonneg]
    _ ≤ (1 / (t + 2 : ℝ)) * (2 * C) :=
          mul_le_mul_of_nonneg_left hdiff_bound hstep_nonneg

open Classical in
/-- Advancing another player's marginal by one empirical step changes the
current pure-deviation gain in the mixed potential by at most `4C/(t+2)`. -/
theorem mixedPotential_pureGain_update_empiricalMarginal_succ_abs_sub_le
    [DecidableEq ι] (G : KernelGame ι) [∀ i, Finite (G.Strategy i)]
    (Φ : Profile G → ℝ) {C : ℝ} (hC : ∀ s : Profile G, |Φ s| ≤ C)
    (a : ℕ → Profile G) (σ : ∀ i, PMF (G.Strategy i))
    {changed who : ι} (b : G.Strategy who) (hne : changed ≠ who) (t : ℕ)
    (hσ : σ changed = G.empiricalMarginal a changed (t + 1)) :
    abs
      ((G.mixedPotential Φ
          (Function.update (Function.update σ changed
            (G.empiricalMarginal a changed (t + 2))) who
            (PMF.pure b)) -
        G.mixedPotential Φ
          (Function.update σ changed (G.empiricalMarginal a changed (t + 2)))) -
      (G.mixedPotential Φ (Function.update σ who (PMF.pure b)) -
        G.mixedPotential Φ σ)) ≤
      (1 / (t + 2 : ℝ)) * (4 * C) := by
  have hcomm :
      Function.update (Function.update σ changed
          (G.empiricalMarginal a changed (t + 2))) who
          (PMF.pure b) =
        Function.update (Function.update σ who (PMF.pure b)) changed
          (G.empiricalMarginal a changed (t + 2)) := by
    ext i
    by_cases hiw : i = who
    · subst hiw
      simp [Function.update, hne.symm]
    · by_cases hic : i = changed
      · subst hic
        simp [Function.update, hne]
      · simp [Function.update, hiw, hic]
  have hσpure :
      (Function.update σ who (PMF.pure b)) changed =
        G.empiricalMarginal a changed (t + 1) := by
    simp [Function.update, hne, hσ]
  have h1 := G.mixedPotential_update_empiricalMarginal_succ_abs_sub_le Φ hC a
    (Function.update σ who (PMF.pure b)) changed t hσpure
  have h2 := G.mixedPotential_update_empiricalMarginal_succ_abs_sub_le Φ hC a σ changed t hσ
  rw [hcomm]
  have htri := abs_sub
    (G.mixedPotential Φ
      (Function.update (Function.update σ who (PMF.pure b)) changed
        (G.empiricalMarginal a changed (t + 2))) -
      G.mixedPotential Φ (Function.update σ who (PMF.pure b)))
    (G.mixedPotential Φ (Function.update σ changed (G.empiricalMarginal a changed (t + 2))) -
      G.mixedPotential Φ σ)
  have htarget_eq :
      ((G.mixedPotential Φ
          (Function.update (Function.update σ who (PMF.pure b)) changed
            (G.empiricalMarginal a changed (t + 2))) -
          G.mixedPotential Φ
            (Function.update σ changed (G.empiricalMarginal a changed (t + 2)))) -
        (G.mixedPotential Φ (Function.update σ who (PMF.pure b)) -
          G.mixedPotential Φ σ)) =
      ((G.mixedPotential Φ
          (Function.update (Function.update σ who (PMF.pure b)) changed
            (G.empiricalMarginal a changed (t + 2))) -
          G.mixedPotential Φ (Function.update σ who (PMF.pure b))) -
        (G.mixedPotential Φ (Function.update σ changed (G.empiricalMarginal a changed (t + 2))) -
          G.mixedPotential Φ σ)) := by ring
  rw [htarget_eq]
  have hsum :
      |G.mixedPotential Φ
          (Function.update (Function.update σ who (PMF.pure b)) changed
            (G.empiricalMarginal a changed (t + 2))) -
          G.mixedPotential Φ (Function.update σ who (PMF.pure b))| +
        |G.mixedPotential Φ (Function.update σ changed (G.empiricalMarginal a changed (t + 2))) -
          G.mixedPotential Φ σ| ≤
        (1 / (t + 2 : ℝ)) * (2 * C) + (1 / (t + 2 : ℝ)) * (2 * C) := by
    exact add_le_add h1 h2
  calc
    |(G.mixedPotential Φ
          (Function.update (Function.update σ who (PMF.pure b)) changed
            (G.empiricalMarginal a changed (t + 2))) -
          G.mixedPotential Φ (Function.update σ who (PMF.pure b))) -
        (G.mixedPotential Φ (Function.update σ changed (G.empiricalMarginal a changed (t + 2))) -
          G.mixedPotential Φ σ)|
        ≤ _ := htri
    _ ≤ (1 / (t + 2 : ℝ)) * (2 * C) + (1 / (t + 2 : ℝ)) * (2 * C) := hsum
    _ = (1 / (t + 2 : ℝ)) * (4 * C) := by ring

open Classical in
/-- Advancing player `who`'s own marginal by one empirical step changes that
player's fixed pure potential gain by at most `2C/(t+2)`. -/
theorem mixedPotentialPureGain_update_empiricalMarginal_succ_self_abs_sub_le
    [DecidableEq ι] (G : KernelGame ι) [∀ i, Finite (G.Strategy i)]
    (Φ : Profile G → ℝ) {C : ℝ} (hC : ∀ s : Profile G, |Φ s| ≤ C)
    (a : ℕ → Profile G) (σ : ∀ i, PMF (G.Strategy i))
    {who : ι} (b : G.Strategy who) (t : ℕ)
    (hσ : σ who = G.empiricalMarginal a who (t + 1)) :
    |G.mixedPotentialPureGain Φ
        (Function.update σ who (G.empiricalMarginal a who (t + 2))) who b -
      G.mixedPotentialPureGain Φ σ who b| ≤
      (1 / (t + 2 : ℝ)) * (2 * C) := by
  have hchange := G.mixedPotential_update_empiricalMarginal_succ_abs_sub_le
    Φ hC a σ who t hσ
  have hpure :
      Function.update (Function.update σ who (G.empiricalMarginal a who (t + 2))) who
          (PMF.pure b) =
        Function.update σ who (PMF.pure b) := by
    ext i
    by_cases hi : i = who
    · subst hi
      simp
    · simp [Function.update, hi]
  rw [mixedPotentialPureGain, mixedPotentialPureGain, hpure]
  have hrewrite :
      (G.mixedPotential Φ (Function.update σ who (PMF.pure b)) -
          G.mixedPotential Φ (Function.update σ who (G.empiricalMarginal a who (t + 2)))) -
        (G.mixedPotential Φ (Function.update σ who (PMF.pure b)) -
          G.mixedPotential Φ σ) =
        -(G.mixedPotential Φ (Function.update σ who (G.empiricalMarginal a who (t + 2))) -
          G.mixedPotential Φ σ) := by
    ring
  rw [hrewrite, abs_neg]
  exact hchange

open Classical in
/-- Advancing any one marginal by one empirical step changes any fixed pure
potential gain by at most `4C/(t+2)`. -/
theorem mixedPotentialPureGain_update_empiricalMarginal_succ_abs_sub_le
    [DecidableEq ι] (G : KernelGame ι) [∀ i, Finite (G.Strategy i)]
    (Φ : Profile G → ℝ) {C : ℝ} (hC : ∀ s : Profile G, |Φ s| ≤ C)
    (a : ℕ → Profile G) (σ : ∀ i, PMF (G.Strategy i))
    {changed who : ι} (b : G.Strategy who) (t : ℕ)
    (hσ : σ changed = G.empiricalMarginal a changed (t + 1)) :
    |G.mixedPotentialPureGain Φ
        (Function.update σ changed (G.empiricalMarginal a changed (t + 2))) who b -
      G.mixedPotentialPureGain Φ σ who b| ≤
      (1 / (t + 2 : ℝ)) * (4 * C) := by
  by_cases hsame : changed = who
  · subst hsame
    have hself := G.mixedPotentialPureGain_update_empiricalMarginal_succ_self_abs_sub_le
      Φ hC a σ b t hσ
    have hC_nonneg : 0 ≤ C := by
      have h := hC (a 0)
      exact (abs_nonneg _).trans h
    have hstep_nonneg : 0 ≤ (1 / (t + 2 : ℝ)) := by positivity
    nlinarith
  · have hne : changed ≠ who := hsame
    have h := G.mixedPotential_pureGain_update_empiricalMarginal_succ_abs_sub_le
      Φ hC a σ b hne t hσ
    simpa [mixedPotentialPureGain] using h

open Classical in
/-- Sweeping a nodup list of empirical marginal updates changes any fixed pure
potential gain by at most the list length times the one-coordinate bound. -/
theorem mixedPotentialPureGain_foldl_update_empiricalMarginal_succ_abs_sub_le
    [DecidableEq ι] (G : KernelGame ι) [∀ i, Finite (G.Strategy i)]
    (Φ : Profile G → ℝ) {C : ℝ} (hC : ∀ s : Profile G, |Φ s| ≤ C)
    (a : ℕ → Profile G) (t : ℕ) :
    ∀ (l : List ι) (σ : ∀ i, PMF (G.Strategy i)), l.Nodup →
      (∀ changed, changed ∈ l → σ changed = G.empiricalMarginal a changed (t + 1)) →
      ∀ (who : ι) (b : G.Strategy who),
        |G.mixedPotentialPureGain Φ
            (l.foldl
              (fun σ changed =>
                Function.update σ changed (G.empiricalMarginal a changed (t + 2))) σ) who b -
          G.mixedPotentialPureGain Φ σ who b| ≤
          (l.length : ℝ) * ((1 / (t + 2 : ℝ)) * (4 * C)) := by
  intro l
  induction l with
  | nil =>
      intro σ _hnodup _hσ who b
      simp
  | cons j rest ih =>
      intro σ hnodup hσ who b
      have hrestN : rest.Nodup := List.Nodup.of_cons hnodup
      have hjnot : j ∉ rest := (List.nodup_cons.mp hnodup).1
      let stepErr : ℝ := (1 / (t + 2 : ℝ)) * (4 * C)
      let σ1 : ∀ i, PMF (G.Strategy i) :=
        Function.update σ j (G.empiricalMarginal a j (t + 2))
      have hσj : σ j = G.empiricalMarginal a j (t + 1) := hσ j (by simp)
      have hσrest1 :
          ∀ changed, changed ∈ rest → σ1 changed =
            G.empiricalMarginal a changed (t + 1) := by
        intro changed hchanged
        have hne : changed ≠ j := by
          intro h
          subst h
          exact hjnot hchanged
        simp [σ1, hne, hσ changed (by simp [hchanged])]
      have htail := ih σ1 hrestN hσrest1 who b
      have hone := G.mixedPotentialPureGain_update_empiricalMarginal_succ_abs_sub_le
        Φ hC a σ b t hσj
      have htri := abs_sub_le
        (G.mixedPotentialPureGain Φ
          (rest.foldl
            (fun σ changed =>
              Function.update σ changed (G.empiricalMarginal a changed (t + 2))) σ1) who b)
        (G.mixedPotentialPureGain Φ σ1 who b)
        (G.mixedPotentialPureGain Φ σ who b)
      calc
        |G.mixedPotentialPureGain Φ
            (rest.foldl
              (fun σ changed =>
                Function.update σ changed (G.empiricalMarginal a changed (t + 2))) σ1) who b -
          G.mixedPotentialPureGain Φ σ who b|
            ≤ |G.mixedPotentialPureGain Φ
                (rest.foldl
                  (fun σ changed =>
                    Function.update σ changed (G.empiricalMarginal a changed (t + 2))) σ1) who b -
              G.mixedPotentialPureGain Φ σ1 who b| +
                |G.mixedPotentialPureGain Φ σ1 who b -
                  G.mixedPotentialPureGain Φ σ who b| := htri
        _ ≤ (rest.length : ℝ) * stepErr + stepErr := add_le_add htail hone
        _ = ((j :: rest).length : ℝ) * stepErr := by
          simp [stepErr]
          ring

open Classical in
/-- Sweeping a nodup list of players and advancing each listed marginal by one
empirical step increases a bounded mixed potential by at least the first-order
sum of pure potential gains, up to a quadratic list-length error. -/
theorem mixedPotential_foldl_update_empiricalMarginal_succ_sub_ge
    [DecidableEq ι] (G : KernelGame ι) [∀ i, Finite (G.Strategy i)]
    (Φ : Profile G → ℝ) {C : ℝ} (hC : ∀ s : Profile G, |Φ s| ≤ C)
    (a : ℕ → Profile G) (t : ℕ) :
    ∀ (l : List ι) (σ : ∀ i, PMF (G.Strategy i)), l.Nodup →
      (∀ who, who ∈ l → σ who = G.empiricalMarginal a who (t + 1)) →
      (1 / (t + 2 : ℝ)) *
          (∑ who ∈ l.toFinset, G.mixedPotentialPureGain Φ σ who (a (t + 1) who)) -
        ((l.length : ℝ) * (l.length : ℝ)) *
          ((1 / (t + 2 : ℝ)) ^ 2 * (4 * C)) ≤
        G.mixedPotential Φ
          (l.foldl
            (fun σ who => Function.update σ who (G.empiricalMarginal a who (t + 2))) σ) -
          G.mixedPotential Φ σ := by
  intro l
  induction l with
  | nil =>
      intro σ _hnodup _hσ
      simp
  | cons j rest ih =>
      intro σ hnodup hσ
      have hrestN : rest.Nodup := List.Nodup.of_cons hnodup
      have hjnot : j ∉ rest := (List.nodup_cons.mp hnodup).1
      let step : ℝ := 1 / (t + 2 : ℝ)
      let err : ℝ := step ^ 2 * (4 * C)
      let σ1 : ∀ i, PMF (G.Strategy i) :=
        Function.update σ j (G.empiricalMarginal a j (t + 2))
      have hσj : σ j = G.empiricalMarginal a j (t + 1) := hσ j (by simp)
      have hσrest1 : ∀ who, who ∈ rest → σ1 who = G.empiricalMarginal a who (t + 1) := by
        intro who hwho
        have hne : who ≠ j := by
          intro h
          subst h
          exact hjnot hwho
        simp [σ1, hne, hσ who (by simp [hwho])]
      have ihrest0 := ih σ1 hrestN hσrest1
      have ihrest :
          step * (∑ who ∈ rest.toFinset,
            G.mixedPotentialPureGain Φ σ1 who (a (t + 1) who)) -
            ((rest.length : ℝ) * (rest.length : ℝ)) * err ≤
          G.mixedPotential Φ
            (rest.foldl
              (fun σ who => Function.update σ who (G.empiricalMarginal a who (t + 2))) σ1) -
            G.mixedPotential Φ σ1 := by
        simpa [step, err] using ihrest0
      have hstep_nonneg : 0 ≤ step := by positivity
      have hC_nonneg : 0 ≤ C := by
        have h := hC (a 0)
        exact (abs_nonneg _).trans h
      have herr_nonneg : 0 ≤ err := by
        dsimp [err]
        positivity
      have hgain_point : ∀ who ∈ rest.toFinset,
          G.mixedPotentialPureGain Φ σ who (a (t + 1) who) ≤
            G.mixedPotentialPureGain Φ σ1 who (a (t + 1) who) + step * (4 * C) := by
        intro who hwho_fin
        have hwho : who ∈ rest := by simpa using hwho_fin
        have hne_j_who : j ≠ who := by
          intro h
          subst h
          exact hjnot hwho
        have hd := G.mixedPotential_pureGain_update_empiricalMarginal_succ_abs_sub_le
          Φ hC a σ (a (t + 1) who) hne_j_who t hσj
        have hrewrite :
            ((G.mixedPotential Φ
                (Function.update (Function.update σ j
                  (G.empiricalMarginal a j (t + 2))) who
                  (PMF.pure (a (t + 1) who))) -
              G.mixedPotential Φ
                (Function.update σ j (G.empiricalMarginal a j (t + 2)))) -
            (G.mixedPotential Φ (Function.update σ who (PMF.pure (a (t + 1) who))) -
              G.mixedPotential Φ σ)) =
            G.mixedPotentialPureGain Φ σ1 who (a (t + 1) who) -
              G.mixedPotentialPureGain Φ σ who (a (t + 1) who) := by
          simp [mixedPotentialPureGain, σ1]
        rw [hrewrite] at hd
        have hle_lower := (abs_le.mp hd).1
        dsimp [step]
        linarith
      have hsum_le :
          (∑ who ∈ rest.toFinset, G.mixedPotentialPureGain Φ σ who (a (t + 1) who)) ≤
            (∑ who ∈ rest.toFinset, G.mixedPotentialPureGain Φ σ1 who (a (t + 1) who)) +
              (rest.length : ℝ) * (step * (4 * C)) := by
        calc
          (∑ who ∈ rest.toFinset, G.mixedPotentialPureGain Φ σ who (a (t + 1) who))
              ≤ ∑ who ∈ rest.toFinset,
                  (G.mixedPotentialPureGain Φ σ1 who (a (t + 1) who) + step * (4 * C)) := by
                exact Finset.sum_le_sum fun who hwho => hgain_point who hwho
          _ = (∑ who ∈ rest.toFinset, G.mixedPotentialPureGain Φ σ1 who (a (t + 1) who)) +
                (rest.toFinset.card : ℝ) * (step * (4 * C)) := by
                rw [Finset.sum_add_distrib]
                simp [Finset.sum_const, nsmul_eq_mul]
          _ = (∑ who ∈ rest.toFinset, G.mixedPotentialPureGain Φ σ1 who (a (t + 1) who)) +
                (rest.length : ℝ) * (step * (4 * C)) := by
                rw [List.toFinset_card_of_nodup hrestN]
      have hgain_cmp :
          step * (∑ who ∈ rest.toFinset, G.mixedPotentialPureGain Φ σ who (a (t + 1) who)) -
            (rest.length : ℝ) * err ≤
          step * (∑ who ∈ rest.toFinset, G.mixedPotentialPureGain Φ σ1 who (a (t + 1) who)) := by
        dsimp [err]
        nlinarith [mul_le_mul_of_nonneg_left hsum_le hstep_nonneg]
      have hinc :
          G.mixedPotential Φ σ1 - G.mixedPotential Φ σ =
            step * G.mixedPotentialPureGain Φ σ j (a (t + 1) j) := by
        simpa [σ1, step] using
          (G.mixedPotential_update_empiricalMarginal_succ_sub_of_eq Φ a σ j t hσj)
      have hsum_cons :
          (∑ who ∈ (j :: rest).toFinset,
              G.mixedPotentialPureGain Φ σ who (a (t + 1) who)) =
            G.mixedPotentialPureGain Φ σ j (a (t + 1) j) +
              ∑ who ∈ rest.toFinset,
                G.mixedPotentialPureGain Φ σ who (a (t + 1) who) := by
        simp [hjnot]
      have hfold_cons :
          ((j :: rest).foldl
            (fun σ who => Function.update σ who (G.empiricalMarginal a who (t + 2))) σ) =
          rest.foldl
            (fun σ who => Function.update σ who (G.empiricalMarginal a who (t + 2))) σ1 := by
        rfl
      rw [hfold_cons, hsum_cons]
      have htail_total :
          step * (∑ who ∈ rest.toFinset,
              G.mixedPotentialPureGain Φ σ who (a (t + 1) who)) -
            (((rest.length : ℝ) * (rest.length : ℝ)) * err + (rest.length : ℝ) * err) ≤
          G.mixedPotential Φ
            (rest.foldl
              (fun σ who => Function.update σ who (G.empiricalMarginal a who (t + 2))) σ1) -
            G.mixedPotential Φ σ1 := by
        nlinarith [hgain_cmp, ihrest]
      have hlen_err :
          (((rest.length : ℝ) * (rest.length : ℝ)) * err + (rest.length : ℝ) * err) ≤
            (((j :: rest).length : ℝ) * ((j :: rest).length : ℝ)) * err := by
        have hn : (0 : ℝ) ≤ rest.length := by positivity
        simp only [List.length_cons]
        push_cast
        nlinarith
      calc
        step * (G.mixedPotentialPureGain Φ σ j (a (t + 1) j) +
              ∑ who ∈ rest.toFinset,
                G.mixedPotentialPureGain Φ σ who (a (t + 1) who)) -
            (((j :: rest).length : ℝ) * ((j :: rest).length : ℝ)) * err
            ≤ (G.mixedPotential Φ σ1 - G.mixedPotential Φ σ) +
                (G.mixedPotential Φ
                  (rest.foldl
                    (fun σ who => Function.update σ who (G.empiricalMarginal a who (t + 2))) σ1) -
                  G.mixedPotential Φ σ1) := by
              nlinarith [hinc, htail_total, hlen_err]
        _ = G.mixedPotential Φ
              (rest.foldl
                (fun σ who => Function.update σ who (G.empiricalMarginal a who (t + 2))) σ1) -
            G.mixedPotential Φ σ := by ring

open Classical in
/-- Sweeping through all players and replacing each marginal by its successor
empirical marginal turns `belief (t+1)` into `belief (t+2)`. -/
theorem foldl_update_empiricalMarginal_succ_eq_belief_succ
    [DecidableEq ι] (G : KernelGame ι) (a : ℕ → Profile G) (t : ℕ) :
    (Finset.univ.toList.foldl
        (fun σ who => Function.update σ who (G.empiricalMarginal a who (t + 2)))
        (G.belief a (t + 1))) =
      G.belief a (t + 2) := by
  have hfold := Math.PMFProduct.foldl_update_family_eq_of_nodup
    (l := Finset.univ.toList)
    (hNodup := Finset.univ.nodup_toList)
    (σ := G.belief a (t + 1))
    (τ := fun who => G.empiricalMarginal a who (t + 2))
  rw [hfold]
  ext who
  simp [belief]

open Classical in
/-- Consecutive empirical beliefs change any fixed pure potential gain by
`O(1/t)`. -/
theorem mixedPotentialPureGain_belief_succ_abs_sub_le
    [DecidableEq ι] (G : KernelGame ι) [∀ i, Finite (G.Strategy i)]
    (Φ : Profile G → ℝ) {C : ℝ} (hC : ∀ s : Profile G, |Φ s| ≤ C)
    (a : ℕ → Profile G) (who : ι) (b : G.Strategy who) (t : ℕ) :
    |G.mixedPotentialPureGain Φ (G.belief a (t + 2)) who b -
      G.mixedPotentialPureGain Φ (G.belief a (t + 1)) who b| ≤
      (Fintype.card ι : ℝ) * ((1 / (t + 2 : ℝ)) * (4 * C)) := by
  have hfold := G.mixedPotentialPureGain_foldl_update_empiricalMarginal_succ_abs_sub_le
    Φ hC a t (Finset.univ.toList : List ι) (G.belief a (t + 1))
    (Finset.univ.nodup_toList) (by intro changed _hchanged; simp [belief]) who b
  rw [G.foldl_update_empiricalMarginal_succ_eq_belief_succ a t] at hfold
  have hlen_nat : (Finset.univ.toList : List ι).length = Fintype.card ι := by
    rw [← List.toFinset_card_of_nodup
      (Finset.univ.nodup_toList : (Finset.univ.toList : List ι).Nodup)]
    simp
  have hlen : ((Finset.univ.toList : List ι).length : ℝ) = (Fintype.card ι : ℝ) := by
    exact_mod_cast hlen_nat
  simpa [hlen] using hfold

open Classical in
/-- In an exact-potential game, consecutive empirical beliefs change any fixed
pure mixed gain by `O(1/t)`. -/
theorem IsExactPotential.mixedGain_belief_succ_abs_sub_le
    [DecidableEq ι] {G : KernelGame ι} [∀ i, Finite (G.Strategy i)] [Finite G.Outcome]
    {Φ : Profile G → ℝ} (hΦ : G.IsExactPotential Φ)
    {C : ℝ} (hC : ∀ s : Profile G, |Φ s| ≤ C)
    (a : ℕ → Profile G) (who : ι) (b : G.Strategy who) (t : ℕ) :
    |G.mixedGain (G.belief a (t + 2)) who b -
      G.mixedGain (G.belief a (t + 1)) who b| ≤
      (Fintype.card ι : ℝ) * ((1 / (t + 2 : ℝ)) * (4 * C)) := by
  have h := G.mixedPotentialPureGain_belief_succ_abs_sub_le Φ hC a who b t
  rw [hΦ.mixedPotentialPureGain_eq_mixedGain (G.belief a (t + 2)) who b,
    hΦ.mixedPotentialPureGain_eq_mixedGain (G.belief a (t + 1)) who b] at h
  exact h

open Classical in
/-- Consecutive aggregate played gains along fictitious play in a bounded
exact-potential game differ by `O(1/t)`. -/
theorem IsExactPotential.fictitiousPlayPlayedGain_succ_abs_sub_le
    [DecidableEq ι] {G : KernelGame ι} [∀ i, Finite (G.Strategy i)] [Finite G.Outcome]
    {Φ : Profile G → ℝ} (hΦ : G.IsExactPotential Φ)
    {C : ℝ} (hC : ∀ s : Profile G, |Φ s| ≤ C)
    {a : ℕ → Profile G} (hfp : G.IsFictitiousPlay a) (t : ℕ) :
    |G.fictitiousPlayPlayedGain a (t + 1) - G.fictitiousPlayPlayedGain a t| ≤
      ((Fintype.card ι : ℝ) * (Fintype.card ι : ℝ)) *
        ((1 / (t + 2 : ℝ)) * (4 * C)) := by
  let L : ℝ := (Fintype.card ι : ℝ) * ((1 / (t + 2 : ℝ)) * (4 * C))
  have hpoint : ∀ who : ι,
      |G.mixedGain (G.belief a (t + 2)) who (a (t + 2) who) -
        G.mixedGain (G.belief a (t + 1)) who (a (t + 1) who)| ≤ L := by
    intro who
    have hnew_bound := hΦ.mixedGain_belief_succ_abs_sub_le hC a who (a (t + 2) who) t
    have hold_bound := hΦ.mixedGain_belief_succ_abs_sub_le hC a who (a (t + 1) who) t
    have hbest_old := hfp t who (a (t + 2) who)
    have hbest_new := hfp (t + 1) who (a (t + 1) who)
    have hold_comp :
        G.mixedGain (G.belief a (t + 1)) who (a (t + 2) who) ≤
          G.mixedGain (G.belief a (t + 1)) who (a (t + 1) who) := by
      rw [mixedGain, mixedGain]
      linarith
    have hnew_comp :
        G.mixedGain (G.belief a (t + 2)) who (a (t + 1) who) ≤
          G.mixedGain (G.belief a (t + 2)) who (a (t + 2) who) := by
      rw [mixedGain, mixedGain]
      linarith
    refine abs_le.mpr ⟨?_, ?_⟩
    · have hlower := (abs_le.mp hold_bound).1
      linarith
    · have hupper := (abs_le.mp hnew_bound).2
      linarith
  rw [fictitiousPlayPlayedGain, fictitiousPlayPlayedGain]
  have hsum_sub :
      (∑ who : ι, G.mixedGain (G.belief a (t + 2)) who (a (t + 2) who)) -
        (∑ who : ι, G.mixedGain (G.belief a (t + 1)) who (a (t + 1) who)) =
      ∑ who : ι,
        (G.mixedGain (G.belief a (t + 2)) who (a (t + 2) who) -
          G.mixedGain (G.belief a (t + 1)) who (a (t + 1) who)) := by
    rw [Finset.sum_sub_distrib]
  rw [hsum_sub]
  calc
    |∑ who : ι,
        (G.mixedGain (G.belief a (t + 2)) who (a (t + 2) who) -
          G.mixedGain (G.belief a (t + 1)) who (a (t + 1) who))|
        ≤ ∑ who : ι,
            |G.mixedGain (G.belief a (t + 2)) who (a (t + 2) who) -
              G.mixedGain (G.belief a (t + 1)) who (a (t + 1) who)| :=
          Finset.abs_sum_le_sum_abs _ _
    _ ≤ ∑ _who : ι, L := Finset.sum_le_sum fun who _ => hpoint who
    _ = (Fintype.card ι : ℝ) * L := by simp [Finset.sum_const, nsmul_eq_mul]
    _ = ((Fintype.card ι : ℝ) * (Fintype.card ι : ℝ)) *
        ((1 / (t + 2 : ℝ)) * (4 * C)) := by
          dsimp [L]
          ring

open Classical in
/-- Lyapunov lower bound for one fictitious-play empirical update in an exact
potential game. The all-player potential increment dominates the played gain
up to a quadratic Cesàro error. -/
theorem IsExactPotential.mixedPotential_belief_succ_sub_ge
    [DecidableEq ι] {G : KernelGame ι} [∀ i, Finite (G.Strategy i)] [Finite G.Outcome]
    {Φ : Profile G → ℝ} (hΦ : G.IsExactPotential Φ)
    {C : ℝ} (hC : ∀ s : Profile G, |Φ s| ≤ C)
    (a : ℕ → Profile G) (t : ℕ) :
    (1 / (t + 2 : ℝ)) * G.fictitiousPlayPlayedGain a t -
        (((Fintype.card ι : ℝ) * (Fintype.card ι : ℝ)) *
          ((1 / (t + 2 : ℝ)) ^ 2 * (4 * C))) ≤
      G.mixedPotential Φ (G.belief a (t + 2)) -
        G.mixedPotential Φ (G.belief a (t + 1)) := by
  have hsweep := G.mixedPotential_foldl_update_empiricalMarginal_succ_sub_ge
    Φ hC a t (Finset.univ.toList : List ι) (G.belief a (t + 1))
    (Finset.univ.nodup_toList) (by intro who _hwho; simp [belief])
  rw [G.foldl_update_empiricalMarginal_succ_eq_belief_succ a t] at hsweep
  have hsum :
      (∑ who ∈ (Finset.univ.toList : List ι).toFinset,
        G.mixedPotentialPureGain Φ (G.belief a (t + 1)) who (a (t + 1) who)) =
      G.fictitiousPlayPlayedGain a t := by
    rw [fictitiousPlayPlayedGain]
    apply Finset.sum_congr
    · ext who
      simp
    · intro who _hwho
      exact hΦ.mixedPotentialPureGain_eq_mixedGain (G.belief a (t + 1)) who
        (a (t + 1) who)
  have hlen_nat : (Finset.univ.toList : List ι).length = Fintype.card ι := by
    rw [← List.toFinset_card_of_nodup
      (Finset.univ.nodup_toList : (Finset.univ.toList : List ι).Nodup)]
    simp
  have hlen : ((Finset.univ.toList : List ι).length : ℝ) = (Fintype.card ι : ℝ) := by
    exact_mod_cast hlen_nat
  rw [hsum, hlen] at hsweep
  simpa using hsweep

open Classical in
/-- The played-gain sequence has finite harmonic energy along fictitious play in
an exact-potential game. This is the summability consequence of the Lyapunov
bound and boundedness of the mixed potential. -/
theorem IsExactPotential.summable_one_div_mul_fictitiousPlayPlayedGain
    [DecidableEq ι] {G : KernelGame ι} [∀ i, Finite (G.Strategy i)] [Finite G.Outcome]
    {Φ : Profile G → ℝ} (hΦ : G.IsExactPotential Φ)
    {C : ℝ} (hC : ∀ s : Profile G, |Φ s| ≤ C)
    {a : ℕ → Profile G} (hfp : G.IsFictitiousPlay a) :
    Summable (fun t : ℕ => (1 / ((t : ℝ) + 2)) * G.fictitiousPlayPlayedGain a t) := by
  let V : ℕ → ℝ := fun n => G.mixedPotential Φ (G.belief a (n + 1))
  let B : ℝ := ((Fintype.card ι : ℝ) * (Fintype.card ι : ℝ)) * (4 * C)
  let β : ℕ → ℝ := fun t => B * ((1 / ((t : ℝ) + 2)) ^ 2)
  have hC_nonneg : 0 ≤ C := by
    have h := hC (a 0)
    exact (abs_nonneg _).trans h
  have hβ_nonneg : ∀ t : ℕ, 0 ≤ β t := by
    intro t
    dsimp [β, B]
    positivity
  have hβ_summable : Summable β := by
    have hs0 : Summable (fun n : ℕ => 1 / (n : ℝ) ^ 2) := by
      exact (Real.summable_one_div_nat_pow (p := 2)).mpr (by norm_num)
    have hs2 : Summable (fun t : ℕ => 1 / (((t : ℝ) + 2) ^ 2)) := by
      simpa [Nat.cast_add] using (summable_nat_add_iff 2).mpr hs0
    have hs3 : Summable (fun t : ℕ => (1 / ((t : ℝ) + 2)) ^ 2) := by
      simpa [one_div, inv_pow, Nat.cast_add] using hs2
    simpa [β] using hs3.mul_left B
  have hterm_nonneg :
      ∀ t : ℕ, 0 ≤ (1 / ((t : ℝ) + 2)) * G.fictitiousPlayPlayedGain a t := by
    intro t
    exact mul_nonneg (by positivity) (hfp.fictitiousPlayPlayedGain_nonneg t)
  have htel : ∀ n : ℕ, (∑ t ∈ Finset.range n, (V (t + 1) - V t)) = V n - V 0 := by
    intro n
    induction n with
    | zero => simp
    | succ n ih =>
        rw [Finset.sum_range_succ, ih]
        ring
  have hpartial : ∀ n : ℕ,
      (∑ t ∈ Finset.range n, (1 / ((t : ℝ) + 2)) * G.fictitiousPlayPlayedGain a t) ≤
        2 * C + ∑' t, β t := by
    intro n
    have hpoint : ∀ t ∈ Finset.range n,
        (1 / ((t : ℝ) + 2)) * G.fictitiousPlayPlayedGain a t ≤
          (V (t + 1) - V t) + β t := by
      intro t _ht
      have hlyap := hΦ.mixedPotential_belief_succ_sub_ge hC a t
      dsimp [V, β, B]
      linarith
    calc
      (∑ t ∈ Finset.range n, (1 / ((t : ℝ) + 2)) * G.fictitiousPlayPlayedGain a t)
          ≤ ∑ t ∈ Finset.range n, ((V (t + 1) - V t) + β t) :=
            Finset.sum_le_sum hpoint
      _ = (∑ t ∈ Finset.range n, (V (t + 1) - V t)) +
            ∑ t ∈ Finset.range n, β t := by
            rw [Finset.sum_add_distrib]
      _ = (V n - V 0) + ∑ t ∈ Finset.range n, β t := by rw [htel]
      _ ≤ 2 * C + ∑' t, β t := by
        have hVn := G.mixedPotential_abs_le_of_abs_bound Φ hC (G.belief a (n + 1))
        have hV0 := G.mixedPotential_abs_le_of_abs_bound Φ hC (G.belief a (0 + 1))
        have hVdiff : V n - V 0 ≤ 2 * C := by
          dsimp [V] at hVn hV0 ⊢
          have hV0_lower := (abs_le.mp hV0).1
          have hVn_upper := (abs_le.mp hVn).2
          linarith
        have hβsum : ∑ t ∈ Finset.range n, β t ≤ ∑' t, β t := by
          exact hβ_summable.sum_le_tsum (Finset.range n) (fun t _ => hβ_nonneg t)
        linarith
  exact summable_of_sum_range_le hterm_nonneg hpartial

open Filter in
/-- If `∑ (x n)/(n+2)` converges absolutely, then `x n` is arbitrarily small
along arbitrarily late indices. -/
theorem frequently_lt_of_summable_one_div_mul
    {x : ℕ → ℝ}
    (hs : Summable (fun n : ℕ => (1 / ((n : ℝ) + 2)) * x n))
    {ε : ℝ} (hε : 0 < ε) :
    ∃ᶠ n in atTop, x n < ε := by
  let w : ℕ → ℝ := fun n => 1 / ((n : ℝ) + 2)
  let y : ℕ → ℝ := fun n => w n * x n
  have hs_y : Summable y := by
    simpa [y, w, mul_comm] using hs
  by_contra hfreq
  rw [not_frequently] at hfreq
  have hev : ∀ᶠ n in atTop, ε ≤ x n := by
    filter_upwards [hfreq] with n hn
    exact le_of_not_gt hn
  have hs_eps_w : Summable (fun n : ℕ => ε * w n) := by
    refine hs_y.of_norm_bounded_eventually_nat ?_
    filter_upwards [hev] with n hn
    have hw_nonneg : 0 ≤ w n := by
      dsimp [w]
      positivity
    have hle : ε * w n ≤ y n := by
      calc
        ε * w n = w n * ε := by ring
        _ ≤ w n * x n := mul_le_mul_of_nonneg_left hn hw_nonneg
        _ = y n := by rfl
    rw [Real.norm_of_nonneg (mul_nonneg hε.le hw_nonneg)]
    exact hle
  have hs_w : Summable w := by
    have hscaled : Summable (fun n : ℕ => ε⁻¹ * (ε * w n)) :=
      hs_eps_w.mul_left ε⁻¹
    refine hscaled.congr ?_
    intro n
    calc
      ε⁻¹ * (ε * w n) = (ε⁻¹ * ε) * w n := by ring
      _ = 1 * w n := by rw [inv_mul_cancel₀ hε.ne']
      _ = w n := by ring
  have hs_tail : Summable (fun n : ℕ => 1 / ((n : ℝ) + 2)) := by
    simpa [w] using hs_w
  have hs_harm : Summable (fun n : ℕ => 1 / (n : ℝ)) := by
    have hs_shift : Summable (fun n : ℕ => 1 / ((n + 2 : ℕ) : ℝ)) := by
      simpa [Nat.cast_add] using hs_tail
    exact (summable_nat_add_iff 2).mp hs_shift
  exact Real.not_summable_one_div_natCast hs_harm

open Filter in
/-- A Tauberian estimate for nonnegative sequences with harmonic energy:
if `∑ x n/(n+2)` converges and adjacent terms change by `O(1/(n+2))`,
then `x n → 0`. -/
theorem tendsto_zero_of_summable_one_div_mul_of_succ_abs_sub_le
    {x : ℕ → ℝ}
    (hx_nonneg : ∀ n, 0 ≤ x n)
    (hs : Summable (fun n : ℕ => (1 / ((n : ℝ) + 2)) * x n))
    {K : ℝ} (hK_nonneg : 0 ≤ K)
    (hslow : ∀ n : ℕ, |x (n + 1) - x n| ≤ K / ((n : ℝ) + 2)) :
    Tendsto x atTop (nhds 0) := by
  let y : ℕ → ℝ := fun n => (1 / ((n : ℝ) + 2)) * x n
  have hs_y : Summable y := by simpa [y] using hs
  have hy_nonneg : ∀ n, 0 ≤ y n := by
    intro n
    dsimp [y]
    exact mul_nonneg (by positivity) (hx_nonneg n)
  rw [tendsto_order]
  constructor
  · intro a' ha'
    filter_upwards with n
    exact lt_of_lt_of_le ha' (hx_nonneg n)
  · intro ε hε
    have hden_base : 0 < ε / (4 * (K + 1)) := by positivity
    obtain ⟨q0, hq0⟩ := exists_nat_one_div_lt hden_base
    let q : ℕ := q0 + 1
    have hq_pos_nat : 0 < q := by dsimp [q]; omega
    have hq_pos : 0 < (q : ℝ) := by exact_mod_cast hq_pos_nat
    have hKp_pos : 0 < K + 1 := by linarith
    have hq_small : K / (q : ℝ) < ε / 4 := by
      have hq0' : 1 / (q : ℝ) < ε / (4 * (K + 1)) := by
        simpa [q, Nat.cast_add, add_comm] using hq0
      calc
        K / (q : ℝ) ≤ (K + 1) / (q : ℝ) := by
          exact div_le_div_of_nonneg_right (by linarith) hq_pos.le
        _ = (K + 1) * (1 / (q : ℝ)) := by ring
        _ < (K + 1) * (ε / (4 * (K + 1))) := by
          exact mul_lt_mul_of_pos_left hq0' hKp_pos
        _ = ε / 4 := by
          field_simp [hKp_pos.ne']
    let δ : ℝ := ε / (16 * (q : ℝ))
    have hδ_pos : 0 < δ := by dsimp [δ]; positivity
    have htail_tendsto : Tendsto (fun n : ℕ => ∑' k : ℕ, y (k + n)) atTop (nhds 0) :=
      tendsto_sum_nat_add y
    have htail_event : ∀ᶠ n in atTop, (∑' k : ℕ, y (k + n)) < δ :=
      htail_tendsto.eventually (eventually_lt_nhds hδ_pos)
    have hlarge_event : ∀ᶠ n in atTop, 2 * q ≤ n + 2 := by
      exact eventually_atTop.2 ⟨2 * q, fun n hn => by omega⟩
    filter_upwards [htail_event, hlarge_event] with n htail hlarge
    by_contra hnlt
    have hxn : ε ≤ x n := le_of_not_gt hnlt
    let N : ℕ := n + 2
    let L : ℕ := N / q
    have hN_pos_nat : 0 < N := by dsimp [N]; omega
    have hN_pos : 0 < (N : ℝ) := by exact_mod_cast hN_pos_nat
    have hlargeN : 2 * q ≤ N := by simpa [N] using hlarge
    have hL_upper : ((L : ℕ) : ℝ) ≤ (N : ℝ) / (q : ℝ) := by
      dsimp [L]
      have hmul_nat : N / q * q ≤ N := Nat.div_mul_le_self N q
      have hmul_real : ((N / q : ℕ) : ℝ) * (q : ℝ) ≤ (N : ℝ) := by
        exact_mod_cast hmul_nat
      rw [le_div_iff₀ hq_pos]
      simpa [mul_comm] using hmul_real
    have hL_lower : (N : ℝ) / (2 * (q : ℝ)) ≤ ((L : ℕ) : ℝ) := by
      dsimp [L]
      have hprod_ge : N - q ≤ N / q * q := by
        have hdiv : q * (N / q) + N % q = N := Nat.div_add_mod N q
        rw [Nat.mul_comm] at hdiv
        have hmod : N % q < q := Nat.mod_lt N hq_pos_nat
        omega
      have hhalf : N ≤ 2 * (N - q) := by omega
      have hmul_nat : N ≤ 2 * (N / q * q) := by omega
      have hmul_real : (N : ℝ) ≤ 2 * (((N / q : ℕ) : ℝ) * (q : ℝ)) := by
        exact_mod_cast hmul_nat
      have hden_pos : 0 < (2 : ℝ) * (q : ℝ) := by positivity
      calc
        (N : ℝ) / (2 * (q : ℝ)) ≤
            (2 * (((N / q : ℕ) : ℝ) * (q : ℝ))) / (2 * (q : ℝ)) := by
          exact div_le_div_of_nonneg_right hmul_real hden_pos.le
        _ = ((N / q : ℕ) : ℝ) := by
          field_simp [hq_pos.ne']
    have hx_lower_block : ∀ j : ℕ, j ≤ L → x (n + j) ≥ ε / 2 := by
      intro j hjL
      have hdrop : x n - ((j : ℝ) * (K / (N : ℝ))) ≤ x (n + j) := by
        induction j with
        | zero => simp
        | succ j ih =>
            have hjL' : j ≤ L := le_trans (Nat.le_succ j) hjL
            have hprev := ih hjL'
            have hstep_abs := hslow (n + j)
            have hstep_lower :
                x (n + j) - K / ((n + j : ℝ) + 2) ≤ x (n + (j + 1)) := by
              have hlow := (abs_le.mp hstep_abs).1
              rw [show n + (j + 1) = n + j + 1 by omega]
              norm_num [Nat.cast_add] at hlow ⊢
              linarith
            have hden_le : K / ((n + j : ℝ) + 2) ≤ K / (N : ℝ) := by
              have hden : (N : ℝ) ≤ (n + j : ℝ) + 2 := by
                dsimp [N]
                norm_num
              exact div_le_div_of_nonneg_left hK_nonneg hN_pos hden
            have : x n - (((j + 1 : ℕ) : ℝ) * (K / (N : ℝ))) ≤
                x (n + (j + 1)) := by
              calc
                x n - (((j + 1 : ℕ) : ℝ) * (K / (N : ℝ))) =
                    (x n - ((j : ℝ) * (K / (N : ℝ)))) - K / (N : ℝ) := by
                  norm_num
                  ring
                _ ≤ x (n + j) - K / (N : ℝ) := by linarith
                _ ≤ x (n + j) - K / ((n + j : ℝ) + 2) := by linarith
                _ ≤ x (n + (j + 1)) := hstep_lower
            simpa using this
      have hj_bound : (j : ℝ) * (K / (N : ℝ)) ≤ K / (q : ℝ) := by
        have hj_real : (j : ℝ) ≤ (L : ℝ) := by exact_mod_cast hjL
        have hLj : (j : ℝ) ≤ (N : ℝ) / (q : ℝ) := hj_real.trans hL_upper
        have hKN_nonneg : 0 ≤ K / (N : ℝ) := div_nonneg hK_nonneg hN_pos.le
        calc
          (j : ℝ) * (K / (N : ℝ)) ≤ ((N : ℝ) / (q : ℝ)) * (K / (N : ℝ)) :=
            mul_le_mul_of_nonneg_right hLj hKN_nonneg
          _ = K / (q : ℝ) := by
            field_simp [hN_pos.ne', hq_pos.ne']
      linarith
    have hblock_point : ∀ k ∈ Finset.range L, ε / (4 * (N : ℝ)) ≤ y (n + k) := by
      intro k hk
      have hkL : k ≤ L := le_of_lt (Finset.mem_range.mp hk)
      have hxk : ε / 2 ≤ x (n + k) := hx_lower_block k hkL
      have hweight : 1 / (((n + k : ℕ) : ℝ) + 2) ≥ 1 / (2 * (N : ℝ)) := by
        have hk_le_N : k ≤ N := by
          have hL_le_N : L ≤ N := Nat.div_le_self N q
          exact hkL.trans hL_le_N
        have hden_le : ((n + k : ℕ) : ℝ) + 2 ≤ 2 * (N : ℝ) := by
          dsimp [N]
          exact_mod_cast (by omega : n + k + 2 ≤ 2 * (n + 2))
        have hden_pos : 0 < ((n + k : ℕ) : ℝ) + 2 := by positivity
        exact one_div_le_one_div_of_le hden_pos hden_le
      dsimp [y]
      calc
        ε / (4 * (N : ℝ)) = (1 / (2 * (N : ℝ))) * (ε / 2) := by ring
        _ ≤ (1 / (((n + k : ℕ) : ℝ) + 2)) * x (n + k) := by
          exact mul_le_mul hweight hxk (by positivity) (by positivity)
    have hblock_sum_lower : ε / (8 * (q : ℝ)) ≤ ∑ k ∈ Finset.range L, y (n + k) := by
      have hconst_nonneg : 0 ≤ ε / (4 * (N : ℝ)) := by positivity
      calc
        ε / (8 * (q : ℝ)) =
            ((N : ℝ) / (2 * (q : ℝ))) * (ε / (4 * (N : ℝ))) := by
          field_simp [hN_pos.ne', hq_pos.ne']
          ring
        _ ≤ (L : ℝ) * (ε / (4 * (N : ℝ))) :=
          mul_le_mul_of_nonneg_right hL_lower hconst_nonneg
        _ = ∑ k ∈ Finset.range L, ε / (4 * (N : ℝ)) := by
          simp [Finset.sum_const, nsmul_eq_mul]
        _ ≤ ∑ k ∈ Finset.range L, y (n + k) :=
          Finset.sum_le_sum hblock_point
    have htail' : (∑' k : ℕ, y (n + k)) < δ := by
      simpa [Nat.add_comm] using htail
    have htail_summable : Summable (fun k : ℕ => y (n + k)) := by
      simpa [Function.comp_def] using
        hs_y.comp_injective (i := fun k => n + k) (add_right_injective n)
    have hfinite_le_tail : ∑ k ∈ Finset.range L, y (n + k) ≤ ∑' k : ℕ, y (n + k) := by
      exact htail_summable.sum_le_tsum (Finset.range L) (fun k _hk => hy_nonneg (n + k))
    have hcontr : ε / (8 * (q : ℝ)) < ε / (16 * (q : ℝ)) := by
      exact lt_of_le_of_lt (hblock_sum_lower.trans hfinite_le_tail) htail'
    have hrewrite : ε / (8 * (q : ℝ)) = 2 * (ε / (16 * (q : ℝ))) := by
      field_simp [hq_pos.ne']
      ring
    rw [hrewrite] at hcontr
    have hpos : 0 < ε / (16 * (q : ℝ)) := by positivity
    nlinarith

open Filter in
/-- Along fictitious play in a bounded exact-potential game, the aggregate
played gain is arbitrarily small along arbitrarily late rounds. -/
theorem IsExactPotential.frequently_fictitiousPlayPlayedGain_lt
    [DecidableEq ι] {G : KernelGame ι} [∀ i, Finite (G.Strategy i)] [Finite G.Outcome]
    {Φ : Profile G → ℝ} (hΦ : G.IsExactPotential Φ)
    {C : ℝ} (hC : ∀ s : Profile G, |Φ s| ≤ C)
    {a : ℕ → Profile G} (hfp : G.IsFictitiousPlay a)
    {ε : ℝ} (hε : 0 < ε) :
    ∃ᶠ t in atTop, G.fictitiousPlayPlayedGain a t < ε :=
  frequently_lt_of_summable_one_div_mul
    (hΦ.summable_one_div_mul_fictitiousPlayPlayedGain hC hfp) hε

open Filter in
open Classical in
/-- Along fictitious play in a bounded exact-potential game, the aggregate
played gain tends to zero. -/
theorem IsExactPotential.fictitiousPlayPlayedGain_tendsto_zero
    [DecidableEq ι] {G : KernelGame ι} [∀ i, Finite (G.Strategy i)] [Finite G.Outcome]
    {Φ : Profile G → ℝ} (hΦ : G.IsExactPotential Φ)
    {C : ℝ} (hC : ∀ s : Profile G, |Φ s| ≤ C)
    {a : ℕ → Profile G} (hfp : G.IsFictitiousPlay a) :
    Tendsto (fun t : ℕ => G.fictitiousPlayPlayedGain a t) atTop (nhds 0) := by
  let K : ℝ := ((Fintype.card ι : ℝ) * (Fintype.card ι : ℝ)) * (4 * C)
  have hC_nonneg : 0 ≤ C := by
    have h := hC (a 0)
    exact (abs_nonneg _).trans h
  refine tendsto_zero_of_summable_one_div_mul_of_succ_abs_sub_le
    (fun t => hfp.fictitiousPlayPlayedGain_nonneg t)
    (hΦ.summable_one_div_mul_fictitiousPlayPlayedGain hC hfp)
    (K := K) ?_ ?_
  · dsimp [K]
    positivity
  · intro t
    have h := hΦ.fictitiousPlayPlayedGain_succ_abs_sub_le hC hfp t
    dsimp [K]
    convert h using 1
    ring_nf

open Classical in
/-- The strategy-cardinality-weighted played gain is nonnegative along
fictitious play. -/
theorem IsFictitiousPlay.fictitiousPlayWeightedPlayedGain_nonneg
    [DecidableEq ι] {G : KernelGame ι} [∀ i, Fintype (G.Strategy i)] [Finite G.Outcome]
    {a : ℕ → Profile G} (hfp : G.IsFictitiousPlay a) (t : ℕ) :
    0 ≤ G.fictitiousPlayWeightedPlayedGain a t := by
  rw [fictitiousPlayWeightedPlayedGain]
  exact Finset.sum_nonneg fun who _ =>
    mul_nonneg (Nat.cast_nonneg _) (hfp.playedGain_nonneg t who)

open Classical in
/-- The weighted played gain is bounded by a fixed strategy-cardinality
constant times the unweighted aggregate played gain. -/
theorem IsFictitiousPlay.fictitiousPlayWeightedPlayedGain_le_cardSum_mul_playedGain
    [DecidableEq ι] {G : KernelGame ι} [∀ i, Fintype (G.Strategy i)] [Finite G.Outcome]
    {a : ℕ → Profile G} (hfp : G.IsFictitiousPlay a) (t : ℕ) :
    G.fictitiousPlayWeightedPlayedGain a t ≤
      (∑ who : ι, (Fintype.card (G.Strategy who) : ℝ)) *
        G.fictitiousPlayPlayedGain a t := by
  let S : ℝ := ∑ who : ι, (Fintype.card (G.Strategy who) : ℝ)
  have hcard_le : ∀ who : ι, (Fintype.card (G.Strategy who) : ℝ) ≤ S := by
    intro who
    dsimp [S]
    exact Finset.single_le_sum
      (fun j _ => Nat.cast_nonneg (Fintype.card (G.Strategy j))) (Finset.mem_univ who)
  rw [fictitiousPlayWeightedPlayedGain, fictitiousPlayPlayedGain]
  calc
    (∑ who : ι, (Fintype.card (G.Strategy who) : ℝ) *
        G.mixedGain (G.belief a (t + 1)) who (a (t + 1) who))
        ≤ ∑ who : ι,
            S * G.mixedGain (G.belief a (t + 1)) who (a (t + 1) who) := by
          refine Finset.sum_le_sum fun who _ => ?_
          exact mul_le_mul_of_nonneg_right (hcard_le who) (hfp.playedGain_nonneg t who)
    _ = S * ∑ who : ι, G.mixedGain (G.belief a (t + 1)) who (a (t + 1) who) := by
          rw [Finset.mul_sum]

open Filter in
open Classical in
/-- Along fictitious play in a bounded exact-potential game, the weighted
played gain tends to zero. -/
theorem IsExactPotential.fictitiousPlayWeightedPlayedGain_tendsto_zero
    [DecidableEq ι] {G : KernelGame ι} [∀ i, Fintype (G.Strategy i)] [Finite G.Outcome]
    {Φ : Profile G → ℝ} (hΦ : G.IsExactPotential Φ)
    {C : ℝ} (hC : ∀ s : Profile G, |Φ s| ≤ C)
    {a : ℕ → Profile G} (hfp : G.IsFictitiousPlay a) :
    Tendsto (fun t : ℕ => G.fictitiousPlayWeightedPlayedGain a t) atTop (nhds 0) := by
  let S : ℝ := ∑ who : ι, (Fintype.card (G.Strategy who) : ℝ)
  have hplayed : Tendsto (fun t : ℕ => G.fictitiousPlayPlayedGain a t) atTop (nhds 0) :=
    hΦ.fictitiousPlayPlayedGain_tendsto_zero hC hfp
  have hbound : ∀ t : ℕ,
      G.fictitiousPlayWeightedPlayedGain a t ≤ S * G.fictitiousPlayPlayedGain a t := by
    intro t
    simpa [S] using hfp.fictitiousPlayWeightedPlayedGain_le_cardSum_mul_playedGain t
  have hSplayed : Tendsto (fun t : ℕ => S * G.fictitiousPlayPlayedGain a t) atTop (nhds 0) := by
    simpa using (tendsto_const_nhds.mul hplayed :
      Tendsto (fun t : ℕ => S * G.fictitiousPlayPlayedGain a t) atTop (nhds (S * 0)))
  exact squeeze_zero (fun t => hfp.fictitiousPlayWeightedPlayedGain_nonneg t) hbound hSplayed

open Filter in
open Classical in
/-- Monderer-Shapley improvement convergence, bounded-potential form:
along fictitious play in an exact-potential game, the aggregate mixed
improvement of the empirical beliefs tends to zero. -/
theorem IsExactPotential.mixedImprovement_belief_tendsto_zero_of_abs_bound
    [DecidableEq ι] {G : KernelGame ι} [∀ i, Fintype (G.Strategy i)] [Finite G.Outcome]
    {Φ : Profile G → ℝ} (hΦ : G.IsExactPotential Φ)
    {C : ℝ} (hC : ∀ s : Profile G, |Φ s| ≤ C)
    {a : ℕ → Profile G} (hfp : G.IsFictitiousPlay a) :
    Tendsto (fun t : ℕ => G.mixedImprovement (G.belief a (t + 1))) atTop (nhds 0) := by
  have hweighted := hΦ.fictitiousPlayWeightedPlayedGain_tendsto_zero hC hfp
  exact squeeze_zero
    (fun t => G.mixedImprovement_nonneg (G.belief a (t + 1)))
    (fun t => hfp.mixedImprovement_le_weightedPlayedGain t)
    hweighted

open Filter in
open Classical in
/-- Monderer-Shapley improvement convergence for finite exact-potential games:
along fictitious play, the aggregate mixed improvement of the empirical beliefs
tends to zero. -/
theorem IsExactPotential.mixedImprovement_belief_tendsto_zero
    [DecidableEq ι] {G : KernelGame ι} [∀ i, Fintype (G.Strategy i)] [Finite G.Outcome]
    {Φ : Profile G → ℝ} (hΦ : G.IsExactPotential Φ)
    {a : ℕ → Profile G} (hfp : G.IsFictitiousPlay a) :
    Tendsto (fun t : ℕ => G.mixedImprovement (G.belief a (t + 1))) atTop (nhds 0) := by
  obtain ⟨C, hC⟩ := G.exists_profile_abs_bound Φ
  exact hΦ.mixedImprovement_belief_tendsto_zero_of_abs_bound hC hfp

open Filter in
open Classical in
/-- Monderer-Shapley approximate-equilibrium convergence, bounded-potential
form: along fictitious play in an exact-potential game, empirical beliefs are
eventually ε-Nash for every positive ε. -/
theorem IsExactPotential.eventually_isεNash_of_isFictitiousPlay_of_abs_bound
    [DecidableEq ι] {G : KernelGame ι} [∀ i, Finite (G.Strategy i)] [Finite G.Outcome]
    {Φ : Profile G → ℝ} (hΦ : G.IsExactPotential Φ)
    {C : ℝ} (hC : ∀ s : Profile G, |Φ s| ≤ C)
    {a : ℕ → Profile G} (hfp : G.IsFictitiousPlay a)
    {ε : ℝ} (hε : 0 < ε) :
    ∀ᶠ t in atTop, G.mixedExtension.IsεNash ε (G.belief a (t + 1)) := by
  letI (i : ι) : Fintype (G.Strategy i) := Fintype.ofFinite (G.Strategy i)
  exact G.eventually_isεNash_of_mixedImprovement_tendsto_zero
    (hΦ.mixedImprovement_belief_tendsto_zero_of_abs_bound hC hfp) hε

open Filter in
open Classical in
/-- **Monderer-Shapley for finite exact-potential games.** Along fictitious
play, empirical beliefs are eventually ε-Nash for every positive ε. -/
theorem IsExactPotential.eventually_isεNash_of_isFictitiousPlay
    [DecidableEq ι] {G : KernelGame ι} [∀ i, Finite (G.Strategy i)] [Finite G.Outcome]
    {Φ : Profile G → ℝ} (hΦ : G.IsExactPotential Φ)
    {a : ℕ → Profile G} (hfp : G.IsFictitiousPlay a)
    {ε : ℝ} (hε : 0 < ε) :
    ∀ᶠ t in atTop, G.mixedExtension.IsεNash ε (G.belief a (t + 1)) := by
  letI (i : ι) : Fintype (G.Strategy i) := Fintype.ofFinite (G.Strategy i)
  exact G.eventually_isεNash_of_mixedImprovement_tendsto_zero
    (hΦ.mixedImprovement_belief_tendsto_zero hfp) hε

open Filter in
/-- If the weighted played-gain gap of a fictitious-play process vanishes, then
the empirical beliefs are eventually ε-Nash for every positive ε. -/
theorem IsFictitiousPlay.eventually_isεNash_of_weightedPlayedGain_tendsto_zero
    [DecidableEq ι] {G : KernelGame ι} [∀ i, Fintype (G.Strategy i)] [Finite G.Outcome]
    {a : ℕ → Profile G} (hfp : G.IsFictitiousPlay a)
    (hgain : Tendsto (fun t : ℕ => G.fictitiousPlayWeightedPlayedGain a t) atTop (nhds 0))
    {ε : ℝ} (hε : 0 < ε) :
    ∀ᶠ t in atTop, G.mixedExtension.IsεNash ε (G.belief a (t + 1)) := by
  have hev : ∀ᶠ t in atTop, G.fictitiousPlayWeightedPlayedGain a t < ε :=
    hgain.eventually (eventually_lt_nhds hε)
  filter_upwards [hev] with t ht
  exact G.isεNash_of_mixedImprovement_le
    (σ := G.belief a (t + 1))
    ((hfp.mixedImprovement_le_weightedPlayedGain t).trans (le_of_lt ht))

open Classical in
/-- Weighted exact-potential games and their finite potential-generated
identical-interest games have the same fictitious-play processes. -/
theorem IsWeightedExactPotential.isFictitiousPlay_iff_finitePotentialTeamGame
    [DecidableEq ι] {G : KernelGame ι} [∀ i, Finite (G.Strategy i)] [Finite G.Outcome]
    {Φ : Profile G → ℝ} {w : ι → ℝ} (hΦ : G.IsWeightedExactPotential Φ w)
    (a : ℕ → Profile G) :
    G.IsFictitiousPlay a ↔ (G.finitePotentialTeamGame Φ).IsFictitiousPlay a := by
  constructor
  · intro hfp t who s'
    have hg :
        G.mixedExtension.eu
            (Function.update (G.belief a (t + 1)) who (PMF.pure s')) who ≤
          G.mixedExtension.eu
            (Function.update (G.belief a (t + 1)) who
              (PMF.pure (a (t + 1) who))) who := by
      exact hfp t who s'
    have hcmp := (hΦ.mixedExtension_le_iff_finitePotentialTeamGame
      (σ := G.belief a (t + 1)) who
      (PMF.pure s') (PMF.pure (a (t + 1) who))).mp hg
    change
      (G.finitePotentialTeamGame Φ).mixedExtension.eu
          (Function.update (G.belief a (t + 1)) who
            (PMF.pure (a (t + 1) who))) who ≥
        (G.finitePotentialTeamGame Φ).mixedExtension.eu
          (Function.update (G.belief a (t + 1)) who (PMF.pure s')) who
    exact hcmp
  · intro hfp t who s'
    have ht :
        (G.finitePotentialTeamGame Φ).mixedExtension.eu
            (Function.update (G.belief a (t + 1)) who (PMF.pure s')) who ≤
          (G.finitePotentialTeamGame Φ).mixedExtension.eu
            (Function.update (G.belief a (t + 1)) who
              (PMF.pure (a (t + 1) who))) who := by
      change
        (G.finitePotentialTeamGame Φ).mixedExtension.eu
            (Function.update ((G.finitePotentialTeamGame Φ).belief a (t + 1)) who
              (PMF.pure s')) who ≤
          (G.finitePotentialTeamGame Φ).mixedExtension.eu
            (Function.update ((G.finitePotentialTeamGame Φ).belief a (t + 1)) who
              (PMF.pure (a (t + 1) who))) who
      exact hfp t who s'
    have hcmp := (hΦ.mixedExtension_le_iff_finitePotentialTeamGame
      (σ := G.belief a (t + 1)) who
      (PMF.pure s') (PMF.pure (a (t + 1) who))).mpr ht
    exact hcmp

open Classical in
/-- Exact-potential games and their finite potential-generated
identical-interest games have the same fictitious-play processes. -/
theorem IsExactPotential.isFictitiousPlay_iff_finitePotentialTeamGame
    [DecidableEq ι] {G : KernelGame ι} [∀ i, Finite (G.Strategy i)] [Finite G.Outcome]
    {Φ : Profile G → ℝ} (hΦ : G.IsExactPotential Φ)
    (a : ℕ → Profile G) :
    G.IsFictitiousPlay a ↔ (G.finitePotentialTeamGame Φ).IsFictitiousPlay a :=
  hΦ.toWeightedExactPotential.isFictitiousPlay_iff_finitePotentialTeamGame a

open Classical in
/-- Approximate equilibria of the finite potential-generated team game transfer
to approximate equilibria of the original weighted-potential game after scaling
by the sum of the positive weights. -/
theorem IsWeightedExactPotential.isεNash_of_finitePotentialTeamGame_isεNash
    [DecidableEq ι] {G : KernelGame ι} [∀ i, Finite (G.Strategy i)] [Finite G.Outcome]
    {Φ : Profile G → ℝ} {w : ι → ℝ} (hΦ : G.IsWeightedExactPotential Φ w)
    {σ : ∀ i, PMF (G.Strategy i)} {δ ε : ℝ}
    (hσ : (G.finitePotentialTeamGame Φ).mixedExtension.IsεNash δ σ)
    (hδ_nonneg : 0 ≤ δ)
    (hδε : (∑ who : ι, w who) * δ ≤ ε) :
    G.mixedExtension.IsεNash ε σ := by
  intro who τ
  change PMF (G.Strategy who) at τ
  let H : KernelGame ι := G.finitePotentialTeamGame Φ
  let σH : ∀ i, PMF (H.Strategy i) := σ
  let τH : PMF (H.Strategy who) := τ
  have hteam := hσ who τH
  have hteam_diff :
      G.mixedPotential Φ (Function.update σ who τ) - G.mixedPotential Φ σ ≤ δ := by
    have hbase :
        H.mixedExtension.eu σH who = G.mixedPotential Φ σ := by
      dsimp [H, σH]
      exact G.finitePotentialTeamGame_mixedExtension_eu_self Φ σ who
    have hupdate :
        H.mixedExtension.eu (Function.update σH who τH) who =
          G.mixedPotential Φ (Function.update σ who τ) := by
      dsimp [H, σH, τH]
      exact G.finitePotentialTeamGame_mixedExtension_eu_self Φ
        (Function.update σ who τ) who
    change H.mixedExtension.eu σH who + δ ≥
      H.mixedExtension.eu (Function.update σH who τH) who at hteam
    rw [hbase, hupdate] at hteam
    linarith
  have hdiff := hΦ.mixedExtension_update_diff σ who τ
  have hscaled :
      G.mixedExtension.eu (Function.update σ who τ) who -
          G.mixedExtension.eu σ who ≤ w who * δ := by
    rw [hdiff]
    exact mul_le_mul_of_nonneg_left hteam_diff (hΦ.1 who).le
  have hw_le_sum :
      w who ≤ ∑ j : ι, w j := by
    exact Finset.single_le_sum (fun j _ => (hΦ.1 j).le) (Finset.mem_univ who)
  have hweight_scaled :
      w who * δ ≤ (∑ j : ι, w j) * δ :=
    mul_le_mul_of_nonneg_right hw_le_sum hδ_nonneg
  have hgain :
      G.mixedExtension.eu (Function.update σ who τ) who -
          G.mixedExtension.eu σ who ≤ ε :=
    hscaled.trans (hweight_scaled.trans hδε)
  linarith

open Filter in
open Classical in
/-- **Monderer-Shapley for finite weighted exact-potential games.** Along
fictitious play, empirical beliefs are eventually ε-Nash for every positive
ε. -/
theorem IsWeightedExactPotential.eventually_isεNash_of_isFictitiousPlay
    [DecidableEq ι] {G : KernelGame ι} [∀ i, Finite (G.Strategy i)] [Finite G.Outcome]
    {Φ : Profile G → ℝ} {w : ι → ℝ} (hΦ : G.IsWeightedExactPotential Φ w)
    {a : ℕ → Profile G} (hfp : G.IsFictitiousPlay a)
    {ε : ℝ} (hε : 0 < ε) :
    ∀ᶠ t in atTop, G.mixedExtension.IsεNash ε (G.belief a (t + 1)) := by
  letI (i : ι) : Fintype (G.Strategy i) := Fintype.ofFinite (G.Strategy i)
  letI (i : ι) : Finite ((G.finitePotentialTeamGame Φ).Strategy i) :=
    inferInstanceAs (Finite (G.Strategy i))
  letI : Finite ((G.finitePotentialTeamGame Φ).Outcome) :=
    inferInstanceAs (Finite (Profile G))
  by_cases hι : Nonempty ι
  · let W : ℝ := ∑ who : ι, w who
    have hW_pos : 0 < W := by
      obtain ⟨who₀⟩ := hι
      dsimp [W]
      exact Finset.sum_pos (fun who _ => hΦ.1 who) ⟨who₀, Finset.mem_univ who₀⟩
    let δ : ℝ := ε / W
    have hδ_pos : 0 < δ := by
      dsimp [δ]
      exact div_pos hε hW_pos
    have hδ_nonneg : 0 ≤ δ := hδ_pos.le
    have hWδ : W * δ ≤ ε := by
      have hWδ_eq : W * δ = ε := by
        dsimp [δ]
        field_simp [hW_pos.ne']
      exact le_of_eq hWδ_eq
    have hteamfp :
        (G.finitePotentialTeamGame Φ).IsFictitiousPlay a :=
      (hΦ.isFictitiousPlay_iff_finitePotentialTeamGame a).mp hfp
    have hteamExact :
        (G.finitePotentialTeamGame Φ).IsExactPotential Φ :=
      G.finitePotentialTeamGame_isExactPotential Φ
    have hevent :
        ∀ᶠ t in atTop,
          (G.finitePotentialTeamGame Φ).mixedExtension.IsεNash δ
            ((G.finitePotentialTeamGame Φ).belief a (t + 1)) :=
      hteamExact.eventually_isεNash_of_isFictitiousPlay hteamfp hδ_pos
    filter_upwards [hevent] with t ht
    change
      (G.finitePotentialTeamGame Φ).mixedExtension.IsεNash δ
        (G.belief a (t + 1)) at ht
    exact hΦ.isεNash_of_finitePotentialTeamGame_isεNash ht hδ_nonneg
      (by simpa [W] using hWδ)
  · filter_upwards [] with _t
    intro who
    exact (hι ⟨who⟩).elim

end KernelGame

end GameTheory
