import GameTheory.Model.SemanticForm

namespace GameTheory
namespace InfoModel

variable {ι : Type} {M : LSM ι} (I : InfoModel M)

/-- Splitting a continuation into two segments splits the corresponding local
history tokens into a prefix part and a suffix part generated after the updated
global state prefix. -/
theorem localHistTokensFrom_append
    (i : ι)
    (pref : List M.State)
    (ha₁ ha₂ : List (JointAction M))
    (ssTail₁ ssTail₂ : List M.State)
    (hLen₁ : ssTail₁.length = ha₁.length) :
    localHistTokensFrom I i pref (ha₁ ++ ha₂) (ssTail₁ ++ ssTail₂) =
      localHistTokensFrom I i pref ha₁ ssTail₁ ++
        localHistTokensFrom I i (pref ++ ssTail₁) ha₂ ssTail₂ := by
  induction ha₁ generalizing pref ssTail₁ with
  | nil =>
      cases ssTail₁ with
      | nil =>
          have hnil : localHistTokensFrom I i pref [] [] = [] := rfl
          calc
            localHistTokensFrom I i pref ([] ++ ha₂) ([] ++ ssTail₂)
                = localHistTokensFrom I i (pref ++ []) ha₂ ssTail₂ := by
                    simp [localHistTokensFrom]
            _ = localHistTokensFrom I i pref [] [] ++
                  localHistTokensFrom I i (pref ++ []) ha₂ ssTail₂ := by
                    simp [hnil]
      | cons s ss =>
          cases hLen₁
  | cons a ha₁ ih =>
      cases ssTail₁ with
      | nil =>
          cases hLen₁
      | cons s ss =>
          have hLen₁' : ss.length = ha₁.length := by
            simpa using Nat.succ.inj hLen₁
          calc
            localHistTokensFrom I i pref ((a :: ha₁) ++ ha₂) ((s :: ss) ++ ssTail₂)
                =
              (I.projectStates i pref, a i) ::
                localHistTokensFrom I i (pref ++ [s]) (ha₁ ++ ha₂) (ss ++ ssTail₂) := by
                  rfl
            _ =
              (I.projectStates i pref, a i) ::
                (localHistTokensFrom I i (pref ++ [s]) ha₁ ss ++
                  localHistTokensFrom I i ((pref ++ [s]) ++ ss) ha₂ ssTail₂) := by
                    rw [ih (pref := pref ++ [s]) (ssTail₁ := ss) hLen₁']
            _ =
              localHistTokensFrom I i pref (a :: ha₁) (s :: ss) ++
                localHistTokensFrom I i (pref ++ s :: ss) ha₂ ssTail₂ := by
                  have hcons :
                      localHistTokensFrom I i pref (a :: ha₁) (s :: ss) =
                        (I.projectStates i pref, a i) ::
                          localHistTokensFrom I i (pref ++ [s]) ha₁ ss := rfl
                  rw [hcons]
                  simp [List.append_assoc]

/-- Global local-history tokens along a trace split into the tokens generated by
an initial prefix and the tokens generated by the remaining continuation. -/
theorem localHistTokens_append
    (i : ι)
    (ha₁ ha₂ : List (JointAction M))
    (ss₁ ssTail₂ : List M.State)
    (hLen₁ : ss₁.length = ha₁.length + 1) :
    localHistTokens I i (ha₁ ++ ha₂) (ss₁ ++ ssTail₂) =
      localHistTokens I i ha₁ ss₁ ++
        localHistTokensFrom I i ss₁ ha₂ ssTail₂ := by
  cases ss₁ with
  | nil =>
      cases hLen₁
  | cons s₀ ssTail₁ =>
      have hLen₁' : ssTail₁.length = ha₁.length := by
        simpa using hLen₁
      calc
        localHistTokens I i (ha₁ ++ ha₂) (s₀ :: (ssTail₁ ++ ssTail₂))
            =
          localHistTokensFrom I i [s₀] (ha₁ ++ ha₂) (ssTail₁ ++ ssTail₂) := by
              simpa using
                (localHistTokens_cons_eq_localHistTokensFrom
                  (I := I) i s₀ (ha₁ ++ ha₂) (ssTail₁ ++ ssTail₂))
        _ =
          localHistTokensFrom I i [s₀] ha₁ ssTail₁ ++
            localHistTokensFrom I i ([s₀] ++ ssTail₁) ha₂ ssTail₂ := by
              exact localHistTokensFrom_append
                (I := I) i [s₀] ha₁ ha₂ ssTail₁ ssTail₂ hLen₁'
        _ =
          localHistTokens I i ha₁ (s₀ :: ssTail₁) ++
            localHistTokensFrom I i (s₀ :: ssTail₁) ha₂ ssTail₂ := by
              simpa using congrArg
                (fun z => z ++ localHistTokensFrom I i (s₀ :: ssTail₁) ha₂ ssTail₂)
                (localHistTokens_cons_eq_localHistTokensFrom (I := I) i s₀ ha₁ ssTail₁).symm

end InfoModel
end GameTheory
