import GameTheory.Model.SemanticForm

namespace GameTheory
namespace InfoModel

variable {ι : Type} {M : LSM ι} (I : InfoModel M)

/-- Local-history tokens generated by continuing after an already accumulated
global state prefix `pref`. Each token records the local trace visible just
before one further action together with the action taken at that point. -/
def localHistTokensFrom
    (i : ι)
    (pref : List M.State)
    (ha : List (M.Label × (∀ j, Option (M.Act j))))
    (ssTail : List M.State) :
    List (I.LocalHistTok i) :=
  match ha, ssTail with
  | [], _ => []
  | (_, a) :: ha', s' :: ss' =>
      (I.projectStates i pref, a i) ::
        localHistTokensFrom I i (pref ++ [s']) ha' ss'
  | _ :: _, [] => []

/-- Appending one more continuation step appends one more continuation local
history token. -/
theorem localHistTokensFrom_snoc
    (i : ι)
    (pref : List M.State)
    (ha : List (M.Label × (∀ j, Option (M.Act j))))
    (ssTail : List M.State)
    (hLen : ssTail.length = ha.length)
    (ℓ : M.Label) (a : ∀ j, Option (M.Act j)) (t : M.State) :
    localHistTokensFrom I i pref (ha ++ [(ℓ, a)]) (ssTail ++ [t]) =
      localHistTokensFrom I i pref ha ssTail ++
        [(I.projectStates i (pref ++ ssTail), a i)] := by
  induction ha generalizing pref ssTail with
  | nil =>
      cases ssTail with
      | nil =>
          simp [localHistTokensFrom]
      | cons s ss =>
          cases hLen
  | cons x ha ih =>
      cases ssTail with
      | nil =>
          cases hLen
      | cons s ss =>
          simp at hLen
          simp [localHistTokensFrom, ih (pref := pref ++ [s]) (ssTail := ss) hLen,
            List.append_assoc]

/-- Splitting a continuation into two segments splits the corresponding local
history tokens into a prefix part and a suffix part generated after the updated
global state prefix. -/
theorem localHistTokensFrom_append
    (i : ι)
    (pref : List M.State)
    (ha₁ ha₂ : List (M.Label × (∀ j, Option (M.Act j))))
    (ssTail₁ ssTail₂ : List M.State)
    (hLen₁ : ssTail₁.length = ha₁.length) :
    localHistTokensFrom I i pref (ha₁ ++ ha₂) (ssTail₁ ++ ssTail₂) =
      localHistTokensFrom I i pref ha₁ ssTail₁ ++
        localHistTokensFrom I i (pref ++ ssTail₁) ha₂ ssTail₂ := by
  induction ha₁ generalizing pref ssTail₁ with
  | nil =>
      cases ssTail₁ with
      | nil =>
          simp [localHistTokensFrom]
      | cons s ss =>
          cases hLen₁
  | cons x ha₁ ih =>
      cases ssTail₁ with
      | nil =>
          cases hLen₁
      | cons s ss =>
          simp at hLen₁
          simp [localHistTokensFrom, ih (pref := pref ++ [s]) (ssTail₁ := ss) hLen₁,
            List.append_assoc]

/-- Global local-history tokens along a trace split into the tokens generated by
an initial prefix and the tokens generated by the remaining continuation. -/
theorem localHistTokens_append
    (i : ι)
    (ha₁ ha₂ : List (M.Label × (∀ j, Option (M.Act j))))
    (ss₁ ssTail₂ : List M.State)
    (hLen₁ : ss₁.length = ha₁.length + 1)
    (hLen₂ : ssTail₂.length = ha₂.length) :
    localHistTokens I i (ha₁ ++ ha₂) (ss₁ ++ ssTail₂) =
      localHistTokens I i ha₁ ss₁ ++
        localHistTokensFrom I i ss₁ ha₂ ssTail₂ := by
  cases ss₁ with
  | nil =>
      cases hLen₁
  | cons s₀ ssTail₁ =>
      have hLen₁' : ssTail₁.length = ha₁.length := by
        simpa using hLen₁
      simpa [localHistTokens, List.cons_append, List.append_assoc] using
        localHistTokensFrom_append
          (I := I) i [s₀] ha₁ ha₂ ssTail₁ ssTail₂ hLen₁'

end InfoModel
end GameTheory
