/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/
import Mathlib.Analysis.Convex.Topology
import Math.PMFProduct

/-!
# Product-image convexification and exact fiberwise replacement

Let `Act i` be finite action sets and let `observation` assign a real vector
to every pure joint action.  Coordinatewise expectation is the affine
extension of this table from pure laws to the simplex of correlated laws.

This file proves the following core results of product-image convexification:

* the convex hull of the observations generated by independent product laws
  is exactly the image generated by all correlated laws;
* consequently, the product image equals the correlated image exactly when
  the product image is convex; and
* exact local image equality permits simultaneous, fiberwise replacement at
  every index while preserving any global predicate which factors through the
  retained observation vectors.

The last result deliberately has no graph hypothesis.  If exit fluxes,
charges, slacks, and other load-bearing data are all coordinates of the local
observation, exact equality preserves the already-selected global balance
system literally.  Routing or recurrent compatibility becomes a separate
issue only when those coordinates are projected away or changed
approximately.
-/

noncomputable section

open scoped BigOperators

namespace GameTheory

namespace Correlation

open Math.Probability
open Math.PMFProduct

universe uι uA uκ uV

variable {ι : Type uι} (Act : ι → Type uA)

/-- A pure action for every player. -/
abbrev ActionProfile : Type (max uι uA) :=
  ∀ i, Act i

/-- Independent mixed actions, one probability law for each player. -/
abbrev IndependentProfile : Type (max uι uA) :=
  ∀ i, PMF (Act i)

/-- Coordinatewise affine extension of a pure joint-action observation table
to a correlated joint law.  Every affine map out of the finite joint simplex
is determined by such a table. -/
def expectedObservation {κ : Type uκ}
    (observation : ActionProfile Act → κ → ℝ)
    (law : PMF (ActionProfile Act)) : κ → ℝ :=
  fun coordinate => expect law (fun action => observation action coordinate)

/-- Observation vectors generated by independent product laws. -/
def productObservationImage [Fintype ι] {κ : Type uκ}
    (observation : ActionProfile Act → κ → ℝ) : Set (κ → ℝ) :=
  Set.range fun profile : IndependentProfile Act =>
    expectedObservation Act observation (pmfPi profile)

/-- Observation vectors generated by arbitrary correlated joint laws. -/
def correlatedObservationImage {κ : Type uκ}
    (observation : ActionProfile Act → κ → ℝ) : Set (κ → ℝ) :=
  Set.range fun law : PMF (ActionProfile Act) =>
    expectedObservation Act observation law

/-- Pure observation vectors. -/
def pureObservationImage {κ : Type uκ}
    (observation : ActionProfile Act → κ → ℝ) : Set (κ → ℝ) :=
  Set.range observation

@[simp] theorem expectedObservation_pure {κ : Type uκ}
    (observation : ActionProfile Act → κ → ℝ) (action : ActionProfile Act) :
    expectedObservation Act observation (PMF.pure action) = observation action := by
  funext coordinate
  simp [expectedObservation]

/-- Every pure law is an independent product law. -/
theorem pureObservationImage_subset_productObservationImage
    [Fintype ι] {κ : Type uκ}
    (observation : ActionProfile Act → κ → ℝ) :
    pureObservationImage Act observation ⊆
      productObservationImage Act observation := by
  rintro _ ⟨action, rfl⟩
  refine ⟨(fun i => PMF.pure (action i)), ?_⟩
  change expectedObservation Act observation
      (pmfPi (fun i => PMF.pure (action i))) = observation action
  rw [pmfPi_pure]
  exact expectedObservation_pure Act observation action

/-- Every independent product law is, in particular, a correlated law. -/
theorem productObservationImage_subset_correlatedObservationImage
    [Fintype ι] {κ : Type uκ}
    (observation : ActionProfile Act → κ → ℝ) :
    productObservationImage Act observation ⊆
      correlatedObservationImage Act observation := by
  rintro _ ⟨profile, rfl⟩
  exact ⟨pmfPi profile, rfl⟩

/-- The correlated image of a finite joint simplex is the convex hull of its
pure observation vectors. -/
theorem correlatedObservationImage_eq_convexHull_pureObservationImage
    [Finite ι] [∀ i, Finite (Act i)] {κ : Type uκ}
    (observation : ActionProfile Act → κ → ℝ) :
    correlatedObservationImage Act observation =
      convexHull ℝ (pureObservationImage Act observation) := by
  classical
  letI : Fintype (ActionProfile Act) := Fintype.ofFinite (ActionProfile Act)
  apply Set.Subset.antisymm
  · rintro _ ⟨law, rfl⟩
    apply mem_convexHull_of_exists_fintype
      (fun action : ActionProfile Act => (law action).toReal) observation
    · exact fun _ => ENNReal.toReal_nonneg
    · exact pmf_toReal_sum_one law
    · exact fun action => ⟨action, rfl⟩
    · funext coordinate
      simp [expectedObservation, expect_eq_sum, Pi.smul_apply, smul_eq_mul]
  · intro value hvalue
    obtain ⟨α, inst, weight, point, hweight0, hweight1, hpoint, hsum⟩ :=
      mem_convexHull_iff_exists_fintype.mp hvalue
    letI : Fintype α := inst
    choose action haction using
      fun index => hpoint index
    let indexLaw : PMF α :=
      PMF.ofFintype (fun index => ENNReal.ofReal (weight index)) (by
        rw [← ENNReal.ofReal_one, ← hweight1]
        exact (ENNReal.ofReal_sum_of_nonneg
          (fun index _ => hweight0 index)).symm)
    let law : PMF (ActionProfile Act) :=
      indexLaw.bind fun index => PMF.pure (action index)
    refine ⟨law, ?_⟩
    funext coordinate
    have hindexLaw (index : α) :
        (indexLaw index).toReal = weight index := by
      simp [indexLaw, PMF.ofFintype_apply,
        ENNReal.toReal_ofReal (hweight0 index)]
    have hsumCoordinate := congrFun hsum coordinate
    calc
      expectedObservation Act observation law coordinate =
          expect indexLaw
            (fun index => observation (action index) coordinate) := by
        simp [expectedObservation, law, expect_bind]
      _ = ∑ index : α,
          weight index * observation (action index) coordinate := by
        rw [expect_eq_sum]
        apply Finset.sum_congr rfl
        intro index _hindex
        rw [hindexLaw]
      _ = ∑ index : α, weight index * point index coordinate := by
        apply Finset.sum_congr rfl
        intro index _hindex
        rw [haction index]
      _ = value coordinate := by
        simpa [Finset.sum_apply, Pi.smul_apply, smul_eq_mul] using hsumCoordinate

/-- Convexifying the independent product image gives exactly the correlated
image.  This does not say that a correlated observation is itself generated
by one product law; that is precisely the remaining deconvexification issue. -/
theorem convexHull_productObservationImage_eq_correlatedObservationImage
    [Fintype ι] [∀ i, Finite (Act i)] {κ : Type uκ}
    (observation : ActionProfile Act → κ → ℝ) :
    convexHull ℝ (productObservationImage Act observation) =
      correlatedObservationImage Act observation := by
  rw [correlatedObservationImage_eq_convexHull_pureObservationImage]
  apply Set.Subset.antisymm
  · apply convexHull_min
    · exact (productObservationImage_subset_correlatedObservationImage
        Act observation).trans (by
          rw [correlatedObservationImage_eq_convexHull_pureObservationImage])
    · exact convex_convexHull ℝ _
  · exact convexHull_mono
      (pureObservationImage_subset_productObservationImage Act observation)

/-- The product and correlated observation images agree exactly when the
product image is convex. -/
theorem productObservationImage_eq_correlatedObservationImage_iff_convex
    [Fintype ι] [∀ i, Finite (Act i)] {κ : Type uκ}
    (observation : ActionProfile Act → κ → ℝ) :
    productObservationImage Act observation =
        correlatedObservationImage Act observation ↔
      Convex ℝ (productObservationImage Act observation) := by
  have hhull :=
    convexHull_productObservationImage_eq_correlatedObservationImage
      Act observation
  constructor
  · intro heq
    rw [← heq] at hhull
    exact convexHull_eq_self.mp hhull
  · intro hconvex
    have hself :
        convexHull ℝ (productObservationImage Act observation) =
          productObservationImage Act observation :=
      convexHull_eq_self.mpr hconvex
    exact hself.symm.trans hhull

section Fiberwise

variable {V : Type uV} (VertexAct : V → ι → Type uA)
variable {κ : V → Type uκ}
variable (observation : ∀ v, ActionProfile (VertexAct v) → κ v → ℝ)

/-- Exact local image equality permits simultaneous product replacement at
every fiber.  No finiteness, ordering, or graph structure on `V` is needed. -/
theorem exists_fiberwise_productProfile_of_image_eq
    [Fintype ι]
    (image_eq : ∀ v,
      productObservationImage (VertexAct v) (observation v) =
        correlatedObservationImage (VertexAct v) (observation v))
    (law : ∀ v, PMF (ActionProfile (VertexAct v))) :
    ∃ profile : ∀ v, IndependentProfile (VertexAct v),
      ∀ v,
        expectedObservation (VertexAct v) (observation v) (pmfPi (profile v)) =
          expectedObservation (VertexAct v) (observation v) (law v) := by
  classical
  have hmember : ∀ v,
      expectedObservation (VertexAct v) (observation v) (law v) ∈
        productObservationImage (VertexAct v) (observation v) := by
    intro v
    rw [image_eq v]
    exact ⟨law v, rfl⟩
  choose profile hprofile using hmember
  exact ⟨profile, hprofile⟩

/-- Full-coordinate fiberwise replacement preserves any global feasibility
predicate which depends only on the scaled retained observation vectors.  This
abstractly includes graph balance, individual edge fluxes, charges, slacks,
and arbitrary global equalities or inequalities built from those coordinates. -/
theorem exists_fiberwise_productProfile_preserving_system
    [Fintype ι]
    (image_eq : ∀ v,
      productObservationImage (VertexAct v) (observation v) =
        correlatedObservationImage (VertexAct v) (observation v))
    (mass : V → ℝ)
    (law : ∀ v, PMF (ActionProfile (VertexAct v)))
    (System : (∀ v, κ v → ℝ) → Prop)
    (hSystem : System (fun v => mass v •
      expectedObservation (VertexAct v) (observation v) (law v))) :
    ∃ profile : ∀ v, IndependentProfile (VertexAct v),
      (∀ v,
        mass v • expectedObservation (VertexAct v) (observation v)
            (pmfPi (profile v)) =
          mass v • expectedObservation (VertexAct v) (observation v) (law v)) ∧
      System (fun v => mass v •
        expectedObservation (VertexAct v) (observation v)
          (pmfPi (profile v))) := by
  obtain ⟨profile, hprofile⟩ :=
    exists_fiberwise_productProfile_of_image_eq
      VertexAct observation image_eq law
  refine ⟨profile, fun v => congrArg (fun x => mass v • x) (hprofile v), ?_⟩
  have heq :
      (fun v => mass v •
        expectedObservation (VertexAct v) (observation v) (pmfPi (profile v))) =
      (fun v => mass v •
        expectedObservation (VertexAct v) (observation v) (law v)) := by
    funext v
    exact congrArg (fun x => mass v • x) (hprofile v)
  rw [heq]
  exact hSystem

end Fiberwise

end Correlation

end GameTheory
