/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/

import GameTheory.Concepts.Correlation.ProductImageConvexification

/-!
# A binary nonconvex product-observation gadget

Two Boolean players are observed only when their actions agree.  The first
coordinate records `(false, false)` and the second records `(true, true)`.
For independent marginals with false-action probabilities `α` and `β`, the
observation is

`(α * β, (1 - α) * (1 - β))`.

This file proves the exact formula through the product-image convexification
API.  It also proves that the only product observations on the affine
top edge `r + s = 1` are its two endpoints, and hence that the product image
is not convex.
-/

set_option autoImplicit false

noncomputable section

open scoped BigOperators

namespace GameTheory
namespace Correlation
namespace SelectedFiber

open Math Probability Math.Probability Math.PMFProduct

/-- Both players have the Boolean action set. -/
@[reducible] def binaryAction (_player : Bool) : Type := Bool

/-- The two coordinates record the two diagonal cells of the Boolean action
table. -/
def binaryObservation
    (action : ActionProfile binaryAction) (coordinate : Bool) : ℝ :=
  if action false = coordinate ∧ action true = coordinate then 1 else 0

/-- Encode a pair `(r,s)` as a Boolean-coordinate observation vector. -/
def binaryPair (r s : ℝ) : Bool → ℝ :=
  fun coordinate => if coordinate then s else r

/-- Real mass of the false action in a Boolean PMF. -/
def falseMass (law : PMF Bool) : ℝ :=
  (law false).toReal

theorem falseMass_nonneg (law : PMF Bool) :
    0 ≤ falseMass law :=
  ENNReal.toReal_nonneg

theorem falseMass_le_one (law : PMF Bool) :
    falseMass law ≤ 1 := by
  exact ENNReal.toReal_mono ENNReal.one_ne_top (law.coe_le_one false)

theorem trueMass_eq_one_sub_falseMass (law : PMF Bool) :
    (law true).toReal = 1 - falseMass law := by
  have hsum := pmf_toReal_sum_one law
  rw [Fintype.sum_bool] at hsum
  unfold falseMass
  linarith

/-- Fubini expansion for the product of two Boolean action laws. -/
private theorem expect_pmfPi_bool
    (profile : IndependentProfile binaryAction)
    (payoff : ActionProfile binaryAction → ℝ) :
    expect (pmfPi profile) payoff =
      expect (profile false) (fun first =>
        expect (profile true) (fun second =>
          payoff (fun player => if player then second else first))) := by
  classical
  have hfalse : Function.update profile false (profile false) = profile :=
    Function.update_eq_self false profile
  rw [← hfalse, pmfPi_update_bind, expect_bind]
  apply congrArg (expect (profile false))
  funext first
  have htrue :
      Function.update (Function.update profile false (PMF.pure first))
          true (profile true) =
        Function.update profile false (PMF.pure first) := by
    funext player
    cases player <;> simp
  rw [← htrue, pmfPi_update_bind, expect_bind]
  apply congrArg (expect (profile true))
  funext second
  have hpure :
      Function.update (Function.update profile false (PMF.pure first))
          true (PMF.pure second) =
        fun player => PMF.pure (if player then second else first) := by
    funext player
    cases player <;> simp
  rw [hpure, pmfPi_pure, expect_pure]

/-- Exact image formula for the binary agreement gadget. -/
theorem expectedObservation_pmfPi_eq_binaryPair
    (profile : IndependentProfile binaryAction) :
    expectedObservation binaryAction binaryObservation (pmfPi profile) =
      binaryPair
        (falseMass (profile false) * falseMass (profile true))
        ((1 - falseMass (profile false)) *
          (1 - falseMass (profile true))) := by
  funext coordinate
  unfold expectedObservation
  rw [expect_pmfPi_bool]
  cases coordinate <;>
    simp [binaryObservation, binaryPair, expect_eq_sum,
      trueMass_eq_one_sub_falseMass, falseMass]

/-- The `(1,0)` endpoint is generated by both players choosing `false`. -/
theorem binaryPair_one_zero_mem_productImage :
    binaryPair 1 0 ∈
      productObservationImage binaryAction binaryObservation := by
  refine ⟨fun _player => PMF.pure false, ?_⟩
  change expectedObservation binaryAction binaryObservation
    (pmfPi (fun _player : Bool => PMF.pure false)) = binaryPair 1 0
  rw [pmfPi_pure, expectedObservation_pure]
  funext coordinate
  cases coordinate <;> simp [binaryObservation, binaryPair]

/-- The `(0,1)` endpoint is generated by both players choosing `true`. -/
theorem binaryPair_zero_one_mem_productImage :
    binaryPair 0 1 ∈
      productObservationImage binaryAction binaryObservation := by
  refine ⟨fun _player => PMF.pure true, ?_⟩
  change expectedObservation binaryAction binaryObservation
    (pmfPi (fun _player : Bool => PMF.pure true)) = binaryPair 0 1
  rw [pmfPi_pure, expectedObservation_pure]
  funext coordinate
  cases coordinate <;> simp [binaryObservation, binaryPair]

/-- A product observation on `r+s=1` must be one of the two pure diagonal
endpoints. -/
theorem productImage_topEdge_only_endpoints {r s : ℝ}
    (htop : r + s = 1)
    (hmember : binaryPair r s ∈
      productObservationImage binaryAction binaryObservation) :
    (r = 1 ∧ s = 0) ∨ (r = 0 ∧ s = 1) := by
  obtain ⟨profile, hprofile⟩ := hmember
  change expectedObservation binaryAction binaryObservation (pmfPi profile) =
    binaryPair r s at hprofile
  rw [expectedObservation_pmfPi_eq_binaryPair] at hprofile
  let α := falseMass (profile false)
  let β := falseMass (profile true)
  have hα0 : 0 ≤ α := falseMass_nonneg (profile false)
  have hα1 : α ≤ 1 := falseMass_le_one (profile false)
  have hβ0 : 0 ≤ β := falseMass_nonneg (profile true)
  have hβ1 : β ≤ 1 := falseMass_le_one (profile true)
  have hr := congrFun hprofile false
  have hs := congrFun hprofile true
  simp only [binaryPair, Bool.false_eq_true, ↓reduceIte] at hr hs
  have hcrossSum : α * (1 - β) + β * (1 - α) = 0 := by
    dsimp only [α, β]
    nlinarith
  have hleftNonneg : 0 ≤ α * (1 - β) :=
    mul_nonneg hα0 (sub_nonneg.mpr hβ1)
  have hrightNonneg : 0 ≤ β * (1 - α) :=
    mul_nonneg hβ0 (sub_nonneg.mpr hα1)
  have hleft : α * (1 - β) = 0 := by linarith
  have hright : β * (1 - α) = 0 := by linarith
  rcases mul_eq_zero.mp hleft with hα | hβ
  · right
    have hβzero : β = 0 := by
      simpa [hα] using hright
    constructor <;> nlinarith
  · left
    have hβone : β = 1 := by linarith
    have hαone : α = 1 := by linarith
    constructor <;> nlinarith

/-- The midpoint of the two diagonal endpoints is not generated by any
independent product law. -/
theorem binaryPair_half_half_not_mem_productImage :
    binaryPair (1 / 2) (1 / 2) ∉
      productObservationImage binaryAction binaryObservation := by
  intro hmember
  have hendpoints := productImage_topEdge_only_endpoints (by norm_num) hmember
  rcases hendpoints with hendpoints | hendpoints <;> norm_num at hendpoints

/-- The binary product-observation image is genuinely nonconvex. -/
theorem not_convex_binary_productObservationImage :
    ¬ Convex ℝ (productObservationImage binaryAction binaryObservation) := by
  intro hconvex
  have hmidpoint := hconvex.midpoint_mem
    binaryPair_one_zero_mem_productImage
    binaryPair_zero_one_mem_productImage
  apply binaryPair_half_half_not_mem_productImage
  convert hmidpoint using 1
  funext coordinate
  cases coordinate <;>
    norm_num [binaryPair, midpoint, AffineMap.lineMap_apply_module]

end SelectedFiber
end Correlation
end GameTheory
