/-
# Principal-agent contracts

Each hidden action induces an ordinary PMF. Payment, reward, and net payoff
are integrated only by the operation that needs them. In particular, the
principal's net payoff can exist when its two components do not.
-/

import GameTheory.Math.Probability.ExpectationAlgebra

noncomputable section

namespace GameTheory.Mechanism

open GameTheory.Math.Probability

universe uAction uOutcome

/-- A hidden-action principal-agent environment. -/
structure PrincipalAgent (Action : Type uAction) (Outcome : Type uOutcome) where
  /-- Distribution of observable outcomes induced by each hidden action. -/
  outcomeLaw : Action → PMF Outcome
  /-- Principal's realized reward before paying the agent. -/
  reward : Outcome → ℝ
  /-- Agent's effort cost for each hidden action. -/
  cost : Action → ℝ

namespace PrincipalAgent

variable {Action : Type uAction} {Outcome : Type uOutcome}

/-- A limited-liability payment never charges the agent. -/
def IsLimitedLiability (payment : Outcome → ℝ) : Prop :=
  ∀ outcome, 0 ≤ payment outcome

variable (I : PrincipalAgent Action Outcome)

/-- Expected payment under the action's actual outcome law. -/
def expectedPayment (payment : Outcome → ℝ) (action : Action)
    (hpayment : PayoffIntegrable (I.outcomeLaw action) payment) : ℝ :=
  expect (I.outcomeLaw action) payment hpayment

/-- Agent payoff: expected payment less private effort cost. -/
def agentUtility (payment : Outcome → ℝ) (action : Action)
    (hpayment : PayoffIntegrable (I.outcomeLaw action) payment) : ℝ :=
  I.expectedPayment payment action hpayment - I.cost action

/-- Principal payoff needs only the actual net-payoff integration. -/
def principalUtility (payment : Outcome → ℝ) (action : Action)
    (hnet : PayoffIntegrable (I.outcomeLaw action)
      (fun outcome => I.reward outcome - payment outcome)) : ℝ :=
  expect (I.outcomeLaw action)
    (fun outcome => I.reward outcome - payment outcome) hnet

/-- Expected gross reward. -/
def expectedReward (action : Action)
    (hreward : PayoffIntegrable (I.outcomeLaw action) I.reward) : ℝ :=
  expect (I.outcomeLaw action) I.reward hreward

/-- Total expected surplus generated by an action. -/
def socialSurplus (action : Action)
    (hreward : PayoffIntegrable (I.outcomeLaw action) I.reward) : ℝ :=
  I.expectedReward action hreward - I.cost action

/-- Linear commission: a fixed share of realized reward. -/
def linearPayment (α : ℝ) : Outcome → ℝ :=
  fun outcome => α * I.reward outcome

/-- An incentivized action has a defined payoff and weakly dominates every
alternative. Undefined alternative payoffs refute the predicate. -/
def IsIncentivized (payment : Outcome → ℝ) (action : Action) : Prop :=
  ∃ hpayment : ∀ alternative, PayoffIntegrable (I.outcomeLaw alternative) payment,
    ∀ alternative,
      I.agentUtility payment alternative (hpayment alternative) ≤
        I.agentUtility payment action (hpayment action)

/-- The agent accepts an action only with a defined payment expectation. -/
def Participates (outsideOption : ℝ) (payment : Outcome → ℝ)
    (action : Action) : Prop :=
  ∃ hpayment : PayoffIntegrable (I.outcomeLaw action) payment,
    outsideOption ≤ I.agentUtility payment action hpayment

/-- Some action meets the outside option. -/
def OffersParticipation (outsideOption : ℝ)
    (payment : Outcome → ℝ) : Prop :=
  ∃ action, I.Participates outsideOption payment action

/-- Accounting needs reward and payment separately integrable, even though
principal utility alone only needs their difference integrable. -/
theorem principalUtility_add_agentUtility
    (payment : Outcome → ℝ) (action : Action)
    (hreward : PayoffIntegrable (I.outcomeLaw action) I.reward)
    (hpayment : PayoffIntegrable (I.outcomeLaw action) payment)
    (hnet : PayoffIntegrable (I.outcomeLaw action)
      (fun outcome => I.reward outcome - payment outcome)) :
    I.principalUtility payment action hnet +
      I.agentUtility payment action hpayment =
      I.socialSurplus action hreward := by
  unfold principalUtility agentUtility expectedPayment socialSurplus expectedReward
  rw [show expect (I.outcomeLaw action)
      (fun outcome => I.reward outcome - payment outcome) hnet =
      expect (I.outcomeLaw action)
        (fun outcome => I.reward outcome - payment outcome)
        (payoffIntegrable_sub hreward hpayment) from
      expect_proof_irrel _ _ _ _, expect_sub hreward hpayment]
  ring

theorem agentUtility_ge (payment : Outcome → ℝ)
    (hpayment : IsLimitedLiability payment) (action : Action)
    (hintegrable : PayoffIntegrable (I.outcomeLaw action) payment) :
    -I.cost action ≤ I.agentUtility payment action hintegrable := by
  have hnonneg : 0 ≤ I.expectedPayment payment action hintegrable := by
    exact expect_nonneg (I.outcomeLaw action) payment hintegrable
      (fun outcome _ => hpayment outcome)
  unfold agentUtility
  linarith

theorem linearPayment_limitedLiability {α : ℝ} (hα : 0 ≤ α)
    (hreward : ∀ outcome, 0 ≤ I.reward outcome) :
    IsLimitedLiability (I.linearPayment α) :=
  fun outcome => mul_nonneg hα (hreward outcome)

theorem agentUtility_linearPayment (α : ℝ) (action : Action)
    (hreward : PayoffIntegrable (I.outcomeLaw action) I.reward) :
    I.agentUtility (I.linearPayment α) action
        (payoffIntegrable_const_mul (c := α) hreward) =
      α * I.expectedReward action hreward - I.cost action := by
  unfold agentUtility expectedPayment linearPayment expectedReward
  rw [expect_const_mul hreward]

theorem principalUtility_linearPayment (α : ℝ) (action : Action)
    (hreward : PayoffIntegrable (I.outcomeLaw action) I.reward)
    (hnet : PayoffIntegrable (I.outcomeLaw action)
      (fun outcome => I.reward outcome - I.linearPayment α outcome)) :
    I.principalUtility (I.linearPayment α) action hnet =
      (1 - α) * I.expectedReward action hreward := by
  have hscale : PayoffIntegrable (I.outcomeLaw action)
      (fun outcome => (1 - α) * I.reward outcome) :=
    payoffIntegrable_const_mul hreward
  have hvalue : ∀ outcome ∈ (I.outcomeLaw action).support,
      I.reward outcome - I.linearPayment α outcome =
        (1 - α) * I.reward outcome := by
    intro outcome _
    simp [linearPayment]
    ring
  unfold principalUtility expectedReward
  calc
    expect (I.outcomeLaw action)
        (fun outcome => I.reward outcome - I.linearPayment α outcome) hnet =
      expect (I.outcomeLaw action)
        (fun outcome => (1 - α) * I.reward outcome) hscale :=
      expect_congr_on_support hvalue hnet hscale
    _ = (1 - α) * expect (I.outcomeLaw action) I.reward hreward :=
      expect_const_mul hreward

theorem agentUtility_linearPayment_one (action : Action)
    (hreward : PayoffIntegrable (I.outcomeLaw action) I.reward) :
    I.agentUtility (I.linearPayment 1) action
        (payoffIntegrable_const_mul (c := (1 : ℝ)) hreward) =
      I.socialSurplus action hreward := by
  rw [I.agentUtility_linearPayment 1 action hreward]
  simp [socialSurplus]

/-- Full commission leaves the principal a zero net payoff without requiring
the reward itself to be integrable. -/
theorem principalUtility_linearPayment_one (action : Action) :
    ∃ hnet : PayoffIntegrable (I.outcomeLaw action)
        (fun outcome => I.reward outcome - I.linearPayment 1 outcome),
      I.principalUtility (I.linearPayment 1) action hnet = 0 := by
  have hzero : ∀ outcome ∈ (I.outcomeLaw action).support,
      I.reward outcome - I.linearPayment 1 outcome = 0 := by
    intro outcome _
    simp [linearPayment]
  have hnet : PayoffIntegrable (I.outcomeLaw action)
      (fun outcome => I.reward outcome - I.linearPayment 1 outcome) :=
    payoffIntegrable_congr_on_support
      (fun outcome hs => (hzero outcome hs).symm)
      (payoffIntegrable_zero (I.outcomeLaw action))
  refine ⟨hnet, ?_⟩
  unfold principalUtility
  calc
    expect (I.outcomeLaw action)
        (fun outcome => I.reward outcome - I.linearPayment 1 outcome) hnet =
      expect (I.outcomeLaw action) (fun _ => 0)
        (payoffIntegrable_zero _) :=
      expect_congr_on_support hzero hnet (payoffIntegrable_zero _)
    _ = 0 := expect_zero _ _

/-- A finite action set has a best defined agent action when every alternative
payment expectation exists. -/
theorem exists_incentivized [Finite Action] [Nonempty Action]
    (payment : Outcome → ℝ)
    (hpayment : ∀ action, PayoffIntegrable (I.outcomeLaw action) payment) :
    ∃ action, I.IsIncentivized payment action := by
  obtain ⟨action, hbest⟩ :=
    Finite.exists_max (fun alternative =>
      I.agentUtility payment alternative (hpayment alternative))
  exact ⟨action, hpayment, hbest⟩

theorem isIncentivized_linearPayment_one_iff
    (action : Action)
    (hreward : ∀ alternative, PayoffIntegrable
      (I.outcomeLaw alternative) I.reward) :
    I.IsIncentivized (I.linearPayment 1) action ↔
      ∀ alternative,
        I.socialSurplus alternative (hreward alternative) ≤
          I.socialSurplus action (hreward action) := by
  constructor
  · rintro ⟨hpayment, hbest⟩ alternative
    have hvalue (candidate : Action) :
        I.agentUtility (I.linearPayment 1) candidate (hpayment candidate) =
          I.socialSurplus candidate (hreward candidate) := by
      calc
        _ = I.agentUtility (I.linearPayment 1) candidate
            (payoffIntegrable_const_mul (c := (1 : ℝ))
              (hreward candidate)) := rfl
        _ = _ := I.agentUtility_linearPayment_one candidate (hreward candidate)
    simpa only [hvalue] using hbest alternative
  · intro hbest
    refine ⟨fun candidate => payoffIntegrable_const_mul (c := (1 : ℝ))
      (hreward candidate), ?_⟩
    intro alternative
    rw [I.agentUtility_linearPayment_one alternative (hreward alternative),
      I.agentUtility_linearPayment_one action (hreward action)]
    exact hbest alternative

theorem agentUtility_mono (payment payment' : Outcome → ℝ)
    (hpayment : ∀ outcome, payment outcome ≤ payment' outcome)
    (action : Action)
    (hfirst : PayoffIntegrable (I.outcomeLaw action) payment)
    (hsecond : PayoffIntegrable (I.outcomeLaw action) payment') :
    I.agentUtility payment action hfirst ≤
      I.agentUtility payment' action hsecond := by
  have h := expect_mono
    (μ := I.outcomeLaw action) (f := payment) (g := payment')
    (fun outcome _ => hpayment outcome) hfirst hsecond
  unfold agentUtility expectedPayment
  linarith

theorem participates_of_offersParticipation_of_isIncentivized
    {outsideOption : ℝ} {payment : Outcome → ℝ} {action : Action}
    (hoffers : I.OffersParticipation outsideOption payment)
    (hincentive : I.IsIncentivized payment action) :
    I.Participates outsideOption payment action := by
  obtain ⟨alternative, hparticipates⟩ := hoffers
  obtain ⟨hpaymentAlternative, hparticipates⟩ := hparticipates
  obtain ⟨hpayment, hbest⟩ := hincentive
  refine ⟨hpayment action, ?_⟩
  exact le_trans hparticipates (hbest alternative)

theorem offersParticipation_zero_of_costless_of_limitedLiability
    (payment : Outcome → ℝ) (hpayment : IsLimitedLiability payment)
    {costless : Action} (hcostless : I.cost costless = 0)
    (hintegrable : PayoffIntegrable (I.outcomeLaw costless) payment) :
    I.OffersParticipation 0 payment := by
  refine ⟨costless, hintegrable, ?_⟩
  have h := I.agentUtility_ge payment hpayment costless hintegrable
  simpa [hcostless] using h

theorem participates_zero_of_costless_of_limitedLiability_of_isIncentivized
    (payment : Outcome → ℝ) (hpayment : IsLimitedLiability payment)
    {costless : Action} (hcostless : I.cost costless = 0)
    (hintegrable : PayoffIntegrable (I.outcomeLaw costless) payment)
    {action : Action} (hincentive : I.IsIncentivized payment action) :
    I.Participates 0 payment action :=
  I.participates_of_offersParticipation_of_isIncentivized
    (I.offersParticipation_zero_of_costless_of_limitedLiability
      payment hpayment hcostless hintegrable) hincentive

theorem principalUtility_le_socialSurplus_sub_outsideOption
    (payment : Outcome → ℝ) {outsideOption : ℝ} {action : Action}
    (hreward : PayoffIntegrable (I.outcomeLaw action) I.reward)
    (hnet : PayoffIntegrable (I.outcomeLaw action)
      (fun outcome => I.reward outcome - payment outcome))
    (hparticipates : I.Participates outsideOption payment action) :
    I.principalUtility payment action hnet ≤
      I.socialSurplus action hreward - outsideOption := by
  obtain ⟨hpayment, houtside⟩ := hparticipates
  have haccount :=
    I.principalUtility_add_agentUtility payment action hreward hpayment hnet
  linarith

theorem principalUtility_le_socialSurplus_of_participates_zero
    (payment : Outcome → ℝ) {action : Action}
    (hreward : PayoffIntegrable (I.outcomeLaw action) I.reward)
    (hnet : PayoffIntegrable (I.outcomeLaw action)
      (fun outcome => I.reward outcome - payment outcome))
    (hparticipates : I.Participates 0 payment action) :
    I.principalUtility payment action hnet ≤
      I.socialSurplus action hreward := by
  simpa using I.principalUtility_le_socialSurplus_sub_outsideOption
    payment hreward hnet hparticipates

theorem principalUtility_eq_socialSurplus_sub_outsideOption_iff
    (payment : Outcome → ℝ) (outsideOption : ℝ) (action : Action)
    (hreward : PayoffIntegrable (I.outcomeLaw action) I.reward)
    (hpayment : PayoffIntegrable (I.outcomeLaw action) payment)
    (hnet : PayoffIntegrable (I.outcomeLaw action)
      (fun outcome => I.reward outcome - payment outcome)) :
    I.principalUtility payment action hnet =
        I.socialSurplus action hreward - outsideOption ↔
      I.agentUtility payment action hpayment = outsideOption := by
  have haccount :=
    I.principalUtility_add_agentUtility payment action hreward hpayment hnet
  constructor <;> intro he <;> linarith

theorem principalUtility_eq_socialSurplus_iff
    (payment : Outcome → ℝ) (action : Action)
    (hreward : PayoffIntegrable (I.outcomeLaw action) I.reward)
    (hpayment : PayoffIntegrable (I.outcomeLaw action) payment)
    (hnet : PayoffIntegrable (I.outcomeLaw action)
      (fun outcome => I.reward outcome - payment outcome)) :
    I.principalUtility payment action hnet =
        I.socialSurplus action hreward ↔
      I.agentUtility payment action hpayment = 0 := by
  simpa using I.principalUtility_eq_socialSurplus_sub_outsideOption_iff
    payment 0 action hreward hpayment hnet

theorem principalUtility_le_firstBest [Finite Action] [Nonempty Action]
    (payment : Outcome → ℝ) {outsideOption : ℝ} {action : Action}
    (hreward : ∀ alternative, PayoffIntegrable
      (I.outcomeLaw alternative) I.reward)
    (hnet : PayoffIntegrable (I.outcomeLaw action)
      (fun outcome => I.reward outcome - payment outcome))
    (hparticipates : I.Participates outsideOption payment action) :
    ∃ best : Action,
      (∀ alternative,
        I.socialSurplus alternative (hreward alternative) ≤
          I.socialSurplus best (hreward best)) ∧
      I.principalUtility payment action hnet ≤
        I.socialSurplus best (hreward best) - outsideOption := by
  obtain ⟨best, hbest⟩ :=
    Finite.exists_max (fun candidate => I.socialSurplus candidate (hreward candidate))
  refine ⟨best, hbest, ?_⟩
  exact le_trans
    (I.principalUtility_le_socialSurplus_sub_outsideOption
      payment (hreward action) hnet hparticipates)
    (sub_le_sub_right (hbest action) outsideOption)

theorem principalUtility_le_firstBest_zero [Finite Action] [Nonempty Action]
    (payment : Outcome → ℝ) {action : Action}
    (hreward : ∀ alternative, PayoffIntegrable
      (I.outcomeLaw alternative) I.reward)
    (hnet : PayoffIntegrable (I.outcomeLaw action)
      (fun outcome => I.reward outcome - payment outcome))
    (hparticipates : I.Participates 0 payment action) :
    ∃ best : Action,
      (∀ alternative,
        I.socialSurplus alternative (hreward alternative) ≤
          I.socialSurplus best (hreward best)) ∧
      I.principalUtility payment action hnet ≤
        I.socialSurplus best (hreward best) := by
  simpa using I.principalUtility_le_firstBest
    payment hreward hnet hparticipates

end PrincipalAgent

end GameTheory.Mechanism
