/-
# Principal-agent contracts

Each hidden action induces an ordinary PMF. Payment, reward, and net payoff
are integrated only by the operation that needs them. In particular, the
principal's net payoff can exist when its two components do not.
-/

import GameTheory.Math.Probability.ExpectationAlgebra

noncomputable section

namespace GameTheory.Mechanism

open GameTheory.Math.Probability

universe uAction uOutcome

/-- A hidden-action principal-agent environment. -/
structure PrincipalAgent (Action : Type uAction) (Outcome : Type uOutcome) where
  /-- Distribution of observable outcomes induced by each hidden action. -/
  outcomeLaw : Action → PMF Outcome
  /-- Principal's realized reward before paying the agent. -/
  reward : Outcome → ℝ
  /-- Agent's effort cost for each hidden action. -/
  cost : Action → ℝ

namespace PrincipalAgent

variable {Action : Type uAction} {Outcome : Type uOutcome}

/-- A limited-liability payment never charges the agent. -/
def IsLimitedLiability (payment : Outcome → ℝ) : Prop :=
  ∀ outcome, 0 ≤ payment outcome

variable (I : PrincipalAgent Action Outcome)

/-- Expected payment under the action's actual outcome law. -/
def expectedPayment (payment : Outcome → ℝ) (action : Action) : ℝ :=
  expect (I.outcomeLaw action) payment

/-- Agent payoff: expected payment less private effort cost. -/
def agentUtility (payment : Outcome → ℝ) (action : Action) : ℝ :=
  I.expectedPayment payment action - I.cost action

/-- Principal payoff needs only the actual net-payoff integration. -/
def principalUtility (payment : Outcome → ℝ) (action : Action) : ℝ :=
  expect (I.outcomeLaw action)
    (fun outcome => I.reward outcome - payment outcome)

/-- Expected gross reward. -/
def expectedReward (action : Action) : ℝ :=
  expect (I.outcomeLaw action) I.reward

/-- Total expected surplus generated by an action. -/
def socialSurplus (action : Action) : ℝ :=
  I.expectedReward action - I.cost action

/-- Linear commission: a fixed share of realized reward. -/
def linearPayment (α : ℝ) : Outcome → ℝ :=
  fun outcome => α * I.reward outcome

/-- An incentivized action has a defined payoff and weakly dominates every
alternative. Undefined alternative payoffs refute the predicate. -/
def IsIncentivized (payment : Outcome → ℝ) (action : Action) : Prop :=
  (∀ alternative, PayoffIntegrable (I.outcomeLaw alternative) payment) ∧
    ∀ alternative, I.agentUtility payment alternative ≤ I.agentUtility payment action

/-- The agent accepts an action only with a defined payment expectation. -/
def Participates (outsideOption : ℝ) (payment : Outcome → ℝ)
    (action : Action) : Prop :=
  PayoffIntegrable (I.outcomeLaw action) payment ∧
    outsideOption ≤ I.agentUtility payment action

/-- Some action meets the outside option. -/
def OffersParticipation (outsideOption : ℝ)
    (payment : Outcome → ℝ) : Prop :=
  ∃ action, I.Participates outsideOption payment action

/-- Accounting needs reward and payment separately integrable, even though
principal utility alone only needs their difference integrable. -/
theorem principalUtility_add_agentUtility
    (payment : Outcome → ℝ) (action : Action)
    (hreward : PayoffIntegrable (I.outcomeLaw action) I.reward)
    (hpayment : PayoffIntegrable (I.outcomeLaw action) payment) :
    I.principalUtility payment action + I.agentUtility payment action =
      I.socialSurplus action := by
  unfold principalUtility agentUtility expectedPayment socialSurplus expectedReward
  rw [expect_sub hreward hpayment]
  ring

theorem agentUtility_ge (payment : Outcome → ℝ)
    (hpayment : IsLimitedLiability payment) (action : Action) :
    -I.cost action ≤ I.agentUtility payment action := by
  have hnonneg : 0 ≤ I.expectedPayment payment action := by
    exact expect_nonneg (I.outcomeLaw action) payment
      (fun outcome _ => hpayment outcome)
  unfold agentUtility
  linarith

theorem linearPayment_limitedLiability {α : ℝ} (hα : 0 ≤ α)
    (hreward : ∀ outcome, 0 ≤ I.reward outcome) :
    IsLimitedLiability (I.linearPayment α) :=
  fun outcome => mul_nonneg hα (hreward outcome)

theorem agentUtility_linearPayment (α : ℝ) (action : Action) :
    I.agentUtility (I.linearPayment α) action =
      α * I.expectedReward action - I.cost action := by
  unfold agentUtility expectedPayment linearPayment expectedReward
  rw [expect_const_mul]

theorem principalUtility_linearPayment (α : ℝ) (action : Action) :
    I.principalUtility (I.linearPayment α) action =
      (1 - α) * I.expectedReward action := by
  have hvalue : ∀ outcome ∈ (I.outcomeLaw action).support,
      I.reward outcome - I.linearPayment α outcome =
        (1 - α) * I.reward outcome := by
    intro outcome _
    simp [linearPayment]
    ring
  unfold principalUtility expectedReward
  calc
    expect (I.outcomeLaw action)
        (fun outcome => I.reward outcome - I.linearPayment α outcome) =
      expect (I.outcomeLaw action)
        (fun outcome => (1 - α) * I.reward outcome) :=
      expect_congr_on_support hvalue
    _ = (1 - α) * expect (I.outcomeLaw action) I.reward :=
      expect_const_mul

theorem agentUtility_linearPayment_one (action : Action) :
    I.agentUtility (I.linearPayment 1) action =
      I.socialSurplus action := by
  rw [I.agentUtility_linearPayment 1 action]
  simp [socialSurplus]

/-- Full commission leaves the principal a zero net payoff without requiring
the reward itself to be integrable. -/
theorem principalUtility_linearPayment_one (action : Action) :
    PayoffIntegrable (I.outcomeLaw action)
        (fun outcome => I.reward outcome - I.linearPayment 1 outcome) ∧
      I.principalUtility (I.linearPayment 1) action = 0 := by
  have hzero : ∀ outcome ∈ (I.outcomeLaw action).support,
      I.reward outcome - I.linearPayment 1 outcome = 0 := by
    intro outcome _
    simp [linearPayment]
  have hnet : PayoffIntegrable (I.outcomeLaw action)
      (fun outcome => I.reward outcome - I.linearPayment 1 outcome) :=
    payoffIntegrable_congr_on_support
      (fun outcome hs => (hzero outcome hs).symm)
      (payoffIntegrable_zero (I.outcomeLaw action))
  refine ⟨hnet, ?_⟩
  unfold principalUtility
  calc
    expect (I.outcomeLaw action)
        (fun outcome => I.reward outcome - I.linearPayment 1 outcome) =
      expect (I.outcomeLaw action) (fun _ => 0) :=
      expect_congr_on_support hzero
    _ = 0 := expect_zero _

/-- A finite action set has a best defined agent action when every alternative
payment expectation exists. -/
theorem exists_incentivized [Finite Action] [Nonempty Action]
    (payment : Outcome → ℝ)
    (hpayment : ∀ action, PayoffIntegrable (I.outcomeLaw action) payment) :
    ∃ action, I.IsIncentivized payment action := by
  obtain ⟨action, hbest⟩ :=
    Finite.exists_max (fun alternative =>
      I.agentUtility payment alternative)
  exact ⟨action, hpayment, hbest⟩

theorem isIncentivized_linearPayment_one_iff
    (action : Action)
    (hreward : ∀ alternative, PayoffIntegrable
      (I.outcomeLaw alternative) I.reward) :
    I.IsIncentivized (I.linearPayment 1) action ↔
      ∀ alternative,
        I.socialSurplus alternative ≤
          I.socialSurplus action := by
  constructor
  · rintro ⟨hpayment, hbest⟩ alternative
    have hvalue (candidate : Action) :
        I.agentUtility (I.linearPayment 1) candidate =
          I.socialSurplus candidate := by
      calc
        _ = I.agentUtility (I.linearPayment 1) candidate := rfl
        _ = _ := I.agentUtility_linearPayment_one candidate
    simpa only [hvalue] using hbest alternative
  · intro hbest
    refine ⟨fun candidate => payoffIntegrable_const_mul (c := (1 : ℝ))
      (hreward candidate), ?_⟩
    intro alternative
    rw [I.agentUtility_linearPayment_one alternative,
      I.agentUtility_linearPayment_one action]
    exact hbest alternative

theorem agentUtility_mono (payment payment' : Outcome → ℝ)
    (hpayment : ∀ outcome, payment outcome ≤ payment' outcome)
    (action : Action)
    (hfirst : PayoffIntegrable (I.outcomeLaw action) payment)
    (hsecond : PayoffIntegrable (I.outcomeLaw action) payment') :
    I.agentUtility payment action ≤
      I.agentUtility payment' action := by
  have h := expect_mono
    (μ := I.outcomeLaw action) (f := payment) (g := payment')
    (fun outcome _ => hpayment outcome) hfirst hsecond
  unfold agentUtility expectedPayment
  linarith

theorem participates_of_offersParticipation_of_isIncentivized
    {outsideOption : ℝ} {payment : Outcome → ℝ} {action : Action}
    (hoffers : I.OffersParticipation outsideOption payment)
    (hincentive : I.IsIncentivized payment action) :
    I.Participates outsideOption payment action := by
  obtain ⟨alternative, hparticipates⟩ := hoffers
  obtain ⟨hpaymentAlternative, hparticipates⟩ := hparticipates
  obtain ⟨hpayment, hbest⟩ := hincentive
  refine ⟨hpayment action, ?_⟩
  exact le_trans hparticipates (hbest alternative)

theorem offersParticipation_zero_of_costless_of_limitedLiability
    (payment : Outcome → ℝ) (hpayment : IsLimitedLiability payment)
    {costless : Action} (hcostless : I.cost costless = 0)
    (hintegrable : PayoffIntegrable (I.outcomeLaw costless) payment) :
    I.OffersParticipation 0 payment := by
  refine ⟨costless, hintegrable, ?_⟩
  have h := I.agentUtility_ge payment hpayment costless
  simpa [hcostless] using h

theorem participates_zero_of_costless_of_limitedLiability_of_isIncentivized
    (payment : Outcome → ℝ) (hpayment : IsLimitedLiability payment)
    {costless : Action} (hcostless : I.cost costless = 0)
    (hintegrable : PayoffIntegrable (I.outcomeLaw costless) payment)
    {action : Action} (hincentive : I.IsIncentivized payment action) :
    I.Participates 0 payment action :=
  I.participates_of_offersParticipation_of_isIncentivized
    (I.offersParticipation_zero_of_costless_of_limitedLiability
      payment hpayment hcostless hintegrable) hincentive

theorem principalUtility_le_socialSurplus_sub_outsideOption
    (payment : Outcome → ℝ) {outsideOption : ℝ} {action : Action}
    (hreward : PayoffIntegrable (I.outcomeLaw action) I.reward)
    (hparticipates : I.Participates outsideOption payment action) :
    I.principalUtility payment action ≤
      I.socialSurplus action - outsideOption := by
  obtain ⟨hpayment, houtside⟩ := hparticipates
  have haccount :=
    I.principalUtility_add_agentUtility payment action hreward hpayment
  linarith

theorem principalUtility_le_socialSurplus_of_participates_zero
    (payment : Outcome → ℝ) {action : Action}
    (hreward : PayoffIntegrable (I.outcomeLaw action) I.reward)
    (hparticipates : I.Participates 0 payment action) :
    I.principalUtility payment action ≤
      I.socialSurplus action := by
  simpa using I.principalUtility_le_socialSurplus_sub_outsideOption
    payment hreward hparticipates

theorem principalUtility_eq_socialSurplus_sub_outsideOption_iff
    (payment : Outcome → ℝ) (outsideOption : ℝ) (action : Action)
    (hreward : PayoffIntegrable (I.outcomeLaw action) I.reward)
    (hpayment : PayoffIntegrable (I.outcomeLaw action) payment) :
    I.principalUtility payment action =
        I.socialSurplus action - outsideOption ↔
      I.agentUtility payment action = outsideOption := by
  have haccount :=
    I.principalUtility_add_agentUtility payment action hreward hpayment
  constructor <;> intro he <;> linarith

theorem principalUtility_eq_socialSurplus_iff
    (payment : Outcome → ℝ) (action : Action)
    (hreward : PayoffIntegrable (I.outcomeLaw action) I.reward)
    (hpayment : PayoffIntegrable (I.outcomeLaw action) payment) :
    I.principalUtility payment action =
        I.socialSurplus action ↔
      I.agentUtility payment action = 0 := by
  simpa using I.principalUtility_eq_socialSurplus_sub_outsideOption_iff
    payment 0 action hreward hpayment

theorem principalUtility_le_firstBest [Finite Action] [Nonempty Action]
    (payment : Outcome → ℝ) {outsideOption : ℝ} {action : Action}
    (hreward : ∀ alternative, PayoffIntegrable
      (I.outcomeLaw alternative) I.reward)
    (hparticipates : I.Participates outsideOption payment action) :
    ∃ best : Action,
      (∀ alternative,
        I.socialSurplus alternative ≤
          I.socialSurplus best) ∧
      I.principalUtility payment action ≤
        I.socialSurplus best - outsideOption := by
  obtain ⟨best, hbest⟩ :=
    Finite.exists_max (fun candidate => I.socialSurplus candidate)
  refine ⟨best, hbest, ?_⟩
  exact le_trans
    (I.principalUtility_le_socialSurplus_sub_outsideOption
      payment (hreward action) hparticipates)
    (sub_le_sub_right (hbest action) outsideOption)

theorem principalUtility_le_firstBest_zero [Finite Action] [Nonempty Action]
    (payment : Outcome → ℝ) {action : Action}
    (hreward : ∀ alternative, PayoffIntegrable
      (I.outcomeLaw alternative) I.reward)
    (hparticipates : I.Participates 0 payment action) :
    ∃ best : Action,
      (∀ alternative,
        I.socialSurplus alternative ≤
          I.socialSurplus best) ∧
      I.principalUtility payment action ≤
        I.socialSurplus best := by
  simpa using I.principalUtility_le_firstBest
    payment hreward hparticipates

end PrincipalAgent

end GameTheory.Mechanism
