/-
# Principal-agent contracts

Each hidden action induces an ordinary PMF. Payment, reward, and net payoff
are integrated only by the operation that needs them. In particular, the
principal's net payoff can exist when its two components do not. The agent's
incentive and participation constraints compare extended-real payoffs, so an
action whose expected payment is infinite is still ranked; only an action whose
expected payment is undefined is left incomparable.
-/

import GameTheory.Math.Probability.ExtendedExpectation

noncomputable section

namespace GameTheory.Mechanism

open GameTheory.Math.Probability

universe uAction uOutcome

/-- A hidden-action principal-agent environment. -/
structure PrincipalAgent (Action : Type uAction) (Outcome : Type uOutcome) where
  /-- Distribution of observable outcomes induced by each hidden action. -/
  outcomeLaw : Action → PMF Outcome
  /-- Principal's realized reward before paying the agent. -/
  reward : Outcome → ℝ
  /-- Agent's effort cost for each hidden action. -/
  cost : Action → ℝ

namespace PrincipalAgent

variable {Action : Type uAction} {Outcome : Type uOutcome}

/-- A limited-liability payment never charges the agent. -/
def IsLimitedLiability (payment : Outcome → ℝ) : Prop :=
  ∀ outcome, 0 ≤ payment outcome

variable (I : PrincipalAgent Action Outcome)

/-- Expected payment under the action's actual outcome law. -/
def expectedPayment (payment : Outcome → ℝ) (action : Action) : ℝ :=
  expect (I.outcomeLaw action) payment

/-- Agent payoff: expected payment less private effort cost. -/
def agentUtility (payment : Outcome → ℝ) (action : Action) : ℝ :=
  I.expectedPayment payment action - I.cost action

/-- Principal payoff needs only the actual net-payoff integration. -/
def principalUtility (payment : Outcome → ℝ) (action : Action) : ℝ :=
  expect (I.outcomeLaw action)
    (fun outcome => I.reward outcome - payment outcome)

/-- Expected gross reward. -/
def expectedReward (action : Action) : ℝ :=
  expect (I.outcomeLaw action) I.reward

/-- Total expected surplus generated by an action. -/
def socialSurplus (action : Action) : ℝ :=
  I.expectedReward action - I.cost action

/-- Linear commission: a fixed share of realized reward. -/
def linearPayment (α : ℝ) : Outcome → ℝ :=
  fun outcome => α * I.reward outcome

/-- Agent payoff in the extended reals: the expected payment may be infinite. -/
def extendedAgentUtility (payment : Outcome → ℝ) (action : Action) : EReal :=
  extendedExpect (I.outcomeLaw action) payment - I.cost action

theorem extendedAgentUtility_eq {payment : Outcome → ℝ} {action : Action}
    (hpayment : PayoffIntegrable (I.outcomeLaw action) payment) :
    I.extendedAgentUtility payment action = I.agentUtility payment action := by
  rw [extendedAgentUtility, extendedExpect_eq_expect hpayment, agentUtility, expectedPayment]
  norm_cast

/-- An incentivized action weakly dominates every alternative, and every
action's payment expectation exists. An alternative whose expected payment is
undefined refutes the predicate. -/
def IsIncentivized (payment : Outcome → ℝ) (action : Action) : Prop :=
  (∀ alternative, HasExpectation (I.outcomeLaw alternative) payment) ∧
    ∀ alternative,
      I.extendedAgentUtility payment alternative ≤ I.extendedAgentUtility payment action

/-- The agent accepts an action whose payment expectation exists and meets the
outside option. -/
def Participates (outsideOption : ℝ) (payment : Outcome → ℝ)
    (action : Action) : Prop :=
  HasExpectation (I.outcomeLaw action) payment ∧
    (outsideOption : EReal) ≤ I.extendedAgentUtility payment action

/-- With integrable payments, incentive compatibility is the real comparison
of agent payoffs. -/
theorem isIncentivized_iff_of_integrable {payment : Outcome → ℝ} {action : Action}
    (hpayment : ∀ alternative, PayoffIntegrable (I.outcomeLaw alternative) payment) :
    I.IsIncentivized payment action ↔
      ∀ alternative, I.agentUtility payment alternative ≤ I.agentUtility payment action := by
  simp only [IsIncentivized, I.extendedAgentUtility_eq (hpayment _), EReal.coe_le_coe_iff]
  exact ⟨fun h => h.2, fun h => ⟨fun alternative =>
    hasExpectation_of_payoffIntegrable (hpayment alternative), h⟩⟩

/-- With an integrable payment, participation is the real comparison with the
outside option. -/
theorem participates_iff_of_integrable {outsideOption : ℝ} {payment : Outcome → ℝ}
    {action : Action} (hpayment : PayoffIntegrable (I.outcomeLaw action) payment) :
    I.Participates outsideOption payment action ↔
      outsideOption ≤ I.agentUtility payment action := by
  rw [Participates, I.extendedAgentUtility_eq hpayment, EReal.coe_le_coe_iff]
  exact ⟨fun h => h.2, fun h => ⟨hasExpectation_of_payoffIntegrable hpayment, h⟩⟩

/-- Some action meets the outside option. -/
def OffersParticipation (outsideOption : ℝ)
    (payment : Outcome → ℝ) : Prop :=
  ∃ action, I.Participates outsideOption payment action

/-- Accounting needs reward and payment separately integrable, even though
principal utility alone only needs their difference integrable. -/
theorem principalUtility_add_agentUtility
    (payment : Outcome → ℝ) (action : Action)
    (hreward : PayoffIntegrable (I.outcomeLaw action) I.reward)
    (hpayment : PayoffIntegrable (I.outcomeLaw action) payment) :
    I.principalUtility payment action + I.agentUtility payment action =
      I.socialSurplus action := by
  unfold principalUtility agentUtility expectedPayment socialSurplus expectedReward
  rw [expect_sub hreward hpayment]
  ring

theorem agentUtility_ge (payment : Outcome → ℝ)
    (hpayment : IsLimitedLiability payment) (action : Action) :
    -I.cost action ≤ I.agentUtility payment action := by
  have hnonneg : 0 ≤ I.expectedPayment payment action := by
    exact expect_nonneg (I.outcomeLaw action) payment
      (fun outcome _ => hpayment outcome)
  unfold agentUtility
  linarith

theorem linearPayment_limitedLiability {α : ℝ} (hα : 0 ≤ α)
    (hreward : ∀ outcome, 0 ≤ I.reward outcome) :
    IsLimitedLiability (I.linearPayment α) :=
  fun outcome => mul_nonneg hα (hreward outcome)

theorem agentUtility_linearPayment (α : ℝ) (action : Action) :
    I.agentUtility (I.linearPayment α) action =
      α * I.expectedReward action - I.cost action := by
  unfold agentUtility expectedPayment linearPayment expectedReward
  rw [expect_const_mul]

theorem principalUtility_linearPayment (α : ℝ) (action : Action) :
    I.principalUtility (I.linearPayment α) action =
      (1 - α) * I.expectedReward action := by
  have hvalue : ∀ outcome ∈ (I.outcomeLaw action).support,
      I.reward outcome - I.linearPayment α outcome =
        (1 - α) * I.reward outcome := by
    intro outcome _
    simp [linearPayment]
    ring
  unfold principalUtility expectedReward
  calc
    expect (I.outcomeLaw action)
        (fun outcome => I.reward outcome - I.linearPayment α outcome) =
      expect (I.outcomeLaw action)
        (fun outcome => (1 - α) * I.reward outcome) :=
      expect_congr_on_support hvalue
    _ = (1 - α) * expect (I.outcomeLaw action) I.reward :=
      expect_const_mul

theorem agentUtility_linearPayment_one (action : Action) :
    I.agentUtility (I.linearPayment 1) action =
      I.socialSurplus action := by
  rw [I.agentUtility_linearPayment 1 action]
  simp [socialSurplus]

/-- Full commission leaves the principal a zero net payoff without requiring
the reward itself to be integrable. -/
theorem principalUtility_linearPayment_one (action : Action) :
    PayoffIntegrable (I.outcomeLaw action)
        (fun outcome => I.reward outcome - I.linearPayment 1 outcome) ∧
      I.principalUtility (I.linearPayment 1) action = 0 := by
  have hzero : ∀ outcome ∈ (I.outcomeLaw action).support,
      I.reward outcome - I.linearPayment 1 outcome = 0 := by
    intro outcome _
    simp [linearPayment]
  have hnet : PayoffIntegrable (I.outcomeLaw action)
      (fun outcome => I.reward outcome - I.linearPayment 1 outcome) :=
    payoffIntegrable_congr_on_support
      (fun outcome hs => (hzero outcome hs).symm)
      (payoffIntegrable_zero (I.outcomeLaw action))
  refine ⟨hnet, ?_⟩
  unfold principalUtility
  calc
    expect (I.outcomeLaw action)
        (fun outcome => I.reward outcome - I.linearPayment 1 outcome) =
      expect (I.outcomeLaw action) (fun _ => 0) :=
      expect_congr_on_support hzero
    _ = 0 := expect_zero _

/-- A finite action set has a best agent action when every alternative
payment expectation exists. -/
theorem exists_incentivized [Finite Action] [Nonempty Action]
    (payment : Outcome → ℝ)
    (hpayment : ∀ action, HasExpectation (I.outcomeLaw action) payment) :
    ∃ action, I.IsIncentivized payment action := by
  obtain ⟨action, hbest⟩ :=
    Finite.exists_max (fun alternative =>
      I.extendedAgentUtility payment alternative)
  exact ⟨action, hpayment, hbest⟩

theorem isIncentivized_linearPayment_one_iff
    (action : Action)
    (hreward : ∀ alternative, PayoffIntegrable
      (I.outcomeLaw alternative) I.reward) :
    I.IsIncentivized (I.linearPayment 1) action ↔
      ∀ alternative,
        I.socialSurplus alternative ≤
          I.socialSurplus action := by
  rw [I.isIncentivized_iff_of_integrable (payment := I.linearPayment 1) fun candidate =>
    payoffIntegrable_const_mul (c := (1 : ℝ)) (hreward candidate)]
  simp only [I.agentUtility_linearPayment_one]

theorem agentUtility_mono (payment payment' : Outcome → ℝ)
    (hpayment : ∀ outcome, payment outcome ≤ payment' outcome)
    (action : Action)
    (hfirst : PayoffIntegrable (I.outcomeLaw action) payment)
    (hsecond : PayoffIntegrable (I.outcomeLaw action) payment') :
    I.agentUtility payment action ≤
      I.agentUtility payment' action := by
  have h := expect_mono
    (μ := I.outcomeLaw action) (f := payment) (g := payment')
    (fun outcome _ => hpayment outcome) hfirst hsecond
  unfold agentUtility expectedPayment
  linarith

theorem participates_of_offersParticipation_of_isIncentivized
    {outsideOption : ℝ} {payment : Outcome → ℝ} {action : Action}
    (hoffers : I.OffersParticipation outsideOption payment)
    (hincentive : I.IsIncentivized payment action) :
    I.Participates outsideOption payment action := by
  obtain ⟨alternative, -, hparticipates⟩ := hoffers
  obtain ⟨hpayment, hbest⟩ := hincentive
  exact ⟨hpayment action, le_trans hparticipates (hbest alternative)⟩

/-- A limited-liability payment has an expectation, possibly infinite, so a
costless action already meets a zero outside option. -/
theorem offersParticipation_zero_of_costless_of_limitedLiability
    (payment : Outcome → ℝ) (hpayment : IsLimitedLiability payment)
    {costless : Action} (hcostless : I.cost costless = 0) :
    I.OffersParticipation 0 payment := by
  refine ⟨costless, hasExpectation_of_nonneg fun outcome _ => hpayment outcome, ?_⟩
  have hnonneg := extendedExpect_mono (μ := I.outcomeLaw costless)
    (f := fun _ => (0 : ℝ)) (g := payment) fun outcome _ => hpayment outcome
  rw [extendedExpect_constant] at hnonneg
  rwa [extendedAgentUtility, hcostless, EReal.coe_zero, sub_zero]

theorem participates_zero_of_costless_of_limitedLiability_of_isIncentivized
    (payment : Outcome → ℝ) (hpayment : IsLimitedLiability payment)
    {costless : Action} (hcostless : I.cost costless = 0)
    {action : Action} (hincentive : I.IsIncentivized payment action) :
    I.Participates 0 payment action :=
  I.participates_of_offersParticipation_of_isIncentivized
    (I.offersParticipation_zero_of_costless_of_limitedLiability
      payment hpayment hcostless) hincentive

theorem principalUtility_le_socialSurplus_sub_outsideOption
    (payment : Outcome → ℝ) {outsideOption : ℝ} {action : Action}
    (hreward : PayoffIntegrable (I.outcomeLaw action) I.reward)
    (hpayment : PayoffIntegrable (I.outcomeLaw action) payment)
    (hparticipates : I.Participates outsideOption payment action) :
    I.principalUtility payment action ≤
      I.socialSurplus action - outsideOption := by
  have houtside := (I.participates_iff_of_integrable hpayment).1 hparticipates
  have haccount :=
    I.principalUtility_add_agentUtility payment action hreward hpayment
  linarith

theorem principalUtility_le_socialSurplus_of_participates_zero
    (payment : Outcome → ℝ) {action : Action}
    (hreward : PayoffIntegrable (I.outcomeLaw action) I.reward)
    (hpayment : PayoffIntegrable (I.outcomeLaw action) payment)
    (hparticipates : I.Participates 0 payment action) :
    I.principalUtility payment action ≤
      I.socialSurplus action := by
  simpa using I.principalUtility_le_socialSurplus_sub_outsideOption
    payment hreward hpayment hparticipates

theorem principalUtility_eq_socialSurplus_sub_outsideOption_iff
    (payment : Outcome → ℝ) (outsideOption : ℝ) (action : Action)
    (hreward : PayoffIntegrable (I.outcomeLaw action) I.reward)
    (hpayment : PayoffIntegrable (I.outcomeLaw action) payment) :
    I.principalUtility payment action =
        I.socialSurplus action - outsideOption ↔
      I.agentUtility payment action = outsideOption := by
  have haccount :=
    I.principalUtility_add_agentUtility payment action hreward hpayment
  constructor <;> intro he <;> linarith

theorem principalUtility_eq_socialSurplus_iff
    (payment : Outcome → ℝ) (action : Action)
    (hreward : PayoffIntegrable (I.outcomeLaw action) I.reward)
    (hpayment : PayoffIntegrable (I.outcomeLaw action) payment) :
    I.principalUtility payment action =
        I.socialSurplus action ↔
      I.agentUtility payment action = 0 := by
  simpa using I.principalUtility_eq_socialSurplus_sub_outsideOption_iff
    payment 0 action hreward hpayment

theorem principalUtility_le_firstBest [Finite Action] [Nonempty Action]
    (payment : Outcome → ℝ) {outsideOption : ℝ} {action : Action}
    (hreward : ∀ alternative, PayoffIntegrable
      (I.outcomeLaw alternative) I.reward)
    (hpayment : PayoffIntegrable (I.outcomeLaw action) payment)
    (hparticipates : I.Participates outsideOption payment action) :
    ∃ best : Action,
      (∀ alternative,
        I.socialSurplus alternative ≤
          I.socialSurplus best) ∧
      I.principalUtility payment action ≤
        I.socialSurplus best - outsideOption := by
  obtain ⟨best, hbest⟩ :=
    Finite.exists_max (fun candidate => I.socialSurplus candidate)
  refine ⟨best, hbest, ?_⟩
  exact le_trans
    (I.principalUtility_le_socialSurplus_sub_outsideOption
      payment (hreward action) hpayment hparticipates)
    (sub_le_sub_right (hbest action) outsideOption)

theorem principalUtility_le_firstBest_zero [Finite Action] [Nonempty Action]
    (payment : Outcome → ℝ) {action : Action}
    (hreward : ∀ alternative, PayoffIntegrable
      (I.outcomeLaw alternative) I.reward)
    (hpayment : PayoffIntegrable (I.outcomeLaw action) payment)
    (hparticipates : I.Participates 0 payment action) :
    ∃ best : Action,
      (∀ alternative,
        I.socialSurplus alternative ≤
          I.socialSurplus best) ∧
      I.principalUtility payment action ≤
        I.socialSurplus best := by
  simpa using I.principalUtility_le_firstBest
    payment hreward hpayment hparticipates

end PrincipalAgent

end GameTheory.Mechanism
