/-
Copyright (c) 2025 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/

import GameTheory.Concepts.Knowledge.ApproximateCommonKnowledge
import GameTheory.Mechanism.Bayesian.BayesianGame
import Mathlib.Probability.Distributions.Uniform
import Mathlib.Tactic.NormNum

/-!
# A finite electronic-mail coordination example

This file gives a compact finite version of Rubinstein's electronic-mail
lesson.  The example has three possible worlds:

* no message;
* only player `true` receives the first message;
* both players receive the confirmation.

The candidate coordinated-attack rule says to attack exactly when a message is
seen.  It fails Bayes-Nash: player `true`, after seeing a message, still cannot
distinguish the one-sided-message world from the two-sided-message world.  Under
the uniform prior, attacking on that information set has negative ex-ante value,
so switching to never attack is profitable.  The payoff-relevant event is that
the first message was sent; at the two-message endpoint this event is mutually
believed but not common `p`-belief for thresholds above `1 / 2`.

This is intentionally a finite worked example, in the style of
`AbsentMindedDriver.lean`, rather than a full parametric formalization of
Rubinstein's infinite email chain.
-/

namespace GameTheory
namespace ElectronicMailGame

noncomputable section

/-- Finite endpoint worlds for the email exchange. -/
inductive EmailWorld where
  | noMessage
  | onlyFirst
  | bothConfirmed
deriving DecidableEq, Repr, Fintype

instance : Nonempty EmailWorld := ⟨EmailWorld.noMessage⟩

/-- A player's private email observation. -/
inductive EmailView where
  | quiet
  | message
deriving DecidableEq, Repr, Fintype

/-- The action in the coordinated-attack game. -/
inductive EmailAction where
  | stay
  | attack
deriving DecidableEq, Repr, Fintype

open EmailWorld EmailView EmailAction

/-- Player observations generated by the finite email worlds. -/
def viewOf : EmailWorld → Bool → EmailView
  | noMessage, _ => quiet
  | onlyFirst, true => message
  | onlyFirst, false => quiet
  | bothConfirmed, _ => message

/-- The type profile associated with a world. -/
def typeProfile (w : EmailWorld) : Bool → EmailView :=
  fun i => viewOf w i

/-- Uniform finite prior over the three endpoint worlds, pushed to type profiles. -/
def emailPrior : PMF (Bool → EmailView) :=
  PMF.map typeProfile (PMF.uniformOfFintype EmailWorld)

/-- The payoff-relevant event: the first message was sent. -/
abbrev attackState (θ : Bool → EmailView) : Prop :=
  θ true = message

/-- Payoffs: successful joint attack in the attack state gives `1`; any attack
outside that case costs `2`; staying gives `0`. -/
def emailUtility (θ : Bool → EmailView) (a : Bool → EmailAction) (i : Bool) : ℝ :=
  if a i = stay then 0
  else if attackState θ ∧ a true = attack ∧ a false = attack then 1
  else -2

/-- The finite Bayesian game induced by the email observations. -/
def game : BayesianGame Bool where
  Θ := fun _ => EmailView
  Act := fun _ => EmailAction
  prior := emailPrior
  utility := emailUtility

/-- The tempting coordinated-attack rule: attack iff a message is observed. -/
def attackOnMessage : game.BProfile :=
  fun _ θ =>
    match θ with
    | quiet => stay
    | message => attack

/-- Player `true`'s deviation: never attack. -/
def trueNeverAttack : game.Strategy true :=
  fun _ => stay

/-- Real-valued uniform prior over worlds for the partition/common-belief API. -/
def worldPrior (_w : EmailWorld) : ℝ := 1 / 3

/-- The finite information partition induced by each player's private view. -/
def emailPartition (i : Bool) : InfoPartition EmailWorld where
  cell w := Finset.univ.filter fun v => viewOf v i = viewOf w i
  reflexive w := by simp
  coherent w v hv := by
    ext u
    simp only [Finset.mem_filter, Finset.mem_univ, true_and] at hv ⊢
    rw [hv]

/-- World-level attack-state event. -/
def attackStateEvent : Finset EmailWorld := {onlyFirst, bothConfirmed}

@[simp] theorem viewOf_noMessage (i : Bool) :
    viewOf noMessage i = quiet := by
  cases i <;> rfl

@[simp] theorem viewOf_onlyFirst_true :
    viewOf onlyFirst true = message := rfl

@[simp] theorem viewOf_onlyFirst_false :
    viewOf onlyFirst false = quiet := rfl

@[simp] theorem viewOf_bothConfirmed (i : Bool) :
    viewOf bothConfirmed i = message := by
  cases i <;> rfl

private theorem EmailWorld_univ :
    (Finset.univ : Finset EmailWorld) =
      {noMessage, onlyFirst, bothConfirmed} := by
  ext w
  cases w <;> simp

/-- At the two-message endpoint, the attack state is mutually `p`-believed for
every threshold at most `1`. -/
theorem bothConfirmed_mem_mutualPBelief_attackStateEvent {p : ℝ} (hp : p ≤ 1) :
    bothConfirmed ∈ mutualPBelief worldPrior emailPartition p attackStateEvent := by
  rw [mem_mutualPBelief_iff]
  intro i
  cases i
  · unfold posterior worldPrior attackStateEvent
    rw [show (emailPartition false).cell bothConfirmed = {bothConfirmed} by decide]
    simp
    linarith
  · unfold posterior worldPrior attackStateEvent
    rw [show (emailPartition true).cell bothConfirmed = {onlyFirst, bothConfirmed} by decide]
    simp
    linarith

/-- The finite email chain does not make the attack state common `p`-belief at
the two-message endpoint for thresholds above `1 / 2`.  This is the finite
worked-example version of the electronic-mail caution: mutual high confidence
does not by itself create the common-belief support required by coordinated
attack arguments. -/
theorem not_commonPBeliefAt_attackStateEvent_bothConfirmed_of_half_lt
    {p : ℝ} (hp : (1 / 2 : ℝ) < p) :
    ¬ CommonPBeliefAt worldPrior emailPartition p attackStateEvent bothConfirmed := by
  intro h
  rcases h with ⟨F, hbothF, hEvident, hFmutual⟩
  have hOnlyF : onlyFirst ∈ F := by
    have hb := hEvident true hbothF
    rw [mem_PBelief_iff] at hb
    by_contra hnot
    have hpost : posterior worldPrior (emailPartition true) F bothConfirmed = (1 / 2 : ℝ) := by
      unfold posterior worldPrior
      rw [show (emailPartition true).cell bothConfirmed = {onlyFirst, bothConfirmed} by decide]
      rw [show {onlyFirst, bothConfirmed} ∩ F = {bothConfirmed} by
        ext w
        cases w <;> simp [hbothF, hnot]]
      simp
      norm_num
    linarith
  have hNoF : noMessage ∈ F := by
    have ho := hEvident false hOnlyF
    rw [mem_PBelief_iff] at ho
    by_contra hnot
    have hpost : posterior worldPrior (emailPartition false) F onlyFirst = (1 / 2 : ℝ) := by
      unfold posterior worldPrior
      rw [show (emailPartition false).cell onlyFirst = {noMessage, onlyFirst} by decide]
      rw [show {noMessage, onlyFirst} ∩ F = {onlyFirst} by
        ext w
        cases w <;> simp [hOnlyF, hnot]]
      simp
      norm_num
    linarith
  have hNoMutual := hFmutual hNoF
  rw [mem_mutualPBelief_iff] at hNoMutual
  have hTrue := hNoMutual true
  have hpost0 : posterior worldPrior (emailPartition true) attackStateEvent noMessage = 0 := by
    unfold posterior worldPrior attackStateEvent
    rw [show (emailPartition true).cell noMessage = {noMessage} by decide]
    simp
  linarith

/-- Under the candidate rule, player `true`'s ex-ante value is negative. -/
theorem exAnte_attackOnMessage_true :
    game.exAnteEU attackOnMessage true = (-1 / 3 : ℝ) := by
  unfold game BayesianGame.exAnteEU emailPrior
  rw [Math.Probability.expect_map_fintype_source]
  rw [EmailWorld_univ]
  simp only [PMF.uniformOfFintype_apply, ENNReal.toReal_inv, ENNReal.toReal_natCast,
    Finset.mem_insert, reduceCtorEq, Finset.mem_singleton, or_self,
    not_false_eq_true, Finset.sum_insert, Finset.sum_singleton]
  have hcard : Fintype.card EmailWorld = 3 := by decide
  rw [hcard]
  simp only [Nat.cast_ofNat, emailUtility, attackState, attackOnMessage, typeProfile,
    viewOf_noMessage, reduceIte, mul_zero, viewOf_onlyFirst_true, reduceCtorEq,
    viewOf_onlyFirst_false, and_false, mul_neg, viewOf_bothConfirmed, and_self,
    mul_one, zero_add]
  norm_num

/-- If player `true` deviates to never attacking, their ex-ante value is zero. -/
theorem exAnte_trueNeverAttack :
    game.exAnteEU (Function.update attackOnMessage true trueNeverAttack) true = 0 := by
  unfold game BayesianGame.exAnteEU emailPrior
  rw [Math.Probability.expect_map_fintype_source]
  rw [EmailWorld_univ]
  simp [trueNeverAttack, emailUtility, PMF.uniformOfFintype_apply, Function.update]

/-- The coordinated-attack-on-message rule is not Bayes-Nash in the finite
email game. -/
theorem attackOnMessage_not_bayesNash :
    ¬ game.BayesNash attackOnMessage := by
  intro hN
  have hdev :=
    (game.bayesNash_iff_exAnteEU attackOnMessage).1 hN true trueNeverAttack
  rw [exAnte_attackOnMessage_true, exAnte_trueNeverAttack] at hdev
  norm_num at hdev

end

end ElectronicMailGame
end GameTheory
