/-
# The finite Electronic Mail example

One finite law on endpoint worlds supplies both the Bayesian type prior and the
epistemic posterior model. The confirmed endpoint separates mutual from common
belief, and the tempting attack-on-message plan fails ordinary Nash equilibrium
of the direct Bayesian form.
-/

import GameTheory.Core.BayesianEquilibrium
import GameTheory.Epistemic.Approximate
import GameTheory.Math.Probability.Uniform
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.NormNum

noncomputable section

namespace GameTheory.Examples.ElectronicMail

open GameTheory.Math.Probability GameTheory.Epistemic

set_option backward.isDefEq.respectTransparency false in
/-- Finite endpoint worlds for the email exchange. -/
inductive EmailWorld where
  | noMessage
  | onlyFirst
  | bothConfirmed
deriving DecidableEq, Repr, Fintype

instance : Nonempty EmailWorld := ⟨.noMessage⟩

set_option backward.isDefEq.respectTransparency false in
/-- A player's private email observation. -/
inductive EmailView where
  | quiet
  | message
deriving DecidableEq, Repr, Fintype

set_option backward.isDefEq.respectTransparency false in
/-- The action in the coordinated-attack game. -/
inductive EmailAction where
  | stay
  | attack
deriving DecidableEq, Repr, Fintype

open EmailWorld EmailView EmailAction

private theorem EmailWorld_univ :
    (Finset.univ : Finset EmailWorld) =
      {noMessage, onlyFirst, bothConfirmed} := by
  ext world
  cases world <;> simp

private theorem emailWorld_card : Fintype.card EmailWorld = 3 := by
  rw [← Finset.card_univ, EmailWorld_univ]
  norm_num

/-- One canonical uniform law on the three endpoint worlds. -/
def worldPrior : PMF EmailWorld :=
  PMF.uniformOfFintype EmailWorld

/-- Player observations generated by the endpoint worlds. -/
def viewOf : EmailWorld → Bool → EmailView
  | noMessage, _ => quiet
  | onlyFirst, true => message
  | onlyFirst, false => quiet
  | bothConfirmed, _ => message

/-- The type profile associated with a world. -/
def typeProfile (world : EmailWorld) : Bool → EmailView :=
  fun player => viewOf world player

/-- The Bayesian type prior is the pushforward of the same world law used by
the epistemic model. -/
def emailPrior : PMF (Bool → EmailView) :=
  worldPrior.map typeProfile

/-- The payoff-relevant event: the first message was sent. -/
abbrev attackState (types : Bool → EmailView) : Prop :=
  types true = message

/-- Successful joint attack in the attack state pays one; any other attack
costs two; staying pays zero. -/
def emailPayoff (types : Bool → EmailView)
    (actions : Bool → EmailAction) (player : Bool) : ℝ :=
  if actions player = stay then 0
  else if attackState types ∧
      actions true = attack ∧ actions false = attack then 1
  else -2

/-- The finite Bayesian game induced by the email observations. -/
@[reducible]
def game : BayesianGame Bool where
  Ty _ := EmailView
  Act _ := EmailAction
  prior := emailPrior
  payoff := emailPayoff

/-- Attack exactly when a message is observed. -/
def attackOnMessage : Profile game.signature :=
  fun _ view =>
    match view with
    | quiet => stay
    | message => attack

/-- Player `true`'s deviation: never attack. -/
def trueNeverAttack : game.signature.Strategy true :=
  fun _ => stay

/-- The finite information partition induced by private views. -/
def emailPartition (player : Bool) : Setoid EmailWorld where
  r first second := viewOf first player = viewOf second player
  iseqv := ⟨fun _ => rfl, fun {_ _} h => h.symm,
    fun {_ _ _} h₁ h₂ => h₁.trans h₂⟩

@[simp]
theorem emailCell_true_confirmed :
    cell (emailPartition true) bothConfirmed = {onlyFirst, bothConfirmed} := by
  ext world
  show (viewOf bothConfirmed true = viewOf world true) ↔
    world = onlyFirst ∨ world = bothConfirmed
  cases world <;> simp [viewOf]

@[simp]
theorem emailCell_false_confirmed :
  cell (emailPartition false) bothConfirmed = {bothConfirmed} := by
  ext world
  show (viewOf bothConfirmed false = viewOf world false) ↔
    world = bothConfirmed
  cases world <;> simp [viewOf]

@[simp]
theorem emailCell_true_first :
  cell (emailPartition true) onlyFirst = {onlyFirst, bothConfirmed} := by
  ext world
  show (viewOf onlyFirst true = viewOf world true) ↔
    world = onlyFirst ∨ world = bothConfirmed
  cases world <;> simp [viewOf]

@[simp]
theorem emailCell_false_first :
  cell (emailPartition false) onlyFirst = {noMessage, onlyFirst} := by
  ext world
  show (viewOf onlyFirst false = viewOf world false) ↔
    world = noMessage ∨ world = onlyFirst
  cases world <;> simp [viewOf]

@[simp]
theorem emailCell_true_noMessage :
  cell (emailPartition true) noMessage = {noMessage} := by
  ext world
  show (viewOf noMessage true = viewOf world true) ↔ world = noMessage
  cases world <;> simp [viewOf]

/-- World-level event that the first message was sent. -/
def attackStateEvent : Set EmailWorld :=
  {world | world = onlyFirst ∨ world = bothConfirmed}

private theorem worldMass_singleton (world : EmailWorld) :
    worldPrior.toOuterMeasure {world} = (1 / 3 : ENNReal) := by
  classical
  rw [worldPrior, PMF.toOuterMeasure_uniformOfFintype_apply]
  rw [emailWorld_card]
  norm_num

private theorem worldMass_messagePair :
    worldPrior.toOuterMeasure {onlyFirst, bothConfirmed} =
      (2 / 3 : ENNReal) := by
  classical
  rw [worldPrior, PMF.toOuterMeasure_uniformOfFintype_apply]
  rw [emailWorld_card]
  norm_num

private theorem worldMass_quietPair :
    worldPrior.toOuterMeasure {noMessage, onlyFirst} =
      (2 / 3 : ENNReal) := by
  classical
  rw [worldPrior, PMF.toOuterMeasure_uniformOfFintype_apply]
  rw [emailWorld_card]
  norm_num

@[simp]
theorem viewOf_noMessage (player : Bool) :
    viewOf noMessage player = quiet := by
  cases player <;> rfl

@[simp]
theorem viewOf_onlyFirst_true :
    viewOf onlyFirst true = message := rfl

@[simp]
theorem viewOf_onlyFirst_false :
    viewOf onlyFirst false = quiet := rfl

@[simp]
theorem viewOf_bothConfirmed (player : Bool) :
    viewOf bothConfirmed player = message := by
  cases player <;> rfl

/-- At the confirmed endpoint, the attack state is mutually believed for every
threshold at most one. -/
theorem bothConfirmed_mem_mutualPBelief_attackStateEvent
    {threshold : ℝ} (hthreshold : threshold ≤ 1) :
    bothConfirmed ∈
      mutualPBelief worldPrior emailPartition threshold attackStateEvent := by
  rw [mem_mutualPBelief_iff]
  intro player
  cases player
  ·
    have hposterior := posterior_eq_one_of_cell_subset_of_cell_mass_pos
      worldPrior (emailPartition false)
        (event := attackStateEvent) (state := bothConfirmed) (by
          intro world hworld
          have hview :
              viewOf bothConfirmed false = viewOf world false := hworld
          cases world <;> simp_all [attackStateEvent, viewOf])
        (by
          apply outerMeasure_pos_of_mem_support bothConfirmed
          · simp [cell]
          · simp [worldPrior])
    rw [hposterior]
    exact hthreshold
  ·
    have hposterior := posterior_eq_one_of_cell_subset_of_cell_mass_pos
      worldPrior (emailPartition true)
        (event := attackStateEvent) (state := bothConfirmed) (by
          intro world hworld
          have hview :
              viewOf bothConfirmed true = viewOf world true := hworld
          cases world <;> simp_all [attackStateEvent, viewOf])
        (by
          apply outerMeasure_pos_of_mem_support bothConfirmed
          · simp [cell]
          · simp [worldPrior])
    rw [hposterior]
    exact hthreshold

/-- Above threshold one half, the attack state is not common belief at the
confirmed endpoint. -/
theorem not_commonPBeliefAt_attackStateEvent_bothConfirmed_of_half_lt
    {threshold : ℝ} (hthreshold : (1 / 2 : ℝ) < threshold) :
    ¬ CommonPBeliefAt worldPrior emailPartition threshold
      attackStateEvent bothConfirmed := by
  rintro ⟨witness, hboth, hevident, hmutual⟩
  have honly : onlyFirst ∈ witness := by
    have hbelief := hevident true hboth
    rw [mem_PBelief_iff] at hbelief
    by_contra hnot
    have hposterior :
      posterior worldPrior (emailPartition true) witness bothConfirmed =
          (1 / 2 : ℝ) := by
      unfold posterior
      rw [emailCell_true_confirmed]
      rw [show witness ∩ {onlyFirst, bothConfirmed} =
        {bothConfirmed} by
          ext world
          cases world <;> simp [hboth, hnot]]
      rw [worldMass_singleton, worldMass_messagePair]
      norm_num
    linarith
  have hnoMessage : noMessage ∈ witness := by
    have hbelief := hevident false honly
    rw [mem_PBelief_iff] at hbelief
    by_contra hnot
    have hposterior :
      posterior worldPrior (emailPartition false) witness onlyFirst =
          (1 / 2 : ℝ) := by
      unfold posterior
      rw [emailCell_false_first]
      rw [show witness ∩ {noMessage, onlyFirst} = {onlyFirst} by
        ext world
        cases world <;> simp [honly, hnot]]
      rw [worldMass_singleton, worldMass_quietPair]
      norm_num
    linarith
  have hnoMutual := hmutual hnoMessage
  rw [mem_mutualPBelief_iff] at hnoMutual
  have htrue := hnoMutual true
  have hposterior :
      posterior worldPrior (emailPartition true)
        attackStateEvent noMessage = 0 := by
    unfold posterior attackStateEvent
    rw [emailCell_true_noMessage]
    have hinter :
        {world | world = onlyFirst ∨ world = bothConfirmed} ∩
            ({noMessage} : Set EmailWorld) = ∅ := by
      ext world
      cases world <;> simp
    rw [hinter]
    simp
  linarith

/-- Under the candidate rule, player `true`'s ex-ante value is negative. -/
theorem expectedUtility_attackOnMessage_true :
    expectedUtility game.utility true
      (game.toForm.play attackOnMessage)
      (payoffIntegrable_of_finite _ _) = (-1 / 3 : ℝ) := by
  rw [game.expectedUtility_eq_prior true attackOnMessage
    (payoffIntegrable_of_finite _ _)]
  simp only [game, emailPrior]
  rw [expect_map typeProfile worldPrior _ (payoffIntegrable_of_finite _ _)
    (payoffIntegrable_of_finite _ _)]
  have hplan :
      (game.planPayoff true attackOnMessage) ∘ typeProfile =
        fun world : EmailWorld =>
          emailPayoff (typeProfile world)
            (fun i => attackOnMessage i (typeProfile world i)) true := by
    funext world
    rfl
  simp only [game] at hplan
  simp only [emailPrior] at hplan
  rw [hplan]
  calc
    expect worldPrior
        (fun world : EmailWorld =>
          emailPayoff (typeProfile world)
            (fun i => attackOnMessage i (typeProfile world i)) true)
        (payoffIntegrable_of_finite _ _) =
      (∑ world : EmailWorld,
        emailPayoff (typeProfile world)
          (fun i => attackOnMessage i (typeProfile world i)) true) /
          (Fintype.card EmailWorld : ℝ) := by
        simpa only [worldPrior] using expect_uniformOfFintype
          (fun world : EmailWorld =>
            emailPayoff (typeProfile world)
              (fun i => attackOnMessage i (typeProfile world i)) true)
    _ = -1 / 3 := by
      rw [emailWorld_card]
      norm_num [emailPayoff, attackState, attackOnMessage, typeProfile, viewOf,
        EmailWorld_univ]

/-- If player `true` deviates to never attacking, its ex-ante value is zero. -/
theorem expectedUtility_trueNeverAttack :
    expectedUtility game.utility true
      (game.toForm.play
        (Profile.update attackOnMessage true trueNeverAttack))
      (payoffIntegrable_of_finite _ _) = 0 := by
  rw [game.expectedUtility_eq_prior true
    (Profile.update attackOnMessage true trueNeverAttack)
    (payoffIntegrable_of_finite _ _)]
  simp only [game, emailPrior]
  rw [expect_map typeProfile worldPrior _ (payoffIntegrable_of_finite _ _)
    (payoffIntegrable_of_finite _ _)]
  have hplan :
      (game.planPayoff true
        (Profile.update attackOnMessage true trueNeverAttack)) ∘ typeProfile =
        fun world : EmailWorld =>
          emailPayoff (typeProfile world)
            (fun i =>
              (Profile.update attackOnMessage true trueNeverAttack i)
                (typeProfile world i)) true := by
    funext world
    rfl
  simp only [game] at hplan
  simp only [emailPrior] at hplan
  rw [hplan]
  calc
    expect worldPrior
        (fun world : EmailWorld =>
          emailPayoff (typeProfile world)
            (fun i =>
              (Profile.update attackOnMessage true trueNeverAttack i)
                (typeProfile world i)) true)
        (payoffIntegrable_of_finite _ _) =
      (∑ world : EmailWorld,
        emailPayoff (typeProfile world)
          (fun i =>
            (Profile.update attackOnMessage true trueNeverAttack i)
              (typeProfile world i)) true) /
          (Fintype.card EmailWorld : ℝ) := by
        simpa only [worldPrior] using expect_uniformOfFintype
          (fun world : EmailWorld =>
            emailPayoff (typeProfile world)
              (fun i =>
                (Profile.update attackOnMessage true trueNeverAttack i)
                  (typeProfile world i)) true)
    _ = 0 := by
      rw [emailWorld_card]
      norm_num [emailPayoff, trueNeverAttack, typeProfile, viewOf,
        EmailWorld_univ]

/-- The attack-on-message rule is not Bayes-Nash, stated through the ordinary
Nash predicate of the canonical direct Bayesian form. -/
theorem attackOnMessage_not_isNash :
    ¬ IsNash game.toForm (euPreference game.utility) attackOnMessage := by
  intro hnash
  rw [isNash_iff] at hnash
  have hdeviation := hnash true trueNeverAttack
  rcases hdeviation with ⟨hpreferred, halternative, hle⟩
  have hpreferredValue : expectedUtility game.utility true
      (game.toForm.play attackOnMessage) hpreferred = -1 / 3 := by
    calc
      expectedUtility game.utility true (game.toForm.play attackOnMessage)
          hpreferred = expectedUtility game.utility true
            (game.toForm.play attackOnMessage) (payoffIntegrable_of_finite _ _) :=
          expectedUtility_congr_law game.utility true rfl hpreferred
            (payoffIntegrable_of_finite _ _)
      _ = -1 / 3 := expectedUtility_attackOnMessage_true
  have halternativeValue : expectedUtility game.utility true
      (game.toForm.play
        (Profile.update attackOnMessage true trueNeverAttack)) halternative = 0 := by
    calc
      expectedUtility game.utility true
          (game.toForm.play
            (Profile.update attackOnMessage true trueNeverAttack)) halternative =
        expectedUtility game.utility true
          (game.toForm.play
            (Profile.update attackOnMessage true trueNeverAttack))
          (payoffIntegrable_of_finite _ _) :=
            expectedUtility_congr_law game.utility true rfl halternative
              (payoffIntegrable_of_finite _ _)
      _ = 0 := expectedUtility_trueNeverAttack
  rw [halternativeValue, hpreferredValue] at hle
  norm_num at hle

end GameTheory.Examples.ElectronicMail
