import Math.GateGAmbientCriticalAlgebraicity
import Math.GateGGermChart

set_option autoImplicit false

noncomputable section

open Filter

namespace Math
namespace GateGSequenceCriticalAlgebraicity

open GateGAmbientCriticalAlgebraicity
open GateGGermChart
open GateGGermComponentScratch

/-- The real-coefficient inclusion into `ℝ(t)`, written explicitly through
constant polynomials. -/
def realToParameterFractionRing :
    ℝ →+* FractionRing (Polynomial ℝ) :=
  (algebraMap (Polynomial ℝ)
    (FractionRing (Polynomial ℝ))).comp
      Polynomial.C

/-- The real scalar embedding induced through the parameter field agrees
with the constant-real embedding into the sequence germ field. -/
theorem algebraMap_real_fractionRing_germ
    {σ : Type*}
    (x : ℕ → (σ → ℝ)) (parameter : σ)
    (hinjective :
      Function.Injective (fun n => x n parameter))
    (a : ℝ) :
    let K := FractionRing (Polynomial ℝ)
    letI : Algebra K GermField :=
      parameterFractionRingGermAlgebra
        x parameter hinjective
    algebraMap K GermField
        (realToParameterFractionRing a) =
      algebraMap ℝ GermField a := by
  dsimp only
  let K := FractionRing (Polynomial ℝ)
  letI : Algebra K GermField :=
    parameterFractionRingGermAlgebra
      x parameter hinjective
  rw [show
    (algebraMap K GermField) =
      parameterFractionRingGermHom
        x parameter hinjective by
      exact RingHom.algebraMap_toAlgebra _]
  change
    parameterFractionRingGermHom
        x parameter hinjective
        (algebraMap (Polynomial ℝ) K
          (Polynomial.C a)) =
      algebraMap ℝ GermField a
  rw [parameterFractionRingGermHom_algebraMap]
  rw [parameterGermEval_apply]
  change
    ((fun n =>
      (Polynomial.C a).eval (x n parameter)) :
      GermField) =
    ((fun _ : ℕ => a) : GermField)
  apply Filter.Germ.coe_eq.mpr
  exact Eventually.of_forall fun n => by simp

/-- Polynomial evaluation in the sequence germ field agrees with passing
the coefficients through the rational parameter field first. -/
theorem eval₂_map_real_fractionRing_germ
    {σ : Type*}
    (x : ℕ → (σ → ℝ)) (parameter : σ)
    (hinjective :
      Function.Injective (fun n => x n parameter))
    (P : MvPolynomial σ ℝ) :
    let K := FractionRing (Polynomial ℝ)
    letI : Algebra K GermField :=
      parameterFractionRingGermAlgebra
        x parameter hinjective
    MvPolynomial.eval₂
        (algebraMap K GermField)
        (fun k =>
          ((fun n => x n k) : GermField))
        (P.map realToParameterFractionRing) =
      sequenceGermEval x P := by
  dsimp only
  let K := FractionRing (Polynomial ℝ)
  letI : Algebra K GermField :=
    parameterFractionRingGermAlgebra
      x parameter hinjective
  rw [MvPolynomial.eval₂_map]
  change
    MvPolynomial.eval₂
        ((algebraMap K GermField).comp
          realToParameterFractionRing)
        (fun k =>
          ((fun n => x n k) : GermField)) P =
      sequenceGermEval x P
  rw [show
    (algebraMap K GermField).comp
        realToParameterFractionRing =
      algebraMap ℝ GermField by
        apply DFunLike.ext _ _
        intro a
        exact
          algebraMap_real_fractionRing_germ
            x parameter hinjective a]
  rfl

/--
An eventual normalized polynomial critical equation along a sequence makes
the objective germ algebraic over the rational field generated by the
strict parameter.

This is the sequence-level adapter between real Lagrange multipliers and
the ambient Kähler-differential algebraicity theorem.
-/
theorem isAlgebraic_objectiveGerm_of_eventually_normalCriticality
    {σ I : Type*} [Finite σ] [Fintype I]
    (x : ℕ → (σ → ℝ)) (parameter : σ)
    (hinjective :
      Function.Injective (fun n => x n parameter))
    (P : I → MvPolynomial σ ℝ)
    (Q : MvPolynomial σ ℝ)
    (Λ : ℕ → I → ℝ)
    (hzero :
      ∀ i,
        ∀ᶠ n in
          (sequenceUltrafilter : Filter ℕ),
          MvPolynomial.eval (x n) (P i) = 0)
    (hcritical :
      ∀ k,
        ∀ᶠ n in
          (sequenceUltrafilter : Filter ℕ),
          MvPolynomial.eval (x n)
              (MvPolynomial.pderiv k Q) =
            ∑ i : I,
              Λ n i *
                MvPolynomial.eval (x n)
                  (MvPolynomial.pderiv k (P i))) :
    let K := FractionRing (Polynomial ℝ)
    letI : Algebra K GermField :=
      parameterFractionRingGermAlgebra
        x parameter hinjective
    IsAlgebraic K (sequenceGermEval x Q) := by
  letI := Fintype.ofFinite σ
  dsimp only
  let K := FractionRing (Polynomial ℝ)
  letI : Algebra K GermField :=
    parameterFractionRingGermAlgebra
      x parameter hinjective
  let xg : σ → GermField :=
    fun k => ((fun n => x n k) : GermField)
  let Λg : I → GermField :=
    fun i => ((fun n => Λ n i) : GermField)
  have hzeroG :
      ∀ i,
        MvPolynomial.eval₂
            (algebraMap K GermField) xg
            ((P i).map realToParameterFractionRing) = 0 := by
    intro i
    rw [eval₂_map_real_fractionRing_germ
      x parameter hinjective (P i)]
    rw [sequenceGermEval_apply]
    apply Filter.Germ.coe_eq.mpr
    exact hzero i
  have hcriticalG :
      ∀ k,
        MvPolynomial.eval₂
            (algebraMap K GermField) xg
            (MvPolynomial.pderiv k
              ((Q).map realToParameterFractionRing)) =
          ∑ i : I,
            Λg i *
              MvPolynomial.eval₂
                (algebraMap K GermField) xg
                (MvPolynomial.pderiv k
                  ((P i).map realToParameterFractionRing)) := by
    intro k
    simp_rw [MvPolynomial.pderiv_map]
    rw [eval₂_map_real_fractionRing_germ
      x parameter hinjective
      (MvPolynomial.pderiv k Q)]
    have hPi :
        ∀ i : I,
          MvPolynomial.eval₂
              (algebraMap K GermField) xg
              ((MvPolynomial.pderiv k (P i)).map
                realToParameterFractionRing) =
            sequenceGermEval x
              (MvPolynomial.pderiv k (P i)) := by
      intro i
      exact
        eval₂_map_real_fractionRing_germ
          x parameter hinjective
          (MvPolynomial.pderiv k (P i))
    simp_rw [hPi]
    simp_rw [sequenceGermEval_apply]
    let φ :
        (ℕ → ℝ) →+* GermField :=
      Filter.Germ.coeRingHom
        (sequenceUltrafilter : Filter ℕ)
    change
      φ (fun n =>
          MvPolynomial.eval (x n)
            (MvPolynomial.pderiv k Q)) =
        ∑ i : I,
          φ (fun n => Λ n i) *
            φ (fun n =>
              MvPolynomial.eval (x n)
                (MvPolynomial.pderiv k (P i)))
    simp_rw [← map_mul]
    rw [← map_sum]
    apply Filter.Germ.coe_eq.mpr
    filter_upwards [hcritical k] with n hn
    simpa only [Finset.sum_apply, Pi.mul_apply] using hn
  have halg :
      IsAlgebraic K
        (MvPolynomial.eval₂
          (algebraMap K GermField) xg
          (Q.map realToParameterFractionRing)) :=
    isAlgebraic_of_equations_and_normalCriticality_in_ambient
      xg
      (fun i => (P i).map realToParameterFractionRing)
      hzeroG
      (Q.map realToParameterFractionRing)
      Λg hcriticalG
  rw [eval₂_map_real_fractionRing_germ
    x parameter hinjective Q] at halg
  exact halg

end GateGSequenceCriticalAlgebraicity
end Math
