/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/
import GameTheory.Concepts.Stochastic.FinkLimit

/-!
# The recurrent meaning of the Fink harmonic obstruction

This file isolates what the nonzero harmonic component of the limiting
Bellman forcing means.  It is exactly the discrepancy between the limiting
discounted value and the recurrent average stage payoff of the limiting
stationary profile.  It also records the corresponding obstruction to a
time-dependent correction: a common harmonic component can only be cancelled
by accumulating it in the correction (or in the one-step errors).
-/

noncomputable section

namespace GameTheory
namespace StochasticGame

open Filter
open Math.Probability Math.PMFProduct

variable {ι : Type}

/-- Stage-payoff vector of a decoded stationary Fink profile. -/
def finkStagePayoffVector (G : StochasticGame ι)
    [Fintype G.State] [Fintype ι] [∀ i, Fintype (G.Act i)]
    {U : ℝ} (z : G.finkDomain U) : G.State → Payoff ι :=
  fun s who => G.finkStageEU z s who

/-- The Bellman forcing is the value/stage-payoff discrepancy minus the
one-step coboundary generated by the limiting relative bias. -/
theorem finkBellmanForcingVector_eq_value_sub_stage_sub_residual
    (G : StochasticGame ι)
    [Fintype G.State] [Fintype ι] [∀ i, Fintype (G.Act i)]
    (W H : G.State → Payoff ι) {U : ℝ} (z : G.finkDomain U) :
    G.finkBellmanForcingVector W H z =
      W - G.finkStagePayoffVector z -
        G.finkContinuationResidualVector H z := by
  ext s who
  unfold finkBellmanForcingVector finkStagePayoffVector
    finkContinuationResidualVector finkContinuationResidual
  simp only [Pi.sub_apply]
  ring

/-- A harmonic decomposition of the limiting Bellman forcing is equivalently
a harmonic decomposition of `value - recurrent stage payoff`; the relative
bias merely changes the Poisson potential. -/
theorem value_sub_finkStagePayoffVector_eq_harmonic_add_residual
    (G : StochasticGame ι)
    [Fintype G.State] [Fintype ι] [∀ i, Fintype (G.Act i)]
    (W H O K : G.State → Payoff ι) {U : ℝ} (z : G.finkDomain U)
    (hdecomp : G.finkBellmanForcingVector W H z =
      O + G.finkContinuationResidualVector K z) :
    W - G.finkStagePayoffVector z =
      O + G.finkContinuationResidualVector (K + H) z := by
  rw [G.finkBellmanForcingVector_eq_value_sub_stage_sub_residual] at hdecomp
  rw [G.finkContinuationResidualVector_add]
  ext s who
  have hs := congrFun (congrFun hdecomp s) who
  simp only [Pi.sub_apply, Pi.add_apply] at hs ⊢
  linarith

/-- Absorbing the harmonic obstruction into the payoff target gives an exact
average-reward Bellman equation.  If
`F(W,H) = O + (P - I)K`, then the shifted target `W - O` and shifted bias
`H + K` solve `Y + B = r + P B` on the limiting stationary profile. -/
theorem finkShiftedTarget_averageRewardBellman_eq
    (G : StochasticGame ι)
    [Fintype G.State] [Fintype ι] [∀ i, Fintype (G.Act i)]
    (W H O K : G.State → Payoff ι) {U : ℝ} (z : G.finkDomain U)
    (hdecomp : G.finkBellmanForcingVector W H z =
      O + G.finkContinuationResidualVector K z) :
    ∀ s who,
      (W - O) s who + (H + K) s who =
        G.finkStageEU z s who +
          G.finkContinuationEU (H + K) z s who := by
  intro s who
  have heq := congrFun (congrFun
    (G.value_sub_finkStagePayoffVector_eq_harmonic_add_residual
      W H O K z hdecomp) s) who
  unfold finkStagePayoffVector finkContinuationResidualVector
    finkContinuationResidual at heq
  rw [add_comm H K]
  simp only [Pi.sub_apply, Pi.add_apply] at heq ⊢
  linarith

/-- Direct stationary verification for the shifted target.  This is the
positive branch behind a nonzero harmonic obstruction: no dynamic correction
is needed when `Y = W - O` is itself excessive and the shifted bias verifies
the continuation-neutral deviations. -/
theorem isUniformEquilibriumPayoff_finkShiftedTarget_of_neutral
    (G : StochasticGame ι) [Fintype G.State] [Fintype ι] [DecidableEq ι]
    [∀ i, Fintype (G.Act i)] (s₀ : G.State)
    (W H O K : G.State → Payoff ι) {U : ℝ} (z : G.finkDomain U)
    (hW : G.finkContinuationResidualVector W z = 0)
    (hO : G.finkContinuationResidualVector O z = 0)
    (hdecomp : G.finkBellmanForcingVector W H z =
      O + G.finkContinuationResidualVector K z)
    (hexcessive : ∀ s who (d : G.Act who),
      expect (pmfPi (Function.update (G.finkProfile z s) who (PMF.pure d)))
          (fun a => expect (G.transition s a)
            (fun s' => (W - O) s' who)) ≤
        (W - O) s who)
    (hneutral : ∀ s who (d : G.Act who),
      expect (pmfPi (Function.update (G.finkProfile z s) who (PMF.pure d)))
          (fun a => expect (G.transition s a)
            (fun s' => (W - O) s' who)) =
          (W - O) s who →
        G.mixedStageEU s
              (Function.update (G.finkProfile z s) who (PMF.pure d)) who +
            expect (pmfPi (Function.update (G.finkProfile z s)
              who (PMF.pure d)))
              (fun a => expect (G.transition s a)
                (fun s' => (H + K) s' who)) ≤
          (W - O) s who + (H + K) s who) :
    G.IsUniformEquilibriumPayoff s₀ ((W - O) s₀) := by
  apply G.isUniformEquilibriumPayoff_of_stationaryAverageRewardBias_on_neutral
    s₀ (G.finkProfile z) (W - O) (H + K)
  · intro s who
    have hWcoord := congrFun (congrFun hW s) who
    have hOcoord := congrFun (congrFun hO s) who
    unfold finkContinuationResidualVector finkContinuationResidual
      finkContinuationEU at hWcoord hOcoord
    simp only [Pi.zero_apply] at hWcoord hOcoord
    simp only [Pi.sub_apply]
    simp_rw [expect_sub]
    linarith
  · exact hexcessive
  · exact G.finkShiftedTarget_averageRewardBellman_eq
      W H O K z hdecomp
  · exact hneutral

/-- The recurrent average stage payoff of the limiting stationary profile is
`W - O`, where `O` is the canonical harmonic obstruction.  Thus a nonzero
obstruction is not a choice of Poisson normalization: it is a genuine mismatch
between the vanishing-discount value and the limiting recurrent payoff. -/
theorem tendsto_cesaro_finkStagePayoffVector_eq_value_sub_obstruction
    (G : StochasticGame ι)
    [Fintype G.State] [Fintype ι] [∀ i, Fintype (G.Act i)]
    (W H O K : G.State → Payoff ι) {U : ℝ} (z : G.finkDomain U)
    (hW : G.finkContinuationResidualVector W z = 0)
    (hO : G.finkContinuationResidualVector O z = 0)
    (hdecomp : G.finkBellmanForcingVector W H z =
      O + G.finkContinuationResidualVector K z) :
    ∀ who, Tendsto (fun T : ℕ =>
      (T : ℝ)⁻¹ • ∑ t ∈ Finset.range T,
        ((Math.MeanErgodic.markovOperator (G.finkStateKernel z)) ^ t)
          (fun s => G.finkStagePayoffVector z s who))
      atTop (nhds (fun s => W s who - O s who)) := by
  intro who
  let o : G.State → ℝ := fun s => W s who - O s who
  let u : G.State → ℝ := fun s => -(K s who + H s who)
  apply Math.MeanErgodic.tendsto_cesaro_of_harmonic_add_poisson
    (G.finkStateKernel z)
    (fun s => G.finkStagePayoffVector z s who) o u
  · intro s
    have hWcoord := congrFun (congrFun hW s) who
    have hOcoord := congrFun (congrFun hO s) who
    unfold finkContinuationResidualVector finkContinuationResidual
      finkContinuationEU at hWcoord hOcoord
    rw [← G.expect_finkStateKernel_eq z s (fun s' => W s' who)] at hWcoord
    rw [← G.expect_finkStateKernel_eq z s (fun s' => O s' who)] at hOcoord
    simp only [Pi.zero_apply] at hWcoord hOcoord
    dsimp only [o]
    rw [expect_sub]
    linarith
  · intro s
    have heq := congrFun (congrFun
      (G.value_sub_finkStagePayoffVector_eq_harmonic_add_residual
        W H O K z hdecomp) s) who
    unfold finkContinuationResidualVector finkContinuationResidual
      finkContinuationEU at heq
    simp only [Pi.sub_apply, Pi.add_apply] at heq
    rw [← G.expect_finkStateKernel_eq z s
      (fun s' => K s' who + H s' who)] at heq
    dsimp only [o, u]
    rw [show (fun s' => -(K s' who + H s' who)) =
      fun s' => (-1 : ℝ) * (K s' who + H s' who) by
        funext s'
        ring, expect_const_mul]
    linarith

/-- The harmonic obstruction vanishes exactly when the limiting discounted
value is the recurrent Cesàro stage payoff of the limiting stationary
profile. -/
theorem harmonicObstruction_eq_zero_iff_cesaro_stage_eq_value
    (G : StochasticGame ι)
    [Fintype G.State] [Fintype ι] [∀ i, Fintype (G.Act i)]
    (W H O K : G.State → Payoff ι) {U : ℝ} (z : G.finkDomain U)
    (hW : G.finkContinuationResidualVector W z = 0)
    (hO : G.finkContinuationResidualVector O z = 0)
    (hdecomp : G.finkBellmanForcingVector W H z =
      O + G.finkContinuationResidualVector K z) :
    O = 0 ↔ ∀ who, Tendsto (fun T : ℕ =>
      (T : ℝ)⁻¹ • ∑ t ∈ Finset.range T,
        ((Math.MeanErgodic.markovOperator (G.finkStateKernel z)) ^ t)
          (fun s => G.finkStagePayoffVector z s who))
      atTop (nhds (fun s => W s who)) := by
  constructor
  · intro hzero who
    have ht := G.tendsto_cesaro_finkStagePayoffVector_eq_value_sub_obstruction
      W H O K z hW hO hdecomp who
    simpa only [hzero, Pi.zero_apply, sub_zero] using ht
  · intro hstage
    have hcanonical :=
      G.tendsto_cesaro_finkStagePayoffVector_eq_value_sub_obstruction
        W H O K z hW hO hdecomp
    ext s who
    have heq : (fun s => W s who - O s who) = (fun s => W s who) :=
      tendsto_nhds_unique (hcanonical who) (hstage who)
    have hs := congrFun heq s
    simp only [Pi.zero_apply]
    linarith

/-- Amount of a harmonic forcing accumulated before calendar stage `t`. -/
def finkHarmonicCorrectionClock (c : ℕ → ℝ) (t : ℕ) : ℝ :=
  ∑ k ∈ Finset.range t, c k

theorem finkHarmonicCorrectionClock_succ (c : ℕ → ℝ) (t : ℕ) :
    finkHarmonicCorrectionClock c (t + 1) =
      finkHarmonicCorrectionClock c t + c t := by
  unfold finkHarmonicCorrectionClock
  rw [Finset.sum_range_succ]

@[simp] theorem finkHarmonicCorrectionClock_zero (c : ℕ → ℝ) :
    finkHarmonicCorrectionClock c 0 = 0 := by
  simp [finkHarmonicCorrectionClock]

/-- A state function harmonic for every profile used by a schedule has
constant expectation throughout that schedule. -/
theorem scheduled_expectedStateValue_harmonic_eq_initial
    (G : StochasticGame ι) [Fintype ι]
    [Finite G.State] [∀ i, Finite (G.Act i)]
    (x : ℕ → G.StationaryMixedProfile) (O : G.State → Payoff ι)
    (who : ι) (s₀ : G.State)
    (hharmonic : ∀ t s,
      expect (pmfPi (x t s)) (fun a =>
        expect (G.transition s a) (fun s' => O s' who)) = O s who)
    (T : ℕ) :
    G.expectedStateValue (G.scheduledMarkovBehaviorProfile x) s₀ T
      (fun s => O s who) = O s₀ who := by
  have hbound := G.scheduled_expectedTimeDependentStateValue_close_initial
    x (fun _ => O) (fun _ => 0) who s₀ (by
      intro t s
      rw [hharmonic t s]
      simp) T
  have hle : |G.expectedStateValue
      (G.scheduledMarkovBehaviorProfile x) s₀ T (fun s => O s who) -
        O s₀ who| ≤ 0 := by
    simpa using hbound
  exact sub_eq_zero.mp (abs_eq_zero.mp
    (le_antisymm hle (abs_nonneg _)))

/-- Exact telescope for a time-dependent correction facing a common
harmonic forcing.  The forcing is not cancelled for free: its cumulative
clock appears at the terminal endpoint.  This allows the scheduled profiles
to vary and already includes history-dependent state distributions. -/
theorem scheduled_harmonicCorrection_telescope
    (G : StochasticGame ι) [Fintype ι]
    [Finite G.State] [∀ i, Finite (G.Act i)]
    (x : ℕ → G.StationaryMixedProfile) (O : G.State → Payoff ι)
    (R : ℕ → G.State → Payoff ι) (c e : ℕ → ℝ)
    (who : ι) (s₀ : G.State)
    (hharmonic : ∀ t s,
      expect (pmfPi (x t s)) (fun a =>
        expect (G.transition s a) (fun s' => O s' who)) = O s who)
    (hstep : ∀ t s,
      |expect (pmfPi (x t s)) (fun a =>
          expect (G.transition s a) (fun s' => R (t + 1) s' who)) -
        R t s who - c t * O s who| ≤ e t)
    (T : ℕ) :
    |G.expectedStateValue (G.scheduledMarkovBehaviorProfile x) s₀ T
        (fun s => R T s who) - R 0 s₀ who -
      finkHarmonicCorrectionClock c T * O s₀ who| ≤
        ∑ t ∈ Finset.range T, e t := by
  let C : ℕ → G.State → Payoff ι := fun t s i =>
    R t s i - finkHarmonicCorrectionClock c t * O s i
  have hCstep : ∀ t s,
      |expect (pmfPi (x t s)) (fun a =>
          expect (G.transition s a) (fun s' => C (t + 1) s' who)) -
        C t s who| ≤ e t := by
    intro t s
    have heq :
        expect (pmfPi (x t s)) (fun a =>
            expect (G.transition s a) (fun s' => C (t + 1) s' who)) -
          C t s who =
        expect (pmfPi (x t s)) (fun a =>
            expect (G.transition s a) (fun s' => R (t + 1) s' who)) -
          R t s who - c t * O s who := by
      dsimp only [C]
      simp_rw [expect_sub, expect_const_mul]
      rw [hharmonic t s, finkHarmonicCorrectionClock_succ]
      ring
    rw [heq]
    exact hstep t s
  have htel := G.scheduled_expectedTimeDependentStateValue_close_initial
    x C e who s₀ hCstep T
  have hOexp := G.scheduled_expectedStateValue_harmonic_eq_initial
    x O who s₀ hharmonic T
  have hCT : G.expectedStateValue
      (G.scheduledMarkovBehaviorProfile x) s₀ T (fun s => C T s who) =
        G.expectedStateValue (G.scheduledMarkovBehaviorProfile x) s₀ T
          (fun s => R T s who) -
        finkHarmonicCorrectionClock c T * O s₀ who := by
    unfold expectedStateValue
    dsimp only [C]
    rw [expect_sub, expect_const_mul]
    change _ - finkHarmonicCorrectionClock c T *
      G.expectedStateValue (G.scheduledMarkovBehaviorProfile x) s₀ T
        (fun s => O s who) = _
    rw [hOexp]
  rw [hCT] at htel
  simp only [C, finkHarmonicCorrectionClock_zero, zero_mul, sub_zero] at htel
  rw [show
    G.expectedStateValue (G.scheduledMarkovBehaviorProfile x) s₀ T
          (fun s => R T s who) - R 0 s₀ who -
        finkHarmonicCorrectionClock c T * O s₀ who =
      G.expectedStateValue (G.scheduledMarkovBehaviorProfile x) s₀ T
          (fun s => R T s who) -
        finkHarmonicCorrectionClock c T * O s₀ who - R 0 s₀ who by ring]
  exact htel

/-- Quantitative obstruction extracted from the exact telescope.  If the
correction is bounded at the two endpoints, a nonzero common harmonic
forcing must be paid either by accumulated one-step error or by exhausting
that endpoint bound. -/
theorem abs_harmonicClock_mul_le_correction_endpoints_add_error
    (G : StochasticGame ι) [Fintype ι]
    [Finite G.State] [∀ i, Finite (G.Act i)]
    (x : ℕ → G.StationaryMixedProfile) (O : G.State → Payoff ι)
    (R : ℕ → G.State → Payoff ι) (c e b : ℕ → ℝ)
    (who : ι) (s₀ : G.State)
    (hharmonic : ∀ t s,
      expect (pmfPi (x t s)) (fun a =>
        expect (G.transition s a) (fun s' => O s' who)) = O s who)
    (hstep : ∀ t s,
      |expect (pmfPi (x t s)) (fun a =>
          expect (G.transition s a) (fun s' => R (t + 1) s' who)) -
        R t s who - c t * O s who| ≤ e t)
    (hR : ∀ t s, |R t s who| ≤ b t)
    (T : ℕ) :
    |finkHarmonicCorrectionClock c T * O s₀ who| ≤
      b 0 + b T + ∑ t ∈ Finset.range T, e t := by
  have htel := G.scheduled_harmonicCorrection_telescope
    x O R c e who s₀ hharmonic hstep T
  have hterminal : |G.expectedStateValue
      (G.scheduledMarkovBehaviorProfile x) s₀ T
        (fun s => R T s who)| ≤ b T := by
    unfold expectedStateValue
    exact abs_expect_le_of_abs_le _ _ fun h => hR T h.2
  have hinitial := hR 0 s₀
  have htriangle : |finkHarmonicCorrectionClock c T * O s₀ who| ≤
      |G.expectedStateValue (G.scheduledMarkovBehaviorProfile x) s₀ T
          (fun s => R T s who) - R 0 s₀ who -
        finkHarmonicCorrectionClock c T * O s₀ who| +
      |G.expectedStateValue (G.scheduledMarkovBehaviorProfile x) s₀ T
          (fun s => R T s who)| + |R 0 s₀ who| := by
    let a := G.expectedStateValue
      (G.scheduledMarkovBehaviorProfile x) s₀ T (fun s => R T s who)
    let r := R 0 s₀ who
    let o := finkHarmonicCorrectionClock c T * O s₀ who
    change |o| ≤ |a - r - o| + |a| + |r|
    have heq : o = -(a - r - o) + a - r := by ring
    calc
      |o| = |- (a - r - o) + a - r| := congrArg abs heq
      _ ≤ |- (a - r - o) + a| + |r| :=
        abs_sub _ _
      _ ≤ (|-(a - r - o)| + |a|) + |r| :=
        add_le_add (abs_add_le _ _) le_rfl
      _ = |a - r - o| + |a| + |r| := by rw [abs_neg]
  exact htriangle.trans (by linarith)

end StochasticGame
end GameTheory
