/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/

import GameTheory.Concepts.Stochastic.QuittingBellmanTelescope

/-!
# Finite exceptional-clock Bellman tail

The exceptional branch has two independent finite survival coordinates:
`π`, the opponents' survival probability, and `α`, the prescribed player's
own survival probability.  This file keeps both coordinates.  In particular,
it does not discard the own-never atom `π * R * α` and makes no infinite-tail
closure claim.
-/

set_option autoImplicit false

noncomputable section

namespace GameTheory

open Math.Probability

/-- Finite survival generated by a scalar sequence of continue masses.  The
recursion is oriented from the current live stage, matching the Bellman
recursions. -/
def quittingFiniteContinueWeight
    (continueMass : ℕ → ℝ) : ℕ → ℕ → ℝ
  | _, 0 => 1
  | start, fuel + 1 =>
      continueMass start *
        quittingFiniteContinueWeight continueMass (start + 1) fuel

/-- A finite product of nonnegative continue masses is nonnegative. -/
theorem quittingFiniteContinueWeight_nonneg
    (continueMass : ℕ → ℝ)
    (hmass : ∀ time, 0 ≤ continueMass time) :
    ∀ start fuel, 0 ≤ quittingFiniteContinueWeight continueMass start fuel := by
  intro start fuel
  induction fuel generalizing start with
  | zero => simp [quittingFiniteContinueWeight]
  | succ fuel ih =>
      rw [quittingFiniteContinueWeight]
      exact mul_nonneg (hmass start) (ih (start + 1))

/-- A finite product of continue masses bounded by one is bounded by one. -/
theorem quittingFiniteContinueWeight_le_one
    (continueMass : ℕ → ℝ)
    (hmass0 : ∀ time, 0 ≤ continueMass time)
    (hmass1 : ∀ time, continueMass time ≤ 1) :
    ∀ start fuel, quittingFiniteContinueWeight continueMass start fuel ≤ 1 := by
  intro start fuel
  induction fuel generalizing start with
  | zero => simp [quittingFiniteContinueWeight]
  | succ fuel ih =>
      rw [quittingFiniteContinueWeight]
      calc
        continueMass start *
              quittingFiniteContinueWeight continueMass (start + 1) fuel ≤
            continueMass start * 1 :=
              mul_le_mul_of_nonneg_left (ih (start + 1)) (hmass0 start)
        _ = continueMass start := mul_one _
        _ ≤ 1 := hmass1 start

/-- Finite survival of the prescribed player's own continue hazards. -/
def quittingFiniteOwnContinueWeight
    (hazard : ℕ → PMF Bool) : ℕ → ℕ → ℝ
  | _, 0 => 1
  | start, fuel + 1 =>
      (hazard start false).toReal *
        quittingFiniteOwnContinueWeight hazard (start + 1) fuel

/-- The own-continue weight is the last (`never within the cutoff`) hazard
simplex weight. -/
theorem quittingFiniteOwnContinueWeight_eq_hazardWeight_last
    (hazard : ℕ → PMF Bool) :
    ∀ start fuel,
      quittingFiniteOwnContinueWeight hazard start fuel =
        quittingFiniteHazardWeight hazard start fuel (Fin.last fuel) := by
  intro start fuel
  induction fuel generalizing start with
  | zero => simp [quittingFiniteOwnContinueWeight,
      quittingFiniteHazardWeight]
  | succ fuel ih =>
      rw [show Fin.last (fuel + 1) = (Fin.last fuel).succ by rfl]
      simp only [quittingFiniteOwnContinueWeight,
        quittingFiniteHazardWeight, Fin.cases_succ, ih]

/-- Deterministic finite quit times have the expected exceptional-clock
estimate.  Every choice that quits within the cutoff is within
`M * (1 - π)` of `π * R`; continuing throughout is within that error of
zero. -/
theorem quittingFinitePureTime_exceptional_bounds
    (quitValue continueReward continueMass : ℕ → ℝ)
    (start fuel : ℕ) (soloReward bound : ℝ)
    (hsolo0 : 0 ≤ soloReward) (hsoloBound : soloReward ≤ bound)
    (hmass0 : ∀ time, 0 ≤ continueMass time)
    (hmass1 : ∀ time, continueMass time ≤ 1)
    (hquit : ∀ time,
      |quitValue time - continueMass time * soloReward| ≤
        bound * (1 - continueMass time))
    (hcontinue : ∀ time,
      |continueReward time| ≤ bound * (1 - continueMass time)) :
    (∀ choice : Fin fuel,
      |quittingFinitePureTimeValue quitValue continueReward continueMass
          start fuel choice.castSucc -
        quittingFiniteContinueWeight continueMass start fuel * soloReward| ≤
      bound *
        (1 - quittingFiniteContinueWeight continueMass start fuel)) ∧
    |quittingFinitePureTimeValue quitValue continueReward continueMass
        start fuel (Fin.last fuel)| ≤
      bound *
        (1 - quittingFiniteContinueWeight continueMass start fuel) := by
  induction fuel generalizing start with
  | zero =>
      constructor
      · intro choice
        exact Fin.elim0 choice
      · simp [quittingFinitePureTimeValue, quittingFiniteContinueWeight]
  | succ fuel ih =>
      let currentMass := continueMass start
      let tailWeight :=
        quittingFiniteContinueWeight continueMass (start + 1) fuel
      have hcurrent0 : 0 ≤ currentMass := hmass0 start
      have hcurrent1 : currentMass ≤ 1 := hmass1 start
      have htail0 : 0 ≤ tailWeight :=
        quittingFiniteContinueWeight_nonneg continueMass hmass0
          (start + 1) fuel
      have htail1 : tailWeight ≤ 1 :=
        quittingFiniteContinueWeight_le_one continueMass hmass0 hmass1
          (start + 1) fuel
      have hmissingNonneg :
          0 ≤ currentMass * (1 - tailWeight) *
            (bound - soloReward) :=
        mul_nonneg
          (mul_nonneg hcurrent0 (sub_nonneg.mpr htail1))
          (sub_nonneg.mpr hsoloBound)
      have hquitNow :
          |quitValue start -
              currentMass * tailWeight * soloReward| ≤
            bound * (1 - currentMass * tailWeight) := by
        calc
          |quitValue start - currentMass * tailWeight * soloReward| =
              |(quitValue start - currentMass * soloReward) +
                currentMass * soloReward * (1 - tailWeight)| := by
                  congr 1
                  ring
          _ ≤ |quitValue start - currentMass * soloReward| +
              |currentMass * soloReward * (1 - tailWeight)| :=
                abs_add_le _ _
          _ ≤ bound * (1 - currentMass) +
              currentMass * soloReward * (1 - tailWeight) := by
                apply add_le_add (hquit start)
                rw [abs_of_nonneg]
                exact mul_nonneg
                  (mul_nonneg hcurrent0 hsolo0)
                  (sub_nonneg.mpr htail1)
          _ ≤ bound * (1 - currentMass * tailWeight) := by
                nlinarith
      have htail := ih (start + 1)
      constructor
      · intro choice
        refine Fin.cases ?_ (fun later => ?_) choice
        · simpa only [quittingFinitePureTimeValue,
            quittingFiniteContinueWeight, Fin.castSucc_zero,
            Fin.cases_zero] using hquitNow
        · have htailQuit := htail.1 later
          have hscaledTail :
              currentMass *
                  |quittingFinitePureTimeValue quitValue continueReward
                      continueMass (start + 1) fuel later.castSucc -
                    tailWeight * soloReward| ≤
                currentMass * (bound * (1 - tailWeight)) :=
            mul_le_mul_of_nonneg_left htailQuit hcurrent0
          simp only [Fin.castSucc_succ, quittingFinitePureTimeValue,
            Fin.cases_succ, quittingFiniteContinueWeight]
          change
            |continueReward start + currentMass *
                  quittingFinitePureTimeValue quitValue continueReward
                    continueMass (start + 1) fuel later.castSucc -
                currentMass * tailWeight * soloReward| ≤
              bound * (1 - currentMass * tailWeight)
          calc
            |continueReward start + currentMass *
                  quittingFinitePureTimeValue quitValue continueReward
                    continueMass (start + 1) fuel later.castSucc -
                currentMass * tailWeight * soloReward| =
                |continueReward start + currentMass *
                  (quittingFinitePureTimeValue quitValue continueReward
                    continueMass (start + 1) fuel later.castSucc -
                      tailWeight * soloReward)| := by
                    congr 1
                    ring
            _ ≤ |continueReward start| + currentMass *
                  |quittingFinitePureTimeValue quitValue continueReward
                    continueMass (start + 1) fuel later.castSucc -
                      tailWeight * soloReward| := by
                    calc
                      _ ≤ |continueReward start| +
                          |currentMass *
                            (quittingFinitePureTimeValue quitValue
                              continueReward continueMass (start + 1) fuel
                                later.castSucc - tailWeight * soloReward)| :=
                            abs_add_le _ _
                      _ = _ := by rw [abs_mul, abs_of_nonneg hcurrent0]
            _ ≤ bound * (1 - currentMass) +
                  currentMass * (bound * (1 - tailWeight)) :=
                    add_le_add (hcontinue start) hscaledTail
            _ = bound * (1 - currentMass * tailWeight) := by ring
      · have htailNever := htail.2
        have hscaledTail :
            currentMass *
                |quittingFinitePureTimeValue quitValue continueReward
                    continueMass (start + 1) fuel (Fin.last fuel)| ≤
              currentMass * (bound * (1 - tailWeight)) :=
          mul_le_mul_of_nonneg_left htailNever hcurrent0
        rw [show Fin.last (fuel + 1) = (Fin.last fuel).succ by rfl]
        simp only [quittingFinitePureTimeValue, Fin.cases_succ,
          quittingFiniteContinueWeight]
        change
          |continueReward start + currentMass *
              quittingFinitePureTimeValue quitValue continueReward
                continueMass (start + 1) fuel (Fin.last fuel)| ≤
            bound * (1 - currentMass * tailWeight)
        calc
          |continueReward start + currentMass *
              quittingFinitePureTimeValue quitValue continueReward
                continueMass (start + 1) fuel (Fin.last fuel)| ≤
              |continueReward start| + currentMass *
                |quittingFinitePureTimeValue quitValue continueReward
                  continueMass (start + 1) fuel (Fin.last fuel)| := by
                calc
                  _ ≤ |continueReward start| +
                      |currentMass *
                        quittingFinitePureTimeValue quitValue continueReward
                          continueMass (start + 1) fuel (Fin.last fuel)| :=
                        abs_add_le _ _
                  _ = _ := by rw [abs_mul, abs_of_nonneg hcurrent0]
          _ ≤ bound * (1 - currentMass) +
                currentMass * (bound * (1 - tailWeight)) :=
                  add_le_add (hcontinue start) hscaledTail
          _ = bound * (1 - currentMass * tailWeight) := by ring

/-- The prescribed finite hazard payoff is close to the no-opponent-event
payoff `π * R * (1 - α)`, with every event involving an opponent charged to
`1 - π`. -/
theorem abs_quittingFiniteHazardValue_sub_exceptionalTarget_le
    (quitValue continueReward continueMass : ℕ → ℝ)
    (hazard : ℕ → PMF Bool)
    (start fuel : ℕ) (soloReward bound : ℝ)
    (hsolo0 : 0 ≤ soloReward) (hsoloBound : soloReward ≤ bound)
    (hmass0 : ∀ time, 0 ≤ continueMass time)
    (hmass1 : ∀ time, continueMass time ≤ 1)
    (hquit : ∀ time,
      |quitValue time - continueMass time * soloReward| ≤
        bound * (1 - continueMass time))
    (hcontinue : ∀ time,
      |continueReward time| ≤ bound * (1 - continueMass time)) :
    |quittingFiniteHazardValue quitValue continueReward continueMass
          hazard start fuel -
        quittingFiniteContinueWeight continueMass start fuel * soloReward *
          (1 - quittingFiniteOwnContinueWeight hazard start fuel)| ≤
      bound *
        (1 - quittingFiniteContinueWeight continueMass start fuel) := by
  induction fuel generalizing start with
  | zero =>
      simp [quittingFiniteHazardValue, quittingFiniteContinueWeight,
        quittingFiniteOwnContinueWeight]
  | succ fuel ih =>
      let currentMass := continueMass start
      let tailWeight :=
        quittingFiniteContinueWeight continueMass (start + 1) fuel
      let tailOwnWeight :=
        quittingFiniteOwnContinueWeight hazard (start + 1) fuel
      let quitProbability := (hazard start true).toReal
      let continueProbability := (hazard start false).toReal
      let tailValue :=
        quittingFiniteHazardValue quitValue continueReward continueMass
          hazard (start + 1) fuel
      let continueValue := continueReward start + currentMass * tailValue
      let quitTarget := currentMass * tailWeight * soloReward
      let continueTarget :=
        currentMass * tailWeight * soloReward * (1 - tailOwnWeight)
      let error := bound * (1 - currentMass * tailWeight)
      have hcurrent0 : 0 ≤ currentMass := hmass0 start
      have hquitProbability0 : 0 ≤ quitProbability := ENNReal.toReal_nonneg
      have hcontinueProbability0 : 0 ≤ continueProbability :=
        ENNReal.toReal_nonneg
      have hprobabilitySum : quitProbability + continueProbability = 1 := by
        dsimp [quitProbability, continueProbability]
        simpa [Fintype.sum_bool] using pmf_toReal_sum_one (hazard start)
      have hquitBranch :
          |quitValue start - quitTarget| ≤ error := by
        have hpure := (quittingFinitePureTime_exceptional_bounds
          quitValue continueReward continueMass start (fuel + 1)
          soloReward bound hsolo0 hsoloBound hmass0 hmass1 hquit hcontinue).1
          (0 : Fin (fuel + 1))
        simpa only [quittingFinitePureTimeValue,
          quittingFiniteContinueWeight, Fin.castSucc_zero,
          Fin.cases_zero] using hpure
      have htail := ih (start + 1)
      have hcontinueBranch :
          |continueValue - continueTarget| ≤ error := by
        have hscaledTail :
            currentMass *
                |tailValue - tailWeight * soloReward *
                  (1 - tailOwnWeight)| ≤
              currentMass * (bound * (1 - tailWeight)) :=
          mul_le_mul_of_nonneg_left htail hcurrent0
        calc
          |continueValue - continueTarget| =
              |continueReward start + currentMass *
                (tailValue - tailWeight * soloReward *
                  (1 - tailOwnWeight))| := by
                    congr 1
                    dsimp [continueValue, continueTarget]
                    ring
          _ ≤ |continueReward start| + currentMass *
                |tailValue - tailWeight * soloReward *
                  (1 - tailOwnWeight)| := by
                  calc
                    _ ≤ |continueReward start| +
                        |currentMass *
                          (tailValue - tailWeight * soloReward *
                            (1 - tailOwnWeight))| := abs_add_le _ _
                    _ = _ := by rw [abs_mul, abs_of_nonneg hcurrent0]
          _ ≤ bound * (1 - currentMass) +
                currentMass * (bound * (1 - tailWeight)) :=
                  add_le_add (hcontinue start) hscaledTail
          _ = error := by dsimp [error]; ring
      have htarget :
          currentMass * tailWeight * soloReward *
              (1 - continueProbability * tailOwnWeight) =
            quitProbability * quitTarget +
              continueProbability * continueTarget := by
        dsimp [quitTarget, continueTarget]
        rw [show quitProbability = 1 - continueProbability by linarith]
        ring
      simp only [quittingFiniteHazardValue,
        quittingFiniteContinueWeight, quittingFiniteOwnContinueWeight]
      change
        |quitProbability * quitValue start +
              continueProbability * continueValue -
            currentMass * tailWeight * soloReward *
              (1 - continueProbability * tailOwnWeight)| ≤ error
      rw [htarget]
      calc
        |quitProbability * quitValue start +
              continueProbability * continueValue -
            (quitProbability * quitTarget +
              continueProbability * continueTarget)| =
            |quitProbability * (quitValue start - quitTarget) +
              continueProbability * (continueValue - continueTarget)| := by
                congr 1
                ring
        _ ≤ quitProbability * |quitValue start - quitTarget| +
              continueProbability * |continueValue - continueTarget| := by
                calc
                  _ ≤ |quitProbability * (quitValue start - quitTarget)| +
                        |continueProbability *
                          (continueValue - continueTarget)| :=
                        abs_add_le _ _
                  _ = _ := by
                    rw [abs_mul, abs_mul,
                      abs_of_nonneg hquitProbability0,
                      abs_of_nonneg hcontinueProbability0]
        _ ≤ quitProbability * error + continueProbability * error :=
          add_le_add
            (mul_le_mul_of_nonneg_left hquitBranch hquitProbability0)
            (mul_le_mul_of_nonneg_left hcontinueBranch
              hcontinueProbability0)
        _ = error := by rw [← add_mul, hprobabilitySum, one_mul]

/-- Every arbitrary finite deviation hazard is bounded by the corrected
exceptional cap estimate `π * R + M * (1 - π)`. -/
theorem quittingFiniteHazardValue_le_exceptionalCap
    (quitValue continueReward continueMass : ℕ → ℝ)
    (hazard : ℕ → PMF Bool)
    (start fuel : ℕ) (soloReward bound : ℝ)
    (hsolo0 : 0 ≤ soloReward) (hsoloBound : soloReward ≤ bound)
    (hmass0 : ∀ time, 0 ≤ continueMass time)
    (hmass1 : ∀ time, continueMass time ≤ 1)
    (hquit : ∀ time,
      |quitValue time - continueMass time * soloReward| ≤
        bound * (1 - continueMass time))
    (hcontinue : ∀ time,
      |continueReward time| ≤ bound * (1 - continueMass time)) :
    quittingFiniteHazardValue quitValue continueReward continueMass
        hazard start fuel ≤
      quittingFiniteContinueWeight continueMass start fuel * soloReward +
        bound *
          (1 - quittingFiniteContinueWeight continueMass start fuel) := by
  obtain ⟨choice, hchoice⟩ :=
    exists_pureTime_ge_quittingFiniteHazardValue
      quitValue continueReward continueMass hazard start fuel
  have hpure := quittingFinitePureTime_exceptional_bounds
    quitValue continueReward continueMass start fuel soloReward bound
      hsolo0 hsoloBound hmass0 hmass1 hquit hcontinue
  have hweight0 := quittingFiniteContinueWeight_nonneg
    continueMass hmass0 start fuel
  refine le_trans hchoice ?_
  refine Fin.lastCases ?_ (fun earlier => ?_) choice
  · have hnever := hpure.2
    have hupper :
        quittingFinitePureTimeValue quitValue continueReward continueMass
            start fuel (Fin.last fuel) ≤
          bound *
            (1 - quittingFiniteContinueWeight continueMass start fuel) :=
      le_trans (le_abs_self _) hnever
    nlinarith [mul_nonneg hweight0 hsolo0]
  · have hquitChoice := hpure.1 earlier
    rw [abs_le] at hquitChoice
    linarith

/-- Corrected finite exceptional gap between an arbitrary deviation hazard
and the prescribed hazard.  The own-survival atom is retained explicitly. -/
theorem quittingFiniteHazardGap_le_exceptional
    (quitValue continueReward continueMass : ℕ → ℝ)
    (prescribedHazard deviationHazard : ℕ → PMF Bool)
    (start fuel : ℕ) (soloReward bound : ℝ)
    (hsolo0 : 0 ≤ soloReward) (hsoloBound : soloReward ≤ bound)
    (hmass0 : ∀ time, 0 ≤ continueMass time)
    (hmass1 : ∀ time, continueMass time ≤ 1)
    (hquit : ∀ time,
      |quitValue time - continueMass time * soloReward| ≤
        bound * (1 - continueMass time))
    (hcontinue : ∀ time,
      |continueReward time| ≤ bound * (1 - continueMass time)) :
    quittingFiniteHazardValue quitValue continueReward continueMass
          deviationHazard start fuel -
        quittingFiniteHazardValue quitValue continueReward continueMass
          prescribedHazard start fuel ≤
      quittingFiniteContinueWeight continueMass start fuel * soloReward *
          quittingFiniteOwnContinueWeight prescribedHazard start fuel +
        2 * bound *
          (1 - quittingFiniteContinueWeight continueMass start fuel) := by
  have hprescribed :=
    abs_quittingFiniteHazardValue_sub_exceptionalTarget_le
      quitValue continueReward continueMass prescribedHazard start fuel
        soloReward bound hsolo0 hsoloBound hmass0 hmass1 hquit hcontinue
  have hcap := quittingFiniteHazardValue_le_exceptionalCap
    quitValue continueReward continueMass deviationHazard start fuel
      soloReward bound hsolo0 hsoloBound hmass0 hmass1 hquit hcontinue
  rw [abs_le] at hprescribed
  nlinarith

/-- The two finite exceptional-tail estimates imply the corrected cap-gap
bound, including the own-never atom. -/
theorem exceptionalBellmanGap_le_of_prescribed_and_cap_bounds
    (prescribed cap opponentSurvival ownSurvival soloReward bound : ℝ)
    (hprescribed :
      |prescribed - opponentSurvival * soloReward * (1 - ownSurvival)| ≤
        bound * (1 - opponentSurvival))
    (hcap :
      cap ≤ opponentSurvival * soloReward +
        bound * (1 - opponentSurvival)) :
    cap - prescribed ≤
      opponentSurvival * soloReward * ownSurvival +
        2 * bound * (1 - opponentSurvival) := by
  rw [abs_le] at hprescribed
  nlinarith

end GameTheory
