import GameTheory.Languages.Expressiveness.Relations
import GameTheory.Languages.Expressiveness.CausalContext

/-!
# GameTheory.Languages.Expressiveness.MAID_EFG

Expressiveness packaging for the MAID-to-EFG bridge and the exact EFG-side
fragment it characterizes.

The full converse "which EFGs are MAIDs?" is not every EFG.  This file names
two equivalent presentations of the exact sublanguage:

* `MAIDLanguage m`: MAID presentations over players `Fin m`.
* `MAIDEFGLanguage m`: EFGs obtained by unrolling those MAIDs along a
  topological order.
* `CausalContextFreeEFGLanguage m`: EFG assignment trees over fixed causal
  variables, where decision choices are context-free and information sets are
  fixed observed-parent projections.
* `IsCausalContextFreeEFGTree`: the intrinsic EFG-side predicate for that tree
  shape.

The already-proved bridge theorem supplies a utility-distribution bisimulation
between each MAID and its generated EFG.
-/

namespace GameTheory
namespace Languages
namespace Expressiveness

/-- A MAID presentation over players `Fin m`.

`seedPolicy` is included because the existing EFG unrolling API takes a policy
argument to build the tree.  The bridge proves this argument is semantically
irrelevant; the MAID kernel semantics below ignores it. -/
structure MAIDPresentation (m : Nat) where
  nodeCount : Nat
  struct : MAID.Struct (Fin m) nodeCount
  sem : MAID.Sem struct
  seedPolicy : MAID.Policy struct

namespace MAIDPresentation

variable {m : Nat}

/-- Compile the MAID presentation to its native kernel game. -/
noncomputable def toKernelGame (X : MAIDPresentation m) :
    KernelGame (Fin m) :=
  MAID.toKernelGame X.struct X.sem

/-- Unroll the MAID presentation to an EFG using the classically chosen
topological order. -/
noncomputable def toEFG (X : MAIDPresentation m) : EFG.EFGGame :=
  MAID_EFG.maidToEFG X.struct X.sem X.seedPolicy

/-- Unroll the MAID presentation to an EFG using an explicit topological order. -/
noncomputable def toEFGAt (X : MAIDPresentation m)
    (order : MAID.TopologicalOrder X.struct) : EFG.EFGGame :=
  MAID_EFG.maidToEFGAt X.struct X.sem X.seedPolicy order

/-- The generated EFG kernel game. -/
noncomputable def toEFGKernelGame (X : MAIDPresentation m) :
    KernelGame (Fin m) :=
  X.toEFG.toKernelGame

/-- Native MAID and generated EFG semantics are utility-distribution
bisimilar. -/
noncomputable def toEFG_bisimulation (X : MAIDPresentation m) :
    KernelGame.Bisimulation X.toKernelGame X.toEFGKernelGame :=
  MAID_EFG.maidToEFG_bisimulation X.sem X.seedPolicy

/-- Native MAID and explicitly ordered generated EFG semantics are
utility-distribution bisimilar. -/
noncomputable def toEFGAt_bisimulation (X : MAIDPresentation m)
    (order : MAID.TopologicalOrder X.struct) :
    KernelGame.Bisimulation X.toKernelGame (X.toEFGAt order).toKernelGame :=
  MAID_EFG.maidToEFGAt_bisimulation X.sem X.seedPolicy order

end MAIDPresentation

/-- The native MAID language over players `Fin m`. -/
noncomputable def MAIDLanguage (m : Nat) : Language (Fin m) where
  Syntax := MAIDPresentation m
  compile := MAIDPresentation.toKernelGame

/-- The EFG sublanguage generated by unrolling MAIDs over players `Fin m`.

This is a genuine EFG sublanguage, but its syntax remembers the source MAID
certificate.  Forgetting that certificate into arbitrary `EFGGame` syntax is a
separate, more intensional presentation issue. -/
noncomputable def MAIDEFGLanguage (m : Nat) : Language (Fin m) where
  Syntax := MAIDPresentation m
  compile := MAIDPresentation.toEFGKernelGame

/-- The EFG sublanguage whose syntax is an explicit causal context-free
assignment-tree presentation.

This is the useful "MAID inside EFG" characterization: fixed causal variables,
fixed value/action domains, chance and utility depending on fixed parent
projections, and information sets induced by fixed observed-parent projections. -/
noncomputable def CausalContextFreeEFGLanguage (m : Nat) : Language (Fin m) where
  Syntax := CausalContextFreeEFGPresentation m
  compile := CausalContextFreeEFGPresentation.toKernelGame

/-- MAID reduces to its generated-EFG sublanguage under utility-distribution
equivalence. -/
noncomputable def maidToMAIDEFGReduction (m : Nat) :
    Reduction (MAIDLanguage m) (MAIDEFGLanguage m)
      UtilityDistributionEquivalent where
  translate := _root_.id
  sound := fun X => ⟨X.toEFG_bisimulation⟩

/-- The generated-EFG sublanguage reduces back to native MAID under
utility-distribution equivalence. -/
noncomputable def maidefgToMAIDReduction (m : Nat) :
    Reduction (MAIDEFGLanguage m) (MAIDLanguage m)
      UtilityDistributionEquivalent where
  translate := _root_.id
  sound := fun X => utilityDistributionEquivalent_symm ⟨X.toEFG_bisimulation⟩

/-- View a MAID presentation as an explicit causal context-free EFG
presentation. -/
noncomputable def MAIDPresentation.toCausalContextFreeEFGPresentation
    {m : Nat} (X : MAIDPresentation m) : CausalContextFreeEFGPresentation m where
  form := CausalContextFreeForm.ofMAID X.struct X.sem
  seedPolicy := X.seedPolicy
  order := Classical.choice (MAID.topologicalOrder_exists X.struct)

/-- Forget an explicit causal context-free EFG presentation back to its native
MAID kernel presentation. -/
noncomputable def CausalContextFreeEFGPresentation.toMAIDPresentation
    {m : Nat} (X : CausalContextFreeEFGPresentation m) : MAIDPresentation m where
  nodeCount := X.form.nodeCount
  struct := X.form.toMAIDStruct
  sem := X.form.toMAIDSem
  seedPolicy := X.seedPolicy

/-- MAID reduces to the explicit causal-context-free EFG sublanguage. -/
noncomputable def maidToCausalContextFreeEFGReduction (m : Nat) :
    Reduction (MAIDLanguage m) (CausalContextFreeEFGLanguage m)
      UtilityDistributionEquivalent where
  translate := MAIDPresentation.toCausalContextFreeEFGPresentation
  sound := fun X => by
    let order : MAID.TopologicalOrder X.struct :=
      Classical.choice (MAID.topologicalOrder_exists X.struct)
    exact ⟨MAID_EFG.maidToEFGAt_bisimulation X.sem X.seedPolicy order⟩

/-- The explicit causal-context-free EFG sublanguage reduces back to native
MAID semantics. -/
noncomputable def causalContextFreeEFGToMAIDReduction (m : Nat) :
    Reduction (CausalContextFreeEFGLanguage m) (MAIDLanguage m)
      UtilityDistributionEquivalent where
  translate := CausalContextFreeEFGPresentation.toMAIDPresentation
  sound := fun X =>
    utilityDistributionEquivalent_symm ⟨X.toEFG_bisimulation⟩

/-- Native MAIDs and MAID-generated EFGs have exactly the same expressiveness
under the default utility-distribution lens. -/
theorem maid_expressiveEq_maidefg (m : Nat) :
    (utilityDistributionLens (Fin m)).ExpressiveEq
      (MAIDLanguage m) (MAIDEFGLanguage m) :=
  (utilityDistributionLens (Fin m)).expressiveEq_of_reductions
    (maidToMAIDEFGReduction m) (maidefgToMAIDReduction m)

/-- Native MAIDs and causal-context-free EFG assignment trees have exactly the
same expressiveness under the default utility-distribution lens. -/
theorem maid_expressiveEq_causalContextFreeEFG (m : Nat) :
    (utilityDistributionLens (Fin m)).ExpressiveEq
      (MAIDLanguage m) (CausalContextFreeEFGLanguage m) :=
  (utilityDistributionLens (Fin m)).expressiveEq_of_reductions
    (maidToCausalContextFreeEFGReduction m)
    (causalContextFreeEFGToMAIDReduction m)

/-! ## Exact generated-tree certificate -/

/-- Certificate that an arbitrary `EFGGame` is literally the unrolling of a
MAID along an explicit topological order.

This is the intensional "MAID-in-EFG" shape.  It is stronger than semantic
equivalence: `sameGame` identifies the EFG presentation itself with the bridge
tree, not just its kernel semantics. -/
structure MAIDEFGTreeCertificate (G : EFG.EFGGame) where
  nodeCount : Nat
  struct : MAID.Struct G.inf.Player nodeCount
  sem : MAID.Sem struct
  seedPolicy : MAID.Policy struct
  order : MAID.TopologicalOrder struct
  sameGame : MAID_EFG.maidToEFGAt struct sem seedPolicy order = G

/-- Predicate for EFG trees that are exactly MAID unrollings. -/
def IsMAIDEFGTree (G : EFG.EFGGame) : Prop :=
  Nonempty (MAIDEFGTreeCertificate G)

namespace MAIDEFGTreeCertificate

variable {G : EFG.EFGGame}

/-- Semantic utility-distribution equivalence for the generated tree named by
the certificate.  The `sameGame` field then identifies that generated tree with
the ambient EFG presentation. -/
theorem generatedUtilityDistributionEquivalent
    (c : MAIDEFGTreeCertificate G) :
    UtilityDistributionEquivalent (MAID.toKernelGame c.struct c.sem)
      (MAID_EFG.maidToEFGAt c.struct c.sem c.seedPolicy c.order).toKernelGame :=
  ⟨MAID_EFG.maidToEFGAt_bisimulation c.sem c.seedPolicy c.order⟩

end MAIDEFGTreeCertificate

/-- Every explicit MAID unrolling is a `MAIDEFGTree`. -/
theorem maidToEFGAt_isMAIDEFGTree
    {m n : Nat} (S : MAID.Struct (Fin m) n)
    (sem : MAID.Sem S) (pol : MAID.Policy S)
    (order : MAID.TopologicalOrder S) :
    IsMAIDEFGTree (MAID_EFG.maidToEFGAt S sem pol order) :=
  ⟨{
    nodeCount := n
    struct := S
    sem := sem
    seedPolicy := pol
    order := order
    sameGame := rfl
  }⟩

/-- Every order-free MAID unrolling is a `MAIDEFGTree`. -/
theorem maidToEFG_isMAIDEFGTree
    {m n : Nat} (S : MAID.Struct (Fin m) n)
    (sem : MAID.Sem S) (pol : MAID.Policy S) :
    IsMAIDEFGTree (MAID_EFG.maidToEFG S sem pol) := by
  unfold MAID_EFG.maidToEFG
  exact maidToEFGAt_isMAIDEFGTree S sem pol
    (Classical.choice (MAID.topologicalOrder_exists S))

/-- Exact-tree characterization, unfolded as an iff for convenient rewriting. -/
theorem isMAIDEFGTree_iff (G : EFG.EFGGame) :
    IsMAIDEFGTree G ↔
      ∃ (n : Nat) (S : MAID.Struct G.inf.Player n)
        (sem : MAID.Sem S) (pol : MAID.Policy S)
        (order : MAID.TopologicalOrder S),
        MAID_EFG.maidToEFGAt S sem pol order = G := by
  constructor
  · intro h
    rcases h with ⟨c⟩
    exact ⟨c.nodeCount, c.struct, c.sem, c.seedPolicy, c.order, c.sameGame⟩
  · rintro ⟨n, S, sem, pol, order, hG⟩
    exact ⟨{
      nodeCount := n
      struct := S
      sem := sem
      seedPolicy := pol
      order := order
      sameGame := hG
    }⟩

/-- The old generated-tree predicate and the explicit causal-context-free EFG
predicate name the same EFG presentations.

The right-hand predicate is the useful characterization: fixed causal variables,
fixed context-free choice domains, and information sets as observed-parent
projection fibers. -/
theorem isMAIDEFGTree_iff_isCausalContextFreeEFGTree (G : EFG.EFGGame) :
    IsMAIDEFGTree G ↔ IsCausalContextFreeEFGTree G := by
  constructor
  · rintro ⟨c⟩
    exact ⟨{
      form := CausalContextFreeForm.ofMAID c.struct c.sem
      seedPolicy := c.seedPolicy
      order := c.order
      sameGame := by
        simpa using c.sameGame
    }⟩
  · rintro ⟨c⟩
    exact ⟨{
      nodeCount := c.form.nodeCount
      struct := c.form.toMAIDStruct
      sem := c.form.toMAIDSem
      seedPolicy := c.seedPolicy
      order := c.order
      sameGame := c.sameGame
    }⟩

end Expressiveness
end Languages
end GameTheory
