/-
# Continuity of finite mixed expected utility

Pointwise convergence of every player's mixed strategy implies convergence of
expected utility.  The finite action carriers make the profile observable a
finite sum, while actual pure-play integration supports arbitrary outcomes.
-/

import GameTheory.Math.Probability.Convergence
import GameTheory.Core.Mixed

noncomputable section

namespace GameTheory

open Filter GameTheory.Math.Probability

universe uι us uo

variable {ι : Type uι} [Fintype ι] [DecidableEq ι]

namespace UtilityGame

variable {G : UtilityGame.{uι, us, uo} ι}
variable [∀ i, Fintype (G.form.sig.Strategy i)]

omit [DecidableEq ι] in
private theorem expectedUtility_mixed_eq_profile_expect
    (hintegrable : GameForm.HasIntegrableUtility G.form G.utility)
    (profile : Profile G.form.sig.mixed) (who : ι) :
    expectedUtility G.utility who (G.form.mixed.play profile)
        (hintegrable.mixed_of_finite who profile) =
      expect (independentProduct profile)
        (fun pureProfile =>
          expectedUtility G.utility who (G.form.play pureProfile)
            (hintegrable who pureProfile))
        (payoffIntegrable_of_finite (independentProduct profile)
          (fun pureProfile =>
            expectedUtility G.utility who (G.form.play pureProfile)
              (hintegrable who pureProfile))) := by
  let hbind := hintegrable.mixed_of_finite who profile
  have htower := expectedUtility_bind G.utility who
    (independentProduct profile) G.form.play
    (by simpa only [GameForm.mixed_play, UtilityIntegrable] using hbind)
    (hintegrable who)
  calc
    expectedUtility G.utility who (G.form.mixed.play profile) hbind =
        expect (independentProduct profile)
          (fun pureProfile =>
            expectedUtility G.utility who (G.form.play pureProfile)
              (hintegrable who pureProfile))
          (payoffIntegrable_bind_conditionalExpectation
            (independentProduct profile) G.form.play
            (fun outcome => G.utility outcome who)
            (by simpa only [GameForm.mixed_play, UtilityIntegrable] using hbind)
            (hintegrable who)) := by
      simpa only [GameForm.mixed_play, hbind] using htower
    _ = expect (independentProduct profile)
          (fun pureProfile =>
            expectedUtility G.utility who (G.form.play pureProfile)
              (hintegrable who pureProfile))
          (payoffIntegrable_of_finite (independentProduct profile)
            (fun pureProfile =>
              expectedUtility G.utility who (G.form.play pureProfile)
                (hintegrable who pureProfile))) :=
      expect_proof_irrel _ _ _ _

/-- Expected utility in the finite mixed extension is continuous under
coordinatewise pointwise convergence of ordinary PMFs. Pure-play integration
is the only utility premise, and the outcome carrier may be arbitrary. -/
theorem expectedUtility_mixed_tendsto
    {sequence : ℕ → Profile G.form.sig.mixed}
    {target : Profile G.form.sig.mixed}
    (hconverges : ∀ i, PMFConvergesPointwise
      (fun n => sequence n i) (target i))
    (hintegrable : GameForm.HasIntegrableUtility G.form G.utility) (who : ι) :
    Tendsto
      (fun n => expectedUtility G.utility who
        (G.form.mixed.play (sequence n))
        (hintegrable.mixed_of_finite who (sequence n)))
      atTop
      (nhds (expectedUtility G.utility who (G.form.mixed.play target)
        (hintegrable.mixed_of_finite who target))) := by
  let observable := fun pureProfile =>
    expectedUtility G.utility who (G.form.play pureProfile)
      (hintegrable who pureProfile)
  have hproduct := PMFConvergesPointwise.independentProduct hconverges
  have hexpect := hproduct.expect_finite observable
  have heq (profile : Profile G.form.sig.mixed) :=
    expectedUtility_mixed_eq_profile_expect hintegrable profile who
  convert hexpect using 1
  · funext n
    exact heq (sequence n)
  · exact congrArg nhds (heq target)

/-- Fixing one player's pure action preserves convergence of the expected
utility generated by the remaining convergent mixed strategies. -/
theorem expectedUtility_update_pure_tendsto
    {sequence : ℕ → Profile G.form.sig.mixed}
    {target : Profile G.form.sig.mixed}
    (hconverges : ∀ i, PMFConvergesPointwise
      (fun n => sequence n i) (target i))
    (hintegrable : GameForm.HasIntegrableUtility G.form G.utility)
    (who : ι) (action : G.form.sig.Strategy who) :
    Tendsto
      (fun n => expectedUtility G.utility who
        (G.form.mixed.play
          (Profile.update (sequence n) who (PMF.pure action)))
        (hintegrable.mixed_of_finite who
          (Profile.update (sequence n) who (PMF.pure action))))
      atTop
      (nhds (expectedUtility G.utility who
        (G.form.mixed.play
          (Profile.update target who (PMF.pure action)))
        (hintegrable.mixed_of_finite who
          (Profile.update target who (PMF.pure action))))) := by
  apply expectedUtility_mixed_tendsto
  · intro other
    by_cases hother : other = who
    · subst hother
      simp only [Profile.update_same]
      exact pmfConvergesPointwise_const _
    · simp only [Profile.update_of_ne _ _ hother]
      exact hconverges other
  · exact hintegrable

end UtilityGame

end GameTheory
