import Math.Probability
import Math.PMFProduct
import Math.ProbabilityMassFunction
import Semantics.SM
import Semantics.TransitionTrace

/-!
# GameTheory.Languages.InfoModel.SemanticForm

Semantics-first model decomposition:
- `InfoModel`: public and player-local visibility, extending `Semantics.SM`
- `ControlModel`: common-knowledge controller specifications (separate layer)

`ObsRecall`, `ActionRecall`, `PerfectRecall`, and `FiniteHorizon` are predicates,
not built-in requirements.
-/

namespace GameTheory

open Math.Probability

/-- Information structure extending a multi-agent state machine.
Inherits `init` and `step` from `SM`; adds public/private observation structure.

`publicView` is the common visible component of a state.
`observe i` is player `i`'s private/local visible component. -/
structure InfoModel (ι σ : Type) (Act : ι → Type)
    extends Semantics.SM (∀ i, Option (Act i)) σ where
  Public : Type
  publicView : σ → Public
  Obs : ι → Type
  observe : (i : ι) → σ → Obs i

namespace InfoModel

variable {ι σ : Type} {Act : ι → Type}

/-- Joint (possibly inactive) action profile. -/
abbrev JointAction (_ : InfoModel ι σ Act) := ∀ i, Option (Act i)

/-- Derived player-information equivalence: same public view and same local view. -/
def obsEq (I : InfoModel ι σ Act) (i : ι) : σ → σ → Prop :=
  fun s t => I.publicView s = I.publicView t ∧ I.observe i s = I.observe i t

/-- Common public trace induced by a state trace. -/
abbrev PublicTrace (I : InfoModel ι σ Act) : Type :=
  List I.Public

/-- Controller-local private observation trace. -/
abbrev PrivateTrace (I : InfoModel ι σ Act) (i : ι) : Type :=
  List (I.Obs i)

/-- Controller-local visible history: public history paired with the player's
private observation history. -/
abbrev LocalTrace (I : InfoModel ι σ Act) (i : ι) : Type :=
  I.PublicTrace × I.PrivateTrace i

/-- Visible outcome induced by a state trace. -/
abbrev Outcome (I : InfoModel ι σ Act) : Type :=
  I.PublicTrace × (∀ i, I.PrivateTrace i)

/-- Project the public component of a state trace. -/
def projectPublic (I : InfoModel ι σ Act) (ss : List σ) : I.PublicTrace :=
  ss.map I.publicView

/-- Project player `i`'s private component of a state trace. -/
def projectPrivate (I : InfoModel ι σ Act) (i : ι) (ss : List σ) : I.PrivateTrace i :=
  ss.map (I.observe i)

/-- Local projection by pairing the public trace with player `i`'s private trace. -/
def projectStates (I : InfoModel ι σ Act) (i : ι) (ss : List σ) : I.LocalTrace i :=
  (I.projectPublic ss, I.projectPrivate i ss)

/-- Outcome induced by a machine state trace via public/private projections. -/
def outcomeOfStates (I : InfoModel ι σ Act) (ss : List σ) : I.Outcome :=
  (I.projectPublic ss, fun i => I.projectPrivate i ss)

/-- A finite local-history cover `H` is sufficient up to horizon `k` if every
reachable state trace of length at most `k + 1` projects into `H`. This is the
generic bounded object needed by the restricted-profile Kuhn theorem. -/
def CoversHistoriesUpTo
    (I : InfoModel ι σ Act)
    (H : ∀ i, Finset (I.LocalTrace i))
    (k : Nat) : Prop :=
  ∀ (i : ι) {ss : List σ},
    Semantics.SM.ReachStateTrace I.toSM ss →
    ss.length ≤ k + 1 →
    I.projectStates i ss ∈ H i

/-- Player-local projected own-action trace from an action-annotated history. -/
def projectActions (_ : InfoModel ι σ Act) (i : ι)
    (ha : List (∀ i, Option (Act i))) : List (Option (Act i)) :=
  ha.map (fun a => a i)

/-- Player-local history token:
visible local history paired with realized own action at that step. -/
abbrev LocalHistTok (I : InfoModel ι σ Act) (i : ι) : Type :=
  I.LocalTrace i × Option (Act i)

/-- Build local-history tokens from action/state traces (auxiliary recursion). -/
private def localHistTokensAux
    (I : InfoModel ι σ Act) (i : ι)
    (pref : List σ)
    (ha : List I.JointAction)
    (ssTail : List σ) :
    List (I.LocalHistTok i) :=
  match ha, ssTail with
  | [], _ => []
  | a :: ha', s' :: ss' =>
      (I.projectStates i pref, a i) ::
        localHistTokensAux I i (pref ++ [s']) ha' ss'
  | _ :: _, [] => []

/-- First-class local-history projection from action/state traces. -/
def localHistTokens
    (I : InfoModel ι σ Act) (i : ι)
    (ha : List I.JointAction)
    (ss : List σ) :
    List (I.LocalHistTok i) :=
  match ss with
  | [] => []
  | s0 :: ssTail => localHistTokensAux I i [s0] ha ssTail

/-- Local-history tokens generated by continuing after an already accumulated
state prefix `pref`. -/
def localHistTokensFrom
    (I : InfoModel ι σ Act) (i : ι)
    (pref : List σ)
    (ha : List I.JointAction)
    (ssTail : List σ) :
    List (I.LocalHistTok i) :=
  localHistTokensAux I i pref ha ssTail

/-- With a nonempty starting prefix, `localHistTokens` agrees with
`localHistTokensFrom`. -/
theorem localHistTokens_cons_eq_localHistTokensFrom
    (I : InfoModel ι σ Act) (i : ι)
    (s₀ : σ)
    (ha : List I.JointAction)
    (ssTail : List σ) :
    localHistTokens I i ha (s₀ :: ssTail) =
      localHistTokensFrom I i [s₀] ha ssTail := rfl

private theorem localHistTokensAux_snoc
    (I : InfoModel ι σ Act) (i : ι)
    (pref : List σ)
    (ha : List I.JointAction)
    (ssTail : List σ)
    (hLen : ssTail.length = ha.length)
    (a : I.JointAction) (t : σ) :
    localHistTokensAux I i pref (ha ++ [a]) (ssTail ++ [t]) =
      localHistTokensAux I i pref ha ssTail ++
        [(I.projectStates i (pref ++ ssTail), a i)] := by
  induction ha generalizing pref ssTail with
  | nil =>
      cases ssTail with
      | nil =>
          simp [localHistTokensAux]
      | cons s ss =>
          cases hLen
  | cons a0 ha ih =>
      cases ssTail with
      | nil =>
          cases hLen
      | cons s ss =>
          simp at hLen
          simp [localHistTokensAux, ih (pref := pref ++ [s]) (ssTail := ss) hLen,
            List.append_assoc]

/-- Appending one step to an action/state trace appends exactly one local
history token. -/
theorem localHistTokens_snoc
    (I : InfoModel ι σ Act) (i : ι)
    (ha : List I.JointAction)
    (ss : List σ)
    (hLen : ss.length = ha.length + 1)
    (a : I.JointAction) (t : σ) :
    localHistTokens I i (ha ++ [a]) (ss ++ [t]) =
      localHistTokens I i ha ss ++ [(I.projectStates i ss, a i)] := by
  cases ss with
  | nil =>
      cases hLen
  | cons s0 ssTail =>
      have hLen' : ssTail.length = ha.length := by
        simpa using hLen
      simpa [localHistTokens, List.cons_append, List.append_assoc] using
        localHistTokensAux_snoc I i [s0] ha ssTail hLen' a t

/-- Appending one step to a continuation appends exactly one continuation local
history token. -/
theorem localHistTokensFrom_snoc
    (I : InfoModel ι σ Act) (i : ι)
    (pref : List σ)
    (ha : List I.JointAction)
    (ssTail : List σ)
    (hLen : ssTail.length = ha.length)
    (a : I.JointAction) (t : σ) :
    localHistTokensFrom I i pref (ha ++ [a]) (ssTail ++ [t]) =
      localHistTokensFrom I i pref ha ssTail ++
        [(I.projectStates i (pref ++ ssTail), a i)] := by
  simpa [localHistTokensFrom] using
    localHistTokensAux_snoc I i pref ha ssTail hLen a t

/-- Observation recall: indistinguishable terminal visible states imply identical
player-local visible histories on the corresponding reaches. -/
def ObsRecall (I : InfoModel ι σ Act) : Prop :=
  ∀ (i : ι) (ss₁ ss₂ : List σ) (s₁ s₂ : σ),
    Semantics.SM.ReachStateTrace I.toSM ss₁ →
    Semantics.SM.ReachStateTrace I.toSM ss₂ →
    ss₁.getLast? = some s₁ →
    ss₂.getLast? = some s₂ →
    I.obsEq i s₁ s₂ →
    I.projectStates i ss₁ = I.projectStates i ss₂

/-- Action recall: indistinguishable terminal visible states imply identical
player-local own-action traces on the corresponding action-annotated reaches. -/
def ActionRecall (I : InfoModel ι σ Act) : Prop :=
  ∀ (i : ι)
    (ha₁ ha₂ : List I.JointAction)
    (ss₁ ss₂ : List σ) (s₁ s₂ : σ),
    Semantics.SM.ReachActionTrace I.toSM ha₁ ss₁ →
    Semantics.SM.ReachActionTrace I.toSM ha₂ ss₂ →
    ss₁.getLast? = some s₁ →
    ss₂.getLast? = some s₂ →
    I.obsEq i s₁ s₂ →
    I.projectActions i ha₁ = I.projectActions i ha₂

/-- Perfect recall is the conjunction of observation recall and action recall. -/
def PerfectRecall (I : InfoModel ι σ Act) : Prop :=
  I.ObsRecall ∧ I.ActionRecall

theorem perfectRecall_obs {I : InfoModel ι σ Act}
    (hPR : I.PerfectRecall) : I.ObsRecall :=
  hPR.1

theorem perfectRecall_action {I : InfoModel ι σ Act}
    (hPR : I.PerfectRecall) : I.ActionRecall :=
  hPR.2

/-- Bounded-horizon predicate (theorem-local assumption). -/
def FiniteHorizon (I : InfoModel ι σ Act) (k : Nat) : Prop :=
  ∀ (h : List I.JointAction) (s : σ),
    Semantics.Transition.ReachBy I.step h I.init s → h.length ≤ k

end InfoModel

/-- Common-knowledge controller specification over local traces/observations. -/
inductive ControlSpec (Obs Act : Type) where
  | utility  : (List Obs → ℝ) → ControlSpec Obs Act
  | behavior : (List Obs → PMF (Option Act)) → ControlSpec Obs Act

/-- Public control layer, separated from machine and information layers. -/
structure ControlModel {ι σ : Type} {Act : ι → Type}
    (I : InfoModel ι σ Act) where
  control : ∀ i, ControlSpec (I.Obs i) (Act i)

namespace Execution

variable {ι σ : Type} {Act : ι → Type}

/-- Deterministic profile over local visible history. -/
abbrev PureProfile (I : InfoModel ι σ Act) : Type :=
  ∀ i, I.LocalTrace i → Option (Act i)

/-- Behavioral profile over local visible history. -/
abbrev BehavioralProfile (I : InfoModel ι σ Act) : Type :=
  ∀ i, I.LocalTrace i → PMF (Option (Act i))

/-- Correlated behavioral profile over the full visible history context. -/
abbrev BehavioralProfileCorr (I : InfoModel ι σ Act) : Type :=
  (∀ i, I.LocalTrace i) → PMF I.JointAction

/-- Embed an independent behavioral profile as a correlated one by product sampling. -/
noncomputable def behavioralToCorr
    [DecidableEq ι] [Fintype ι] [∀ i, Fintype (Option (Act i))]
    (I : InfoModel ι σ Act) (b : BehavioralProfile I) : BehavioralProfileCorr I :=
  fun v => Math.PMFProduct.pmfPi (fun i => b i (v i))

/-- Lift a deterministic profile to a behavioral one. -/
noncomputable def pureToBehavioral (I : InfoModel ι σ Act)
    (π : PureProfile I) : BehavioralProfile I :=
  fun i v => PMF.pure (π i v)

/-- Stochastic execution choices on top of nondeterministic machine rules. -/
structure Dynamics (I : InfoModel ι σ Act) where
  /-- Next-state kernel, conditioned on joint action and current latent state. -/
  nextState : I.JointAction → σ → PMF σ
  /-- Soundness: sampled next states respect machine step relation. -/
  nextState_sound :
    ∀ (a : I.JointAction) (s t : σ),
      (nextState a s) t ≠ 0 → I.step a s t

namespace Dynamics

variable {I : InfoModel ι σ Act}

/-- Independent joint-action distribution induced by a behavioral profile. -/
noncomputable def jointActionDist
    [DecidableEq ι] [Fintype ι] [∀ i, Fintype (Option (Act i))]
    (b : BehavioralProfile I) (ss : List σ) : PMF I.JointAction :=
  Math.PMFProduct.pmfPi (fun i => b i (I.projectStates i ss))

/-- One stochastic step from a current state under behavioral profile. -/
noncomputable def stepDist (D : Dynamics I)
    [DecidableEq ι] [Fintype ι] [∀ i, Fintype (Option (Act i))]
    (b : BehavioralProfile I) (ss : List σ) : PMF σ :=
  let s := (ss.getLast?).getD I.init
  (jointActionDist (I := I) b ss).bind fun a =>
    D.nextState a s

/-- One stochastic step under a correlated behavioral profile. -/
noncomputable def stepDistCorr (D : Dynamics I)
    [Fintype ι] [∀ i, Fintype (Option (Act i))]
    (b : BehavioralProfileCorr I) (ss : List σ) : PMF σ :=
  let s := (ss.getLast?).getD I.init
  let v : ∀ i, I.LocalTrace i := fun i => I.projectStates i ss
  (b v).bind fun a =>
    D.nextState a s

/-- Bounded run distribution of length exactly `k`, storing just the state trace. -/
noncomputable def runDist (D : Dynamics I)
    [DecidableEq ι] [Fintype ι] [∀ i, Fintype (Option (Act i))]
    (k : Nat) (b : BehavioralProfile I) : PMF (List σ) :=
  Nat.rec (PMF.pure [I.init])
    (fun _ rec =>
      rec.bind (fun ss =>
        Math.ProbabilityMassFunction.pushforward (D.stepDist b ss)
          (fun t => ss ++ [t])))
    k

/-- Pure-profile run distribution via `pureToBehavioral`. -/
noncomputable def runDistPure (D : Dynamics I)
    [DecidableEq ι] [Fintype ι] [∀ i, Fintype (Option (Act i))]
    (k : Nat) (π : PureProfile I) : PMF (List σ) :=
  D.runDist k (pureToBehavioral I π)

/-- Outcome distribution from bounded behavioral runs. -/
noncomputable def evalBehavioral (D : Dynamics I)
    [DecidableEq ι] [Fintype ι] [∀ i, Fintype (Option (Act i))]
    (k : Nat) (b : BehavioralProfile I) : PMF I.Outcome :=
  Math.ProbabilityMassFunction.pushforward (D.runDist k b) I.outcomeOfStates

/-- Outcome distribution from bounded pure runs. -/
noncomputable def evalPure (D : Dynamics I)
    [DecidableEq ι] [Fintype ι] [∀ i, Fintype (Option (Act i))]
    (k : Nat) (π : PureProfile I) : PMF I.Outcome :=
  Math.ProbabilityMassFunction.pushforward (D.runDistPure k π) I.outcomeOfStates

/-- Independent one-step realizability. -/
def OneStepIndependentRealizable (D : Dynamics I)
    [DecidableEq ι] [Fintype ι] [∀ i, Fintype (Option (Act i))]
    (ν : PMF (PureProfile I)) (n : Nat) : Prop :=
  ∃ b : BehavioralProfile I,
    (ν.bind (fun π =>
      (D.runDistPure n π).bind (fun ss =>
        Math.ProbabilityMassFunction.pushforward
          (D.stepDist b ss)
          (fun t => ss ++ [t])))) =
    (ν.bind (fun π =>
      (D.runDistPure n π).bind (fun ss =>
        Math.ProbabilityMassFunction.pushforward
          (D.stepDist (pureToBehavioral I π) ss)
          (fun t => ss ++ [t]))))

/-- Correlated one-step realizability. -/
def OneStepCorrelatedRealizable (D : Dynamics I)
    [DecidableEq ι] [Fintype ι] [∀ i, Fintype (Option (Act i))]
    (ν : PMF (PureProfile I)) (n : Nat) : Prop :=
  ∃ b : BehavioralProfileCorr I,
    (ν.bind (fun π =>
      (D.runDistPure n π).bind (fun ss =>
        Math.ProbabilityMassFunction.pushforward
          (D.stepDistCorr b ss)
          (fun t => ss ++ [t])))) =
    (ν.bind (fun π =>
      (D.runDistPure n π).bind (fun ss =>
        Math.ProbabilityMassFunction.pushforward
          (D.stepDist (pureToBehavioral I π) ss)
          (fun t => ss ++ [t]))))

end Dynamics
end Execution

end GameTheory
