/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/
import GameTheory.Concepts.Repeated.Uniform
import GameTheory.Concepts.Welfare.FolkTheorem.Trigger

/-!
# Cesàro trigger accounting

This file gives the finite-horizon counterpart of the discounted trigger
argument in `Trigger.lean`.  The monitoring model is the same one: the chosen
stage-game profile is publicly observed after every period.  In particular,
when the stage game is a mixed extension, mixed-action profiles themselves are
observed; this is not a theorem about monitoring only realized pure actions.

The primitive arithmetic hypothesis is a uniform bound on *punishment debt*:
over every finite tail of the intended path, the punishment cap can exceed the
intended total payoff by at most a fixed constant.  A first deviation can gain
at most one bounded stage payoff, and all later stages are capped.  Hence the
total deviation gain is bounded independently of the horizon and its average
is `O(1 / T)`.

The principal conclusions here concern one fixed repeated profile.  They do
not assert that every payoff satisfying individual-rationality inequalities is
generated by one coherent profile; that payoff-level selection statement has
strictly different quantifiers.
-/

noncomputable section

open scoped BigOperators

namespace GameTheory

namespace KernelGame

variable {ι : Type}

/-- The punishment cap accumulates at most `D` more payoff than the intended
path on every finite tail.  This is the exact Cesàro accounting condition used
by the trigger proof; periodic cycles satisfying the appropriate cycle-average
inequality provide the main application. -/
def HasCesaroPunishmentDebtBound (G : KernelGame ι)
    (path : ℕ → Profile G) (who : ι) (b D : ℝ) : Prop :=
  ∀ start length : ℕ,
    (length : ℝ) * b -
        ∑ k ∈ Finset.range length, G.eu (path (start + k)) who ≤ D

/-- Every finite block of a bounded periodic real sequence differs from its
length times the cycle average by at most the cost of one incomplete cycle. -/
theorem abs_sum_periodic_sub_mul_average_le
    {n : ℕ} [NeZero n] (a : Fin n → ℝ) {C : ℝ}
    (hC0 : 0 ≤ C) (hbd : ∀ j, |a j| ≤ C) (start length : ℕ) :
    |(∑ k ∈ Finset.range length, a (Fin.ofNat n (start + k))) -
        (length : ℝ) * ((n : ℝ)⁻¹ * ∑ j : Fin n, a j)| ≤
      2 * (n : ℝ) * C := by
  have hnposNat : 0 < n := Nat.pos_of_ne_zero (NeZero.ne n)
  have hnpos : (0 : ℝ) < n := by exact_mod_cast hnposNat
  let avg : ℝ := (n : ℝ)⁻¹ * ∑ j : Fin n, a j
  have hsum_upper : (∑ j : Fin n, a j) ≤ ∑ _j : Fin n, C := by
    apply Finset.sum_le_sum
    intro j _hj
    exact (abs_le.mp (hbd j)).2
  have hsum_lower : (∑ _j : Fin n, -C) ≤ ∑ j : Fin n, a j := by
    apply Finset.sum_le_sum
    intro j _hj
    exact (abs_le.mp (hbd j)).1
  have havg_upper : avg ≤ C := by
    dsimp [avg]
    calc
      (n : ℝ)⁻¹ * ∑ j : Fin n, a j ≤
          (n : ℝ)⁻¹ * ∑ _j : Fin n, C := by
        exact mul_le_mul_of_nonneg_left hsum_upper (by positivity)
      _ = C := by
        simp [Finset.sum_const, nsmul_eq_mul]
        field_simp
  have havg_lower : -C ≤ avg := by
    calc
      -C = (n : ℝ)⁻¹ * ((n : ℝ) * (-C)) := by field_simp
      _ = (n : ℝ)⁻¹ * ∑ _j : Fin n, -C := by
        simp [Finset.sum_const, nsmul_eq_mul]
      _ ≤ (n : ℝ)⁻¹ * ∑ j : Fin n, a j := by
        exact mul_le_mul_of_nonneg_left hsum_lower (inv_nonneg.mpr hnpos.le)
      _ = avg := rfl
  change |(∑ k ∈ Finset.range length, a (Fin.ofNat n (start + k))) -
      (length : ℝ) * avg| ≤ 2 * (n : ℝ) * C
  induction length using Nat.strong_induction_on generalizing start with
  | h length ih =>
      by_cases hshort : length < n
      · have hblock_upper :
            (∑ k ∈ Finset.range length, a (Fin.ofNat n (start + k))) ≤
              (length : ℝ) * C := by
          calc
            (∑ k ∈ Finset.range length, a (Fin.ofNat n (start + k))) ≤
                ∑ _k ∈ Finset.range length, C := by
              apply Finset.sum_le_sum
              intro k _hk
              exact (abs_le.mp (hbd (Fin.ofNat n (start + k)))).2
            _ = (length : ℝ) * C := by
              simp [Finset.sum_const, nsmul_eq_mul]
        have hblock_lower :
            (length : ℝ) * (-C) ≤
              ∑ k ∈ Finset.range length, a (Fin.ofNat n (start + k)) := by
          calc
            (length : ℝ) * (-C) = ∑ _k ∈ Finset.range length, -C := by
              simp [Finset.sum_const, nsmul_eq_mul]
            _ ≤ ∑ k ∈ Finset.range length, a (Fin.ofNat n (start + k)) := by
              apply Finset.sum_le_sum
              intro k _hk
              exact (abs_le.mp (hbd (Fin.ofNat n (start + k)))).1
        have havgpart_upper : (length : ℝ) * avg ≤ (length : ℝ) * C :=
          mul_le_mul_of_nonneg_left havg_upper (Nat.cast_nonneg length)
        have havgpart_lower : (length : ℝ) * (-C) ≤ (length : ℝ) * avg :=
          mul_le_mul_of_nonneg_left havg_lower (Nat.cast_nonneg length)
        have hlength_le : (length : ℝ) ≤ n := by
          exact_mod_cast hshort.le
        rw [abs_le]
        constructor <;> nlinarith
      · have hnle : n ≤ length := Nat.le_of_not_gt hshort
        let remainder : ℕ := length - n
        have hlength : length = n + remainder := by
          dsimp [remainder]
          omega
        have hremainder_lt : remainder < length := by
          dsimp [remainder]
          omega
        have hblock :
            (∑ k ∈ Finset.range n, a (Fin.ofNat n (start + k))) =
              ∑ j : Fin n, a j := by
          rw [← Fin.sum_univ_eq_sum_range
            (fun k => a (Fin.ofNat n (start + k))) n]
          exact sum_fin_rotate start a
        have hsplit :
            (∑ k ∈ Finset.range length, a (Fin.ofNat n (start + k))) =
              (∑ k ∈ Finset.range n, a (Fin.ofNat n (start + k))) +
              ∑ k ∈ Finset.range remainder,
                a (Fin.ofNat n (start + n + k)) := by
          rw [hlength, Finset.sum_range_add]
          congr 1
          apply Finset.sum_congr rfl
          intro k _hk
          congr 2
          omega
        have hnavg : (n : ℝ) * avg = ∑ j : Fin n, a j := by
          dsimp [avg]
          field_simp
        have hlengthReal : (length : ℝ) = (n : ℝ) + remainder := by
          exact_mod_cast hlength
        rw [hsplit, hblock, hlengthReal]
        rw [← hnavg]
        convert ih remainder hremainder_lt (start + n) using 1
        ring_nf

/-- A periodic path whose cycle average weakly exceeds `b` has uniformly
bounded punishment debt.  The deliberately simple bound `2 * n * C` covers
the one incomplete cycle at the end of any finite tail; every complete rotated
cycle has nonpositive debt. -/
theorem periodicPath_hasCesaroPunishmentDebtBound
    (G : KernelGame ι) {n : ℕ} [NeZero n]
    (cycle : Fin n → Profile G) (who : ι) {C b : ℝ}
    (hC0 : 0 ≤ C)
    (hbd : ∀ j : Fin n, |G.eu (cycle j) who| ≤ C)
    (hcycle : b ≤ G.cycleAveragePayoff cycle who) :
    G.HasCesaroPunishmentDebtBound
      (fun t => cycle (Fin.ofNat n t)) who b (2 * (n : ℝ) * C) := by
  intro start length
  have hdisc := abs_sum_periodic_sub_mul_average_le
    (fun j : Fin n => G.eu (cycle j) who) hC0 hbd start length
  have havg :
      (n : ℝ)⁻¹ * ∑ j : Fin n, G.eu (cycle j) who =
        G.cycleAveragePayoff cycle who := rfl
  rw [havg] at hdisc
  have hscaled :
      (length : ℝ) * b ≤
        (length : ℝ) * G.cycleAveragePayoff cycle who :=
    mul_le_mul_of_nonneg_left hcycle (Nat.cast_nonneg length)
  have hlower := (abs_le.mp hdisc).1
  linarith

/-- Cesàro averages of a bounded finite cycle converge to its uniform cycle
average.  The proof retains the explicit incomplete-cycle discrepancy bound
rather than appealing to an abstract summability theorem. -/
theorem tendsto_periodic_average
    {n : ℕ} [NeZero n] (a : Fin n → ℝ) {C : ℝ}
    (hC0 : 0 ≤ C) (hbd : ∀ j, |a j| ≤ C) :
    Filter.Tendsto
      (fun T : ℕ => (T : ℝ)⁻¹ *
        ∑ t ∈ Finset.range T, a (Fin.ofNat n t))
      Filter.atTop (nhds ((n : ℝ)⁻¹ * ∑ j : Fin n, a j)) := by
  apply Metric.tendsto_atTop.mpr
  intro ε hε
  let K : ℝ := 2 * (n : ℝ) * C
  obtain ⟨N, hN⟩ := exists_nat_gt (K / ε)
  refine ⟨max N 1, fun T hT => ?_⟩
  have hTpos : 0 < T :=
    lt_of_lt_of_le Nat.one_pos (le_trans (le_max_right N 1) hT)
  have hTreal : (0 : ℝ) < T := by exact_mod_cast hTpos
  have hTne : (T : ℝ) ≠ 0 := ne_of_gt hTreal
  have hTge : (N : ℝ) ≤ T := by
    exact_mod_cast le_trans (le_max_left N 1) hT
  have hKltN : K < (N : ℝ) * ε := by
    rw [div_lt_iff₀ hε] at hN
    exact hN
  have hKltT : K < (T : ℝ) * ε :=
    hKltN.trans_le (mul_le_mul_of_nonneg_right hTge hε.le)
  have hdisc := abs_sum_periodic_sub_mul_average_le a hC0 hbd 0 T
  have hrewrite :
      (T : ℝ)⁻¹ * (∑ t ∈ Finset.range T, a (Fin.ofNat n t)) -
          (n : ℝ)⁻¹ * ∑ j : Fin n, a j =
        (T : ℝ)⁻¹ *
          ((∑ t ∈ Finset.range T, a (Fin.ofNat n t)) -
            (T : ℝ) * ((n : ℝ)⁻¹ * ∑ j : Fin n, a j)) := by
    field_simp
  rw [Real.dist_eq, hrewrite, abs_mul,
    abs_of_nonneg (inv_nonneg.mpr hTreal.le)]
  calc
    (T : ℝ)⁻¹ *
        |(∑ t ∈ Finset.range T, a (Fin.ofNat n t)) -
          (T : ℝ) * ((n : ℝ)⁻¹ * ∑ j : Fin n, a j)| ≤
        (T : ℝ)⁻¹ * K := by
      exact mul_le_mul_of_nonneg_left (by simpa [K] using hdisc)
        (inv_nonneg.mpr hTreal.le)
    _ = K / T := by rw [inv_mul_eq_div]
    _ < ε := (div_lt_iff₀ hTreal).2 (by simpa [mul_comm] using hKltT)

/-- The prescribed periodic stage-profile path converges coordinatewise to
the cycle-average payoff. -/
theorem tendsto_periodicPath_cycleAveragePayoff
    (G : KernelGame ι) {n : ℕ} [NeZero n]
    (cycle : Fin n → Profile G) {C : ℝ} (hC0 : 0 ≤ C)
    (hbd : ∀ (who : ι) (j : Fin n), |G.eu (cycle j) who| ≤ C) :
    ∀ who,
      Filter.Tendsto
        (fun T : ℕ => (T : ℝ)⁻¹ *
          ∑ t ∈ Finset.range T,
            G.eu (cycle (Fin.ofNat n t)) who)
        Filter.atTop (nhds (G.cycleAveragePayoff cycle who)) := by
  intro who
  simpa [cycleAveragePayoff] using
    (tendsto_periodic_average
      (fun j : Fin n => G.eu (cycle j) who) hC0 (hbd who))

/-- On path, the trigger profile has exactly the intended finite-horizon
average payoff. -/
theorem finiteAveragePayoff_triggerRepeatedProfile_eq_path
    (G : KernelGame ι) [DecidableEq ι] [∀ i, Nonempty (G.Strategy i)]
    (path : ℕ → Profile G) (punish : ∀ who, G.OpponentProfile who)
    (T : ℕ) (who : ι) :
    G.finiteAveragePayoff T (G.triggerRepeatedProfile path punish) who =
      (T : ℝ)⁻¹ * ∑ t ∈ Finset.range T, G.eu (path t) who := by
  simp only [finiteAveragePayoff]
  congr 1
  apply Finset.sum_congr rfl
  intro t _ht
  rw [G.repeatedPlay_triggerRepeatedProfile_eq_path path punish t]

/-- A deviation which never fires the trigger has exactly the on-path
finite-horizon payoff. -/
theorem finiteAveragePayoff_update_trigger_eq_of_forall_status_none
    (G : KernelGame ι) [DecidableEq ι] [∀ i, Nonempty (G.Strategy i)]
    (path : ℕ → Profile G) (punish : ∀ who, G.OpponentProfile who)
    (who : ι) (dev : G.RepeatedStrategy who) (T : ℕ)
    (hstatus : ∀ t : ℕ,
      G.triggerStatus path t
        (fun k =>
          G.repeatedPlay
            (Function.update (G.triggerRepeatedProfile path punish) who dev) k) =
          none) :
    G.finiteAveragePayoff T
        (Function.update (G.triggerRepeatedProfile path punish) who dev) who =
      G.finiteAveragePayoff T (G.triggerRepeatedProfile path punish) who := by
  simp only [finiteAveragePayoff]
  congr 1
  apply Finset.sum_congr rfl
  intro t _ht
  rw [G.repeatedPlay_update_trigger_eq_path_of_forall_status_none
    path punish who dev hstatus t]
  rw [G.repeatedPlay_triggerRepeatedProfile_eq_path path punish t]

/-- Before a least trigger time `s`, every completed period strictly before
the firing period `s - 1` agrees with the intended path. -/
private theorem repeatedPlay_update_trigger_eq_path_before_first_fire
    (G : KernelGame ι) [DecidableEq ι] [∀ i, Nonempty (G.Strategy i)]
    (path : ℕ → Profile G) (punish : ∀ who, G.OpponentProfile who)
    (who : ι) (dev : G.RepeatedStrategy who) {s t : ℕ}
    (hmin : ∀ k < s,
      G.triggerStatus path k
        (fun m =>
          G.repeatedPlay
            (Function.update (G.triggerRepeatedProfile path punish) who dev) m) =
          none)
    (ht : t + 1 < s) :
    G.repeatedPlay
        (Function.update (G.triggerRepeatedProfile path punish) who dev) t =
      path t := by
  apply G.repeatedPlay_update_trigger_eq_path_of_status_none_succ
    path punish who dev
  · exact hmin t (lt_trans (Nat.lt_succ_self t) ht)
  · exact hmin (t + 1) ht

/-- A unilateral deviation whose trigger first fires at `s` gains at most one
bounded firing-stage discrepancy plus the path's punishment debt.  The bound
is on total payoff, so it is independent of the horizon. -/
theorem sum_stageEU_update_trigger_le_path_add_of_first_fire
    (G : KernelGame ι) [DecidableEq ι] [∀ i, Nonempty (G.Strategy i)]
    (path : ℕ → Profile G) (punish : ∀ who, G.OpponentProfile who)
    (who : ι) (dev : G.RepeatedStrategy who) {s : ℕ} (T : ℕ)
    {C b D : ℝ}
    (hbd : ∀ ρ : Profile G, |G.eu ρ who| ≤ C)
    (hbdd : BddAbove (Set.range fun own : G.Strategy who =>
      G.eu (G.profileWithOpponent who own (punish who)) who))
    (hpunish : G.bestResponseValueAgainstOpponents who (punish who) < b)
    (hdebt : G.HasCesaroPunishmentDebtBound path who b D)
    (hfire :
      G.triggerStatus path s
        (fun k =>
          G.repeatedPlay
            (Function.update (G.triggerRepeatedProfile path punish) who dev) k) =
          some who)
    (hmin : ∀ t < s,
      G.triggerStatus path t
        (fun k =>
          G.repeatedPlay
            (Function.update (G.triggerRepeatedProfile path punish) who dev) k) =
          none) :
    (∑ t ∈ Finset.range T,
        G.eu
          (G.repeatedPlay
            (Function.update (G.triggerRepeatedProfile path punish) who dev) t)
          who) ≤
      (∑ t ∈ Finset.range T, G.eu (path t) who) + (2 * C + D) := by
  let playDev : ℕ → Profile G := fun t =>
    G.repeatedPlay
      (Function.update (G.triggerRepeatedProfile path punish) who dev) t
  cases s with
  | zero =>
      simp [triggerStatus] at hfire
  | succ q =>
      by_cases hqT : q < T
      · let length : ℕ := T - (q + 1)
        have hT : T = (q + 1) + length := by
          dsimp [length]
          omega
        have hpref : ∀ t < q, playDev t = path t := by
          intro t ht
          apply G.repeatedPlay_update_trigger_eq_path_before_first_fire
            path punish who dev hmin
          omega
        have hpref_sum :
            (∑ t ∈ Finset.range q, G.eu (playDev t) who) =
              ∑ t ∈ Finset.range q, G.eu (path t) who := by
          apply Finset.sum_congr rfl
          intro t ht
          rw [hpref t (Finset.mem_range.mp ht)]
        have hheadDev : G.eu (playDev q) who ≤ C :=
          (abs_le.mp (hbd (playDev q))).2
        have hheadPath : -C ≤ G.eu (path q) who :=
          (abs_le.mp (hbd (path q))).1
        have hhead : G.eu (playDev q) who ≤ G.eu (path q) who + 2 * C := by
          linarith
        have htailStage : ∀ k : ℕ,
            G.eu (playDev (q + 1 + k)) who < b := by
          intro k
          have hkstatus := G.triggerStatus_update_trigger_some_mono
            path punish who dev hfire k
          exact G.eu_repeatedPlay_update_trigger_lt_of_status_some
            path punish who dev hbdd hpunish (by simpa [playDev] using hkstatus)
        have htail :
            (∑ k ∈ Finset.range length, G.eu (playDev (q + 1 + k)) who) ≤
              (∑ k ∈ Finset.range length, G.eu (path (q + 1 + k)) who) + D := by
          calc
            (∑ k ∈ Finset.range length, G.eu (playDev (q + 1 + k)) who) ≤
                ∑ _k ∈ Finset.range length, b := by
              apply Finset.sum_le_sum
              intro k _hk
              exact le_of_lt (htailStage k)
            _ = (length : ℝ) * b := by
              simp [Finset.sum_const, nsmul_eq_mul]
            _ ≤ (∑ k ∈ Finset.range length,
                    G.eu (path (q + 1 + k)) who) + D := by
              have := hdebt (q + 1) length
              linarith
        have hsplitDev :
            (∑ t ∈ Finset.range T, G.eu (playDev t) who) =
              ((∑ t ∈ Finset.range q, G.eu (playDev t) who) +
                G.eu (playDev q) who) +
              ∑ k ∈ Finset.range length, G.eu (playDev (q + 1 + k)) who := by
          rw [hT, Finset.sum_range_add, Finset.sum_range_succ]
        have hsplitPath :
            (∑ t ∈ Finset.range T, G.eu (path t) who) =
              ((∑ t ∈ Finset.range q, G.eu (path t) who) +
                G.eu (path q) who) +
              ∑ k ∈ Finset.range length, G.eu (path (q + 1 + k)) who := by
          rw [hT, Finset.sum_range_add, Finset.sum_range_succ]
        change (∑ t ∈ Finset.range T, G.eu (playDev t) who) ≤ _
        rw [hsplitDev, hsplitPath, hpref_sum]
        linarith
      · have hqge : T ≤ q := Nat.le_of_not_gt hqT
        have hall : ∀ t < T, playDev t = path t := by
          intro t ht
          apply G.repeatedPlay_update_trigger_eq_path_before_first_fire
            path punish who dev hmin
          omega
        have heq :
            (∑ t ∈ Finset.range T, G.eu (playDev t) who) =
              ∑ t ∈ Finset.range T, G.eu (path t) who := by
          apply Finset.sum_congr rfl
          intro t ht
          rw [hall t (Finset.mem_range.mp ht)]
        change (∑ t ∈ Finset.range T, G.eu (playDev t) who) ≤ _
        rw [heq]
        have hC0 : 0 ≤ C := by
          exact (abs_nonneg (G.eu (path 0) who)).trans (hbd (path 0))
        have hD0 : 0 ≤ D := by
          have h := hdebt 0 0
          simpa using h
        linarith

/-- At every horizon, the average gain from an arbitrary unilateral deviation
against a bounded-debt trigger profile is at most `(2 * C + D) / T`.  This is
the finite-horizon engine of the Cesàro trigger argument. -/
theorem finiteAveragePayoff_update_trigger_le_add_error
    (G : KernelGame ι) [DecidableEq ι] [∀ i, Nonempty (G.Strategy i)]
    (path : ℕ → Profile G) (punish : ∀ who, G.OpponentProfile who)
    (who : ι) (dev : G.RepeatedStrategy who) (T : ℕ)
    {C b D : ℝ} (hC0 : 0 ≤ C) (hD0 : 0 ≤ D)
    (hbd : ∀ ρ : Profile G, |G.eu ρ who| ≤ C)
    (hbdd : BddAbove (Set.range fun own : G.Strategy who =>
      G.eu (G.profileWithOpponent who own (punish who)) who))
    (hpunish : G.bestResponseValueAgainstOpponents who (punish who) < b)
    (hdebt : G.HasCesaroPunishmentDebtBound path who b D) :
    G.finiteAveragePayoff T
        (Function.update (G.triggerRepeatedProfile path punish) who dev) who ≤
      G.finiteAveragePayoff T (G.triggerRepeatedProfile path punish) who +
        (T : ℝ)⁻¹ * (2 * C + D) := by
  rcases G.triggerStatus_update_trigger_first_fire_or_never
      path punish who dev with hnever | hfirst
  · rw [G.finiteAveragePayoff_update_trigger_eq_of_forall_status_none
      path punish who dev T hnever]
    apply le_add_of_nonneg_right
    exact mul_nonneg (by positivity) (by linarith)
  · rcases hfirst with ⟨s, hfire, hmin⟩
    have hsum := G.sum_stageEU_update_trigger_le_path_add_of_first_fire
      path punish who dev T hbd hbdd hpunish hdebt hfire hmin
    rw [G.finiteAveragePayoff_triggerRepeatedProfile_eq_path path punish]
    unfold finiteAveragePayoff
    calc
      (T : ℝ)⁻¹ *
          ∑ t ∈ Finset.range T,
            G.eu
              (G.repeatedPlay
                (Function.update (G.triggerRepeatedProfile path punish) who dev) t)
              who ≤
          (T : ℝ)⁻¹ *
            ((∑ t ∈ Finset.range T, G.eu (path t) who) + (2 * C + D)) := by
        exact mul_le_mul_of_nonneg_left hsum (by positivity)
      _ = (T : ℝ)⁻¹ * (∑ t ∈ Finset.range T, G.eu (path t) who) +
          (T : ℝ)⁻¹ * (2 * C + D) := by ring

/-- A scalar error bound turns the total-gain estimate into finite-horizon
approximate Nash for the fixed trigger profile. -/
theorem triggerRepeatedProfile_isεFiniteRepeatedNash_of_error_bound
    (G : KernelGame ι) [DecidableEq ι] [∀ i, Nonempty (G.Strategy i)]
    (path : ℕ → Profile G) (punish : ∀ who, G.OpponentProfile who)
    (b : Payoff ι) {C D ε : ℝ} (hC0 : 0 ≤ C) (hD0 : 0 ≤ D)
    (hbd : ∀ (who : ι) (ρ : Profile G), |G.eu ρ who| ≤ C)
    (hbdd : ∀ who, BddAbove (Set.range fun own : G.Strategy who =>
      G.eu (G.profileWithOpponent who own (punish who)) who))
    (hpunish : ∀ who,
      G.bestResponseValueAgainstOpponents who (punish who) < b who)
    (hdebt : ∀ who, G.HasCesaroPunishmentDebtBound path who (b who) D)
    {T : ℕ} (herror : (T : ℝ)⁻¹ * (2 * C + D) ≤ ε) :
    G.IsεFiniteRepeatedNash T ε (G.triggerRepeatedProfile path punish) := by
  intro who dev
  have hgain := G.finiteAveragePayoff_update_trigger_le_add_error
    path punish who dev T hC0 hD0 (hbd who) (hbdd who) (hpunish who) (hdebt who)
  linarith

/-- Exact on-path equality transfers a prescribed Cesàro limit to the fixed
trigger profile. -/
theorem hasLongRunAveragePayoff_triggerRepeatedProfile_of_path
    (G : KernelGame ι) [DecidableEq ι] [∀ i, Nonempty (G.Strategy i)]
    (path : ℕ → Profile G) (punish : ∀ who, G.OpponentProfile who)
    (v : Payoff ι)
    (hpath : ∀ who,
      Filter.Tendsto
        (fun T : ℕ => (T : ℝ)⁻¹ *
          ∑ t ∈ Finset.range T, G.eu (path t) who)
        Filter.atTop (nhds (v who))) :
    G.HasLongRunAveragePayoff (G.triggerRepeatedProfile path punish) v := by
  intro who
  have hfun :
      (fun T => G.finiteAveragePayoff T
        (G.triggerRepeatedProfile path punish) who) =
      (fun T : ℕ => (T : ℝ)⁻¹ *
        ∑ t ∈ Finset.range T, G.eu (path t) who) := by
    funext T
    exact G.finiteAveragePayoff_triggerRepeatedProfile_eq_path
      path punish T who
  rw [hfun]
  exact hpath who

/-- A bounded-debt trigger architecture is a uniform equilibrium whenever its
on-path Cesàro payoff converges.  This is a fixed-profile theorem: the same
trigger profile works at every accuracy and every sufficiently long horizon. -/
theorem triggerRepeatedProfile_isUniformEquilibrium_of_cesaroDebt
    (G : KernelGame ι) [DecidableEq ι] [∀ i, Nonempty (G.Strategy i)]
    (path : ℕ → Profile G) (punish : ∀ who, G.OpponentProfile who)
    (b v : Payoff ι) {C D : ℝ} (hC0 : 0 ≤ C) (hD0 : 0 ≤ D)
    (hbd : ∀ (who : ι) (ρ : Profile G), |G.eu ρ who| ≤ C)
    (hbdd : ∀ who, BddAbove (Set.range fun own : G.Strategy who =>
      G.eu (G.profileWithOpponent who own (punish who)) who))
    (hpunish : ∀ who,
      G.bestResponseValueAgainstOpponents who (punish who) < b who)
    (hdebt : ∀ who, G.HasCesaroPunishmentDebtBound path who (b who) D)
    (hpath : ∀ who,
      Filter.Tendsto
        (fun T : ℕ => (T : ℝ)⁻¹ *
          ∑ t ∈ Finset.range T, G.eu (path t) who)
        Filter.atTop (nhds (v who))) :
    G.IsUniformEquilibrium (G.triggerRepeatedProfile path punish) := by
  refine ⟨⟨v,
    G.hasLongRunAveragePayoff_triggerRepeatedProfile_of_path path punish v hpath⟩,
    ?_⟩
  intro ε hε
  obtain ⟨T₀, hT₀⟩ := exists_nat_gt ((2 * C + D) / ε)
  refine ⟨max T₀ 1, fun T hT => ?_⟩
  have hTpos : 0 < T :=
    lt_of_lt_of_le Nat.one_pos (le_trans (le_max_right T₀ 1) hT)
  have hTreal : (0 : ℝ) < T := by exact_mod_cast hTpos
  have hTge : (T₀ : ℝ) ≤ T := by
    exact_mod_cast le_trans (le_max_left T₀ 1) hT
  have hKlt : 2 * C + D < (T₀ : ℝ) * ε := by
    rw [div_lt_iff₀ hε] at hT₀
    exact hT₀
  have hKle : 2 * C + D ≤ (T : ℝ) * ε := by
    have hmul : (T₀ : ℝ) * ε ≤ (T : ℝ) * ε :=
      mul_le_mul_of_nonneg_right hTge hε.le
    exact hKlt.le.trans hmul
  apply G.triggerRepeatedProfile_isεFiniteRepeatedNash_of_error_bound
    path punish b hC0 hD0 hbd hbdd hpunish hdebt
  rw [inv_mul_eq_div, div_le_iff₀ hTreal]
  simpa [mul_comm] using hKle

/-- Explicit finite-horizon Cesàro trigger bound for a periodic intended path.
The numerator consists of one firing-stage discrepancy `2 * C` and one
incomplete-cycle discrepancy `2 * n * C`. -/
theorem triggerPeriodicRepeatedProfile_isεFiniteRepeatedNash
    (G : KernelGame ι) [DecidableEq ι] [∀ i, Nonempty (G.Strategy i)]
    {n : ℕ} [NeZero n] (cycle : Fin n → Profile G)
    (punish : ∀ who, G.OpponentProfile who) (b : Payoff ι)
    {C ε : ℝ} (hC0 : 0 ≤ C)
    (hbd : ∀ (who : ι) (ρ : Profile G), |G.eu ρ who| ≤ C)
    (hbdd : ∀ who, BddAbove (Set.range fun own : G.Strategy who =>
      G.eu (G.profileWithOpponent who own (punish who)) who))
    (hpunish : ∀ who,
      G.bestResponseValueAgainstOpponents who (punish who) < b who)
    (hcycle : ∀ who, b who ≤ G.cycleAveragePayoff cycle who)
    {T : ℕ}
    (herror :
      (T : ℝ)⁻¹ * (2 * C + 2 * (n : ℝ) * C) ≤ ε) :
    G.IsεFiniteRepeatedNash T ε
      (G.triggerRepeatedProfile
        (fun t => cycle (Fin.ofNat n t)) punish) := by
  apply G.triggerRepeatedProfile_isεFiniteRepeatedNash_of_error_bound
    (C := C) (D := 2 * (n : ℝ) * C)
    (fun t => cycle (Fin.ofNat n t)) punish b hC0
    (by positivity) hbd hbdd hpunish
  · intro who
    exact G.periodicPath_hasCesaroPunishmentDebtBound
      cycle who hC0 (fun j => hbd who (cycle j)) (hcycle who)
  · exact herror

/-- Observable-profile Cesàro trigger theorem for a fixed finite cycle.  If
each player's cycle average weakly exceeds a strict punishment cap, the single
trigger profile is a uniform equilibrium and its long-run payoff is exactly
the cycle average.

This theorem observes the chosen `KernelGame` strategy profile each period.
For a mixed extension that means observable mixed actions, not merely realized
pure actions. -/
theorem triggerPeriodicRepeatedProfile_isUniformEquilibrium
    (G : KernelGame ι) [DecidableEq ι] [∀ i, Nonempty (G.Strategy i)]
    {n : ℕ} [NeZero n] (cycle : Fin n → Profile G)
    (punish : ∀ who, G.OpponentProfile who) (b : Payoff ι)
    {C : ℝ} (hC0 : 0 ≤ C)
    (hbd : ∀ (who : ι) (ρ : Profile G), |G.eu ρ who| ≤ C)
    (hbdd : ∀ who, BddAbove (Set.range fun own : G.Strategy who =>
      G.eu (G.profileWithOpponent who own (punish who)) who))
    (hpunish : ∀ who,
      G.bestResponseValueAgainstOpponents who (punish who) < b who)
    (hcycle : ∀ who, b who ≤ G.cycleAveragePayoff cycle who) :
    G.IsUniformEquilibrium
      (G.triggerRepeatedProfile
        (fun t => cycle (Fin.ofNat n t)) punish) := by
  apply G.triggerRepeatedProfile_isUniformEquilibrium_of_cesaroDebt
    (C := C) (D := 2 * (n : ℝ) * C)
    (fun t => cycle (Fin.ofNat n t)) punish b
    (G.cycleAveragePayoff cycle) hC0 (by positivity) hbd hbdd hpunish
  · intro who
    exact G.periodicPath_hasCesaroPunishmentDebtBound
      cycle who hC0 (fun j => hbd who (cycle j)) (hcycle who)
  · exact G.tendsto_periodicPath_cycleAveragePayoff
      cycle hC0 (fun who j => hbd who (cycle j))

end KernelGame

end GameTheory
