import FixedPointTheorems.brouwer
import FixedPointTheorems.kakutani
import GameTheory
import UniformEquilibrium
import Math.Probability.PhaseOccupationDuality
import Math.Probability.WeightedCollisionConcentration
import Math.PMFProduct.CollisionMass
import Math.SchauderFixedPoint
import UniformEquilibrium.Quitting.Classification.SingletonPacketDefectAlgebra
import UniformEquilibrium.Quitting.Classification.SingletonPacketEnergy
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimePacketEnergy
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeAggregatePrefixConsumption
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeAggregatePrefixResidualRegression
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeAtomicOwner
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeBallisticity
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeBoundaryProvenanceAlternative
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeCollisionAwareFiniteReturn
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeCommonWordRealization
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeConditionedFloorViability
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeConditionedDiffuseFixedOutsider
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeConditionedDiffuseReset
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeConditionedDiffuseFloorClip
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeConditionedDiffuseActualRepair
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeConditionedDiffuseClippedEdgeObstruction
import UniformEquilibrium.Quitting.Root.ApproximateFirstBranch
import UniformEquilibrium.Quitting.Root.TailStability
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeConditionedNegativeTangent
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeConditionedSlackThreshold
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeExactCycleStrata
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeEventualAllContinuePlateau
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeDebtSourceObstructionCarrier
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeDebtSourceDynamicAlternative
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeDebtSourceStrategicDecoder
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeKilledCapacityPotential
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeKilledTailPotential
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeOneStageObstructionCarrier
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimePeriodOneAttachmentRepair
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimePeriodOneTangentReadout
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimePreferenceLassoCirculationObstruction
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeReachableCarryTelescope
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeNonpositiveFloorTerminalCapRegression
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeTerminalIncomingPathAlternative
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeCapacityNearMaximizerRebase
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeStatePreservingChronologyCapacity
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeTerminalFundingFarkasDecoder
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeTerminalFundingSupportNecessity
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeTerminalFundingSupportEnlargement
import UniformEquilibrium.Diagnostics.Quitting.TerminalDebtLiteralStack
import UniformEquilibrium.Diagnostics.Quitting.TerminalEndpointGapTransport
import UniformEquilibrium.Diagnostics.Quitting.TerminalSemanticConditionedEndpointRegression
import UniformEquilibrium.Diagnostics.Quitting.TerminalSemanticEqualityStratum
import UniformEquilibrium.Diagnostics.Quitting.TerminalSemanticSoloOwnerRefinement
import UniformEquilibrium.Diagnostics.Quitting.TerminalSemanticMinimumSpine
import UniformEquilibrium.Diagnostics.Quitting.TerminalSemanticAllContinuePlateau
import UniformEquilibrium.Diagnostics.Quitting.TerminalSemanticPlateauTightness
import UniformEquilibrium.Diagnostics.Quitting.TerminalSemanticSoloSpineOccupation
import UniformEquilibrium.Diagnostics.Quitting.TerminalSemanticSupportEntry
import UniformEquilibrium.Diagnostics.Quitting.TerminalSemanticAtomicSupportBoundary
import UniformEquilibrium.Diagnostics.Quitting.TerminalSemanticAuxiliaryNashBudget
import UniformEquilibrium.Diagnostics.Quitting.TerminalCapNashEndpointTransport
import UniformEquilibrium.Diagnostics.Quitting.TerminalCapNashChronology
import UniformEquilibrium.Diagnostics.Quitting.TerminalSemanticCapNashDebtSupport
import UniformEquilibrium.Diagnostics.Quitting.TerminalSemanticCapNashNearMinimum
import UniformEquilibrium.Diagnostics.Quitting.TerminalSemanticMinimumDebtSimplex
import UniformEquilibrium.Diagnostics.Quitting.TerminalSemanticWeightedAuxiliaryNashBudget
import UniformEquilibrium.Diagnostics.Quitting.TerminalSemanticMinimumAggregateSurplus
import UniformEquilibrium.Diagnostics.Quitting.TerminalSemanticMinimumAggregateSurplusConsumer
import UniformEquilibrium.Diagnostics.Quitting.TerminalSemanticMinimumPlateauPacket
import UniformEquilibrium.Diagnostics.Quitting.TerminalSemanticPlateauQuantitativePassport
import UniformEquilibrium.Diagnostics.Quitting.TerminalSemanticPlateauTimeDisintegration
import UniformEquilibrium.Diagnostics.Quitting.TerminalSemanticPlateauIncidence
import UniformEquilibrium.Diagnostics.Quitting.TerminalSemanticPlateauDefectCharge
import UniformEquilibrium.Diagnostics.Quitting.TerminalSemanticPlateauDefectTelescope
import UniformEquilibrium.Diagnostics.Quitting.TerminalSemanticPlateauPositivePartSplit
import UniformEquilibrium.Diagnostics.Quitting.TerminalSemanticPlateauDebtTransfer
import UniformEquilibrium.Diagnostics.Quitting.TerminalSemanticPlateauDynamicCostate
import UniformEquilibrium.Diagnostics.Quitting.TerminalSemanticPlateauMaxDebtConsumer
import UniformEquilibrium.Diagnostics.Quitting.TerminalSemanticNegativeVertexGerm
import UniformEquilibrium.Diagnostics.Quitting.TerminalSemanticSoloQuantitativePassport
import UniformEquilibrium.Diagnostics.Quitting.TerminalDebtLiteralStackAllContinueRegression
import UniformEquilibrium.Quitting.Root.TerminalSemanticMoment
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeTargetTailGluingObstruction
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeTangentPacket
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeTangentAnchoredProjectiveLCP
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeTangentMixingCompatibility
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeTangentPacketEnergy
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeTangentProjectiveGauge
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeTangentProjectiveGaugeDefect
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeTangentProjectiveGaugeScalarClosure
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeTangentProjectiveGaugeSecondJet
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeTangentRegularArcLift
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeTangentSupportTransversality
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeTangentTwoOwnerExactRoot
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeTangentTwoOwnerPacketEdge
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeTangentTwoOwnerPacketDichotomy
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeTangentTwoOwnerOutsiderJetDichotomy
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeTangentTwoOwnerApproxPunishment
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeTangentTwoOwnerSupport
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeTangentSupportLiftFarkas
import UniformEquilibrium.Quitting.AbsorptionPath.CollisionConcentration
import UniformEquilibrium.Quitting.AbsorptionPath.NormalizedFiniteWindowOccupation
import UniformEquilibrium.Quitting.AbsorptionPath.FiniteWindowRefusalReweighting
import UniformEquilibrium.Quitting.AbsorptionPath.FlowCostateObstructionAdapter
import UniformEquilibrium.Quitting.AbsorptionPath.SurvivalWeightedObstructionAdapter
import UniformEquilibrium.Quitting.Bellman.Finite.BooleanMobiusAdapter
import UniformEquilibrium.Quitting.Boundary.Repair.SupportEnlargementAlternative
import UniformEquilibrium.Quitting.Boundary.Repair.FixedTailPositiveAbsorptionRoot
import UniformEquilibrium.Quitting.Cycles.PhantomBoundaryLimitGeometry
import UniformEquilibrium.Quitting.Cycles.PhantomBoundaryConditioning
import UniformEquilibrium.Quitting.Cycles.ConditionedDiffuseChronology
import UniformEquilibrium.Quitting.Cycles.ConditionedDiffuseCompiler
import UniformEquilibrium.Quitting.Cycles.ConditionedDeletedClockMonopoly
import UniformEquilibrium.Quitting.Cycles.ConditionedDeletedClockTerminalConcentration
import UniformEquilibrium.Quitting.Cycles.ConditionedDeletedClockSoloCompletion
import UniformEquilibrium.Quitting.Cycles.ConditionedDiffuseUniform
import UniformEquilibrium.Quitting.Cycles.ConditionedProperFaceDeficientClock
import UniformEquilibrium.Quitting.Cycles.ConditionedSoloExtraction
import UniformEquilibrium.Quitting.Cycles.ConditionedDiffuseProductRescaling
import UniformEquilibrium.Quitting.Cycles.ConditionedDiffuseStrategicRescaling
import UniformEquilibrium.Quitting.Cycles.ConditionedProductPurification
import UniformEquilibrium.Quitting.Cycles.ConditionedSingletonStrategicPurification
import UniformEquilibrium.Quitting.Cycles.ConditionedTangentSeam
import UniformEquilibrium.Quitting.Cycles.ConditionedPeriodicRenewal
import UniformEquilibrium.Quitting.Cycles.OwnShiftCycleExactification
import UniformEquilibrium.Quitting.Cycles.PeriodOneTangentAtlas
import UniformEquilibrium.Quitting.Paths.OutsiderNeverGluing
import UniformEquilibrium.Quitting.Paths.HazardScaledResidualCompiler
import UniformEquilibrium.Quitting.Paths.JointPolicySeparatedErrorCompiler
import UniformEquilibrium.Quitting.Punishment.ApproximateCompletedCycle
import UniformEquilibrium.Quitting.EssentialAPS.NashBellmanSingletonCycle
import UniformEquilibrium.Quitting.Terminal.TailCompression.SummableTailBestResponse

-- Fixed-point infrastructure used by existence theorems.
#print axioms brouwer_fixed_point
#print axioms brouwer_fixed_point_isFixedPt
#print axioms brouwer_fixedPoints_nonempty
#print axioms kakutani_fixed_point
#print axioms Math.Schauder.schauder_fixed_point
#print axioms Math.Schauder.schauder_fixed_point_isFixedPt
#print axioms Math.Schauder.schauder_fixedPoints_nonempty

-- Literal terminal-debt root-prefix descent.
#print axioms GameTheory.quittingContinuationBestResponseValue_rootThenContinuation_eq_max
#print axioms GameTheory.quittingTerminalDeviationDebt_rootThenContinuation_eq
#print axioms GameTheory.quittingTerminalDeviationDebt_rootThenContinuation_le_sub_min
#print axioms GameTheory.exists_exactRoot_terminalExploitability_le_and_debtSum_descent
#print axioms GameTheory.exists_lexicographicallyNearMinimal_terminalProfile
#print axioms GameTheory.not_hasLexicographicallyNearMinimalSingletonGap
#print axioms GameTheory.not_hasLexicographicallyNearMinimalFixedOutsider
#print axioms Math.SurvivalWeightedObstruction.Block.act_concat
#print axioms GameTheory.quittingTerminalDebt_utilization
#print axioms GameTheory.quittingRoot_all_quitProbability_mul_debtFloor_le_of_two_debtors
#print axioms GameTheory.quittingLiteralRootStack_debt_conservation_of_pos
#print axioms GameTheory.exists_deep_lexicographicallyNearMinimal_literalExactRootStack
#print axioms GameTheory.affineConditionedEndpointGap_le_terminalCoordinateDebt
#print axioms GameTheory.eventually_half_min_le_terminalCoordinateDebt_of_conditionedEndpointGap
#print axioms GameTheory.not_exists_sameProfile_conditionedEndpointGap_of_allContinueSemanticPair
#print axioms GameTheory.quittingTerminalSemanticCarrier_isCompact
#print axioms GameTheory.quittingTerminalSemanticPrefix_mem_carrier
#print axioms GameTheory.exists_profile_sequence_tendsto_minimumTerminalSemanticDebt
#print axioms GameTheory.quittingTerminalSemantic_minimum_twoPositiveDebt_all_quit_eq_zero
#print axioms GameTheory.quittingTerminalSemantic_minimum_stratum_alternative
#print axioms GameTheory.QuittingCounterexampleRegime.minimumTerminalSemantic_soloOwner_refinement
#print axioms GameTheory.exists_positive_minimumTerminalSemanticDebt_face_of_no_uniformPayoff
#print axioms GameTheory.quittingTerminalSemanticCarrier_prescribed_mem_rewardMomentSet
#print axioms GameTheory.exists_infinite_minimumTerminalSemanticSpine
#print axioms GameTheory.exists_positiveMinimumPlateau_or_fixedOwnerSoloSemanticSpine_of_no_uniformPayoff
#print axioms GameTheory.quittingTerminalSemantic_allContinuePlateau_finiteRewardObstruction
#print axioms GameTheory.exists_profiles_tendsto_allContinuePlateau_with_finiteRewardObstruction
#print axioms GameTheory.exists_pureTimeDeviation_terminalLaw_tendsto_semanticEnvelope
#print axioms GameTheory.exists_persistent_profitableAtom_of_allContinueSemanticPlateau
#print axioms GameTheory.QuittingCounterexampleRegime.exists_other_terminalGap_subsequence_of_semanticDebt_reset
#print axioms GameTheory.exists_persistent_profitableAtom_trichotomy_of_allContinueSemanticPlateau
#print axioms GameTheory.exists_minimum_allContinueNash_of_soloSemanticSpine_survival_lower
#print axioms GameTheory.exists_semanticPlateau_or_atomicSolo_of_noUE
#print axioms GameTheory.exists_minimalSoloBoundary_collision_nonzero_or_cotight_of_soloRoot
#print axioms GameTheory.exists_semanticPlateau_or_provenanceAtomicSolo_of_noUE
#print axioms GameTheory.exists_punishmentSeparated_sharp_minimalSoloBoundary_of_soloRoot
#print axioms GameTheory.exists_semanticPlateau_or_sharpBoundaryProvenanceAtomicSolo_of_noUE
#print axioms GameTheory.minimumTerminalSemantic_auxiliaryNash_budget
#print axioms GameTheory.minimumTerminalSemantic_auxiliaryNash_criticalFace
#print axioms GameTheory.minimumTerminalSemantic_exactNash_criticalFace
#print axioms GameTheory.minimumTerminalSemantic_is_allContinuePlateau
#print axioms GameTheory.minimumTerminalSemantic_singletonTight_iff_debtGate
#print axioms GameTheory.minimumTerminalSemantic_exactNash_allContinue_or_debtGateSolo
#print axioms GameTheory.minimumTerminalSemantic_weightedAuxiliaryNash_budget
#print axioms GameTheory.minimumTerminalSemantic_weightedIs_allContinuePlateau
#print axioms GameTheory.minimumTerminalSemantic_subset_singletonSurplus
#print axioms GameTheory.exists_terminalOutcome_subset_singletonSurplus_ge_minimumDebt
#print axioms GameTheory.minimumTerminalSemantic_subset_singletonSurplus_exact
#print axioms GameTheory.QuittingCounterexampleRegime.exists_supportedNever_or_supportedBlockedCoalition_exact
#print axioms GameTheory.QuittingCounterexampleRegime.exists_threeDebt_neverBudget_or_blockedCoalition_of_tightOwner
#print axioms GameTheory.not_hasProvenanceAtomicMinimumSemanticSoloRow
#print axioms GameTheory.noUniformPayoff_implies_positiveMinimumSemanticPlateau
#print axioms GameTheory.exists_terminalOutcome_quantitative_trichotomy_of_allContinuePlateau
#print axioms GameTheory.quittingTerminalOutcomeMass_eq_timeDisintegration
#print axioms GameTheory.positive_pureTime_terminalAtom_timeAlternative
#print axioms GameTheory.positive_stageCoalitionMass_has_semanticPrefixIncidence
#print axioms GameTheory.not_isZeroQuittingRootNash_profileLiveRoot_of_positive_collisionStageMass_at_minimumTail
#print axioms GameTheory.quittingTerminalSemanticDebt_prefix_le_nashDefect_add_transport
#print axioms GameTheory.minimumTerminalSemantic_sum_opponentAbsorption_charge_le_excess_add_defect
#print axioms GameTheory.quittingStageCoalitionMass_mul_tailDebt_le_liveMass_mul_drift_add_initialDebt
#print axioms GameTheory.terminalSemanticDebt_prefix_eq_stationaryContinueMass_mul_of_pureContinue_of_quit_le
#print axioms GameTheory.exists_samePureTimeLaw_negativeNever_or_chronologicalOpponentCharge
#print axioms GameTheory.sum_stageCollisionMass_mul_tailDebtSum_le_stoppedDefectExcess
#print axioms GameTheory.sum_liveMass_mul_spineOpponentAbsorptionDebtCharge_le_epsilon_add_defect
#print axioms GameTheory.exists_terminalSemanticResetCluster_quantitative_transfer
#print axioms GameTheory.exists_samePureTimeLaw_resetCluster_negativeNever_or_matched_separator
#print axioms GameTheory.nearMinimumTerminalSemantic_exploitabilityAuxiliaryNash_absorptionMass_le_sharp
#print axioms GameTheory.minimumTerminalSemantic_exploitabilityIs_allContinuePlateau
#print axioms GameTheory.exists_maxDebtSelector_sum_liveMass_mul_charge_le_epsilon_add_defect
#print axioms GameTheory.exists_maxDebtSelector_reference_mul_sum_opponentAbsorptionMass_le
#print axioms GameTheory.exists_maxDebtSelector_reference_mul_fixedOpponentClock_le
#print axioms GameTheory.quittingTerminalDebtSum_rootThenContinuation_eq_continueMass_mul_of_capNash
#print axioms GameTheory.capNash_absorptionMass_mul_debtSum_le_debtExcess
#print axioms GameTheory.terminalDebt_ge_endpointGap_sub_error_sub_joiningLossExcess
#print axioms GameTheory.terminalSemantic_exactNash_nearMinimum_support_budget
#print axioms GameTheory.exists_constantShiftNash_with_endpoint_moat
#print axioms GameTheory.not_nearMinimumTerminalSemantic_conditionedEndpointGap
#print axioms GameTheory.nearMinimumTerminalSemantic_capNash_eq_allContinue
#print axioms GameTheory.quittingTerminalDeviationDebt_capNashRootStack_eq
#print axioms GameTheory.debtSumInf_mul_capNashStackAbsorptionSum_le_debtDrop
#print axioms GameTheory.exists_deep_nearMinimum_capNashChronology
#print axioms GameTheory.QuittingCounterexampleRegime.exists_joiner_or_punishmentMoat_sameLaw
#print axioms GameTheory.isUniformEquilibriumPayoff_soloReward_of_stationarySemanticGerm
#print axioms GameTheory.tendsto_quittingWindowRestartDelivery_conditionedValue
#print axioms GameTheory.tendsto_quittingTerminalPayoff_periodizedTailWindow_conditionedValue
#print axioms GameTheory.QuittingCounterexampleRegime.chargeTangentPacket_minimumBoundary_underfunds_outsider
#print axioms GameTheory.isQuittingLiteralExactRootStack_replicate_allContinue

-- README headline theorem packages.
#print axioms GameTheory.KernelGame.mixed_nash_exists
#print axioms GameTheory.KernelGame.correlatedEq_exists
#print axioms GameTheory.KernelGame.coarseCorrelatedEq_exists
#print axioms EFG.zermelo
#print axioms EFG.oneShotDeviation_iff_spe
#print axioms GameTheory.KernelGame.von_neumann_minimax
#print axioms ObsModel.kuhn_behavioral_to_mixed
#print axioms ObsModel.kuhn_mixed_to_behavioral_semantic
#print axioms ObsModelCore.kuhn_behavioral_to_mixed
#print axioms ObsModelCore.kuhn_mixed_to_behavioral_semantic
#print axioms GameTheory.arrow_impossibility_exact
#print axioms GameTheory.SCF.gibbard_satterthwaite
#print axioms GameTheory.May.may_theorem
#print axioms GameTheory.GeneralMechanism.revelation_principle
#print axioms GameTheory.SocialChoice.FairDivision.Divisible.stromquist_envyFree_exists
#print axioms GameTheory.SocialChoice.FairDivision.Divisible.MeasureInstance.envyFree_exists
#print axioms GameTheory.CoalGame.shapleyValue_unique
#print axioms GameTheory.VNM.exists_representsExpectedUtility_of_vnmAxioms
#print axioms GameTheory.VNM.vnmAxioms_iff_exists_representsExpectedUtility

-- Repeated games and online learning.
#print axioms GameTheory.KernelGame.discounted_folk_theorem_approx
#print axioms Math.OnlineLearning.mw_externalRegret_le
#print axioms GameTheory.KernelGame.timeAverage_isεCCE_of_regret_le
#print axioms Math.Approachability.blackwell_approaches
#print axioms Math.Approachability.regretMatch_approaches

-- Auction and mechanism-design headline results.
#print axioms GameTheory.VCGSetup.vcg_truthful
#print axioms GameTheory.vickrey_truthful_dominant
#print axioms GameTheory.ReserveVickrey.mechanism_isDSIC
#print axioms GameTheory.KnapsackAuction.welfareMaximizingMechanism_isDSIC
#print axioms GameTheory.SingleParameterMechanism.existsUnique_zeroNormalized_payment_of_isMonotone

-- Social choice, matching, and cooperative games.
#print axioms GameTheory.sen_paretian_liberal
#print axioms GameTheory.median_is_condorcet_winner
#print axioms GameTheory.MatchingMarket.exists_stable
#print axioms GameTheory.MatchingMarket.OptionalOrder.lattice
#print axioms GameTheory.CoalGame.IsCore.isBalanced
#print axioms GameTheory.CoalGame.costOfStability_eq_zero_iff_core
#print axioms GameTheory.CoalGame.banzhafIndex_additive
#print axioms GameTheory.CoalGame.shapleyShubikIndex_sum_eq_one

-- Indivisible fair division and correlation saturation.
#print axioms GameTheory.SocialChoice.FairDivision.Indivisible.roundRobinAllocation_isEF1
#print axioms GameTheory.SocialChoice.FairDivision.Indivisible.exists_efx_two_agents
#print axioms GameTheory.KernelGame.strictDominant_isCoarseCorrelationSaturated
#print axioms GameTheory.KernelGame.IsIESDSSolvable.isCorrelationSaturated

-- ============================================================================
-- Uniform-equilibrium / quitting-game program: headline landed declarations.
-- The two intentional open declarations (`GameTheory.quittingGame_exists_
-- uniformEquilibriumPayoff` and `GameTheory.exists_uniformDeviationCapConstructor`)
-- are deliberately excluded: they carry `sorry` and are expected to report it.
-- ============================================================================

-- Terminal-to-uniform selection and the asymptotic-Nash bridge.
#print axioms GameTheory.StochasticGame.isUniformεEquilibrium_of_isεAsymptoticNash_of_upperApproximation
#print axioms GameTheory.quittingGame_exists_uniformEquilibriumPayoff_of_terminalNash_all_errors
#print axioms GameTheory.quittingGame_exists_uniformEquilibriumPayoff_iff_terminalNash_all_errors

-- The admissible-cycle compiler and the three-branch trichotomy.
#print axioms GameTheory.exists_uniformEquilibriumPayoff_of_admissible_quittingCyclicContinuationBlock
#print axioms GameTheory.exists_uniformEquilibriumPayoff_of_zeroSolo_or_admissibleCycle
#print axioms GameTheory.quittingCycle_zeroSolo_or_admissible_or_isolatedNegative
#print axioms GameTheory.QuittingDisjunctionCounterexample.not_zeroSolo_and_not_admissible_and_isolatedNegative
#print axioms GameTheory.quittingThreeBranch_not_mutually_exclusive

-- The low-dimensional closures of the quitting conjecture.
#print axioms GameTheory.QuittingTwoPlayerExistence.quittingGame_exists_uniformEquilibriumPayoff_twoPlayer
#print axioms GameTheory.QuittingTwoPlayerExistence.quittingGame_isUniformEquilibriumPayoff_jointExit
#print axioms GameTheory.quittingGame_exists_uniformEquilibriumPayoff_threePlayer

-- The sure-exit-set characterization at every number of players: a pure
-- exit profile is an exact terminal equilibrium exactly when no player
-- gains by toggling its own membership in the exit set.
#print axioms GameTheory.isεAsymptoticNash_pureSetRoot_iff
#print axioms GameTheory.isεAsymptoticNash_pureSetRoot_iff_isQuittingSureExitSet
#print axioms GameTheory.isUniformEquilibriumPayoff_setReward_of_isQuittingSureExitSet
#print axioms GameTheory.isεAsymptoticNash_pureSetRoot_univ_iff

-- The exact dynamic-debt transport law and the seam-price results.
#print axioms GameTheory.quittingFiniteDynamicDebt_eq_max_zero_sub_accumulatedStageGaps
#print axioms GameTheory.quittingDynamicDebtTail_conservation
#print axioms GameTheory.QuittingCounterexampleSeamWitness.debt_eq_survivalLimit_mul_limit_add_tsum_weightedSeam
#print axioms GameTheory.QuittingCounterexampleSeamWitness.ownerSemanticGap_tendsto_limitValue
#print axioms GameTheory.QuittingCounterexampleSeamWitness.tailDynamicDebtCap_mem_and_floor
#print axioms GameTheory.QuittingCounterexampleSeamWitness.canonicalPeriodicTailWindow_eventuallyPayoffBlocked
#print axioms GameTheory.QuittingCounterexampleRegime.exists_pos_uniform_normalizedSingletonPacketRefusal
#print axioms GameTheory.punishmentFloorPrefixChargeCapacity_eq_top_of_coalitionLock
#print axioms GameTheory.QuittingCounterexampleRegime.not_isQuittingSureExitSet_of_nonempty_via_prefixCapacity
#print axioms GameTheory.quitting_sub_blockFixedPoint_eq_div
#print axioms GameTheory.QuittingSeamPriceDeviationFalsity.seamPriceLaw_fails_for_deviation_via_fullDeficit

-- The sequential marked-path completion and its correlated closed splice
-- relations.
#print axioms GameTheory.MetrizableMarkedAbsorptionCompletion.exists_finite_sequence_tendsto
#print axioms GameTheory.MetrizableMarkedAbsorptionCompletion.surjective_maximalToMetrizable
#print axioms GameTheory.MetrizableMarkedAbsorptionCompletion.exists_exactSeam_sequence_tendsto
#print axioms GameTheory.MetrizableMarkedAbsorptionCompletion.associativityWitness_common_result
#print axioms GameTheory.chronology_holonomy_coordinates_mem_box
#print axioms GameTheory.MetrizableMarkedAbsorptionCompletion.metrizableBoundaryHolonomy_completeMetrizable
#print axioms GameTheory.MetrizableMarkedAbsorptionCompletion.continuous_metrizableBehavioralTailRepairValue
#print axioms GameTheory.MetrizableMarkedAbsorptionCompletion.exists_finite_subsequence_with_repairState_limit

-- Punishment level and individual rationality.
#print axioms GameTheory.StochasticGame.punishmentLevel_le_add_of_isUniformEquilibriumPayoff
#print axioms GameTheory.StochasticGame.not_isUniformEquilibriumPayoff_of_punishmentLevel_gt
#print axioms GameTheory.StochasticGame.eventually_isεIndividuallyRational_of_isUniformEquilibriumPayoff
#print axioms GameTheory.punishmentLevel_quittingGame_le_max

-- The action-legality chain, including the disintegration payoff equality.
#print axioms GameTheory.StochasticGame.finiteAveragePayoff_devPrime_eq
#print axioms GameTheory.StochasticGame.isLegalUniformEquilibriumPayoff_of_witness

-- The `PMF Bool` / real-hazard encoding bridge.
#print axioms GameTheory.isExactRowComplementary_hazardOfRoot_iff

-- The perturbed-cyclic-weight exclusion and the row dichotomy it restates.
#print axioms GameTheory.atMostOnePositive_of_isεQuittingRootEndpointNash_cyclicWeightReward
#print axioms GameTheory.atMostOnePositive_of_isExactRowComplementary

-- Joint complementarity, absorption-from-optimality, and coordinate silence.
#print axioms GameTheory.isQuittingJointComplementary_quittingCyclicBlockRoots
#print axioms GameTheory.isCompletelyAbsorbing_of_isQuittingJointComplementary_of_solo_pos
#print axioms GameTheory.QuittingCandidateHardWeightCoordinateSilence.quitProbability_true_eq_zero_of_isQuittingJointComplementary

-- Backward stability of root ε-complementarity (E64, period-one base case)
-- and the lens-identity's first leg: the condition number is the
-- weighted-to-unweighted conversion factor.
#print axioms GameTheory.exists_exact_of_isεQuittingRootEndpointNash
#print axioms GameTheory.exists_exact_of_pure
#print axioms GameTheory.abs_le_div_min_of_weighted_bounds
#print axioms GameTheory.abs_quittingRootEndpointDifference_le_div_min_of_isεQuittingRootEndpointNash
#print axioms GameTheory.exists_exact_ownShift_abs_eq_abs_quittingRootEndpointDifference
#print axioms GameTheory.min_lt_inv_of_exists_weighted_bound_not_isεRowComplementary

-- The weighted continue-mass bound and its scaled-cyclic-weight absence package.
#print axioms GameTheory.exists_pos_le_continueMass
#print axioms GameTheory.hasNoInstantApproxEquilibria_scaledCyclicWeight

-- The two-coordinate circulation boundary: the headline closed form.
#print axioms GameTheory.QuittingCirculationTwoCoordinateBoundary.circulationTwoExists_iff

-- The repaired four-player stress-point orbit and the general multi-owner
-- face-circulation orbit theorem.
#print axioms GameTheory.RepairedFourPlayerStress.exists_stressCirculation_orbit
#print axioms GameTheory.exists_multiCirculation_orbit

-- The one-sided decision-variation maximal inequality and the quitting
-- live-chain domination cap.
#print axioms Math.Probability.expect_indicator_scoreRunningMax_le_div
#print axioms GameTheory.quittingTerminalPayoff_update_quittingPhaseSwitchProfile_le_of_quitRegret_le

-- The pinned-pure row decoupling exclusion.
#print axioms GameTheory.not_isExactRowComplementary_cyclicWeight_of_pinned

-- The two-blocker interval cover, its non-exclusivity fence, the corrected
-- solo-quitter gate, and the three-player table refuting the single-blocker
-- designation.
#print axioms GameTheory.exists_switchingPair_of_forall_not_isUniversalRateBlocker
#print axioms GameTheory.exists_universalRateBlocker_or_switchingPair
#print axioms GameTheory.exists_family_isUniversalRateBlocker_and_switchingPair
#print axioms GameTheory.isUniversalRateBlocker_quittingJoiningGain_iff
#print axioms GameTheory.exists_soloQuitterRate_or_universalJoiner_or_switchingPair
#print axioms GameTheory.exists_soloQuitterRate_or_universalJoiner_of_card_le_two
#print axioms GameTheory.QuittingSwitchingBlockerTable.not_exists_universalJoiner

-- The bounded survival-window landing, the truncation fold, and the surviving
-- gap-free conditional compiler.  The former universal package producer is
-- refuted by the two-player theorem audited below and no longer exists.
#print axioms GameTheory.exists_pos_ratio_forall_exists_jointSurvivalWeight_mem_survivalWindow
#print axioms GameTheory.quittingRootSequenceHazardTerminalValue_quittingTruncatedRoots_le_of_plan_ledger_le
#print axioms GameTheory.quittingTerminalPayoff_update_quittingPhaseSwitchProfile_le_of_plan_ledger_le
#print axioms GameTheory.quittingGame_exists_uniformEquilibriumPayoff_of_hasQuittingLedgerCapPackage
#print axioms GameTheory.quittingGame_exists_uniformEquilibriumPayoff_of_truncatedLedgerCapPackage
#print axioms GameTheory.QuittingTruncatedLedgerCapCounterexample.not_hasQuittingTruncatedLedgerCapPackage_half
#print axioms GameTheory.exists_uniformEquilibriumPayoff_of_zeroSolo_or_truncatedLedgerCapProducer

-- ============================================================================
-- The three-player switching-residue regression table (pure arithmetic;
-- no stochastic-game dynamics) and its two general scalar lemmas.
-- ============================================================================

#print axioms GameTheory.QuittingSwitchingResidueRegression.q_one_pos
#print axioms GameTheory.QuittingSwitchingResidueRegression.max_d12_d13_ge
#print axioms GameTheory.QuittingSwitchingResidueRegression.d12_le_zero
#print axioms GameTheory.QuittingSwitchingResidueRegression.d13_le_zero
#print axioms GameTheory.QuittingSwitchingResidueRegression.d21_eq_one
#print axioms GameTheory.QuittingSwitchingResidueRegression.d31_eq_one
#print axioms GameTheory.QuittingSwitchingResidueRegression.sureExitFails_1
#print axioms GameTheory.QuittingSwitchingResidueRegression.sureExitFails_2
#print axioms GameTheory.QuittingSwitchingResidueRegression.sureExitFails_3
#print axioms GameTheory.QuittingSwitchingResidueRegression.sureExitFails_12
#print axioms GameTheory.QuittingSwitchingResidueRegression.sureExitFails_13
#print axioms GameTheory.QuittingSwitchingResidueRegression.sureExitFails_23
#print axioms GameTheory.QuittingSwitchingResidueRegression.sureExitFails_123
#print axioms GameTheory.QuittingSwitchingResidueRegression.collisionRepairFails12
#print axioms GameTheory.QuittingSwitchingResidueRegression.collisionRepairFails13
#print axioms GameTheory.QuittingSwitchingResidueRegression.collisionRepairFails21
#print axioms GameTheory.QuittingSwitchingResidueRegression.collisionRepairFails23
#print axioms GameTheory.QuittingSwitchingResidueRegression.collisionRepairFails31
#print axioms GameTheory.QuittingSwitchingResidueRegression.collisionRepairFails32
#print axioms GameTheory.QuittingSwitchingResidueRegression.collisionRate_ge_of_balance_nonneg
#print axioms GameTheory.QuittingSwitchingResidueRegression.not_balance_nonneg_of_gain_nonpos
#print axioms GameTheory.QuittingSwitchingResidueRegression.fixedGap_ge_half

-- ============================================================================
-- The game-layer bridge: the switching-residue regression table has no sure
-- exit set at all.
-- ============================================================================

#print axioms GameTheory.QuittingSwitchingResidueRegressionBridge.quittingSetReward_gameReward
#print axioms GameTheory.QuittingSwitchingResidueRegressionBridge.not_isQuittingSureExitSet_of_sureExitFails
#print axioms GameTheory.QuittingSwitchingResidueRegressionBridge.not_isQuittingSureExitSet_gameReward

-- The stationary endpoint compiler and the two exact solutions of the
-- switching-residue table.
#print axioms GameTheory.isZeroAsymptoticNash_stationary_iff_endpointNash_and_boundary
#print axioms GameTheory.isUniformEquilibriumPayoff_of_stationaryEndpointCertificate
#print axioms GameTheory.QuittingSwitchingResidueExactRoot.noSureExitSet_but_two_distinct_stationary_uniformPayoffs

-- The parametric witness that escapes the four local mechanisms while
-- retaining an exact stationary equilibrium.
#print axioms GameTheory.QuittingLocalMechanismResidueWitness.isLocalMechanismResidue_four
#print axioms GameTheory.QuittingLocalMechanismResidueWitness.isExactTerminalNash_doubleSureMixerProfile
#print axioms GameTheory.QuittingLocalMechanismResidueWitness.exists_uniformEquilibriumPayoff_four

-- Shared punishment: zero combination price for two players, versus the
-- exact positive price and optimizer classification on the cyclic
-- three-player table.
#print axioms GameTheory.quittingTwoPlayerSharedPunishmentExcess_eq_zero
#print axioms GameTheory.QuittingSharedThreePlayer.quittingSharedPunishmentExcess_eq_three_quarters
#print axioms GameTheory.QuittingSharedThreePlayer.quittingSharedPunishmentGap_eq_three_quarters_iff_first_eq_fair
#print axioms GameTheory.QuittingSharedThreePlayerDice.quittingBestReplyValue_eq_alwaysContinue

-- The quitting min-max is a stationary stopping value: the punishment
-- value, an infimum over all history-dependent opponent plans of the
-- supremum over all replies, is computed by constant opponent rows.
#print axioms GameTheory.quittingBestReplyValue_stationary
#print axioms GameTheory.quittingPunishmentValue_le_stationaryPunishmentValue
#print axioms GameTheory.quittingStationaryPunishmentValue_le_quittingPunishmentValue
#print axioms GameTheory.quittingPunishmentValue_eq_stationaryPunishmentValue
#print axioms GameTheory.quittingStationaryPunishmentValue_le_of_forall_hazard_le
#print axioms GameTheory.quittingRootSequenceHazardTerminalValue_const_le_cap
#print axioms GameTheory.quittingPunishmentValue_le_max_solo
#print axioms GameTheory.QuittingHostileTwoCoordinate.quittingPunishmentValue_eq
#print axioms GameTheory.QuittingProfitableSoloTwoCoordinate.quittingPunishmentValue_lt_max_solo

-- Diagonal target-tail assembly: player-indexed closed tails, exact
-- arbitrary-endpoint prefixes, exceptional-target selection, and the
-- resulting conditional uniform-payoff and counterexample restrictions.
#print axioms GameTheory.exists_quittingTargetClosedTail_of_stationaryRoot
#print axioms GameTheory.exists_finiteEndpointExactQuittingNashBellmanChain
#print axioms GameTheory.quittingPhaseSwitchHazardGap_le_four_mul_opponentSurvival
#print axioms GameTheory.exists_target_forall_opponentSurvivalWeight_le_of_joint_le_sq
#print axioms GameTheory.quittingGame_exists_uniformEquilibriumPayoff_of_exactDiagonalTargetTailCertificates
#print axioms GameTheory.exists_exactDiagonalTargetTailCertificate_errorFloor_of_no_uniformPayoff

-- Essential APS on the executable singleton-flow stratum: exact successor
-- extraction, algebraic greatest fixed family, zero-mass boundary, and the
-- supplied finite proper-cycle compiler.
#print axioms GameTheory.quittingFleschSuccessor_of_consecutive_arcs
#print axioms GameTheory.quittingEssentialAPSGreatestFamily_fixed
#print axioms GameTheory.quittingEssentialAPS_zeroMassFixedPoint_regression
#print axioms GameTheory.QuittingEssentialAPSCycleCertificate.opponentContracts
#print axioms GameTheory.QuittingEssentialAPSCycleCertificate.isUniformEquilibriumPayoff

-- Path budgets and bounded potentials.
#print axioms Math.ChargedPathBudget.ChargedRelation.hasFiniteBudget_iff_exists_boundedPotential
#print axioms Math.ChargedPathBudget.ChargedRelation.isLeast_oscillation
#print axioms Math.ChargedPathBudget.ChargedRelation.budgetEN_eq_iInf_oscillation
#print axioms Math.ChargedPathBudget.ChargedRelation.isLeast_value
#print axioms Math.ChargedPathBudget.ChargedRelation.not_exists_boundedPotential_of_positive_selfLoop
#print axioms Math.ChargedPathBudget.Towers.not_hasFiniteBudget
#print axioms Math.ChargedPathBudget.Interpolation.budget_eq_one
#print axioms Math.ChargedPathBudget.Interpolation.not_continuous_of_isPotential
#print axioms Math.ChargedPathBudget.QuitBonus.oneStageUpdate_fixed
#print axioms Math.ChargedPathBudget.QuitBonus.no_boundedPotential

-- The one-stage collision repair works iff owner endpoint optimality,
-- spectator no-join, and the blocker-floor balance against the exact
-- min-max all hold; sub-floor gaps force the collision intensity.
#print axioms GameTheory.quittingCollisionRepairWorks_iff
#print axioms GameTheory.quittingCollisionRepairWorks_one_iff
#print axioms GameTheory.quittingCollisionOwnerCap_le_of_isεAsymptoticNash
#print axioms GameTheory.quittingCollisionSpectatorJoin_le_of_isεAsymptoticNash
#print axioms GameTheory.quittingCollisionBlockerFloor_le_of_isεAsymptoticNash
#print axioms GameTheory.isεAsymptoticNash_quittingCollisionRepairProfile
#print axioms GameTheory.quittingTerminalPayoff_update_oneStagePunishedProfile_le
#print axioms GameTheory.quittingRootSequenceHazardTerminalValue_zero_split
#print axioms GameTheory.quittingCollisionRate_ge_of_blockerBalance
#print axioms GameTheory.quittingCollisionBlockerGain_ge_of_subFloor
#print axioms GameTheory.not_quittingCollisionRepairWorks_of_subFloor_of_rate_lt
#print axioms GameTheory.quittingCollisionOwnerOptimal_iff_of_mem_Ioo

-- The repo's canonical one-stage operator realizes the quit-bonus
-- calibration self-loop exactly; no bounded potential exists for it.
#print axioms GameTheory.QuittingQuitBonusSelfLoopBridge.oneStageNext_reward_isSelfLoop
#print axioms GameTheory.QuittingQuitBonusSelfLoopBridge.no_boundedPotential

-- Matching-order projective extraction, affine/Farkas boundary, and the
-- rotation-uniform weighted-lasso compiler.
#print axioms GameTheory.QuittingGermMatchingLeadingData.nonsingletonFirstEventWeight_tendsto_zero
#print axioms GameTheory.QuittingGermMatchingLeadingData.toProjectiveSingletonPacket
#print axioms GameTheory.QuittingProjectiveTargetMismatch.germ_matchingOrder
#print axioms GameTheory.QuittingProjectiveTargetMismatch.one_sub_le_four_mul_add_of_terminalNash_close
#print axioms GameTheory.QuittingProjectiveTargetMismatch.packet_value_not_isUniformEquilibriumPayoff
#print axioms GameTheory.QuittingProjectiveTargetMismatch.germ_endpointValue_not_isUniformEquilibriumPayoff
#print axioms GameTheory.QuittingProjectiveTargetMismatch.firstExitValue_isUniformEquilibriumPayoff
#print axioms GameTheory.QuittingProjectiveTargetMismatch.secondExitValue_isUniformEquilibriumPayoff
#print axioms Math.LinearAlgebra.affineEqualityInequality_feasible_or_farkas
#print axioms GameTheory.quittingGame_exists_uniformEquilibriumPayoff_of_weightedProjectiveLassos

-- The punishment-floor predecessor producer and its selected-orbit
-- charge alternative.
#print axioms GameTheory.quittingPunishmentValue_le_rootSuccessorPayoff_of_tail_ge
#print axioms GameTheory.quittingGame_exists_uniformEquilibriumPayoff_of_punishmentFloorForwardCharge
#print axioms GameTheory.quittingGame_uniformPayoff_or_punishmentFloorForwardChargeBound
#print axioms GameTheory.quittingPunishmentValue_le_finitePrefixValue
#print axioms GameTheory.quittingGame_exists_uniformPayoff_of_arbitrarilyCharged_floorPrefixes
#print axioms GameTheory.quittingGame_uniformPayoff_or_bounded_floorPrefixCharge
#print axioms Math.ChargedPathBudget.ChargedRelation.DivergentSelection.exists_normalizedPath
#print axioms Math.ChargedPathBudget.ChargedRelation.chargeRenewal_iff_unboundedFiniteCharge_implies_canDiverge
#print axioms Math.ChargedPathBudget.ChargedRelation.exists_path_eq_finiteHorizonMaxCharge
#print axioms Math.ChargedPathBudget.ChargedRelation.hasUnboundedFiniteCharge_iff_hasUnboundedHorizonCharge
#print axioms Math.ChargedPathBudget.ChargedRelation.OneStepTower.unboundedFiniteCharge_and_not_canDiverge
#print axioms Math.ChargedPathBudget.ChargedRelation.DelayedPositiveLoop.firstUnitBlock_length
#print axioms Math.ChargedPathBudget.ChargedRelation.GreedyTrap.greedy_target_not_canDiverge
#print axioms Math.ChargedPathBudget.ChargedRelation.IncompatibleHorizonOptima.horizon_three_investment_optimum
#print axioms GameTheory.QuittingPunishmentFloorBoxPath.toFinitePrefix_charge
#print axioms GameTheory.quittingGame_uniformPayoff_or_punishmentFloorReachable_hasFiniteBudget
#print axioms GameTheory.quittingGame_uniformPayoff_or_punishmentFloorReachable_canonicalPotential
#print axioms GameTheory.quittingPunishmentFloorSelected_potential_decrement
#print axioms GameTheory.not_exists_uniformEquilibriumPayoff_iff_nonempty_counterexampleRegime
#print axioms GameTheory.not_exists_uniformEquilibriumPayoff_iff_exists_gap_and_finiteChargeCapacity
#print axioms GameTheory.punishmentFloorPrefixChargeCapacity_ne_top_iff
#print axioms GameTheory.terminalExploitabilityGap_le_finiteMinMaxDynamicDebt
#print axioms GameTheory.QuittingCounterexampleRegime.reachable_cycle_chargeSum_eq_zero
#print axioms GameTheory.QuittingCounterexampleRegime.exists_terminalGapDynamicDebtTail
#print axioms GameTheory.QuittingCounterexampleRegime.infiniteOrbit_absorptionMass_summable
#print axioms GameTheory.QuittingCounterexampleRegime.eventually_smallAbsorption_and_terminalExploitability
#print axioms GameTheory.QuittingCounterexampleRegime.exists_terminalGapDynamicDebtTail_with_summableAbsorption_of_nonpos
#print axioms GameTheory.quittingGame_exists_uniformPayoff_of_positive_reachable_return

-- Regime narrowing: toggle/stationary instability, small-player emptiness,
-- orbit value limits, the floor-violation collapse, and the analytic waist
-- with its forced packet.
#print axioms GameTheory.QuittingCounterexampleRegime.exists_toggle_gain
#print axioms GameTheory.QuittingCounterexampleRegime.exists_leave_or_join_gain
#print axioms GameTheory.QuittingCounterexampleRegime.not_isQuittingSureExitSet
#print axioms GameTheory.QuittingCounterexampleRegime.exists_terminalGap_le_soloReward
#print axioms GameTheory.QuittingCounterexampleRegime.exists_collision_gain
#print axioms GameTheory.QuittingCounterexampleRegime.one_lt_card
#print axioms GameTheory.QuittingCounterexampleRegime.exists_stationaryCap_gain
#print axioms GameTheory.quittingGame_exists_uniformEquilibriumPayoff_onePlayer
#print axioms GameTheory.QuittingCounterexampleRegime.elim_isEmpty
#print axioms GameTheory.QuittingCounterexampleRegime.elim_unique
#print axioms GameTheory.QuittingCounterexampleRegime.elim_twoPlayer
#print axioms GameTheory.QuittingCounterexampleRegime.elim_threePlayer
#print axioms GameTheory.QuittingCounterexampleRegime.infiniteOrbit_exists_value_limit
#print axioms GameTheory.quittingPunishmentValue_sub_le_continueMass_mul_of_nashBellmanEdge
#print axioms GameTheory.quittingDynamicDebtTail_floorViolation_mono
#print axioms GameTheory.summable_dynamicDebtTailAbsorptionCharge_of_floorViolation_of_positiveDebt
#print axioms GameTheory.QuittingCounterexampleRegime.exists_terminalGapDynamicDebtTail_summableAbsorption
#print axioms GameTheory.quittingGame_uniformPayoff_or_normalizedSingletonSourcePacket
#print axioms GameTheory.QuittingCounterexampleRegime.nonempty_normalizedSingletonSourcePacket
#print axioms GameTheory.quittingDynamicDebtCap_eq_rootSuccessorPayoff_add_seam
#print axioms GameTheory.QuittingCounterexampleRegime.exists_terminalGapDynamicDebtTail_selfLoopLimit
#print axioms GameTheory.QuittingCounterexampleRegime.exists_active_strictSingletonRefusal
#print axioms GameTheory.QuittingNormalizedSingletonSourcePacket.refusal_sub_mixture_eq_mass_div_mul_surplus
#print axioms GameTheory.QuittingCounterexampleRegime.exists_cyclicWindow_pureTimeCap_gap
#print axioms GameTheory.QuittingCounterexampleRegime.nonempty_seamWitness
#print axioms GameTheory.QuittingCounterexampleRegime.infiniteOrbit_tsum_abs_value_succ_sub_le
#print axioms GameTheory.QuittingCounterexampleRegime.infiniteOrbit_exists_selfLoop_limit
#print axioms GameTheory.quittingGame_exists_uniformEquilibriumPayoff_of_reindex
#print axioms GameTheory.quittingGame_exists_uniformEquilibriumPayoff_of_card_eq_two
#print axioms GameTheory.quittingGame_exists_uniformEquilibriumPayoff_of_card_eq_three
#print axioms GameTheory.QuittingCounterexampleRegime.three_lt_card

-- Canonical finite counterexamples, finite instability screens, packet support,
-- quantitative floor clocks, and the cap/restart semantic seams.
#print axioms GameTheory.isUniformEquilibriumPayoff_reindex_iff
#print axioms GameTheory.nonempty_counterexampleRegime_reindex_fin_iff
#print axioms GameTheory.exists_minimalFinQuittingCounterexample
#print axioms GameTheory.MinimalFinQuittingCounterexample.properRestriction_exists_uniformEquilibriumPayoff
#print axioms GameTheory.QuittingCounterexampleRegime.terminalGap_le_pureToggleCeiling
#print axioms GameTheory.QuittingCounterexampleRegime.exists_closedImprovementWalk_multiple_four
#print axioms GameTheory.QuittingCounterexampleRegime.exists_strictToggleClosedOrbit_from_empty_with_collision_entry
#print axioms GameTheory.QuittingCounterexampleRegime.terminalGap_le_stationaryCapCeiling
#print axioms GameTheory.QuittingNormalizedSingletonSourcePacket.exists_weakPreferenceClosedOrbit
#print axioms GameTheory.QuittingCounterexampleRegime.exists_supportedSingleton_terminalGap
#print axioms GameTheory.FourPlayerSingletonBlocker.exists_pos_uniform_escapeSeparation
#print axioms Math.Probability.DiscreteHazard.ScalarHazard.gap_le_survival_mul
#print axioms Math.Probability.DiscreteHazard.ScalarHazard.gap_div_bound_le_survival
#print axioms Math.Probability.DiscreteHazard.ScalarHazard.gap_mul_sum_stop_le_bound
#print axioms Math.Probability.DiscreteHazard.ScalarHazard.gap_mul_tsum_stop_natAdd_le_bound
#print axioms Math.Probability.DiscreteHazard.ScalarHazard.summable_stop_of_survivalAmplification
#print axioms GameTheory.quittingPunishmentGapTail_amplify
#print axioms GameTheory.quittingPunishmentGap_mul_partialOpponentClock_le
#print axioms GameTheory.quittingPunishmentGap_mul_tsum_opponentClock_le
#print axioms GameTheory.quittingPunishmentFloorAdmissiblePotential_predecessor_decrement
#print axioms GameTheory.QuittingCapSeededPrefix.terminalGap_le_jointSurvivalWeight_mul_capBound
#print axioms GameTheory.QuittingCapSeededPrefix.sum_absorptionMass_le_log_capBound_div_terminalGap
#print axioms GameTheory.QuittingDynamicDebtCapChargedAnchorCounterexample.absorptionCharge_eq_zero_of_nash_at_augmentedCap
#print axioms GameTheory.quittingDynamicDebtCap_transport_iff_capSeam_eq_zero
#print axioms GameTheory.terminalSemantic_debtHomotopy_absorption_budget
#print axioms GameTheory.QuittingCounterexampleRegime.minimumDebtHomotopy_endpoint_selection
#print axioms GameTheory.exists_fixed_playedMobiusIncidenceOccupation_of_defectOccupation
#print axioms GameTheory.QuittingFiniteMaxDebtMatchedFlow.QuittingFiniteMaxDebtMatchedCut.exists_maxDebtSource_vertex_or_weightedMinimumSurplus
#print axioms GameTheory.QuittingFiniteMaxDebtMatchedFlow.exists_pure_maxDebt_matched_path
#print axioms GameTheory.not_nonempty_maxDebtMatchedFlow_chronological_of_conserved
#print axioms GameTheory.exists_stops_tendsto_coordinateNashDefect_zero_of_persistent_collision
#print axioms GameTheory.QuittingMobiusIncidenceCancellationRegression.coordinateNashDefect_false_eq_zero
#print axioms GameTheory.quittingTerminalPayoff_update_sub_le_terminalSemanticDebt
#print axioms GameTheory.exists_markedTailCluster_escape_or_otherNashDefect
#print axioms GameTheory.quittingTerminalPayoff_stageBestEndpointDeviation_sub_eq_liveMass_mul_defect
#print axioms GameTheory.quittingTerminalSemanticDebt_stagePartialBestEndpoint_eq
#print axioms GameTheory.partialBestEndpoint_minimumReference_transfer_with_positiveIncidence
#print axioms GameTheory.isZeroQuittingRootNash_of_marked_sureQuit_of_others
#print axioms GameTheory.QuittingMarkedExitNashificationRegression.no_exact_unmarked_nashification_retains_marked_exit
#print axioms GameTheory.QuittingMarkedExitNashificationRegression.iterated_bestResponseReset_transfers_then_kills_defect
#print axioms GameTheory.capNashPrefix_resetExcursion_exact_account
#print axioms GameTheory.exists_resetFace_minimizer_with_unique_allContinue_capNash
#print axioms GameTheory.exists_fixedLaw_resetFace_minimizer_with_incidence
#print axioms GameTheory.quittingTerminalOpponentIncidenceMass_lawPrefix
#print axioms GameTheory.nearMinimum_resetPrefix_with_incidence_of_capNashReturnSelection
#print axioms GameTheory.QuittingCounterexampleRegime.exists_fixedLaw_resetFace_dispatch
#print axioms GameTheory.QuittingResetIncidenceCapRegression.positive_incidence_and_toggle_but_only_allContinue_capNash
#print axioms GameTheory.isQuittingNashBellmanEdge_dynamicDebtCapPoint_of_capSeam_eq_zero
#print axioms GameTheory.quittingOpponentSurvivalWeight_eq_one_of_returningDynamicDebt
#print axioms GameTheory.quittingDynamicDebtTailRoots_eq_allContinue_of_two_returningDynamicDebt
#print axioms GameTheory.eq_of_two_returningDynamicDebt_of_jointSurvival_lt_one
#print axioms GameTheory.quittingPrescribedValue_eq_terminalValue_add_survivalLimit_mul
#print axioms GameTheory.sSup_range_quittingTerminalPayoff_update_eq_periodicWindow
#print axioms GameTheory.quittingPeriodicWindowRefusalValue_sub_restartDelivery_eq_normalizedSeam
#print axioms GameTheory.quittingPeriodicWindowBestResponseValue_sub_terminalValue_le_normalizedDrift_of_exactNash
#print axioms GameTheory.QuittingCounterexampleRegime.exists_cyclicWindow_finiteEvaluation_gap
#print axioms GameTheory.QuittingPeriodicWindowFamily.lateRepairable_or_eventuallyPayoffBlocked
#print axioms GameTheory.abs_quittingRootSequenceBestResponseValue_sub_maxSolo_le_totalCharge_of_lt_one
#print axioms GameTheory.exists_quittingAnnotationBoundary_of_summableAbsorption
#print axioms GameTheory.quittingAnnotationBoundary_eq_singleton_of_activeSubsequence
#print axioms GameTheory.phaseUnderfunded_or_refusalFloorMissing
#print axioms GameTheory.quittingPacketWeightedSurplus_eq_quadraticForm
#print axioms GameTheory.quittingSingletonPacketSkewEnergy_eq_zero
#print axioms GameTheory.exists_uniformEquilibriumPayoff_of_pairwise_reciprocalSolo_nonpos
#print axioms GameTheory.quittingPacketWeightedRefusal_eq_quadraticForm
#print axioms GameTheory.QuittingCounterexampleRegime.exists_supported_pair_pos_reciprocalSoloEffect
#print axioms Math.Probability.finiteWeightedCollisionConcentration_or_zero
#print axioms Math.Probability.abs_conditionalPayoff_sub_singletonMixture_le
#print axioms Math.PMFProduct.collisionMass_le_choose_card_mul_absorption_sq
#print axioms GameTheory.finiteQuittingRootCollisionConcentration_or_zero
#print axioms GameTheory.abs_finiteQuittingRootConditionalPayoff_sub_singletonMixture_le
#print axioms GameTheory.QuittingFiniteRootWindow.zero_or_positive_normalizedMass
#print axioms GameTheory.QuittingFiniteRootWindow.tendsto_normalizedCollisionMass_zero
#print axioms GameTheory.QuittingFiniteRootWindow.tendsto_normalizedCollisionMass_zero_of_start_tendsto
#print axioms GameTheory.QuittingFiniteRootWindow.abs_delivery_sub_absorptionSingletonMixture_le
#print axioms GameTheory.QuittingFiniteRootWindow.abs_absorbingDelivery_sub_singletonMixture_le_of_cap
#print axioms GameTheory.QuittingFiniteRootWindow.quittingAnnotationBoundary_eq_singleton_of_normalizedWindowOccupation
#print axioms GameTheory.QuittingFiniteRootWindow.abs_normalized_forceContinue_sub_jointOff_le_of_lowerBound
#print axioms GameTheory.quittingRootExpectedPayoff_eq_continuation_add_multilinearValue
#print axioms GameTheory.quittingRootEndpointDifference_eq_mobiusCoordinateDerivative
#print axioms GameTheory.CoalGame.coordinateDerivative_eq_singleton_add_pair_add_higherOrder
#print axioms GameTheory.quittingRootEndpointDifference_eq_mobiusCardinalitySplit
#print axioms GameTheory.quittingRootEndpointDifference_eq_outsiderNever
#print axioms GameTheory.quittingRootSequencePureTimeTerminalValue_some_sub_none_eq
#print axioms GameTheory.quittingTerminalPayoff_update_le_never_add
#print axioms Math.ChargedPathBudget.ChargedRelation.hasChronologicalExecution_of_reachable_progress
#print axioms GameTheory.quittingEssentialAPSCarrier_terminalPath_or_infiniteRun_of_segmentClosed
#print axioms GameTheory.EssentialAPSOccupationCancellationRegression.global_balance_does_not_supply_chronological_cancellation
#print axioms GameTheory.QuittingCounterexampleSeamWitness.punishmentValue_le_tailValue
#print axioms GameTheory.QuittingCounterexampleSeamWitness.tailSegmentPunishmentFloorPrefix_charge
#print axioms GameTheory.QuittingCounterexampleSeamWitness.not_exists_sublinearAbsorptionReturn
#print axioms GameTheory.QuittingCounterexampleSeamWitness.exists_pos_eventually_endpointDistance_ge_absorptionMass
#print axioms GameTheory.QuittingCounterexampleSeamWitness.eventually_allContinue_or_exists_chargeTangentPacket
#print axioms GameTheory.QuittingCounterexampleSeamWitness.eventually_allContinue_or_exists_oneStage_chargeTangentPacket
#print axioms GameTheory.QuittingCounterexampleSeamWitness.eventually_allContinue_or_exists_periodOneTangentReadout
#print axioms GameTheory.QuittingCounterexampleSeamWitness.CounterexampleRegimePeriodOneTangentReadout.activePositive_refusalGain
#print axioms GameTheory.quittingPeriodOne_attachedNever_sub_initial_eq
#print axioms GameTheory.QuittingCounterexampleSeamWitness.CounterexampleRegimePeriodOneTangentReadout.actualAttachmentNever_sub_initial_eq
#print axioms GameTheory.QuittingCounterexampleSeamWitness.CounterexampleRegimePeriodOneTangentReadout.activePositive_actualAttachmentNever_profitable
#print axioms GameTheory.terminalExploitabilityGap_le_behavioralTailRepairValue
#print axioms GameTheory.exists_elementaryTailCap_terminalExploitability_gt_sub
#print axioms GameTheory.QuittingCounterexampleSeamWitness.CounterexampleRegimePeriodOneTangentReadout.terminalGap_le_periodOne_behavioralTailRepairValue
#print axioms GameTheory.QuittingCounterexampleRegime.terminalGap_le_repairValue_le_minAggregate
#print axioms GameTheory.QuittingCounterexampleRegime.exists_aggregateAnchor_terminalGap_le_packetCharge
#print axioms GameTheory.QuittingCounterexampleRegime.elementaryCap_consumed_by_minAggregateDrop_or_reachableCharge
#print axioms GameTheory.QuittingCounterexampleRegime.immediateNever_terminalExploitability_eq_maxDynamicDebt
#print axioms GameTheory.QuittingCounterexampleRegime.immediateNever_consumed_of_prependResidual_le_charge
#print axioms GameTheory.QuittingCounterexampleRegime.prependResidual_le_jointContinue_mul_anchorDebt_add_charge
#print axioms GameTheory.QuittingCounterexampleRegime.immediateNever_consumed_of_carriedDebt_le_charge
#print axioms GameTheory.QuittingDynamicDebtCapChargedAnchorCounterexample.no_universal_currentDebt_sum_le_mul_nash_absorption
#print axioms GameTheory.QuittingReachableDynamicDebtChronology.source_add_aggregateCapacityAccount_succ_le
#print axioms GameTheory.QuittingReachableDynamicDebtChronology.debt_le_aggregateCapacityAccount_of_boundary
#print axioms GameTheory.quittingPunishmentFloor_le_reachableState
#print axioms GameTheory.aggregateCalibratedAnchor_initial_not_reachable_of_lt_punishmentFloor
#print axioms GameTheory.QuittingReachableDynamicDebtChronology.debt_le_aggregateCapacityAccount_add_boundary
#print axioms GameTheory.quittingPunishmentValue_le_finiteDynamicDebtPoint_of_nonpos
#print axioms GameTheory.isQuittingPunishmentFloorReachable_finiteDynamicDebtPoint_of_terminal
#print axioms GameTheory.QuittingFiniteDynamicDebtAdmissibleChronology.debt_zero_le_aggregateCapacityAccount_zero_of_far
#print axioms GameTheory.aggregateCalibratedAnchor_initialDebt_le_admissibleCapacity_of_far
#print axioms GameTheory.QuittingFiniteDynamicDebtAdmissibleChronology.debt_cutoff_eq_sum_positiveSingletonDebtCap
#print axioms GameTheory.QuittingFiniteDynamicDebtAdmissibleChronology.debt_zero_le_aggregateCapacityAccount_zero_of_incomingPath
#print axioms GameTheory.aggregateCalibratedAnchor_initialDebt_le_admissibleCapacity_of_terminalCap_eq_zero
#print axioms GameTheory.QuittingNonpositiveFloorTerminalCapRegression.not_terminalCap_eq_zero_of_punishmentValue_nonpos
#print axioms GameTheory.QuittingFiniteDynamicDebtAdmissibleChronology.strict_terminalDebt_fundingEdge_or_farkas
#print axioms GameTheory.QuittingFiniteDynamicDebtAdmissibleChronology.saturated_terminalDebt_no_pureSingleton_incomingEdge
#print axioms GameTheory.sum_positiveSingletonDebtCap_le_quittingRewardBound
#print axioms GameTheory.QuittingAggregateCalibratedTerminalAnchor.zeroFace_zero_or_one_or_initialCapacitySlack_or_farkas
#print axioms GameTheory.exists_finitePrefix_source_forbids_incoming_charge
#print axioms GameTheory.exists_nearMaximal_positiveDebt_chargeTimeCompactEdge
#print axioms GameTheory.allContinue_dynamicDebtEdge_ignores_successorRoot
#print axioms GameTheory.QuittingAggregateCalibratedTerminalAnchor.exists_canonicalOwnerFundingFarkas
#print axioms GameTheory.exists_negativeCollision_of_positiveSingleton_zeroTargetLift
#print axioms GameTheory.QuittingChargeTangentPacket.not_exists_zeroTargetLift_on_compatible_twoOwnerPacketSupport
#print axioms GameTheory.QuittingCollisionAwareFiniteReturn.isSolvedExactQuittingCycle
#print axioms GameTheory.QuittingCounterexampleRegime.not_nonempty_collisionAwareFiniteReturn
#print axioms GameTheory.QuittingDebtSourceFaceReturnWord.isSolvedExactQuittingCycle
#print axioms GameTheory.QuittingCounterexampleSeamWitness.not_hasQuittingDebtSourceFaceReturnWord
#print axioms GameTheory.QuittingStrictSupportedPreferenceLasso.faceCirculation_mixWeight_ne_packetMass
#print axioms GameTheory.QuittingChargeTangentPacket.twoOwnerCommonWordRepairValue_eq_zero_iff
#print axioms GameTheory.QuittingChargeTangentPacket.not_twoOwnerCommonWordRepairValue_eq_zero
#print axioms GameTheory.quittingTailConditionedValue_step
#print axioms GameTheory.abs_quittingTailConditionedValue_sub_singleton_le_weight
#print axioms GameTheory.exists_conditionedSingletonProductRoot_step
#print axioms GameTheory.no_conditionedProductPurification_of_two_active_phantom
#print axioms GameTheory.isUniformEquilibriumPayoff_of_nashBellmanSingletonCycle
#print axioms GameTheory.QuittingCounterexampleRegime.chargeTangentData_underfunded_or_active_funded
#print axioms GameTheory.QuittingChargeTangentPacket.exists_supported_outsider_pos_soloEffect
#print axioms GameTheory.QuittingChargeTangentPacket.exists_supported_pair_pos_reciprocalSoloEffect
#print axioms GameTheory.QuittingChargeTangentPacket.anchoredProjectiveLCPDirection_eq
#print axioms GameTheory.QuittingChargeTangentPacket.anchoredProjectiveLCPDirection_neg
#print axioms GameTheory.QuittingChargeTangentPacket.activePairCompatibilityResidual_eq_sum_pairJoinEffect
#print axioms GameTheory.QuittingChargeTangentPacket.exists_supported_pair_neg_reciprocalCollisionIncrement
#print axioms GameTheory.quittingActiveCompatibilitySignFunctional_pairing_pos_iff
#print axioms GameTheory.QuittingChargeTangentPacket.activeMixingCompatibility_or_signedPivot
#print axioms GameTheory.t_mul_quittingBellmanBlowupResidual
#print axioms GameTheory.t_mul_quittingMixingBlowupResidual
#print axioms GameTheory.QuittingChargeTangentPacket.supportBlowupResidual_basePoint_eq_zero
#print axioms GameTheory.isNashBellmanRoot_of_supportBlowupResidual_eq_zero
#print axioms GameTheory.QuittingChargeTangentPacket.hasPositiveRadialAnalyticArcAt_of_regular_supportBlowup
#print axioms GameTheory.QuittingChargeTangentPacket.not_surjective_and_positiveRadialKernel_of_compatible
#print axioms GameTheory.quittingFinThree_augmentedSurjective_xor_outward
#print axioms GameTheory.QuittingChargeTangentPacket.mem_image_projectiveGauge_zeroSet_iff
#print axioms GameTheory.QuittingChargeTangentPacket.hasPositiveRadialAnalyticArcAt_of_regular_projectiveGauge
#print axioms GameTheory.quittingMixingBlowupResidual_eq_zero_iff_omittedDefect_eq_zero
#print axioms GameTheory.QuittingChargeTangentPacket.deletedMixingRegressionPoint_mixing_eq_scale_mul_pairJoinRow
#print axioms GameTheory.QuittingChargeTangentPacket.deletedMixingRegressionPoint_omittedDefect_fixedSign
#print axioms GameTheory.quittingFinThree_defect_fixedSign_of_radialMinor_ne_zero
#print axioms GameTheory.QuittingChargeTangentPacket.finThreeRowTwoJoinDefect_secondJet
#print axioms GameTheory.QuittingChargeTangentPacket.finThreeRowTwoJoinDefect_fixedSign_of_quadratic_ne_zero
#print axioms GameTheory.QuittingChargeTangentPacket.finThreeRowTwoJoinDefect_eq_zero_of_coefficients_eq_zero
#print axioms GameTheory.quittingTwoOwnerSupportJacobian_det
#print axioms GameTheory.quittingMixingFirstOrderResidual_twoOwner_eq_mulVec
#print axioms GameTheory.QuittingChargeTangentPacket.twoOwnerSupportJacobian_eq_zero_of_compatible
#print axioms GameTheory.QuittingChargeTangentPacket.twoOwner_singular_and_reciprocalSoloEffect_pos_of_compatible_collision_neg
#print axioms GameTheory.twoOwnerBellmanContinuation_activeExact
#print axioms GameTheory.twoOwnerBellmanContinuation_active_formula
#print axioms GameTheory.isQuittingNashBellmanEdge_twoOwner_of_pairJoin_zero
#print axioms GameTheory.QuittingChargeTangentPacket.twoOwnerBellmanContinuationAt_active_formula
#print axioms GameTheory.QuittingChargeTangentPacket.not_floor_le_twoOwnerBellmanContinuationAt_first_of_tangent_pos
#print axioms GameTheory.QuittingChargeTangentPacket.isQuittingNashBellmanEdge_twoOwnerAt
#print axioms GameTheory.QuittingChargeTangentPacket.positiveChargeExactEdge_or_tightPhysicalGate
#print axioms GameTheory.QuittingChargeTangentPacket.positiveChargeExactEdge_or_positiveTightOutsiderJet
#print axioms GameTheory.QuittingChargeTangentPacket.punishmentFloor_obstructs_twoOwnerRay_of_tangent_pos
#print axioms GameTheory.quittingStationaryPunishment_attained_of_uniform_add_error
#print axioms GameTheory.QuittingChargeTangentPacket.eventually_exists_targetClosedTail_of_tightPunishment
#print axioms GameTheory.quittingFrozenRootContinuationLift_or_farkas
#print axioms GameTheory.quittingFrozenRootNashBellmanEdge_or_farkas
#print axioms GameTheory.QuittingChargeTangentPacket.frozenRootContinuationLift_or_farkas
#print axioms GameTheory.QuittingCounterexampleSeamWitness.killedDebtReference_eq_killedTailAccount
#print axioms GameTheory.QuittingCounterexampleSeamWitness.debtBoundary_le_potentialBoundary_iff_dissipationSum_eq_zero
#print axioms GameTheory.QuittingCounterexampleSeamWitness.potentialBoundary_lt_debtBoundary_of_strictDissipation
#print axioms GameTheory.QuittingCounterexampleSeamWitness.killedCapacityDebtAccount_isKilledExcessive
#print axioms GameTheory.QuittingCounterexampleSeamWitness.killedCapacityInitialMismatch_eq_zero_iff
#print axioms GameTheory.QuittingFiniteRootWindow.toSurvivalBlock_concat
#print axioms GameTheory.QuittingFiniteRootWindow.absorptionMass_mul_normalizedEndpointTangent_concat
#print axioms GameTheory.QuittingFiniteRootWindow.toObstructionRawGradedFlow_concat
#print axioms GameTheory.QuittingFiniteRootWindow.pair_toObstructionRawGradedFlow_concat
#print axioms GameTheory.quittingOneStageObstructionCarrier_isCompact
#print axioms GameTheory.QuittingCounterexampleSeamWitness.exists_hasSupportValue_oneStageObstructionCarrier
#print axioms GameTheory.quittingDebtSourceOneStageObstructionCarrier_isCompact
#print axioms GameTheory.quittingDebtSourceObstructionFold_eq_debt_sub_surviving
#print axioms GameTheory.QuittingCounterexampleSeamWitness.mem_exposedFace_quittingDebtSourceZeroFaceCostate_iff
#print axioms GameTheory.QuittingCounterexampleSeamWitness.debtSourceFlow_mem_all_zeroFaces_iff_cap_transport
#print axioms GameTheory.QuittingCounterexampleSeamWitness.debt_eq_survivalLimit_mul_limit_add_tsum_pair_tailDebtSource
#print axioms GameTheory.QuittingCounterexampleSeamWitness.zeroFace_or_succ_zeroFace_or_capacityDissipation_pos
#print axioms GameTheory.QuittingCounterexampleSeamWitness.zeroFace_recurrence_of_eventual_boundaryMismatch_le
#print axioms GameTheory.projectiveTerminalEscapeDebt_step
#print axioms GameTheory.MetrizableMarkedAbsorptionCompletion.exists_finite_subsequence_with_anchor_repairState_limit
#print axioms GameTheory.QuittingCounterexampleSeamWitness.summable_killedCapacityDissipation
#print axioms GameTheory.QuittingCounterexampleSeamWitness.boundaryMismatch_one_sub_initialMismatch_tendsto_zero
#print axioms GameTheory.floor_le_quittingTailConditionedValue_of_boundary_eq_floor
#print axioms GameTheory.quittingConditionedAffineShrink_survival_mul_complement
#print axioms GameTheory.QuittingCounterexampleSeamWitness.conditionedTail_floor_or_strictPlateauSlack
#print axioms GameTheory.exists_conditionedSingletonProductRoot_step_isEndpointNash_of_tightBoundary
#print axioms GameTheory.exists_conditionedSingletonProductRoot_path_with_opponentSurvivalObstruction
#print axioms GameTheory.soloReward_owner_neg_of_noUniform_of_atomicSoloLimit
#print axioms GameTheory.isUniformEquilibriumPayoff_soloReward_of_endpointNash_of_punishmentIR
#print axioms GameTheory.QuittingCounterexampleRegime.terminalGap_le_neg_soloReward_of_soloEndpointNash
#print axioms GameTheory.QuittingCounterexampleRegime.not_atomicSoloLimit_of_punishment_le_tightBoundary
#print axioms GameTheory.QuittingCounterexampleSeamWitness.not_atomicSoloLimit_of_limitValue_eq_singleton
#print axioms GameTheory.quittingTailConditionedCollisionWeight_le_mesh_sq
#print axioms GameTheory.abs_conditionedOpponentWeight_sub_rescaledRoot_opponentAbsorption_le
#print axioms GameTheory.quittingTailDiffuse_deletedContinuation_rescaling_identity
#print axioms GameTheory.tendsto_zero_opponentSurvivalWeight_quittingTailDiffuseRescaledRoots
#print axioms GameTheory.abs_rescaledQuitValue_sub_conditionedValue_le_six_mul_opponent
#print axioms GameTheory.quittingSoloBaseline_le_sourceValue_add_opponentAbsorption
#print axioms GameTheory.quittingSoloBaseline_le_conditionedValue_add_opponentWeight
#print axioms GameTheory.quittingStationaryFixedOpponentsQuitValue_rescaledRoot_le_conditionedValue_add_of_nash
#print axioms GameTheory.tendsto_quittingTailEventualAbsorption_zero_of_summable_absorption
#print axioms GameTheory.QuittingInfinitePathJointPolicySeparatedErrorCertificate.isεAsymptoticNash_and_approximates
#print axioms GameTheory.conditionedDiffuseRescaledRoots_isεAsymptoticNash_and_approximates
#print axioms GameTheory.QuittingConditionedDiffuseCertificate.isεAsymptoticNash_and_approximates
#print axioms GameTheory.quittingGame_exists_uniformEquilibriumPayoff_of_arbitrarilyFineConditionedDiffuseCertificates
#print axioms GameTheory.quittingGame_exists_uniformEquilibriumPayoff_of_conditionedDiffuseCertificates
#print axioms GameTheory.quittingGame_exists_uniformEquilibriumPayoff_of_conditionedDiffuseTail
#print axioms GameTheory.quittingGame_uniformPayoff_or_exists_summable_conditionedOpponentWeight
#print axioms Math.not_summable_of_tendsto_prod_one_sub_zero
#print axioms Math.tendsto_prod_one_sub_zero_of_not_summable
#print axioms GameTheory.conditionedDeletedClock_ownerMonopoly
#print axioms GameTheory.conditionedDeletedClock_terminalConcentration
#print axioms GameTheory.isUniformEquilibriumPayoff_soloReward_of_deletedQuitLimits
#print axioms GameTheory.isUniformEquilibriumPayoff_soloReward_of_summableConditionedDeletedClock
#print axioms GameTheory.quittingGame_exists_uniformEquilibriumPayoff_of_conditionedDiffuseTail_punishmentIR
#print axioms GameTheory.QuittingCounterexampleSeamWitness.not_all_limitValue_eq_singleton_of_diffuse
#print axioms GameTheory.QuittingCounterexampleSeamWitness.exists_singleton_lt_limitValue_of_diffuse
#print axioms GameTheory.QuittingCounterexampleSeamWitness.eventually_pureContinue_of_singleton_lt_limitValue
#print axioms GameTheory.QuittingCounterexampleSeamWitness.eventually_active_implies_limitValue_eq_singleton
#print axioms GameTheory.QuittingCounterexampleSeamWitness.exists_strictPlateau_eventually_pureContinue_of_diffuse
#print axioms GameTheory.value_le_sum_charge_add_product_tail
#print axioms GameTheory.tendsto_quittingTailConditionedValue_solo_of_summableOpponentWeight
#print axioms GameTheory.isUniformEquilibriumPayoff_soloReward_of_soloFloor_of_punishmentIR
#print axioms GameTheory.isUniformEquilibriumPayoff_solo_of_summableClock_and_vanishingQuitDefect
#print axioms GameTheory.QuittingCounterexampleSeamWitness.not_tendsto_rescaledQuitDefect_of_diffuse
#print axioms GameTheory.QuittingCounterexampleSeamWitness.exists_persistent_rescaledQuitDefect_of_diffuse
#print axioms GameTheory.quittingRootEndpointDifference_update_ownMarginal
#print axioms GameTheory.quitProbability_eq_one_of_supportEndpointApproxNash_of_tolerance_lt
#print axioms GameTheory.ownMarginal_repair_is_sureQuit_of_supportEndpointApproxNash
#print axioms GameTheory.QuittingCounterexampleSeamWitness.exists_fixed_inactive_rescaledQuitDefect_of_diffuse
#print axioms GameTheory.QuittingCounterexampleSeamWitness.exists_cofinal_fixed_inactive_rescaledEndpointGap_of_diffuse
#print axioms GameTheory.QuittingCounterexampleSeamWitness.exists_cofinal_endpoint_reset_or_fixed_underfloor_slack
#print axioms GameTheory.exists_isZeroQuittingRootEndpointNash_simplex_with_positive_absorption_of_singleton_gap
#print axioms GameTheory.QuittingCounterexampleSeamWitness.exists_cofinal_fixedOutsider_positiveAbsorptionReset_of_diffuse
#print axioms GameTheory.QuittingCounterexampleSeamWitness.exists_cofinal_floorAdmissible_positiveAbsorptionReset_or_fundedUnderfloor
#print axioms GameTheory.exists_pos_gap_quittingPunishmentFloorClip_le_singleton_sub
#print axioms GameTheory.singletonReward_neg_or_punishmentValue_eq_of_singleton_le
#print axioms GameTheory.QuittingCounterexampleSeamWitness.exists_fixedOutsider_punishment_ge_singleton_or_cofinal_floorClippedReset
#print axioms GameTheory.QuittingCounterexampleSeamWitness.exists_positiveSolo_owner_and_scalar_diffuse_alternative
#print axioms GameTheory.quittingRootExpectedPayoff_update_ownMarginal_sub
#print axioms GameTheory.quittingRootExpectedPayoff_update_ownMarginal_ge_pureContinue_add_gap_sub
#print axioms GameTheory.conditionedDiffuse_ownMarginalEndpointRepair_ge_jointCharge_shift
#print axioms GameTheory.abs_quittingOutsiderJoiningContribution_le_two_mul_absorptionMass
#print axioms GameTheory.gap_div_le_quittingRootAbsorptionMass_of_isZeroEndpointNash
#print axioms GameTheory.abs_quittingRootEndpointDifference_sub_le_tail
#print axioms GameTheory.isεQuittingRootEndpointNash_of_tail_close
#print axioms GameTheory.isδQuittingRootSuccessorCertificate_of_target_close
#print axioms GameTheory.ClippedStateMatchingObstruction.no_composable_positive_absorption_clipped_edges
#print axioms GameTheory.isεAsymptoticNash_quittingRootThenContinuation_of_target_close
#print axioms GameTheory.isεAsymptoticNash_quittingRootThenContinuation_of_endpointNash_target_close
#print axioms GameTheory.conditionalAbsorbingDelivery_sub_value_eq_conditionedGap_add_phantomGap
#print axioms GameTheory.conditionedGap_neg_or_strictPhantomFunding_of_tangent_neg
#print axioms GameTheory.QuittingCounterexampleSeamWitness.CounterexampleRegimePeriodOneTangentReadout.conditionedGap_neg_or_strictPhantomFunding
#print axioms GameTheory.QuittingCounterexampleSeamWitness.CounterexampleRegimePeriodOneTangentReadout.tendsto_phaseGain_of_mass_pos_of_tangent_neg
#print axioms GameTheory.quittingConditionedAffineShrink_initialScale_eq_one_of_finiteReturn
#print axioms GameTheory.conditionedGap_neg_or_conditionedFloorViolation_or_tangentFunding
#print axioms GameTheory.QuittingChargeTangentData.punishmentValue_le_singletonMixture_iff_neg_tangent_le_slack
#print axioms GameTheory.QuittingCounterexampleSeamWitness.CounterexampleRegimePeriodOneTangentReadout.neg_tangent_le_punishmentSlack_or_eventually_phaseGain_and_underfloor
#print axioms GameTheory.quittingDynamicDebtPoint_eq_successor_of_two_allContinue
#print axioms GameTheory.QuittingCounterexampleSeamWitness.tail_eq_limitDebtPoint_of_eventually_allContinue
#print axioms GameTheory.QuittingCounterexampleSeamWitness.exists_exact_late_phantomSemantics_of_eventually_allContinue
#print axioms GameTheory.QuittingCounterexampleSeamWitness.terminalGap_le_limitDebt_le_soloReward_le_limitValue
#print axioms GameTheory.QuittingCounterexampleSeamWitness.limitOwner_endpointNash_requires_second_quitter
#print axioms GameTheory.QuittingCounterexampleSeamWitness.limitOwner_exists_universalJoiner_or_switchingPair
#print axioms GameTheory.exists_isεAsymptoticNash_close_of_punishmentAdmissibleCycle_rootError
#print axioms GameTheory.isUniformEquilibriumPayoff_soloReward_of_approximate_caps
#print axioms GameTheory.isUniformEquilibriumPayoff_soloReward_of_approximate_endpointNash
#print axioms GameTheory.isUniformEquilibriumPayoff_of_approximate_punishmentAdmissibleCycles

-- Support-witness relaxed compiler and its all-errors uniform-payoff capstone.
#print axioms GameTheory.exists_isεAsymptoticNash_of_divergentAbsorption_supportRationalPath
#print axioms GameTheory.exists_isThreeEpsilonAsymptoticNash_of_divergentAbsorption_supportRationalPath
#print axioms GameTheory.quittingGame_exists_uniformEquilibriumPayoff_of_supportRationalDivergentPaths

-- Solved exact-cycle strata and finite global reward-shift exactification.
#print axioms GameTheory.isUniformEquilibriumPayoff_of_isSolvedExactQuittingCycle
#print axioms GameTheory.HasSolvedExactQuittingCycle.exists_uniformEquilibriumPayoff
#print axioms GameTheory.exists_rewardNeighborhood_without_solvedExactQuittingCycle
#print axioms GameTheory.QuittingCounterexampleRegime.exists_solvedExactCycleExclusionRadius
#print axioms GameTheory.quittingPeriodOneBestPhaseStop_sub_restartDelivery_eq_tangent
#print axioms GameTheory.quittingPeriodOneRefusalValue_sub_restartDelivery_eq_tangent
#print axioms GameTheory.quittingPeriodOne_slacks_nonneg_of_step_nash
#print axioms GameTheory.quittingPeriodOne_refusalSlack_eq_zero_of_continueProbability_pos
#print axioms GameTheory.quittingPeriodOne_fullSingletonMass_boundary
#print axioms GameTheory.ownShiftExactificationSystem_iff
#print axioms GameTheory.eq_canonicalOwnShiftCycleCorrection_of_feedback_of_absorbing
#print axioms GameTheory.correction_eq_multiplier_mul_of_feedback_of_absorbing
#print axioms GameTheory.one_sub_ownShiftCycleFeedbackMultiplier_eq_continue_mul_gapSlope
#print axioms GameTheory.ownShiftCycleGapSlope_mem_unitInterval_of_absorbing
#print axioms GameTheory.exists_ownShiftExactificationSystem_iff_reduced_of_absorbing
#print axioms GameTheory.exists_ownShiftReducedExactificationSystem_iff_forall_exists_scalar
#print axioms GameTheory.ownShiftSolvedCycleExactificationSystem_iff

-- Stopping-law accounting, cyclic exposure, and phase-occupation duality.
-- These checks live here rather than in production modules so ordinary builds
-- remain quiet while the repository audit retains the same proof-hygiene
-- coverage.
#print axioms GameTheory.quittingHazardStoppingLaw_expect
#print axioms Math.Probability.DiscreteHazard.ScalarHazard.stoppingLaw_expect
#print axioms Math.Probability.DiscreteHazard.ScalarHazard.neverMass_eq_zero_of_tendsto_sum_atTop
#print axioms Math.CyclicExposure.Neighbours.exists_exposure_le_quarter
#print axioms Math.CyclicExposure.Neighbours.forall_quarter_le_exposure_iff_eq_fair
#print axioms Math.Probability.PhaseOccupationDuality.hasPointwisePhaseShiftFlow_iff_hasPhaseShiftFlow
#print axioms Math.Probability.PhaseOccupationDuality.phaseAverageReward_le_phaseSlack
#print axioms Math.Probability.PhaseOccupationDuality.minPrimalFeasible_of_isPhaseOccupation
#print axioms Math.Probability.PhaseOccupationDuality.compiled_lp_attains_and_has_dual

-- Coupled phase-switch accounting and punishment-completed instant/cyclic
-- mechanisms.
#print axioms GameTheory.quittingRootSequenceHazardTerminalValue_quittingPhaseSwitchRoots_le_coupled
#print axioms GameTheory.quittingInstantPunishmentWorks_iff
#print axioms GameTheory.isUniformEquilibriumPayoff_soloReward_of_instantPunishment
#print axioms GameTheory.isUniformEquilibriumPayoff_of_punishmentAdmissibleCycle
