import FixedPointTheorems.brouwer
import FixedPointTheorems.kakutani
import GameTheory
import UniformEquilibrium
import Math.Probability.PhaseOccupationDuality
import Math.Probability.WeightedCollisionConcentration
import Math.PMFProduct.CollisionMass
import Math.SchauderFixedPoint
import UniformEquilibrium.Quitting.Classification.SingletonPacketDefectAlgebra
import UniformEquilibrium.Quitting.Classification.SingletonPacketEnergy
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimePacketEnergy
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeBallisticity
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeBoundaryProvenanceAlternative
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeExactCycleStrata
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeDebtSourceObstructionCarrier
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeDebtSourceDynamicAlternative
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeKilledCapacityPotential
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeKilledTailPotential
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeOneStageObstructionCarrier
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimePeriodOneAttachmentRepair
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimePeriodOneTangentReadout
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeTangentPacket
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeTangentAnchoredProjectiveLCP
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeTangentPacketEnergy
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeTangentSupportLiftFarkas
import UniformEquilibrium.Quitting.AbsorptionPath.CollisionConcentration
import UniformEquilibrium.Quitting.AbsorptionPath.NormalizedFiniteWindowOccupation
import UniformEquilibrium.Quitting.AbsorptionPath.FiniteWindowRefusalReweighting
import UniformEquilibrium.Quitting.AbsorptionPath.FlowCostateObstructionAdapter
import UniformEquilibrium.Quitting.AbsorptionPath.SurvivalWeightedObstructionAdapter
import UniformEquilibrium.Quitting.Bellman.Finite.BooleanMobiusAdapter
import UniformEquilibrium.Quitting.Cycles.PhantomBoundaryLimitGeometry
import UniformEquilibrium.Quitting.Cycles.OwnShiftCycleExactification
import UniformEquilibrium.Quitting.Cycles.PeriodOneTangentAtlas
import UniformEquilibrium.Quitting.Paths.OutsiderNeverGluing
import UniformEquilibrium.Quitting.Terminal.TailCompression.SummableTailBestResponse

-- Fixed-point infrastructure used by existence theorems.
#print axioms brouwer_fixed_point
#print axioms brouwer_fixed_point_isFixedPt
#print axioms brouwer_fixedPoints_nonempty
#print axioms kakutani_fixed_point
#print axioms Math.Schauder.schauder_fixed_point
#print axioms Math.Schauder.schauder_fixed_point_isFixedPt
#print axioms Math.Schauder.schauder_fixedPoints_nonempty

-- README headline theorem packages.
#print axioms GameTheory.KernelGame.mixed_nash_exists
#print axioms GameTheory.KernelGame.correlatedEq_exists
#print axioms GameTheory.KernelGame.coarseCorrelatedEq_exists
#print axioms EFG.zermelo
#print axioms EFG.oneShotDeviation_iff_spe
#print axioms GameTheory.KernelGame.von_neumann_minimax
#print axioms ObsModel.kuhn_behavioral_to_mixed
#print axioms ObsModel.kuhn_mixed_to_behavioral_semantic
#print axioms ObsModelCore.kuhn_behavioral_to_mixed
#print axioms ObsModelCore.kuhn_mixed_to_behavioral_semantic
#print axioms GameTheory.arrow_impossibility_exact
#print axioms GameTheory.SCF.gibbard_satterthwaite
#print axioms GameTheory.May.may_theorem
#print axioms GameTheory.GeneralMechanism.revelation_principle
#print axioms GameTheory.SocialChoice.FairDivision.Divisible.stromquist_envyFree_exists
#print axioms GameTheory.SocialChoice.FairDivision.Divisible.MeasureInstance.envyFree_exists
#print axioms GameTheory.CoalGame.shapleyValue_unique
#print axioms GameTheory.VNM.exists_representsExpectedUtility_of_vnmAxioms
#print axioms GameTheory.VNM.vnmAxioms_iff_exists_representsExpectedUtility

-- Repeated games and online learning.
#print axioms GameTheory.KernelGame.discounted_folk_theorem_approx
#print axioms Math.OnlineLearning.mw_externalRegret_le
#print axioms GameTheory.KernelGame.timeAverage_isεCCE_of_regret_le
#print axioms Math.Approachability.blackwell_approaches
#print axioms Math.Approachability.regretMatch_approaches

-- Auction and mechanism-design headline results.
#print axioms GameTheory.VCGSetup.vcg_truthful
#print axioms GameTheory.vickrey_truthful_dominant
#print axioms GameTheory.ReserveVickrey.mechanism_isDSIC
#print axioms GameTheory.KnapsackAuction.welfareMaximizingMechanism_isDSIC
#print axioms GameTheory.SingleParameterMechanism.existsUnique_zeroNormalized_payment_of_isMonotone

-- Social choice, matching, and cooperative games.
#print axioms GameTheory.sen_paretian_liberal
#print axioms GameTheory.median_is_condorcet_winner
#print axioms GameTheory.MatchingMarket.exists_stable
#print axioms GameTheory.MatchingMarket.OptionalOrder.lattice
#print axioms GameTheory.CoalGame.IsCore.isBalanced
#print axioms GameTheory.CoalGame.costOfStability_eq_zero_iff_core
#print axioms GameTheory.CoalGame.banzhafIndex_additive
#print axioms GameTheory.CoalGame.shapleyShubikIndex_sum_eq_one

-- Indivisible fair division and correlation saturation.
#print axioms GameTheory.SocialChoice.FairDivision.Indivisible.roundRobinAllocation_isEF1
#print axioms GameTheory.SocialChoice.FairDivision.Indivisible.exists_efx_two_agents
#print axioms GameTheory.KernelGame.strictDominant_isCoarseCorrelationSaturated
#print axioms GameTheory.KernelGame.IsIESDSSolvable.isCorrelationSaturated

-- ============================================================================
-- Uniform-equilibrium / quitting-game program: headline landed declarations.
-- The two intentional open declarations (`GameTheory.quittingGame_exists_
-- uniformEquilibriumPayoff` and `GameTheory.exists_uniformDeviationCapConstructor`)
-- are deliberately excluded: they carry `sorry` and are expected to report it.
-- ============================================================================

-- Terminal-to-uniform selection and the asymptotic-Nash bridge.
#print axioms GameTheory.StochasticGame.isUniformεEquilibrium_of_isεAsymptoticNash_of_upperApproximation
#print axioms GameTheory.quittingGame_exists_uniformEquilibriumPayoff_of_terminalNash_all_errors
#print axioms GameTheory.quittingGame_exists_uniformEquilibriumPayoff_iff_terminalNash_all_errors

-- The admissible-cycle compiler and the three-branch trichotomy.
#print axioms GameTheory.exists_uniformEquilibriumPayoff_of_admissible_quittingCyclicContinuationBlock
#print axioms GameTheory.exists_uniformEquilibriumPayoff_of_zeroSolo_or_admissibleCycle
#print axioms GameTheory.quittingCycle_zeroSolo_or_admissible_or_isolatedNegative
#print axioms GameTheory.QuittingDisjunctionCounterexample.not_zeroSolo_and_not_admissible_and_isolatedNegative
#print axioms GameTheory.quittingThreeBranch_not_mutually_exclusive

-- The low-dimensional closures of the quitting conjecture.
#print axioms GameTheory.QuittingTwoPlayerExistence.quittingGame_exists_uniformEquilibriumPayoff_twoPlayer
#print axioms GameTheory.QuittingTwoPlayerExistence.quittingGame_isUniformEquilibriumPayoff_jointExit
#print axioms GameTheory.quittingGame_exists_uniformEquilibriumPayoff_threePlayer

-- The sure-exit-set characterization at every number of players: a pure
-- exit profile is an exact terminal equilibrium exactly when no player
-- gains by toggling its own membership in the exit set.
#print axioms GameTheory.isεAsymptoticNash_pureSetRoot_iff
#print axioms GameTheory.isεAsymptoticNash_pureSetRoot_iff_isQuittingSureExitSet
#print axioms GameTheory.isUniformEquilibriumPayoff_setReward_of_isQuittingSureExitSet
#print axioms GameTheory.isεAsymptoticNash_pureSetRoot_univ_iff

-- The exact dynamic-debt transport law and the seam-price results.
#print axioms GameTheory.quittingFiniteDynamicDebt_eq_max_zero_sub_accumulatedStageGaps
#print axioms GameTheory.quittingDynamicDebtTail_conservation
#print axioms GameTheory.QuittingCounterexampleSeamWitness.debt_eq_survivalLimit_mul_limit_add_tsum_weightedSeam
#print axioms GameTheory.QuittingCounterexampleSeamWitness.ownerSemanticGap_tendsto_limitValue
#print axioms GameTheory.QuittingCounterexampleSeamWitness.tailDynamicDebtCap_mem_and_floor
#print axioms GameTheory.QuittingCounterexampleSeamWitness.canonicalPeriodicTailWindow_eventuallyPayoffBlocked
#print axioms GameTheory.QuittingCounterexampleRegime.exists_pos_uniform_normalizedSingletonPacketRefusal
#print axioms GameTheory.punishmentFloorPrefixChargeCapacity_eq_top_of_coalitionLock
#print axioms GameTheory.QuittingCounterexampleRegime.not_isQuittingSureExitSet_of_nonempty_via_prefixCapacity
#print axioms GameTheory.quitting_sub_blockFixedPoint_eq_div
#print axioms GameTheory.QuittingSeamPriceDeviationFalsity.seamPriceLaw_fails_for_deviation_via_fullDeficit

-- The sequential marked-path completion and its correlated closed splice
-- relations.
#print axioms GameTheory.MetrizableMarkedAbsorptionCompletion.exists_finite_sequence_tendsto
#print axioms GameTheory.MetrizableMarkedAbsorptionCompletion.surjective_maximalToMetrizable
#print axioms GameTheory.MetrizableMarkedAbsorptionCompletion.exists_exactSeam_sequence_tendsto
#print axioms GameTheory.MetrizableMarkedAbsorptionCompletion.associativityWitness_common_result
#print axioms GameTheory.chronology_holonomy_coordinates_mem_box
#print axioms GameTheory.MetrizableMarkedAbsorptionCompletion.metrizableBoundaryHolonomy_completeMetrizable
#print axioms GameTheory.MetrizableMarkedAbsorptionCompletion.continuous_metrizableBehavioralTailRepairValue
#print axioms GameTheory.MetrizableMarkedAbsorptionCompletion.exists_finite_subsequence_with_repairState_limit

-- Punishment level and individual rationality.
#print axioms GameTheory.StochasticGame.punishmentLevel_le_add_of_isUniformEquilibriumPayoff
#print axioms GameTheory.StochasticGame.not_isUniformEquilibriumPayoff_of_punishmentLevel_gt
#print axioms GameTheory.StochasticGame.eventually_isεIndividuallyRational_of_isUniformEquilibriumPayoff
#print axioms GameTheory.punishmentLevel_quittingGame_le_max

-- The action-legality chain, including the disintegration payoff equality.
#print axioms GameTheory.StochasticGame.finiteAveragePayoff_devPrime_eq
#print axioms GameTheory.StochasticGame.isLegalUniformEquilibriumPayoff_of_witness

-- The `PMF Bool` / real-hazard encoding bridge.
#print axioms GameTheory.isExactRowComplementary_hazardOfRoot_iff

-- The perturbed-cyclic-weight exclusion and the row dichotomy it restates.
#print axioms GameTheory.atMostOnePositive_of_isεQuittingRootEndpointNash_cyclicWeightReward
#print axioms GameTheory.atMostOnePositive_of_isExactRowComplementary

-- Joint complementarity, absorption-from-optimality, and coordinate silence.
#print axioms GameTheory.isQuittingJointComplementary_quittingCyclicBlockRoots
#print axioms GameTheory.isCompletelyAbsorbing_of_isQuittingJointComplementary_of_solo_pos
#print axioms GameTheory.QuittingCandidateHardWeightCoordinateSilence.quitProbability_true_eq_zero_of_isQuittingJointComplementary

-- Backward stability of root ε-complementarity (E64, period-one base case)
-- and the lens-identity's first leg: the condition number is the
-- weighted-to-unweighted conversion factor.
#print axioms GameTheory.exists_exact_of_isεQuittingRootEndpointNash
#print axioms GameTheory.exists_exact_of_pure
#print axioms GameTheory.abs_le_div_min_of_weighted_bounds
#print axioms GameTheory.abs_quittingRootEndpointDifference_le_div_min_of_isεQuittingRootEndpointNash
#print axioms GameTheory.exists_exact_ownShift_abs_eq_abs_quittingRootEndpointDifference
#print axioms GameTheory.min_lt_inv_of_exists_weighted_bound_not_isεRowComplementary

-- The weighted continue-mass bound and its scaled-cyclic-weight absence package.
#print axioms GameTheory.exists_pos_le_continueMass
#print axioms GameTheory.hasNoInstantApproxEquilibria_scaledCyclicWeight

-- The two-coordinate circulation boundary: the headline closed form.
#print axioms GameTheory.QuittingCirculationTwoCoordinateBoundary.circulationTwoExists_iff

-- The repaired four-player stress-point orbit and the general multi-owner
-- face-circulation orbit theorem.
#print axioms GameTheory.RepairedFourPlayerStress.exists_stressCirculation_orbit
#print axioms GameTheory.exists_multiCirculation_orbit

-- The one-sided decision-variation maximal inequality and the quitting
-- live-chain domination cap.
#print axioms Math.Probability.expect_indicator_scoreRunningMax_le_div
#print axioms GameTheory.quittingTerminalPayoff_update_quittingPhaseSwitchProfile_le_of_quitRegret_le

-- The pinned-pure row decoupling exclusion.
#print axioms GameTheory.not_isExactRowComplementary_cyclicWeight_of_pinned

-- The two-blocker interval cover, its non-exclusivity fence, the corrected
-- solo-quitter gate, and the three-player table refuting the single-blocker
-- designation.
#print axioms GameTheory.exists_switchingPair_of_forall_not_isUniversalRateBlocker
#print axioms GameTheory.exists_universalRateBlocker_or_switchingPair
#print axioms GameTheory.exists_family_isUniversalRateBlocker_and_switchingPair
#print axioms GameTheory.isUniversalRateBlocker_quittingJoiningGain_iff
#print axioms GameTheory.exists_soloQuitterRate_or_universalJoiner_or_switchingPair
#print axioms GameTheory.exists_soloQuitterRate_or_universalJoiner_of_card_le_two
#print axioms GameTheory.QuittingSwitchingBlockerTable.not_exists_universalJoiner

-- The bounded survival-window landing, the truncation fold, and the surviving
-- gap-free conditional compiler.  The former universal package producer is
-- refuted by the two-player theorem audited below and no longer exists.
#print axioms GameTheory.exists_pos_ratio_forall_exists_jointSurvivalWeight_mem_survivalWindow
#print axioms GameTheory.quittingRootSequenceHazardTerminalValue_quittingTruncatedRoots_le_of_plan_ledger_le
#print axioms GameTheory.quittingTerminalPayoff_update_quittingPhaseSwitchProfile_le_of_plan_ledger_le
#print axioms GameTheory.quittingGame_exists_uniformEquilibriumPayoff_of_hasQuittingLedgerCapPackage
#print axioms GameTheory.quittingGame_exists_uniformEquilibriumPayoff_of_truncatedLedgerCapPackage
#print axioms GameTheory.QuittingTruncatedLedgerCapCounterexample.not_hasQuittingTruncatedLedgerCapPackage_half
#print axioms GameTheory.exists_uniformEquilibriumPayoff_of_zeroSolo_or_truncatedLedgerCapProducer

-- ============================================================================
-- The three-player switching-residue regression table (pure arithmetic;
-- no stochastic-game dynamics) and its two general scalar lemmas.
-- ============================================================================

#print axioms GameTheory.QuittingSwitchingResidueRegression.q_one_pos
#print axioms GameTheory.QuittingSwitchingResidueRegression.max_d12_d13_ge
#print axioms GameTheory.QuittingSwitchingResidueRegression.d12_le_zero
#print axioms GameTheory.QuittingSwitchingResidueRegression.d13_le_zero
#print axioms GameTheory.QuittingSwitchingResidueRegression.d21_eq_one
#print axioms GameTheory.QuittingSwitchingResidueRegression.d31_eq_one
#print axioms GameTheory.QuittingSwitchingResidueRegression.sureExitFails_1
#print axioms GameTheory.QuittingSwitchingResidueRegression.sureExitFails_2
#print axioms GameTheory.QuittingSwitchingResidueRegression.sureExitFails_3
#print axioms GameTheory.QuittingSwitchingResidueRegression.sureExitFails_12
#print axioms GameTheory.QuittingSwitchingResidueRegression.sureExitFails_13
#print axioms GameTheory.QuittingSwitchingResidueRegression.sureExitFails_23
#print axioms GameTheory.QuittingSwitchingResidueRegression.sureExitFails_123
#print axioms GameTheory.QuittingSwitchingResidueRegression.collisionRepairFails12
#print axioms GameTheory.QuittingSwitchingResidueRegression.collisionRepairFails13
#print axioms GameTheory.QuittingSwitchingResidueRegression.collisionRepairFails21
#print axioms GameTheory.QuittingSwitchingResidueRegression.collisionRepairFails23
#print axioms GameTheory.QuittingSwitchingResidueRegression.collisionRepairFails31
#print axioms GameTheory.QuittingSwitchingResidueRegression.collisionRepairFails32
#print axioms GameTheory.QuittingSwitchingResidueRegression.collisionRate_ge_of_balance_nonneg
#print axioms GameTheory.QuittingSwitchingResidueRegression.not_balance_nonneg_of_gain_nonpos
#print axioms GameTheory.QuittingSwitchingResidueRegression.fixedGap_ge_half

-- ============================================================================
-- The game-layer bridge: the switching-residue regression table has no sure
-- exit set at all.
-- ============================================================================

#print axioms GameTheory.QuittingSwitchingResidueRegressionBridge.quittingSetReward_gameReward
#print axioms GameTheory.QuittingSwitchingResidueRegressionBridge.not_isQuittingSureExitSet_of_sureExitFails
#print axioms GameTheory.QuittingSwitchingResidueRegressionBridge.not_isQuittingSureExitSet_gameReward

-- The stationary endpoint compiler and the two exact solutions of the
-- switching-residue table.
#print axioms GameTheory.isZeroAsymptoticNash_stationary_iff_endpointNash_and_boundary
#print axioms GameTheory.isUniformEquilibriumPayoff_of_stationaryEndpointCertificate
#print axioms GameTheory.QuittingSwitchingResidueExactRoot.noSureExitSet_but_two_distinct_stationary_uniformPayoffs

-- The parametric witness that escapes the four local mechanisms while
-- retaining an exact stationary equilibrium.
#print axioms GameTheory.QuittingLocalMechanismResidueWitness.isLocalMechanismResidue_four
#print axioms GameTheory.QuittingLocalMechanismResidueWitness.isExactTerminalNash_doubleSureMixerProfile
#print axioms GameTheory.QuittingLocalMechanismResidueWitness.exists_uniformEquilibriumPayoff_four

-- Shared punishment: zero combination price for two players, versus the
-- exact positive price and optimizer classification on the cyclic
-- three-player table.
#print axioms GameTheory.quittingTwoPlayerSharedPunishmentExcess_eq_zero
#print axioms GameTheory.QuittingSharedThreePlayer.quittingSharedPunishmentExcess_eq_three_quarters
#print axioms GameTheory.QuittingSharedThreePlayer.quittingSharedPunishmentGap_eq_three_quarters_iff_first_eq_fair
#print axioms GameTheory.QuittingSharedThreePlayerDice.quittingBestReplyValue_eq_alwaysContinue

-- The quitting min-max is a stationary stopping value: the punishment
-- value, an infimum over all history-dependent opponent plans of the
-- supremum over all replies, is computed by constant opponent rows.
#print axioms GameTheory.quittingBestReplyValue_stationary
#print axioms GameTheory.quittingPunishmentValue_le_stationaryPunishmentValue
#print axioms GameTheory.quittingStationaryPunishmentValue_le_quittingPunishmentValue
#print axioms GameTheory.quittingPunishmentValue_eq_stationaryPunishmentValue
#print axioms GameTheory.quittingStationaryPunishmentValue_le_of_forall_hazard_le
#print axioms GameTheory.quittingRootSequenceHazardTerminalValue_const_le_cap
#print axioms GameTheory.quittingPunishmentValue_le_max_solo
#print axioms GameTheory.QuittingHostileTwoCoordinate.quittingPunishmentValue_eq
#print axioms GameTheory.QuittingProfitableSoloTwoCoordinate.quittingPunishmentValue_lt_max_solo

-- Diagonal target-tail assembly: player-indexed closed tails, exact
-- arbitrary-endpoint prefixes, exceptional-target selection, and the
-- resulting conditional uniform-payoff and counterexample restrictions.
#print axioms GameTheory.exists_quittingTargetClosedTail_of_stationaryRoot
#print axioms GameTheory.exists_finiteEndpointExactQuittingNashBellmanChain
#print axioms GameTheory.quittingPhaseSwitchHazardGap_le_four_mul_opponentSurvival
#print axioms GameTheory.exists_target_forall_opponentSurvivalWeight_le_of_joint_le_sq
#print axioms GameTheory.quittingGame_exists_uniformEquilibriumPayoff_of_exactDiagonalTargetTailCertificates
#print axioms GameTheory.exists_exactDiagonalTargetTailCertificate_errorFloor_of_no_uniformPayoff

-- Essential APS on the executable singleton-flow stratum: exact successor
-- extraction, algebraic greatest fixed family, zero-mass boundary, and the
-- supplied finite proper-cycle compiler.
#print axioms GameTheory.quittingFleschSuccessor_of_consecutive_arcs
#print axioms GameTheory.quittingEssentialAPSGreatestFamily_fixed
#print axioms GameTheory.quittingEssentialAPS_zeroMassFixedPoint_regression
#print axioms GameTheory.QuittingEssentialAPSCycleCertificate.opponentContracts
#print axioms GameTheory.QuittingEssentialAPSCycleCertificate.isUniformEquilibriumPayoff

-- Path budgets and bounded potentials.
#print axioms Math.ChargedPathBudget.ChargedRelation.hasFiniteBudget_iff_exists_boundedPotential
#print axioms Math.ChargedPathBudget.ChargedRelation.isLeast_oscillation
#print axioms Math.ChargedPathBudget.ChargedRelation.budgetEN_eq_iInf_oscillation
#print axioms Math.ChargedPathBudget.ChargedRelation.isLeast_value
#print axioms Math.ChargedPathBudget.ChargedRelation.not_exists_boundedPotential_of_positive_selfLoop
#print axioms Math.ChargedPathBudget.Towers.not_hasFiniteBudget
#print axioms Math.ChargedPathBudget.Interpolation.budget_eq_one
#print axioms Math.ChargedPathBudget.Interpolation.not_continuous_of_isPotential
#print axioms Math.ChargedPathBudget.QuitBonus.oneStageUpdate_fixed
#print axioms Math.ChargedPathBudget.QuitBonus.no_boundedPotential

-- The one-stage collision repair works iff owner endpoint optimality,
-- spectator no-join, and the blocker-floor balance against the exact
-- min-max all hold; sub-floor gaps force the collision intensity.
#print axioms GameTheory.quittingCollisionRepairWorks_iff
#print axioms GameTheory.quittingCollisionRepairWorks_one_iff
#print axioms GameTheory.quittingCollisionOwnerCap_le_of_isεAsymptoticNash
#print axioms GameTheory.quittingCollisionSpectatorJoin_le_of_isεAsymptoticNash
#print axioms GameTheory.quittingCollisionBlockerFloor_le_of_isεAsymptoticNash
#print axioms GameTheory.isεAsymptoticNash_quittingCollisionRepairProfile
#print axioms GameTheory.quittingTerminalPayoff_update_oneStagePunishedProfile_le
#print axioms GameTheory.quittingRootSequenceHazardTerminalValue_zero_split
#print axioms GameTheory.quittingCollisionRate_ge_of_blockerBalance
#print axioms GameTheory.quittingCollisionBlockerGain_ge_of_subFloor
#print axioms GameTheory.not_quittingCollisionRepairWorks_of_subFloor_of_rate_lt
#print axioms GameTheory.quittingCollisionOwnerOptimal_iff_of_mem_Ioo

-- The repo's canonical one-stage operator realizes the quit-bonus
-- calibration self-loop exactly; no bounded potential exists for it.
#print axioms GameTheory.QuittingQuitBonusSelfLoopBridge.oneStageNext_reward_isSelfLoop
#print axioms GameTheory.QuittingQuitBonusSelfLoopBridge.no_boundedPotential

-- Matching-order projective extraction, affine/Farkas boundary, and the
-- rotation-uniform weighted-lasso compiler.
#print axioms GameTheory.QuittingGermMatchingLeadingData.nonsingletonFirstEventWeight_tendsto_zero
#print axioms GameTheory.QuittingGermMatchingLeadingData.toProjectiveSingletonPacket
#print axioms GameTheory.QuittingProjectiveTargetMismatch.germ_matchingOrder
#print axioms GameTheory.QuittingProjectiveTargetMismatch.one_sub_le_four_mul_add_of_terminalNash_close
#print axioms GameTheory.QuittingProjectiveTargetMismatch.packet_value_not_isUniformEquilibriumPayoff
#print axioms GameTheory.QuittingProjectiveTargetMismatch.germ_endpointValue_not_isUniformEquilibriumPayoff
#print axioms GameTheory.QuittingProjectiveTargetMismatch.firstExitValue_isUniformEquilibriumPayoff
#print axioms GameTheory.QuittingProjectiveTargetMismatch.secondExitValue_isUniformEquilibriumPayoff
#print axioms Math.LinearAlgebra.affineEqualityInequality_feasible_or_farkas
#print axioms GameTheory.quittingGame_exists_uniformEquilibriumPayoff_of_weightedProjectiveLassos

-- The punishment-floor predecessor producer and its selected-orbit
-- charge alternative.
#print axioms GameTheory.quittingPunishmentValue_le_rootSuccessorPayoff_of_tail_ge
#print axioms GameTheory.quittingGame_exists_uniformEquilibriumPayoff_of_punishmentFloorForwardCharge
#print axioms GameTheory.quittingGame_uniformPayoff_or_punishmentFloorForwardChargeBound
#print axioms GameTheory.quittingPunishmentValue_le_finitePrefixValue
#print axioms GameTheory.quittingGame_exists_uniformPayoff_of_arbitrarilyCharged_floorPrefixes
#print axioms GameTheory.quittingGame_uniformPayoff_or_bounded_floorPrefixCharge
#print axioms Math.ChargedPathBudget.ChargedRelation.DivergentSelection.exists_normalizedPath
#print axioms Math.ChargedPathBudget.ChargedRelation.chargeRenewal_iff_unboundedFiniteCharge_implies_canDiverge
#print axioms Math.ChargedPathBudget.ChargedRelation.exists_path_eq_finiteHorizonMaxCharge
#print axioms Math.ChargedPathBudget.ChargedRelation.hasUnboundedFiniteCharge_iff_hasUnboundedHorizonCharge
#print axioms Math.ChargedPathBudget.ChargedRelation.OneStepTower.unboundedFiniteCharge_and_not_canDiverge
#print axioms Math.ChargedPathBudget.ChargedRelation.DelayedPositiveLoop.firstUnitBlock_length
#print axioms Math.ChargedPathBudget.ChargedRelation.GreedyTrap.greedy_target_not_canDiverge
#print axioms Math.ChargedPathBudget.ChargedRelation.IncompatibleHorizonOptima.horizon_three_investment_optimum
#print axioms GameTheory.QuittingPunishmentFloorBoxPath.toFinitePrefix_charge
#print axioms GameTheory.quittingGame_uniformPayoff_or_punishmentFloorReachable_hasFiniteBudget
#print axioms GameTheory.quittingGame_uniformPayoff_or_punishmentFloorReachable_canonicalPotential
#print axioms GameTheory.quittingPunishmentFloorSelected_potential_decrement
#print axioms GameTheory.not_exists_uniformEquilibriumPayoff_iff_nonempty_counterexampleRegime
#print axioms GameTheory.not_exists_uniformEquilibriumPayoff_iff_exists_gap_and_finiteChargeCapacity
#print axioms GameTheory.punishmentFloorPrefixChargeCapacity_ne_top_iff
#print axioms GameTheory.terminalExploitabilityGap_le_finiteMinMaxDynamicDebt
#print axioms GameTheory.QuittingCounterexampleRegime.reachable_cycle_chargeSum_eq_zero
#print axioms GameTheory.QuittingCounterexampleRegime.exists_terminalGapDynamicDebtTail
#print axioms GameTheory.QuittingCounterexampleRegime.infiniteOrbit_absorptionMass_summable
#print axioms GameTheory.QuittingCounterexampleRegime.eventually_smallAbsorption_and_terminalExploitability
#print axioms GameTheory.QuittingCounterexampleRegime.exists_terminalGapDynamicDebtTail_with_summableAbsorption_of_nonpos
#print axioms GameTheory.quittingGame_exists_uniformPayoff_of_positive_reachable_return

-- Regime narrowing: toggle/stationary instability, small-player emptiness,
-- orbit value limits, the floor-violation collapse, and the analytic waist
-- with its forced packet.
#print axioms GameTheory.QuittingCounterexampleRegime.exists_toggle_gain
#print axioms GameTheory.QuittingCounterexampleRegime.exists_leave_or_join_gain
#print axioms GameTheory.QuittingCounterexampleRegime.not_isQuittingSureExitSet
#print axioms GameTheory.QuittingCounterexampleRegime.exists_terminalGap_le_soloReward
#print axioms GameTheory.QuittingCounterexampleRegime.exists_collision_gain
#print axioms GameTheory.QuittingCounterexampleRegime.one_lt_card
#print axioms GameTheory.QuittingCounterexampleRegime.exists_stationaryCap_gain
#print axioms GameTheory.quittingGame_exists_uniformEquilibriumPayoff_onePlayer
#print axioms GameTheory.QuittingCounterexampleRegime.elim_isEmpty
#print axioms GameTheory.QuittingCounterexampleRegime.elim_unique
#print axioms GameTheory.QuittingCounterexampleRegime.elim_twoPlayer
#print axioms GameTheory.QuittingCounterexampleRegime.elim_threePlayer
#print axioms GameTheory.QuittingCounterexampleRegime.infiniteOrbit_exists_value_limit
#print axioms GameTheory.quittingPunishmentValue_sub_le_continueMass_mul_of_nashBellmanEdge
#print axioms GameTheory.quittingDynamicDebtTail_floorViolation_mono
#print axioms GameTheory.summable_dynamicDebtTailAbsorptionCharge_of_floorViolation_of_positiveDebt
#print axioms GameTheory.QuittingCounterexampleRegime.exists_terminalGapDynamicDebtTail_summableAbsorption
#print axioms GameTheory.quittingGame_uniformPayoff_or_normalizedSingletonSourcePacket
#print axioms GameTheory.QuittingCounterexampleRegime.nonempty_normalizedSingletonSourcePacket
#print axioms GameTheory.quittingDynamicDebtCap_eq_rootSuccessorPayoff_add_seam
#print axioms GameTheory.QuittingCounterexampleRegime.exists_terminalGapDynamicDebtTail_selfLoopLimit
#print axioms GameTheory.QuittingCounterexampleRegime.exists_active_strictSingletonRefusal
#print axioms GameTheory.QuittingNormalizedSingletonSourcePacket.refusal_sub_mixture_eq_mass_div_mul_surplus
#print axioms GameTheory.QuittingCounterexampleRegime.exists_cyclicWindow_pureTimeCap_gap
#print axioms GameTheory.QuittingCounterexampleRegime.nonempty_seamWitness
#print axioms GameTheory.QuittingCounterexampleRegime.infiniteOrbit_tsum_abs_value_succ_sub_le
#print axioms GameTheory.QuittingCounterexampleRegime.infiniteOrbit_exists_selfLoop_limit
#print axioms GameTheory.quittingGame_exists_uniformEquilibriumPayoff_of_reindex
#print axioms GameTheory.quittingGame_exists_uniformEquilibriumPayoff_of_card_eq_two
#print axioms GameTheory.quittingGame_exists_uniformEquilibriumPayoff_of_card_eq_three
#print axioms GameTheory.QuittingCounterexampleRegime.three_lt_card

-- Canonical finite counterexamples, finite instability screens, packet support,
-- quantitative floor clocks, and the cap/restart semantic seams.
#print axioms GameTheory.isUniformEquilibriumPayoff_reindex_iff
#print axioms GameTheory.nonempty_counterexampleRegime_reindex_fin_iff
#print axioms GameTheory.exists_minimalFinQuittingCounterexample
#print axioms GameTheory.MinimalFinQuittingCounterexample.properRestriction_exists_uniformEquilibriumPayoff
#print axioms GameTheory.QuittingCounterexampleRegime.terminalGap_le_pureToggleCeiling
#print axioms GameTheory.QuittingCounterexampleRegime.exists_closedImprovementWalk_multiple_four
#print axioms GameTheory.QuittingCounterexampleRegime.terminalGap_le_stationaryCapCeiling
#print axioms GameTheory.QuittingNormalizedSingletonSourcePacket.exists_weakPreferenceClosedOrbit
#print axioms GameTheory.QuittingCounterexampleRegime.exists_supportedSingleton_terminalGap
#print axioms GameTheory.FourPlayerSingletonBlocker.exists_pos_uniform_escapeSeparation
#print axioms Math.Probability.DiscreteHazard.ScalarHazard.gap_le_survival_mul
#print axioms Math.Probability.DiscreteHazard.ScalarHazard.gap_div_bound_le_survival
#print axioms Math.Probability.DiscreteHazard.ScalarHazard.gap_mul_sum_stop_le_bound
#print axioms Math.Probability.DiscreteHazard.ScalarHazard.gap_mul_tsum_stop_natAdd_le_bound
#print axioms Math.Probability.DiscreteHazard.ScalarHazard.summable_stop_of_survivalAmplification
#print axioms GameTheory.quittingPunishmentGapTail_amplify
#print axioms GameTheory.quittingPunishmentGap_mul_partialOpponentClock_le
#print axioms GameTheory.quittingPunishmentGap_mul_tsum_opponentClock_le
#print axioms GameTheory.quittingPunishmentFloorAdmissiblePotential_predecessor_decrement
#print axioms GameTheory.QuittingCapSeededPrefix.terminalGap_le_jointSurvivalWeight_mul_capBound
#print axioms GameTheory.QuittingCapSeededPrefix.sum_absorptionMass_le_log_capBound_div_terminalGap
#print axioms GameTheory.QuittingDynamicDebtCapChargedAnchorCounterexample.absorptionCharge_eq_zero_of_nash_at_augmentedCap
#print axioms GameTheory.quittingDynamicDebtCap_transport_iff_capSeam_eq_zero
#print axioms GameTheory.isQuittingNashBellmanEdge_dynamicDebtCapPoint_of_capSeam_eq_zero
#print axioms GameTheory.quittingOpponentSurvivalWeight_eq_one_of_returningDynamicDebt
#print axioms GameTheory.quittingDynamicDebtTailRoots_eq_allContinue_of_two_returningDynamicDebt
#print axioms GameTheory.eq_of_two_returningDynamicDebt_of_jointSurvival_lt_one
#print axioms GameTheory.quittingPrescribedValue_eq_terminalValue_add_survivalLimit_mul
#print axioms GameTheory.sSup_range_quittingTerminalPayoff_update_eq_periodicWindow
#print axioms GameTheory.quittingPeriodicWindowRefusalValue_sub_restartDelivery_eq_normalizedSeam
#print axioms GameTheory.quittingPeriodicWindowBestResponseValue_sub_terminalValue_le_normalizedDrift_of_exactNash
#print axioms GameTheory.QuittingCounterexampleRegime.exists_cyclicWindow_finiteEvaluation_gap
#print axioms GameTheory.QuittingPeriodicWindowFamily.lateRepairable_or_eventuallyPayoffBlocked
#print axioms GameTheory.abs_quittingRootSequenceBestResponseValue_sub_maxSolo_le_totalCharge_of_lt_one
#print axioms GameTheory.exists_quittingAnnotationBoundary_of_summableAbsorption
#print axioms GameTheory.quittingAnnotationBoundary_eq_singleton_of_activeSubsequence
#print axioms GameTheory.phaseUnderfunded_or_refusalFloorMissing
#print axioms GameTheory.quittingPacketWeightedSurplus_eq_quadraticForm
#print axioms GameTheory.quittingSingletonPacketSkewEnergy_eq_zero
#print axioms GameTheory.exists_uniformEquilibriumPayoff_of_pairwise_reciprocalSolo_nonpos
#print axioms GameTheory.quittingPacketWeightedRefusal_eq_quadraticForm
#print axioms GameTheory.QuittingCounterexampleRegime.exists_supported_pair_pos_reciprocalSoloEffect
#print axioms Math.Probability.finiteWeightedCollisionConcentration_or_zero
#print axioms Math.Probability.abs_conditionalPayoff_sub_singletonMixture_le
#print axioms Math.PMFProduct.collisionMass_le_choose_card_mul_absorption_sq
#print axioms GameTheory.finiteQuittingRootCollisionConcentration_or_zero
#print axioms GameTheory.abs_finiteQuittingRootConditionalPayoff_sub_singletonMixture_le
#print axioms GameTheory.QuittingFiniteRootWindow.zero_or_positive_normalizedMass
#print axioms GameTheory.QuittingFiniteRootWindow.tendsto_normalizedCollisionMass_zero
#print axioms GameTheory.QuittingFiniteRootWindow.tendsto_normalizedCollisionMass_zero_of_start_tendsto
#print axioms GameTheory.QuittingFiniteRootWindow.abs_delivery_sub_absorptionSingletonMixture_le
#print axioms GameTheory.QuittingFiniteRootWindow.abs_absorbingDelivery_sub_singletonMixture_le_of_cap
#print axioms GameTheory.QuittingFiniteRootWindow.quittingAnnotationBoundary_eq_singleton_of_normalizedWindowOccupation
#print axioms GameTheory.QuittingFiniteRootWindow.abs_normalized_forceContinue_sub_jointOff_le_of_lowerBound
#print axioms GameTheory.quittingRootExpectedPayoff_eq_continuation_add_multilinearValue
#print axioms GameTheory.quittingRootEndpointDifference_eq_mobiusCoordinateDerivative
#print axioms GameTheory.CoalGame.coordinateDerivative_eq_singleton_add_pair_add_higherOrder
#print axioms GameTheory.quittingRootEndpointDifference_eq_mobiusCardinalitySplit
#print axioms GameTheory.quittingRootEndpointDifference_eq_outsiderNever
#print axioms GameTheory.quittingRootSequencePureTimeTerminalValue_some_sub_none_eq
#print axioms GameTheory.quittingTerminalPayoff_update_le_never_add
#print axioms Math.ChargedPathBudget.ChargedRelation.hasChronologicalExecution_of_reachable_progress
#print axioms GameTheory.quittingEssentialAPSCarrier_terminalPath_or_infiniteRun_of_segmentClosed
#print axioms GameTheory.EssentialAPSOccupationCancellationRegression.global_balance_does_not_supply_chronological_cancellation
#print axioms GameTheory.QuittingCounterexampleSeamWitness.punishmentValue_le_tailValue
#print axioms GameTheory.QuittingCounterexampleSeamWitness.tailSegmentPunishmentFloorPrefix_charge
#print axioms GameTheory.QuittingCounterexampleSeamWitness.not_exists_sublinearAbsorptionReturn
#print axioms GameTheory.QuittingCounterexampleSeamWitness.exists_pos_eventually_endpointDistance_ge_absorptionMass
#print axioms GameTheory.QuittingCounterexampleSeamWitness.eventually_allContinue_or_exists_chargeTangentPacket
#print axioms GameTheory.QuittingCounterexampleSeamWitness.eventually_allContinue_or_exists_oneStage_chargeTangentPacket
#print axioms GameTheory.QuittingCounterexampleSeamWitness.eventually_allContinue_or_exists_periodOneTangentReadout
#print axioms GameTheory.CounterexampleRegimePeriodOneTangentReadout.activePositive_refusalGain
#print axioms GameTheory.quittingPeriodOne_attachedNever_sub_initial_eq
#print axioms GameTheory.CounterexampleRegimePeriodOneTangentReadout.actualAttachmentNever_sub_initial_eq
#print axioms GameTheory.CounterexampleRegimePeriodOneTangentReadout.activePositive_actualAttachmentNever_profitable
#print axioms GameTheory.terminalExploitabilityGap_le_behavioralTailRepairValue
#print axioms GameTheory.exists_elementaryTailCap_terminalExploitability_gt_sub
#print axioms GameTheory.QuittingCounterexampleSeamWitness.CounterexampleRegimePeriodOneTangentReadout.terminalGap_le_periodOne_behavioralTailRepairValue
#print axioms GameTheory.QuittingCounterexampleRegime.chargeTangentData_underfunded_or_active_funded
#print axioms GameTheory.QuittingChargeTangentPacket.exists_supported_outsider_pos_soloEffect
#print axioms GameTheory.QuittingChargeTangentPacket.exists_supported_pair_pos_reciprocalSoloEffect
#print axioms GameTheory.QuittingChargeTangentPacket.anchoredProjectiveLCPDirection_eq
#print axioms GameTheory.QuittingChargeTangentPacket.anchoredProjectiveLCPDirection_neg
#print axioms GameTheory.quittingFrozenRootContinuationLift_or_farkas
#print axioms GameTheory.quittingFrozenRootNashBellmanEdge_or_farkas
#print axioms GameTheory.QuittingChargeTangentPacket.frozenRootContinuationLift_or_farkas
#print axioms GameTheory.QuittingCounterexampleSeamWitness.killedDebtReference_eq_killedTailAccount
#print axioms GameTheory.QuittingCounterexampleSeamWitness.debtBoundary_le_potentialBoundary_iff_dissipationSum_eq_zero
#print axioms GameTheory.QuittingCounterexampleSeamWitness.potentialBoundary_lt_debtBoundary_of_strictDissipation
#print axioms GameTheory.QuittingCounterexampleSeamWitness.killedCapacityDebtAccount_isKilledExcessive
#print axioms GameTheory.QuittingCounterexampleSeamWitness.killedCapacityInitialMismatch_eq_zero_iff
#print axioms GameTheory.QuittingFiniteRootWindow.toSurvivalBlock_concat
#print axioms GameTheory.QuittingFiniteRootWindow.absorptionMass_mul_normalizedEndpointTangent_concat
#print axioms GameTheory.QuittingFiniteRootWindow.toObstructionRawGradedFlow_concat
#print axioms GameTheory.QuittingFiniteRootWindow.pair_toObstructionRawGradedFlow_concat
#print axioms GameTheory.quittingOneStageObstructionCarrier_isCompact
#print axioms GameTheory.QuittingCounterexampleSeamWitness.exists_hasSupportValue_oneStageObstructionCarrier
#print axioms GameTheory.quittingDebtSourceOneStageObstructionCarrier_isCompact
#print axioms GameTheory.quittingDebtSourceObstructionFold_eq_debt_sub_surviving
#print axioms GameTheory.QuittingCounterexampleSeamWitness.mem_exposedFace_quittingDebtSourceZeroFaceCostate_iff
#print axioms GameTheory.QuittingCounterexampleSeamWitness.debtSourceFlow_mem_all_zeroFaces_iff_cap_transport
#print axioms GameTheory.QuittingCounterexampleSeamWitness.debt_eq_survivalLimit_mul_limit_add_tsum_pair_tailDebtSource
#print axioms GameTheory.QuittingCounterexampleSeamWitness.zeroFace_or_succ_zeroFace_or_capacityDissipation_pos
#print axioms GameTheory.QuittingCounterexampleSeamWitness.zeroFace_recurrence_of_eventual_boundaryMismatch_le
#print axioms GameTheory.projectiveTerminalEscapeDebt_step
#print axioms GameTheory.MetrizableMarkedAbsorptionCompletion.exists_finite_subsequence_with_anchor_repairState_limit
#print axioms GameTheory.QuittingCounterexampleSeamWitness.summable_killedCapacityDissipation
#print axioms GameTheory.QuittingCounterexampleSeamWitness.boundaryMismatch_one_sub_initialMismatch_tendsto_zero

-- Solved exact-cycle strata and finite global reward-shift exactification.
#print axioms GameTheory.isUniformEquilibriumPayoff_of_isSolvedExactQuittingCycle
#print axioms GameTheory.HasSolvedExactQuittingCycle.exists_uniformEquilibriumPayoff
#print axioms GameTheory.exists_rewardNeighborhood_without_solvedExactQuittingCycle
#print axioms GameTheory.QuittingCounterexampleRegime.exists_solvedExactCycleExclusionRadius
#print axioms GameTheory.quittingPeriodOneBestPhaseStop_sub_restartDelivery_eq_tangent
#print axioms GameTheory.quittingPeriodOneRefusalValue_sub_restartDelivery_eq_tangent
#print axioms GameTheory.quittingPeriodOne_slacks_nonneg_of_step_nash
#print axioms GameTheory.quittingPeriodOne_refusalSlack_eq_zero_of_continueProbability_pos
#print axioms GameTheory.quittingPeriodOne_fullSingletonMass_boundary
#print axioms GameTheory.ownShiftExactificationSystem_iff
#print axioms GameTheory.eq_canonicalOwnShiftCycleCorrection_of_feedback_of_absorbing
#print axioms GameTheory.correction_eq_multiplier_mul_of_feedback_of_absorbing
#print axioms GameTheory.one_sub_ownShiftCycleFeedbackMultiplier_eq_continue_mul_gapSlope
#print axioms GameTheory.ownShiftCycleGapSlope_mem_unitInterval_of_absorbing
#print axioms GameTheory.exists_ownShiftExactificationSystem_iff_reduced_of_absorbing
#print axioms GameTheory.exists_ownShiftReducedExactificationSystem_iff_forall_exists_scalar
#print axioms GameTheory.ownShiftSolvedCycleExactificationSystem_iff

-- Stopping-law accounting, cyclic exposure, and phase-occupation duality.
-- These checks live here rather than in production modules so ordinary builds
-- remain quiet while the repository audit retains the same proof-hygiene
-- coverage.
#print axioms GameTheory.quittingHazardStoppingLaw_expect
#print axioms Math.Probability.DiscreteHazard.ScalarHazard.stoppingLaw_expect
#print axioms Math.Probability.DiscreteHazard.ScalarHazard.neverMass_eq_zero_of_tendsto_sum_atTop
#print axioms Math.CyclicExposure.Neighbours.exists_exposure_le_quarter
#print axioms Math.CyclicExposure.Neighbours.forall_quarter_le_exposure_iff_eq_fair
#print axioms Math.Probability.PhaseOccupationDuality.hasPointwisePhaseShiftFlow_iff_hasPhaseShiftFlow
#print axioms Math.Probability.PhaseOccupationDuality.phaseAverageReward_le_phaseSlack
#print axioms Math.Probability.PhaseOccupationDuality.minPrimalFeasible_of_isPhaseOccupation
#print axioms Math.Probability.PhaseOccupationDuality.compiled_lp_attains_and_has_dual

-- Coupled phase-switch accounting and punishment-completed instant/cyclic
-- mechanisms.
#print axioms GameTheory.quittingRootSequenceHazardTerminalValue_quittingPhaseSwitchRoots_le_coupled
#print axioms GameTheory.quittingInstantPunishmentWorks_iff
#print axioms GameTheory.isUniformEquilibriumPayoff_soloReward_of_instantPunishment
#print axioms GameTheory.isUniformEquilibriumPayoff_of_punishmentAdmissibleCycle
