import GameTheory.Languages.FOSG.History

/-!
# GameTheory.Languages.FOSG.Information

Information states and public states for FOSGs.
-/

namespace GameTheory

namespace FOSG

variable {ι W : Type} [DecidableEq ι]
variable {Act : ι → Type} {PrivObs : ι → Type} {PubObs : Type}

/-- Local player-visible events: own actions and resulting observations. -/
inductive PlayerEvent
    (G : FOSG ι W Act PrivObs PubObs) (i : ι) where
  | act : Act i → PlayerEvent G i
  | obs : PrivObs i → PubObs → PlayerEvent G i

namespace PlayerEvent

variable {G : FOSG ι W Act PrivObs PubObs} {i : ι}

/-- Extract the public component carried by an event, if any. -/
def publicPart : PlayerEvent G i → Option PubObs
  | .act _ => none
  | .obs _ o => some o

/-- Extract the player's own action component carried by an event, if any. -/
def actionPart : PlayerEvent G i → Option (Act i)
  | .act a => some a
  | .obs _ _ => none

/-- Extract the full private/public observation component carried by an event,
if any. -/
def observationPart : PlayerEvent G i → Option (PrivObs i × PubObs)
  | .act _ => none
  | .obs oPriv oPub => some (oPriv, oPub)

@[simp] theorem publicPart_act (a : Act i) :
    publicPart (.act a : PlayerEvent G i) = none := rfl

@[simp] theorem publicPart_obs (oPriv : PrivObs i) (oPub : PubObs) :
    publicPart (.obs oPriv oPub : PlayerEvent G i) = some oPub := rfl

@[simp] theorem actionPart_act (a : Act i) :
    actionPart (.act a : PlayerEvent G i) = some a := rfl

@[simp] theorem actionPart_obs (oPriv : PrivObs i) (oPub : PubObs) :
    actionPart (.obs oPriv oPub : PlayerEvent G i) = none := rfl

@[simp] theorem observationPart_act (a : Act i) :
    observationPart (.act a : PlayerEvent G i) = none := rfl

@[simp] theorem observationPart_obs (oPriv : PrivObs i) (oPub : PubObs) :
    observationPart (.obs oPriv oPub : PlayerEvent G i) = some (oPriv, oPub) := rfl

end PlayerEvent

/-- Player information states. -/
abbrev InfoState (G : FOSG ι W Act PrivObs PubObs) (i : ι) : Type :=
  List (PlayerEvent G i)

/-- Public states. -/
abbrev PublicState (_G : FOSG ι W Act PrivObs PubObs) : Type :=
  List PubObs

namespace InfoState

variable {G : FOSG ι W Act PrivObs PubObs} {i : ι}

/-- Last element of a list, as an `Option`. -/
def last? {α : Type} : List α → Option α
  | [] => none
  | [x] => some x
  | _ :: xs => last? xs

@[simp] theorem last?_append_singleton {α : Type} (xs : List α) (x : α) :
    last? (xs ++ [x]) = some x := by
  induction xs with
  | nil => rfl
  | cons y ys ih =>
      cases ys with
      | nil => rfl
      | cons z zs =>
          simpa [last?] using ih

/-- Observation events extracted from a FOSG information state. -/
def observationEvents (s : G.InfoState i) : List (PrivObs i × PubObs) :=
  s.filterMap (PlayerEvent.observationPart (G := G) (i := i))

/-- Latest private/public observation recorded in a FOSG information state. -/
def latestObservation? (s : G.InfoState i) : Option (PrivObs i × PubObs) :=
  last? (observationEvents s)

@[simp] theorem observationEvents_nil :
    observationEvents ([] : G.InfoState i) = [] := rfl

@[simp] theorem latestObservation?_nil :
    latestObservation? ([] : G.InfoState i) = none := rfl

theorem latestObservation?_append_obs
    (s : G.InfoState i) (priv : PrivObs i) (pub : PubObs) :
    latestObservation? (s ++ [PlayerEvent.obs priv pub]) =
      some (priv, pub) := by
  simp [latestObservation?, observationEvents]

theorem latestObservation?_append_act_obs
    (s : G.InfoState i) (a : Act i)
    (priv : PrivObs i) (pub : PubObs) :
    latestObservation? (s ++ [PlayerEvent.act a, PlayerEvent.obs priv pub]) =
      some (priv, pub) := by
  simp [latestObservation?, observationEvents]

end InfoState

namespace Step

variable {G : FOSG ι W Act PrivObs PubObs}

/-- Player `i`'s visible event sequence generated by one realized step. -/
def playerView (e : G.Step) (i : ι) : List (PlayerEvent G i) :=
  match e.ownAction? i with
  | some ai => [.act ai, .obs (e.privateObs i) (e.publicObs)]
  | none => [.obs (e.privateObs i) (e.publicObs)]

@[simp] theorem playerView_of_some
    (e : G.Step) (i : ι) {ai : Act i}
    (h : e.ownAction? i = some ai) :
    e.playerView i = [.act ai, .obs (e.privateObs i) (e.publicObs)] := by
  simp [playerView, h]

@[simp] theorem playerView_of_none
    (e : G.Step) (i : ι)
    (h : e.ownAction? i = none) :
    e.playerView i = [.obs (e.privateObs i) (e.publicObs)] := by
  simp [playerView, h]

theorem filterMap_publicPart_playerView
    (e : G.Step) (i : ι) :
    (e.playerView i).filterMap (PlayerEvent.publicPart (G := G) (i := i)) = [e.publicObs] := by
  unfold playerView
  split <;> simp [PlayerEvent.publicPart]

theorem playerView_length_pos
    (e : G.Step) (i : ι) :
    0 < (e.playerView i).length := by
  unfold playerView
  split <;> simp

theorem latestObservation?_append_playerView
    (s : G.InfoState i) (e : G.Step) :
    InfoState.latestObservation? (s ++ e.playerView i) =
      some (e.privateObs i, e.publicObs) := by
  cases hact : e.ownAction? i with
  | none =>
      rw [Step.playerView_of_none e i hact]
      exact InfoState.latestObservation?_append_obs s
        (e.privateObs i) e.publicObs
  | some ai =>
      rw [Step.playerView_of_some e i hact]
      exact InfoState.latestObservation?_append_act_obs s ai
        (e.privateObs i) e.publicObs

end Step

namespace History

variable {G : FOSG ι W Act PrivObs PubObs}

/-- Public observations induced by a list of realized steps. -/
def publicViewFrom : List G.Step → G.PublicState
  | [] => []
  | e :: es => e.publicObs :: publicViewFrom es

/-- Player `i`'s information state induced by a list of realized steps. -/
def playerViewFrom (i : ι) : List G.Step → G.InfoState i
  | [] => []
  | e :: es => e.playerView i ++ playerViewFrom i es

/-- Public observation history of a realized history. -/
def publicView (h : G.History) : G.PublicState :=
  publicViewFrom h.steps

/-- Player `i`'s information state along a realized history. -/
def playerView (h : G.History) (i : ι) : G.InfoState i :=
  playerViewFrom i h.steps

/-- The sequence of own actions recalled by player `i` along a realized
history. -/
def projectActions (h : G.History) (i : ι) : List (Act i) :=
  (h.playerView i).filterMap (PlayerEvent.actionPart (G := G) (i := i))

/-- The sequence of private/public observations recalled by player `i` along a
realized history. -/
def projectObservations (h : G.History) (i : ι) : List (PrivObs i × PubObs) :=
  (h.playerView i).filterMap (PlayerEvent.observationPart (G := G) (i := i))

theorem publicViewFrom_append_singleton
    (es : List G.Step) (e : G.Step) :
    publicViewFrom (G := G) (es ++ [e]) =
      publicViewFrom (G := G) es ++ [e.publicObs] := by
  induction es with
  | nil =>
      simp [publicViewFrom]
  | cons e₀ es ih =>
      simp [publicViewFrom, ih]

theorem publicViewFrom_append
    (es₁ es₂ : List G.Step) :
    publicViewFrom (G := G) (es₁ ++ es₂) =
      publicViewFrom (G := G) es₁ ++ publicViewFrom (G := G) es₂ := by
  induction es₁ with
  | nil =>
      simp [publicViewFrom]
  | cons e es ih =>
      simp [publicViewFrom, ih]

theorem playerViewFrom_append_singleton
    (i : ι) (es : List G.Step) (e : G.Step) :
    playerViewFrom (G := G) i (es ++ [e]) =
      playerViewFrom (G := G) i es ++ e.playerView i := by
  induction es with
  | nil =>
      simp [playerViewFrom]
  | cons e₀ es ih =>
      simp [playerViewFrom, ih, List.append_assoc]

theorem playerViewFrom_append
    (i : ι) (es₁ es₂ : List G.Step) :
    playerViewFrom (G := G) i (es₁ ++ es₂) =
      playerViewFrom (G := G) i es₁ ++ playerViewFrom (G := G) i es₂ := by
  induction es₁ with
  | nil =>
      simp [playerViewFrom]
  | cons e es ih =>
      simp [playerViewFrom, ih, List.append_assoc]

@[simp] theorem publicView_nil :
    (History.nil G).publicView = [] := rfl

@[simp] theorem playerView_nil (i : ι) :
    (History.nil G).playerView i = [] := rfl

@[simp] theorem publicView_snoc
    (h : G.History) (a : G.LegalAction h.lastState)
    (dst : W) (support : G.transition h.lastState a dst ≠ 0) :
    (h.snoc a dst support).publicView =
      h.publicView ++ [G.pubObs h.lastState a dst] := by
  simpa [History.publicView, History.snoc] using
    publicViewFrom_append_singleton (G := G) h.steps ⟨h.lastState, a, dst, support⟩

@[simp] theorem playerView_snoc
    (h : G.History) (i : ι) (a : G.LegalAction h.lastState)
    (dst : W) (support : G.transition h.lastState a dst ≠ 0) :
    (h.snoc a dst support).playerView i =
      h.playerView i ++ (Step.playerView ⟨h.lastState, a, dst, support⟩ i) := by
  simpa [History.playerView, History.snoc] using
    playerViewFrom_append_singleton (G := G) i h.steps ⟨h.lastState, a, dst, support⟩

theorem latestObservation?_playerView_snoc
    (h : G.History) (i : ι) (a : G.LegalAction h.lastState)
    (dst : W) (support : G.transition h.lastState a dst ≠ 0) :
    InfoState.latestObservation?
        ((h.snoc a dst support).playerView i) =
      some (G.privObs i h.lastState a dst, G.pubObs h.lastState a dst) := by
  rw [History.playerView_snoc]
  exact Step.latestObservation?_append_playerView
    (G := G) (i := i) (h.playerView i)
    ⟨h.lastState, a, dst, support⟩

theorem latestObservation?_playerView_appendStep
    (h : G.History) (i : ι) (e : G.Step)
    (hsrc : e.src = h.lastState) :
    InfoState.latestObservation?
        ((h.appendStep e hsrc).playerView i) =
      some (e.privateObs i, e.publicObs) := by
  rw [History.playerView]
  change InfoState.latestObservation?
      (playerViewFrom (G := G) i (h.steps ++ [e])) =
    some (e.privateObs i, e.publicObs)
  rw [playerViewFrom_append_singleton]
  exact Step.latestObservation?_append_playerView
    (G := G) (i := i) (h.playerView i) e

theorem publicViewFrom_eq_filterMap_playerViewFrom
    (i : ι) (es : List G.Step) :
    publicViewFrom (G := G) es =
      (playerViewFrom (G := G) i es).filterMap (PlayerEvent.publicPart (G := G) (i := i)) := by
  induction es with
  | nil =>
      rfl
  | cons e es ih =>
      simp [publicViewFrom, playerViewFrom, Step.filterMap_publicPart_playerView, ih,
        List.filterMap_append]

theorem publicView_eq_filterMap_playerView
    (h : G.History) (i : ι) :
    h.publicView =
      (h.playerView i).filterMap (PlayerEvent.publicPart (G := G) (i := i)) := by
  simpa [History.publicView, History.playerView] using
    publicViewFrom_eq_filterMap_playerViewFrom (G := G) i h.steps

theorem publicView_eq_of_playerView_eq
    (i : ι) {h h' : G.History}
    (hInfo : h.playerView i = h'.playerView i) :
    h.publicView = h'.publicView := by
  simpa [h.publicView_eq_filterMap_playerView i, h'.publicView_eq_filterMap_playerView i] using
    congrArg (fun xs => xs.filterMap (PlayerEvent.publicPart (G := G) (i := i))) hInfo

theorem projectActions_eq_of_playerView_eq
    (i : ι) {h h' : G.History}
    (hInfo : h.playerView i = h'.playerView i) :
    h.projectActions i = h'.projectActions i := by
  simpa [History.projectActions] using
    congrArg (fun xs => xs.filterMap (PlayerEvent.actionPart (G := G) (i := i))) hInfo

theorem projectObservations_eq_of_playerView_eq
    (i : ι) {h h' : G.History}
    (hInfo : h.playerView i = h'.playerView i) :
    h.projectObservations i = h'.projectObservations i := by
  simpa [History.projectObservations] using
    congrArg (fun xs => xs.filterMap (PlayerEvent.observationPart (G := G) (i := i))) hInfo

theorem playerView_length_snoc
    (h : G.History) (i : ι) (a : G.LegalAction h.lastState)
    (dst : W) (support : G.transition h.lastState a dst ≠ 0) :
    ((h.snoc a dst support).playerView i).length =
      (h.playerView i).length + (Step.playerView ⟨h.lastState, a, dst, support⟩ i).length := by
  simp

theorem playerView_length_lt_snoc
    (h : G.History) (i : ι) (a : G.LegalAction h.lastState)
    (dst : W) (support : G.transition h.lastState a dst ≠ 0) :
    (h.playerView i).length < ((h.snoc a dst support).playerView i).length := by
  rw [playerView_length_snoc]
  exact Nat.lt_add_of_pos_right (Step.playerView_length_pos ⟨h.lastState, a, dst, support⟩ i)

theorem playerView_ne_snoc
    (h : G.History) (i : ι) (a : G.LegalAction h.lastState)
    (dst : W) (support : G.transition h.lastState a dst ≠ 0) :
    h.playerView i ≠ (h.snoc a dst support).playerView i := by
  intro hEq
  have hlt := playerView_length_lt_snoc (G := G) h i a dst support
  have hEqLen : (h.playerView i).length = ((h.snoc a dst support).playerView i).length := by
    exact congrArg List.length hEq
  exact Nat.lt_irrefl _ (hEqLen ▸ hlt)

theorem playerView_eq_append_of_prefix
    {h h' : G.History} (i : ι)
    (hpref : h.IsPrefix h') :
    ∃ es : List G.Step,
      h'.playerView i = h.playerView i ++ playerViewFrom (G := G) i es := by
  rcases hpref with ⟨es, hes⟩
  refine ⟨es, ?_⟩
  rw [History.playerView, History.playerView, hes]
  exact playerViewFrom_append (G := G) i h.steps es

theorem playerView_length_lt_of_properPrefix
    {h h' : G.History} (i : ι)
    (hpref : h.IsPrefix h') (hne : h ≠ h') :
    (h.playerView i).length < (h'.playerView i).length := by
  rcases hpref with ⟨es, hes⟩
  have hneEs : es ≠ [] := by
    intro hnil
    apply hne
    apply History.ext
    simp [hes, hnil]
  cases es with
  | nil =>
      contradiction
  | cons e es' =>
      have hpos : 0 < (e.playerView i).length := Step.playerView_length_pos (G := G) e i
      simp [History.playerView, hes, playerViewFrom_append, playerViewFrom]
      omega

theorem playerView_ne_of_properPrefix
    {h h' : G.History} (i : ι)
    (hpref : h.IsPrefix h') (hne : h ≠ h') :
    h.playerView i ≠ h'.playerView i := by
  intro hEq
  have hlt := playerView_length_lt_of_properPrefix (G := G) i hpref hne
  exact Nat.lt_irrefl _ ((congrArg List.length hEq) ▸ hlt)

/-- Information set fiber for player `i`. -/
def infoSet (i : ι) (s : G.InfoState i) : Set G.History :=
  { h | h.playerView i = s }

/-- Histories at which player `i` is about to act. -/
def IsDecisionHistory (i : ι) (h : G.History) : Prop :=
  i ∈ G.active h.lastState

/-- Paper-style information set for player `i`: matching information state at a
decision point for `i`. -/
def decisionInfoSet (i : ι) (s : G.InfoState i) : Set G.History :=
  { h | h.playerView i = s ∧ IsDecisionHistory (G := G) i h }

/-- Public-set fiber. -/
def publicSet (s : G.PublicState) : Set G.History :=
  { h | h.publicView = s }

theorem mem_publicSet_of_mem_infoSet
    (i : ι) (s : G.InfoState i) {h : G.History}
    (hh : h ∈ infoSet (G := G) i s) :
    h ∈ publicSet (G := G)
      (s.filterMap (PlayerEvent.publicPart (G := G) (i := i))) := by
  change h.publicView = s.filterMap (PlayerEvent.publicPart (G := G) (i := i))
  rw [h.publicView_eq_filterMap_playerView i, hh]

theorem infoSet_subset_publicSet
    (i : ι) (s : G.InfoState i) :
    infoSet (G := G) i s ⊆
      publicSet (G := G) (s.filterMap (PlayerEvent.publicPart (G := G) (i := i))) := by
  intro h hh
  exact mem_publicSet_of_mem_infoSet (G := G) i s hh

theorem decisionInfoSet_subset_infoSet
    (i : ι) (s : G.InfoState i) :
    decisionInfoSet (G := G) i s ⊆ infoSet (G := G) i s := by
  intro h hh
  exact hh.1

theorem mem_decisionInfoSet_iff
    (i : ι) (s : G.InfoState i) (h : G.History) :
    h ∈ decisionInfoSet (G := G) i s ↔
      h.playerView i = s ∧ i ∈ G.active h.lastState := by
  rfl

theorem infoSet_mem_publicSet
    (i : ι) (s : G.InfoState i) {h h' : G.History}
    (hh : h.playerView i = s) (hh' : h'.playerView i = s) :
    h.publicView = h'.publicView := by
  exact publicView_eq_of_playerView_eq (G := G) i (hh.trans hh'.symm)

end History

/-- Observation recall for a FOSG: equal player information states determine
equal recalled observation histories. -/
def ObsRecall (G : FOSG ι W Act PrivObs PubObs) : Prop :=
  ∀ (i : ι) {h h' : G.History},
    h.playerView i = h'.playerView i →
    h.projectObservations i = h'.projectObservations i

/-- Action recall for a FOSG: equal player information states determine equal
recalled own-action histories. -/
def ActionRecall (G : FOSG ι W Act PrivObs PubObs) : Prop :=
  ∀ (i : ι) {h h' : G.History},
    h.playerView i = h'.playerView i →
    h.projectActions i = h'.projectActions i

/-- Perfect recall for a FOSG is the conjunction of observation recall and
action recall. For native FOSGs this holds by construction, since information
states are action-observation histories. -/
def PerfectRecall (G : FOSG ι W Act PrivObs PubObs) : Prop :=
  G.ObsRecall ∧ G.ActionRecall

theorem obsRecall
    (G : FOSG ι W Act PrivObs PubObs) : G.ObsRecall := by
  intro i h h' hInfo
  exact History.projectObservations_eq_of_playerView_eq (G := G) i hInfo

theorem actionRecall
    (G : FOSG ι W Act PrivObs PubObs) : G.ActionRecall := by
  intro i h h' hInfo
  exact History.projectActions_eq_of_playerView_eq (G := G) i hInfo

theorem perfectRecall
    (G : FOSG ι W Act PrivObs PubObs) : G.PerfectRecall :=
  ⟨G.obsRecall, G.actionRecall⟩

theorem perfectRecall_obs
    {G : FOSG ι W Act PrivObs PubObs}
    (hPR : G.PerfectRecall) : G.ObsRecall :=
  hPR.1

theorem perfectRecall_action
    {G : FOSG ι W Act PrivObs PubObs}
    (hPR : G.PerfectRecall) : G.ActionRecall :=
  hPR.2

end FOSG

end GameTheory
