/-
# Interim optimality in Bayesian games

Bayes-Nash is not a second equilibrium predicate: it is ordinary `IsNash` of
the direct type-contingent game form under expected utility. The theorem below
identifies it with prior-weighted interim optimality at every own type.

The interim value is intentionally unnormalised, so zero-probability types
contribute zero. Normalized conditioning and posterior comparison use shared
PMF probability mathematics.

Primary reference: J. C. Harsanyi, “Games with Incomplete Information Played
by Bayesian Players,” *Management Science* 14 (1967–1968).
-/

import GameTheory.Core.Bayesian
import GameTheory.Core.Utility
import GameTheory.Math.Probability.ExpectationConditioning
import GameTheory.Math.Probability.ExpectationMap

noncomputable section

namespace GameTheory

open GameTheory.Math.Probability

universe uι ut ua

variable {ι : Type uι}

namespace BayesianGame

/-- The induced real utility on realized type/action outcomes. -/
def utility (B : BayesianGame ι) : Utility B.signature :=
  fun outcome who => B.payoff outcome.1 outcome.2 who

/-- The contingent deviation that changes the response only at one own type. -/
def singleTypeDeviation (B : BayesianGame ι)
    (plan : Profile B.signature) (who : ι) [DecidableEq (B.Ty who)]
    (ownType : B.Ty who) (respond : B.Act who) : B.Ty who → B.Act who :=
  fun t => if t = ownType then respond else plan who t

/-- The unnormalised payoff contributed by one own-type event. -/
def interimPayoff (B : BayesianGame ι) [DecidableEq ι]
    (who : ι) [DecidableEq (B.Ty who)] (ownType : B.Ty who)
    (plan : Profile B.signature) (respond : B.Act who) :
    (∀ i, B.Ty i) → ℝ :=
  fun types => if types who = ownType then
    B.payoff types (Profile.update (B.actionsOf plan types) who respond) who
    else 0

/-- The prior-weighted interim value of taking `respond` at one own type while
all other coordinates use `plan`. No other player's type is an argument. -/
def interimValue (B : BayesianGame ι) [DecidableEq ι] (who : ι)
    [DecidableEq (B.Ty who)] (ownType : B.Ty who)
    (plan : Profile B.signature) (respond : B.Act who)
    (hintegrable : PayoffIntegrable B.prior
      (B.interimPayoff who ownType plan respond)) : ℝ :=
  expect B.prior (B.interimPayoff who ownType plan respond) hintegrable

/-- The payoff on type profiles generated by a pure contingent plan. -/
def planPayoff (B : BayesianGame ι) (who : ι)
    (plan : Profile B.signature) : (∀ i, B.Ty i) → ℝ :=
  fun types => B.payoff types (B.actionsOf plan types) who

/-- Integrability of an actual plan outcome law transports to the prior's
type-profile presentation. -/
theorem planPayoff_integrable (B : BayesianGame ι)
    (who : ι) (plan : Profile B.signature)
    (h : UtilityIntegrable B.utility who (B.toForm.play plan)) :
    PayoffIntegrable B.prior (B.planPayoff who plan) := by
  exact (payoffIntegrable_map_iff
    (fun types => (types, B.actionsOf plan types)) B.prior
    (fun outcome => B.utility outcome who)).mp
    (by simpa only [BayesianGame.toForm_play] using h)

/-- Integrability is invariant between a plan's outcome law and its prior
type-profile representation. -/
theorem planPayoff_integrable_iff (B : BayesianGame ι)
    (who : ι) (plan : Profile B.signature) :
    UtilityIntegrable B.utility who (B.toForm.play plan) ↔
      PayoffIntegrable B.prior (B.planPayoff who plan) := by
  let encode := fun types : ∀ i, B.Ty i =>
    (types, B.actionsOf plan types)
  let u := fun outcome : B.signature.Outcome =>
    B.payoff outcome.1 outcome.2 who
  have hmap : PayoffIntegrable (PMF.map encode B.prior) u ↔
      PayoffIntegrable B.prior (u ∘ encode) :=
    payoffIntegrable_map_iff encode B.prior u
  have hfun : ∀ types, (u ∘ encode) types = B.planPayoff who plan types := by
    intro types
    rfl
  have hplay : UtilityIntegrable B.utility who (B.toForm.play plan) ↔
      PayoffIntegrable (PMF.map encode B.prior) u := by
    rfl
  constructor
  · intro h
    have hcompose := hmap.mp (hplay.mp h)
    exact payoffIntegrable_congr_on_support
      (fun types _ => hfun types) hcompose
  · intro h
    have hcompose := payoffIntegrable_congr_on_support
      (fun types _ => (hfun types).symm) h
    exact hplay.mpr (hmap.mpr hcompose)

/-- Restricting an updated-plan payoff to one type gives the corresponding
interim payoff. -/
theorem planPayoff_indicator_eq_interimPayoff (B : BayesianGame ι)
    [DecidableEq ι] (who : ι) [DecidableEq (B.Ty who)]
    (ownType : B.Ty who) (plan : Profile B.signature)
    (respond : B.Act who) (deviation : B.Ty who → B.Act who)
    (hrespond : deviation ownType = respond) :
    ∀ types, {types | types who = ownType}.indicator
        (B.planPayoff who (Profile.update plan who deviation)) types =
      B.interimPayoff who ownType plan respond types := by
  intro types
  by_cases ht : types who = ownType
  · simp [planPayoff, interimPayoff, ht, B.actionsOf_update, hrespond]
  · simp [interimPayoff, ht]

/-- The actual whole-plan deviation guard supplies the local interim guard. -/
theorem interimPayoff_integrable_of_deviation (B : BayesianGame ι)
    [DecidableEq ι] (who : ι) [DecidableEq (B.Ty who)]
    (ownType : B.Ty who) (plan : Profile B.signature)
    (respond : B.Act who) (deviation : B.Ty who → B.Act who)
    (hrespond : deviation ownType = respond)
    (hdev : UtilityIntegrable B.utility who
      (B.toForm.play (Profile.update plan who deviation))) :
    PayoffIntegrable B.prior (B.interimPayoff who ownType plan respond) := by
  exact payoffIntegrable_congr_on_support
    (fun types _ => B.planPayoff_indicator_eq_interimPayoff who ownType
      plan respond deviation hrespond types)
    (payoffIntegrable_indicator _
      (B.planPayoff_integrable who (Profile.update plan who deviation) hdev))

/-- The ex-ante utility of a contingent plan is its prior expectation over
type profiles, with the exact same integrability guard. -/
theorem expectedUtility_eq_prior (B : BayesianGame ι)
    (who : ι) (plan : Profile B.signature)
    (h : UtilityIntegrable B.utility who (B.toForm.play plan)) :
    expectedUtility B.utility who (B.toForm.play plan) h =
      expect B.prior (B.planPayoff who plan)
        (B.planPayoff_integrable who plan h) := by
  let encode : (∀ i, B.Ty i) → B.signature.Outcome := fun types =>
    (types, B.actionsOf plan types)
  have hprior : PayoffIntegrable B.prior
      ((fun outcome => B.utility outcome who) ∘ encode) :=
    (payoffIntegrable_map_iff encode B.prior
      (fun outcome => B.utility outcome who)).mp
      (by simpa only [BayesianGame.toForm_play, encode] using h)
  have hmap : PayoffIntegrable (PMF.map encode B.prior)
      (fun outcome => B.utility outcome who) := by
    simpa only [BayesianGame.toForm_play, encode] using h
  calc
    expectedUtility B.utility who (B.toForm.play plan) h =
        expect (PMF.map encode B.prior)
          (fun outcome => B.utility outcome who) hmap := by
            simp only [expectedUtility, encode]
    _ = expect B.prior ((fun outcome => B.utility outcome who) ∘ encode)
        hprior := expect_map encode B.prior _ hprior hmap
    _ = expect B.prior (B.planPayoff who plan)
        (payoffIntegrable_congr_on_support (fun _ _ => rfl) hprior) := by
          rfl

/-- A guarded prior-weighted interim value obtained from an actual contingent
plan deviation. -/
noncomputable def interimValueOfDeviation (B : BayesianGame ι)
    [DecidableEq ι] (who : ι) [DecidableEq (B.Ty who)]
    (ownType : B.Ty who) (plan : Profile B.signature)
    (respond : B.Act who) (deviation : B.Ty who → B.Act who)
    (hrespond : deviation ownType = respond)
    (hdev : UtilityIntegrable B.utility who
      (B.toForm.play (Profile.update plan who deviation))) : ℝ :=
  B.interimValue who ownType plan respond
    (B.interimPayoff_integrable_of_deviation who ownType plan
      respond deviation hrespond hdev)

/-- An interim value is the prior expectation of the corresponding
event-restricted whole-plan payoff. -/
theorem interimValueOfDeviation_eq_restricted (B : BayesianGame ι)
    [DecidableEq ι] (who : ι) [DecidableEq (B.Ty who)]
    (ownType : B.Ty who) (plan : Profile B.signature)
    (respond : B.Act who) (deviation : B.Ty who → B.Act who)
    (hrespond : deviation ownType = respond)
    (hdev : UtilityIntegrable B.utility who
      (B.toForm.play (Profile.update plan who deviation))) :
    B.interimValueOfDeviation who ownType plan respond deviation hrespond hdev =
      expect B.prior
        ({types | types who = ownType}.indicator
          (B.planPayoff who (Profile.update plan who deviation)))
        (payoffIntegrable_indicator _
          (B.planPayoff_integrable who
            (Profile.update plan who deviation) hdev)) := by
  unfold interimValueOfDeviation interimValue
  exact (expect_congr_on_support
    (fun types _ => B.planPayoff_indicator_eq_interimPayoff who ownType
      plan respond deviation hrespond types)
    (payoffIntegrable_indicator _
      (B.planPayoff_integrable who (Profile.update plan who deviation) hdev))
    (B.interimPayoff_integrable_of_deviation who ownType plan
      respond deviation hrespond hdev)).symm

/-- A finite own-type carrier partitions prior expectation into the
prior-weighted interim values of its coordinates. -/
theorem prior_expect_eq_sum (B : BayesianGame ι) (who : ι)
    [Fintype (B.Ty who)]
    (f : (∀ i, B.Ty i) → ℝ) (hf : PayoffIntegrable B.prior f) :
    expect B.prior f hf =
      ∑ ownType : B.Ty who,
        expect B.prior (((fun types => types who) ⁻¹' {ownType}).indicator f)
          (payoffIntegrable_indicator _ hf) := by
  simpa only [Set.indicator_apply, Set.mem_preimage,
    Set.mem_singleton_iff] using
      expect_eq_sum_fibers B.prior (fun types => types who) f hf

/-- Finite own-type expected-utility decomposition. The general interim
characterization below does not require this finite carrier. -/
theorem expectedUtility_update (B : BayesianGame ι)
    [DecidableEq ι] (plan : Profile B.signature) (who : ι)
    [Fintype (B.Ty who)] [DecidableEq (B.Ty who)]
    (deviation : B.Ty who → B.Act who)
    (hdev : UtilityIntegrable B.utility who
      (B.toForm.play (Profile.update plan who deviation))) :
    expectedUtility B.utility who
        (B.toForm.play (Profile.update plan who deviation)) hdev =
      ∑ ownType : B.Ty who,
        B.interimValueOfDeviation who ownType plan (deviation ownType)
          deviation rfl hdev := by
  let updated := Profile.update plan who deviation
  have hprior : PayoffIntegrable B.prior (B.planPayoff who updated) :=
    B.planPayoff_integrable who updated
      (by simpa only [updated] using hdev)
  have hmap := B.expectedUtility_eq_prior who updated
    (by simpa only [updated] using hdev)
  rw [hmap]
  rw [expect_eq_sum_fibers B.prior (fun types => types who)
    (B.planPayoff who updated) hprior]
  apply Finset.sum_congr rfl
  intro ownType _
  simp only [interimValueOfDeviation, interimValue]
  exact expect_congr_on_support
    (fun types _ => B.planPayoff_indicator_eq_interimPayoff who ownType
      plan (deviation ownType) deviation rfl types)
    (payoffIntegrable_indicator _ hprior)
    (B.interimPayoff_integrable_of_deviation who ownType plan
      (deviation ownType) deviation rfl hdev)

private theorem isNash_implies_interim (B : BayesianGame ι)
    [DecidableEq ι] [∀ i, DecidableEq (B.Ty i)]
    (plan : Profile B.signature)
    (hdeviation : ∀ who (deviation : B.Ty who → B.Act who),
      UtilityIntegrable B.utility who
        (B.toForm.play (Profile.update plan who deviation))) :
    IsNash B.toForm (euPreference B.utility) plan →
      ∀ (who : ι) (ownType : B.Ty who) (respond : B.Act who),
        B.interimValueOfDeviation who ownType plan respond
          (B.singleTypeDeviation plan who ownType respond) (by
            simp [singleTypeDeviation])
          (hdeviation who (B.singleTypeDeviation plan who ownType respond)) ≤
        B.interimValueOfDeviation who ownType plan (plan who ownType)
          (fun t => plan who t) rfl (by
            simpa only [Profile.update_eq_self] using
              hdeviation who (plan who)) := by
  rw [isNash_iff]
  intro hnash who ownType respond
  let one := B.singleTypeDeviation plan who ownType respond
  have hOneRespond : one ownType = respond := by
    simp [one, singleTypeDeviation]
  have hOneRespond' :
      B.singleTypeDeviation plan who ownType respond ownType = respond := by
    simpa only [one] using hOneRespond
  have hone : UtilityIntegrable B.utility who
      (B.toForm.play (Profile.update plan who one)) := hdeviation who one
  have hbase : UtilityIntegrable B.utility who (B.toForm.play plan) := by
    simpa only [Profile.update_eq_self] using hdeviation who (plan who)
  have hpref := (hnash who one)
  have hle := (euPreference_iff B.utility who
    (B.toForm.play plan) (B.toForm.play (Profile.update plan who one))
    hbase hone).mp hpref
  rw [B.expectedUtility_eq_prior who
    (Profile.update plan who one) hone,
    B.expectedUtility_eq_prior who plan hbase] at hle
  have hpriorOne : PayoffIntegrable B.prior
      (B.planPayoff who (Profile.update plan who one)) :=
    B.planPayoff_integrable who (Profile.update plan who one) hone
  have hpriorBase : PayoffIntegrable B.prior (B.planPayoff who plan) :=
    B.planPayoff_integrable who plan hbase
  have hfg : ∀ types ∈ B.prior.support,
      types ∉ {types | types who = ownType} →
        B.planPayoff who (Profile.update plan who one) types =
          B.planPayoff who plan types := by
    intro types _ hnot
    have ht : types who ≠ ownType := by simpa using hnot
    unfold planPayoff
    have ha : B.actionsOf (Profile.update plan who one) types =
        B.actionsOf plan types := by
      rw [B.actionsOf_update]
      funext i
      by_cases hi : i = who
      · subst hi
        simp [one, singleTypeDeviation, ht, BayesianGame.actionsOf]
      · simp [Profile.update_of_ne _ _ hi, BayesianGame.actionsOf]
    exact congrArg (fun actions => B.payoff types actions who) ha
  have hnum := expect_indicator_le_of_expect_le_eq_off
    B.prior {types | types who = ownType}
    (B.planPayoff who (Profile.update plan who one))
    (B.planPayoff who plan) hpriorOne hpriorBase hfg hle
  have hvalueOne := B.interimValueOfDeviation_eq_restricted who ownType
    plan respond (B.singleTypeDeviation plan who ownType respond)
    hOneRespond'
    (by simpa only [one] using hone)
  have hbaseIdentity : UtilityIntegrable B.utility who
      (B.toForm.play (Profile.update plan who (fun t => plan who t))) := by
    simpa only [Profile.update_eq_self] using hbase
  have hplanIdentity : Profile.update plan who (fun t => plan who t) = plan := by
    simpa only using Profile.update_eq_self plan who
  have hvalueBase := B.interimValueOfDeviation_eq_restricted who ownType
    plan (plan who ownType) (fun t => plan who t) rfl hbaseIdentity
  have hvalueBase' : expect B.prior
      ({types | types who = ownType}.indicator
        (B.planPayoff who plan))
      (payoffIntegrable_indicator _ hpriorBase) =
    B.interimValueOfDeviation who ownType plan (plan who ownType)
      (fun t => plan who t) rfl hbaseIdentity := by
    simpa only [hplanIdentity] using hvalueBase.symm
  calc
    B.interimValueOfDeviation who ownType plan respond
        (B.singleTypeDeviation plan who ownType respond) _ _ =
      expect B.prior
        ({types | types who = ownType}.indicator
          (B.planPayoff who
            (Profile.update plan who (B.singleTypeDeviation plan who ownType respond))))
        _ := hvalueOne
    _ ≤ expect B.prior
        ({types | types who = ownType}.indicator (B.planPayoff who plan)) _ := hnum
    _ = B.interimValueOfDeviation who ownType plan (plan who ownType)
        (fun t => plan who t) _ _ := hvalueBase'

private theorem interim_implies_isNash (B : BayesianGame ι)
    [DecidableEq ι] [∀ i, DecidableEq (B.Ty i)]
    (plan : Profile B.signature)
    (hdeviation : ∀ who (deviation : B.Ty who → B.Act who),
      UtilityIntegrable B.utility who
        (B.toForm.play (Profile.update plan who deviation))) :
    (∀ (who : ι) (ownType : B.Ty who) (respond : B.Act who),
        B.interimValueOfDeviation who ownType plan respond
          (B.singleTypeDeviation plan who ownType respond) (by
            simp [singleTypeDeviation])
          (hdeviation who (B.singleTypeDeviation plan who ownType respond)) ≤
        B.interimValueOfDeviation who ownType plan (plan who ownType)
          (fun t => plan who t) rfl (by
            simpa only [Profile.update_eq_self] using
              hdeviation who (plan who))) →
      IsNash B.toForm (euPreference B.utility) plan := by
  rw [isNash_iff]
  intro hinterim who deviation
  have hbase : UtilityIntegrable B.utility who (B.toForm.play plan) := by
    simpa only [Profile.update_eq_self] using hdeviation who (plan who)
  have hdev := hdeviation who deviation
  have hpriorDev : PayoffIntegrable B.prior
      (B.planPayoff who (Profile.update plan who deviation)) :=
    B.planPayoff_integrable who (Profile.update plan who deviation) hdev
  have hpriorBase : PayoffIntegrable B.prior (B.planPayoff who plan) :=
    B.planPayoff_integrable who plan hbase
  have hfiber := expect_fiberwise_le B.prior (fun types => types who)
    (B.planPayoff who (Profile.update plan who deviation))
    (B.planPayoff who plan) hpriorDev hpriorBase ?_
  · have hcmp : expectedUtility B.utility who
        (B.toForm.play (Profile.update plan who deviation)) hdev ≤
      expectedUtility B.utility who (B.toForm.play plan) hbase := by
        rw [B.expectedUtility_eq_prior who
          (Profile.update plan who deviation) hdev,
          B.expectedUtility_eq_prior who plan hbase]
        exact hfiber
    exact (euPreference_iff B.utility who
      (B.toForm.play plan)
      (B.toForm.play (Profile.update plan who deviation)) hbase hdev).2 hcmp
  · intro ownType hb
    let one := B.singleTypeDeviation plan who ownType
      (deviation ownType)
    have hone : UtilityIntegrable B.utility who
        (B.toForm.play (Profile.update plan who one)) :=
      hdeviation who one
    have hOneRespond : one ownType = deviation ownType := by
      simp [one, singleTypeDeviation]
    have hOneRespond' :
        B.singleTypeDeviation plan who ownType (deviation ownType) ownType =
          deviation ownType := by
      simpa only [one] using hOneRespond
    have hraw := hinterim who ownType (deviation ownType)
    have hnumDev : expect B.prior
        ({types | types who = ownType}.indicator
          (B.planPayoff who (Profile.update plan who deviation)))
        (payoffIntegrable_indicator _ hpriorDev) =
        B.interimValueOfDeviation who ownType plan
          (deviation ownType)
          (B.singleTypeDeviation plan who ownType (deviation ownType))
          hOneRespond' (by simpa only [one] using hone) := by
      rw [B.interimValueOfDeviation_eq_restricted]
      apply expect_congr_on_support
      intro types _
      by_cases ht : types who = ownType
      · simp [planPayoff, singleTypeDeviation, actionsOf_update, ht]
      · simp [Set.indicator, ht]
    have hbaseIdentity : UtilityIntegrable B.utility who
        (B.toForm.play (Profile.update plan who (fun t => plan who t))) :=
      hdeviation who (plan who)
    have hnumBase := B.interimValueOfDeviation_eq_restricted who ownType
      plan (plan who ownType) (fun t => plan who t) rfl hbaseIdentity
    have hnumBase' : B.interimValueOfDeviation who ownType plan
        (plan who ownType) (fun t => plan who t) rfl hbaseIdentity =
      expect B.prior ({types | types who = ownType}.indicator
        (B.planPayoff who plan))
        (payoffIntegrable_indicator _ hpriorBase) := by
      simpa only [Profile.update_eq_self] using hnumBase
    have hnum_le : expect B.prior
        ({types | types who = ownType}.indicator
          (B.planPayoff who (Profile.update plan who deviation)))
        (payoffIntegrable_indicator _ hpriorDev) ≤
      expect B.prior ({types | types who = ownType}.indicator
        (B.planPayoff who plan)) (payoffIntegrable_indicator _ hpriorBase) := by
      rw [hnumDev, ← hnumBase']
      exact hraw
    rw [expect_fiberPosterior B.prior (fun types => types who)
      (B.planPayoff who (Profile.update plan who deviation)) hpriorDev
      ownType hb,
      expect_fiberPosterior B.prior (fun types => types who)
        (B.planPayoff who plan) hpriorBase ownType hb]
    exact (div_le_div_iff_of_pos_right
      (fiberMass_toReal_pos B.prior (fun types => types who) ownType hb)).2
        hnum_le

/-- Ex-ante Nash of the direct form is exactly interim optimality at every own
type, under explicit integration of every actual whole-plan deviation. No
finite type carrier is needed. -/
theorem isNash_iff_interim (B : BayesianGame ι)
    [DecidableEq ι] [∀ i, DecidableEq (B.Ty i)]
    (plan : Profile B.signature)
    (hdeviation : ∀ who (deviation : B.Ty who → B.Act who),
      UtilityIntegrable B.utility who
        (B.toForm.play (Profile.update plan who deviation))) :
    IsNash B.toForm (euPreference B.utility) plan ↔
      ∀ (who : ι) (ownType : B.Ty who) (respond : B.Act who),
        B.interimValueOfDeviation who ownType plan respond
          (B.singleTypeDeviation plan who ownType respond) (by
            simp [singleTypeDeviation])
          (hdeviation who (B.singleTypeDeviation plan who ownType respond)) ≤
        B.interimValueOfDeviation who ownType plan (plan who ownType)
          (fun t => plan who t) rfl (by
            simpa only [Profile.update_eq_self] using
              hdeviation who (plan who)) := by
  constructor
  · exact B.isNash_implies_interim plan hdeviation
  · exact B.interim_implies_isNash plan hdeviation

end BayesianGame

end GameTheory
