/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/

import GameTheory.Languages.OpenGame.Mixed

/-!
# Coend Contexts for Bayesian Open Games

The concrete context coend of Bolt--Hedges--Zahn is represented by:

* a hidden-state type `Θ`;
* a joint finite law on `Θ × X`; and
* a continuation kernel `Θ × Y → FinPMF R`.

Representatives are quotiented by the coend reparameterization equation. For
`f : Θ → Ξ`, pushing the hidden coordinate of the prior through `f` is
identified with pulling the continuation back through `f`. The equivalence
relation is the reflexive, symmetric, transitive closure of this generating
step.

This module formalizes contexts only. It does not yet replace `OpenGame`'s
deterministic context field or claim the full Bayesian-open-game composition
theorems.
-/

noncomputable section

namespace OpenGames

universe u

/-- A representative of a finite Bayesian/coend context. -/
structure CoendContextRep (X Y R : Type u) where
  /-- Unobservable state carried between the prior and continuation. -/
  Hidden : Type u
  /-- Joint law of hidden state and visible input history. -/
  prior : Math.FinPMF (Hidden × X)
  /-- Continuation kernel retaining correlation through the hidden state. -/
  continuation : Hidden × Y → Math.FinPMF R

namespace CoendContextRep

variable {X Y R : Type u}

/-- One generating coend equation. The left representative pushes hidden
state forward; the right representative pulls the continuation back. -/
inductive ReparamStep : CoendContextRep X Y R →
    CoendContextRep X Y R → Prop where
  | reparam {Θ Ξ : Type u} (f : Θ → Ξ)
      (prior : Math.FinPMF (Θ × X))
      (continuation : Ξ × Y → Math.FinPMF R) :
      ReparamStep
        ⟨Ξ, Math.FinPMF.map (fun z => (f z.1, z.2)) prior,
          continuation⟩
        ⟨Θ, prior, fun z => continuation (f z.1, z.2)⟩

/-- The equivalence relation generated by hidden-state reparameterization. -/
abbrev Reparam := Relation.EqvGen
  (ReparamStep (X := X) (Y := Y) (R := R))

/-- Setoid presenting the concrete context coend. -/
def reparamSetoid : Setoid (CoendContextRep X Y R) where
  r := Reparam
  iseqv := Relation.EqvGen.is_equivalence _

/-- Visible history marginal of a representative. -/
def historyMarginal (c : CoendContextRep X Y R) : Math.FinPMF X :=
  Math.FinPMF.map Prod.snd c.prior

/-- Hidden-state reparameterization preserves the visible history marginal. -/
theorem historyMarginal_eq_of_reparam {c d : CoendContextRep X Y R}
    (h : Reparam c d) : historyMarginal c = historyMarginal d := by
  induction h with
  | rel c d hstep =>
      cases hstep
      rw [historyMarginal, historyMarginal, Math.FinPMF.map_comp]
      rfl
  | refl => rfl
  | symm _ _ _ ih => exact ih.symm
  | trans _ _ _ _ _ ih ih' => exact ih.trans ih'

/-- Unconditional continuation response at output `y`, retaining the hidden
state correlation encoded by the representative. -/
def responseAt (c : CoendContextRep X Y R) (y : Y) : Math.FinPMF R :=
  Math.FinPMF.bind (Math.FinPMF.map Prod.fst c.prior)
    fun θ => c.continuation (θ, y)

/-- The unconditional response law is invariant under hidden-state
reparameterization. -/
theorem responseAt_eq_of_reparam {c d : CoendContextRep X Y R}
    (h : Reparam c d) (y : Y) : responseAt c y = responseAt d y := by
  induction h with
  | rel c d hstep =>
      cases hstep
      simp [responseAt, Function.comp_def]
  | refl => rfl
  | symm _ _ _ ih => exact ih.symm
  | trans _ _ _ _ _ ih ih' => exact ih.trans ih'

end CoendContextRep

/-- A Bayesian context modulo hidden-state reparameterization. -/
def CoendContext (X Y R : Type u) :=
  Quotient (CoendContextRep.reparamSetoid (X := X) (Y := Y) (R := R))

namespace CoendContext

variable {X Y R : Type u}

/-- Insert a raw representative into the context coend. -/
def mk (c : CoendContextRep X Y R) : CoendContext X Y R :=
  Quotient.mk _ c

/-- Embed an ordinary deterministic history/continuation context. -/
def ofDeterministic (x : X) (k : Y → R) : CoendContext X Y R :=
  mk
    { Hidden := ULift.{u} Unit
      prior := Math.FinPMF.pure (ULift.up (), x)
      continuation := fun z => Math.FinPMF.pure (k z.2) }

/-- Reparameterizing a representative does not change its coend class. -/
theorem reparam_eq {Θ Ξ : Type u} (f : Θ → Ξ)
    (prior : Math.FinPMF (Θ × X))
    (continuation : Ξ × Y → Math.FinPMF R) :
    mk
        { Hidden := Ξ
          prior := Math.FinPMF.map (fun z => (f z.1, z.2)) prior
          continuation := continuation } =
      mk
        { Hidden := Θ
          prior := prior
          continuation := fun z => continuation (f z.1, z.2) } := by
  apply Quotient.sound
  exact Relation.EqvGen.rel _ _
    (CoendContextRep.ReparamStep.reparam f prior continuation)

/-- The visible history marginal is well-defined on coend classes. -/
def historyMarginal (c : CoendContext X Y R) : Math.FinPMF X :=
  Quotient.lift CoendContextRep.historyMarginal
    (fun _ _ h => CoendContextRep.historyMarginal_eq_of_reparam h) c

/-- The unconditional continuation response is well-defined on coend
classes. -/
def responseAt (c : CoendContext X Y R) (y : Y) : Math.FinPMF R :=
  Quotient.lift (fun representative => representative.responseAt y)
    (fun _ _ h => CoendContextRep.responseAt_eq_of_reparam h y) c

@[simp] theorem historyMarginal_mk (c : CoendContextRep X Y R) :
    historyMarginal (mk c) = c.historyMarginal := rfl

@[simp] theorem historyMarginal_ofDeterministic (x : X) (k : Y → R) :
    historyMarginal (ofDeterministic x k) = Math.FinPMF.pure x := by
  simp [historyMarginal, ofDeterministic, mk,
    CoendContextRep.historyMarginal]

@[simp] theorem responseAt_ofDeterministic (x : X) (k : Y → R) (y : Y) :
    responseAt (ofDeterministic x k) y = Math.FinPMF.pure (k y) := by
  simp [responseAt, ofDeterministic, mk, CoendContextRep.responseAt]

end CoendContext

end OpenGames
