/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/

import GameTheory.Languages.OpenGame.Sequential

/-!
# Sparse Typed Decision DAG Open Games

`DecisionDAG n` presents a finite decision DAG in a certified natural
topological order.  Node `i` may observe only the typed actions at
`parents i`; the proof `parent_lt` makes recursive realization well founded.

This is the sparse-parent generalization of `ShapeSeqDep`: strategies remain
contingent plans, realization follows the causal graph, and the plain
equilibrium predicate still compiles exactly to pure strategic-form Nash.
The graph-local irrelevance theorem makes the intended Bayesian-network/MAID
reading explicit: changing a plan cannot affect a node outside its descendant
cone.
-/

namespace OpenGames

/-- A finite decision DAG whose node numbering is a topological order. -/
structure DecisionDAG (n : Nat) where
  parents : Fin n → Finset (Fin n)
  parent_lt : ∀ {i j : Fin n}, j ∈ parents i → j.val < i.val

namespace DecisionDAG

variable {n : Nat}

/-- The edge relation points from an informational parent to its child. -/
def Edge (D : DecisionDAG n) (parent child : Fin n) : Prop :=
  parent ∈ D.parents child

/-- Strict causal ancestry generated by the parent relation. -/
abbrev IsAncestor (D : DecisionDAG n) : Fin n → Fin n → Prop :=
  Relation.TransGen D.Edge

/-- A causal ancestor has a strictly smaller topological index. -/
theorem ancestor_lt (D : DecisionDAG n) {i j : Fin n}
    (h : D.IsAncestor i j) : i.val < j.val := by
  induction h with
  | single hparent => exact D.parent_lt hparent
  | tail _ hparent ih => exact Nat.lt_trans ih (D.parent_lt hparent)

/-- The complete-history DAG: stage `i` observes every earlier stage. -/
def complete (n : Nat) : DecisionDAG n where
  parents i := Finset.univ.filter fun j => j.val < i.val
  parent_lt hij := (Finset.mem_filter.mp hij).2

/-- The edgeless DAG presents simultaneous decisions in natural numbering. -/
def discrete (n : Nat) : DecisionDAG n where
  parents _ := ∅
  parent_lt h := by simp at h

end DecisionDAG

namespace ShapeDAG

variable {n : Nat}

/-- The typed action configuration observed at decision `i`. -/
abbrev History (D : DecisionDAG n) (A : Fin n → Type) (i : Fin n) :=
  ∀ parent : ↥(D.parents i), A parent.val

/-- One parent-contingent plan per decision node. -/
abbrev Strategy (D : DecisionDAG n) (A : Fin n → Type) :=
  ∀ i, History D A i → A i

/-- Realize one node by recursively realizing exactly its informational
parents. -/
def realizeAt (D : DecisionDAG n) {A : Fin n → Type}
    (σ : Strategy D A) (i : Fin n) : A i :=
  σ i fun parent => realizeAt D σ parent.val
termination_by i.val
decreasing_by exact D.parent_lt parent.property

/-- Realize the complete typed action assignment. -/
def realize (D : DecisionDAG n) {A : Fin n → Type}
    (σ : Strategy D A) : ∀ i, A i :=
  fun i => realizeAt D σ i

/-- Realization unfolds to the plan selected at the realized parent
configuration. -/
theorem realize_eq (D : DecisionDAG n) {A : Fin n → Type}
    (σ : Strategy D A) (i : Fin n) :
    realize D σ i = σ i (fun parent => realize D σ parent.val) := by
  change realizeAt D σ i = σ i (fun parent => realizeAt D σ parent.val)
  rw [realizeAt]

/-- Replacing a later-numbered plan cannot alter an earlier node. -/
theorem realizeAt_update_of_lt (D : DecisionDAG n) {A : Fin n → Type}
    (σ : Strategy D A) (i : Fin n) (deviation : History D A i → A i)
    (j : Fin n) (hji : j.val < i.val) :
    realizeAt D (Function.update σ i deviation) j = realizeAt D σ j := by
  rw [realizeAt, realizeAt]
  have hne : j ≠ i := by intro h; subst h; omega
  rw [Function.update_of_ne hne]
  congr 1
  funext parent
  exact realizeAt_update_of_lt D σ i deviation parent.val
    (Nat.lt_trans (D.parent_lt parent.property) hji)
termination_by j.val
decreasing_by exact D.parent_lt parent.property

/-- A plan replacement is causally irrelevant outside that node's strict
descendant cone (and outside the node itself). -/
theorem realizeAt_update_of_not_ancestor (D : DecisionDAG n)
    {A : Fin n → Type} (σ : Strategy D A) (i : Fin n)
    (deviation : History D A i → A i) (j : Fin n)
    (hne : j ≠ i) (hnot : ¬ D.IsAncestor i j) :
    realizeAt D (Function.update σ i deviation) j = realizeAt D σ j := by
  rw [realizeAt, realizeAt, Function.update_of_ne hne]
  congr 1
  funext parent
  have hip : parent.val ≠ i := by
    intro heq
    subst i
    exact hnot (.single parent.property)
  have hparent : ¬ D.IsAncestor i parent.val := by
    intro hancestor
    exact hnot (hancestor.tail parent.property)
  exact realizeAt_update_of_not_ancestor D σ i deviation parent.val
    hip hparent
termination_by j.val
decreasing_by exact D.parent_lt parent.property

/-! ## Discrete specialization -/

/-- An edgeless decision node has exactly one parent configuration. -/
def discreteHistoryEquiv (A : Fin n → Type) (i : Fin n) :
    History (DecisionDAG.discrete n) A i ≃ Unit where
  toFun _ := ()
  invFun _ parent := by
    have hp : parent.val ∈ (∅ : Finset (Fin n)) := by
      rw [← show (DecisionDAG.discrete n).parents i = ∅ from rfl]
      exact parent.property
    exact (Finset.notMem_empty parent.val hp).elim
  left_inv history := by
    funext parent
    have hp : parent.val ∈ (∅ : Finset (Fin n)) := by
      rw [← show (DecisionDAG.discrete n).parents i = ∅ from rfl]
      exact parent.property
    exact (Finset.notMem_empty parent.val hp).elim
  right_inv _ := rfl

/-- A singleton boundary is equivalent to a Π-shaped boundary of singleton
components. -/
def unitPiEquiv (ι : Type) : Unit ≃ (ι → Unit) where
  toFun _ _ := ()
  invFun _ := ()
  left_inv _ := rfl
  right_inv f := by
    funext i
    exact Subsingleton.elim _ _

/-- Strategies on an edgeless decision DAG are precisely closed simultaneous
contingent strategies. -/
def discreteStrategyEquiv (A : Fin n → Type) :
    Strategy (DecisionDAG.discrete n) A ≃ (∀ i, Unit → A i) where
  toFun σ i u := σ i ((discreteHistoryEquiv A i).symm u)
  invFun τ i history := τ i (discreteHistoryEquiv A i history)
  left_inv σ := by
    funext i history
    change σ i ((discreteHistoryEquiv A i).symm
      (discreteHistoryEquiv A i history)) = σ i history
    rw [(discreteHistoryEquiv A i).symm_apply_apply]
  right_inv τ := by
    funext i u
    change τ i (discreteHistoryEquiv A i
      ((discreteHistoryEquiv A i).symm u)) = τ i u
    rw [(discreteHistoryEquiv A i).apply_symm_apply]

/-- With no parent edges, realization at a node is evaluation at its unique
empty history. -/
theorem realize_discrete (A : Fin n → Type)
    (σ : Strategy (DecisionDAG.discrete n) A) (i : Fin n) :
    realize (DecisionDAG.discrete n) σ i =
      (discreteStrategyEquiv A σ) i () := by
  rw [realize_eq]
  change σ i (fun parent =>
      realize (DecisionDAG.discrete n) σ parent.val) =
    σ i ((discreteHistoryEquiv A i).symm ())
  congr 1
  apply (discreteHistoryEquiv A i).injective
  rfl

/-- On a discrete DAG, changing one contingent plan changes exactly the
corresponding realized action. -/
theorem realize_update_discrete (A : Fin n → Type)
    (σ : Strategy (DecisionDAG.discrete n) A) (i : Fin n)
    (deviation : History (DecisionDAG.discrete n) A i → A i) :
    realize (DecisionDAG.discrete n) (Function.update σ i deviation) =
      Function.update (realize (DecisionDAG.discrete n) σ) i
        (deviation ((discreteHistoryEquiv A i).symm ())) := by
  funext j
  by_cases hji : j = i
  · subst j
    rw [realize_discrete]
    simp [discreteStrategyEquiv, Function.update_self]
  · rw [realize_discrete, Function.update_of_ne hji, realize_discrete]
    simp [discreteStrategyEquiv, Function.update_of_ne hji]

/-- Encoding a discrete-DAG strategy as a closed simultaneous strategy
preserves its realized action profile. -/
theorem realize_discreteStrategyEquiv (A : Fin n → Type)
    (σ : Strategy (DecisionDAG.discrete n) A) :
    ShapeN.realize (fun _ => ()) (discreteStrategyEquiv A σ) =
      realize (DecisionDAG.discrete n) σ := by
  funext i
  exact (realize_discrete A σ i).symm

/-! ## Complete-history specialization -/

/-- Parents of `DecisionDAG.complete` at stage `i` are exactly the indices in
the strict prefix `Fin i.val`. -/
def completeParentEquiv (i : Fin n) :
    ↥((DecisionDAG.complete n).parents i) ≃ Fin i.val where
  toFun parent := ⟨parent.val.val, by
    have hp := parent.property
    simpa only [DecisionDAG.complete, Finset.mem_filter,
      Finset.mem_univ, true_and] using hp⟩
  invFun j := ⟨ShapeSeqDep.priorIndex i j, by
    simp only [DecisionDAG.complete, Finset.mem_filter,
      Finset.mem_univ, true_and]
    exact j.isLt⟩
  left_inv parent := by
    apply Subtype.ext
    apply Fin.ext
    rfl
  right_inv j := by
    apply Fin.ext
    rfl

/-- The action type at a complete-DAG parent is the corresponding dependent
prefix action type. -/
def completeParentValueEquiv (A : Fin n → Type) (i : Fin n)
    (parent : ↥((DecisionDAG.complete n).parents i)) :
    A parent.val ≃
      A (ShapeSeqDep.priorIndex i (completeParentEquiv i parent)) := by
  apply Equiv.cast
  congr 1

/-- Complete-DAG parent configurations are exactly the dependent histories
of `ShapeSeqDep`. -/
def completeHistoryEquiv (A : Fin n → Type) (i : Fin n) :
    History (DecisionDAG.complete n) A i ≃ ShapeSeqDep.History A i :=
  Equiv.piCongr (completeParentEquiv i) (completeParentValueEquiv A i)

/-- A complete-DAG contingent profile is exactly a `ShapeSeqDep` contingent
profile. -/
def completeStrategyEquiv (A : Fin n → Type) :
    Strategy (DecisionDAG.complete n) A ≃ ShapeSeqDep.Strategy A where
  toFun σ i h := σ i ((completeHistoryEquiv A i).symm h)
  invFun τ i h := τ i (completeHistoryEquiv A i h)
  left_inv σ := by
    funext i h
    change σ i ((completeHistoryEquiv A i).symm
      (completeHistoryEquiv A i h)) = σ i h
    rw [(completeHistoryEquiv A i).symm_apply_apply]
  right_inv τ := by
    funext i h
    change τ i (completeHistoryEquiv A i
      ((completeHistoryEquiv A i).symm h)) = τ i h
    rw [(completeHistoryEquiv A i).apply_symm_apply]

/-- Encoding a complete-DAG strategy as a sequential dependent strategy
preserves its realized typed action path. -/
theorem realize_completeStrategyEquiv (A : Fin n → Type)
    (σ : Strategy (DecisionDAG.complete n) A) :
    ShapeSeqDep.realize (completeStrategyEquiv A σ) =
      realize (DecisionDAG.complete n) σ := by
  funext i
  induction hi : i.val using Nat.strongRecOn generalizing i with
  | _ d ih =>
      rw [ShapeSeqDep.realize_eq, realize_eq]
      change σ i ((completeHistoryEquiv A i).symm
          (fun j => ShapeSeqDep.realize (completeStrategyEquiv A σ)
            (ShapeSeqDep.priorIndex i j))) =
        σ i (fun parent => realize (DecisionDAG.complete n) σ parent.val)
      congr 1
      apply (completeHistoryEquiv A i).injective
      rw [(completeHistoryEquiv A i).apply_symm_apply]
      funext j
      let parent := (completeParentEquiv i).symm j
      have hpi := Equiv.piCongr_apply_apply
        (W := fun parent : ↥((DecisionDAG.complete n).parents i) => A parent.val)
        (Z := fun q : Fin i.val => A (ShapeSeqDep.priorIndex i q))
        (completeParentEquiv i) (completeParentValueEquiv A i)
        (fun parent => realize (DecisionDAG.complete n) σ parent.val) parent
      have hj := (completeParentEquiv i).apply_symm_apply j
      change completeParentEquiv i parent = j at hj
      cases hj
      apply eq_of_heq
      exact ((heq_of_eq hpi).trans (heq_of_eq (ih parent.val.val (by
        have hp := (DecisionDAG.complete n).parent_lt parent.property
        simpa [hi] using hp) parent.val rfl).symm)).symm

/-- Decoding a dependent sequential profile into the complete DAG also
preserves realization. -/
theorem realize_completeStrategyEquiv_symm (A : Fin n → Type)
    (σ : ShapeSeqDep.Strategy A) :
    realize (DecisionDAG.complete n) ((completeStrategyEquiv A).symm σ) =
      ShapeSeqDep.realize σ := by
  have h := realize_completeStrategyEquiv A ((completeStrategyEquiv A).symm σ)
  rw [(completeStrategyEquiv A).apply_symm_apply] at h
  exact h.symm

/-- The action-level strategic game induced by a closing continuation. -/
def actionNFG (D : DecisionDAG n) (A : Fin n → Type)
    (k : (∀ i, A i) → Fin n → ℝ) :
    NFG.NFGGame (Fin n) (fun i => History D A i → A i) where
  Outcome := ∀ i, A i
  outcome := realize D
  utility := k

/-- Compile the sparse decision DAG through the existing NFG kernel bridge. -/
noncomputable def compileAction (D : DecisionDAG n) (A : Fin n → Type)
    (k : (∀ i, A i) → Fin n → ℝ) : GameTheory.KernelGame (Fin n) :=
  (actionNFG D A k).toKernelGame

end ShapeDAG

/-- The open-game shape generated by a sparse typed decision DAG. -/
def ShapeDAG {n : Nat} (D : DecisionDAG n) (A : Fin n → Type) :
    OpenGame Unit Unit (∀ i, A i) (Fin n → ℝ) where
  Strategy := ShapeDAG.Strategy D A
  play σ _ := ShapeDAG.realize D σ
  coplay _ _ _ := ()
  IsEquilibriumIn _ k σ :=
    ∀ i (deviation : ShapeDAG.History D A i → A i),
      k (ShapeDAG.realize D (Function.update σ i deviation)) i ≤
        k (ShapeDAG.realize D σ) i

namespace ShapeDAG

/-- Plain sparse-DAG equilibrium is exactly pure Nash in its induced
strategic form. -/
theorem isEquilibriumIn_iff_isNashPure {n : Nat}
    (D : DecisionDAG n) (A : Fin n → Type)
    (k : (∀ i, A i) → Fin n → ℝ) (σ : Strategy D A) :
    (OpenGames.ShapeDAG D A).IsEquilibriumIn () k σ ↔
      NFG.IsNashPure (actionNFG D A k) σ := by
  rfl

/-- Kernel-level correctness for sparse typed decision DAGs. -/
theorem isEquilibriumIn_iff_isNash {n : Nat}
    (D : DecisionDAG n) (A : Fin n → Type)
    (k : (∀ i, A i) → Fin n → ℝ) (σ : Strategy D A) :
    (OpenGames.ShapeDAG D A).IsEquilibriumIn () k σ ↔
      (compileAction D A k).IsNash σ := by
  rw [isEquilibriumIn_iff_isNashPure]
  exact NFG.IsNashPure_iff_kernelGame (actionNFG D A k) σ

/-- The edgeless decision DAG is the closed simultaneous shape, up to the
contractible Π-shaped input and cooutcome boundaries. -/
def discreteIso {n : Nat} (A : Fin n → Type) :
    OpenGameIso (OpenGames.ShapeDAG (DecisionDAG.discrete n) A)
      (ShapeN (fun _ : Fin n => Unit) A) where
  eX := unitPiEquiv (Fin n)
  eS := unitPiEquiv (Fin n)
  eY := Equiv.refl _
  eR := Equiv.refl _
  stratEquiv := discreteStrategyEquiv A
  play_preserved := by
    intro σ x
    cases x
    exact realize_discreteStrategyEquiv A σ
  coplay_preserved := by
    intro σ x r
    cases x
    rfl
  equilibrium_preserved := by
    intro x k σ
    cases x
    change (∀ i (action : A i),
        k (Function.update
          (ShapeN.realize (fun _ : Fin n => ())
            (discreteStrategyEquiv A σ)) i action) i ≤
          k (ShapeN.realize (fun _ : Fin n => ())
            (discreteStrategyEquiv A σ)) i) ↔
      ∀ i (deviation : History (DecisionDAG.discrete n) A i → A i),
        k (realize (DecisionDAG.discrete n)
          (Function.update σ i deviation)) i ≤
        k (realize (DecisionDAG.discrete n) σ) i
    rw [realize_discreteStrategyEquiv A σ]
    constructor
    · intro hsim i deviation
      rw [realize_update_discrete]
      exact hsim i (deviation ((discreteHistoryEquiv A i).symm ()))
    · intro hdag i action
      let deviation : History (DecisionDAG.discrete n) A i → A i :=
        fun _ => action
      have h := hdag i deviation
      rw [realize_update_discrete] at h
      exact h

/-- The complete-parent decision DAG recovers `ShapeSeqDep` up to the explicit
dependent-history strategy equivalence. -/
def completeIso {n : Nat} (A : Fin n → Type) :
    OpenGameIso (OpenGames.ShapeDAG (DecisionDAG.complete n) A)
      (OpenGames.ShapeSeqDep A) where
  eX := Equiv.refl _
  eS := Equiv.refl _
  eY := Equiv.refl _
  eR := Equiv.refl _
  stratEquiv := completeStrategyEquiv A
  play_preserved := by
    intro σ x
    cases x
    exact realize_completeStrategyEquiv A σ
  coplay_preserved := by
    intro σ x r
    cases x
    rfl
  equilibrium_preserved := by
    intro x k σ
    cases x
    constructor
    · intro hseq i deviation
      let seqDeviation : ShapeSeqDep.History A i → A i :=
        fun history => deviation ((completeHistoryEquiv A i).symm history)
      have hineq := hseq i seqDeviation
      have hupdate : Function.update (completeStrategyEquiv A σ) i seqDeviation =
          completeStrategyEquiv A (Function.update σ i deviation) := by
        funext j history
        by_cases hji : j = i
        · subst j
          simp [completeStrategyEquiv, seqDeviation]
        · simp [completeStrategyEquiv, Function.update_of_ne hji]
      have hpath : ShapeSeqDep.realize
          (Function.update (completeStrategyEquiv A σ) i seqDeviation) =
          realize (DecisionDAG.complete n) (Function.update σ i deviation) :=
        (congrArg ShapeSeqDep.realize hupdate).trans
          (realize_completeStrategyEquiv A (Function.update σ i deviation))
      change k (realize (DecisionDAG.complete n)
        (Function.update σ i deviation)) i ≤
          k (realize (DecisionDAG.complete n) σ) i
      calc
        _ = k (ShapeSeqDep.realize
            (Function.update (completeStrategyEquiv A σ) i seqDeviation)) i :=
          congrArg (fun path => k path i) hpath.symm
        _ ≤ k (ShapeSeqDep.realize (completeStrategyEquiv A σ)) i := hineq
        _ = _ := congrArg (fun path => k path i)
          (realize_completeStrategyEquiv A σ)
    · intro hdag i deviation
      let dagDeviation : History (DecisionDAG.complete n) A i → A i :=
        fun history => deviation (completeHistoryEquiv A i history)
      have hineq := hdag i dagDeviation
      have hupdate : completeStrategyEquiv A
          (Function.update σ i dagDeviation) =
          Function.update (completeStrategyEquiv A σ) i deviation := by
        funext j history
        by_cases hji : j = i
        · subst j
          simp [completeStrategyEquiv, dagDeviation]
        · simp [completeStrategyEquiv, Function.update_of_ne hji]
      have hpath : realize (DecisionDAG.complete n)
          (Function.update σ i dagDeviation) =
          ShapeSeqDep.realize
            (Function.update (completeStrategyEquiv A σ) i deviation) :=
        (realize_completeStrategyEquiv A
          (Function.update σ i dagDeviation)).symm.trans
            (congrArg ShapeSeqDep.realize hupdate)
      change k (ShapeSeqDep.realize
          (Function.update (completeStrategyEquiv A σ) i deviation)) i ≤
        k (ShapeSeqDep.realize (completeStrategyEquiv A σ)) i
      calc
        _ = k (realize (DecisionDAG.complete n)
            (Function.update σ i dagDeviation)) i :=
          congrArg (fun path => k path i) hpath.symm
        _ ≤ k (realize (DecisionDAG.complete n) σ) i := hineq
        _ = _ := congrArg (fun path => k path i)
          (realize_completeStrategyEquiv A σ).symm

end ShapeDAG

end OpenGames
