/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/

import GameTheory.Languages.OpenGame.Sequential

/-!
# Sparse Typed Decision DAG Open Games

`DecisionDAG n` presents a finite decision DAG in a certified natural
topological order.  Node `i` may observe only the typed actions at
`parents i`; the proof `parent_lt` makes recursive realization well founded.

This is the sparse-parent generalization of `ShapeSeqDep`: strategies remain
contingent plans, realization follows the causal graph, and the plain
equilibrium predicate still compiles exactly to pure strategic-form Nash.
The graph-local irrelevance theorem makes the intended Bayesian-network/MAID
reading explicit: changing a plan cannot affect a node outside its descendant
cone.
-/

namespace OpenGames

/-- A finite decision DAG whose node numbering is a topological order. -/
structure DecisionDAG (n : Nat) where
  parents : Fin n → Finset (Fin n)
  parent_lt : ∀ {i j : Fin n}, j ∈ parents i → j.val < i.val

namespace DecisionDAG

variable {n : Nat}

/-- The edge relation points from an informational parent to its child. -/
def Edge (D : DecisionDAG n) (parent child : Fin n) : Prop :=
  parent ∈ D.parents child

/-- Strict causal ancestry generated by the parent relation. -/
abbrev IsAncestor (D : DecisionDAG n) : Fin n → Fin n → Prop :=
  Relation.TransGen D.Edge

/-- A causal ancestor has a strictly smaller topological index. -/
theorem ancestor_lt (D : DecisionDAG n) {i j : Fin n}
    (h : D.IsAncestor i j) : i.val < j.val := by
  induction h with
  | single hparent => exact D.parent_lt hparent
  | tail _ hparent ih => exact Nat.lt_trans ih (D.parent_lt hparent)

/-- The complete-history DAG: stage `i` observes every earlier stage. -/
def complete (n : Nat) : DecisionDAG n where
  parents i := Finset.univ.filter fun j => j.val < i.val
  parent_lt hij := (Finset.mem_filter.mp hij).2

/-- The edgeless DAG presents simultaneous decisions in natural numbering. -/
def discrete (n : Nat) : DecisionDAG n where
  parents _ := ∅
  parent_lt h := by simp at h

end DecisionDAG

namespace ShapeDAG

variable {n : Nat}

/-- The typed action configuration observed at decision `i`. -/
abbrev History (D : DecisionDAG n) (A : Fin n → Type) (i : Fin n) :=
  ∀ parent : ↥(D.parents i), A parent.val

/-- One parent-contingent plan per decision node. -/
abbrev Strategy (D : DecisionDAG n) (A : Fin n → Type) :=
  ∀ i, History D A i → A i

/-- Realize one node by recursively realizing exactly its informational
parents. -/
def realizeAt (D : DecisionDAG n) {A : Fin n → Type}
    (σ : Strategy D A) (i : Fin n) : A i :=
  σ i fun parent => realizeAt D σ parent.val
termination_by i.val
decreasing_by exact D.parent_lt parent.property

/-- Realize the complete typed action assignment. -/
def realize (D : DecisionDAG n) {A : Fin n → Type}
    (σ : Strategy D A) : ∀ i, A i :=
  fun i => realizeAt D σ i

/-- Realization unfolds to the plan selected at the realized parent
configuration. -/
theorem realize_eq (D : DecisionDAG n) {A : Fin n → Type}
    (σ : Strategy D A) (i : Fin n) :
    realize D σ i = σ i (fun parent => realize D σ parent.val) := by
  change realizeAt D σ i = σ i (fun parent => realizeAt D σ parent.val)
  rw [realizeAt]

/-- Replacing a later-numbered plan cannot alter an earlier node. -/
theorem realizeAt_update_of_lt (D : DecisionDAG n) {A : Fin n → Type}
    (σ : Strategy D A) (i : Fin n) (deviation : History D A i → A i)
    (j : Fin n) (hji : j.val < i.val) :
    realizeAt D (Function.update σ i deviation) j = realizeAt D σ j := by
  rw [realizeAt, realizeAt]
  have hne : j ≠ i := by intro h; subst h; omega
  rw [Function.update_of_ne hne]
  congr 1
  funext parent
  exact realizeAt_update_of_lt D σ i deviation parent.val
    (Nat.lt_trans (D.parent_lt parent.property) hji)
termination_by j.val
decreasing_by exact D.parent_lt parent.property

/-- A plan replacement is causally irrelevant outside that node's strict
descendant cone (and outside the node itself). -/
theorem realizeAt_update_of_not_ancestor (D : DecisionDAG n)
    {A : Fin n → Type} (σ : Strategy D A) (i : Fin n)
    (deviation : History D A i → A i) (j : Fin n)
    (hne : j ≠ i) (hnot : ¬ D.IsAncestor i j) :
    realizeAt D (Function.update σ i deviation) j = realizeAt D σ j := by
  rw [realizeAt, realizeAt, Function.update_of_ne hne]
  congr 1
  funext parent
  have hip : parent.val ≠ i := by
    intro heq
    subst i
    exact hnot (.single parent.property)
  have hparent : ¬ D.IsAncestor i parent.val := by
    intro hancestor
    exact hnot (hancestor.tail parent.property)
  exact realizeAt_update_of_not_ancestor D σ i deviation parent.val
    hip hparent
termination_by j.val
decreasing_by exact D.parent_lt parent.property

/-- The action-level strategic game induced by a closing continuation. -/
def actionNFG (D : DecisionDAG n) (A : Fin n → Type)
    (k : (∀ i, A i) → Fin n → ℝ) :
    NFG.NFGGame (Fin n) (fun i => History D A i → A i) where
  Outcome := ∀ i, A i
  outcome := realize D
  utility := k

/-- Compile the sparse decision DAG through the existing NFG kernel bridge. -/
noncomputable def compileAction (D : DecisionDAG n) (A : Fin n → Type)
    (k : (∀ i, A i) → Fin n → ℝ) : GameTheory.KernelGame (Fin n) :=
  (actionNFG D A k).toKernelGame

end ShapeDAG

/-- The open-game shape generated by a sparse typed decision DAG. -/
def ShapeDAG {n : Nat} (D : DecisionDAG n) (A : Fin n → Type) :
    OpenGame Unit Unit (∀ i, A i) (Fin n → ℝ) where
  Strategy := ShapeDAG.Strategy D A
  play σ _ := ShapeDAG.realize D σ
  coplay _ _ _ := ()
  IsEquilibriumIn _ k σ :=
    ∀ i (deviation : ShapeDAG.History D A i → A i),
      k (ShapeDAG.realize D (Function.update σ i deviation)) i ≤
        k (ShapeDAG.realize D σ) i

namespace ShapeDAG

/-- Plain sparse-DAG equilibrium is exactly pure Nash in its induced
strategic form. -/
theorem isEquilibriumIn_iff_isNashPure {n : Nat}
    (D : DecisionDAG n) (A : Fin n → Type)
    (k : (∀ i, A i) → Fin n → ℝ) (σ : Strategy D A) :
    (OpenGames.ShapeDAG D A).IsEquilibriumIn () k σ ↔
      NFG.IsNashPure (actionNFG D A k) σ := by
  rfl

/-- Kernel-level correctness for sparse typed decision DAGs. -/
theorem isEquilibriumIn_iff_isNash {n : Nat}
    (D : DecisionDAG n) (A : Fin n → Type)
    (k : (∀ i, A i) → Fin n → ℝ) (σ : Strategy D A) :
    (OpenGames.ShapeDAG D A).IsEquilibriumIn () k σ ↔
      (compileAction D A k).IsNash σ := by
  rw [isEquilibriumIn_iff_isNashPure]
  exact NFG.IsNashPure_iff_kernelGame (actionNFG D A k) σ

end ShapeDAG

end OpenGames
