/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/

import GameTheory.Languages.OpenGame.Sequential

/-!
# Sparse Typed Decision DAG Open Games

`DecisionDAG n` presents a finite decision DAG in a certified natural
topological order.  Node `i` may observe only the typed actions at
`parents i`; the proof `parent_lt` makes recursive realization well founded.

This is the sparse-parent generalization of `ShapeSeqDep`: strategies remain
contingent plans, realization follows the causal graph, and the plain
equilibrium predicate still compiles exactly to pure strategic-form Nash.
The graph-local irrelevance theorem makes the intended Bayesian-network/MAID
reading explicit: changing a plan cannot affect a node outside its descendant
cone.
-/

namespace OpenGames

/-- A finite decision DAG whose node numbering is a topological order. -/
structure DecisionDAG (n : Nat) where
  parents : Fin n → Finset (Fin n)
  parent_lt : ∀ {i j : Fin n}, j ∈ parents i → j.val < i.val

namespace DecisionDAG

variable {n : Nat}

/-- The edge relation points from an informational parent to its child. -/
def Edge (D : DecisionDAG n) (parent child : Fin n) : Prop :=
  parent ∈ D.parents child

/-- Strict causal ancestry generated by the parent relation. -/
abbrev IsAncestor (D : DecisionDAG n) : Fin n → Fin n → Prop :=
  Relation.TransGen D.Edge

/-- A causal ancestor has a strictly smaller topological index. -/
theorem ancestor_lt (D : DecisionDAG n) {i j : Fin n}
    (h : D.IsAncestor i j) : i.val < j.val := by
  induction h with
  | single hparent => exact D.parent_lt hparent
  | tail _ hparent ih => exact Nat.lt_trans ih (D.parent_lt hparent)

/-- The complete-history DAG: stage `i` observes every earlier stage. -/
def complete (n : Nat) : DecisionDAG n where
  parents i := Finset.univ.filter fun j => j.val < i.val
  parent_lt hij := (Finset.mem_filter.mp hij).2

/-- The edgeless DAG presents simultaneous decisions in natural numbering. -/
def discrete (n : Nat) : DecisionDAG n where
  parents _ := ∅
  parent_lt h := by simp at h

/-- In the complete DAG, strict causal ancestry is exactly the natural
topological order. -/
theorem complete_isAncestor_iff {i j : Fin n} :
    (complete n).IsAncestor i j ↔ i.val < j.val := by
  constructor
  · exact (complete n).ancestor_lt
  · intro hij
    apply Relation.TransGen.single
    simp only [Edge, complete, Finset.mem_filter, Finset.mem_univ, true_and]
    exact hij

/-- The discrete DAG has no strict causal ancestors. -/
theorem discrete_not_isAncestor (i j : Fin n) :
    ¬(discrete n).IsAncestor i j := by
  intro h
  induction h with
  | single hedge => simp [Edge, discrete] at hedge
  | tail _ _ ih => exact ih

end DecisionDAG

namespace ShapeDAG

variable {n : Nat}

/-- The typed action configuration observed at decision `i`. -/
abbrev History (D : DecisionDAG n) (A : Fin n → Type) (i : Fin n) :=
  ∀ parent : ↥(D.parents i), A parent.val

/-- One parent-contingent plan per decision node. -/
abbrev Strategy (D : DecisionDAG n) (A : Fin n → Type) :=
  ∀ i, History D A i → A i

/-- Realize one node by recursively realizing exactly its informational
parents. -/
def realizeAt (D : DecisionDAG n) {A : Fin n → Type}
    (σ : Strategy D A) (i : Fin n) : A i :=
  σ i fun parent => realizeAt D σ parent.val
termination_by i.val
decreasing_by exact D.parent_lt parent.property

/-- Realize the complete typed action assignment. -/
def realize (D : DecisionDAG n) {A : Fin n → Type}
    (σ : Strategy D A) : ∀ i, A i :=
  fun i => realizeAt D σ i

/-- Realization unfolds to the plan selected at the realized parent
configuration. -/
theorem realize_eq (D : DecisionDAG n) {A : Fin n → Type}
    (σ : Strategy D A) (i : Fin n) :
    realize D σ i = σ i (fun parent => realize D σ parent.val) := by
  change realizeAt D σ i = σ i (fun parent => realizeAt D σ parent.val)
  rw [realizeAt]

/-- Replacing a later-numbered plan cannot alter an earlier node. -/
theorem realizeAt_update_of_lt (D : DecisionDAG n) {A : Fin n → Type}
    (σ : Strategy D A) (i : Fin n) (deviation : History D A i → A i)
    (j : Fin n) (hji : j.val < i.val) :
    realizeAt D (Function.update σ i deviation) j = realizeAt D σ j := by
  rw [realizeAt, realizeAt]
  have hne : j ≠ i := by intro h; subst h; omega
  rw [Function.update_of_ne hne]
  congr 1
  funext parent
  exact realizeAt_update_of_lt D σ i deviation parent.val
    (Nat.lt_trans (D.parent_lt parent.property) hji)
termination_by j.val
decreasing_by exact D.parent_lt parent.property

/-- A plan replacement is causally irrelevant outside that node's strict
descendant cone (and outside the node itself). -/
theorem realizeAt_update_of_not_ancestor (D : DecisionDAG n)
    {A : Fin n → Type} (σ : Strategy D A) (i : Fin n)
    (deviation : History D A i → A i) (j : Fin n)
    (hne : j ≠ i) (hnot : ¬ D.IsAncestor i j) :
    realizeAt D (Function.update σ i deviation) j = realizeAt D σ j := by
  rw [realizeAt, realizeAt, Function.update_of_ne hne]
  congr 1
  funext parent
  have hip : parent.val ≠ i := by
    intro heq
    subst i
    exact hnot (.single parent.property)
  have hparent : ¬ D.IsAncestor i parent.val := by
    intro hancestor
    exact hnot (hancestor.tail parent.property)
  exact realizeAt_update_of_not_ancestor D σ i deviation parent.val
    hip hparent
termination_by j.val
decreasing_by exact D.parent_lt parent.property

/-- Coordinatewise off-path irrelevance: two replacements at the same node
produce the same realization when they choose the same action at the parent
configuration reached by the original profile. -/
theorem realizeAt_updates_eq_of_eq_at_reached_history (D : DecisionDAG n)
    {A : Fin n → Type} (σ : Strategy D A) (i : Fin n)
    (deviation deviation' : History D A i → A i)
    (hdev : deviation (fun parent => realize D σ parent.val) =
      deviation' (fun parent => realize D σ parent.val)) (j : Fin n) :
    realizeAt D (Function.update σ i deviation) j =
      realizeAt D (Function.update σ i deviation') j := by
  rw [realizeAt, realizeAt]
  by_cases hji : j = i
  · subst j
    simp only [Function.update_self]
    have hparents : (fun parent : ↥(D.parents i) =>
        realizeAt D (Function.update σ i deviation) parent.val) =
        fun parent : ↥(D.parents i) => realize D σ parent.val := by
      funext parent
      exact realizeAt_update_of_lt D σ i deviation parent.val
        (D.parent_lt parent.property)
    have hparents' : (fun parent : ↥(D.parents i) =>
        realizeAt D (Function.update σ i deviation') parent.val) =
        fun parent : ↥(D.parents i) => realize D σ parent.val := by
      funext parent
      exact realizeAt_update_of_lt D σ i deviation' parent.val
        (D.parent_lt parent.property)
    rw [hparents, hparents', hdev]
  · rw [Function.update_of_ne hji, Function.update_of_ne hji]
    congr 1
    funext parent
    exact realizeAt_updates_eq_of_eq_at_reached_history D σ i deviation
      deviation' hdev parent.val
termination_by j.val
decreasing_by exact D.parent_lt parent.property

/-- Function-level off-path irrelevance for a sparse decision DAG. -/
theorem realize_update_eq_of_eq_at_reached_history (D : DecisionDAG n)
    {A : Fin n → Type} (σ : Strategy D A) (i : Fin n)
    (deviation deviation' : History D A i → A i)
    (hdev : deviation (fun parent => realize D σ parent.val) =
      deviation' (fun parent => realize D σ parent.val)) :
    realize D (Function.update σ i deviation) =
      realize D (Function.update σ i deviation') := by
  funext j
  exact realizeAt_updates_eq_of_eq_at_reached_history D σ i deviation
    deviation' hdev j

/-! ## Discrete specialization -/

/-- An edgeless decision node has exactly one parent configuration. -/
def discreteHistoryEquiv (A : Fin n → Type) (i : Fin n) :
    History (DecisionDAG.discrete n) A i ≃ Unit where
  toFun _ := ()
  invFun _ parent := by
    have hp : parent.val ∈ (∅ : Finset (Fin n)) := by
      rw [← show (DecisionDAG.discrete n).parents i = ∅ from rfl]
      exact parent.property
    exact (Finset.notMem_empty parent.val hp).elim
  left_inv history := by
    funext parent
    have hp : parent.val ∈ (∅ : Finset (Fin n)) := by
      rw [← show (DecisionDAG.discrete n).parents i = ∅ from rfl]
      exact parent.property
    exact (Finset.notMem_empty parent.val hp).elim
  right_inv _ := rfl

/-- A singleton boundary is equivalent to a Π-shaped boundary of singleton
components. -/
def unitPiEquiv (ι : Type) : Unit ≃ (ι → Unit) where
  toFun _ _ := ()
  invFun _ := ()
  left_inv _ := rfl
  right_inv f := by
    funext i
    exact Subsingleton.elim _ _

/-- Strategies on an edgeless decision DAG are precisely closed simultaneous
contingent strategies. -/
def discreteStrategyEquiv (A : Fin n → Type) :
    Strategy (DecisionDAG.discrete n) A ≃ (∀ i, Unit → A i) where
  toFun σ i u := σ i ((discreteHistoryEquiv A i).symm u)
  invFun τ i history := τ i (discreteHistoryEquiv A i history)
  left_inv σ := by
    funext i history
    change σ i ((discreteHistoryEquiv A i).symm
      (discreteHistoryEquiv A i history)) = σ i history
    rw [(discreteHistoryEquiv A i).symm_apply_apply]
  right_inv τ := by
    funext i u
    change τ i (discreteHistoryEquiv A i
      ((discreteHistoryEquiv A i).symm u)) = τ i u
    rw [(discreteHistoryEquiv A i).apply_symm_apply]

/-- With no parent edges, realization at a node is evaluation at its unique
empty history. -/
theorem realize_discrete (A : Fin n → Type)
    (σ : Strategy (DecisionDAG.discrete n) A) (i : Fin n) :
    realize (DecisionDAG.discrete n) σ i =
      (discreteStrategyEquiv A σ) i () := by
  rw [realize_eq]
  change σ i (fun parent =>
      realize (DecisionDAG.discrete n) σ parent.val) =
    σ i ((discreteHistoryEquiv A i).symm ())
  congr 1
  apply (discreteHistoryEquiv A i).injective
  rfl

/-- On a discrete DAG, changing one contingent plan changes exactly the
corresponding realized action. -/
theorem realize_update_discrete (A : Fin n → Type)
    (σ : Strategy (DecisionDAG.discrete n) A) (i : Fin n)
    (deviation : History (DecisionDAG.discrete n) A i → A i) :
    realize (DecisionDAG.discrete n) (Function.update σ i deviation) =
      Function.update (realize (DecisionDAG.discrete n) σ) i
        (deviation ((discreteHistoryEquiv A i).symm ())) := by
  funext j
  by_cases hji : j = i
  · subst j
    rw [realize_discrete]
    simp [discreteStrategyEquiv, Function.update_self]
  · rw [realize_discrete, Function.update_of_ne hji, realize_discrete]
    simp [discreteStrategyEquiv, Function.update_of_ne hji]

/-- Encoding a discrete-DAG strategy as a closed simultaneous strategy
preserves its realized action profile. -/
theorem realize_discreteStrategyEquiv (A : Fin n → Type)
    (σ : Strategy (DecisionDAG.discrete n) A) :
    ShapeN.realize (fun _ => ()) (discreteStrategyEquiv A σ) =
      realize (DecisionDAG.discrete n) σ := by
  funext i
  exact (realize_discrete A σ i).symm

/-! ## Complete-history specialization -/

/-- Parents of `DecisionDAG.complete` at stage `i` are exactly the indices in
the strict prefix `Fin i.val`. -/
def completeParentEquiv (i : Fin n) :
    ↥((DecisionDAG.complete n).parents i) ≃ Fin i.val where
  toFun parent := ⟨parent.val.val, by
    have hp := parent.property
    simpa only [DecisionDAG.complete, Finset.mem_filter,
      Finset.mem_univ, true_and] using hp⟩
  invFun j := ⟨ShapeSeqDep.priorIndex i j, by
    simp only [DecisionDAG.complete, Finset.mem_filter,
      Finset.mem_univ, true_and]
    exact j.isLt⟩
  left_inv parent := by
    apply Subtype.ext
    apply Fin.ext
    rfl
  right_inv j := by
    apply Fin.ext
    rfl

/-- The action type at a complete-DAG parent is the corresponding dependent
prefix action type. -/
def completeParentValueEquiv (A : Fin n → Type) (i : Fin n)
    (parent : ↥((DecisionDAG.complete n).parents i)) :
    A parent.val ≃
      A (ShapeSeqDep.priorIndex i (completeParentEquiv i parent)) := by
  apply Equiv.cast
  congr 1

/-- Complete-DAG parent configurations are exactly the dependent histories
of `ShapeSeqDep`. -/
def completeHistoryEquiv (A : Fin n → Type) (i : Fin n) :
    History (DecisionDAG.complete n) A i ≃ ShapeSeqDep.History A i :=
  Equiv.piCongr (completeParentEquiv i) (completeParentValueEquiv A i)

/-- A complete-DAG contingent profile is exactly a `ShapeSeqDep` contingent
profile. -/
def completeStrategyEquiv (A : Fin n → Type) :
    Strategy (DecisionDAG.complete n) A ≃ ShapeSeqDep.Strategy A where
  toFun σ i h := σ i ((completeHistoryEquiv A i).symm h)
  invFun τ i h := τ i (completeHistoryEquiv A i h)
  left_inv σ := by
    funext i h
    change σ i ((completeHistoryEquiv A i).symm
      (completeHistoryEquiv A i h)) = σ i h
    rw [(completeHistoryEquiv A i).symm_apply_apply]
  right_inv τ := by
    funext i h
    change τ i (completeHistoryEquiv A i
      ((completeHistoryEquiv A i).symm h)) = τ i h
    rw [(completeHistoryEquiv A i).apply_symm_apply]

/-- Encoding a complete-DAG strategy as a sequential dependent strategy
preserves its realized typed action path. -/
theorem realize_completeStrategyEquiv (A : Fin n → Type)
    (σ : Strategy (DecisionDAG.complete n) A) :
    ShapeSeqDep.realize (completeStrategyEquiv A σ) =
      realize (DecisionDAG.complete n) σ := by
  funext i
  induction hi : i.val using Nat.strongRecOn generalizing i with
  | _ d ih =>
      rw [ShapeSeqDep.realize_eq, realize_eq]
      change σ i ((completeHistoryEquiv A i).symm
          (fun j => ShapeSeqDep.realize (completeStrategyEquiv A σ)
            (ShapeSeqDep.priorIndex i j))) =
        σ i (fun parent => realize (DecisionDAG.complete n) σ parent.val)
      congr 1
      apply (completeHistoryEquiv A i).injective
      rw [(completeHistoryEquiv A i).apply_symm_apply]
      funext j
      let parent := (completeParentEquiv i).symm j
      have hpi := Equiv.piCongr_apply_apply
        (W := fun parent : ↥((DecisionDAG.complete n).parents i) => A parent.val)
        (Z := fun q : Fin i.val => A (ShapeSeqDep.priorIndex i q))
        (completeParentEquiv i) (completeParentValueEquiv A i)
        (fun parent => realize (DecisionDAG.complete n) σ parent.val) parent
      have hj := (completeParentEquiv i).apply_symm_apply j
      change completeParentEquiv i parent = j at hj
      cases hj
      apply eq_of_heq
      exact ((heq_of_eq hpi).trans (heq_of_eq (ih parent.val.val (by
        have hp := (DecisionDAG.complete n).parent_lt parent.property
        simpa [hi] using hp) parent.val rfl).symm)).symm

/-- Decoding a dependent sequential profile into the complete DAG also
preserves realization. -/
theorem realize_completeStrategyEquiv_symm (A : Fin n → Type)
    (σ : ShapeSeqDep.Strategy A) :
    realize (DecisionDAG.complete n) ((completeStrategyEquiv A).symm σ) =
      ShapeSeqDep.realize σ := by
  have h := realize_completeStrategyEquiv A ((completeStrategyEquiv A).symm σ)
  rw [(completeStrategyEquiv A).apply_symm_apply] at h
  exact h.symm

/-- The complete-history strategy equivalence transports a one-node plan
replacement to the corresponding dependent sequential replacement. -/
theorem completeStrategyEquiv_update (A : Fin n → Type)
    (σ : Strategy (DecisionDAG.complete n) A) (i : Fin n)
    (deviation : History (DecisionDAG.complete n) A i → A i) :
    completeStrategyEquiv A (Function.update σ i deviation) =
      Function.update (completeStrategyEquiv A σ) i
        (fun history => deviation ((completeHistoryEquiv A i).symm history)) := by
  funext j history
  by_cases hji : j = i
  · subst j
    simp [completeStrategyEquiv]
  · simp [completeStrategyEquiv, Function.update_of_ne hji]

/-- The action-level strategic game induced by a closing continuation. -/
def actionNFG (D : DecisionDAG n) (A : Fin n → Type)
    (k : (∀ i, A i) → Fin n → ℝ) :
    NFG.NFGGame (Fin n) (fun i => History D A i → A i) where
  Outcome := ∀ i, A i
  outcome := realize D
  utility := k

/-- Compile the sparse decision DAG through the existing NFG kernel bridge. -/
noncomputable def compileAction (D : DecisionDAG n) (A : Fin n → Type)
    (k : (∀ i, A i) → Fin n → ℝ) : GameTheory.KernelGame (Fin n) :=
  (actionNFG D A k).toKernelGame

end ShapeDAG

/-- The open-game shape generated by a sparse typed decision DAG. -/
def ShapeDAG {n : Nat} (D : DecisionDAG n) (A : Fin n → Type) :
    OpenGame Unit Unit (∀ i, A i) (Fin n → ℝ) where
  Strategy := ShapeDAG.Strategy D A
  play σ _ := ShapeDAG.realize D σ
  coplay _ _ _ := ()
  IsEquilibriumIn _ k σ :=
    ∀ i (deviation : ShapeDAG.History D A i → A i),
      k (ShapeDAG.realize D (Function.update σ i deviation)) i ≤
        k (ShapeDAG.realize D σ) i

namespace ShapeDAG

/-- Plain sparse-DAG equilibrium is exactly pure Nash in its induced
strategic form. -/
theorem isEquilibriumIn_iff_isNashPure {n : Nat}
    (D : DecisionDAG n) (A : Fin n → Type)
    (k : (∀ i, A i) → Fin n → ℝ) (σ : Strategy D A) :
    (OpenGames.ShapeDAG D A).IsEquilibriumIn () k σ ↔
      NFG.IsNashPure (actionNFG D A k) σ := by
  rfl

/-- Kernel-level correctness for sparse typed decision DAGs. -/
theorem isEquilibriumIn_iff_isNash {n : Nat}
    (D : DecisionDAG n) (A : Fin n → Type)
    (k : (∀ i, A i) → Fin n → ℝ) (σ : Strategy D A) :
    (OpenGames.ShapeDAG D A).IsEquilibriumIn () k σ ↔
      (compileAction D A k).IsNash σ := by
  rw [isEquilibriumIn_iff_isNashPure]
  exact NFG.IsNashPure_iff_kernelGame (actionNFG D A k) σ

/-! ## Conditioning along causal ancestry -/

/-- A counterfactual profile for node `i` may alter plans only at strict
causal ancestors of `i`. Plans at `i`, its descendants, and unrelated nodes
remain those of the reference profile.

This is the conservative, observable-history reading of sparse conditioning:
only decisions that can causally affect `i` generate histories tested at `i`.
One could instead allow every non-descendant to vary. That agrees with this
definition on complete DAGs but is generally stronger on sparse DAGs, because
an unrelated decision can change realized play and utility without changing
`i`'s observed parent history. -/
def AgreesOutsideAncestors {n : Nat} {A : Fin n → Type}
    (D : DecisionDAG n) (σ τ : Strategy D A) (i : Fin n) : Prop :=
  ∀ j, ¬D.IsAncestor j i → τ j = σ j

/-- Graph-conditioned equilibrium tests a node at every causally generated
counterfactual predecessor profile while retaining all non-ancestor plans.

This is deliberately not named subgame perfection: for sparse information
graphs, MAID/EFG refinement requires additional information-set and belief
hypotheses. -/
def IsConditionedEquilibrium {n : Nat} {A : Fin n → Type}
    (D : DecisionDAG n) (k : (∀ i, A i) → Fin n → ℝ)
    (σ : Strategy D A) : Prop :=
  ∀ (i : Fin n) (τ : Strategy D A), AgreesOutsideAncestors D σ τ i →
    ∀ deviation : History D A i → A i,
      k (realize D (Function.update τ i deviation)) i ≤ k (realize D τ) i

/-- One-shot form of graph-conditioned equilibrium: only the action selected
at the reached parent configuration matters. -/
def IsOneShotConditionedEquilibrium {n : Nat} {A : Fin n → Type}
    (D : DecisionDAG n) (k : (∀ i, A i) → Fin n → ℝ)
    (σ : Strategy D A) : Prop :=
  ∀ (i : Fin n) (τ : Strategy D A), AgreesOutsideAncestors D σ τ i →
    ∀ action : A i,
      k (realize D (Function.update τ i (fun _ => action))) i ≤
        k (realize D τ) i

/-- Arbitrary contingent plan replacements and literal one-action changes are
equivalent at each graph-conditioned counterfactual. -/
theorem isConditionedEquilibrium_iff_isOneShot {n : Nat}
    {A : Fin n → Type} (D : DecisionDAG n)
    (k : (∀ i, A i) → Fin n → ℝ) (σ : Strategy D A) :
    IsConditionedEquilibrium D k σ ↔
      IsOneShotConditionedEquilibrium D k σ := by
  constructor
  · intro h i τ hagree action
    exact h i τ hagree (fun _ => action)
  · intro h i τ hagree deviation
    let history : History D A i := fun parent => realize D τ parent.val
    have hone := h i τ hagree (deviation history)
    have hrealize : realize D (Function.update τ i deviation) =
        realize D (Function.update τ i (fun _ => deviation history)) := by
      apply realize_update_eq_of_eq_at_reached_history
      rfl
    rw [hrealize]
    exact hone

/-- The sparse-DAG shape conditioned along strict causal ancestry. It retains
the same boundaries, strategies, and play as the plain DAG shape. -/
def conditioned {n : Nat} (D : DecisionDAG n) (A : Fin n → Type) :
    OpenGame Unit Unit (∀ i, A i) (Fin n → ℝ) where
  Strategy := Strategy D A
  play σ _ := realize D σ
  coplay _ _ _ := ()
  IsEquilibriumIn _ k σ := IsConditionedEquilibrium D k σ

/-- Graph conditioning strengthens plain agent-form equilibrium. -/
theorem conditioned_implies_plain {n : Nat} {A : Fin n → Type}
    (D : DecisionDAG n) (k : (∀ i, A i) → Fin n → ℝ)
    (σ : Strategy D A)
    (hσ : (conditioned D A).IsEquilibriumIn () k σ) :
    (OpenGames.ShapeDAG D A).IsEquilibriumIn () k σ := by
  intro i deviation
  exact hσ i σ (fun _ _ => rfl) deviation

/-- On an edgeless DAG there are no causal counterfactual predecessors, so
graph conditioning is exactly ordinary simultaneous equilibrium. -/
theorem conditioned_discrete_iff_plain {n : Nat} {A : Fin n → Type}
    (k : (∀ i, A i) → Fin n → ℝ)
    (σ : Strategy (DecisionDAG.discrete n) A) :
    (conditioned (DecisionDAG.discrete n) A).IsEquilibriumIn () k σ ↔
      (OpenGames.ShapeDAG (DecisionDAG.discrete n) A).IsEquilibriumIn () k σ := by
  constructor
  · exact conditioned_implies_plain (DecisionDAG.discrete n) k σ
  · intro hplain i τ hagree deviation
    have htau : τ = σ := by
      funext j
      exact hagree j (DecisionDAG.discrete_not_isAncestor j i)
    subst τ
    exact hplain i deviation

/-- For the complete DAG, agreeing outside the ancestors of `i` is exactly
agreeing from the natural-number cut `i` onward. -/
theorem complete_agreesOutsideAncestors_iff {n : Nat} {A : Fin n → Type}
    (σ τ : Strategy (DecisionDAG.complete n) A) (i : Fin n) :
    AgreesOutsideAncestors (DecisionDAG.complete n) σ τ i ↔
      ∀ j, i.val ≤ j.val → τ j = σ j := by
  constructor
  · intro hagree j hij
    apply hagree j
    intro hancestor
    exact (Nat.not_lt_of_ge hij)
      (DecisionDAG.complete_isAncestor_iff.mp hancestor)
  · intro hagree j hnot
    apply hagree j
    apply Nat.le_of_not_gt
    intro hji
    exact hnot (DecisionDAG.complete_isAncestor_iff.mpr hji)

/-- Causal conditioning on the complete DAG is exactly the established
prefix-conditioned equilibrium of `ShapeSeqDep`. -/
theorem conditioned_complete_iff_sequential {n : Nat} (A : Fin n → Type)
    (k : (∀ i, A i) → Fin n → ℝ)
    (σ : Strategy (DecisionDAG.complete n) A) :
    (conditioned (DecisionDAG.complete n) A).IsEquilibriumIn () k σ ↔
      (ShapeSeqDep.conditioned A).IsEquilibriumIn () k
        (completeStrategyEquiv A σ) := by
  change IsConditionedEquilibrium (DecisionDAG.complete n) k σ ↔
    ShapeSeqDep.IsConditionedEquilibrium k (completeStrategyEquiv A σ)
  constructor
  · intro hdag i τseq hagree deviation
    let τdag := (completeStrategyEquiv A).symm τseq
    have hτagree : AgreesOutsideAncestors (DecisionDAG.complete n) σ τdag i := by
      rw [complete_agreesOutsideAncestors_iff]
      intro j hij
      funext history
      change τseq j (completeHistoryEquiv A j history) = σ j history
      rw [hagree j hij]
      simp [completeStrategyEquiv]
    let dagDeviation : History (DecisionDAG.complete n) A i → A i :=
      fun history => deviation (completeHistoryEquiv A i history)
    have hineq := hdag i τdag hτagree dagDeviation
    have hbase : realize (DecisionDAG.complete n) τdag =
        ShapeSeqDep.realize τseq := by
      exact realize_completeStrategyEquiv_symm A τseq
    have hupdate : completeStrategyEquiv A
        (Function.update τdag i dagDeviation) =
        Function.update τseq i deviation := by
      funext j history
      by_cases hji : j = i
      · subst j
        simp [completeStrategyEquiv, τdag, dagDeviation]
      · simp [completeStrategyEquiv, τdag, dagDeviation,
          Function.update_of_ne hji]
    have hchanged : realize (DecisionDAG.complete n)
        (Function.update τdag i dagDeviation) =
        ShapeSeqDep.realize (Function.update τseq i deviation) :=
      (realize_completeStrategyEquiv A
        (Function.update τdag i dagDeviation)).symm.trans
          (congrArg ShapeSeqDep.realize hupdate)
    calc
      k (ShapeSeqDep.realize (Function.update τseq i deviation)) i =
          k (realize (DecisionDAG.complete n)
            (Function.update τdag i dagDeviation)) i :=
        congrArg (fun path => k path i) hchanged.symm
      _ ≤ k (realize (DecisionDAG.complete n) τdag) i := hineq
      _ = k (ShapeSeqDep.realize τseq) i :=
        congrArg (fun path => k path i) hbase
  · intro hseq i τdag hagree deviation
    let τseq := completeStrategyEquiv A τdag
    have hτagree : ∀ j, i.val ≤ j.val →
        τseq j = completeStrategyEquiv A σ j := by
      intro j hij
      have houtside : ¬(DecisionDAG.complete n).IsAncestor j i := by
        intro hancestor
        exact (Nat.not_lt_of_ge hij)
          (DecisionDAG.complete_isAncestor_iff.mp hancestor)
      have hj := hagree j houtside
      funext history
      change τdag j ((completeHistoryEquiv A j).symm history) =
        σ j ((completeHistoryEquiv A j).symm history)
      rw [hj]
    let seqDeviation : ShapeSeqDep.History A i → A i :=
      fun history => deviation ((completeHistoryEquiv A i).symm history)
    have hineq := hseq i τseq hτagree seqDeviation
    have hbase : ShapeSeqDep.realize τseq =
        realize (DecisionDAG.complete n) τdag :=
      realize_completeStrategyEquiv A τdag
    have hupdate : completeStrategyEquiv A
        (Function.update τdag i deviation) =
        Function.update τseq i seqDeviation := by
      exact completeStrategyEquiv_update A τdag i deviation
    have hchanged : ShapeSeqDep.realize
        (Function.update τseq i seqDeviation) =
        realize (DecisionDAG.complete n)
          (Function.update τdag i deviation) :=
      (congrArg ShapeSeqDep.realize hupdate.symm).trans
        (realize_completeStrategyEquiv A
          (Function.update τdag i deviation))
    calc
      k (realize (DecisionDAG.complete n)
          (Function.update τdag i deviation)) i =
          k (ShapeSeqDep.realize
            (Function.update τseq i seqDeviation)) i :=
        congrArg (fun path => k path i) hchanged.symm
      _ ≤ k (ShapeSeqDep.realize τseq) i := hineq
      _ = k (realize (DecisionDAG.complete n) τdag) i :=
        congrArg (fun path => k path i) hbase

/-- The edgeless decision DAG is the closed simultaneous shape, up to the
contractible Π-shaped input and cooutcome boundaries. -/
def discreteIso {n : Nat} (A : Fin n → Type) :
    OpenGameIso (OpenGames.ShapeDAG (DecisionDAG.discrete n) A)
      (ShapeN (fun _ : Fin n => Unit) A) where
  eX := unitPiEquiv (Fin n)
  eS := unitPiEquiv (Fin n)
  eY := Equiv.refl _
  eR := Equiv.refl _
  stratEquiv := discreteStrategyEquiv A
  play_preserved := by
    intro σ x
    cases x
    exact realize_discreteStrategyEquiv A σ
  coplay_preserved := by
    intro σ x r
    cases x
    rfl
  equilibrium_preserved := by
    intro x k σ
    cases x
    change (∀ i (action : A i),
        k (Function.update
          (ShapeN.realize (fun _ : Fin n => ())
            (discreteStrategyEquiv A σ)) i action) i ≤
          k (ShapeN.realize (fun _ : Fin n => ())
            (discreteStrategyEquiv A σ)) i) ↔
      ∀ i (deviation : History (DecisionDAG.discrete n) A i → A i),
        k (realize (DecisionDAG.discrete n)
          (Function.update σ i deviation)) i ≤
        k (realize (DecisionDAG.discrete n) σ) i
    rw [realize_discreteStrategyEquiv A σ]
    constructor
    · intro hsim i deviation
      rw [realize_update_discrete]
      exact hsim i (deviation ((discreteHistoryEquiv A i).symm ()))
    · intro hdag i action
      let deviation : History (DecisionDAG.discrete n) A i → A i :=
        fun _ => action
      have h := hdag i deviation
      rw [realize_update_discrete] at h
      exact h

/-- Conditioning the discrete DAG still yields the closed simultaneous shape:
there are no strict ancestors over which to range counterfactual profiles. -/
def discreteConditionedIso {n : Nat} (A : Fin n → Type) :
    OpenGameIso
      (conditioned (DecisionDAG.discrete n) A)
      (ShapeN (fun _ : Fin n => Unit) A) where
  eX := unitPiEquiv (Fin n)
  eS := unitPiEquiv (Fin n)
  eY := Equiv.refl _
  eR := Equiv.refl _
  stratEquiv := discreteStrategyEquiv A
  play_preserved := by
    intro σ x
    cases x
    exact realize_discreteStrategyEquiv A σ
  coplay_preserved := by
    intro σ x r
    cases x
    rfl
  equilibrium_preserved := by
    intro x k σ
    have hplain := (discreteIso A).equilibrium_preserved x k σ
    exact hplain.trans (conditioned_discrete_iff_plain k σ).symm

/-- The complete-parent decision DAG recovers `ShapeSeqDep` up to the explicit
dependent-history strategy equivalence. -/
def completeIso {n : Nat} (A : Fin n → Type) :
    OpenGameIso (OpenGames.ShapeDAG (DecisionDAG.complete n) A)
      (OpenGames.ShapeSeqDep A) where
  eX := Equiv.refl _
  eS := Equiv.refl _
  eY := Equiv.refl _
  eR := Equiv.refl _
  stratEquiv := completeStrategyEquiv A
  play_preserved := by
    intro σ x
    cases x
    exact realize_completeStrategyEquiv A σ
  coplay_preserved := by
    intro σ x r
    cases x
    rfl
  equilibrium_preserved := by
    intro x k σ
    cases x
    constructor
    · intro hseq i deviation
      let seqDeviation : ShapeSeqDep.History A i → A i :=
        fun history => deviation ((completeHistoryEquiv A i).symm history)
      have hineq := hseq i seqDeviation
      have hupdate : Function.update (completeStrategyEquiv A σ) i seqDeviation =
          completeStrategyEquiv A (Function.update σ i deviation) := by
        funext j history
        by_cases hji : j = i
        · subst j
          simp [completeStrategyEquiv, seqDeviation]
        · simp [completeStrategyEquiv, Function.update_of_ne hji]
      have hpath : ShapeSeqDep.realize
          (Function.update (completeStrategyEquiv A σ) i seqDeviation) =
          realize (DecisionDAG.complete n) (Function.update σ i deviation) :=
        (congrArg ShapeSeqDep.realize hupdate).trans
          (realize_completeStrategyEquiv A (Function.update σ i deviation))
      change k (realize (DecisionDAG.complete n)
        (Function.update σ i deviation)) i ≤
          k (realize (DecisionDAG.complete n) σ) i
      calc
        _ = k (ShapeSeqDep.realize
            (Function.update (completeStrategyEquiv A σ) i seqDeviation)) i :=
          congrArg (fun path => k path i) hpath.symm
        _ ≤ k (ShapeSeqDep.realize (completeStrategyEquiv A σ)) i := hineq
        _ = _ := congrArg (fun path => k path i)
          (realize_completeStrategyEquiv A σ)
    · intro hdag i deviation
      let dagDeviation : History (DecisionDAG.complete n) A i → A i :=
        fun history => deviation (completeHistoryEquiv A i history)
      have hineq := hdag i dagDeviation
      have hupdate : completeStrategyEquiv A
          (Function.update σ i dagDeviation) =
          Function.update (completeStrategyEquiv A σ) i deviation := by
        funext j history
        by_cases hji : j = i
        · subst j
          simp [completeStrategyEquiv, dagDeviation]
        · simp [completeStrategyEquiv, Function.update_of_ne hji]
      have hpath : realize (DecisionDAG.complete n)
          (Function.update σ i dagDeviation) =
          ShapeSeqDep.realize
            (Function.update (completeStrategyEquiv A σ) i deviation) :=
        (realize_completeStrategyEquiv A
          (Function.update σ i dagDeviation)).symm.trans
            (congrArg ShapeSeqDep.realize hupdate)
      change k (ShapeSeqDep.realize
          (Function.update (completeStrategyEquiv A σ) i deviation)) i ≤
        k (ShapeSeqDep.realize (completeStrategyEquiv A σ)) i
      calc
        _ = k (realize (DecisionDAG.complete n)
            (Function.update σ i dagDeviation)) i :=
          congrArg (fun path => k path i) hpath.symm
        _ ≤ k (realize (DecisionDAG.complete n) σ) i := hineq
        _ = _ := congrArg (fun path => k path i)
          (realize_completeStrategyEquiv A σ).symm

/-- The complete-parent specialization preserves the strengthened conditioned
equilibrium semantics, not only plain play and Nash equilibrium. -/
def completeConditionedIso {n : Nat} (A : Fin n → Type) :
    OpenGameIso
      (conditioned (DecisionDAG.complete n) A)
      (ShapeSeqDep.conditioned A) where
  eX := Equiv.refl _
  eS := Equiv.refl _
  eY := Equiv.refl _
  eR := Equiv.refl _
  stratEquiv := completeStrategyEquiv A
  play_preserved := by
    intro σ x
    cases x
    exact realize_completeStrategyEquiv A σ
  coplay_preserved := by
    intro σ x r
    cases x
    rfl
  equilibrium_preserved := by
    intro x k σ
    cases x
    exact (conditioned_complete_iff_sequential A k σ).symm

end ShapeDAG

end OpenGames
