/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/

import Math.FiniteProbabilityMassFunction

/-!
# Probabilistic open games

This file implements the finite-distribution `GProb` semantics of
Ghani--Kupke--Lambert--Nordvall Forsberg.  Play and coplay remain
deterministic; only the equilibrium predicate ranges over finite mixed
strategies.  Parallel and sequential composition admit independent joint
strategies.  Sequential composition uses the relational Kleisli lifting
`FinPMF.RelKleisli` at the random intermediate history.
-/

noncomputable section

namespace OpenGames

open Math

/-- A probabilistic open game.  The backward boundaries are intended to carry
`AvgAlgebra` instances when games are composed. -/
structure ProbOpenGame (X S Y R : Type*) where
  /-- Pure strategy profiles internal to the component. -/
  Strategy : Type*
  /-- Deterministic play for a pure strategy. -/
  play : Strategy → X → Y
  /-- Deterministic backward propagation of a cooutcome (coutility). -/
  coplay : Strategy → X → R → S
  /-- Selected finite mixed strategies in a deterministic context. -/
  IsEquilibriumIn : X → (Y → R) → FinPMF Strategy → Prop

namespace ProbOpenGame

variable {X S Y R Z Q : Type*}

/-- Expected value of an observable under a finite distribution. -/
def expect (μ : FinPMF α) (u : α → ℝ) : ℝ :=
  Math.Probability.expect μ.toPMF u

@[simp] theorem expect_pure (a : α) (u : α → ℝ) :
    expect (FinPMF.pure a) u = u a :=
  Math.Probability.expect_pure u a

/-- Sequential composition from the paper's Definition 12.  The first game
sees the average cooutcome generated by the second mixed strategy.  The
second mixed strategy must be selected by `D̄#` at the pushforward law of
intermediate histories. -/
def seq [AvgAlgebra R]
    (g : ProbOpenGame X S Y R) (h : ProbOpenGame Y R Z Q) :
    ProbOpenGame X S Z Q where
  Strategy := g.Strategy × h.Strategy
  play σ x := h.play σ.2 (g.play σ.1 x)
  coplay σ x q := g.coplay σ.1 x (h.coplay σ.2 (g.play σ.1 x) q)
  IsEquilibriumIn x k φ :=
    let φg := FinPMF.map Prod.fst φ
    let φh := FinPMF.map Prod.snd φ
    φ = FinPMF.product φg φh ∧
      g.IsEquilibriumIn x
        (fun y => AvgAlgebra.avg
          (FinPMF.map
            (fun σh => h.coplay σh y (k (h.play σh y))) φh)) φg ∧
      FinPMF.RelKleisli
        (fun y => {ψ | h.IsEquilibriumIn y k ψ})
        (FinPMF.map (fun σg => g.play σg x) φg) φh

/-- Parallel composition from the paper's Definition 5.  Equilibrium joint
strategies are required to factor into their marginals. -/
def tensor {X' S' Y' R' : Type*} [AvgAlgebra R] [AvgAlgebra R']
    (g : ProbOpenGame X S Y R) (h : ProbOpenGame X' S' Y' R') :
    ProbOpenGame (X × X') (S × S') (Y × Y') (R × R') where
  Strategy := g.Strategy × h.Strategy
  play σ x := (g.play σ.1 x.1, h.play σ.2 x.2)
  coplay σ x r := (g.coplay σ.1 x.1 r.1, h.coplay σ.2 x.2 r.2)
  IsEquilibriumIn x k φ :=
    let φg := FinPMF.map Prod.fst φ
    let φh := FinPMF.map Prod.snd φ
    φ = FinPMF.product φg φh ∧
      g.IsEquilibriumIn x.1
        (fun y => AvgAlgebra.avg
          (FinPMF.map
            (fun σh => (k (y, h.play σh x.2)).1) φh)) φg ∧
      h.IsEquilibriumIn x.2
        (fun y' => AvgAlgebra.avg
          (FinPMF.map
            (fun σg => (k (g.play σg x.1, y')).2) φg)) φh

end ProbOpenGame

scoped[OpenGames] infixr:90 " ;ₚ " => ProbOpenGame.seq
scoped[OpenGames] infixr:88 " ⊗ₚ " => ProbOpenGame.tensor

namespace ProbOpenGame

variable {X S Y R Z Q : Type*}

/-- The sequential equilibrium predicate reduces cleanly on an explicitly
independent strategy. -/
theorem seq_isEquilibriumIn_product_iff [AvgAlgebra R]
    (g : ProbOpenGame X S Y R) (h : ProbOpenGame Y R Z Q)
    (x : X) (k : Z → Q) (φg : FinPMF g.Strategy)
    (φh : FinPMF h.Strategy) :
    (g ;ₚ h).IsEquilibriumIn x k (FinPMF.product φg φh) ↔
      g.IsEquilibriumIn x
        (fun y => AvgAlgebra.avg
          (FinPMF.map
            (fun σh => h.coplay σh y (k (h.play σh y))) φh)) φg ∧
      FinPMF.RelKleisli
        (fun y => {ψ | h.IsEquilibriumIn y k ψ})
        (FinPMF.map (fun σg => g.play σg x) φg) φh := by
  simp [seq]

/-- If the later equilibrium predicate is independent of the incoming
history, `D̄#` has an exact and simple meaning: the later mixed strategy lies
in the finite convex closure of the selected set.  This is the
history-independent case of the semantic question left open after Example 13
of the paper. -/
theorem seq_historyIndependent_iff [AvgAlgebra R]
    (g : ProbOpenGame X S Y R) (h : ProbOpenGame Y R Z Q)
    (x : X) (k : Z → Q) (φg : FinPMF g.Strategy)
    (φh : FinPMF h.Strategy) (E : Set (FinPMF h.Strategy))
    (hE : ∀ y ψ, h.IsEquilibriumIn y k ψ ↔ ψ ∈ E) :
    (g ;ₚ h).IsEquilibriumIn x k (FinPMF.product φg φh) ↔
      g.IsEquilibriumIn x
        (fun y => AvgAlgebra.avg
          (FinPMF.map
            (fun σh => h.coplay σh y (k (h.play σh y))) φh)) φg ∧
      φh ∈ FinPMF.convexClosure E := by
  rw [seq_isEquilibriumIn_product_iff]
  apply and_congr_right
  intro _hg
  rw [show (fun y => {ψ | h.IsEquilibriumIn y k ψ}) = (fun _ => E) by
    funext y
    ext ψ
    exact hE y ψ]
  exact FinPMF.relKleisli_const_iff E _ _

/-- The parallel equilibrium predicate reduces cleanly on an independent
strategy. -/
theorem tensor_isEquilibriumIn_product_iff
    {X' S' Y' R' : Type*} [AvgAlgebra R] [AvgAlgebra R']
    (g : ProbOpenGame X S Y R) (h : ProbOpenGame X' S' Y' R')
    (x : X × X') (k : Y × Y' → R × R')
    (φg : FinPMF g.Strategy) (φh : FinPMF h.Strategy) :
    (g ⊗ₚ h).IsEquilibriumIn x k (FinPMF.product φg φh) ↔
      g.IsEquilibriumIn x.1
        (fun y => AvgAlgebra.avg
          (FinPMF.map
            (fun σh => (k (y, h.play σh x.2)).1) φh)) φg ∧
      h.IsEquilibriumIn x.2
        (fun y' => AvgAlgebra.avg
          (FinPMF.map
            (fun σg => (k (g.play σg x.1, y')).2) φg)) φh := by
  simp [tensor]

/-- Strategically trivial probabilistic wiring. -/
def ofLens (view : X → Y) (update : X → R → S) :
    ProbOpenGame X S Y R where
  Strategy := Unit
  play _ := view
  coplay _ := update
  IsEquilibriumIn _ _ _ := True

/-- Identity wiring. -/
def idWire (X S : Type*) : ProbOpenGame X S X S :=
  ofLens id fun _ s => s

/-- A mixed decision after observing `X`.  A distribution over contingent
pure plans is selected exactly when no alternative distribution has greater
expected payoff at the realized history. -/
def decision (X Y : Type*) : ProbOpenGame X Unit Y ℝ where
  Strategy := X → Y
  play σ x := σ x
  coplay _ _ _ := ()
  IsEquilibriumIn x k μ :=
    ∀ ν : FinPMF (X → Y),
      expect ν (fun σ => k (σ x)) ≤ expect μ (fun σ => k (σ x))

/-- Mixed optimality can be tested using pure constant deviations. -/
theorem decision_isEquilibriumIn_iff (X Y : Type*) (x : X) (k : Y → ℝ)
    (μ : FinPMF (X → Y)) :
    (decision X Y).IsEquilibriumIn x k μ ↔
      ∀ y, k y ≤ expect μ (fun σ => k (σ x)) := by
  constructor
  · intro h y
    simpa using h (FinPMF.pure fun _ => y)
  · intro h ν
    exact FinPMF.expect_le_const ν (fun σ => k (σ x))
      (expect μ fun σ => k (σ x)) fun σ => h (σ x)

/-- State-free decisions use actions themselves as pure strategies, avoiding
an inessential `Unit → Y` wrapper in normal-form bridges. -/
def actionDecision (Y : Type*) : ProbOpenGame Unit Unit Y ℝ where
  Strategy := Y
  play y _ := y
  coplay _ _ _ := ()
  IsEquilibriumIn _ k μ :=
    ∀ ν : FinPMF Y, expect ν k ≤ expect μ k

theorem actionDecision_isEquilibriumIn_iff (Y : Type*) (k : Y → ℝ)
    (μ : FinPMF Y) :
    (actionDecision Y).IsEquilibriumIn () k μ ↔
      ∀ y, k y ≤ expect μ k := by
  constructor
  · intro h y
    simpa using h (FinPMF.pure y)
  · intro h ν
    exact FinPMF.expect_le_const ν k (expect μ k) h

/-! ## Two-player normal-form recovery -/

/-- The usual two-player mixed-Nash inequalities, stated directly for
finite-support marginals on arbitrary action carriers. -/
def IsMixedNash2 {A B : Type*} (u : A × B → ℝ × ℝ)
    (μ : FinPMF A) (ν : FinPMF B) : Prop :=
  (∀ μ' : FinPMF A,
    expect (FinPMF.product μ' ν) (fun p => (u p).1) ≤
      expect (FinPMF.product μ ν) (fun p => (u p).1)) ∧
  (∀ ν' : FinPMF B,
    expect (FinPMF.product μ ν') (fun p => (u p).2) ≤
      expect (FinPMF.product μ ν) (fun p => (u p).2))

/-- Tensoring two mixed decisions recovers exactly the ordinary independent
two-player mixed-Nash predicate. -/
theorem actionDecision_tensor_isEquilibriumIn_iff_isMixedNash2
    {A B : Type*} (u : A × B → ℝ × ℝ)
    (μ : FinPMF A) (ν : FinPMF B) :
    (actionDecision A ⊗ₚ actionDecision B).IsEquilibriumIn ((), ()) u
        (FinPMF.product μ ν) ↔
      IsMixedNash2 u μ ν := by
  rw [tensor_isEquilibriumIn_product_iff]
  simp only [actionDecision]
  unfold IsMixedNash2 expect
  simp only [AvgAlgebra.avg_map_real]
  constructor
  · rintro ⟨hμ, hν⟩
    constructor
    · intro μ'
      simpa only [FinPMF.expect_product] using hμ μ'
    · intro ν'
      rw [FinPMF.expect_product_swap, FinPMF.expect_product_swap]
      exact hν ν'
  · rintro ⟨hμ, hν⟩
    constructor
    · intro μ'
      simpa only [FinPMF.expect_product] using hμ μ'
    · intro ν'
      have h := hν ν'
      rw [FinPMF.expect_product_swap, FinPMF.expect_product_swap] at h
      exact h

end ProbOpenGame

end OpenGames
