/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/

import Math.FiniteProbabilityMassFunction

/-!
# Probabilistic open games

This file implements the finite-distribution `GProb` semantics of
Ghani--Kupke--Lambert--Nordvall Forsberg.  Play and coplay remain
deterministic; only the equilibrium predicate ranges over finite mixed
strategies.  Parallel and sequential composition admit independent joint
strategies.  Sequential composition uses the relational Kleisli lifting
`FinPMF.RelKleisli` at the random intermediate history.

The lifting does not preserve the distribution monad's unit: composing an
identity on the left convexifies the later equilibrium set.  Accordingly,
the raw structure does not satisfy Lemma 16's left-unit claim.  This file
implements repair (c): `ProbOpenGame.ConvexIso` compares equilibrium semantics
after finite convex closure, and `convexSeqIdLeft`/`convexSeqIdRight` prove both
unit laws in that semantics.  It is not a quotient-category repair:
`Examples.convexIso_not_left_seq_congruence` proves that this equivalence is
not a left congruence for raw composition.  A categorical repair must therefore
also change composition or restrict its morphisms.  `ProbOpenGame.Saturated`
implements that next repair: morphisms carry convex-closed equilibrium sets and
composition closes after each step; closure and both unitors are proved.
However, `Examples.probabilistic_seq_not_associative` refutes the paper's raw
Theorem 15, and `Examples.saturated_seq_not_associative` shows that post-closing
does not repair associativity.  Thus neither repair (a) nor repair (c) yields
the claimed category without a deeper change to the lifting or strategy-law
semantics.
-/

noncomputable section

namespace OpenGames

open Math

/-- A probabilistic open game.  The backward boundaries are intended to carry
`AvgAlgebra` instances when games are composed. -/
structure ProbOpenGame (X S Y R : Type*) where
  /-- Pure strategy profiles internal to the component. -/
  Strategy : Type*
  /-- Deterministic play for a pure strategy. -/
  play : Strategy → X → Y
  /-- Deterministic backward propagation of a cooutcome (coutility). -/
  coplay : Strategy → X → R → S
  /-- Selected finite mixed strategies in a deterministic context. -/
  IsEquilibriumIn : X → (Y → R) → FinPMF Strategy → Prop

namespace ProbOpenGame

variable {X S Y R Z Q : Type*}

/-- Sequential composition from the paper's Definition 12.  The first game
sees the average cooutcome generated by the second mixed strategy.  The
second mixed strategy must be selected by `D̄#` at the pushforward law of
intermediate histories. -/
def seq [AvgAlgebra R]
    (g : ProbOpenGame X S Y R) (h : ProbOpenGame Y R Z Q) :
    ProbOpenGame X S Z Q where
  Strategy := g.Strategy × h.Strategy
  play σ x := h.play σ.2 (g.play σ.1 x)
  coplay σ x q := g.coplay σ.1 x (h.coplay σ.2 (g.play σ.1 x) q)
  IsEquilibriumIn x k φ :=
    let φg := FinPMF.map Prod.fst φ
    let φh := FinPMF.map Prod.snd φ
    φ = FinPMF.product φg φh ∧
      g.IsEquilibriumIn x
        (fun y => AvgAlgebra.avg
          (FinPMF.map
            (fun σh => h.coplay σh y (k (h.play σh y))) φh)) φg ∧
      FinPMF.RelKleisli
        (fun y => {ψ | h.IsEquilibriumIn y k ψ})
        (FinPMF.map (fun σg => g.play σg x) φg) φh

/-- Parallel composition from the paper's Definition 5.  Equilibrium joint
strategies are required to factor into their marginals. -/
def tensor {X' S' Y' R' : Type*} [AvgAlgebra R] [AvgAlgebra R']
    (g : ProbOpenGame X S Y R) (h : ProbOpenGame X' S' Y' R') :
    ProbOpenGame (X × X') (S × S') (Y × Y') (R × R') where
  Strategy := g.Strategy × h.Strategy
  play σ x := (g.play σ.1 x.1, h.play σ.2 x.2)
  coplay σ x r := (g.coplay σ.1 x.1 r.1, h.coplay σ.2 x.2 r.2)
  IsEquilibriumIn x k φ :=
    let φg := FinPMF.map Prod.fst φ
    let φh := FinPMF.map Prod.snd φ
    φ = FinPMF.product φg φh ∧
      g.IsEquilibriumIn x.1
        (fun y => AvgAlgebra.avg
          (FinPMF.map
            (fun σh => (k (y, h.play σh x.2)).1) φh)) φg ∧
      h.IsEquilibriumIn x.2
        (fun y' => AvgAlgebra.avg
          (FinPMF.map
            (fun σg => (k (g.play σg x.1, y')).2) φg)) φh

end ProbOpenGame

scoped[OpenGames] infixr:90 " ;ₚ " => ProbOpenGame.seq
scoped[OpenGames] infixr:88 " ⊗ₚ " => ProbOpenGame.tensor

namespace ProbOpenGame

variable {X S Y R Z Q : Type*}

/-- The sequential equilibrium predicate reduces cleanly on an explicitly
independent strategy. -/
theorem seq_isEquilibriumIn_product_iff [AvgAlgebra R]
    (g : ProbOpenGame X S Y R) (h : ProbOpenGame Y R Z Q)
    (x : X) (k : Z → Q) (φg : FinPMF g.Strategy)
    (φh : FinPMF h.Strategy) :
    (g ;ₚ h).IsEquilibriumIn x k (FinPMF.product φg φh) ↔
      g.IsEquilibriumIn x
        (fun y => AvgAlgebra.avg
          (FinPMF.map
            (fun σh => h.coplay σh y (k (h.play σh y))) φh)) φg ∧
      FinPMF.RelKleisli
        (fun y => {ψ | h.IsEquilibriumIn y k ψ})
        (FinPMF.map (fun σg => g.play σg x) φg) φh := by
  simp [seq]

/-- If the later equilibrium predicate is independent of the incoming
history, `D̄#` has an exact and simple meaning: the later mixed strategy lies
in the finite convex closure of the selected set.  This is the
history-independent case of the semantic question left open after Example 13
of the paper. -/
theorem seq_historyIndependent_iff [AvgAlgebra R]
    (g : ProbOpenGame X S Y R) (h : ProbOpenGame Y R Z Q)
    (x : X) (k : Z → Q) (φg : FinPMF g.Strategy)
    (φh : FinPMF h.Strategy) (E : Set (FinPMF h.Strategy))
    (hE : ∀ y ψ, h.IsEquilibriumIn y k ψ ↔ ψ ∈ E) :
    (g ;ₚ h).IsEquilibriumIn x k (FinPMF.product φg φh) ↔
      g.IsEquilibriumIn x
        (fun y => AvgAlgebra.avg
          (FinPMF.map
            (fun σh => h.coplay σh y (k (h.play σh y))) φh)) φg ∧
      φh ∈ FinPMF.convexClosure E := by
  rw [seq_isEquilibriumIn_product_iff]
  apply and_congr_right
  intro _hg
  rw [show (fun y => {ψ | h.IsEquilibriumIn y k ψ}) = (fun _ => E) by
    funext y
    ext ψ
    exact hE y ψ]
  exact FinPMF.relKleisli_const_iff E _ _

/-- The parallel equilibrium predicate reduces cleanly on an independent
strategy. -/
theorem tensor_isEquilibriumIn_product_iff
    {X' S' Y' R' : Type*} [AvgAlgebra R] [AvgAlgebra R']
    (g : ProbOpenGame X S Y R) (h : ProbOpenGame X' S' Y' R')
    (x : X × X') (k : Y × Y' → R × R')
    (φg : FinPMF g.Strategy) (φh : FinPMF h.Strategy) :
    (g ⊗ₚ h).IsEquilibriumIn x k (FinPMF.product φg φh) ↔
      g.IsEquilibriumIn x.1
        (fun y => AvgAlgebra.avg
          (FinPMF.map
            (fun σh => (k (y, h.play σh x.2)).1) φh)) φg ∧
      h.IsEquilibriumIn x.2
        (fun y' => AvgAlgebra.avg
          (FinPMF.map
            (fun σg => (k (g.play σg x.1, y')).2) φg)) φh := by
  simp [tensor]

/-- Strategically trivial probabilistic wiring. -/
def ofLens (view : X → Y) (update : X → R → S) :
    ProbOpenGame X S Y R where
  Strategy := Unit
  play _ := view
  coplay _ := update
  IsEquilibriumIn _ _ _ := True

/-- Identity wiring. -/
def idWire (X S : Type*) : ProbOpenGame X S X S :=
  ofLens id fun _ s => s

/-- Every equilibrium set of `g` is closed under finite barycenters.  Exact
`D̄#` composition needs this semantic property for the left identity law. -/
def HasConvexEquilibria (g : ProbOpenGame X S Y R) : Prop :=
  ∀ (x : X) (k : Y → R),
    FinPMF.convexClosure {μ | g.IsEquilibriumIn x k μ} ⊆
      {μ | g.IsEquilibriumIn x k μ}

/-- The equilibrium semantics observed only up to finite convex closure. -/
def IsConvexEquilibriumIn (g : ProbOpenGame X S Y R)
    (x : X) (k : Y → R) (μ : FinPMF g.Strategy) : Prop :=
  μ ∈ FinPMF.convexClosure {ψ | g.IsEquilibriumIn x k ψ}

/-- Strategy isomorphism preserving play, coplay, and equilibrium semantics
after finite convex closure.  This is the equality notion used by the repaired
probabilistic unit laws. -/
structure ConvexIso
    (g g' : ProbOpenGame X S Y R) where
  stratEquiv : g.Strategy ≃ g'.Strategy
  play_preserved : ∀ σ x,
    g'.play (stratEquiv σ) x = g.play σ x
  coplay_preserved : ∀ σ x r,
    g'.coplay (stratEquiv σ) x r = g.coplay σ x r
  equilibrium_preserved : ∀ x k φ,
    g'.IsConvexEquilibriumIn x k (FinPMF.map stratEquiv φ) ↔
      g.IsConvexEquilibriumIn x k φ

namespace ConvexIso

/-- Reflexivity of convex-semantic game isomorphism. -/
def refl (g : ProbOpenGame X S Y R) : ConvexIso g g where
  stratEquiv := Equiv.refl _
  play_preserved := fun _ _ => rfl
  coplay_preserved := fun _ _ _ => rfl
  equilibrium_preserved := by
    intro x k φ
    change g.IsConvexEquilibriumIn x k (FinPMF.map id φ) ↔ _
    rw [FinPMF.map_id]

/-- Symmetry of convex-semantic game isomorphism. -/
def symm {g g' : ProbOpenGame X S Y R}
    (e : ConvexIso g g') : ConvexIso g' g where
  stratEquiv := e.stratEquiv.symm
  play_preserved := by
    intro σ x
    simpa using (e.play_preserved (e.stratEquiv.symm σ) x).symm
  coplay_preserved := by
    intro σ x r
    simpa using (e.coplay_preserved (e.stratEquiv.symm σ) x r).symm
  equilibrium_preserved := by
    intro x k φ
    have h := (e.equilibrium_preserved x k
      (FinPMF.map e.stratEquiv.symm φ)).symm
    rw [FinPMF.map_comp] at h
    have hmap : FinPMF.map
        (e.stratEquiv ∘ e.stratEquiv.symm) φ = φ := by
      calc
        FinPMF.map (e.stratEquiv ∘ e.stratEquiv.symm) φ =
            FinPMF.map id φ := by
          congr 1
          funext σ
          exact e.stratEquiv.apply_symm_apply σ
        _ = φ := FinPMF.map_id φ
    rw [hmap] at h
    exact h

/-- Transitivity of convex-semantic game isomorphism. -/
def trans {g g' g'' : ProbOpenGame X S Y R}
    (e : ConvexIso g g') (f : ConvexIso g' g'') : ConvexIso g g'' where
  stratEquiv := e.stratEquiv.trans f.stratEquiv
  play_preserved := by
    intro σ x
    exact (f.play_preserved (e.stratEquiv σ) x).trans
      (e.play_preserved σ x)
  coplay_preserved := by
    intro σ x r
    exact (f.coplay_preserved (e.stratEquiv σ) x r).trans
      (e.coplay_preserved σ x r)
  equilibrium_preserved := by
    intro x k φ
    simpa [FinPMF.map_comp, Function.comp_def] using
      (f.equilibrium_preserved x k (FinPMF.map e.stratEquiv φ)).trans
        (e.equilibrium_preserved x k φ)

end ConvexIso

/-- Saturate every equilibrium set under finite barycenters. -/
def convexify (g : ProbOpenGame X S Y R) : ProbOpenGame X S Y R where
  Strategy := g.Strategy
  play := g.play
  coplay := g.coplay
  IsEquilibriumIn x k μ :=
    μ ∈ FinPMF.convexClosure {ψ | g.IsEquilibriumIn x k ψ}

theorem convexify_hasConvexEquilibria (g : ProbOpenGame X S Y R) :
    HasConvexEquilibria (convexify g) := by
  intro x k μ hμ
  change μ ∈ FinPMF.convexClosure
    (FinPMF.convexClosure {ψ | g.IsEquilibriumIn x k ψ}) at hμ
  change μ ∈ FinPMF.convexClosure {ψ | g.IsEquilibriumIn x k ψ}
  rwa [FinPMF.convexClosure_idempotent] at hμ

@[simp] theorem convexify_isEquilibriumIn_iff
    (g : ProbOpenGame X S Y R) (x : X) (k : Y → R)
    (μ : FinPMF g.Strategy) :
    (convexify g).IsEquilibriumIn x k μ ↔
      μ ∈ FinPMF.convexClosure {ψ | g.IsEquilibriumIn x k ψ} :=
  Iff.rfl

@[simp] theorem convexify_isEquilibriumIn_iff_isConvexEquilibriumIn
    (g : ProbOpenGame X S Y R) (x : X) (k : Y → R)
    (μ : FinPMF g.Strategy) :
    (convexify g).IsEquilibriumIn x k μ ↔
      g.IsConvexEquilibriumIn x k μ :=
  Iff.rfl

/-- Every game is convex-semantically isomorphic to its saturation. -/
def convexifyConvexIso (g : ProbOpenGame X S Y R) :
    ConvexIso g (convexify g) where
  stratEquiv := Equiv.refl _
  play_preserved := fun _ _ => rfl
  coplay_preserved := fun _ _ _ => rfl
  equilibrium_preserved := by
    intro x k φ
    change FinPMF g.Strategy at φ
    unfold IsConvexEquilibriumIn
    change FinPMF.map (Equiv.refl g.Strategy) φ ∈ FinPMF.convexClosure
      (FinPMF.convexClosure {ψ | g.IsEquilibriumIn x k ψ}) ↔
        φ ∈ FinPMF.convexClosure {ψ | g.IsEquilibriumIn x k ψ}
    have hmap : FinPMF.map (Equiv.refl g.Strategy) φ = φ := by
      change FinPMF.map id φ = φ
      exact FinPMF.map_id φ
    rw [hmap, FinPMF.convexClosure_idempotent]

/-- `D̄#` already convex-saturates every downstream equilibrium fiber, so
convexifying the second component before composition changes nothing. -/
theorem seq_convexify_right_isEquilibriumIn_iff [AvgAlgebra R]
    (g : ProbOpenGame X S Y R) (h : ProbOpenGame Y R Z Q)
    (x : X) (k : Z → Q) (φ : FinPMF (g.Strategy × h.Strategy)) :
    (g ;ₚ convexify h).IsEquilibriumIn x k φ ↔
      (g ;ₚ h).IsEquilibriumIn x k φ := by
  simp only [seq, convexify]
  apply and_congr_right
  intro _
  apply and_congr_right
  intro _
  exact FinPMF.relKleisli_convexClosure_iff
    (fun y => {ψ | h.IsEquilibriumIn y k ψ})
    (FinPMF.map (fun σg => g.play σg x) (FinPMF.map Prod.fst φ))
    (FinPMF.map Prod.snd φ)

/-- Composing an identity before a game convexifies the game's equilibrium
set.  This is exact, not merely an inclusion. -/
theorem idWire_seq_isEquilibriumIn_iff [AvgAlgebra S]
    (g : ProbOpenGame X S Y R) (x : X) (k : Y → R)
    (φ : FinPMF (Unit × g.Strategy)) :
    (idWire X S ;ₚ g).IsEquilibriumIn x k φ ↔
      FinPMF.map Prod.snd φ ∈
        FinPMF.convexClosure {ψ | g.IsEquilibriumIn x k ψ} := by
  change
    (φ = FinPMF.product (FinPMF.map Prod.fst φ)
          (FinPMF.map Prod.snd φ) ∧
        True ∧
        FinPMF.RelKleisli
          (fun y => {ψ | g.IsEquilibriumIn y k ψ})
          (FinPMF.map (fun _ : Unit => x) (FinPMF.map Prod.fst φ))
          (FinPMF.map Prod.snd φ)) ↔ _
  rw [FinPMF.map_fst_unit_product,
    FinPMF.product_pure_unit_map_snd]
  simp only [FinPMF.map_pure, true_and]
  exact FinPMF.relKleisli_pure_iff
    (fun y => {ψ | g.IsEquilibriumIn y k ψ}) x _

/-- Product-form specialization of `idWire_seq_isEquilibriumIn_iff`. -/
theorem idWire_seq_isEquilibriumIn_product_iff [AvgAlgebra S]
    (g : ProbOpenGame X S Y R) (x : X) (k : Y → R)
    (φ : FinPMF g.Strategy) :
    (idWire X S ;ₚ g).IsEquilibriumIn x k
        (FinPMF.product (FinPMF.pure ()) φ) ↔
      φ ∈ FinPMF.convexClosure {ψ | g.IsEquilibriumIn x k ψ} := by
  rw [seq_isEquilibriumIn_product_iff]
  simp only [idWire, ofLens, true_and, FinPMF.map_pure]
  exact FinPMF.relKleisli_pure_iff
    (fun y => {ψ | g.IsEquilibriumIn y k ψ}) x φ

/-- A left identity composite always has convex equilibrium sets, even when
the original game's selected sets are not convex. -/
theorem idWire_seq_hasConvexEquilibria [AvgAlgebra S]
    (g : ProbOpenGame X S Y R) :
    HasConvexEquilibria (idWire X S ;ₚ g) := by
  intro x k φ hφ
  change (idWire X S ;ₚ g).IsEquilibriumIn x k φ
  rw [idWire_seq_isEquilibriumIn_iff]
  rcases hφ with ⟨θ, hθ, hjoin⟩
  have hdouble : FinPMF.map Prod.snd φ ∈ FinPMF.convexClosure
      (FinPMF.convexClosure {ψ | g.IsEquilibriumIn x k ψ}) := by
    refine ⟨FinPMF.map (FinPMF.map Prod.snd) θ, ?_, ?_⟩
    · intro ψ hψ
      rw [FinPMF.support_map] at hψ
      rcases hψ with ⟨ρ, hρ, rfl⟩
      exact (idWire_seq_isEquilibriumIn_iff g x k ρ).1 (hθ hρ)
    · calc
        FinPMF.join (FinPMF.map (FinPMF.map Prod.snd) θ) =
            FinPMF.map Prod.snd (FinPMF.join θ) :=
          FinPMF.join_map_map Prod.snd θ
        _ = FinPMF.map Prod.snd φ := congrArg _ hjoin
  rwa [FinPMF.convexClosure_idempotent] at hdouble

/-- The left identity law is valid for every probabilistic open game when
equilibrium predicates are observed up to convex closure. -/
theorem idWire_seq_isConvexEquilibriumIn_iff [AvgAlgebra S]
    (g : ProbOpenGame X S Y R) (x : X) (k : Y → R)
    (φ : FinPMF (Unit × g.Strategy)) :
    (idWire X S ;ₚ g).IsConvexEquilibriumIn x k φ ↔
      g.IsConvexEquilibriumIn x k (FinPMF.map Prod.snd φ) := by
  constructor
  · intro hφ
    exact (idWire_seq_isEquilibriumIn_iff g x k φ).1
      (idWire_seq_hasConvexEquilibria g x k hφ)
  · intro hφ
    exact FinPMF.subset_convexClosure _
      ((idWire_seq_isEquilibriumIn_iff g x k φ).2 hφ)

/-- Thus the unrestricted left composite agrees exactly with the convexified
game, identifying convex saturation as the minimal unit-law repair. -/
theorem idWire_seq_isEquilibriumIn_product_iff_convexify [AvgAlgebra S]
    (g : ProbOpenGame X S Y R) (x : X) (k : Y → R)
    (φ : FinPMF g.Strategy) :
    (idWire X S ;ₚ g).IsEquilibriumIn x k
        (FinPMF.product (FinPMF.pure ()) φ) ↔
      (convexify g).IsEquilibriumIn x k φ :=
  idWire_seq_isEquilibriumIn_product_iff g x k φ

/-- The left identity law holds on games whose equilibrium sets are already
closed under the convexification performed by `D̄#`. -/
theorem idWire_seq_isEquilibriumIn_product_iff_of_convex [AvgAlgebra S]
    (g : ProbOpenGame X S Y R) (hg : HasConvexEquilibria g)
    (x : X) (k : Y → R) (φ : FinPMF g.Strategy) :
    (idWire X S ;ₚ g).IsEquilibriumIn x k
        (FinPMF.product (FinPMF.pure ()) φ) ↔
      g.IsEquilibriumIn x k φ := by
  rw [idWire_seq_isEquilibriumIn_product_iff]
  constructor
  · intro hφ
    exact hg x k hφ
  · intro hφ
    exact FinPMF.subset_convexClosure _ hφ

/-- Composing a game with an identity on the right preserves equilibrium
without an additional closure hypothesis. -/
theorem seq_idWire_isEquilibriumIn_product_iff [AvgAlgebra R]
    (g : ProbOpenGame X S Y R) (x : X) (k : Y → R)
    (φ : FinPMF g.Strategy) :
    (g ;ₚ idWire Y R).IsEquilibriumIn x k
        (FinPMF.product φ (FinPMF.pure ())) ↔
      g.IsEquilibriumIn x k φ := by
  rw [seq_isEquilibriumIn_product_iff]
  constructor
  · rintro ⟨hg, _hid⟩
    simpa [idWire, ofLens] using hg
  · intro hg
    constructor
    · simpa [idWire, ofLens] using hg
    · apply FinPMF.relKleisli_of_forall_mem
      intro y _hy
      exact Set.mem_univ _

/-- General right-unit characterization; every law on `Strategy × Unit`
already has product form. -/
theorem seq_idWire_isEquilibriumIn_iff [AvgAlgebra R]
    (g : ProbOpenGame X S Y R) (x : X) (k : Y → R)
    (φ : FinPMF (g.Strategy × Unit)) :
    (g ;ₚ idWire Y R).IsEquilibriumIn x k φ ↔
      g.IsEquilibriumIn x k (FinPMF.map Prod.fst φ) := by
  change
    (φ = FinPMF.product (FinPMF.map Prod.fst φ)
          (FinPMF.map Prod.snd φ) ∧
        g.IsEquilibriumIn x
          (fun y => AvgAlgebra.avg
            (FinPMF.map (fun _ : Unit => k y)
              (FinPMF.map Prod.snd φ)))
          (FinPMF.map Prod.fst φ) ∧
        FinPMF.RelKleisli (fun _ => Set.univ)
          (FinPMF.map (fun σ => g.play σ x) (FinPMF.map Prod.fst φ))
          (FinPMF.map Prod.snd φ)) ↔ _
  rw [FinPMF.map_snd_product_unit,
    FinPMF.product_map_fst_pure_unit]
  simp only [FinPMF.map_pure, AvgAlgebra.avg_pure, true_and]
  apply and_iff_left
  apply FinPMF.relKleisli_of_forall_mem
  intro _ _
  exact Set.mem_univ _

/-- The right identity law also holds up to convex closure. -/
theorem seq_idWire_isConvexEquilibriumIn_iff [AvgAlgebra R]
    (g : ProbOpenGame X S Y R) (x : X) (k : Y → R)
    (φ : FinPMF (g.Strategy × Unit)) :
    (g ;ₚ idWire Y R).IsConvexEquilibriumIn x k φ ↔
      g.IsConvexEquilibriumIn x k (FinPMF.map Prod.fst φ) := by
  constructor
  · rintro ⟨θ, hθ, hjoin⟩
    refine ⟨FinPMF.map (FinPMF.map Prod.fst) θ, ?_, ?_⟩
    · intro ψ hψ
      rw [FinPMF.support_map] at hψ
      rcases hψ with ⟨ρ, hρ, rfl⟩
      exact (seq_idWire_isEquilibriumIn_iff g x k ρ).1 (hθ hρ)
    · calc
        FinPMF.join (FinPMF.map (FinPMF.map Prod.fst) θ) =
            FinPMF.map Prod.fst (FinPMF.join θ) :=
          FinPMF.join_map_map Prod.fst θ
        _ = FinPMF.map Prod.fst φ := congrArg _ hjoin
  · rintro ⟨θ, hθ, hjoin⟩
    let pairUnit : g.Strategy → g.Strategy × Unit := fun σ => (σ, ())
    refine ⟨FinPMF.map (FinPMF.map pairUnit) θ, ?_, ?_⟩
    · intro ρ hρ
      rw [FinPMF.support_map] at hρ
      rcases hρ with ⟨ψ, hψ, rfl⟩
      simp only [seq, idWire, ofLens, pairUnit]
      have hfst : FinPMF.map Prod.fst
          (FinPMF.map (fun σ : g.Strategy => (σ, ())) ψ) = ψ :=
        FinPMF.map_fst_map_mk_right ψ ()
      have hsnd : FinPMF.map Prod.snd
          (FinPMF.map (fun σ : g.Strategy => (σ, ())) ψ) =
          FinPMF.pure () :=
        FinPMF.map_snd_map_mk_right ψ ()
      constructor
      · rw [hfst, hsnd, FinPMF.product_pure_right]
      · constructor
        · simpa [hfst, hsnd] using hθ hψ
        · apply FinPMF.relKleisli_of_forall_mem
          intro _ _
          exact Set.mem_univ _
    · calc
        FinPMF.join (FinPMF.map (FinPMF.map pairUnit) θ) =
            FinPMF.map pairUnit (FinPMF.join θ) :=
          FinPMF.join_map_map pairUnit θ
        _ = FinPMF.map pairUnit (FinPMF.map Prod.fst φ) :=
          congrArg _ hjoin
        _ = FinPMF.product (FinPMF.map Prod.fst φ)
            (FinPMF.pure ()) := by
          rw [FinPMF.product_pure_right]
        _ = φ := FinPMF.product_map_fst_pure_unit φ

/-- Repair (c) for the left unit in Lemma 16: the usual strategy unitor is an
isomorphism when equilibrium predicates are compared up to convex closure. -/
def convexSeqIdLeft [AvgAlgebra S] (g : ProbOpenGame X S Y R) :
    ConvexIso (idWire X S ;ₚ g) g where
  stratEquiv := {
    toFun := fun σ => σ.2
    invFun := fun σ => ((), σ)
    left_inv := by rintro ⟨u, σ⟩; cases u; rfl
    right_inv := fun _ => rfl }
  play_preserved := by
    rintro ⟨u, σ⟩ x
    cases u
    rfl
  coplay_preserved := by
    rintro ⟨u, σ⟩ x r
    cases u
    rfl
  equilibrium_preserved := by
    intro x k φ
    change FinPMF (Unit × g.Strategy) at φ
    change g.IsConvexEquilibriumIn x k (FinPMF.map Prod.snd φ) ↔
      (idWire X S ;ₚ g).IsConvexEquilibriumIn x k φ
    exact (idWire_seq_isConvexEquilibriumIn_iff g x k φ).symm

/-- Repair (c) for the right unit in Lemma 16. -/
def convexSeqIdRight [AvgAlgebra R] (g : ProbOpenGame X S Y R) :
    ConvexIso (g ;ₚ idWire Y R) g where
  stratEquiv := {
    toFun := fun σ => σ.1
    invFun := fun σ => (σ, ())
    left_inv := by rintro ⟨σ, u⟩; cases u; rfl
    right_inv := fun _ => rfl }
  play_preserved := by
    rintro ⟨σ, u⟩ x
    cases u
    rfl
  coplay_preserved := by
    rintro ⟨σ, u⟩ x r
    cases u
    rfl
  equilibrium_preserved := by
    intro x k φ
    change FinPMF (g.Strategy × Unit) at φ
    change g.IsConvexEquilibriumIn x k (FinPMF.map Prod.fst φ) ↔
      (g ;ₚ idWire Y R).IsConvexEquilibriumIn x k φ
    exact (seq_idWire_isConvexEquilibriumIn_iff g x k φ).symm

/-! ## Post-closed composition -/

/-- A probabilistic open game whose equilibrium sets are convex-closed.  This
is the morphism carrier for repair (a): composition is saturated after every
step, so the carrier is closed by construction. -/
def Saturated (X S Y R : Type*) :=
  {g : ProbOpenGame X S Y R // HasConvexEquilibria g}

namespace Saturated

/-- Identity is already convex-closed. -/
def id (X S : Type*) : Saturated X S X S :=
  ⟨idWire X S, by
    intro _ _ _ _
    trivial⟩

/-- Repair (a): sequentially compose, then close the resulting equilibrium
sets under finite barycenters. -/
def seq [AvgAlgebra R]
    (g : Saturated X S Y R) (h : Saturated Y R Z Q) :
    Saturated X S Z Q :=
  ⟨convexify (g.1 ;ₚ h.1), convexify_hasConvexEquilibria _⟩

/-- On a saturated game, convex equilibrium semantics and the carried raw
predicate coincide. -/
theorem isConvexEquilibriumIn_iff
    (g : Saturated X S Y R) (x : X) (k : Y → R)
    (φ : FinPMF g.1.Strategy) :
    g.1.IsConvexEquilibriumIn x k φ ↔
      g.1.IsEquilibriumIn x k φ := by
  constructor
  · intro hφ
    exact g.2 x k hφ
  · intro hφ
    exact FinPMF.subset_convexClosure _ hφ

/-- The post-closed composition has a left unit up to strategy isomorphism and
convex semantics.  Since both bundled games are saturated, this also compares
their raw equilibrium predicates. -/
def seqIdLeft [AvgAlgebra S] (g : Saturated X S Y R) :
    ConvexIso (seq (id X S) g).1 g.1 :=
  ConvexIso.trans
    (ConvexIso.symm (convexifyConvexIso (idWire X S ;ₚ g.1)))
    (convexSeqIdLeft g.1)

/-- Right unit for post-closed composition. -/
def seqIdRight [AvgAlgebra R] (g : Saturated X S Y R) :
    ConvexIso (seq g (id Y R)).1 g.1 :=
  ConvexIso.trans
    (ConvexIso.symm (convexifyConvexIso (g.1 ;ₚ idWire Y R)))
    (convexSeqIdRight g.1)

end Saturated

/-- A mixed decision after observing `X`.  A distribution over contingent
pure plans is selected exactly when no alternative distribution has greater
expected payoff at the realized history. -/
def decision (X Y : Type*) : ProbOpenGame X Unit Y ℝ where
  Strategy := X → Y
  play σ x := σ x
  coplay _ _ _ := ()
  IsEquilibriumIn x k μ :=
    ∀ ν : FinPMF (X → Y),
      FinPMF.expect ν (fun σ => k (σ x)) ≤
        FinPMF.expect μ (fun σ => k (σ x))

/-- Mixed optimality can be tested using pure constant deviations. -/
theorem decision_isEquilibriumIn_iff (X Y : Type*) (x : X) (k : Y → ℝ)
    (μ : FinPMF (X → Y)) :
    (decision X Y).IsEquilibriumIn x k μ ↔
      ∀ y, k y ≤ FinPMF.expect μ (fun σ => k (σ x)) := by
  constructor
  · intro h y
    simpa using h (FinPMF.pure fun _ => y)
  · intro h ν
    exact FinPMF.expect_le_const ν (fun σ => k (σ x))
      (FinPMF.expect μ fun σ => k (σ x)) fun σ => h (σ x)

theorem decision_hasConvexEquilibria (X Y : Type*) :
    HasConvexEquilibria (decision X Y) := by
  intro x k μ hμ
  rcases hμ with ⟨θ, hθ, rfl⟩
  intro ν
  calc
    FinPMF.expect ν (fun σ => k (σ x)) =
        FinPMF.expect θ
          (fun _ => FinPMF.expect ν (fun σ => k (σ x))) := by
      symm
      exact Math.Probability.expect_const _ _
    _ ≤ FinPMF.expect θ
          (fun ψ => FinPMF.expect ψ (fun σ => k (σ x))) := by
      apply FinPMF.expect_mono_on_support
      intro ψ hψ
      exact hθ hψ ν
    _ = FinPMF.expect (FinPMF.join θ) (fun σ => k (σ x)) := by
      exact (FinPMF.expect_bind θ id (fun σ => k (σ x))).symm

/-- State-free decisions use actions themselves as pure strategies, avoiding
an inessential `Unit → Y` wrapper in normal-form bridges. -/
def actionDecision (Y : Type*) : ProbOpenGame Unit Unit Y ℝ where
  Strategy := Y
  play y _ := y
  coplay _ _ _ := ()
  IsEquilibriumIn _ k μ :=
    ∀ ν : FinPMF Y, FinPMF.expect ν k ≤ FinPMF.expect μ k

theorem actionDecision_isEquilibriumIn_iff (Y : Type*) (k : Y → ℝ)
    (μ : FinPMF Y) :
    (actionDecision Y).IsEquilibriumIn () k μ ↔
      ∀ y, k y ≤ FinPMF.expect μ k := by
  constructor
  · intro h y
    simpa using h (FinPMF.pure y)
  · intro h ν
    exact FinPMF.expect_le_const ν k (FinPMF.expect μ k) h

theorem actionDecision_hasConvexEquilibria (Y : Type*) :
    HasConvexEquilibria (actionDecision Y) := by
  intro _x k μ hμ
  rcases hμ with ⟨θ, hθ, rfl⟩
  intro ν
  calc
    FinPMF.expect ν k = FinPMF.expect θ (fun _ => FinPMF.expect ν k) := by
      symm
      exact Math.Probability.expect_const _ _
    _ ≤ FinPMF.expect θ (fun ψ => FinPMF.expect ψ k) := by
      apply FinPMF.expect_mono_on_support
      intro ψ hψ
      exact hθ hψ ν
    _ = FinPMF.expect (FinPMF.join θ) k := by
      exact (FinPMF.expect_bind θ id k).symm

/-! ## Two-player normal-form recovery -/

/-- The usual two-player mixed-Nash inequalities, stated directly for
finite-support marginals on arbitrary action carriers. -/
def IsMixedNash2 {A B : Type*} (u : A × B → ℝ × ℝ)
    (μ : FinPMF A) (ν : FinPMF B) : Prop :=
  (∀ μ' : FinPMF A,
    FinPMF.expect (FinPMF.product μ' ν) (fun p => (u p).1) ≤
      FinPMF.expect (FinPMF.product μ ν) (fun p => (u p).1)) ∧
  (∀ ν' : FinPMF B,
    FinPMF.expect (FinPMF.product μ ν') (fun p => (u p).2) ≤
      FinPMF.expect (FinPMF.product μ ν) (fun p => (u p).2))

/-- Tensoring two mixed decisions recovers exactly the ordinary independent
two-player mixed-Nash predicate. -/
theorem actionDecision_tensor_isEquilibriumIn_iff_isMixedNash2
    {A B : Type*} (u : A × B → ℝ × ℝ)
    (μ : FinPMF A) (ν : FinPMF B) :
    (actionDecision A ⊗ₚ actionDecision B).IsEquilibriumIn ((), ()) u
        (FinPMF.product μ ν) ↔
      IsMixedNash2 u μ ν := by
  rw [tensor_isEquilibriumIn_product_iff]
  simp only [actionDecision]
  unfold IsMixedNash2
  simp only [AvgAlgebra.avg_map_real]
  constructor
  · rintro ⟨hμ, hν⟩
    constructor
    · intro μ'
      simpa only [FinPMF.expect_product] using hμ μ'
    · intro ν'
      rw [FinPMF.expect_product_swap, FinPMF.expect_product_swap]
      exact hν ν'
  · rintro ⟨hμ, hν⟩
    constructor
    · intro μ'
      simpa only [FinPMF.expect_product] using hμ μ'
    · intro ν'
      have h := hν ν'
      rw [FinPMF.expect_product_swap, FinPMF.expect_product_swap] at h
      exact h

end ProbOpenGame

end OpenGames
