/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/

import GameTheory.Languages.OpenGame

/-!
# Tests for Deterministic Open Games

These compilation tests exercise the typed wiring diagram for a two-move game
and check its equilibrium predicate by reduction.
-/

namespace OpenGames.Tests

open scoped OpenGames

/-- The standard two-move diagram: decide, copy the first move, decide again,
then deliver both players' cooutcomes through a costate. -/
def twoMove {A B : Type} (u : A × B → ℝ × ℝ) :
    OpenGame Unit Unit Unit Unit :=
  ShapeS.wiring A B ;ₒ OpenGame.costate u

/-- Embed the usual leader action and follower contingent plan into the
strategy type generated by the wiring diagram. -/
def twoMoveStrategy {A B : Type} (u : A × B → ℝ × ℝ)
    (first : A) (second : A → B) : (twoMove u).Strategy :=
  (((fun _ => first), ((), ((), second))), ())

/-- Plain sequential composition checks the follower only at the realized
history.  The first mover, however, compares deviations after the fixed
contingent follower plan has reacted to each alternative. -/
theorem twoMove_equilibrium_iff {A B : Type} (u : A × B → ℝ × ℝ)
    (first : A) (second : A → B) :
    (twoMove u).IsEquilibriumIn () (fun _ => ())
        (twoMoveStrategy u first second) ↔
      (∀ a, (u (first, second first)).1 ≥ (u (a, second a)).1) ∧
      (∀ b, (u (first, second first)).2 ≥ (u (first, b)).2) := by
  simp [twoMove, twoMoveStrategy, ShapeS.wiring, OpenGame.seq, OpenGame.tensor,
    OpenGame.decision, OpenGame.copyWire, OpenGame.idWire, OpenGame.costate,
    OpenGame.ofLens, Lens.toOpenGame]

/-- Bundled contexts are an exercised convenience API, not parallel
scaffolding. -/
example {X S Y R : Type*} (g : OpenGame X S Y R)
    (c : Context X Y R) (σ : g.Strategy) :
    g.IsEquilibriumAt c σ ↔ g.IsEquilibriumIn c.1 c.2 σ :=
  Iff.rfl

/-- The public API exposes the ordered tensor representation for any finite
heterogeneous simultaneous shape. -/
example (X Y : Fin 3 → Type) :
    OpenGameIso (ShapeN X Y) (ShapeN.tensorDecisions X Y) :=
  ShapeN.finTensorIso X Y

/-- The finite-horizon shape extends the existing two-stage presentation. -/
example (A : Type) :
    OpenGameIso (ShapeSeq 2 A) (ShapeS A A) :=
  ShapeSeq.twoStageIso A

/-- Arbitrary finite horizons compile to the existing kernel-game Nash
semantics. -/
example {n : Nat} {A : Type} (k : (Fin n → A) → Fin n → ℝ)
    (σ : ShapeSeq.Strategy n A) :
    (ShapeSeq n A).IsEquilibriumIn () k σ ↔
      (ShapeSeq.compileAction n A k).IsNash σ :=
  ShapeSeq.isEquilibriumIn_iff_isNash k σ

/-- Stage-specific action types retain the same exact compilation theorem. -/
example {n : Nat} {A : Fin n → Type}
    (k : (∀ i, A i) → Fin n → ℝ) (σ : ShapeSeqDep.Strategy A) :
    (ShapeSeqDep A).IsEquilibriumIn () k σ ↔
      (ShapeSeqDep.compileAction A k).IsNash σ :=
  ShapeSeqDep.isEquilibriumIn_iff_isNash k σ

/-- One-decision-per-player ownership makes agent and player deviations
coincide. -/
example {n : Nat} {ι : Type} [DecidableEq ι]
    {A : Fin n → Type} {owner : Fin n → ι}
    (howner : Function.Injective owner)
    (u : (∀ i, A i) → ι → ℝ) (σ : ShapeSeqDep.Strategy A) :
    ShapeSeqDep.IsAgentEquilibrium owner u σ ↔
      ShapeSeqDep.IsPlayerNash owner u σ :=
  ShapeSeqDep.isAgentEquilibrium_iff_isPlayerNash_of_injective
    howner u σ

/-- Two stages owned by one player strictly separate agent-form equilibrium
from player-form Nash. -/
example :
    ShapeSeqDep.IsAgentEquilibrium
        ShapeSeqDep.OwnershipExample.owner
        ShapeSeqDep.OwnershipExample.utility
        ShapeSeqDep.OwnershipExample.allFalse ∧
      ¬ShapeSeqDep.IsPlayerNash
        ShapeSeqDep.OwnershipExample.owner
        ShapeSeqDep.OwnershipExample.utility
        ShapeSeqDep.OwnershipExample.allFalse :=
  ShapeSeqDep.OwnershipExample.agentForm_not_playerForm

/-- Deterministic contexts embed into the coend-context quotient with their
visible history and continuation laws intact. -/
example {X Y R : Type} (x : X) (k : Y → R) (y : Y) :
    CoendContext.historyMarginal (CoendContext.ofDeterministic x k) =
        Math.FinPMF.pure x ∧
      CoendContext.responseAt (CoendContext.ofDeterministic x k) y =
        Math.FinPMF.pure (k y) := by
  simp

/-- The public coend API exposes its generating hidden-state
reparameterization equation. -/
example {X Y R Θ Ξ : Type} (f : Θ → Ξ)
    (prior : Math.FinPMF (Θ × X))
    (k : Ξ × Y → Math.FinPMF R) :
    CoendContext.mk
        { Hidden := Ξ
          prior := Math.FinPMF.map (fun z => (f z.1, z.2)) prior
          continuation := k } =
      CoendContext.mk
        { Hidden := Θ
          prior := prior
          continuation := fun z => k (f z.1, z.2) } :=
  CoendContext.reparam_eq f prior k

/-- ESS refines equilibrium of the corresponding symmetric open shape. -/
example {S : Type} {u : S → S → ℝ} {s : S}
    (h : GameTheory.IsESS u s) :
    (Evolutionary.SymmetricShape S).IsEquilibriumIn (fun _ => ())
      (Evolutionary.symmetricContinuation u) (Evolutionary.resident s) :=
  Evolutionary.isEquilibriumIn_of_isESS h

/-- Independent additive products preserve evolutionary stability. -/
example {S T : Type} {u : S → S → ℝ} {v : T → T → ℝ}
    {s : S} {t : T} (hs : GameTheory.IsESS u s)
    (ht : GameTheory.IsESS v t) :
    GameTheory.IsESS (Evolutionary.productPayoff u v) (s, t) :=
  Evolutionary.isESS_product hs ht

noncomputable section

open GameTheory

variable {ι : Type} [DecidableEq ι]
variable {G : KernelGame ι}

example (μ : PMF G.Profile) :
    (PrivateDevice.canonical G μ).IsEquilibrium ↔ G.IsCorrelatedEq μ :=
  PrivateDevice.canonical_isEquilibrium_iff_isCorrelatedEq μ

example (μ : PMF G.Profile) :
    (PrivateDevice.canonical G μ).IsExAnteEquilibrium ↔
      G.IsCoarseCorrelatedEq μ :=
  PrivateDevice.canonical_isExAnteEquilibrium_iff_isCoarseCorrelatedEq μ

example (k : Bool × Bool → ℝ × ℝ) (σ : Bool × (Bool → Bool)) :
    (ShapeS.conditioned Bool Bool).IsEquilibriumIn () k σ ↔
      (ShapeS.toEFG Bool Bool k).IsSubgamePerfectEq
        (ShapeS.toPureProfile Bool Bool σ) :=
  ShapeS.conditioned_isEquilibriumIn_iff_efg_isSubgamePerfectEq Bool Bool k σ

example (μ : PMF G.Profile) :
    (BroadcastDevice.canonical G μ).IsEquilibrium ↔
      ∀ σ, μ σ ≠ 0 → G.IsNash σ :=
  BroadcastDevice.canonical_isEquilibrium_iff_nashSupport μ

example :
    (ProbOpenGame.actionDecision NFG.MPAction ⊗ₚ
      ProbOpenGame.actionDecision NFG.MPAction).IsEquilibriumIn ((), ())
        (ProbOpenGame.boolPayoffPair NFG.matchingPennies)
        (Math.FinPMF.product Examples.matchingPenniesFairFin
          Examples.matchingPenniesFairFin) :=
  Examples.matchingPennies_fair_probabilistic_equilibrium

/-- The public probabilistic API records that convex equilibrium predicates
are not closed under the independent tensor. -/
example :
    ProbOpenGame.HasConvexEquilibria
        (ProbOpenGame.actionDecision Bool) ∧
      ¬ProbOpenGame.HasConvexEquilibria
        (ProbOpenGame.actionDecision Bool ⊗ₚ
          ProbOpenGame.actionDecision Bool) :=
  Examples.probabilistic_tensor_does_not_preserve_convexEquilibria

/-- Convex equilibrium predicates are likewise not closed under sequential
composition when composite laws must factor independently. -/
example :
    ProbOpenGame.HasConvexEquilibria
        (Examples.freeStrategyWire Bool Unit ℝ) ∧
      ¬ProbOpenGame.HasConvexEquilibria
        (Examples.freeStrategyWire Bool Unit ℝ ;ₚ
          Examples.freeStrategyWire Bool Unit ℝ) :=
  Examples.probabilistic_seq_does_not_preserve_convexEquilibria

example {X S Y R : Type*} [Math.AvgAlgebra S]
    (g : ProbOpenGame X S Y R) :
    ProbOpenGame.ConvexIso (ProbOpenGame.idWire X S ;ₚ g) g :=
  ProbOpenGame.convexSeqIdLeft g

example {X S Y R : Type*} [Math.AvgAlgebra R]
    (g : ProbOpenGame X S Y R) :
    ProbOpenGame.ConvexIso (g ;ₚ ProbOpenGame.idWire Y R) g :=
  ProbOpenGame.convexSeqIdRight g

example :
    Nonempty (ProbOpenGame.ConvexIso Examples.binaryHistorySource
      (ProbOpenGame.convexify Examples.binaryHistorySource)) ∧
    (ProbOpenGame.convexify Examples.binaryHistorySource ;ₚ
      Examples.echoHistory).IsEquilibriumIn () (fun _ => 0)
        (Math.FinPMF.product Examples.fairBoolFin Examples.fairBoolFin) ∧
    ¬(Examples.binaryHistorySource ;ₚ
      Examples.echoHistory).IsConvexEquilibriumIn () (fun _ => 0)
        (Math.FinPMF.product Examples.fairBoolFin Examples.fairBoolFin) :=
  Examples.convexIso_not_left_seq_congruence

example {X S Y R : Type*} [Math.AvgAlgebra S]
    (g : ProbOpenGame.Saturated X S Y R) :
    ProbOpenGame.ConvexIso
      (ProbOpenGame.Saturated.seq (ProbOpenGame.Saturated.id X S) g).1
      g.1 :=
  ProbOpenGame.Saturated.seqIdLeft g

example {X S Y R : Type*} [Math.AvgAlgebra R]
    (g : ProbOpenGame.Saturated X S Y R) :
    ProbOpenGame.ConvexIso
      (ProbOpenGame.Saturated.seq g
        (ProbOpenGame.Saturated.id Y R)).1 g.1 :=
  ProbOpenGame.Saturated.seqIdRight g

end

end OpenGames.Tests
