/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/

import GameTheory.Languages.OpenGame

/-!
# Tests for Deterministic Open Games

These compilation tests exercise the typed wiring diagram for a two-move game
and check its equilibrium predicate by reduction.
-/

namespace OpenGames.Tests

open scoped OpenGames

/-- The standard two-move diagram: decide, copy the first move, decide again,
then deliver both players' cooutcomes through a costate. -/
def twoMove {A B : Type} (u : A × B → ℝ × ℝ) :
    OpenGame Unit Unit Unit Unit :=
  ShapeS.wiring A B ;ₒ OpenGame.costate u

/-- Embed the usual leader action and follower contingent plan into the
strategy type generated by the wiring diagram. -/
def twoMoveStrategy {A B : Type} (u : A × B → ℝ × ℝ)
    (first : A) (second : A → B) : (twoMove u).Strategy :=
  (((fun _ => first), ((), ((), second))), ())

/-- Plain sequential composition checks the follower only at the realized
history.  The first mover, however, compares deviations after the fixed
contingent follower plan has reacted to each alternative. -/
theorem twoMove_equilibrium_iff {A B : Type} (u : A × B → ℝ × ℝ)
    (first : A) (second : A → B) :
    (twoMove u).IsEquilibriumIn () (fun _ => ())
        (twoMoveStrategy u first second) ↔
      (∀ a, (u (first, second first)).1 ≥ (u (a, second a)).1) ∧
      (∀ b, (u (first, second first)).2 ≥ (u (first, b)).2) := by
  simp [twoMove, twoMoveStrategy, ShapeS.wiring, OpenGame.seq, OpenGame.tensor,
    OpenGame.decision, OpenGame.copyWire, OpenGame.idWire, OpenGame.costate,
    OpenGame.ofLens, Lens.toOpenGame]

/-- Bundled contexts are an exercised convenience API, not parallel
scaffolding. -/
example {X S Y R : Type*} (g : OpenGame X S Y R)
    (c : Context X Y R) (σ : g.Strategy) :
    g.IsEquilibriumAt c σ ↔ g.IsEquilibriumIn c.1 c.2 σ :=
  Iff.rfl

/-- The public API exposes the ordered tensor representation for any finite
heterogeneous simultaneous shape. -/
example (X Y : Fin 3 → Type) :
    OpenGameIso (ShapeN X Y) (ShapeN.tensorDecisions X Y) :=
  ShapeN.finTensorIso X Y

noncomputable section

open GameTheory

variable {ι : Type} [DecidableEq ι]
variable {G : KernelGame ι}

example (μ : PMF G.Profile) :
    (PrivateDevice.canonical G μ).IsEquilibrium ↔ G.IsCorrelatedEq μ :=
  PrivateDevice.canonical_isEquilibrium_iff_isCorrelatedEq μ

example (μ : PMF G.Profile) :
    (PrivateDevice.canonical G μ).IsExAnteEquilibrium ↔
      G.IsCoarseCorrelatedEq μ :=
  PrivateDevice.canonical_isExAnteEquilibrium_iff_isCoarseCorrelatedEq μ

example (k : Bool × Bool → ℝ × ℝ) (σ : Bool × (Bool → Bool)) :
    (ShapeS.conditioned Bool Bool).IsEquilibriumIn () k σ ↔
      (ShapeS.toEFG Bool Bool k).IsSubgamePerfectEq
        (ShapeS.toPureProfile Bool Bool σ) :=
  ShapeS.conditioned_isEquilibriumIn_iff_efg_isSubgamePerfectEq Bool Bool k σ

example (μ : PMF G.Profile) :
    (BroadcastDevice.canonical G μ).IsEquilibrium ↔
      ∀ σ, μ σ ≠ 0 → G.IsNash σ :=
  BroadcastDevice.canonical_isEquilibrium_iff_nashSupport μ

example :
    (ProbOpenGame.actionDecision NFG.MPAction ⊗ₚ
      ProbOpenGame.actionDecision NFG.MPAction).IsEquilibriumIn ((), ())
        (ProbOpenGame.boolPayoffPair NFG.matchingPennies)
        (Math.FinPMF.product Examples.matchingPenniesFairFin
          Examples.matchingPenniesFairFin) :=
  Examples.matchingPennies_fair_probabilistic_equilibrium

/-- The public probabilistic API records that convex equilibrium predicates
are not closed under the independent tensor. -/
example :
    ProbOpenGame.HasConvexEquilibria
        (ProbOpenGame.actionDecision Bool) ∧
      ¬ProbOpenGame.HasConvexEquilibria
        (ProbOpenGame.actionDecision Bool ⊗ₚ
          ProbOpenGame.actionDecision Bool) :=
  Examples.probabilistic_tensor_does_not_preserve_convexEquilibria

/-- Convex equilibrium predicates are likewise not closed under sequential
composition when composite laws must factor independently. -/
example :
    ProbOpenGame.HasConvexEquilibria
        (Examples.freeStrategyWire Bool Unit ℝ) ∧
      ¬ProbOpenGame.HasConvexEquilibria
        (Examples.freeStrategyWire Bool Unit ℝ ;ₚ
          Examples.freeStrategyWire Bool Unit ℝ) :=
  Examples.probabilistic_seq_does_not_preserve_convexEquilibria

example {X S Y R : Type*} [Math.AvgAlgebra S]
    (g : ProbOpenGame X S Y R) :
    ProbOpenGame.ConvexIso (ProbOpenGame.idWire X S ;ₚ g) g :=
  ProbOpenGame.convexSeqIdLeft g

example {X S Y R : Type*} [Math.AvgAlgebra R]
    (g : ProbOpenGame X S Y R) :
    ProbOpenGame.ConvexIso (g ;ₚ ProbOpenGame.idWire Y R) g :=
  ProbOpenGame.convexSeqIdRight g

end

end OpenGames.Tests
