/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/

import GameTheory.Languages.OpenGame

/-!
# Tests for Deterministic Open Games

These compilation tests exercise the typed wiring diagram for a two-move game
and check its equilibrium predicate by reduction.
-/

namespace OpenGames.Tests

open scoped OpenGames

/-- The standard two-move diagram: decide, copy the first move, decide again,
then deliver both players' cooutcomes through a costate. -/
def twoMove {A B : Type} (u : A × B → ℝ × ℝ) :
    OpenGame Unit Unit Unit Unit :=
  ShapeS.wiring A B ;ₒ OpenGame.costate u

/-- Embed the usual leader action and follower contingent plan into the
strategy type generated by the wiring diagram. -/
def twoMoveStrategy {A B : Type} (u : A × B → ℝ × ℝ)
    (first : A) (second : A → B) : (twoMove u).Strategy :=
  (((fun _ => first), ((), ((), second))), ())

/-- Plain sequential composition checks the follower only at the realized
history.  The first mover, however, compares deviations after the fixed
contingent follower plan has reacted to each alternative. -/
theorem twoMove_equilibrium_iff {A B : Type} (u : A × B → ℝ × ℝ)
    (first : A) (second : A → B) :
    (twoMove u).IsEquilibriumIn () (fun _ => ())
        (twoMoveStrategy u first second) ↔
      (∀ a, (u (first, second first)).1 ≥ (u (a, second a)).1) ∧
      (∀ b, (u (first, second first)).2 ≥ (u (first, b)).2) := by
  simp [twoMove, twoMoveStrategy, ShapeS.wiring, OpenGame.seq, OpenGame.tensor,
    OpenGame.decision, OpenGame.copyWire, OpenGame.idWire, OpenGame.costate,
    OpenGame.ofLens, Lens.toOpenGame]

/-- Bundled contexts are an exercised convenience API, not parallel
scaffolding. -/
example {X S Y R : Type*} (g : OpenGame X S Y R)
    (c : Context X Y R) (σ : g.Strategy) :
    g.IsEquilibriumAt c σ ↔ g.IsEquilibriumIn c.1 c.2 σ :=
  Iff.rfl

/-- The public API exposes the ordered tensor representation for any finite
heterogeneous simultaneous shape. -/
example (X Y : Fin 3 → Type) :
    OpenGameIso (ShapeN X Y) (ShapeN.tensorDecisions X Y) :=
  ShapeN.finTensorIso X Y

/-- The finite-horizon shape extends the existing two-stage presentation. -/
example (A : Type) :
    OpenGameIso (ShapeSeq 2 A) (ShapeS A A) :=
  ShapeSeq.twoStageIso A

/-- Arbitrary finite horizons compile to the existing kernel-game Nash
semantics. -/
example {n : Nat} {A : Type} (k : (Fin n → A) → Fin n → ℝ)
    (σ : ShapeSeq.Strategy n A) :
    (ShapeSeq n A).IsEquilibriumIn () k σ ↔
      (ShapeSeq.compileAction n A k).IsNash σ :=
  ShapeSeq.isEquilibriumIn_iff_isNash k σ

/-- Stage-specific action types retain the same exact compilation theorem. -/
example {n : Nat} {A : Fin n → Type}
    (k : (∀ i, A i) → Fin n → ℝ) (σ : ShapeSeqDep.Strategy A) :
    (ShapeSeqDep A).IsEquilibriumIn () k σ ↔
      (ShapeSeqDep.compileAction A k).IsNash σ :=
  ShapeSeqDep.isEquilibriumIn_iff_isNash k σ

/-- Finite-horizon conditioning tests every counterfactual predecessor
profile and therefore strengthens the plain sequential predicate. -/
example {n : Nat} {A : Fin n → Type}
    (k : (∀ i, A i) → Fin n → ℝ) (σ : ShapeSeqDep.Strategy A)
    (hσ : (ShapeSeqDep.conditioned A).IsEquilibriumIn () k σ) :
    (ShapeSeqDep A).IsEquilibriumIn () k σ :=
  ShapeSeqDep.conditioned_implies_plain k σ hσ

/-- Arbitrary contingent deviations in the conditioned predicate reduce
exactly to changing one action at the reached counterfactual history. -/
example {n : Nat} {A : Fin n → Type}
    (k : (∀ i, A i) → Fin n → ℝ) (σ : ShapeSeqDep.Strategy A) :
    (ShapeSeqDep.conditioned A).IsEquilibriumIn () k σ ↔
      ShapeSeqDep.IsOneShotConditionedEquilibrium k σ :=
  ShapeSeqDep.conditioned_isEquilibriumIn_iff_oneShot k σ

/-- Sparse typed decision DAGs retain exact strategic-form compilation. -/
example {n : Nat} (D : DecisionDAG n) (A : Fin n → Type)
    (k : (∀ i, A i) → Fin n → ℝ) (σ : ShapeDAG.Strategy D A) :
    (OpenGames.ShapeDAG D A).IsEquilibriumIn () k σ ↔
      (ShapeDAG.compileAction D A k).IsNash σ :=
  ShapeDAG.isEquilibriumIn_iff_isNash D A k σ

/-- Node ownership on a sparse DAG compiles player-level joint plan
deviations to the common kernel-game semantics. -/
example {n : Nat} {Player : Type} [DecidableEq Player]
    (D : DecisionDAG n) (owner : Fin n → Player) (A : Fin n → Type)
    (u : (∀ i, A i) → Player → ℝ) (σ : ShapeDAG.Strategy D A) :
    ShapeDAG.IsPlayerNash D owner u σ ↔
      (ShapeDAG.compileOwned D owner A u).IsNash
        (OwnedProfile.group owner σ) :=
  ShapeDAG.isPlayerNash_iff_kernelNash D owner u σ

/-- Player-level stability remains stronger than nodewise agent-form
stability on an arbitrary sparse graph. -/
example {n : Nat} {Player : Type} [DecidableEq Player]
    {D : DecisionDAG n} {owner : Fin n → Player} {A : Fin n → Type}
    {u : (∀ i, A i) → Player → ℝ} {σ : ShapeDAG.Strategy D A}
    (hσ : ShapeDAG.IsPlayerNash D owner u σ) :
    ShapeDAG.IsAgentEquilibrium D owner u σ :=
  hσ.isAgentEquilibrium

/-- The existing deviation-family calculus recovers DAG owner-fibre Nash
exactly, with no graph-specific deviation-family definition. -/
example {n : Nat} {Player : Type} [DecidableEq Player]
    (D : DecisionDAG n) (owner : Fin n → Player) {A : Fin n → Type}
    (u : (∀ i, A i) → Player → ℝ) (σ : ShapeDAG.Strategy D A) :
    DeviationFamily.IsStableUnder
        (DeviationFamily.fiber
          (S := fun i => ShapeDAG.History D A i → A i) owner)
        (ShapeDAG.realize D) u σ ↔
      ShapeDAG.IsPlayerNash D owner u σ :=
  ShapeDAG.isStableUnder_fiber_iff_isPlayerNash D owner u σ

/-- Sparse local stochastic kernels are evaluated by the existing
order-independent MAID/Bayesian-network factorization. -/
example {n : Nat} (D : DecisionDAG n) (A : Fin n → Type)
    [∀ i, Fintype (A i)] [∀ i, DecidableEq (A i)]
    [∀ i, Inhabited (A i)] (κ : ShapeDAG.Causal.LocalKernel D A) :
    (ShapeDAG.Causal.eval D A κ).toPMF =
      MAID.evalAssignDist (ShapeDAG.Causal.maidStruct D A)
        (ShapeDAG.Causal.sem D A κ)
        (MAID.defaultPolicy (ShapeDAG.Causal.maidStruct D A)) :=
  ShapeDAG.Causal.eval_toPMF D A κ

/-- Pure contingent plans embed as point kernels and recover exactly the
existing well-founded deterministic realization. -/
example {n : Nat} (D : DecisionDAG n) (A : Fin n → Type)
    [∀ i, Fintype (A i)] [∀ i, DecidableEq (A i)]
    [∀ i, Inhabited (A i)] (σ : ShapeDAG.Strategy D A) :
    ShapeDAG.Causal.eval D A (ShapeDAG.Causal.deterministic D σ) =
      Math.FinPMF.pure (ShapeDAG.realize D σ) :=
  ShapeDAG.Causal.eval_deterministic D A σ

/-- Fixed chance nodes and player-owned behavioral kernels form an ordinary
strategic game with exact kernel compilation. -/
example {n : Nat} {Player : Type} [DecidableEq Player]
    (D : DecisionDAG n) (owner : Fin n → Option Player)
    (A : Fin n → Type)
    [∀ i, Fintype (A i)] [∀ i, DecidableEq (A i)]
    [∀ i, Inhabited (A i)] (chance : ShapeDAG.Causal.LocalKernel D A)
    (u : (∀ i, A i) → Player → ℝ)
    (policy : ∀ player : Player,
      ShapeDAG.Causal.PlayerPolicy (Player := Player) D A player) :
    ShapeDAG.Causal.IsBehavioralNash D owner A chance u policy ↔
      (ShapeDAG.Causal.compileBehavioral D owner A chance u).IsNash policy :=
  ShapeDAG.Causal.isBehavioralNash_iff_kernelNash
    D owner A chance u policy

/-- Sparse graph conditioning has an exact one-action presentation without
claiming an EFG subgame interpretation at imperfect information sets. -/
example {n : Nat} (D : DecisionDAG n) {A : Fin n → Type}
    (k : (∀ i, A i) → Fin n → ℝ) (σ : ShapeDAG.Strategy D A) :
    ShapeDAG.IsConditionedEquilibrium D k σ ↔
      ShapeDAG.IsOneShotConditionedEquilibrium D k σ :=
  ShapeDAG.isConditionedEquilibrium_iff_isOneShot D k σ

/-- With no causal ancestors, graph conditioning adds no tests beyond plain
simultaneous equilibrium. -/
example {n : Nat} {A : Fin n → Type}
    (k : (∀ i, A i) → Fin n → ℝ)
    (σ : ShapeDAG.Strategy (DecisionDAG.discrete n) A) :
    (ShapeDAG.conditioned (DecisionDAG.discrete n) A).IsEquilibriumIn () k σ ↔
      (OpenGames.ShapeDAG (DecisionDAG.discrete n) A).IsEquilibriumIn () k σ :=
  ShapeDAG.conditioned_discrete_iff_plain k σ

/-- Consequently the conditioned edgeless DAG is itself isomorphic to the
closed simultaneous shape. -/
example {n : Nat} (A : Fin n → Type) :
    OpenGameIso
      (ShapeDAG.conditioned (DecisionDAG.discrete n) A)
      (ShapeN (fun _ : Fin n => Unit) A) :=
  ShapeDAG.discreteConditionedIso A

/-- The edgeless decision DAG coheres with the existing closed simultaneous
shape, including the contractible boundary reindexing. -/
example {n : Nat} (A : Fin n → Type) :
    OpenGameIso
      (OpenGames.ShapeDAG (DecisionDAG.discrete n) A)
      (ShapeN (fun _ : Fin n => Unit) A) :=
  ShapeDAG.discreteIso A

/-- A plan change cannot affect nodes outside its causal descendant cone. -/
example {n : Nat} (D : DecisionDAG n) {A : Fin n → Type}
    (σ : ShapeDAG.Strategy D A) (i j : Fin n)
    (deviation : ShapeDAG.History D A i → A i)
    (hne : j ≠ i) (hnot : ¬ D.IsAncestor i j) :
    ShapeDAG.realizeAt D (Function.update σ i deviation) j =
      ShapeDAG.realizeAt D σ j :=
  ShapeDAG.realizeAt_update_of_not_ancestor D σ i deviation j hne hnot

/-- Observing every earlier node recovers the existing dependent sequential
shape, including its equilibrium predicate. -/
example {n : Nat} (A : Fin n → Type) :
    OpenGameIso
      (OpenGames.ShapeDAG (DecisionDAG.complete n) A)
      (OpenGames.ShapeSeqDep A) :=
  ShapeDAG.completeIso A

/-- The complete-DAG identification also transports the strengthened
counterfactual equilibrium semantics exactly. -/
example {n : Nat} (A : Fin n → Type) :
    OpenGameIso
      (ShapeDAG.conditioned (DecisionDAG.complete n) A)
      (ShapeSeqDep.conditioned A) :=
  ShapeDAG.completeConditionedIso A

/-- The predecessor-profile presentation of conditioning covers every
dependent prefix history. -/
example {n : Nat} {A : Fin n → Type} (σ : ShapeSeqDep.Strategy A)
    (i : Fin n) (h : ShapeSeqDep.History A i) :
    ∃ τ : ShapeSeqDep.Strategy A,
      (∀ j, i.val ≤ j.val → τ j = σ j) ∧
      ∀ j, ShapeSeqDep.realize τ (ShapeSeqDep.priorIndex i j) = h j :=
  ShapeSeqDep.exists_profile_realizing_history σ i h

noncomputable section

/-- Finite sequential open-game profiles are exactly pure policies of the
canonical agent-form MAID. -/
example {n : Nat} (A : Fin n → Type)
    [∀ i, Fintype (A i)] [∀ i, DecidableEq (A i)]
    [∀ i, Inhabited (A i)] :
    MAID.PurePolicy (ShapeSeqDep.MAIDBridge.sequentialStruct A) ≃
      ShapeSeqDep.Strategy A :=
  ShapeSeqDep.MAIDBridge.purePolicyEquiv A

/-- The MAID bridge preserves the dependent action path exactly. -/
example {n : Nat} (A : Fin n → Type)
    [∀ i, Fintype (A i)] [∀ i, DecidableEq (A i)]
    [∀ i, Inhabited (A i)] :
    MAID.TAssign (ShapeSeqDep.MAIDBridge.sequentialStruct A) ≃
      (∀ i, A i) :=
  ShapeSeqDep.MAIDBridge.assignPathEquiv A

/-- Canonical MAID utility agrees with the open-game continuation on every
assignment, not merely on realized paths. -/
example {n : Nat} (A : Fin n → Type)
    [∀ i, Fintype (A i)] [∀ i, DecidableEq (A i)]
    [∀ i, Inhabited (A i)] (k : (∀ i, A i) → Fin n → ℝ)
    (a : MAID.TAssign (ShapeSeqDep.MAIDBridge.sequentialStruct A))
    (p : Fin n) :
    MAID.utilityOf (ShapeSeqDep.MAIDBridge.sequentialStruct A)
        (ShapeSeqDep.MAIDBridge.sequentialSem A k) a p =
      k (ShapeSeqDep.MAIDBridge.pathOfAssign A a) p :=
  ShapeSeqDep.MAIDBridge.utilityOf_eq A k a p

/-- Native pure-policy MAID evaluation produces exactly the open-game
realization on decision coordinates. -/
example {n : Nat} (A : Fin n → Type)
    [∀ i, Fintype (A i)] [∀ i, DecidableEq (A i)]
    [∀ i, Inhabited (A i)] (k : (∀ i, A i) → Fin n → ℝ)
    (σ : ShapeSeqDep.Strategy A) :
    PMF.map (ShapeSeqDep.MAIDBridge.pathOfAssign A)
        (MAID.evalAssignDist (ShapeSeqDep.MAIDBridge.sequentialStruct A)
          (ShapeSeqDep.MAIDBridge.sequentialSem A k)
          (MAID.pureToPolicy (ShapeSeqDep.MAIDBridge.toPurePolicy A σ))) =
      PMF.pure (ShapeSeqDep.realize σ) :=
  ShapeSeqDep.MAIDBridge.map_evalAssignDist_toPurePolicy A k σ

/-- Pure contingent-plan equilibrium agrees exactly with native pure-policy
Nash equilibrium in the canonical MAID. -/
example {n : Nat} (A : Fin n → Type)
    [∀ i, Fintype (A i)] [∀ i, DecidableEq (A i)]
    [∀ i, Inhabited (A i)] (k : (∀ i, A i) → Fin n → ℝ)
    (σ : ShapeSeqDep.Strategy A) :
    (ShapeSeqDep A).IsEquilibriumIn () k σ ↔
      MAID.IsPurePolicyNash (ShapeSeqDep.MAIDBridge.sequentialStruct A)
        (ShapeSeqDep.MAIDBridge.sequentialSem A k)
        (ShapeSeqDep.MAIDBridge.toPurePolicy A σ) :=
  ShapeSeqDep.MAIDBridge.isEquilibriumIn_iff_isPurePolicyNash A k σ

/-- The same equilibrium remains exact after allowing randomization over
complete contingent MAID plans. -/
example {n : Nat} (A : Fin n → Type)
    [∀ i, Fintype (A i)] [∀ i, DecidableEq (A i)]
    [∀ i, Inhabited (A i)] (k : (∀ i, A i) → Fin n → ℝ)
    (σ : ShapeSeqDep.Strategy A) :
    let G := MAID.purePolicyKernelGame
      (ShapeSeqDep.MAIDBridge.sequentialStruct A)
      (ShapeSeqDep.MAIDBridge.sequentialSem A k)
    (ShapeSeqDep A).IsEquilibriumIn () k σ ↔
      G.mixedExtension.IsNash
        (G.pureMixedProfile (ShapeSeqDep.MAIDBridge.toPurePolicy A σ)) :=
  ShapeSeqDep.MAIDBridge.isEquilibriumIn_iff_mixedPurePolicyNash A k σ

/-- Perfect recall upgrades the same result to arbitrary behavioral
randomization at individual MAID information sets. -/
example {n : Nat} (A : Fin n → Type)
    [∀ i, Fintype (A i)] [∀ i, DecidableEq (A i)]
    [∀ i, Inhabited (A i)] (k : (∀ i, A i) → Fin n → ℝ)
    (σ : ShapeSeqDep.Strategy A) :
    (ShapeSeqDep A).IsEquilibriumIn () k σ ↔
      (MAID.toKernelGame (ShapeSeqDep.MAIDBridge.sequentialStruct A)
        (ShapeSeqDep.MAIDBridge.sequentialSem A k)).IsNash
        (MAID.pureToPolicy
          (ShapeSeqDep.MAIDBridge.toPurePolicy A σ)) :=
  ShapeSeqDep.MAIDBridge.isEquilibriumIn_iff_behavioralNash A k σ

/-- The canonical agent-form sequential MAID has perfect recall. -/
example {n : Nat} (A : Fin n → Type)
    [∀ i, Fintype (A i)] [∀ i, DecidableEq (A i)]
    [∀ i, Inhabited (A i)] :
    (ShapeSeqDep.MAIDBridge.sequentialStruct A).PerfectRecall :=
  ShapeSeqDep.MAIDBridge.sequentialStruct_perfectRecall A

/-- Reusing the repository's general MAID-to-EFG translation preserves the
entire strategic kernel up to bisimulation. -/
example {n : Nat} (A : Fin n → Type)
    [∀ i, Fintype (A i)] [∀ i, DecidableEq (A i)]
    [∀ i, Inhabited (A i)] (k : (∀ i, A i) → Fin n → ℝ) :
    GameTheory.KernelGame.Bisimulation
      (MAID.toKernelGame (ShapeSeqDep.MAIDBridge.sequentialStruct A)
        (ShapeSeqDep.MAIDBridge.sequentialSem A k))
      ((ShapeSeqDep.MAIDBridge.toEFG A k).toKernelGame) :=
  ShapeSeqDep.MAIDBridge.toEFGBisimulation A k

/-- The pure strategic form is preserved separately from the behavioral
kernel, and plain open equilibrium becomes ordinary EFG Nash. -/
example {n : Nat} (A : Fin n → Type)
    [∀ i, Fintype (A i)] [∀ i, DecidableEq (A i)]
    [∀ i, Inhabited (A i)] (k : (∀ i, A i) → Fin n → ℝ)
    (σ : ShapeSeqDep.Strategy A) :
    (ShapeSeqDep A).IsEquilibriumIn () k σ ↔
      ((ShapeSeqDep.MAIDBridge.toEFG A k).toStrategicKernelGame).IsNash
        (ShapeSeqDep.MAIDBridge.toEFGPureProfile A k σ) :=
  ShapeSeqDep.MAIDBridge.isEquilibriumIn_iff_efgIsNash A k σ

/-- The canonical finite-horizon EFG is perfect-information, so its SPE and
one-shot-deviation predicates coincide. -/
example {n : Nat} (A : Fin n → Type)
    [∀ i, Fintype (A i)] [∀ i, DecidableEq (A i)]
    [∀ i, Inhabited (A i)] (k : (∀ i, A i) → Fin n → ℝ)
    (σ : ShapeSeqDep.Strategy A) :
    EFG.IsPerfectInfo (ShapeSeqDep.MAIDBridge.toEFG A k).tree ∧
      ((ShapeSeqDep.MAIDBridge.toEFG A k).IsSubgamePerfectEq
          (ShapeSeqDep.MAIDBridge.toEFGPureProfile A k σ) ↔
        EFG.HasNoOneShotDeviation (ShapeSeqDep.MAIDBridge.toEFG A k)
          (ShapeSeqDep.MAIDBridge.toEFGPureProfile A k σ)) :=
  ⟨ShapeSeqDep.MAIDBridge.toEFG_isPerfectInfo A k,
    ShapeSeqDep.MAIDBridge.efg_isSubgamePerfectEq_iff_hasNoOneShotDeviation
      A k σ⟩

/-- At every finite heterogeneous horizon, intrinsic conditioning is exactly
subgame-perfect equilibrium in the induced EFG. -/
example {n : Nat} (A : Fin n → Type)
    [∀ i, Fintype (A i)] [∀ i, DecidableEq (A i)]
    [∀ i, Inhabited (A i)] (k : (∀ i, A i) → Fin n → ℝ)
    (σ : ShapeSeqDep.Strategy A) :
    (ShapeSeqDep.conditioned A).IsEquilibriumIn () k σ ↔
      (ShapeSeqDep.MAIDBridge.toEFG A k).IsSubgamePerfectEq
        (ShapeSeqDep.MAIDBridge.toEFGPureProfile A k σ) :=
  ShapeSeqDep.MAIDBridge.conditioned_isEquilibriumIn_iff_efgIsSubgamePerfect
    A k σ

/-- Perfect recall transfers through the existing MAID-to-EFG bridge. -/
example {n : Nat} (A : Fin n → Type)
    [∀ i, Fintype (A i)] [∀ i, DecidableEq (A i)]
    [∀ i, Inhabited (A i)] (k : (∀ i, A i) → Fin n → ℝ) :
    EFG.PerfectRecall (ShapeSeqDep.MAIDBridge.toEFG A k).tree :=
  ShapeSeqDep.MAIDBridge.toEFG_perfectRecall A k

end

/-- One-decision-per-player ownership makes agent and player deviations
coincide. -/
example {n : Nat} {ι : Type} [DecidableEq ι]
    {A : Fin n → Type} {owner : Fin n → ι}
    (howner : Function.Injective owner)
    (u : (∀ i, A i) → ι → ℝ) (σ : ShapeSeqDep.Strategy A) :
    ShapeSeqDep.IsAgentEquilibrium owner u σ ↔
      ShapeSeqDep.IsPlayerNash owner u σ :=
  ShapeSeqDep.isAgentEquilibrium_iff_isPlayerNash_of_injective
    howner u σ

/-- The generic single-stage deviation family recovers agent form exactly. -/
example {n : Nat} {ι : Type} [DecidableEq ι]
    {A : Fin n → Type} (owner : Fin n → ι)
    (u : (∀ i, A i) → ι → ℝ) (σ : ShapeSeqDep.Strategy A) :
    DeviationFamily.IsStableUnder
        (DeviationFamily.single
          (S := fun i => ShapeSeqDep.History A i → A i))
        ShapeSeqDep.realize (fun path i => u path (owner i)) σ ↔
      ShapeSeqDep.IsAgentEquilibrium owner u σ :=
  ShapeSeqDep.isStableUnder_single_iff_isAgentEquilibrium owner u σ

/-- Owner-fibre deviation families recover player-form Nash exactly. -/
example {n : Nat} {ι : Type} [DecidableEq ι]
    {A : Fin n → Type} (owner : Fin n → ι)
    (u : (∀ i, A i) → ι → ℝ) (σ : ShapeSeqDep.Strategy A) :
    DeviationFamily.IsStableUnder
        (DeviationFamily.fiber
          (S := fun i => ShapeSeqDep.History A i → A i) owner)
        ShapeSeqDep.realize u σ ↔
      ShapeSeqDep.IsPlayerNash owner u σ :=
  ShapeSeqDep.isStableUnder_fiber_iff_isPlayerNash owner u σ

/-- Two stages owned by one player strictly separate agent-form equilibrium
from player-form Nash. -/
example :
    ShapeSeqDep.IsAgentEquilibrium
        ShapeSeqDep.OwnershipExample.owner
        ShapeSeqDep.OwnershipExample.utility
        ShapeSeqDep.OwnershipExample.allFalse ∧
      ¬ShapeSeqDep.IsPlayerNash
        ShapeSeqDep.OwnershipExample.owner
        ShapeSeqDep.OwnershipExample.utility
        ShapeSeqDep.OwnershipExample.allFalse :=
  ShapeSeqDep.OwnershipExample.agentForm_not_playerForm

/-- Deterministic contexts embed into the coend-context quotient with their
visible history and continuation laws intact. -/
example {X Y R : Type} (x : X) (k : Y → R) (y : Y) :
    CoendContext.historyMarginal (CoendContext.ofDeterministic x k) =
        Math.FinPMF.pure x ∧
      CoendContext.responseAt (CoendContext.ofDeterministic x k) y =
        Math.FinPMF.pure (k y) := by
  simp

/-- The coend context exposes a quotient-invariant joint response whose first
marginal is the visible history law. -/
example {X Y R : Type} (c : CoendContext X Y R) (policy : X → Y) :
    Math.FinPMF.map Prod.fst (CoendContext.jointResponse c policy) =
      CoendContext.historyMarginal c :=
  CoendContext.map_fst_jointResponse c policy

/-- Deterministic contexts give the expected point-mass joint response. -/
example {X Y R : Type} (x : X) (k : Y → R) (policy : X → Y) :
    CoendContext.jointResponse (CoendContext.ofDeterministic x k) policy =
      Math.FinPMF.pure (x, k (policy x)) := by
  simp

/-- The public coend API exposes its generating hidden-state
reparameterization equation. -/
example {X Y R Θ Ξ : Type} (f : Θ → Ξ)
    (prior : Math.FinPMF (Θ × X))
    (k : Ξ × Y → Math.FinPMF R) :
    CoendContext.mk
        { Hidden := Ξ
          prior := Math.FinPMF.map (fun z => (f z.1, z.2)) prior
          continuation := k } =
      CoendContext.mk
        { Hidden := Θ
          prior := prior
          continuation := fun z => k (f z.1, z.2) } :=
  CoendContext.reparam_eq f prior k

/-- ESS refines equilibrium of the corresponding symmetric open shape. -/
example {S : Type} {u : S → S → ℝ} {s : S}
    (h : GameTheory.IsESS u s) :
    (Evolutionary.SymmetricShape S).IsEquilibriumIn (fun _ => ())
      (Evolutionary.symmetricContinuation u) (Evolutionary.resident s) :=
  Evolutionary.isEquilibriumIn_of_isESS h

/-- Independent additive products preserve evolutionary stability. -/
example {S T : Type} {u : S → S → ℝ} {v : T → T → ℝ}
    {s : S} {t : T} (hs : GameTheory.IsESS u s)
    (ht : GameTheory.IsESS v t) :
    GameTheory.IsESS (Evolutionary.productPayoff u v) (s, t) :=
  Evolutionary.isESS_product hs ht

noncomputable section

open GameTheory

variable {ι : Type} [DecidableEq ι]
variable {G : KernelGame ι}

example (μ : PMF G.Profile) :
    (PrivateDevice.canonical G μ).IsEquilibrium ↔ G.IsCorrelatedEq μ :=
  PrivateDevice.canonical_isEquilibrium_iff_isCorrelatedEq μ

example (μ : PMF G.Profile) :
    (PrivateDevice.canonical G μ).IsExAnteEquilibrium ↔
      G.IsCoarseCorrelatedEq μ :=
  PrivateDevice.canonical_isExAnteEquilibrium_iff_isCoarseCorrelatedEq μ

example (k : Bool × Bool → ℝ × ℝ) (σ : Bool × (Bool → Bool)) :
    (ShapeS.conditioned Bool Bool).IsEquilibriumIn () k σ ↔
      (ShapeS.toEFG Bool Bool k).IsSubgamePerfectEq
        (ShapeS.toPureProfile Bool Bool σ) :=
  ShapeS.conditioned_isEquilibriumIn_iff_efg_isSubgamePerfectEq Bool Bool k σ

example (μ : PMF G.Profile) :
    (BroadcastDevice.canonical G μ).IsEquilibrium ↔
      ∀ σ, μ σ ≠ 0 → G.IsNash σ :=
  BroadcastDevice.canonical_isEquilibrium_iff_nashSupport μ

example :
    (ProbOpenGame.actionDecision NFG.MPAction ⊗ₚ
      ProbOpenGame.actionDecision NFG.MPAction).IsEquilibriumIn ((), ())
        (ProbOpenGame.boolPayoffPair NFG.matchingPennies)
        (Math.FinPMF.product Examples.matchingPenniesFairFin
          Examples.matchingPenniesFairFin) :=
  Examples.matchingPennies_fair_probabilistic_equilibrium

/-- The public probabilistic API records that convex equilibrium predicates
are not closed under the independent tensor. -/
example :
    ProbOpenGame.HasConvexEquilibria
        (ProbOpenGame.actionDecision Bool) ∧
      ¬ProbOpenGame.HasConvexEquilibria
        (ProbOpenGame.actionDecision Bool ⊗ₚ
          ProbOpenGame.actionDecision Bool) :=
  Examples.probabilistic_tensor_does_not_preserve_convexEquilibria

/-- Convex equilibrium predicates are likewise not closed under sequential
composition when composite laws must factor independently. -/
example :
    ProbOpenGame.HasConvexEquilibria
        (Examples.freeStrategyWire Bool Unit ℝ) ∧
      ¬ProbOpenGame.HasConvexEquilibria
        (Examples.freeStrategyWire Bool Unit ℝ ;ₚ
          Examples.freeStrategyWire Bool Unit ℝ) :=
  Examples.probabilistic_seq_does_not_preserve_convexEquilibria

example {X S Y R : Type*} [Math.AvgAlgebra S]
    (g : ProbOpenGame X S Y R) :
    ProbOpenGame.ConvexIso (ProbOpenGame.idWire X S ;ₚ g) g :=
  ProbOpenGame.convexSeqIdLeft g

example {X S Y R : Type*} [Math.AvgAlgebra R]
    (g : ProbOpenGame X S Y R) :
    ProbOpenGame.ConvexIso (g ;ₚ ProbOpenGame.idWire Y R) g :=
  ProbOpenGame.convexSeqIdRight g

example :
    Nonempty (ProbOpenGame.ConvexIso Examples.binaryHistorySource
      (ProbOpenGame.convexify Examples.binaryHistorySource)) ∧
    (ProbOpenGame.convexify Examples.binaryHistorySource ;ₚ
      Examples.echoHistory).IsEquilibriumIn () (fun _ => 0)
        (Math.FinPMF.product Examples.fairBoolFin Examples.fairBoolFin) ∧
    ¬(Examples.binaryHistorySource ;ₚ
      Examples.echoHistory).IsConvexEquilibriumIn () (fun _ => 0)
        (Math.FinPMF.product Examples.fairBoolFin Examples.fairBoolFin) :=
  Examples.convexIso_not_left_seq_congruence

example {X S Y R : Type*} [Math.AvgAlgebra S]
    (g : ProbOpenGame.Saturated X S Y R) :
    ProbOpenGame.ConvexIso
      (ProbOpenGame.Saturated.seq (ProbOpenGame.Saturated.id X S) g).1
      g.1 :=
  ProbOpenGame.Saturated.seqIdLeft g

example {X S Y R : Type*} [Math.AvgAlgebra R]
    (g : ProbOpenGame.Saturated X S Y R) :
    ProbOpenGame.ConvexIso
      (ProbOpenGame.Saturated.seq g
        (ProbOpenGame.Saturated.id Y R)).1 g.1 :=
  ProbOpenGame.Saturated.seqIdRight g

end

end OpenGames.Tests
