import Math.Probability
import Math.PMFProduct
import Math.ProbabilityMassFunction
import GameTheory.Model.FiniteRecall

/-!
# GameTheory.Model.SemanticForm

Semantics-first model decomposition:
- `LSM`: labeled nondeterministic machine with joint actions
- `InfoModel`: information structure over an `LSM`
- `ControlModel`: common-knowledge controller specifications (separate layer)

`ObsRecall`, `ActionRecall`, `PerfectRecall`, and `FiniteHorizon` are predicates,
not built-in requirements.
-/

namespace GameTheory

open Math.Probability

/-- Labeled nondeterministic machine with joint (possibly inactive) actions. -/
structure LSM (ι : Type) where
  Label : Type
  State : Type
  Act : ι → Type
  init : State
  step : Label → (∀ i, Option (Act i)) → State → State → Prop

namespace LSM

variable {ι : Type}

/-- Action-erased one-step relation. -/
def stepExists (M : LSM ι) : M.Label → M.State → M.State → Prop :=
  fun ℓ s t => ∃ a, M.step ℓ a s t

/-- Bounded-horizon predicate (theorem-local assumption). -/
def FiniteHorizon (M : LSM ι) (k : Nat) : Prop :=
  ∀ (h : List M.Label) (s : M.State),
    Semantics.Transition.ReachBy M.stepExists h M.init s → h.length ≤ k

end LSM

/-- Information structure over a fixed machine. -/
structure InfoModel {ι : Type} (M : LSM ι) where
  Obs : ι → Type
  /-- Primitive observation map from states. -/
  observe : (i : ι) → M.State → Obs i
  /-- Information partition as a state equivalence relation per controller. -/
  infoSetoid : (i : ι) → Setoid M.State
  /-- Coherence: equal observations imply information equivalence. -/
  observe_eq_implies_obsEq :
    ∀ (i : ι) {s t : M.State},
      observe i s = observe i t → (infoSetoid i).r s t

namespace InfoModel

variable {ι : Type} {M : LSM ι}

/-- Derived observation-equivalence relation from the partition. -/
def obsEq (I : InfoModel M) (i : ι) : M.State → M.State → Prop :=
  (I.infoSetoid i).r

/-- Controller-local observation-trace type. -/
abbrev LocalTrace (I : InfoModel M) (i : ι) : Type :=
  List (I.Obs i)

/-- Derived global projected-trace outcome (no primitive `Outcome` type). -/
abbrev Outcome (I : InfoModel M) : Type := ∀ i, I.LocalTrace i

/-- Local projection by mapping primitive state observations over a state trace. -/
def projectStates (I : InfoModel M) (i : ι) (ss : List M.State) : I.LocalTrace i :=
  ss.map (I.observe i)

/-- Outcome induced by a machine state trace via local projections. -/
def outcomeOfStates (I : InfoModel M) (ss : List M.State) : I.Outcome :=
  fun i => I.projectStates i ss

/-- Reachability witness carrying both labels and visited states (states include init). -/
inductive ReachStateTrace (M : LSM ι) : List M.Label → List M.State → Prop
  | nil : ReachStateTrace M [] [M.init]
  | snoc {h : List M.Label} {ss : List M.State} {s t : M.State} {ℓ : M.Label} :
      ReachStateTrace M h ss →
      ss.getLast? = some s →
      M.stepExists ℓ s t →
      ReachStateTrace M (h ++ [ℓ]) (ss ++ [t])

/-- Reachability witness carrying labels, joint actions, and visited states. -/
inductive ReachActionTrace (M : LSM ι) :
    List (M.Label × (∀ i, Option (M.Act i))) → List M.State → Prop
  | nil : ReachActionTrace M [] [M.init]
  | snoc
      {ha : List (M.Label × (∀ i, Option (M.Act i)))}
      {ss : List M.State} {s t : M.State} {ℓ : M.Label} {a : ∀ i, Option (M.Act i)} :
      ReachActionTrace M ha ss →
      ss.getLast? = some s →
      M.step ℓ a s t →
      ReachActionTrace M (ha ++ [(ℓ, a)]) (ss ++ [t])

/-- Player-local projected own-action trace from an action-annotated history. -/
def projectActions (i : ι)
    (ha : List (M.Label × (∀ j, Option (M.Act j)))) : List (Option (M.Act i)) :=
  ha.map (fun e => e.2 i)

/-- Player-local history token:
prefix local observation trace paired with realized own action at that step. -/
abbrev LocalHistTok (I : InfoModel M) (i : ι) : Type :=
  I.LocalTrace i × Option (M.Act i)

/-- Build local-history tokens from action/state traces (auxiliary recursion). -/
private def localHistTokensAux
    (I : InfoModel M) (i : ι)
    (pref : List M.State)
    (ha : List (M.Label × (∀ j, Option (M.Act j))))
    (ssTail : List M.State) :
    List (I.LocalHistTok i) :=
  match ha, ssTail with
  | [], _ => []
  | (_, a) :: ha', s' :: ss' =>
      (I.projectStates i pref, a i) ::
        localHistTokensAux I i (pref ++ [s']) ha' ss'
  | _ :: _, [] => []

/-- First-class local-history projection from action/state traces. -/
def localHistTokens
    (I : InfoModel M) (i : ι)
    (ha : List (M.Label × (∀ j, Option (M.Act j))))
    (ss : List M.State) :
    List (I.LocalHistTok i) :=
  match ss with
  | [] => []
  | s0 :: ssTail => localHistTokensAux I i [s0] ha ssTail

/-- Local-history tokens generated by continuing after an already accumulated
global state prefix `pref`. Each token records the local trace visible just
before one further action together with the action taken at that point. -/
def localHistTokensFrom
    (I : InfoModel M) (i : ι)
    (pref : List M.State)
    (ha : List (M.Label × (∀ j, Option (M.Act j))))
    (ssTail : List M.State) :
    List (I.LocalHistTok i) :=
  localHistTokensAux I i pref ha ssTail

/-- With a nonempty starting prefix, `localHistTokens` agrees with
`localHistTokensFrom`. -/
theorem localHistTokens_cons_eq_localHistTokensFrom
    (I : InfoModel M) (i : ι)
    (s₀ : M.State)
    (ha : List (M.Label × (∀ j, Option (M.Act j))))
    (ssTail : List M.State) :
    localHistTokens I i ha (s₀ :: ssTail) =
      localHistTokensFrom I i [s₀] ha ssTail := rfl

private theorem localHistTokensAux_snoc
    (I : InfoModel M) (i : ι)
    (pref : List M.State)
    (ha : List (M.Label × (∀ j, Option (M.Act j))))
    (ssTail : List M.State)
    (hLen : ssTail.length = ha.length)
    (ℓ : M.Label) (a : ∀ j, Option (M.Act j)) (t : M.State) :
    localHistTokensAux I i pref (ha ++ [(ℓ, a)]) (ssTail ++ [t]) =
      localHistTokensAux I i pref ha ssTail ++ [(I.projectStates i (pref ++ ssTail), a i)] := by
  induction ha generalizing pref ssTail with
  | nil =>
      cases ssTail with
      | nil =>
          simp [localHistTokensAux]
      | cons s ss =>
          cases hLen
  | cons x ha ih =>
      cases ssTail with
      | nil =>
          cases hLen
      | cons s ss =>
          simp at hLen
          simp [localHistTokensAux, ih (pref := pref ++ [s]) (ssTail := ss) hLen,
            List.append_assoc]

/-- Appending one step to an action/state trace appends exactly one local
history token. -/
theorem localHistTokens_snoc
    (I : InfoModel M) (i : ι)
    (ha : List (M.Label × (∀ j, Option (M.Act j))))
    (ss : List M.State)
    (hLen : ss.length = ha.length + 1)
    (ℓ : M.Label) (a : ∀ j, Option (M.Act j)) (t : M.State) :
    localHistTokens I i (ha ++ [(ℓ, a)]) (ss ++ [t]) =
      localHistTokens I i ha ss ++ [(I.projectStates i ss, a i)] := by
  cases ss with
  | nil =>
      cases hLen
  | cons s0 ssTail =>
      have hLen' : ssTail.length = ha.length := by
        simpa using hLen
      simpa [localHistTokens, List.cons_append, List.append_assoc] using
        localHistTokensAux_snoc I i [s0] ha ssTail hLen' ℓ a t

/-- Appending one step to a continuation appends exactly one continuation local
history token. -/
theorem localHistTokensFrom_snoc
    (I : InfoModel M) (i : ι)
    (pref : List M.State)
    (ha : List (M.Label × (∀ j, Option (M.Act j))))
    (ssTail : List M.State)
    (hLen : ssTail.length = ha.length)
    (ℓ : M.Label) (a : ∀ j, Option (M.Act j)) (t : M.State) :
    localHistTokensFrom I i pref (ha ++ [(ℓ, a)]) (ssTail ++ [t]) =
      localHistTokensFrom I i pref ha ssTail ++ [(I.projectStates i (pref ++ ssTail), a i)] := by
  simpa [localHistTokensFrom] using localHistTokensAux_snoc I i pref ha ssTail hLen ℓ a t

/-- Length relation on action/state traces induced by `ReachActionTrace`. -/
theorem ReachActionTrace.length_states_eq_succ_actions
    {ha : List (M.Label × (∀ i, Option (M.Act i)))}
    {ss : List M.State}
    (h : ReachActionTrace M ha ss) :
    ss.length = ha.length + 1 := by
  induction h with
  | nil =>
      simp
  | snoc _ _ _ ih =>
      simp [List.length_append, ih, Nat.add_comm]

/-- Project an action trace to a state trace by forgetting joint actions. -/
theorem ReachActionTrace.toReachStateTrace {ha : List (M.Label × (∀ i, Option (M.Act i)))}
    {ss : List M.State} (h : ReachActionTrace M ha ss) :
    ReachStateTrace M (ha.map Prod.fst) ss := by
  induction h with
  | nil => exact .nil
  | snoc _ hlast hstep ih =>
    simp only [List.map_append, List.map_cons, List.map_nil]
    exact .snoc ih hlast ⟨_, hstep⟩

/-- Observation recall: indistinguishable terminal states imply identical
player-local projected observation traces on the corresponding reaches. -/
def ObsRecall (I : InfoModel M) : Prop :=
  ∀ (i : ι) (h₁ h₂ : List M.Label) (ss₁ ss₂ : List M.State) (s₁ s₂ : M.State),
    ReachStateTrace M h₁ ss₁ →
    ReachStateTrace M h₂ ss₂ →
    ss₁.getLast? = some s₁ →
    ss₂.getLast? = some s₂ →
    I.obsEq i s₁ s₂ →
    I.projectStates i ss₁ = I.projectStates i ss₂

/-- Action recall: indistinguishable terminal states imply identical
player-local own-action traces on the corresponding action-annotated reaches. -/
def ActionRecall (I : InfoModel M) : Prop :=
  ∀ (i : ι)
    (ha₁ ha₂ : List (M.Label × (∀ j, Option (M.Act j))))
    (ss₁ ss₂ : List M.State) (s₁ s₂ : M.State),
    ReachActionTrace M ha₁ ss₁ →
    ReachActionTrace M ha₂ ss₂ →
    ss₁.getLast? = some s₁ →
    ss₂.getLast? = some s₂ →
    I.obsEq i s₁ s₂ →
    projectActions i ha₁ = projectActions i ha₂

/-- Perfect recall is the conjunction of observation recall and action recall. -/
def PerfectRecall (I : InfoModel M) : Prop :=
  I.ObsRecall ∧ I.ActionRecall

theorem perfectRecall_obs {I : InfoModel M} (hPR : I.PerfectRecall) : I.ObsRecall :=
  hPR.1

theorem perfectRecall_action {I : InfoModel M} (hPR : I.PerfectRecall) : I.ActionRecall :=
  hPR.2

end InfoModel

/-- Common-knowledge controller specification over local traces/observations. -/
inductive ControlSpec (Obs Act : Type) where
  | utility  : (List Obs → ℝ) → ControlSpec Obs Act
  | behavior : (List Obs → PMF (Option Act)) → ControlSpec Obs Act

/-- Public control layer, separated from machine and information layers. -/
structure ControlModel {ι : Type} (M : LSM ι) (I : InfoModel M) where
  control : ∀ i, ControlSpec (I.Obs i) (M.Act i)

namespace Execution

variable {ι : Type} {M : LSM ι}

/-- Joint (possibly inactive) action profile. -/
abbrev JointAction (M : LSM ι) : Type := ∀ i, Option (M.Act i)

/-- Deterministic profile over label and local trace view. -/
abbrev PureProfile (I : InfoModel M) : Type :=
  ∀ i, I.LocalTrace i → Option (M.Act i)

/-- Behavioral profile over label and local trace view. -/
abbrev BehavioralProfile (I : InfoModel M) : Type :=
  ∀ i, I.LocalTrace i → PMF (Option (M.Act i))

/-- Correlated behavioral profile over local trace context.
This is defined for future correlated-realizability developments.
Current execution semantics continues to use `BehavioralProfile` (independent). -/
abbrev BehavioralProfileCorr (I : InfoModel M) : Type :=
  (∀ i, I.LocalTrace i) → PMF (JointAction M)

/-- Embed an independent behavioral profile as a correlated one by product sampling. -/
noncomputable def behavioralToCorr
    [Fintype ι] [∀ i, Fintype (Option (M.Act i))]
    (I : InfoModel M) (σ : BehavioralProfile I) : BehavioralProfileCorr I := by
  classical
  intro v
  exact Math.PMFProduct.pmfPi (fun i => σ i (v i))

/-- Lift a deterministic profile to a behavioral one. -/
noncomputable def pureToBehavioral (I : InfoModel M) (π : PureProfile I) : BehavioralProfile I :=
  fun i v => PMF.pure (π i v)

/-- Stochastic execution choices on top of nondeterministic machine rules. -/
structure Dynamics (I : InfoModel M) where
  /-- Label sampling policy from current state. -/
  labelKernel : M.State → PMF M.Label
  /-- Next-state kernel, conditioned on label/joint-action/current-state. -/
  nextState : M.Label → JointAction M → M.State → PMF M.State
  /-- Soundness: sampled next states respect machine step relation. -/
  nextState_sound :
    ∀ (ℓ : M.Label) (a : JointAction M) (s t : M.State),
      (nextState ℓ a s) t ≠ 0 → M.step ℓ a s t

namespace Dynamics

variable {I : InfoModel M}

open Classical in
/-- Independent joint-action distribution induced by a behavioral profile. -/
noncomputable def jointActionDist
    [Fintype ι] [∀ i, Fintype (Option (M.Act i))]
    (σ : BehavioralProfile I) (ss : List M.State) : PMF (JointAction M) :=
  Math.PMFProduct.pmfPi (fun i => σ i (I.projectStates i ss))

/-- One stochastic step from a current state under behavioral profile `σ`. -/
noncomputable def stepDist (D : Dynamics I)
    [Fintype ι] [∀ i, Fintype (Option (M.Act i))]
    (σ : BehavioralProfile I) (ss : List M.State) : PMF (M.Label × M.State) :=
  let s := (ss.getLast?).getD M.init
  (D.labelKernel s).bind fun ℓ =>
    (jointActionDist (I := I) σ ss).bind fun a =>
      Math.ProbabilityMassFunction.pushforward (D.nextState ℓ a s) (fun t => (ℓ, t))

/-- One stochastic step from a current state under a correlated behavioral profile. -/
noncomputable def stepDistCorr (D : Dynamics I)
    [Fintype ι] [∀ i, Fintype (Option (M.Act i))]
    (σ : BehavioralProfileCorr I) (ss : List M.State) : PMF (M.Label × M.State) :=
  let s := (ss.getLast?).getD M.init
  let v : ∀ i, I.LocalTrace i := fun i => I.projectStates i ss
  (D.labelKernel s).bind fun ℓ =>
    (σ v).bind fun a =>
      Math.ProbabilityMassFunction.pushforward (D.nextState ℓ a s) (fun t => (ℓ, t))

/-- Bounded run distribution of length exactly `k`:
stores (label-trace, state-trace). -/
noncomputable def runDist (D : Dynamics I)
    [Fintype ι] [∀ i, Fintype (Option (M.Act i))]
    (k : Nat) (σ : BehavioralProfile I) : PMF (List M.Label × List M.State) :=
  Nat.rec (PMF.pure ([], [M.init]))
    (fun _ rec =>
      rec.bind (fun hs =>
        Math.ProbabilityMassFunction.pushforward (D.stepDist σ hs.2)
          (fun ls => (hs.1 ++ [ls.1], hs.2 ++ [ls.2]))))
    k

/-- Pure-profile run distribution via `pureToBehavioral`. -/
noncomputable def runDistPure (D : Dynamics I)
    [Fintype ι] [∀ i, Fintype (Option (M.Act i))]
    (k : Nat) (π : PureProfile I) : PMF (List M.Label × List M.State) :=
  D.runDist k (pureToBehavioral I π)

/-- Outcome distribution (projected-trace outcome) from bounded behavioral runs. -/
noncomputable def evalBehavioral (D : Dynamics I)
    [Fintype ι] [∀ i, Fintype (Option (M.Act i))]
    (k : Nat) (σ : BehavioralProfile I) : PMF I.Outcome :=
  Math.ProbabilityMassFunction.pushforward (D.runDist k σ) (fun hs => I.outcomeOfStates hs.2)

/-- Outcome distribution from bounded pure runs. -/
noncomputable def evalPure (D : Dynamics I)
    [Fintype ι] [∀ i, Fintype (Option (M.Act i))]
    (k : Nat) (π : PureProfile I) : PMF I.Outcome :=
  Math.ProbabilityMassFunction.pushforward (D.runDistPure k π) (fun hs => I.outcomeOfStates hs.2)

/-- Independent one-step realizability:
there exists an independent behavioral profile matching the mixed/pure one-step law. -/
def OneStepIndependentRealizable (D : Dynamics I)
    [Fintype ι] [∀ i, Fintype (Option (M.Act i))]
    (ν : PMF (PureProfile I)) (n : Nat) : Prop :=
  ∃ σ : BehavioralProfile I,
    (ν.bind (fun π =>
      (D.runDistPure n π).bind (fun hs =>
        Math.ProbabilityMassFunction.pushforward
          (D.stepDist σ hs.2)
          (fun ls => (hs.1 ++ [ls.1], hs.2 ++ [ls.2]))))) =
    (ν.bind (fun π =>
      (D.runDistPure n π).bind (fun hs =>
        Math.ProbabilityMassFunction.pushforward
          (D.stepDist (pureToBehavioral I π) hs.2)
          (fun ls => (hs.1 ++ [ls.1], hs.2 ++ [ls.2])))))

/-- Correlated one-step realizability:
there exists a correlated behavioral profile matching the mixed/pure one-step law. -/
def OneStepCorrelatedRealizable (D : Dynamics I)
    [Fintype ι] [∀ i, Fintype (Option (M.Act i))]
    (ν : PMF (PureProfile I)) (n : Nat) : Prop :=
  ∃ σ : BehavioralProfileCorr I,
    (ν.bind (fun π =>
      (D.runDistPure n π).bind (fun hs =>
        Math.ProbabilityMassFunction.pushforward
          (D.stepDistCorr σ hs.2)
          (fun ls => (hs.1 ++ [ls.1], hs.2 ++ [ls.2]))))) =
    (ν.bind (fun π =>
      (D.runDistPure n π).bind (fun hs =>
        Math.ProbabilityMassFunction.pushforward
          (D.stepDist (pureToBehavioral I π) hs.2)
          (fun ls => (hs.1 ++ [ls.1], hs.2 ++ [ls.2])))))

end Dynamics
end Execution

end GameTheory
