import GameTheory.Theorems.KuhnCore
import GameTheory.Model.Lemmas.PerfectRecall
import GameTheory.Model.Lemmas.LocalHistories
import GameTheory.Model.Lemmas.LocalConditioning
import GameTheory.Model.Lemmas.ReachFactorization

namespace GameTheory
namespace Theorems

open Math
open Math.PMFProduct

section InfoModel

open Execution
open InfoModel

variable {ι : Type} [Fintype ι] [DecidableEq ι]
variable {M : LSM ι} (I : InfoModel M)
variable (D : Execution.Dynamics I)
variable (k : Nat)

/-- Player-local history token used for iterated conditioning:
past local observation trace paired with the realized own action. -/
abbrev LocalHistTok (i : ι) : Type :=
  InfoModel.LocalHistTok (I := I) i


/-- Canonical conditional behavioral realization from a mixed profile,
defined by conditioning on one chosen reachable local history witness. -/
noncomputable def mixedToBehavioral
    [∀ i, Fintype (I.LocalTrace i)]
    [∀ i, Fintype (InfoModel.LocalPure (I := I) i)]
    [∀ i, Fintype (Option (M.Act i))]
    (μ : InfoModel.MixedProfile (I := I)) :
    BehavioralProfile I := by
  classical
  refine fun i v =>
    if h :
      ∃ ha : List (JointAction M),
      ∃ ss : List M.State,
        InfoModel.ReachActionTrace M ha ss ∧
        I.projectStates i ss = v
    then ?_ else PMF.pure none
  let ha : List (JointAction M) := Classical.choose h
  let ss : List M.State := Classical.choose (Classical.choose_spec h)
  have hv : I.projectStates i ss = v := (Classical.choose_spec (Classical.choose_spec h)).2
  let hist := InfoModel.localHistTokens (I := I) i ha ss
  exact Math.ProbabilityMassFunction.pushforward
    (iterCondMixedLocal (I := I) i (μ i) hist) (fun f => f v)

omit [Fintype ι] [DecidableEq ι] in
theorem mixedToBehavioral_eq_iterCond_pushforward
    [∀ i, Fintype (I.LocalTrace i)]
    [∀ i, Fintype (InfoModel.LocalPure (I := I) i)]
    [∀ i, Fintype (Option (M.Act i))]
    (hPR : I.PerfectRecall)
    (μ : InfoModel.MixedProfile (I := I))
    (i : ι)
    {ha : List (JointAction M)}
    {ss : List M.State}
    (hr : InfoModel.ReachActionTrace M ha ss) :
    mixedToBehavioral (I := I) μ i (I.projectStates i ss) =
      Math.ProbabilityMassFunction.pushforward
        (iterCondMixedLocal (I := I) i (μ i)
          (InfoModel.localHistTokens (I := I) i ha ss))
        (fun f => f (I.projectStates i ss)) := by
  classical
  unfold mixedToBehavioral
  let v : I.LocalTrace i := I.projectStates i ss
  have hreach :
      ∃ ha' : List (JointAction M),
      ∃ ss' : List M.State,
        InfoModel.ReachActionTrace M ha' ss' ∧
          I.projectStates i ss' = v := by
    exact ⟨ha, ss, hr, rfl⟩
  rw [dif_pos hreach]
  dsimp [v]
  let ha' : List (JointAction M) := Classical.choose hreach
  let ss' : List M.State := Classical.choose (Classical.choose_spec hreach)
  have hr' : InfoModel.ReachActionTrace M ha' ss' :=
    (Classical.choose_spec (Classical.choose_spec hreach)).1
  have hproj :
      I.projectStates i ss' = I.projectStates i ss :=
    (Classical.choose_spec (Classical.choose_spec hreach)).2
  have hacts :
      InfoModel.projectActions i ha' = InfoModel.projectActions i ha :=
    actionRecall_of_projectStates_eq (I := I) hPR i hr' hr hproj
  have hLen' :
      ss'.length = ha'.length + 1 :=
    InfoModel.ReachActionTrace.length_states_eq_succ_actions hr'
  have hLen :
      ss.length = ha.length + 1 :=
    InfoModel.ReachActionTrace.length_states_eq_succ_actions hr
  have hhist :
      InfoModel.localHistTokens (I := I) i ha' ss' =
        InfoModel.localHistTokens (I := I) i ha ss :=
    localHistTokens_eq_of_projectStates_actions_eq
      (I := I) i hLen' hLen hproj hacts
  simp [ha', ss', hhist]

/-- Behavioral realization relative to a fixed reachable prefix. The mixed
profile supplied to this constructor is already understood to encode any
conditioning performed along the prefix; the definition only conditions on the
additional local-history tokens generated by a continuation of that prefix. -/
noncomputable def mixedToBehavioralAfter
    [∀ i, Fintype (I.LocalTrace i)]
    [∀ i, Fintype (InfoModel.LocalPure (I := I) i)]
    [∀ i, Fintype (Option (M.Act i))]
    (μ : InfoModel.MixedProfile (I := I))
    (ha0 : List (JointAction M))
    (ss0 : List M.State) :
    BehavioralProfile I := by
  classical
  refine fun i v =>
    if h :
      ∃ haTail : List (JointAction M),
      ∃ ssTail : List M.State,
        InfoModel.ReachActionTrace M (ha0 ++ haTail) (ss0 ++ ssTail) ∧
        I.projectStates i (ss0 ++ ssTail) = v
    then ?_ else PMF.pure none
  let haTail : List (JointAction M) := Classical.choose h
  let ssTail : List M.State := Classical.choose (Classical.choose_spec h)
  let histTail := InfoModel.localHistTokensFrom (I := I) i ss0 haTail ssTail
  exact Math.ProbabilityMassFunction.pushforward
    (iterCondMixedLocal (I := I) i (μ i) histTail) (fun f => f v)

/-- Mixed profile obtained by conditioning each player's local pure-plan law on
the local history realized along a reachable prefix. -/
noncomputable def conditionedMixedProfile
    [∀ i, Fintype (InfoModel.LocalPure (I := I) i)]
    [∀ i, Fintype (Option (M.Act i))]
    (μ : InfoModel.MixedProfile (I := I))
    (ha : List (JointAction M))
    (ss : List M.State) :
    InfoModel.MixedProfile (I := I) :=
  fun i => iterCondMixedLocal (I := I) i (μ i)
    (InfoModel.localHistTokens (I := I) i ha ss)

omit [Fintype ι] [DecidableEq ι] in
private theorem conditionedMixedProfile_append
    [∀ i, Fintype (InfoModel.LocalPure (I := I) i)]
    [∀ i, Fintype (Option (M.Act i))]
    (μ : InfoModel.MixedProfile (I := I))
    (ha0 haTail : List (JointAction M))
    (ss0 ssTail : List M.State)
    (hLen0 : ss0.length = ha0.length + 1) :
    conditionedMixedProfile (I := I) μ (ha0 ++ haTail) (ss0 ++ ssTail) =
      fun i =>
        iterCondMixedLocal (I := I) i
          (conditionedMixedProfile (I := I) μ ha0 ss0 i)
          (InfoModel.localHistTokensFrom (I := I) i ss0 haTail ssTail) := by
  funext i
  dsimp [conditionedMixedProfile]
  rw [InfoModel.localHistTokens_append (I := I) i ha0 haTail ss0 ssTail hLen0]
  rw [iterCondMixedLocal_append]

omit [Fintype ι] [DecidableEq ι] in
theorem mixedToBehavioralAfter_eq_iterCond_pushforward
    [∀ i, Fintype (I.LocalTrace i)]
    [∀ i, Fintype (InfoModel.LocalPure (I := I) i)]
    [∀ i, Fintype (Option (M.Act i))]
    (hPR : I.PerfectRecall)
    (μ : InfoModel.MixedProfile (I := I))
    {ha0 : List (JointAction M)}
    {ss0 : List M.State}
    (hr0 : InfoModel.ReachActionTrace M ha0 ss0)
    (i : ι)
    {haTail : List (JointAction M)}
    {ssTail : List M.State}
    (hr : InfoModel.ReachActionTrace M (ha0 ++ haTail) (ss0 ++ ssTail)) :
    mixedToBehavioralAfter (I := I) μ ha0 ss0 i (I.projectStates i (ss0 ++ ssTail)) =
      Math.ProbabilityMassFunction.pushforward
        (iterCondMixedLocal (I := I) i (μ i)
          (InfoModel.localHistTokensFrom (I := I) i ss0 haTail ssTail))
        (fun f => f (I.projectStates i (ss0 ++ ssTail))) := by
  classical
  unfold mixedToBehavioralAfter
  let v : I.LocalTrace i := I.projectStates i (ss0 ++ ssTail)
  have hreach :
      ∃ haTail' : List (JointAction M),
      ∃ ssTail' : List M.State,
        InfoModel.ReachActionTrace M (ha0 ++ haTail') (ss0 ++ ssTail') ∧
          I.projectStates i (ss0 ++ ssTail') = v := by
    exact ⟨haTail, ssTail, hr, rfl⟩
  rw [dif_pos hreach]
  dsimp [v]
  let haTail' : List (JointAction M) := Classical.choose hreach
  let ssTail' : List M.State := Classical.choose (Classical.choose_spec hreach)
  have hr' : InfoModel.ReachActionTrace M (ha0 ++ haTail') (ss0 ++ ssTail') :=
    (Classical.choose_spec (Classical.choose_spec hreach)).1
  have hproj :
      I.projectStates i (ss0 ++ ssTail') = I.projectStates i (ss0 ++ ssTail) :=
    (Classical.choose_spec (Classical.choose_spec hreach)).2
  have hactsFull :
      InfoModel.projectActions i (ha0 ++ haTail') =
        InfoModel.projectActions i (ha0 ++ haTail) :=
    actionRecall_of_projectStates_eq (I := I) hPR i hr' hr hproj
  have hactsTail :
      InfoModel.projectActions i haTail' =
        InfoModel.projectActions i haTail := by
    have hactsFull' :
        InfoModel.projectActions i ha0 ++ InfoModel.projectActions i haTail' =
          InfoModel.projectActions i ha0 ++ InfoModel.projectActions i haTail := by
      simpa [InfoModel.projectActions, List.map_append] using hactsFull
    exact (List.append_right_injective (InfoModel.projectActions i ha0)) hactsFull'
  have hLen0 :
      ss0.length = ha0.length + 1 :=
    InfoModel.ReachActionTrace.length_states_eq_succ_actions hr0
  have hLen' :
      (ss0 ++ ssTail').length = (ha0 ++ haTail').length + 1 :=
    InfoModel.ReachActionTrace.length_states_eq_succ_actions hr'
  have hLen :
      (ss0 ++ ssTail).length = (ha0 ++ haTail).length + 1 :=
    InfoModel.ReachActionTrace.length_states_eq_succ_actions hr
  have hhistFull :
      InfoModel.localHistTokens (I := I) i (ha0 ++ haTail') (ss0 ++ ssTail') =
        InfoModel.localHistTokens (I := I) i (ha0 ++ haTail) (ss0 ++ ssTail) :=
    localHistTokens_eq_of_projectStates_actions_eq
      (I := I) i hLen' hLen hproj hactsFull
  have hhistTail :
      InfoModel.localHistTokensFrom (I := I) i ss0 haTail' ssTail' =
        InfoModel.localHistTokensFrom (I := I) i ss0 haTail ssTail := by
    have hsplit' :
        InfoModel.localHistTokens (I := I) i (ha0 ++ haTail') (ss0 ++ ssTail') =
          InfoModel.localHistTokens (I := I) i ha0 ss0 ++
            InfoModel.localHistTokensFrom (I := I) i ss0 haTail' ssTail' := by
      exact InfoModel.localHistTokens_append
        (I := I) i ha0 haTail' ss0 ssTail' hLen0
    have hsplit :
        InfoModel.localHistTokens (I := I) i (ha0 ++ haTail) (ss0 ++ ssTail) =
          InfoModel.localHistTokens (I := I) i ha0 ss0 ++
            InfoModel.localHistTokensFrom (I := I) i ss0 haTail ssTail := by
      exact InfoModel.localHistTokens_append
        (I := I) i ha0 haTail ss0 ssTail hLen0
    have happend :
        InfoModel.localHistTokens (I := I) i ha0 ss0 ++
          InfoModel.localHistTokensFrom (I := I) i ss0 haTail' ssTail' =
        InfoModel.localHistTokens (I := I) i ha0 ss0 ++
          InfoModel.localHistTokensFrom (I := I) i ss0 haTail ssTail := by
      calc
        InfoModel.localHistTokens (I := I) i ha0 ss0 ++
            InfoModel.localHistTokensFrom (I := I) i ss0 haTail' ssTail'
            =
          InfoModel.localHistTokens (I := I) i (ha0 ++ haTail') (ss0 ++ ssTail') := by
              exact hsplit'.symm
        _ =
          InfoModel.localHistTokens (I := I) i (ha0 ++ haTail) (ss0 ++ ssTail) := hhistFull
        _ =
          InfoModel.localHistTokens (I := I) i ha0 ss0 ++
            InfoModel.localHistTokensFrom (I := I) i ss0 haTail ssTail := hsplit
    exact (List.append_right_injective (InfoModel.localHistTokens (I := I) i ha0 ss0)) happend
  simp [haTail', ssTail', hhistTail]

omit [Fintype ι] [DecidableEq ι] in
theorem mixedToBehavioral_tail_agree
    [∀ i, Fintype (I.LocalTrace i)]
    [∀ i, Fintype (InfoModel.LocalPure (I := I) i)]
    [∀ i, Fintype (Option (M.Act i))]
    (hPR : I.PerfectRecall)
    (μ : InfoModel.MixedProfile (I := I))
    {ha0 : List (JointAction M)}
    {ss0 : List M.State}
    (hr0 : InfoModel.ReachActionTrace M ha0 ss0)
    (μ0 : InfoModel.MixedProfile (I := I))
    (hμ0 :
      μ0 =
        fun i => iterCondMixedLocal (I := I) i (μ i)
          (InfoModel.localHistTokens (I := I) i ha0 ss0))
    (i : ι)
    {haTail : List (JointAction M)}
    {ssTail : List M.State}
    (hr : InfoModel.ReachActionTrace M (ha0 ++ haTail) (ss0 ++ ssTail)) :
    mixedToBehavioral (I := I) μ i (I.projectStates i (ss0 ++ ssTail)) =
      mixedToBehavioralAfter (I := I) μ0 ha0 ss0 i (I.projectStates i (ss0 ++ ssTail)) := by
  have hglobal :=
    mixedToBehavioral_eq_iterCond_pushforward
      (I := I) (hPR := hPR) (μ := μ) i hr
  have hlocal :=
    mixedToBehavioralAfter_eq_iterCond_pushforward
      (I := I) (hPR := hPR) (μ := μ0) hr0 i hr
  have hLen0 :
      ss0.length = ha0.length + 1 :=
    InfoModel.ReachActionTrace.length_states_eq_succ_actions hr0
  have hhistSplit :
      InfoModel.localHistTokens (I := I) i (ha0 ++ haTail) (ss0 ++ ssTail) =
        InfoModel.localHistTokens (I := I) i ha0 ss0 ++
          InfoModel.localHistTokensFrom (I := I) i ss0 haTail ssTail := by
    exact InfoModel.localHistTokens_append
      (I := I) i ha0 haTail ss0 ssTail hLen0
  calc
    mixedToBehavioral (I := I) μ i (I.projectStates i (ss0 ++ ssTail))
        =
      Math.ProbabilityMassFunction.pushforward
        (iterCondMixedLocal (I := I) i (μ i)
          (InfoModel.localHistTokens (I := I) i (ha0 ++ haTail) (ss0 ++ ssTail)))
        (fun f => f (I.projectStates i (ss0 ++ ssTail))) := hglobal
    _ =
      Math.ProbabilityMassFunction.pushforward
        (iterCondMixedLocal (I := I) i (μ i)
          (InfoModel.localHistTokens (I := I) i ha0 ss0 ++
            InfoModel.localHistTokensFrom (I := I) i ss0 haTail ssTail))
        (fun f => f (I.projectStates i (ss0 ++ ssTail))) := by
          simp [hhistSplit]
    _ =
      Math.ProbabilityMassFunction.pushforward
        (iterCondMixedLocal (I := I) i
          (iterCondMixedLocal (I := I) i (μ i)
            (InfoModel.localHistTokens (I := I) i ha0 ss0))
          (InfoModel.localHistTokensFrom (I := I) i ss0 haTail ssTail))
        (fun f => f (I.projectStates i (ss0 ++ ssTail))) := by
          rw [iterCondMixedLocal_append]
    _ =
      Math.ProbabilityMassFunction.pushforward
        (iterCondMixedLocal (I := I) i (μ0 i)
          (InfoModel.localHistTokensFrom (I := I) i ss0 haTail ssTail))
        (fun f => f (I.projectStates i (ss0 ++ ssTail))) := by
          simp [hμ0]
    _ =
      mixedToBehavioralAfter (I := I) μ0 ha0 ss0 i
        (I.projectStates i (ss0 ++ ssTail)) := hlocal.symm

private theorem stepDist_mixedToBehavioral_tail_agree
    [∀ i, Fintype (I.LocalTrace i)]
    [∀ i, Fintype (InfoModel.LocalPure (I := I) i)]
    [∀ i, Fintype (Option (M.Act i))]
    (hPR : I.PerfectRecall)
    (μ : InfoModel.MixedProfile (I := I))
    {ha0 : List (JointAction M)}
    {ss0 : List M.State}
    (hr0 : InfoModel.ReachActionTrace M ha0 ss0)
    {haTail : List (JointAction M)}
    {ssTail : List M.State}
    (hr : InfoModel.ReachActionTrace M (ha0 ++ haTail) (ss0 ++ ssTail)) :
    D.stepDist (mixedToBehavioral (I := I) μ) (ss0 ++ ssTail) =
      D.stepDist
        (mixedToBehavioralAfter (I := I)
          (conditionedMixedProfile (I := I) μ ha0 ss0) ha0 ss0)
        (ss0 ++ ssTail) := by
  apply stepDist_behavioral_depends_on_current_context (I := I) (D := D)
  intro i
  exact mixedToBehavioral_tail_agree
    (I := I) (hPR := hPR) (μ := μ) hr0
    (μ0 := conditionedMixedProfile (I := I) μ ha0 ss0)
    (hμ0 := rfl) i hr

private theorem mixedToBehavioralAfter_stepPoint_eq_conditioned
    [∀ i, Fintype (I.LocalTrace i)]
    [∀ i, Fintype (InfoModel.LocalPure (I := I) i)]
    [∀ i, Fintype (Option (M.Act i))]
    (hPR : I.PerfectRecall)
    (μ : InfoModel.MixedProfile (I := I))
    {ha0 : List (JointAction M)}
    {ss0 : List M.State}
    (hr0 : InfoModel.ReachActionTrace M ha0 ss0)
    (y : List M.State) :
    let μ0 := conditionedMixedProfile (I := I) μ ha0 ss0
    (Math.ProbabilityMassFunction.pushforward
      (D.stepDist (mixedToBehavioralAfter (I := I) μ0 ha0 ss0) ss0)
      (fun t => ss0 ++ [t])) y
      =
    ∑' π, (InfoModel.mixedJoint (I := I) μ0) π *
      ((Math.ProbabilityMassFunction.pushforward
        (D.stepDist (pureToBehavioral I π) ss0)
        (fun t => ss0 ++ [t])) y) := by
  classical
  let μ0 : InfoModel.MixedProfile (I := I) := conditionedMixedProfile (I := I) μ ha0 ss0
  have hr0' : InfoModel.ReachActionTrace M (ha0 ++ []) (ss0 ++ []) := by
    simpa using hr0
  have htail :
      D.stepDist (mixedToBehavioral (I := I) μ) ss0 =
        D.stepDist (mixedToBehavioralAfter (I := I) μ0 ha0 ss0) ss0 := by
    simpa [μ0] using
      (stepDist_mixedToBehavioral_tail_agree
        (I := I) (D := D) (hPR := hPR) (μ := μ) hr0 hr0')
  have hbeh_now :
      ∀ i,
        mixedToBehavioral (I := I) μ i (I.projectStates i ss0) =
          InfoModel.realizeBehavioralCanonical (I := I) μ0 i
            (I.projectStates i ss0) := by
    intro i
    simpa [μ0, conditionedMixedProfile, InfoModel.realizeBehavioralCanonical] using
      mixedToBehavioral_eq_iterCond_pushforward
        (I := I) (hPR := hPR) (μ := μ) i hr0
  have hstep_realize :
      D.stepDist (mixedToBehavioral (I := I) μ) ss0 =
        D.stepDist (InfoModel.realizeBehavioralCanonical (I := I) μ0) ss0 := by
    apply stepDist_behavioral_depends_on_current_context (I := I) (D := D)
    intro i
    exact hbeh_now i
  calc
    (Math.ProbabilityMassFunction.pushforward
      (D.stepDist (mixedToBehavioralAfter (I := I) μ0 ha0 ss0) ss0)
      (fun t => ss0 ++ [t])) y
        =
      (Math.ProbabilityMassFunction.pushforward
        (D.stepDist (mixedToBehavioral (I := I) μ) ss0)
        (fun t => ss0 ++ [t])) y := by
          simpa using congrArg
            (fun ν =>
              (Math.ProbabilityMassFunction.pushforward ν
                (fun t => ss0 ++ [t])) y)
            htail.symm
    _ =
      (Math.ProbabilityMassFunction.pushforward
        (D.stepDist (InfoModel.realizeBehavioralCanonical (I := I) μ0) ss0)
        (fun t => ss0 ++ [t])) y := by
          simpa using congrArg
            (fun ν =>
              (Math.ProbabilityMassFunction.pushforward ν
                (fun t => ss0 ++ [t])) y)
            hstep_realize
    _ =
      ∑' π, (InfoModel.mixedJoint (I := I) μ0) π *
        ((Math.ProbabilityMassFunction.pushforward
          (D.stepDist (pureToBehavioral I π) ss0)
          (fun t => ss0 ++ [t])) y) := by
            simpa using
              (mixedJoint_stepPoint_eq_realizeBehavioralCanonical
                (I := I) (D := D) μ0 ss0 y).symm

omit [Fintype ι] [DecidableEq ι] in
theorem mixedToBehavioralAfter_eq_realizeBehavioralCanonical_reachable
    [∀ i, Fintype (I.LocalTrace i)]
    [∀ i, Fintype (InfoModel.LocalPure (I := I) i)]
    [∀ i, Fintype (Option (M.Act i))]
    (hPR : I.PerfectRecall)
    (μ : InfoModel.MixedProfile (I := I))
    {ha0 : List (JointAction M)}
    {ss0 : List M.State}
    (hr0 : InfoModel.ReachActionTrace M ha0 ss0)
    (i : ι)
    {haTail : List (JointAction M)}
    {ssTail : List M.State}
    (hr : InfoModel.ReachActionTrace M (ha0 ++ haTail) (ss0 ++ ssTail)) :
    mixedToBehavioralAfter (I := I)
      (conditionedMixedProfile (I := I) μ ha0 ss0) ha0 ss0 i
      (I.projectStates i (ss0 ++ ssTail))
      =
    InfoModel.realizeBehavioralCanonical (I := I)
      (conditionedMixedProfile (I := I) μ (ha0 ++ haTail) (ss0 ++ ssTail)) i
      (I.projectStates i (ss0 ++ ssTail)) := by
  classical
  let μ0 : InfoModel.MixedProfile (I := I) := conditionedMixedProfile (I := I) μ ha0 ss0
  have hlocal :=
    mixedToBehavioralAfter_eq_iterCond_pushforward
      (I := I) (hPR := hPR) (μ := μ0) hr0 i hr
  have hLen0 :
      ss0.length = ha0.length + 1 :=
    InfoModel.ReachActionTrace.length_states_eq_succ_actions hr0
  have hcond :
      conditionedMixedProfile (I := I) μ (ha0 ++ haTail) (ss0 ++ ssTail)
        =
      fun i =>
        iterCondMixedLocal (I := I) i (μ0 i)
          (InfoModel.localHistTokensFrom (I := I) i ss0 haTail ssTail) := by
    simpa [μ0] using
      conditionedMixedProfile_append
        (I := I) (μ := μ) ha0 haTail ss0 ssTail hLen0
  calc
    mixedToBehavioralAfter (I := I) μ0 ha0 ss0 i
        (I.projectStates i (ss0 ++ ssTail))
        =
      Math.ProbabilityMassFunction.pushforward
        (iterCondMixedLocal (I := I) i (μ0 i)
          (InfoModel.localHistTokensFrom (I := I) i ss0 haTail ssTail))
        (fun f => f (I.projectStates i (ss0 ++ ssTail))) := hlocal
    _ =
      InfoModel.realizeBehavioralCanonical (I := I)
        (fun i =>
          iterCondMixedLocal (I := I) i (μ0 i)
            (InfoModel.localHistTokensFrom (I := I) i ss0 haTail ssTail)) i
        (I.projectStates i (ss0 ++ ssTail)) := by
          rfl
    _ =
      InfoModel.realizeBehavioralCanonical (I := I)
        (conditionedMixedProfile (I := I) μ (ha0 ++ haTail) (ss0 ++ ssTail)) i
        (I.projectStates i (ss0 ++ ssTail)) := by
          simp [hcond]

theorem mixedToBehavioralAfter_stepPoint_eq_conditioned_reachable
    [∀ i, Fintype (I.LocalTrace i)]
    [∀ i, Fintype (InfoModel.LocalPure (I := I) i)]
    [∀ i, Fintype (Option (M.Act i))]
    (hPR : I.PerfectRecall)
    (μ : InfoModel.MixedProfile (I := I))
    {ha0 : List (JointAction M)}
    {ss0 : List M.State}
    (hr0 : InfoModel.ReachActionTrace M ha0 ss0)
    {haTail : List (JointAction M)}
    {ssTail : List M.State}
    (hr : InfoModel.ReachActionTrace M (ha0 ++ haTail) (ss0 ++ ssTail))
    (y : List M.State) :
    let μFull := conditionedMixedProfile (I := I) μ (ha0 ++ haTail) (ss0 ++ ssTail)
    (Math.ProbabilityMassFunction.pushforward
      (D.stepDist
        (mixedToBehavioralAfter (I := I)
          (conditionedMixedProfile (I := I) μ ha0 ss0) ha0 ss0)
        (ss0 ++ ssTail))
      (fun t => (ss0 ++ ssTail) ++ [t])) y
      =
    ∑' π, (InfoModel.mixedJoint (I := I) μFull) π *
      ((Math.ProbabilityMassFunction.pushforward
        (D.stepDist (pureToBehavioral I π) (ss0 ++ ssTail))
        (fun t => (ss0 ++ ssTail) ++ [t])) y) := by
  classical
  let μFull : InfoModel.MixedProfile (I := I) :=
    conditionedMixedProfile (I := I) μ (ha0 ++ haTail) (ss0 ++ ssTail)
  have hstep :
      D.stepDist
        (mixedToBehavioralAfter (I := I)
          (conditionedMixedProfile (I := I) μ ha0 ss0) ha0 ss0)
        (ss0 ++ ssTail)
        =
      D.stepDist (InfoModel.realizeBehavioralCanonical (I := I) μFull) (ss0 ++ ssTail) := by
    apply stepDist_behavioral_depends_on_current_context (I := I) (D := D)
    intro i
    exact mixedToBehavioralAfter_eq_realizeBehavioralCanonical_reachable
      (I := I) (hPR := hPR) (μ := μ) hr0 i hr
  calc
    (Math.ProbabilityMassFunction.pushforward
      (D.stepDist
        (mixedToBehavioralAfter (I := I)
          (conditionedMixedProfile (I := I) μ ha0 ss0) ha0 ss0)
        (ss0 ++ ssTail))
      (fun t => (ss0 ++ ssTail) ++ [t])) y
        =
      (Math.ProbabilityMassFunction.pushforward
        (D.stepDist (InfoModel.realizeBehavioralCanonical (I := I) μFull) (ss0 ++ ssTail))
        (fun t => (ss0 ++ ssTail) ++ [t])) y := by
          simpa using congrArg
            (fun ν =>
              (Math.ProbabilityMassFunction.pushforward ν
                (fun t => (ss0 ++ ssTail) ++ [t])) y)
            hstep
    _ =
      ∑' π, (InfoModel.mixedJoint (I := I) μFull) π *
        ((Math.ProbabilityMassFunction.pushforward
          (D.stepDist (pureToBehavioral I π) (ss0 ++ ssTail))
          (fun t => (ss0 ++ ssTail) ++ [t])) y) := by
            simpa using
              (mixedJoint_stepPoint_eq_realizeBehavioralCanonical
                (I := I) (D := D) μFull (ss0 ++ ssTail) y).symm

theorem mixedToBehavioralAfter_stepActionStatePoint_eq_conditioned_reachable
    [∀ i, Fintype (I.LocalTrace i)]
    [∀ i, Fintype (InfoModel.LocalPure (I := I) i)]
    [∀ i, Fintype (Option (M.Act i))]
    (hPR : I.PerfectRecall)
    (μ : InfoModel.MixedProfile (I := I))
    {ha0 : List (JointAction M)}
    {ss0 : List M.State}
    (hr0 : InfoModel.ReachActionTrace M ha0 ss0)
    {haTail : List (JointAction M)}
    {ssTail : List M.State}
    (hr : InfoModel.ReachActionTrace M (ha0 ++ haTail) (ss0 ++ ssTail))
    (y : List (JointAction M) × List M.State) :
    let μFull := conditionedMixedProfile (I := I) μ (ha0 ++ haTail) (ss0 ++ ssTail)
    (Math.ProbabilityMassFunction.pushforward
      (D.stepActionStateDist
        (mixedToBehavioralAfter (I := I)
          (conditionedMixedProfile (I := I) μ ha0 ss0) ha0 ss0)
        (ss0 ++ ssTail))
      (fun x => ((ha0 ++ haTail) ++ [x.1], (ss0 ++ ssTail) ++ [x.2]))) y
      =
    ∑' π, (InfoModel.mixedJoint (I := I) μFull) π *
      ((Math.ProbabilityMassFunction.pushforward
        (D.stepActionStateDist (pureToBehavioral I π) (ss0 ++ ssTail))
        (fun x => ((ha0 ++ haTail) ++ [x.1], (ss0 ++ ssTail) ++ [x.2]))) y) := by
  classical
  let μFull : InfoModel.MixedProfile (I := I) :=
    conditionedMixedProfile (I := I) μ (ha0 ++ haTail) (ss0 ++ ssTail)
  have hstep :
      D.stepActionStateDist
        (mixedToBehavioralAfter (I := I)
          (conditionedMixedProfile (I := I) μ ha0 ss0) ha0 ss0)
        (ss0 ++ ssTail)
        =
      D.stepActionStateDist
        (InfoModel.realizeBehavioralCanonical (I := I) μFull)
        (ss0 ++ ssTail) := by
    apply stepActionStateDist_behavioral_depends_on_current_context (I := I) (D := D)
    intro i
    exact mixedToBehavioralAfter_eq_realizeBehavioralCanonical_reachable
      (I := I) (hPR := hPR) (μ := μ) hr0 i hr
  calc
    (Math.ProbabilityMassFunction.pushforward
      (D.stepActionStateDist
        (mixedToBehavioralAfter (I := I)
          (conditionedMixedProfile (I := I) μ ha0 ss0) ha0 ss0)
        (ss0 ++ ssTail))
      (fun x => ((ha0 ++ haTail) ++ [x.1], (ss0 ++ ssTail) ++ [x.2]))) y
        =
      (Math.ProbabilityMassFunction.pushforward
        (D.stepActionStateDist
          (InfoModel.realizeBehavioralCanonical (I := I) μFull)
          (ss0 ++ ssTail))
        (fun x => ((ha0 ++ haTail) ++ [x.1], (ss0 ++ ssTail) ++ [x.2]))) y := by
          simpa using congrArg
            (fun ν =>
              (Math.ProbabilityMassFunction.pushforward ν
                (fun x => ((ha0 ++ haTail) ++ [x.1], (ss0 ++ ssTail) ++ [x.2]))) y)
            hstep
    _ =
      ∑' π, (InfoModel.mixedJoint (I := I) μFull) π *
        ((Math.ProbabilityMassFunction.pushforward
          (D.stepActionStateDist (pureToBehavioral I π) (ss0 ++ ssTail))
          (fun x => ((ha0 ++ haTail) ++ [x.1], (ss0 ++ ssTail) ++ [x.2]))) y) := by
            simpa using
              (mixedJoint_stepActionStatePoint_eq_realizeBehavioralCanonical
                (I := I) (D := D) μFull (ha0 ++ haTail, ss0 ++ ssTail) y).symm

-- Reachable-prefix distributive law: conditioning the mixed profile on the
-- realized local history and then taking one continuation step gives the same
-- continuation law as first passing to `mixedToBehavioral`.
theorem kuhn_conditioning_distributes_over_sequencing
    [∀ i, Fintype (I.LocalTrace i)]
    [∀ i, Fintype (InfoModel.LocalPure (I := I) i)]
    [∀ i, Fintype (Option (M.Act i))]
    (hPR : I.PerfectRecall)
    (μ : InfoModel.MixedProfile (I := I))
    {ha : List (JointAction M)}
    {ss : List M.State}
    (hr : InfoModel.ReachActionTrace M ha ss) :
    Math.ProbabilityMassFunction.pushforward
      (D.stepDist (mixedToBehavioral (I := I) μ) ss)
      (fun t => ss ++ [t]) =
    (InfoModel.mixedJoint (I := I)
      (conditionedMixedProfile (I := I) μ ha ss)).bind
      (fun π =>
        Math.ProbabilityMassFunction.pushforward
          (D.stepDist (pureToBehavioral I π) ss)
          (fun t => ss ++ [t])) := by
  classical
  letI : DecidableEq ι := Classical.decEq ι
  ext y
  have hbeh_now :
      ∀ i,
        mixedToBehavioral (I := I) μ i (I.projectStates i ss) =
          InfoModel.realizeBehavioralCanonical (I := I)
            (conditionedMixedProfile (I := I) μ ha ss) i
            (I.projectStates i ss) := by
    intro i
    simpa [conditionedMixedProfile, InfoModel.realizeBehavioralCanonical] using
      mixedToBehavioral_eq_iterCond_pushforward
        (I := I) (hPR := hPR) (μ := μ) i hr
  have hstep_beh :
      D.stepDist (mixedToBehavioral (I := I) μ) ss =
        D.stepDist
          (InfoModel.realizeBehavioralCanonical (I := I)
            (conditionedMixedProfile (I := I) μ ha ss))
          ss := by
    apply stepDist_behavioral_depends_on_current_context (I := I) (D := D)
    intro i
    exact hbeh_now i
  calc
    (Math.ProbabilityMassFunction.pushforward
      (D.stepDist (mixedToBehavioral (I := I) μ) ss)
      (fun t => ss ++ [t])) y
        =
      (Math.ProbabilityMassFunction.pushforward
        (D.stepDist
          (InfoModel.realizeBehavioralCanonical (I := I)
            (conditionedMixedProfile (I := I) μ ha ss))
          ss)
        (fun t => ss ++ [t])) y := by
          simpa using congrArg
            (fun ν =>
              (Math.ProbabilityMassFunction.pushforward ν
                (fun t => ss ++ [t])) y)
            hstep_beh
    _ =
      ∑' π, (InfoModel.mixedJoint (I := I)
        (conditionedMixedProfile (I := I) μ ha ss)) π *
        ((Math.ProbabilityMassFunction.pushforward
          (D.stepDist (pureToBehavioral I π) ss)
          (fun t => ss ++ [t])) y) := by
            simpa using
              (mixedJoint_stepPoint_eq_realizeBehavioralCanonical
                (I := I) (D := D)
                (conditionedMixedProfile (I := I) μ ha ss) ss y).symm
    _ =
      ((InfoModel.mixedJoint (I := I)
        (conditionedMixedProfile (I := I) μ ha ss)).bind
        (fun π =>
          Math.ProbabilityMassFunction.pushforward
            (D.stepDist (pureToBehavioral I π) ss)
            (fun t => ss ++ [t]))) y := by
              simp [PMF.bind_apply]

theorem stepPoint_eq_via_query_disintegration
    [∀ i, Fintype (I.LocalTrace i)]
    [∀ i, Fintype (InfoModel.LocalPure (I := I) i)]
    [∀ i, Fintype (Option (M.Act i))]
    (hPR : I.PerfectRecall)
    (μ : InfoModel.MixedProfile (I := I))
    (n : Nat)
    (hs y : List M.State)
    (hlen : hs.length = n + 1) :
    let μJ : PMF (PureProfile I) := InfoModel.mixedJoint (I := I) μ
    let C : ENNReal := ∑' π, μJ π * (D.runDistPure n π) hs
    C *
      ((Math.ProbabilityMassFunction.pushforward
        (D.stepDist (mixedToBehavioral (I := I) μ) hs)
        (fun t => hs ++ [t])) y)
      =
    ∑' π, μJ π *
      ((D.runDistPure n π) hs *
        ((Math.ProbabilityMassFunction.pushforward
          (D.stepDist (pureToBehavioral I π) hs)
          (fun t => hs ++ [t])) y)) := by
  classical
  let μJ : PMF (PureProfile I) := InfoModel.mixedJoint (I := I) μ
  let v : ∀ i, I.LocalTrace i := fun i => I.projectStates i hs
  let stepPureY : PureProfile I → ENNReal := fun π =>
    (Math.ProbabilityMassFunction.pushforward
      (D.stepDist (pureToBehavioral I π) hs)
      (fun t => hs ++ [t])) y
  let q : PureProfile I → (∀ i, Option (M.Act i)) := fun π i => π i (v i)
  have hstepPure_dep_q :
      ∀ π : PureProfile I,
        stepPureY π = stepPureY (fun i _ => q π i) := by
    intro π
    unfold stepPureY q
    exact pure_step_pushforward_depends_on_query (I := I) (D := D) hs y π
      (fun i _ => q π i) (by intro i; rfl)
  -- Query-disintegration at `v`, then identification of conditional factors
  -- with `mixedToBehavioral` at `hs.2`.
  -- (Perfect recall is used for witness-independence of local histories.)
  let C : ENNReal := ∑' π, μJ π * (D.runDistPure n π) hs
  by_cases hC0 : C = 0
  · have hsum0 :
      ∑' π, μJ π *
        ((D.runDistPure n π) hs * stepPureY π) = 0 := by
      refine ENNReal.tsum_eq_zero.2 ?_
      intro π
      have hpi0 : μJ π * (D.runDistPure n π) hs = 0 := by
        apply (ENNReal.tsum_eq_zero.1 hC0)
      simpa [stepPureY, mul_assoc] using congrArg (fun z => z * stepPureY π) hpi0
    calc
      C *
        ((Math.ProbabilityMassFunction.pushforward
          (D.stepDist (mixedToBehavioral (I := I) μ) hs)
          (fun t => hs ++ [t])) y)
          = 0 := by rw [hC0, zero_mul]
      _ = ∑' π, μJ π *
            ((D.runDistPure n π) hs *
              ((Math.ProbabilityMassFunction.pushforward
                (D.stepDist (pureToBehavioral I π) hs)
                (fun t => hs ++ [t])) y)) := by
            simpa [stepPureY] using hsum0.symm
  · have hCpos : C ≠ 0 := hC0
    have hexists : ∃ π : PureProfile I, μJ π * (D.runDistPure n π) hs ≠ 0 := by
      by_contra hnone
      apply hCpos
      refine ENNReal.tsum_eq_zero.2 ?_
      intro π
      exact by_contra fun h => hnone ⟨π, h⟩
    obtain ⟨π0, hπ0⟩ := hexists
    have hrun0 : (D.runDistPure n π0) hs ≠ 0 := by
      intro hzero
      apply hπ0
      simp [hzero]
    obtain ⟨ha, hr, hcompat⟩ :=
      exists_reachActionTrace_of_runDistPure_ne_zero
        (I := I) (D := D) n π0 hs hrun0
    let hist : ∀ i, List (LocalHistTok (I := I) i) :=
      fun i => InfoModel.localHistTokens (I := I) i ha hs
    let μHist : InfoModel.MixedProfile (I := I) :=
      conditionedMixedProfile (I := I) μ ha hs
    have hbeh_now :
        ∀ i,
          mixedToBehavioral (I := I) μ i (I.projectStates i hs) =
            InfoModel.realizeBehavioralCanonical (I := I) μHist i
              (I.projectStates i hs) := by
      intro i
      simpa [μHist, conditionedMixedProfile, hist, InfoModel.realizeBehavioralCanonical] using
        mixedToBehavioral_eq_iterCond_pushforward
          (I := I) (hPR := hPR) (μ := μ) i hr
    have hstep_beh :
        D.stepDist (mixedToBehavioral (I := I) μ) hs =
          D.stepDist (InfoModel.realizeBehavioralCanonical (I := I) μHist) hs := by
      apply stepDist_behavioral_depends_on_current_context (I := I) (D := D)
      intro i
      exact hbeh_now i
    have hleft_rewrite :
        (Math.ProbabilityMassFunction.pushforward
          (D.stepDist (mixedToBehavioral (I := I) μ) hs)
          (fun t => hs ++ [t])) y
          =
        (∑' π, (InfoModel.mixedJoint (I := I) μHist) π * stepPureY π) := by
      calc
        (Math.ProbabilityMassFunction.pushforward
          (D.stepDist (mixedToBehavioral (I := I) μ) hs)
          (fun t => hs ++ [t])) y
            =
          (Math.ProbabilityMassFunction.pushforward
            (D.stepDist (InfoModel.realizeBehavioralCanonical (I := I) μHist) hs)
            (fun t => hs ++ [t])) y := by
              simpa using congrArg
                (fun ν =>
                  (Math.ProbabilityMassFunction.pushforward ν
                    (fun t => hs ++ [t])) y)
                hstep_beh
        _ = (∑' π, (InfoModel.mixedJoint (I := I) μHist) π * stepPureY π) := by
              simpa [stepPureY] using
                (mixedJoint_stepPoint_eq_realizeBehavioralCanonical
                  (I := I) (D := D) μHist hs y).symm
    have hfactor_run :
        ∃ traceMass compatMass : ENNReal,
          C = traceMass * compatMass ∧
          (∑' π, μJ π *
            ((D.runDistPure n π) hs * stepPureY π))
            = traceMass * compatMass *
                (∑' π, (InfoModel.mixedJoint (I := I) μHist) π * stepPureY π) := by
      have hhaLen : ha.length = n := by
        have hreachLen :=
          InfoModel.ReachActionTrace.length_states_eq_succ_actions hr
        exact Nat.succ.inj <| by
          simpa [Nat.add_comm, Nat.add_left_comm, Nat.add_assoc] using
            hreachLen.symm.trans hlen
      let traceMass : ENNReal := (D.runDistPure n π0) hs
      let compatMass : ENNReal :=
        ∏ i, localHistMass (I := I) i (μ i) (hist i)
      have hrun_factor :
          ∀ π : PureProfile I,
            (D.runDistPure n π) hs =
              traceMass *
                ∏ i, localHistIndicator (I := I) i (π i) (hist i) := by
        intro π
        dsimp [traceMass]
        calc
          (D.runDistPure n π) hs =
            D.runDistPure ha.length π hs := by
              simp [hhaLen]
          _ =
            D.runDistPure ha.length π0 hs *
              ∏ i, localHistIndicator (I := I) i (π i) (hist i) := by
                simpa [hist] using
                  runDistPure_factor_via_localHistIndicators
                    (I := I) (D := D) hPR hr π0 hcompat π
          _ =
            (D.runDistPure n π0) hs *
              ∏ i, localHistIndicator (I := I) i (π i) (hist i) := by
                simp [hhaLen]
      have hmixed_factor :
          ∀ π : PureProfile I,
            compatMass * (InfoModel.mixedJoint (I := I) μHist) π =
              μJ π * ∏ i, localHistIndicator (I := I) i (π i) (hist i) := by
        intro π
        simpa [compatMass, μHist, μJ] using
          localHistMass_mul_mixedJoint_iterCond_apply
            (I := I) (μ := μ) (hist := hist) π
      have hsum_indicators :
          ∑' π, μJ π *
            ∏ i, localHistIndicator (I := I) i (π i) (hist i) = compatMass := by
        calc
          ∑' π, μJ π *
            ∏ i, localHistIndicator (I := I) i (π i) (hist i)
              =
            ∑' π, compatMass * (InfoModel.mixedJoint (I := I) μHist) π := by
                refine tsum_congr ?_
                intro π
                exact (hmixed_factor π).symm
          _ = compatMass * ∑' π, (InfoModel.mixedJoint (I := I) μHist) π := by
                rw [ENNReal.tsum_mul_left]
          _ = compatMass * 1 := by
                simpa using congrArg (fun z : ENNReal => compatMass * z)
                  ((InfoModel.mixedJoint (I := I) μHist).tsum_coe)
          _ = compatMass := by simp
      refine ⟨traceMass, compatMass, ?_, ?_⟩
      · calc
          C = ∑' π, μJ π *
              (traceMass *
                ∏ i, localHistIndicator (I := I) i (π i) (hist i)) := by
                refine tsum_congr ?_
                intro π
                rw [hrun_factor π]
          _ = ∑' π, traceMass *
              (μJ π * ∏ i, localHistIndicator (I := I) i (π i) (hist i)) := by
                refine tsum_congr ?_
                intro π
                ac_rfl
          _ = traceMass *
              ∑' π, μJ π *
                ∏ i, localHistIndicator (I := I) i (π i) (hist i) := by
                rw [ENNReal.tsum_mul_left]
          _ = traceMass * compatMass := by
                rw [hsum_indicators]
      · calc
          (∑' π, μJ π *
            ((D.runDistPure n π) hs * stepPureY π))
              =
            ∑' π, μJ π *
              ((traceMass *
                ∏ i, localHistIndicator (I := I) i (π i) (hist i)) *
                stepPureY π) := by
                  refine tsum_congr ?_
                  intro π
                  rw [hrun_factor π]
          _ = ∑' π, traceMass *
              ((μJ π *
                ∏ i, localHistIndicator (I := I) i (π i) (hist i)) *
                stepPureY π) := by
                  refine tsum_congr ?_
                  intro π
                  ac_rfl
          _ = traceMass *
              ∑' π, ((μJ π *
                ∏ i, localHistIndicator (I := I) i (π i) (hist i)) *
                stepPureY π) := by
                  rw [ENNReal.tsum_mul_left]
          _ = traceMass *
              ∑' π, ((compatMass *
                (InfoModel.mixedJoint (I := I) μHist) π) *
                stepPureY π) := by
                  congr 1
                  refine tsum_congr ?_
                  intro π
                  rw [← hmixed_factor π]
          _ = traceMass *
              (compatMass *
                ∑' π, (InfoModel.mixedJoint (I := I) μHist) π * stepPureY π) := by
                  congr 1
                  calc
                    ∑' π, ((compatMass *
                      (InfoModel.mixedJoint (I := I) μHist) π) *
                      stepPureY π)
                        =
                      ∑' π, compatMass *
                        ((InfoModel.mixedJoint (I := I) μHist) π * stepPureY π) := by
                          refine tsum_congr ?_
                          intro π
                          ac_rfl
                    _ = compatMass *
                        ∑' π, (InfoModel.mixedJoint (I := I) μHist) π * stepPureY π := by
                          rw [ENNReal.tsum_mul_left]
          _ = traceMass * compatMass *
              (∑' π, (InfoModel.mixedJoint (I := I) μHist) π * stepPureY π) := by
                ac_rfl
    rcases hfactor_run with ⟨traceMass, compatMass, hCfact, hRfact⟩
    calc
      C *
        ((Math.ProbabilityMassFunction.pushforward
          (D.stepDist (mixedToBehavioral (I := I) μ) hs)
          (fun t => hs ++ [t])) y)
          = (traceMass * compatMass) *
              (∑' π, (InfoModel.mixedJoint (I := I) μHist) π * stepPureY π) := by
                rw [hCfact, hleft_rewrite]
      _ = ∑' π, μJ π *
            ((D.runDistPure n π) hs * stepPureY π) := by
            simpa [mul_assoc, mul_left_comm, mul_comm] using hRfact.symm
      _ = ∑' π, μJ π *
            ((D.runDistPure n π) hs *
              ((Math.ProbabilityMassFunction.pushforward
                (D.stepDist (pureToBehavioral I π) hs)
                (fun t => hs ++ [t])) y)) := by
            simp [stepPureY]

theorem mixedToBehavioral_stepIndependence
    [∀ i, Fintype (I.LocalTrace i)]
    [∀ i, Fintype (InfoModel.LocalPure (I := I) i)]
    [∀ i, Fintype (Option (M.Act i))]
    (hPR : I.PerfectRecall)
    (μ : InfoModel.MixedProfile (I := I)) :
    ∀ n,
      (InfoModel.mixedJoint (I := I) μ).bind (fun π =>
        (D.runDistPure n π).bind (fun hs =>
          Math.ProbabilityMassFunction.pushforward
            (D.stepDist (mixedToBehavioral (I := I) μ) hs)
            (fun t => hs ++ [t]))) =
      (InfoModel.mixedJoint (I := I) μ).bind (fun π =>
        (D.runDistPure n π).bind (fun hs =>
          Math.ProbabilityMassFunction.pushforward
            (D.stepDist (pureToBehavioral I π) hs)
            (fun t => hs ++ [t]))) := by
  intro n
  classical
  ext y
  set μJ : PMF (PureProfile I) := InfoModel.mixedJoint (I := I) μ
  let Lfun : (List M.State) → ENNReal :=
    fun hs =>
      (Math.ProbabilityMassFunction.pushforward
        (D.stepDist (mixedToBehavioral (I := I) μ) hs)
        (fun t => hs ++ [t])) y
  let Gfun : (List M.State) → PureProfile I → ENNReal :=
    fun hs π =>
      (Math.ProbabilityMassFunction.pushforward
        (D.stepDist (pureToBehavioral I π) hs)
        (fun t => hs ++ [t])) y
  let FL : PureProfile I → (List M.State) → ENNReal :=
    fun π hs => μJ π * ((D.runDistPure n π) hs * Lfun hs)
  let FR : PureProfile I → (List M.State) → ENNReal :=
    fun π hs => μJ π * ((D.runDistPure n π) hs * Gfun hs π)
  have hswapL :
      (∑' π, μJ π * ∑' hs, (D.runDistPure n π) hs * Lfun hs)
        = ∑' hs, ∑' π, FL π hs := by
    calc
      (∑' π, μJ π * ∑' hs, (D.runDistPure n π) hs * Lfun hs)
          = ∑' π, ∑' hs, μJ π * ((D.runDistPure n π) hs * Lfun hs) := by
              refine tsum_congr ?_
              intro π
              rw [ENNReal.tsum_mul_left]
      _ = ∑' hs, ∑' π, μJ π * ((D.runDistPure n π) hs * Lfun hs) := by
            simpa using
              (ENNReal.tsum_comm
                (f := fun π hs => μJ π * ((D.runDistPure n π) hs * Lfun hs)))
      _ = ∑' hs, ∑' π, FL π hs := by simp [FL]
  have hswapR :
      (∑' π, μJ π * ∑' hs, (D.runDistPure n π) hs * Gfun hs π)
        = ∑' hs, ∑' π, FR π hs := by
    calc
      (∑' π, μJ π * ∑' hs, (D.runDistPure n π) hs * Gfun hs π)
          = ∑' π, ∑' hs, μJ π * ((D.runDistPure n π) hs * Gfun hs π) := by
              refine tsum_congr ?_
              intro π
              rw [ENNReal.tsum_mul_left]
      _ = ∑' hs, ∑' π, μJ π * ((D.runDistPure n π) hs * Gfun hs π) := by
            simpa using
              (ENNReal.tsum_comm
                (f := fun π hs => μJ π * ((D.runDistPure n π) hs * Gfun hs π)))
      _ = ∑' hs, ∑' π, FR π hs := by simp [FR]
  have hPerHs :
      ∀ hs : List M.State, (∑' π, FL π hs) = ∑' π, FR π hs := by
    intro hs
    by_cases hlen : hs.length = n + 1
    · let C : ENNReal := ∑' π, μJ π * (D.runDistPure n π) hs
      have hL :
          (∑' π, FL π hs) = C * Lfun hs := by
        calc
          (∑' π, FL π hs)
              = ∑' π, μJ π * ((D.runDistPure n π) hs * Lfun hs) := by
                  simp [FL]
          _ = ∑' π, (μJ π * (D.runDistPure n π) hs) * Lfun hs := by
                apply tsum_congr
                intro π
                ring
          _ = (∑' π, μJ π * (D.runDistPure n π) hs) * Lfun hs := by
                rw [ENNReal.tsum_mul_right]
          _ = C * Lfun hs := rfl
      have hR :
          (∑' π, FR π hs) =
            ∑' π, μJ π * ((D.runDistPure n π) hs * Gfun hs π) := by
        simp [FR, mul_assoc, mul_comm]
      have hBridge :
          C * Lfun hs =
            ∑' π, μJ π * ((D.runDistPure n π) hs * Gfun hs π) := by
        simpa [Lfun, Gfun, C, mul_assoc, mul_left_comm, mul_comm] using
          (stepPoint_eq_via_query_disintegration
            (I := I) (D := D) (hPR := hPR) (μ := μ) (n := n) (hs := hs) (y := y) hlen)
      exact hL.trans (hBridge.trans hR.symm)
    · have hfzero : ∀ π : PureProfile I, (D.runDistPure n π) hs = 0 := by
        intro π
        by_contra hne
        have hlen' :
            hs.length = n + 1 := by
          have hrun : (D.runDist n (pureToBehavioral I π)) hs ≠ 0 := by
            simpa [Execution.Dynamics.runDistPure] using hne
          exact InfoModel.runDist_support_stateLength (I := I) (D := D) n
            (pureToBehavioral I π) hs hrun
        exact hlen hlen'
      have hFL0 : (∑' π, FL π hs) = 0 := by
        exact (ENNReal.tsum_eq_zero).2 (by intro π; simp [FL, hfzero π])
      have hFR0 : (∑' π, FR π hs) = 0 := by
        exact (ENNReal.tsum_eq_zero).2 (by intro π; simp [FR, hfzero π])
      rw [hFL0, hFR0]
  calc
    (μJ.bind (fun π =>
      (D.runDistPure n π).bind (fun hs =>
        Math.ProbabilityMassFunction.pushforward
          (D.stepDist (mixedToBehavioral (I := I) μ) hs)
          (fun t => hs ++ [t])))) y
        = (∑' π, μJ π * ∑' hs, (D.runDistPure n π) hs * Lfun hs) := by
            simp [μJ, Lfun, PMF.bind_apply]
    _ = ∑' hs, ∑' π, FL π hs := hswapL
    _ = ∑' hs, ∑' π, FR π hs := by
          apply tsum_congr
          intro hs
          exact hPerHs hs
    _ = (∑' π, μJ π * ∑' hs, (D.runDistPure n π) hs * Gfun hs π) := hswapR.symm
    _ = (μJ.bind (fun π =>
      (D.runDistPure n π).bind (fun hs =>
        Math.ProbabilityMassFunction.pushforward
          (D.stepDist (pureToBehavioral I π) hs)
          (fun t => hs ++ [t])))) y := by
            simp [μJ, Gfun, PMF.bind_apply]

/-- Kuhn's mixed-to-behavioral direction for `InfoModel` outcome distributions. -/
theorem mixedToBehavioral_correct
    [∀ i, Fintype (I.LocalTrace i)]
    [∀ i, Fintype (InfoModel.LocalPure (I := I) i)]
    [∀ i, Fintype (Option (M.Act i))]
    (hPR : I.PerfectRecall)
    (μ : InfoModel.MixedProfile (I := I)) :
    D.evalBehavioral k (mixedToBehavioral (I := I) μ) =
      (InfoModel.mixedJoint (I := I) μ).bind (D.evalPure k) := by
  exact evalBehavioral_eq_mixed_of_stepIndependence (I := I) (D := D) (k := k) μ
    (mixedToBehavioral (I := I) μ)
    (mixedToBehavioral_stepIndependence (I := I) (D := D) hPR μ)

theorem kuhn_mixed_to_behavioral
    [∀ i, Finite (I.LocalTrace i)]
    [∀ i, Fintype (InfoModel.LocalPure (I := I) i)]
    [∀ i, Fintype (Option (M.Act i))]
    (hPR : I.PerfectRecall) :
    KuhnMixedToBehavioralViaOutcome
      (BehavioralProfile I) (InfoModel.MixedProfile (I := I)) (PureProfile I) I.Outcome
      (InfoModel.mixedJoint (I := I)) (D.evalBehavioral k) (D.evalPure k) := by
  letI : ∀ i, Fintype (I.LocalTrace i) := fun i => Fintype.ofFinite (I.LocalTrace i)
  intro μ
  refine ⟨mixedToBehavioral (I := I) μ, ?_⟩
  simpa using mixedToBehavioral_correct (I := I) (D := D) (k := k) hPR μ

end InfoModel

end Theorems
end GameTheory


