/-
Copyright (c) 2025 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/
import GameTheory.Concepts.Repeated.MonitoringDecomposition

/-!
# Self-Generating Payoff Sets under Public Monitoring

This file constructs the public strategy selected by an APS self-generating
set.  Promised payoff vectors are strategy states; after each public signal,
the state moves to the continuation payoff selected by the decomposition.
-/

noncomputable section

namespace GameTheory

namespace KernelGame

namespace PublicMonitoring

variable {ι : Type} {G : KernelGame ι}

/-- Coordinatewise boundedness of a payoff set. -/
def IsBoundedPayoffSet (W : Set (Payoff ι)) : Prop :=
  ∀ who, ∃ C : ℝ, ∀ v ∈ W, |v who| ≤ C

/-- Payoff vectors delivered by perfect-public equilibria. -/
def perfectPublicEquilibriumPayoffs
    (M : G.PublicMonitoring) [DecidableEq ι] (δ : ℝ) : Set (Payoff ι) :=
  {v | ∃ σ : M.MonitoredProfile,
    M.IsPerfectPublicEquilibrium δ σ ∧
      ∀ who, M.discountedAveragePayoff δ σ who = v who}

namespace SelfGenerating

variable {M : G.PublicMonitoring} [DecidableEq ι]
variable {δ : ℝ} {W : Set (Payoff ι)}

/-- Current action profile selected from a self-generating decomposition. -/
noncomputable def action
    (h : M.SelfGenerating δ W) (v : W) : Profile G :=
  (h v.1 v.2).choose

/-- Public continuation assignment selected from a self-generating
decomposition. -/
noncomputable def continuation
    (h : M.SelfGenerating δ W) (v : W) : M.ContinuationAssignment :=
  (h v.1 v.2).choose_spec.choose

theorem continuation_bounded
    (h : M.SelfGenerating δ W) (v : W) :
    M.IsBoundedContinuationAssignment (h.continuation v) :=
  (h v.1 v.2).choose_spec.choose_spec.1

theorem continuation_mem
    (h : M.SelfGenerating δ W) (v : W) (y : M.Signal) :
    h.continuation v y ∈ W :=
  (h v.1 v.2).choose_spec.choose_spec.2.1 y

theorem promiseKeeping
    (h : M.SelfGenerating δ W) (v : W) :
    M.IsPromiseKeeping δ v.1 (h.action v) (h.continuation v) :=
  (h v.1 v.2).choose_spec.choose_spec.2.2.1

theorem enforceable
    (h : M.SelfGenerating δ W) (v : W) :
    M.IsEnforceable δ (h.action v) (h.continuation v) :=
  (h v.1 v.2).choose_spec.choose_spec.2.2.2

/-- Promise state reached after one public signal. -/
noncomputable def nextState
    (h : M.SelfGenerating δ W) (v : W) (y : M.Signal) : W :=
  ⟨h.continuation v y, h.continuation_mem v y⟩

@[simp] theorem nextState_val
    (h : M.SelfGenerating δ W) (v : W) (y : M.Signal) :
    (h.nextState v y).1 = h.continuation v y :=
  rfl

/-- Promise state reached after a finite chronological list of public
signals. -/
noncomputable def stateAfterSignals
    (h : M.SelfGenerating δ W) : W → List M.Signal → W
  | v, [] => v
  | v, y :: ys => h.stateAfterSignals (h.nextState v y) ys

@[simp] theorem stateAfterSignals_nil
    (h : M.SelfGenerating δ W) (v : W) :
    h.stateAfterSignals v [] = v :=
  rfl

@[simp] theorem stateAfterSignals_cons
    (h : M.SelfGenerating δ W) (v : W)
    (y : M.Signal) (ys : List M.Signal) :
    h.stateAfterSignals v (y :: ys) =
      h.stateAfterSignals (h.nextState v y) ys :=
  rfl

/-- Public strategy generated by repeatedly selecting the decomposition of
the current promised payoff state. -/
noncomputable def generatedProfile
    (h : M.SelfGenerating δ W) (v : W) : M.MonitoredProfile :=
  fun i _ hist => h.action (h.stateAfterSignals v (List.ofFn hist)) i

@[simp] theorem generatedProfile_zero
    (h : M.SelfGenerating δ W) (v : W) (i : ι)
    (hist : M.SignalHistory 0) :
    h.generatedProfile v i 0 hist = h.action v i := by
  simp [generatedProfile]

/-- The generated strategy continues from the selected next promise state. -/
theorem afterSignal_generatedProfile
    (h : M.SelfGenerating δ W) (v : W) (y : M.Signal) :
    M.afterSignal (h.generatedProfile v) y =
      h.generatedProfile (h.nextState v y) := by
  funext i n hist
  simp [afterSignal, generatedProfile, List.ofFn_succ]

/-- Iterated continuation follows the corresponding iterated promise-state
transition. -/
theorem afterSignals_generatedProfile
    (h : M.SelfGenerating δ W) (v : W) (ys : List M.Signal) :
    M.afterSignals (h.generatedProfile v) ys =
      h.generatedProfile (h.stateAfterSignals v ys) := by
  induction ys generalizing v with
  | nil => rfl
  | cons y ys ih =>
      rw [M.afterSignals_cons, h.afterSignal_generatedProfile, ih]
      rfl

/-- Continuation after an arbitrary public history is the generated strategy
from the promise state reached along that history. -/
theorem after_generatedProfile
    (h : M.SelfGenerating δ W) (v : W)
    {t : ℕ} (hist : M.SignalHistory t) :
    M.after (h.generatedProfile v) hist =
      h.generatedProfile (h.stateAfterSignals v (List.ofFn hist)) := by
  exact h.afterSignals_generatedProfile v (List.ofFn hist)

end SelfGenerating

end PublicMonitoring

end KernelGame

end GameTheory
