/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/
import Mathlib.Analysis.Convex.Topology
import GameTheory.Concepts.Repeated.MonitoringSelfGeneration

/-!
# Public Randomization under Public Monitoring

Finite public lotteries convexify payoff sets. This module records both the
geometric presentation, as a real convex hull, and the operational
presentation, as the expected payoff of a finite `PMF` whose branches lie in
the original set.

This is an ex-ante payoff-set construction. The existing monitoring signal is
drawn after current actions and is not reinterpreted as a pre-action public
coin.
-/

noncomputable section

open scoped BigOperators

namespace GameTheory

namespace KernelGame

namespace PublicMonitoring

variable {ι : Type} {G : KernelGame ι}

/-- The payoff set generated by finite public lotteries over `W`. -/
def publicRandomizationHull (W : Set (Payoff ι)) : Set (Payoff ι) :=
  convexHull ℝ W

/-- Operational witness that `v` is the expected payoff of a finite public
lottery whose branch payoffs lie in `W`. -/
def IsFinitePublicRandomizationOf
    (W : Set (Payoff ι)) (v : Payoff ι) : Prop :=
  ∃ (α : Type) (_ : Fintype α) (ν : PMF α) (x : α → Payoff ι),
    (∀ z, x z ∈ W) ∧
      ∀ who, Math.Probability.expect ν (fun z => x z who) = v who

/-- The PMF and convex-hull presentations of finite public randomization are
equivalent. -/
theorem mem_publicRandomizationHull_iff
    (W : Set (Payoff ι)) (v : Payoff ι) :
    v ∈ publicRandomizationHull W ↔
      IsFinitePublicRandomizationOf W v := by
  constructor
  · intro hv
    obtain ⟨α, inst, weight, x, hweight0, hweight1, hx, hv⟩ :=
      mem_convexHull_iff_exists_fintype.mp hv
    letI : Fintype α := inst
    let ν : PMF α :=
      PMF.ofFintype (fun z => ENNReal.ofReal (weight z)) (by
        rw [← ENNReal.ofReal_one, ← hweight1]
        exact (ENNReal.ofReal_sum_of_nonneg
          (fun z _ => hweight0 z)).symm)
    refine ⟨α, inferInstance, ν, x, hx, ?_⟩
    intro who
    rw [Math.Probability.expect_eq_sum]
    have hν (z : α) : (ν z).toReal = weight z := by
      simp [ν, PMF.ofFintype_apply, ENNReal.toReal_ofReal (hweight0 z)]
    have hvwho := congrFun hv who
    simpa [hν, Pi.smul_apply, smul_eq_mul] using hvwho
  · rintro ⟨α, inst, ν, x, hx, hv⟩
    letI : Fintype α := inst
    apply mem_convexHull_of_exists_fintype
      (fun z => (ν z).toReal) x
    · exact fun _ => ENNReal.toReal_nonneg
    · exact Math.Probability.pmf_toReal_sum_one ν
    · exact hx
    · funext who
      simpa [Math.Probability.expect_eq_sum, Pi.smul_apply, smul_eq_mul]
        using hv who

/-- Every original payoff is available through a degenerate public lottery. -/
theorem subset_publicRandomizationHull (W : Set (Payoff ι)) :
    W ⊆ publicRandomizationHull W :=
  subset_convexHull ℝ W

/-- Enlarging the branch payoff set enlarges its public-randomization hull. -/
theorem publicRandomizationHull_mono {W W' : Set (Payoff ι)}
    (h : W ⊆ W') :
    publicRandomizationHull W ⊆ publicRandomizationHull W' :=
  convexHull_mono h

/-- Public randomization produces a convex payoff set. -/
theorem convex_publicRandomizationHull (W : Set (Payoff ι)) :
    Convex ℝ (publicRandomizationHull W) :=
  convex_convexHull ℝ W

/-- Exact binary public randomization stays in the public-randomization
hull. -/
theorem publicRandomizationHull_combo
    (W : Set (Payoff ι)) {v w : Payoff ι}
    (hv : v ∈ publicRandomizationHull W)
    (hw : w ∈ publicRandomizationHull W)
    {p : ℝ} (hp0 : 0 ≤ p) (hp1 : p ≤ 1) :
    (fun who => p * v who + (1 - p) * w who) ∈
      publicRandomizationHull W := by
  have hmem := (convex_iff_add_mem.mp (convex_publicRandomizationHull W))
    hv hw hp0 (sub_nonneg.mpr hp1) (by ring)
  have heq : p • v + (1 - p) • w =
      (fun who => p * v who + (1 - p) * w who) := by
    funext who
    rfl
  rw [← heq]
  exact hmem

/-- Public randomization preserves coordinatewise boundedness. -/
theorem isBoundedPayoffSet_publicRandomizationHull
    {W : Set (Payoff ι)} (hW : IsBoundedPayoffSet W) :
    IsBoundedPayoffSet (publicRandomizationHull W) := by
  intro who
  obtain ⟨C, hC⟩ := hW who
  let C' := max C 0
  refine ⟨C', ?_⟩
  intro v hv
  rw [mem_publicRandomizationHull_iff] at hv
  obtain ⟨α, inst, ν, x, hx, hv⟩ := hv
  letI : Fintype α := inst
  rw [← hv who, Math.Probability.expect_eq_sum]
  calc
    |∑ z, (ν z).toReal * x z who| ≤
        ∑ z, |(ν z).toReal * x z who| :=
      Finset.abs_sum_le_sum_abs _ _
    _ ≤ ∑ z, (ν z).toReal * C' := by
      apply Finset.sum_le_sum
      intro z _
      rw [abs_mul, abs_of_nonneg ENNReal.toReal_nonneg]
      exact mul_le_mul_of_nonneg_left
        ((hC (x z) (hx z)).trans (le_max_left C 0))
        ENNReal.toReal_nonneg
    _ = C' := by
      rw [← Finset.sum_mul, Math.Probability.pmf_toReal_sum_one, one_mul]

/-- A payoff set is unchanged by public randomization exactly when it is
convex. -/
theorem publicRandomizationHull_eq_self_iff (W : Set (Payoff ι)) :
    publicRandomizationHull W = W ↔ Convex ℝ W :=
  convexHull_eq_self

/-- The public-randomized PPE payoff set is the finite public-lottery hull of
ordinary PPE payoff vectors. -/
def publicRandomizedPerfectPublicEquilibriumPayoffs
    (M : G.PublicMonitoring) [DecidableEq ι] (δ : ℝ) : Set (Payoff ι) :=
  publicRandomizationHull (M.perfectPublicEquilibriumPayoffs δ)

/-- Every ordinary PPE payoff is a public-randomized PPE payoff. -/
theorem perfectPublicEquilibriumPayoffs_subset_publicRandomized
    (M : G.PublicMonitoring) [DecidableEq ι] (δ : ℝ) :
    M.perfectPublicEquilibriumPayoffs δ ⊆
      M.publicRandomizedPerfectPublicEquilibriumPayoffs δ :=
  subset_publicRandomizationHull _

/-- Public-randomized PPE payoffs form a convex set. -/
theorem convex_publicRandomizedPerfectPublicEquilibriumPayoffs
    (M : G.PublicMonitoring) [DecidableEq ι] (δ : ℝ) :
    Convex ℝ (M.publicRandomizedPerfectPublicEquilibriumPayoffs δ) :=
  convex_publicRandomizationHull _

/-- Binary public randomization between public-randomized PPE payoffs remains
a public-randomized PPE payoff. -/
theorem publicRandomizedPerfectPublicEquilibriumPayoffs_combo
    (M : G.PublicMonitoring) [DecidableEq ι]
    {δ : ℝ} {v w : Payoff ι}
    (hv : v ∈ M.publicRandomizedPerfectPublicEquilibriumPayoffs δ)
    (hw : w ∈ M.publicRandomizedPerfectPublicEquilibriumPayoffs δ)
    {p : ℝ} (hp0 : 0 ≤ p) (hp1 : p ≤ 1) :
    (fun who => p * v who + (1 - p) * w who) ∈
      M.publicRandomizedPerfectPublicEquilibriumPayoffs δ :=
  publicRandomizationHull_combo _ hv hw hp0 hp1

/-- Under bounded stage payoffs, public-randomized PPE payoffs remain
coordinatewise bounded. -/
theorem isBoundedPayoffSet_publicRandomizedPerfectPublicEquilibriumPayoffs_of_bounded
    (M : G.PublicMonitoring) [DecidableEq ι]
    {δ : ℝ} (hδ0 : 0 ≤ δ) (hδ1 : δ < 1)
    (hstage : ∀ who : ι, ∃ C : ℝ,
      ∀ a : Profile G, |G.eu a who| ≤ C) :
    IsBoundedPayoffSet
      (M.publicRandomizedPerfectPublicEquilibriumPayoffs δ) :=
  isBoundedPayoffSet_publicRandomizationHull
    (M.isBoundedPayoffSet_perfectPublicEquilibriumPayoffs_of_bounded
      hδ0 hδ1 hstage)

/-- A finite public lottery over ordinary PPE payoffs delivers a
public-randomized PPE payoff. -/
theorem finitePublicRandomization_mem_publicRandomizedPPE
    (M : G.PublicMonitoring) [DecidableEq ι]
    {δ : ℝ} {α : Type} [Finite α]
    (ν : PMF α) (x : α → Payoff ι)
    (hx : ∀ z, x z ∈ M.perfectPublicEquilibriumPayoffs δ) :
    (fun who => Math.Probability.expect ν (fun z => x z who)) ∈
      M.publicRandomizedPerfectPublicEquilibriumPayoffs δ := by
  letI : Fintype α := Fintype.ofFinite α
  unfold publicRandomizedPerfectPublicEquilibriumPayoffs
  rw [mem_publicRandomizationHull_iff]
  exact ⟨α, inferInstance, ν, x, hx, fun _ => rfl⟩

/-- Every bounded self-generating payoff set remains attainable after public
randomization: finite public lotteries over its payoffs are public-randomized
PPE payoffs. -/
theorem SelfGenerating.publicRandomizationHull_subset_publicRandomizedPPE
    {M : G.PublicMonitoring} [DecidableEq ι]
    {δ : ℝ} (hδ0 : 0 ≤ δ) (hδ1 : δ < 1)
    (hstage : ∀ who : ι, ∃ C : ℝ,
      ∀ a : Profile G, |G.eu a who| ≤ C)
    {W : Set (Payoff ι)} (hW : IsBoundedPayoffSet W)
    (h : M.SelfGenerating δ W) :
    publicRandomizationHull W ⊆
      M.publicRandomizedPerfectPublicEquilibriumPayoffs δ := by
  apply publicRandomizationHull_mono
  exact h.selfGenerating_subset_perfectPublicEquilibriumPayoffs
    M hδ0 hδ1 hstage hW

/-- Finite-outcome convenience form for public randomizations over a
self-generating set. -/
theorem SelfGenerating.publicRandomizationHull_subset_publicRandomizedPPE_of_finite_outcome
    {M : G.PublicMonitoring} [DecidableEq ι] [Finite G.Outcome]
    {δ : ℝ} (hδ0 : 0 ≤ δ) (hδ1 : δ < 1)
    {W : Set (Payoff ι)} (hW : IsBoundedPayoffSet W)
    (h : M.SelfGenerating δ W) :
    publicRandomizationHull W ⊆
      M.publicRandomizedPerfectPublicEquilibriumPayoffs δ := by
  apply h.publicRandomizationHull_subset_publicRandomizedPPE
    hδ0 hδ1 _ hW
  exact fun who => G.exists_eu_abs_bound_of_finite_outcome who

/-! ## Convexified APS operator -/

/-- The APS decomposition operator followed by finite public randomization. -/
def publicDecompositionOperator
    (M : G.PublicMonitoring) [DecidableEq ι]
    (δ : ℝ) (W : Set (Payoff ι)) : Set (Payoff ι) :=
  publicRandomizationHull (M.decompositionOperator δ W)

/-- A set is publicly self-generating when each promise is a finite public
lottery over payoffs that decompose using continuations in the set. -/
def PublicSelfGenerating
    (M : G.PublicMonitoring) [DecidableEq ι]
    (δ : ℝ) (W : Set (Payoff ι)) : Prop :=
  W ⊆ M.publicDecompositionOperator δ W

/-- The public decomposition operator is monotone in its continuation set. -/
theorem publicDecompositionOperator_mono
    (M : G.PublicMonitoring) [DecidableEq ι] (δ : ℝ) :
    Monotone (M.publicDecompositionOperator δ) := by
  intro W W' hWW'
  apply publicRandomizationHull_mono
  exact M.decompositionOperator_mono δ hWW'

/-- Every public decomposition-operator value set is convex. -/
theorem convex_publicDecompositionOperator
    (M : G.PublicMonitoring) [DecidableEq ι]
    (δ : ℝ) (W : Set (Payoff ι)) :
    Convex ℝ (M.publicDecompositionOperator δ W) :=
  convex_publicRandomizationHull _

/-- Ordinary self-generation is a special case of public self-generation,
using degenerate public lotteries. -/
theorem SelfGenerating.publicSelfGenerating
    {M : G.PublicMonitoring} [DecidableEq ι]
    {δ : ℝ} {W : Set (Payoff ι)}
    (h : M.SelfGenerating δ W) :
    M.PublicSelfGenerating δ W := by
  intro v hv
  exact subset_publicRandomizationHull _ (h v hv)

@[simp] theorem publicSelfGenerating_empty
    (M : G.PublicMonitoring) [DecidableEq ι] (δ : ℝ) :
    M.PublicSelfGenerating δ (∅ : Set (Payoff ι)) := by
  simp [PublicSelfGenerating]

end PublicMonitoring

end KernelGame

end GameTheory
