/-
Copyright (c) 2025 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/

import GameTheory.Concepts.Communication.Babbling
import GameTheory.Concepts.Correlation.CorrelationRegimes

/-!
# Cheap-Talk Play as Induced Public Randomness

For an observable cheap-talk mixed profile, the realized message profile is a
public signal.  Conditional on that signal, the independently sampled
cheap-talk strategies factor player-by-player, and each player induces a mixed
base-game action by evaluating their contingent plan at the public message.

The main distributional theorem is
`CheapTalkExtension.mixedActionLaw_eq_publicCorrelatedLaw`: the law of base
action profiles generated by mixed cheap-talk play is exactly the
`publicCorrelatedLaw` generated by the public message signal and the conditional
base mixed profiles.

The file then records the solution-concept consequences when the induced public
regime is a public-signal Nash regime: the cheap-talk action law is a CE,
hence a CCE, its payoff vector is a mixture of mixed-Nash payoff vectors, and in
two-player constant/zero-sum games it has the Nash value.
-/

noncomputable section

namespace GameTheory

open Math.Probability

namespace KernelGame

open Math.PMFProduct
open Math.ProbabilityMassFunction

variable {ι : Type} [DecidableEq ι]
variable {G : KernelGame ι}

namespace CheapTalkExtension

/-- Message profiles in an observable cheap-talk extension. -/
abbrev MessageProfile (C : G.CheapTalkExtension) : Type :=
  ∀ i : ι, C.Msg i

instance instFiniteGameOutcome (C : G.CheapTalkExtension) [Finite G.Outcome] :
    Finite C.game.Outcome := by
  change Finite G.Outcome
  infer_instance

/-- The marginal distribution of player `i`'s cheap-talk message under a mixed
cheap-talk profile. -/
noncomputable def mixedMessageMarginal (C : G.CheapTalkExtension) [Fintype ι]
    (τ : Profile C.game.mixedExtension) (i : ι) : PMF (C.Msg i) :=
  pushforward (τ i) (fun s : C.game.Strategy i => s.1)

/-- The public signal law generated by a mixed cheap-talk profile: independently
sample each player's cheap-talk strategy and retain only the message profile. -/
noncomputable def mixedMessageLaw (C : G.CheapTalkExtension) [Fintype ι]
    (τ : Profile C.game.mixedExtension) : PMF C.MessageProfile :=
  pmfPi (A := fun i => C.Msg i) (fun i => C.mixedMessageMarginal τ i)

/-- Player `i`'s conditional cheap-talk strategy distribution after the public
message profile `m` is observed.  At zero-probability messages this uses the
`condOn` fallback; all public-regime theorems only inspect positive-probability
signals. -/
noncomputable def conditionalCheapTalkStrategy (C : G.CheapTalkExtension) [Fintype ι]
    (τ : Profile C.game.mixedExtension) (m : C.MessageProfile) (i : ι) :
    PMF (C.game.Strategy i) :=
  condOn (τ i) (fun s : C.game.Strategy i => s.1) (m i)

/-- The product of the playerwise conditional cheap-talk strategy laws after
public message `m`. -/
noncomputable def conditionalCheapTalkProfile (C : G.CheapTalkExtension) [Fintype ι]
    (τ : Profile C.game.mixedExtension) (m : C.MessageProfile) :
    Profile C.game.mixedExtension :=
  fun i => C.conditionalCheapTalkStrategy τ m i

/-- The base-game mixed profile selected by public message `m`: each player
conditions their cheap-talk strategy on their message and evaluates the
contingent plan at the public message profile. -/
noncomputable def publicPlay (C : G.CheapTalkExtension) [Fintype ι]
    (τ : Profile C.game.mixedExtension) (m : C.MessageProfile) :
    Profile G.mixedExtension :=
  fun i => pushforward (C.conditionalCheapTalkStrategy τ m i)
    (fun s : C.game.Strategy i => s.2 m)

/-- The base action-profile law generated by mixed play in the cheap-talk
extension. -/
noncomputable def actionLaw (C : G.CheapTalkExtension)
    (μ : PMF C.game.Profile) : PMF (Profile G) :=
  pushforward μ C.actionProfile

/-- The base action-profile law generated by mixed play in the cheap-talk
extension. -/
noncomputable def mixedActionLaw (C : G.CheapTalkExtension) [Fintype ι]
    (τ : Profile C.game.mixedExtension) : PMF (Profile G) :=
  C.actionLaw (pmfPi (A := fun i => C.game.Strategy i) τ)

/-- Lift a base recommendation-dependent action deviation to a cheap-talk
strategy deviation by keeping the message fixed and applying the base deviation
to every contingent action in the plan. -/
def liftActionDeviation (C : G.CheapTalkExtension) (who : ι)
    (dev : G.Strategy who → G.Strategy who)
    (s : C.game.Strategy who) : C.game.Strategy who :=
  (s.1, fun m => dev (s.2 m))

theorem actionProfile_update_liftActionDeviation
    (C : G.CheapTalkExtension) (σ' : C.game.Profile) (who : ι)
    (dev : G.Strategy who → G.Strategy who) :
    C.actionProfile
        (Function.update σ' who
          (C.liftActionDeviation who dev (σ' who))) =
      G.unilateralDeviation who dev (C.actionProfile σ') := by
  classical
  have hmsg :
      C.messageProfile
          (Function.update σ' who
            (C.liftActionDeviation who dev (σ' who))) =
        C.messageProfile σ' := by
    simpa [liftActionDeviation] using
      C.messageProfile_update_sameMessage σ' who
        (fun m => dev ((σ' who).2 m))
  have hmsg' :
      C.messageProfile
          (Function.update σ' who
            ((σ' who).1, fun m => dev ((σ' who).2 m))) =
        C.messageProfile σ' := by
    simpa [liftActionDeviation] using hmsg
  funext i
  by_cases hi : i = who
  · subst hi
    simp only [GameForm.CheapTalkExtension.actionProfile,
      KernelGame.unilateralDeviation, liftActionDeviation]
    rw [hmsg']
    simp
  · simp only [GameForm.CheapTalkExtension.actionProfile,
      KernelGame.unilateralDeviation, liftActionDeviation]
    rw [Function.update_of_ne hi, Function.update_of_ne hi]
    exact congrArg (fun m => (σ' i).2 m) hmsg'

omit [DecidableEq ι] in
/-- Correlated utility of the pushed base action law is the same as correlated
utility in the cheap-talk game before pushing through `actionProfile`. -/
theorem correlatedEu_actionLaw_eq
    (C : G.CheapTalkExtension) [Finite G.Outcome]
    (μ : PMF C.game.Profile) (who : ι) :
    G.correlatedEu (C.actionLaw μ) who = C.game.correlatedEu μ who := by
  rw [G.correlatedEu_eq_expect_eu (μ := C.actionLaw μ) who]
  rw [C.game.correlatedEu_eq_expect_eu (μ := μ) who]
  unfold actionLaw
  calc
    expect (pushforward μ C.actionProfile) (fun σ => G.eu σ who)
        =
      expect μ (fun σ' => G.eu (C.actionProfile σ') who) := by
        exact expect_pushforward_of_bounded_on_source
          (μ := μ) (f := C.actionProfile) (φ := fun σ => G.eu σ who)
          (hbd := fun σ' =>
            G.eu_abs_le_of_bounded who
              (Classical.choose_spec
                (Math.Probability.exists_abs_bound_of_finite
                  (fun ω => G.utility ω who)))
              (C.actionProfile σ'))
    _ = expect μ (fun σ' => C.game.eu σ' who) := by
        rfl

/-- A base unilateral deviation after pushing through `actionProfile` is the
same as first applying the lifted cheap-talk deviation and then pushing through
`actionProfile`. -/
theorem unilateralDeviationDistribution_actionLaw
    (C : G.CheapTalkExtension) (μ : PMF C.game.Profile)
    (who : ι) (dev : G.Strategy who → G.Strategy who) :
    G.unilateralDeviationDistribution (C.actionLaw μ) who dev =
      C.actionLaw
        (C.game.unilateralDeviationDistribution μ who
          (C.liftActionDeviation who dev)) := by
  classical
  unfold actionLaw KernelGame.unilateralDeviationDistribution
    KernelGame.deviationDistribution
  rw [bind_pure_eq_pushforward, bind_pure_eq_pushforward]
  rw [pushforward_comp, pushforward_comp]
  congr 1
  funext σ'
  exact (C.actionProfile_update_liftActionDeviation σ' who dev).symm

private theorem pmf_map_congr_on_support {α β : Type}
    (μ : PMF α) (f g : α → β)
    (hfg : ∀ a, a ∈ μ.support → f a = g a) :
    PMF.map f μ = PMF.map g μ := by
  rw [← PMF.bind_pure_comp f μ, ← PMF.bind_pure_comp g μ]
  exact bind_congr_on_support μ (fun a => PMF.pure (f a))
    (fun a => PMF.pure (g a)) (fun a ha => by simp [hfg a ha])

omit [DecidableEq ι] in
/-- The mixed cheap-talk strategy law disintegrates by public messages and then
playerwise conditional cheap-talk strategies. -/
theorem mixedStrategyLaw_eq_message_bind_conditional
    (C : G.CheapTalkExtension) [Fintype ι]
    [∀ i, Finite (C.Msg i)] [∀ i, Finite (C.game.Strategy i)]
    (τ : Profile C.game.mixedExtension) :
    pmfPi (A := fun i => C.game.Strategy i) τ =
      (C.mixedMessageLaw τ).bind fun m =>
        pmfPi (A := fun i => C.game.Strategy i)
          (C.conditionalCheapTalkProfile τ m) := by
  classical
  symm
  let msg : ∀ i, PMF (C.Msg i) := fun i => C.mixedMessageMarginal τ i
  let cond : C.MessageProfile → ∀ i, PMF (C.game.Strategy i) :=
    fun m => C.conditionalCheapTalkProfile τ m
  have hfactor :
      (fun k => (pmfPi (A := fun i => C.Msg i) msg).bind
          (fun m => cond m k)) = τ := by
    funext k
    have heval := pmfPi_bind_eval
      (A := fun i => C.Msg i) (σ := msg) k
      (fun mi => condOn (τ k) (fun s : C.game.Strategy k => s.1) mi)
    have hcond := bind_pushforward_condOn
      (μ := τ k) (proj := fun s : C.game.Strategy k => s.1)
      (g := fun s : C.game.Strategy k => PMF.pure s)
    change ((pmfPi (A := fun i => C.Msg i) msg).bind
        (fun m => condOn (τ k) (fun s : C.game.Strategy k => s.1) (m k))) = τ k
    rw [heval]
    simpa [msg, cond, mixedMessageMarginal, conditionalCheapTalkProfile,
      conditionalCheapTalkStrategy, PMF.bind_pure] using hcond.symm
  have hdis :=
    pmfPi_bind_pmfPi_of_disjoint_coords
      (A := fun i => C.Msg i) (B := fun i => C.game.Strategy i)
      (σ := msg) (G := cond) (coord := fun i : ι => some i)
      (h_const := by
        intro k hk
        cases hk)
      (h_single := by
        intro k i hki j hji
        cases hki
        intro m a
        have hkj : k ≠ j := Ne.symm hji
        simp [cond, conditionalCheapTalkProfile, conditionalCheapTalkStrategy,
          Function.update, hkj])
      (h_inj := by
        intro k₁ k₂ i h₁ h₂
        cases h₁
        cases h₂
        rfl)
  calc
    ((C.mixedMessageLaw τ).bind fun m =>
        pmfPi (A := fun i => C.game.Strategy i)
          (C.conditionalCheapTalkProfile τ m))
        =
      ((pmfPi (A := fun i => C.Msg i) msg).bind fun m =>
        pmfPi (A := fun i => C.game.Strategy i) (cond m)) := by
          rfl
    _ = pmfPi (A := fun i => C.game.Strategy i)
        (fun k => (pmfPi (A := fun i => C.Msg i) msg).bind
          (fun m => cond m k)) := hdis
    _ = pmfPi (A := fun i => C.game.Strategy i) τ := by
          rw [hfactor]

omit [DecidableEq ι] in
/-- Positive-probability public messages really are the messages of every
profile in the corresponding conditional product support. -/
theorem messageProfile_eq_of_conditionalCheapTalkProfile_ne_zero
    (C : G.CheapTalkExtension) [Fintype ι]
    (τ : Profile C.game.mixedExtension) {m : C.MessageProfile}
    {σ' : C.game.Profile}
    (hm : C.mixedMessageLaw τ m ≠ 0)
    (hσ : pmfPi (A := fun i => C.game.Strategy i)
        (C.conditionalCheapTalkProfile τ m) σ' ≠ 0) :
    C.messageProfile σ' = m := by
  classical
  funext i
  have hmprod :
      (∏ j, C.mixedMessageMarginal τ j (m j)) ≠ 0 := by
    simpa [mixedMessageLaw, pmfPi_apply] using hm
  have hmi : C.mixedMessageMarginal τ i (m i) ≠ 0 :=
    (Finset.prod_ne_zero_iff.mp hmprod) i (Finset.mem_univ i)
  have hσprod :
      (∏ j, C.conditionalCheapTalkStrategy τ m j (σ' j)) ≠ 0 := by
    simpa [pmfPi_apply, conditionalCheapTalkProfile] using hσ
  have hcond : C.conditionalCheapTalkStrategy τ m i (σ' i) ≠ 0 :=
    (Finset.prod_ne_zero_iff.mp hσprod) i (Finset.mem_univ i)
  by_contra hneq
  have hfst : ¬ (σ' i).1 = m i := by
    simpa [GameForm.CheapTalkExtension.messageProfile] using hneq
  have hz : C.conditionalCheapTalkStrategy τ m i (σ' i) = 0 := by
    unfold conditionalCheapTalkStrategy
    rw [condOn_apply
      (μ := τ i) (proj := fun s : C.game.Strategy i => s.1)
      (b := m i) (a := σ' i)
      (hb := by simpa [mixedMessageMarginal] using hmi)]
    simp [hfst]
  exact hcond hz

omit [DecidableEq ι] in
/-- Conditional on a positive-probability public message, mapping conditional
cheap-talk strategies through `actionProfile` is the product of the conditional
base mixed actions selected by that message. -/
theorem actionProfile_map_conditional_eq_pmfPi_publicPlay
    (C : G.CheapTalkExtension) [Fintype ι]
    (τ : Profile C.game.mixedExtension) {m : C.MessageProfile}
    (hm : C.mixedMessageLaw τ m ≠ 0) :
    pushforward
        (pmfPi (A := fun i => C.game.Strategy i)
          (C.conditionalCheapTalkProfile τ m))
        C.actionProfile =
      pmfPi (A := fun i => G.Strategy i) (C.publicPlay τ m) := by
  classical
  calc
    pushforward
        (pmfPi (A := fun i => C.game.Strategy i)
          (C.conditionalCheapTalkProfile τ m))
        C.actionProfile
        =
      pushforward
        (pmfPi (A := fun i => C.game.Strategy i)
          (C.conditionalCheapTalkProfile τ m))
        (fun σ' : C.game.Profile => fun i => (σ' i).2 m) := by
          unfold pushforward
          apply pmf_map_congr_on_support
          intro σ' hσ
          have hσne :
              pmfPi (A := fun i => C.game.Strategy i)
                (C.conditionalCheapTalkProfile τ m) σ' ≠ 0 := by
            simpa [PMF.mem_support_iff] using hσ
          have hmsg :=
            C.messageProfile_eq_of_conditionalCheapTalkProfile_ne_zero
              τ hm hσne
          funext i
          simp [GameForm.CheapTalkExtension.actionProfile, hmsg]
    _ = pmfPi (A := fun i => G.Strategy i) (C.publicPlay τ m) := by
          change PMF.map (fun σ' : C.game.Profile => fun i => (σ' i).2 m)
              (pmfPi (A := fun i => C.game.Strategy i) (C.conditionalCheapTalkProfile τ m)) =
            pmfPi (A := fun i => G.Strategy i)
              (fun i => PMF.map (fun s : C.game.Strategy i => s.2 m)
                (C.conditionalCheapTalkProfile τ m i))
          exact pmfPi_push_coordwise
            (A := fun i => C.game.Strategy i)
            (B := fun i => G.Strategy i)
            (μ := C.conditionalCheapTalkProfile τ m)
            (g := fun i (s : C.game.Strategy i) => s.2 m)

omit [DecidableEq ι] in
/-- **Mixed cheap-talk play induces a public-randomness representation.**

The base action-profile law generated by a mixed profile of the observable
cheap-talk extension is exactly the public-signal mixture generated by:

* the public signal `mixedMessageLaw τ`, and
* the conditional base mixed profile `publicPlay τ m` after each signal `m`.
-/
theorem mixedActionLaw_eq_publicCorrelatedLaw
    (C : G.CheapTalkExtension) [Fintype ι]
    [∀ i, Finite (C.Msg i)] [∀ i, Finite (C.game.Strategy i)]
    (τ : Profile C.game.mixedExtension) :
    C.mixedActionLaw τ =
      G.publicCorrelatedLaw (C.mixedMessageLaw τ) (C.publicPlay τ) := by
  classical
  unfold mixedActionLaw actionLaw
  rw [C.mixedStrategyLaw_eq_message_bind_conditional τ]
  unfold pushforward
  rw [PMF.map_bind]
  unfold publicCorrelatedLaw
  exact bind_congr_of_ne_zero (C.mixedMessageLaw τ)
    (fun m => PMF.map C.actionProfile
      (pmfPi (A := fun i => C.game.Strategy i)
        (C.conditionalCheapTalkProfile τ m)))
    (fun m => pmfPi (A := fun i => G.Strategy i) (C.publicPlay τ m))
    (fun m hm => by
      exact C.actionProfile_map_conditional_eq_pmfPi_publicPlay τ hm)

/-- The induced public regime is public-signal Nash: after every
positive-probability public message, the selected base mixed profile is Nash. -/
def InducesPublicSignalNash (C : G.CheapTalkExtension) [Fintype ι]
    (τ : Profile C.game.mixedExtension) : Prop :=
  G.PublicSignalNash (C.mixedMessageLaw τ) (C.publicPlay τ)

/-- Every mixed Nash equilibrium of the cheap-talk extension induces a
correlated equilibrium over base action profiles.

This does not assert that every positive-probability public message selects a
base mixed Nash profile.  It uses the weaker, always available fact that any
base recommendation-dependent action deviation can be lifted to a cheap-talk
deviation that keeps the message fixed and applies the base deviation to the
contingent plan. -/
theorem mixedNash_mixedActionLaw_isCorrelatedEq
    (C : G.CheapTalkExtension) [Fintype ι] [Finite G.Outcome]
    (τ : Profile C.game.mixedExtension)
    (hN : C.game.mixedExtension.IsNash τ) :
    G.IsCorrelatedEq (C.mixedActionLaw τ) := by
  classical
  intro who dev
  have hcheap : C.game.IsCorrelatedEq
      (pmfPi (A := fun i => C.game.Strategy i) τ) :=
    C.game.mixed_nash_isCorrelatedEq τ hN
  have hcheapDev := hcheap who (C.liftActionDeviation who dev)
  calc
    G.correlatedEu (C.mixedActionLaw τ) who
        = C.game.correlatedEu
            (pmfPi (A := fun i => C.game.Strategy i) τ) who := by
            simpa [mixedActionLaw] using
              C.correlatedEu_actionLaw_eq
                (μ := pmfPi (A := fun i => C.game.Strategy i) τ) who
    _ ≥ C.game.correlatedEu
          (C.game.unilateralDeviationDistribution
            (pmfPi (A := fun i => C.game.Strategy i) τ) who
            (C.liftActionDeviation who dev)) who := hcheapDev
    _ = G.correlatedEu
          (C.actionLaw
            (C.game.unilateralDeviationDistribution
              (pmfPi (A := fun i => C.game.Strategy i) τ) who
              (C.liftActionDeviation who dev))) who := by
            exact (C.correlatedEu_actionLaw_eq
              (μ := C.game.unilateralDeviationDistribution
                (pmfPi (A := fun i => C.game.Strategy i) τ) who
                (C.liftActionDeviation who dev)) who).symm
    _ = G.correlatedEu
          (G.unilateralDeviationDistribution (C.mixedActionLaw τ) who dev) who := by
            have hdist := C.unilateralDeviationDistribution_actionLaw
              (μ := pmfPi (A := fun i => C.game.Strategy i) τ)
              (who := who) (dev := dev)
            simpa [mixedActionLaw] using
              congrArg (fun μ => G.correlatedEu μ who) hdist.symm

/-- Coarse-correlated consequence of
`mixedNash_mixedActionLaw_isCorrelatedEq`. -/
theorem mixedNash_mixedActionLaw_isCoarseCorrelatedEq
    (C : G.CheapTalkExtension) [Fintype ι] [Finite G.Outcome]
    (τ : Profile C.game.mixedExtension)
    (hN : C.game.mixedExtension.IsNash τ) :
    G.IsCoarseCorrelatedEq (C.mixedActionLaw τ) :=
  (C.mixedNash_mixedActionLaw_isCorrelatedEq τ hN).toCoarseCorrelatedEq

/-- If the public regime induced by cheap talk is public-signal Nash, then the
cheap-talk action law is a correlated equilibrium of the base game. -/
theorem InducesPublicSignalNash.mixedActionLaw_isCorrelatedEq
    (C : G.CheapTalkExtension) [Fintype ι] [Finite G.Outcome]
    [∀ i, Finite (C.Msg i)] [∀ i, Finite (C.game.Strategy i)]
    {τ : Profile C.game.mixedExtension}
    (hpub : C.InducesPublicSignalNash τ) :
    G.IsCorrelatedEq (C.mixedActionLaw τ) := by
  rw [C.mixedActionLaw_eq_publicCorrelatedLaw τ]
  exact hpub.isCorrelatedEq

/-- The same induced action law is therefore a coarse correlated equilibrium. -/
theorem InducesPublicSignalNash.mixedActionLaw_isCoarseCorrelatedEq
    (C : G.CheapTalkExtension) [Fintype ι] [Finite G.Outcome]
    [∀ i, Finite (C.Msg i)] [∀ i, Finite (C.game.Strategy i)]
    {τ : Profile C.game.mixedExtension}
    (hpub : C.InducesPublicSignalNash τ) :
    G.IsCoarseCorrelatedEq (C.mixedActionLaw τ) :=
  (hpub.mixedActionLaw_isCorrelatedEq C).toCoarseCorrelatedEq

/-- The correlated payoff vector of the induced cheap-talk action law lies in
the PMF-supported convex hull of mixed-Nash payoff vectors. -/
theorem InducesPublicSignalNash.mixedActionLaw_payoff_isMixedNashPayoffMixture
    (C : G.CheapTalkExtension) [Fintype ι] [Finite G.Outcome]
    [∀ i, Finite (C.Msg i)] [∀ i, Finite (C.game.Strategy i)]
    {τ : Profile C.game.mixedExtension}
    (hpub : C.InducesPublicSignalNash τ) :
    G.IsMixedNashPayoffMixture
      (fun i => G.correlatedEu (C.mixedActionLaw τ) i) := by
  have hmix := hpub.correlatedPayoff_isMixedNashPayoffMixture
  convert hmix using 1
  funext i
  rw [C.mixedActionLaw_eq_publicCorrelatedLaw τ]

omit [DecidableEq ι] in
/-- Expected utility in the mixed cheap-talk extension is the correlated
expected utility of the induced base action-profile law. -/
theorem mixedExtension_eu_eq_correlatedEu_mixedActionLaw_of_bounded
    (C : G.CheapTalkExtension) [Fintype ι]
    (τ : Profile C.game.mixedExtension) (who : ι)
    {K : ℝ} (hbd : ∀ ω, |G.utility ω who| ≤ K) :
    C.game.mixedExtension.eu τ who =
      G.correlatedEu (C.mixedActionLaw τ) who := by
  rw [C.game.mixedExtension_eu_of_bounded τ who hbd]
  rw [G.correlatedEu_eq_expect_eu_of_bounded
    (μ := C.mixedActionLaw τ) who hbd]
  unfold mixedActionLaw
  calc
    expect (pmfPi (A := fun i => C.game.Strategy i) τ)
        (fun s => C.game.eu s who)
        =
      expect (pmfPi (A := fun i => C.game.Strategy i) τ)
        (fun s => G.eu (C.actionProfile s) who) := by
          rfl
    _ = expect
        (pushforward (pmfPi (A := fun i => C.game.Strategy i) τ)
          C.actionProfile)
        (fun σ => G.eu σ who) := by
          exact (expect_pushforward_of_bounded_on_source
            (μ := pmfPi (A := fun i => C.game.Strategy i) τ)
            (f := C.actionProfile)
            (φ := fun σ => G.eu σ who)
            (hbd := fun σ' =>
              G.eu_abs_le_of_bounded who hbd (C.actionProfile σ'))).symm

omit [DecidableEq ι] in
/-- Finite-outcome wrapper for
`mixedExtension_eu_eq_correlatedEu_mixedActionLaw_of_bounded`. -/
theorem mixedExtension_eu_eq_correlatedEu_mixedActionLaw
    (C : G.CheapTalkExtension) [Fintype ι] [Finite G.Outcome]
    (τ : Profile C.game.mixedExtension) (who : ι) :
    C.game.mixedExtension.eu τ who =
      G.correlatedEu (C.mixedActionLaw τ) who := by
  classical
  obtain ⟨K, hbd⟩ :=
    Math.Probability.exists_abs_bound_of_finite (fun ω => G.utility ω who)
  exact C.mixedExtension_eu_eq_correlatedEu_mixedActionLaw_of_bounded
    τ who hbd

end CheapTalkExtension

end KernelGame

end GameTheory
